#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE BOUNDED PROJECT-SCOPED READ HANDOFF ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PROJECT_BOUND_HANDOFF"
echo "CLASSIFICATION_COMMIT=03c0b91b"
echo "PACKAGE_HANDOFF_CONTRACT_REMAINS_CLOSED=YES"

echo
echo "=== AUTHORIZED IMPLEMENTATION UNIT ==="
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_UNIT=SERVER_SIDE_PROJECT_SCOPED_OPERATIONAL_AUTHORITY_TO_MISSION_READ_HANDOFF"
echo "AUTHORIZED_ENTRY_IDENTITY=project_id"
echo "AUTHORIZED_AUTHORITY_SOURCE=operational_package_authority"
echo "AUTHORIZED_MISSION_READ_IDENTITY=project_id+package_id+package_version"

echo
echo "=== AUTHORIZED SURFACES ==="
echo "SURFACE_1=db/mission-read-repository.ts"
echo "SURFACE_2=routes/api-mission-read.ts"
echo "SURFACE_3=TARGETED_SERVER_SIDE_TESTS"
echo "db/operational-package-authority.ts_CHANGE_AUTHORIZED=NO_UNLESS_REQUIRED_TO_FIX_A_CONFIRMED_READ_CONTRACT_DEFECT"
echo "SCHEMA_CHANGE_AUTHORIZED=NO"
echo "MIGRATION_CHANGE_AUTHORIZED=NO"

echo
echo "=== REQUIRED SERVER-SIDE FLOW ==="
echo "STEP_1=RECEIVE_project_id"
echo "STEP_2=RESOLVE_OPERATIONAL_PACKAGE_AUTHORITY_BY_project_id"
echo "STEP_3=OBTAIN_EXACT_project_id+package_id+package_version"
echo "STEP_4=LOAD_MISSION_BY_EXACT_RESOLVED_IDENTITY"
echo "STEP_5=ASSEMBLE_EXISTING_MISSION_READ_MODEL"
echo "CALLER_PACKAGE_ID_AS_SELECTION_AUTHORITY=NO"
echo "NEWEST_PACKAGE_INFERENCE=NO"
echo "SUCCESSOR_VERSION_INFERENCE=NO"
echo "DELEGATION_AS_SELECTION_AUTHORITY=NO"

echo
echo "=== MISSION READ REPOSITORY CONTRACT ==="
echo "MISSION_READ_REPOSITORY_INPUT=EXACT_project_id+package_id+package_version"
echo "MISSION_READ_REPOSITORY_MUST_QUERY_EXACT_IDENTITY=YES"
echo "MISSION_READ_REPOSITORY_MUST_PRESERVE_SELECTED_VERSION=YES"
echo "MISSION_READ_REPOSITORY_OWNS_SELECTION_AUTHORITY=NO"
echo "MISSION_READ_REPOSITORY_MUTATES_OPERATIONAL_AUTHORITY=NO"

echo
echo "=== ROUTE CONTRACT ==="
echo "PROJECT_SCOPED_HTTP_BOUNDARY=routes/api-mission-read.ts"
echo "ROUTE_INPUT=project_id"
echo "ROUTE_RESOLVES_OPERATIONAL_AUTHORITY=YES"
echo "NO_OPERATIONAL_AUTHORITY_FOR_PROJECT=NO_ACTIVE_MISSION"
echo "MISSING_EXACT_MISSION_PROJECTION=FAIL_CLOSED"
echo "IDENTITY_MISMATCH=FAIL_CLOSED"
echo "CALLER_PACKAGE_OVERRIDE=NOT_ALLOWED"

echo
echo "=== EXPLICITLY OUT OF SCOPE ==="
echo "MISSION_CONTROL_UI_CHANGE_AUTHORIZED=NO"
echo "MISSION_CONTROL_PROVIDER_CHANGE_AUTHORIZED=NO"
echo "MISSION_CONTROL_WORKSPACE_CHANGE_AUTHORIZED=NO"
echo "CLIENT_OPERATIONAL_SELECTION_CHANGE_AUTHORIZED=NO"
echo "MISSION_CONTROL_INTAKE_AUTHORIZED=NO"
echo "CANONICAL_PACKAGE_MUTATION_AUTHORIZED=NO"
echo "MISSION_PACKAGE_PROJECTION_MUTATION_AUTHORIZED=NO"
echo "OPERATIONAL_PACKAGE_AUTHORITY_MUTATION_AUTHORIZED=NO"
echo "DELEGATION_CHANGE_AUTHORIZED=NO"
echo "VALIDATION_CHANGE_AUTHORIZED=NO"
echo "ROUTING_CHANGE_AUTHORIZED=NO"
echo "ASSIGNMENT_CHANGE_AUTHORIZED=NO"
echo "EXECUTION_CHANGE_AUTHORIZED=NO"

echo
echo "=== REQUIRED VALIDATION ==="
echo "TYPECHECK_REQUIRED=YES"
echo "PROJECT_WITH_OPERATIONAL_BINDING_READS_EXACT_SELECTED_PACKAGE=YES"
echo "EXACT_SELECTED_PACKAGE_VERSION_PRESERVED=YES"
echo "UNSELECTED_PROJECT_RETURNS_NO_ACTIVE_MISSION=YES"
echo "MISSING_SELECTED_PROJECTION_FAILS_CLOSED=YES"
echo "WRONG_PROJECT_IDENTITY_FAILS_CLOSED=YES"
echo "WRONG_PACKAGE_VERSION_FAILS_CLOSED=YES"
echo "NEWER_CANONICAL_VERSION_DOES_NOT_AUTO_ACTIVATE=YES"
echo "OPERATIONAL_AUTHORITY_STATE_UNCHANGED=YES"
echo "DELEGATION_STATE_UNCHANGED=YES"
echo "EXECUTION_STATE_UNCHANGED=YES"

echo
echo "=== BUILD PROTOCOL ==="
echo "MAX_FAILED_BUILDS_PER_HYPOTHESIS=3"
echo "SPECULATIVE_LAYERING_ALLOWED=NO"
echo "REVERT_IF_FAILURE_DOES_NOT_POINT_TO_CONFIDENT_NEXT_STEP=YES"
echo "STABLE_BASE=03c0b91b"

echo
echo "=== CORRIDOR STATE ==="
echo "PROJECT_BOUND_HANDOFF_READ_HANDOFF_IMPLEMENTATION_AUTHORIZED=YES"
echo "PROJECT_BOUND_HANDOFF_READ_HANDOFF_IMPLEMENTATION_STARTED=NO"
echo "MISSION_CONTROL_INTAKE_STARTED=NO"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=IMPLEMENT_ONLY_THE_BOUNDED_SERVER_SIDE_PROJECT_SCOPED_READ_HANDOFF_AND_TARGETED_VALIDATION"
