#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE DECISIONS LIST COMPACT TITLE IMPLEMENTATION ==="
echo "EXPECTED_HEAD_PREFIX=e8aa73534"
echo "RECOVERY_POINT=DR_20260826_171804"
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != e8aa73534* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED DESIGN ==="
echo "DESIGN=DECISIONS_LIST_COMPACT_TITLE_RULE"
echo "TITLE_SOURCE=expected_outcome_WITH_interpreted_objective_FALLBACK"
echo "PRESENTATION_ONLY=YES"
echo "MAX_DISPLAY_CHARACTERS=64"
echo "WHOLE_WORD_BOUNDARY_PREFERRED=YES"
echo "ELLIPSIS=YES"
echo "HEADING_MAX_LINES=2"
echo "DETAIL_EXPECTED_OUTCOME_REMAINS_FULL=YES"
echo "SEMANTIC_SUMMARIZATION=NO"
echo "MODEL_CALL=NO"
echo "PERSISTED_DATA_CHANGE=NO"

echo
echo "=== IMPLEMENTATION AUTHORIZATION ==="
echo "AUTHORIZED_UNIT=DECISIONS_LIST_PRESENTATION_ONLY_COMPACT_TITLE"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_COMPONENT=client/src/approvals/ApprovalsWorkspace.tsx"
echo "AUTHORIZED_STYLE_SURFACE=client/src/approvals/approvals-workspace.css"
echo "AUTHORIZED_TEST_SURFACE=FOCUSED_DECISION_LIST_TITLE_PRESENTATION_TESTS"
echo "TITLE_HELPER=deriveDecisionListTitle"
echo "TITLE_HELPER_SCOPE=LOCAL_PRESENTATION_ONLY"

echo
echo "=== REQUIRED BEHAVIOR ==="
echo "SHORT_TITLE_REMAINS_UNCHANGED_AFTER_WHITESPACE_NORMALIZATION=REQUIRED"
echo "LONG_TITLE_SHORTENED_AT_OR_BEFORE_64_CHARACTERS=REQUIRED"
echo "WHOLE_WORD_BOUNDARY_PREFERRED=REQUIRED"
echo "ELLIPSIS_ON_SHORTENED_TITLE=REQUIRED"
echo "DECISION_LIST_HEADING_ONLY_USES_COMPACT_TITLE=REQUIRED"
echo "DETAIL_EXPECTED_OUTCOME_REMAINS_FULL=REQUIRED"
echo "INTERPRETED_OBJECTIVE_SUMMARY_REMAINS_UNCHANGED=REQUIRED"
echo "UNDERLYING_REQUEST_OBJECT_REMAINS_UNCHANGED=REQUIRED"
echo "TWO_LINE_VISUAL_CONTAINMENT=REQUIRED"

echo
echo "=== REQUIRED VALIDATION ==="
echo "FOCUSED_COMPACT_TITLE_TESTS=REQUIRED"
echo "APPROVALS_PRESENTATION_REGRESSION=REQUIRED"
echo "TYPECHECK=REQUIRED"
echo "BUILD=REQUIRED"
echo "DIFF_CHECK=REQUIRED"

echo
echo "=== EXPLICIT NON-AUTHORIZATION ==="
echo "BACKEND_CHANGE=NO"
echo "DATABASE_CHANGE=NO"
echo "API_CHANGE=NO"
echo "PACKAGE_SEMANTICS_CHANGE=NO"
echo "MATILDA_PROMPT_CHANGE=NO"
echo "MATILDA_GENERATION_CHANGE=NO"
echo "NEW_TITLE_FIELD=NO"
echo "MODEL_AUTHORED_TITLE=NO"
echo "APPROVAL_AUTHORITY_CHANGE=NO"
echo "SEMANTIC_MUTATION=NO"
echo "LIVE_OLLAMA_INVOCATION=NO"

echo
echo "NEXT_ACTION=IMPLEMENT_PRESENTATION_ONLY_COMPACT_TITLE_RULE_AND_REQUIRED_TESTS"

git diff --check
git add authorize-decisions-list-compact-title-implementation.sh
git commit -m "Authorize decisions list compact title implementation"
git push
