#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE LIVE DELEGATION MIGRATION ==="
echo "IMPLEMENTATION_COMMIT=5b9082f2"
echo "LINEAGE_CLASSIFICATION_COMMIT=74f332ca"
echo "LIVE_DATA_COMPATIBILITY=BOUNDED_COMPATIBLE"
echo "KNOWN_DOWNSTREAM_LEGACY_ROOT_DEFECT=VERIFIED_UNCHANGED_AND_SEPARATE"
echo "LIVE_MIGRATION_TECHNICAL_COMPATIBILITY=ESTABLISHED"
echo "LIVE_MIGRATION_AUTHORIZED=YES"
echo "LIVE_MIGRATION_STARTED=NO"
echo "CORRIDOR_CLOSED=NO"
echo "NEXT_ACTION=APPLY_ONLY_0010_PROJECT_SCOPED_DELEGATION_REFERENCE_WITH_PRE_POST_VALIDATION"
