#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
DELEGATION_ID="8782c8fa-7c82-4ca8-b7cb-3fce7d072b0c"
PACKAGE_ID="pkg-68dfc4bc-791d-4156-b32a-e51e458b3160"
PACKAGE_VERSION="1"

git fetch origin "$BRANCH"
test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse HEAD)" = "$(git rev-parse "origin/$BRANCH")"
test -z "$(git status --porcelain)"

printf '\n====================================================\n'
printf ' LIVE GOVERNANCE VALIDATION — AUTHORIZED\n'
printf '====================================================\n\n'

echo "AUTHORIZED_BY=marcela"
echo "AUTHORIZED_ACTION=ONE_LIVE_GOVERNANCE_VALIDATION"
echo "AUTHORIZED_ATTEMPT_COUNT=1"
echo "DELEGATION_ID=$DELEGATION_ID"
echo "PACKAGE_ID=$PACKAGE_ID"
echo "PACKAGE_VERSION=$PACKAGE_VERSION"

printf '\n=== AUTHORIZED EFFECT ===\n'
echo "ONE_LIVE_VALIDATION_RESULT_CREATION=YES"
echo "LIVE_GOVERNANCE_DB_MUTATION_FOR_VALIDATION=YES"
echo "EXACT_AUTHORIZED_DELEGATION_REQUIRED=YES"
echo "EXPLICIT_OPERATOR_VALIDATION=YES"

printf '\n=== AUTHORITY REMAINS EXCLUDED ===\n'
echo "AUTOMATIC_VALIDATION=NO"
echo "AUTOMATIC_ENVELOPE_GATE_CREATION=NO"
echo "AUTOMATIC_ENVELOPE_CREATION=NO"
echo "LIFECYCLE_TRANSITION_AUTHORITY=NO"
echo "ROUTING_AUTHORITY=NO"
echo "ASSIGNMENT_AUTHORITY=NO"
echo "SCHEDULING_AUTHORITY=NO"
echo "WORKER_CLAIM_AUTHORITY=NO"
echo "ORCHESTRATION_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "DOWNSTREAM_EXECUTION_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"
echo "GENERIC_SHELL_AUTHORITY=NO"
echo "SELF_AUTHORIZATION=NO"

printf '\n=== FAILURE CONTAINMENT ===\n'
echo "SECOND_LIVE_VALIDATION_WITHOUT_NEW_AUTHORIZATION=PROHIBITED"
echo "AUTOMATIC_SUCCESSOR_MUTATION=NO"
echo "AUTOMATIC_ADVANCE=NO"

printf '\nONE_LIVE_GOVERNANCE_VALIDATION_AUTHORIZATION=RECORDED\n'
