#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE SECOND NARROW GOVERNANCE RUNTIME IMPORT FIX ==="
echo "BASELINE_COMMIT=c835e408"
echo "IMPLEMENTATION_AUTHORIZED=YES_NARROWLY"
echo "PRODUCTION_CHANGE=NO"
echo "FIRST_FIX_ROLLBACK_REQUIRED=NO"
echo "ESTABLISHED_SECOND_FAILURE=TS_NODE_SOURCE_IMPORT_EXTENSION_MISMATCH"
echo "TARGET_SOURCE_EXISTS=db/governance-runtime.ts"
echo "TARGET_JS_SOURCE_ABSENT=YES"
echo "COMPILED_TARGET_EXISTS=dist/db/governance-runtime.js"
echo "AUTHORIZED_SOURCE_FILE=server/delegation/production-delegation-consumer.ts"
echo "AUTHORIZED_CHANGE=REMOVE_DOT_JS_FROM_../../db/governance-runtime_IMPORT"
echo "OTHER_governance-runtime_IMPORTS_AUTHORIZED=NO"
echo "OTHER_SOURCE_CHANGES_AUTHORIZED=NO"
echo "ROLLBACK_BOUNDARY=REVERT_SINGLE_SECOND_IMPORT_FIX_COMMIT_IF_SERVER_BOOT_DOES_NOT_ADVANCE"
echo "NEXT_ACTION=IMPLEMENT_ONLY_THE_CONFIRMED_SECOND_IMPORT_FIX_AND_REVALIDATE_SERVER_BOOT"
