#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE VALIDATION-ONLY PACKAGE SEMANTICS OBSERVER ==="
echo "EXPECTED_HEAD_PREFIX=570fcda95"
echo "RECOVERY_POINT=DR_20260826_111719"
echo "SCOPE=VALIDATION_ONLY_PACKAGE_SEMANTICS_OBSERVER"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "PRODUCTION_BEHAVIOR_CHANGE=NO"
echo "RESULT_ACCEPTANCE_CHANGE=NO"
echo "FAIL_CLOSED_SUPPORT_VALIDATION_CHANGE=NO"
echo "SECOND_OLLAMA_INVOCATION=NO"
echo "PRODUCTION_SAMPLING_POLICY_CHANGE=NO"
echo "AUTHORITY_MODEL_CHANGE=NO"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 570fcda95* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== AUTHORIZED OBSERVER CONTRACT ==="
echo "OBSERVER_PURPOSE=VALIDATION_ONLY_VISIBILITY_INTO_PARSED_AND_VALIDATED_packageSemantics"
echo "OBSERVER_LOCATION=AFTER_STRUCTURED_RESPONSE_PARSE_AND_PACKAGE_SEMANTICS_VALIDATION_BEFORE_SUPPORT_PROVENANCE_VALIDATION"
echo "OBSERVER_MAY_SEE_NULL=YES"
echo "OBSERVER_MAY_SEE_VALIDATED_NON_NULL_ARTIFACT=YES"
echo "OBSERVER_MUST_NOT_BYPASS_OR_SUPPRESS_LATER_VALIDATION_FAILURE=YES"
echo "OBSERVER_MUST_NOT_MUTATE_MODEL_OUTPUT=YES"
echo "OBSERVER_MUST_NOT_CHANGE_PUBLIC_RESULT=YES"
echo "OBSERVER_MUST_NOT_BE_USED_BY_NORMAL_PRODUCTION_WORKFLOW=YES"

echo
echo "=== AUTHORIZED IMPLEMENTATION SURFACE ==="
echo "PRIMARY=scripts/utils/ollamaChat.ts"
echo "TEST=FOCUSED_OBSERVER_TEST_ONLY"
echo "WORKFLOW_CHANGE=NO"
echo "IEL_CHANGE=NO"
echo "LIVING_DRAFT_CHANGE=NO"
echo "APPROVAL_UI_CHANGE=NO"

echo
echo "=== REQUIRED VALIDATION ==="
echo "TEST_1=OBSERVER_RECEIVES_VALIDATED_PACKAGE_SEMANTICS_BEFORE_SUPPORT_PROVENANCE_REJECTION"
echo "TEST_2=INVALID_PACKAGE_SEMANTICS_FAILS_BEFORE_OBSERVER"
echo "TEST_3=SUPPORT_PROVENANCE_REJECTION_STILL_OCCURS_AFTER_OBSERVER"
echo "TEST_4=NORMAL_CALL_WITHOUT_OBSERVER_UNCHANGED"
echo "TEST_5=PACKAGE_SEMANTICS_CONTRACT_SUITE_PASSES"
echo "TEST_6=LIFECYCLE_REGRESSION_SUITE_PASSES"
echo "TEST_7=TYPECHECK_AND_BUILD_PASS"
echo "TEST_8=DIFF_CHECK_PASS"

echo
echo "=== NEXT STEP ==="
echo "NEXT_ACTION=IMPLEMENT_NARROW_VALIDATION_ONLY_OBSERVER_AND_THEN_RUN_BOUNDED_SEEDED_AUTHORSHIP_REVALIDATION"

git diff --check

git add authorize-validation-only-package-semantics-observer.sh
git commit -m "Authorize validation-only package semantics observer"
git push
