#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="395a4fdb1"

git fetch origin "$BRANCH"
test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$EXPECTED_HEAD"

printf '\n====================================================\n'
printf ' ENVELOPE CREATION — AUTHORIZATION\n'
printf '====================================================\n\n'

echo "PREDECESSOR_BOUNDARY=EXPLICIT_OPERATOR_ENVELOPE_GATE_ACTION"
echo "PREDECESSOR_STATUS=CLOSED"
echo "SUCCESSOR_BOUNDARY=ENVELOPE_CREATION"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_BY=marcela"
echo "AUTHORIZED_SCOPE=BOUNDED_ENVELOPE_CREATION_IMPLEMENTATION"

printf '\n=== AUTHORIZED IMPLEMENTATION BOUNDARY ===\n'
echo "IMPLEMENT_ENVELOPE_CREATION_PATH=YES"
echo "LIVE_ENVELOPE_CREATION=NO"
echo "LIVE_GOVERNANCE_DATA_MUTATION=NO"
echo "AUTOMATIC_GATE_TO_ENVELOPE_TRANSITION=NO"
echo "AUTOMATIC_EXECUTION_TRANSITION=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "DOWNSTREAM_EXECUTION_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"

printf '\n=== PRESERVED INVARIANTS ===\n'
echo "APPROVAL_NE_DELEGATION=YES"
echo "DELEGATION_NE_VALIDATION=YES"
echo "VALIDATION_NE_ENVELOPE_GATE=YES"
echo "ENVELOPE_GATE_NE_ENVELOPE=YES"
echo "ENVELOPE_NE_EXECUTION=YES"
echo "EXACT_PACKAGE_VERSION_LINEAGE_REQUIRED=YES"
echo "EXACT_DELEGATION_LINEAGE_REQUIRED=YES"
echo "EXACT_VALIDATION_LINEAGE_REQUIRED=YES"
echo "EXACT_ENVELOPE_GATE_LINEAGE_REQUIRED=YES"
echo "FAIL_CLOSED_ELIGIBILITY_REQUIRED=YES"
echo "NO_GENERIC_SHELL=YES"
echo "NO_SELF_AUTHORIZATION=YES"

printf '\nENVELOPE_CREATION_IMPLEMENTATION_AUTHORIZED=YES\n'
