#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE PACKAGE SEMANTICS IMPLEMENTATION UNIT ==="
echo "BASELINE_COMMIT=2e6bf09a"
echo "RECOVERY_POINT=DR_20260826_092915"
echo "IMPLEMENTATION_AUTHORIZED=YES_NARROWLY"
echo "AUTHORIZED_SCOPE=MATILDA_PACKAGE_SEMANTICS_END_TO_END_TRANSPORT"
echo "PACKAGES_TAB_REMOVAL_AUTHORIZED=NO"
echo "AUTHORITY_MODEL_CHANGE_AUTHORIZED=NO"
echo "SECOND_OLLAMA_INVOCATION_AUTHORIZED=NO"
echo "HEURISTIC_EXTRACTION_AUTHORIZED=NO"

echo
echo "=== AUTHORIZED MODEL CONTRACT ==="
echo "ADD_TOP_LEVEL_FIELD=packageSemantics"
echo "PACKAGE_SEMANTICS_NULLABLE=YES"
echo "FIELDS=expectedOutcome,proposedWork,proposedArtifacts,inScope,outOfScope,constraints,unresolvedQuestions"
echo "FIELD_VALUES=trimmed_nonempty_string_or_null"
echo "MALFORMED_PRESENT_ARTIFACT=FAIL_CLOSED"
echo "UNKNOWN_FIELDS=FAIL_CLOSED"
echo "PACKAGE_SEMANTICS_AUTHOR=MATILDA"
echo "PACKAGE_SEMANTICS_AUTHORITY=INTERPRETIVE_NON_AUTHORITATIVE"

echo
echo "=== AUTHORIZED TRANSPORT ==="
echo "SOURCE=ollamaResult.packageSemantics"
echo "WRITE_OWNER=EXISTING_WORKFLOW_IEL_ENTRY"
echo "IEL_COLUMN=package_semantics_json"
echo "HISTORICAL_ROWS=SQL_NULL_NO_BACKFILL"
echo "READ_RECONSTRUCTION=JSON_PARSE_PLUS_SHARED_FAIL_CLOSED_VALIDATOR"
echo "ONE_WORKFLOW_ONE_IEL_ENTRY=PRESERVED"
echo "ONE_USER_MESSAGE_ONE_OLLAMA_INVOCATION=PRESERVED"

echo
echo "=== AUTHORIZED SYNTHESIS ==="
echo "SELECTION=NEWEST_ELIGIBLE_NON_NULL_packageSemantics_WITHIN_EXACT_DRAFT_EVIDENCE_SET"
echo "PROJECT_CONVERSATION_ISOLATION=PRESERVE"
echo "FIELD_BY_FIELD_CROSS_TURN_MERGE=NO"
echo "OLDER_NULL_FIELD_BACKFILL=NO"
echo "CURRENT_INTERPRETATION_SOURCE=EXISTING_matilda_observation_AGGREGATION"
echo "STRUCTURED_FIELDS_SOURCE=SELECTED_ATOMIC_packageSemantics"
echo "NO_VALID_PACKAGE_SEMANTICS=STRUCTURED_FIELDS_REMAIN_NULL"
echo "STATIC_GENERIC_STRUCTURED_DEFAULTS=REMOVE"

echo
echo "=== LEGACY COMPATIBILITY ==="
echo "IEL_unresolved_questions_COLUMN=PRESERVE"
echo "WORKFLOW_unresolved_questions_WRITE=REMAIN_NULL"
echo "PACKAGE_SEMANTICS_unresolvedQuestions=SINGLE_ACTIVE_STRUCTURED_OWNER"
echo "HISTORICAL_unresolved_questions=NO_BACKFILL_NO_REINTERPRETATION"
echo "CANONICAL_PACKAGE_PIPELINE=UNCHANGED"
echo "USER_APPROVAL_TRANSITION=UNCHANGED"
echo "LIVING_DRAFT_REMAINS_NON_AUTHORITATIVE=YES"

echo
echo "=== REQUIRED VALIDATION ==="
echo "VALIDATE=OLLAMA_SCHEMA_AND_PARSER_TESTS"
echo "VALIDATE=PACKAGE_SEMANTICS_VALIDATOR_TESTS"
echo "VALIDATE=IEL_WRITE_READ_RECONSTRUCTION_TESTS"
echo "VALIDATE=DRAFT_SELECTION_AND_SYNTHESIS_TESTS"
echo "VALIDATE=EXISTING_TARGETED_TESTS"
echo "VALIDATE=CLIENT_OR_SERVER_BUILD_AS_APPLICABLE"
echo "ROLLBACK_BOUNDARY=DR_20260826_092915"
echo "NEXT_ACTION=IMPLEMENT_THIS_EXACT_UNIT_ONLY"
