#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE NARROW PUSH APPROVAL GATE TRANSITION ==="
echo "MODE=EXECUTION"
echo "AUTHORIZATION_SCOPE=GOVERNED_REMOTE_PUSH_APPROVAL_TRANSITION_ONLY"
echo "REMOTE_PUSH_EFFECT_IMPLEMENTATION_AUTHORIZED=NO"
echo "REMOTE_PUSH_EXECUTION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="7bd9d5692"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== CLOSED PREDECESSOR ==="
echo "LOCAL_COMMIT_EFFECT_UNIT=CLOSED"
echo "LOCAL_COMMIT_CLOSURE_COMMIT=693d3c9f6"
echo "REMOTE_PUSH_SUCCESSOR_CLASSIFICATION=7bd9d5692"
echo "LOCAL_COMMIT_APPROVAL_PHASE_MUST_REMAIN_STABLE=YES"
echo "LOCAL_COMMIT_EFFECT_MUST_REMAIN_STABLE=YES"

echo
echo "=== AUTHORIZED PATCH SET ==="
echo "FILE_1=server/execution/execution-approval-gate.mjs"
echo "FILE_2=server/execution/smoke-test-version-control-contract.mjs"
echo "OPTIONAL_FILE_3=server/execution/smoke-test-version-control-push-approval.mjs"
echo "CADE_VERSION_CONTROL_EFFECT_CHANGE=PROHIBITED"
echo "CADE_COMMIT_ADAPTER_CHANGE=PROHIBITED"
echo "GENERIC_CADE_EXECUTOR_CHANGE=PROHIBITED"
echo "GENERIC_CADE_ROUTE_CHANGE=PROHIBITED"
echo "GOVERNANCE_VALIDATOR_CHANGE=PROHIBITED"
echo "EXECUTION_SWITCH_CHANGE=PROHIBITED"
echo "EVENT_SCHEMA_CHANGE=PROHIBITED"

echo
echo "=== REQUIRED PUSH PHASE ==="
echo "PHASE=governed_version_control_push"
echo "CAPABILITY=REMOTE_PUSH_AUTHORITY_ONLY"

echo
echo "=== REQUIRED GRANT CONDITIONS ==="
echo "GOVERNANCE_OK=true"
echo "DELEGATED_ENVELOPE=true"
echo "APPROVAL_PRESENT=true"
echo "APPROVAL_STATUS=approved"
echo "REQUESTED_COMMIT_AUTHORIZED=true"
echo "REQUESTED_PUSH_AUTHORIZED=true"
echo "EXPECTED_HEAD_PRESENT=true"
echo "REPO_PATH_PRESENT=true"
echo "BRANCH_PRESENT=true"
echo "REMOTE_PRESENT=true"
echo "GENERIC_MUTATION_AUTHORIZED=false"
echo "SHELL_EXECUTION_AUTHORIZED=false"
echo "AUTONOMOUS_EXECUTION_AUTHORIZED=false"

echo
echo "=== REQUIRED SUCCESSFUL-LOCAL-COMMIT PROOF ==="
echo "LOCAL_COMMIT_RESULT_REQUIRED=YES"
echo "LOCAL_COMMIT_RESULT_STATUS=ok"
echo "LOCAL_COMMIT_POST_HEAD_REQUIRED=YES"
echo "LOCAL_COMMIT_PRE_HEAD_REQUIRED=YES"
echo "LOCAL_COMMIT_BRANCH_REQUIRED=YES"
echo "LOCAL_COMMIT_APPROVAL_ID_REQUIRED=YES"
echo "LOCAL_COMMIT_ENVELOPE_ID_REQUIRED=YES"
echo "LOCAL_COMMIT_EXECUTION_ID_REQUIRED=YES"
echo "LOCAL_COMMIT_REMOTE_EFFECT=false_REQUIRED"
echo "LOCAL_COMMIT_PUSH_EFFECT=false_REQUIRED"

echo
echo "=== REQUIRED CORRELATION RULES ==="
echo "ENVELOPE_ID_MUST_MATCH_LOCAL_COMMIT_RESULT=YES"
echo "APPROVAL_ID_MUST_MATCH_LOCAL_COMMIT_RESULT=YES"
echo "AUTHORIZED_BRANCH_MUST_MATCH_LOCAL_COMMIT_RESULT=YES"
echo "EXPECTED_PUSH_HEAD_MUST_EQUAL_LOCAL_COMMIT_POST_HEAD=YES"
echo "LOCAL_COMMIT_RESULT_MUST_NOT_BE_MODEL_INFERRED=YES"

echo
echo "=== REQUIRED EFFECTIVE OUTPUT ==="
echo "execution_phase=governed_version_control_push"
echo "version_control_authorization.commit_authorized=true"
echo "version_control_authorization.push_authorized=true"
echo "version_control_authorization.remote=APPROVED_REMOTE"
echo "version_control_authorization.branch=APPROVED_BRANCH"
echo "mutation_authorized=false"
echo "shell_execution_authorized=false"
echo "autonomous_execution_authorized=false"
echo "expected_push_head=LOCAL_COMMIT_POST_HEAD"

echo
echo "=== REQUIRED FAIL-CLOSED CONDITIONS ==="
echo "MISSING_LOCAL_COMMIT_RESULT=BLOCK"
echo "FAILED_LOCAL_COMMIT_RESULT=BLOCK"
echo "LOCAL_COMMIT_REMOTE_EFFECT_TRUE=BLOCK"
echo "LOCAL_COMMIT_PUSH_EFFECT_TRUE=BLOCK"
echo "LOCAL_COMMIT_HEAD_MISSING=BLOCK"
echo "LOCAL_COMMIT_BRANCH_MISMATCH=BLOCK"
echo "LOCAL_COMMIT_APPROVAL_ID_MISMATCH=BLOCK"
echo "LOCAL_COMMIT_ENVELOPE_ID_MISMATCH=BLOCK"
echo "MISSING_REMOTE=BLOCK"
echo "MISSING_BRANCH=BLOCK"
echo "MISSING_REPO_PATH=BLOCK"
echo "MISSING_EXPECTED_HEAD=BLOCK"
echo "COMMIT_AUTHORIZED_FALSE=BLOCK"
echo "PUSH_AUTHORIZED_FALSE=NO_PUSH_PHASE"
echo "GENERIC_MUTATION_TRUE=BLOCK"
echo "GENERIC_SHELL_TRUE=BLOCK"
echo "AUTONOMOUS_TRUE=BLOCK"
echo "GOVERNANCE_FAILURE=BLOCK"
echo "UNDELEGATED_ENVELOPE=BLOCK"

echo
echo "=== REQUIRED TRACE ==="
echo "approval_artifact_normalized=YES"
echo "governance_validated=YES"
echo "delegation_validated=YES"
echo "governed_local_commit_verified=YES"
echo "push_authority_granted=YES"
echo "mutation_authority_blocked=YES"
echo "shell_authority_blocked=YES"
echo "autonomous_authority_blocked=YES"

echo
echo "=== PRESERVED LOCAL COMMIT BEHAVIOR ==="
echo "COMMIT_ONLY_REQUEST_STILL_PHASE=governed_version_control_commit"
echo "COMMIT_ONLY_REQUEST_STILL_PUSH_AUTHORIZED=false"
echo "PUSH_REQUEST_MUST_NOT_REEXECUTE_LOCAL_COMMIT=YES"
echo "PUSH_PHASE_MUST_NOT_STAGE_FILES=YES"
echo "PUSH_PHASE_MUST_NOT_MODIFY_WORKTREE=YES"

echo
echo "=== REQUIRED TESTS ==="
echo "TEST_1=ORDINARY_PLANNING_REMAINS_governed_planning_only"
echo "TEST_2=COMMIT_ONLY_APPROVAL_REMAINS_governed_version_control_commit"
echo "TEST_3=VALID_PUSH_APPROVAL_WITH_SUCCESSFUL_LOCAL_COMMIT_GRANTS_PUSH"
echo "TEST_4=VALID_PUSH_APPROVAL_KEEPS_MUTATION_FALSE"
echo "TEST_5=VALID_PUSH_APPROVAL_KEEPS_SHELL_FALSE"
echo "TEST_6=VALID_PUSH_APPROVAL_KEEPS_AUTONOMOUS_FALSE"
echo "TEST_7=MISSING_LOCAL_COMMIT_RESULT_BLOCKS_PUSH"
echo "TEST_8=FAILED_LOCAL_COMMIT_RESULT_BLOCKS_PUSH"
echo "TEST_9=LOCAL_COMMIT_HEAD_MISMATCH_BLOCKS_PUSH"
echo "TEST_10=LOCAL_COMMIT_BRANCH_MISMATCH_BLOCKS_PUSH"
echo "TEST_11=APPROVAL_ID_MISMATCH_BLOCKS_PUSH"
echo "TEST_12=ENVELOPE_ID_MISMATCH_BLOCKS_PUSH"
echo "TEST_13=MISSING_REMOTE_BLOCKS_PUSH"
echo "TEST_14=NO_GIT_PROCESS_EXECUTION"
echo "TEST_15=NO_REMOTE_WRITE"

echo
echo "=== FAILURE CONTAINMENT ==="
echo "ANY_LOCAL_COMMIT_PHASE_REGRESSION=REVERT"
echo "ANY_PUSH_EFFECT_EXECUTION=REVERT"
echo "ANY_GENERIC_MUTATION_AUTHORITY_GRANT=REVERT"
echo "ANY_SHELL_AUTHORITY_GRANT=REVERT"
echo "ANY_AUTONOMOUS_AUTHORITY_GRANT=REVERT"
echo "ANY_GENERIC_CADE_ROUTE_CHANGE=REVERT"
echo "THREE_FAILED_HYPOTHESIS_RULE=ACTIVE"

echo
echo "=== AUTHORIZATION ==="
echo "NARROW_PUSH_APPROVAL_GATE_TRANSITION_AUTHORIZED=YES"
echo "REMOTE_PUSH_EFFECT_IMPLEMENTATION_AUTHORIZED=NO"
echo "REMOTE_PUSH_EXECUTION_AUTHORIZED=NO"
echo "NEXT_ACTION=IMPLEMENT_AND_VALIDATE_PUSH_APPROVAL_TRANSITION_ONLY"
