#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE EMPTY MISSION CONTROL PRESENTATION FIX ==="
echo "ROOT_CAUSE_CLASSIFICATION_COMMIT=f10a0d9b"
echo "GAP_CLASS=MISSION_CONTROL_EMPTY_STATE_PRESENTATION"

echo
echo "=== AUTHORIZED CHANGE ==="
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_UNIT=EMPTY_MISSION_CONTROL_TELEMETRY_PRESENTATION"
echo "PRIMARY_SURFACE=client/src/shell/MissionDashboardWorkspace.tsx"
echo "TARGETED_TESTS_AUTHORIZED=YES"

echo
echo "=== REQUIRED BEHAVIOR ==="
echo "NOT_FOUND_MUST_KEEP_DASHBOARD_SHELL_VISIBLE=YES"
echo "NOT_FOUND_MUST_KEEP_TELEMETRY_CARDS_VISIBLE=YES"
echo "EMPTY_PIPELINE_VALUES_MUST_BE_EXPLICIT_AND_NON_INVENTED=YES"
echo "ACTIVE_MISSION_RENDERING_MUST_REMAIN_UNCHANGED=YES"
echo "409_AND_500_MUST_REMAIN_FAIL_CLOSED_ERROR_STATES=YES"

echo
echo "=== OUT OF SCOPE ==="
echo "MISSION_READ_CHANGE_AUTHORIZED=NO"
echo "SERVER_CHANGE_AUTHORIZED=NO"
echo "PROJECT_CONTEXT_CHANGE_AUTHORIZED=NO"
echo "PACKAGE_HANDOFF_CHANGE_AUTHORIZED=NO"
echo "OPERATIONAL_AUTHORITY_CHANGE_AUTHORIZED=NO"
echo "DELEGATION_CHANGE_AUTHORIZED=NO"
echo "ROUTING_CHANGE_AUTHORIZED=NO"
echo "ASSIGNMENT_CHANGE_AUTHORIZED=NO"
echo "EXECUTION_CHANGE_AUTHORIZED=NO"
echo "SCHEMA_CHANGE_AUTHORIZED=NO"
echo "MIGRATION_CHANGE_AUTHORIZED=NO"

echo
echo "=== VALIDATION REQUIRED ==="
echo "TYPECHECK_REQUIRED=YES"
echo "NOT_FOUND_DASHBOARD_RENDER_TEST_REQUIRED=YES"
echo "TELEMETRY_CARDS_VISIBLE_WITHOUT_MISSION_TEST_REQUIRED=YES"
echo "ACTIVE_MISSION_REGRESSION_TEST_REQUIRED=YES"
echo "ERROR_STATE_REGRESSION_TEST_REQUIRED=YES"

echo
echo "=== BUILD PROTOCOL ==="
echo "MAX_FAILED_BUILDS_PER_HYPOTHESIS=3"
echo "SPECULATIVE_LAYERING_ALLOWED=NO"
echo "REVERT_IF_FAILURE_DOES_NOT_POINT_TO_CONFIDENT_NEXT_STEP=YES"

echo
echo "NEXT_ACTION=IMPLEMENT_ONLY_THE_BOUNDED_EMPTY_MISSION_CONTROL_PRESENTATION_FIX"
