#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE BOUNDED PACKAGE HANDOFF PROJECTION IMPLEMENTATION ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PACKAGE_HANDOFF_CONTRACT"
echo "PACKAGE_HANDOFF_CONTRACT_DESIGN=CLOSED"
echo "PACKAGE_HANDOFF_CONTRACT_RUNTIME_IMPLEMENTED=NO"
echo "PROJECT_BOUND_HANDOFF_STARTED=NO"

echo
echo "=== AUTHORIZED IMPLEMENTATION UNIT ==="
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_UNIT=CANONICAL_PACKAGE_TO_MISSION_PACKAGE_PROJECTION"
echo "AUTHORIZED_SCOPE=NEW_PROJECTION_ADAPTER+POST_APPROVAL_INTEGRATION+TARGETED_TESTS_ONLY"
echo "SOURCE=EXACT_canonical_approved_PACKAGE"
echo "SOURCE_IDENTITY=project_id+package_id+package_version"
echo "TARGET=governance_packages_DERIVED_MISSION_READ_PROJECTION"
echo "TARGET_FIELDS=package_id+package_version+project_id+conversation_id+requested_outcome+created_at"
echo "REQUESTED_OUTCOME_SOURCE=approved_expected_outcome"
echo "UNUSED_LEGACY_FIELDS=NULL"

echo
echo "=== REQUIRED RUNTIME BEHAVIOR ==="
echo "READ_EXACT_CANONICAL_IDENTITY=YES"
echo "REQUIRE_STATUS_canonical_approved=YES"
echo "CALLER_SUPPLIED_SEMANTIC_OVERRIDE=NO"
echo "SELECT_NEWEST_PACKAGE=NO"
echo "TARGET_ABSENT=INSERT_DERIVED_PROJECTION"
echo "EXACT_EXISTING_TARGET=IDEMPOTENT_SUCCESS"
echo "CONFLICTING_EXISTING_TARGET=FAIL_CLOSED"
echo "OVERWRITE_EXISTING_TARGET=NO"
echo "REPARENT_LEGACY_TARGET=NO"
echo "RETRY_CREATES_NEW_CANONICAL_VERSION=NO"

echo
echo "=== FAILURE MODEL ==="
echo "CANONICAL_APPROVAL_REMAINS_DURABLE_ON_PROJECTION_FAILURE=YES"
echo "PROJECTION_FAILURE_VISIBLE_TO_APPROVAL_CALLER=YES"
echo "PROJECTION_FAILURE_REPORTED_AS_SUCCESSFUL_HANDOFF=NO"
echo "PROJECTION_RETRY_MUST_BE_IDEMPOTENT=YES"

echo
echo "=== EXPLICITLY OUT OF SCOPE ==="
echo "SCHEMA_CHANGE_AUTHORIZED=NO"
echo "MIGRATION_CHANGE_AUTHORIZED=NO"
echo "MISSION_READ_CHANGE_AUTHORIZED=NO"
echo "MISSION_CONTROL_CHANGE_AUTHORIZED=NO"
echo "DELEGATION_CHANGE_AUTHORIZED=NO"
echo "VALIDATION_CHANGE_AUTHORIZED=NO"
echo "ROUTING_CHANGE_AUTHORIZED=NO"
echo "ASSIGNMENT_CHANGE_AUTHORIZED=NO"
echo "EXECUTION_CHANGE_AUTHORIZED=NO"
echo "EXISTING_CALLER_SUPPLIED_GOVERNANCE_PACKAGE_ROUTE_RECLASSIFICATION=NO"

echo
echo "=== REQUIRED VALIDATION ==="
echo "TYPECHECK_REQUIRED=YES"
echo "CANONICAL_APPROVAL_REGRESSION_TESTS_REQUIRED=YES"
echo "EXACT_APPROVED_IDENTITY_PROJECTION_TEST_REQUIRED=YES"
echo "PROJECT_ID_PRESERVATION_TEST_REQUIRED=YES"
echo "PACKAGE_ID_AND_VERSION_PRESERVATION_TEST_REQUIRED=YES"
echo "CONVERSATION_ID_PRESERVATION_TEST_REQUIRED=YES"
echo "REQUESTED_OUTCOME_DERIVATION_TEST_REQUIRED=YES"
echo "UNUSED_LEGACY_FIELDS_NULL_TEST_REQUIRED=YES"
echo "MISSING_SOURCE_FAIL_CLOSED_TEST_REQUIRED=YES"
echo "NON_APPROVED_SOURCE_FAIL_CLOSED_TEST_REQUIRED=YES"
echo "CONFLICTING_TARGET_NO_OVERWRITE_TEST_REQUIRED=YES"
echo "EXACT_TARGET_IDEMPOTENCY_TEST_REQUIRED=YES"
echo "DELEGATION_AUTHORITY_REMAINS_FALSE_TEST_REQUIRED=YES"
echo "EXECUTION_AUTHORITY_REMAINS_FALSE_TEST_REQUIRED=YES"

echo
echo "=== BUILD PROTOCOL ==="
echo "MAX_FAILED_BUILDS_PER_HYPOTHESIS=3"
echo "SPECULATIVE_LAYERING_ALLOWED=NO"
echo "REVERT_IF_FAILURE_DOES_NOT_POINT_TO_CONFIDENT_NEXT_STEP=YES"
echo "STABLE_BASE=7e5d0ba7"
echo "PRODUCTION_CHANGE=NONE_YET"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=IMPLEMENT_ONLY_THE_AUTHORIZED_PROJECTION_UNIT_AND_RUN_TARGETED_VALIDATION"
