#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE MINIMUM MISSION CONTROL PROJECT-SCOPED INTAKE ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=MISSION_CONTROL_INTAKE"
echo "PROJECT_BOUND_HANDOFF_CORRIDOR=CLOSED"
echo "ACTIVE_PROJECT_SOURCE_CLASSIFICATION=COMPLETE"
echo "IMPLEMENTATION_AUTHORIZED=YES"

echo
echo "=== AUTHORIZED IMPLEMENTATION UNIT ==="
echo "AUTHORIZED_UNIT=MINIMUM_MISSION_CONTROL_PROJECT_SCOPED_INTAKE_WIRING"
echo "AUTHORIZED_PROJECT_SOURCE=ProjectContextProvider.registry.activeProjectId"
echo "AUTHORIZED_SERVER_ENTRY_IDENTITY=project_id"
echo "AUTHORIZED_ENDPOINT=/api/mission-read/:projectId"
echo "SERVER_OPERATIONAL_AUTHORITY_RESOLUTION_REMAINS_AUTHORITATIVE=YES"

echo
echo "=== AUTHORIZED SURFACES ==="
echo "SURFACE_1=client/src/mission-control/missionReadApi.ts"
echo "SURFACE_2=client/src/mission-control/MissionControlProvider.tsx"
echo "SURFACE_3=client/src/shell/MissionDashboardWorkspace.tsx"
echo "SURFACE_4=TARGETED_CLIENT_TESTS_IF_SUPPORTED_BY_EXISTING_TEST_ARCHITECTURE"
echo "ProjectContextProvider_CHANGE_AUTHORIZED=NO"
echo "PackageReadProvider_CHANGE_AUTHORIZED=NO"
echo "SERVER_ROUTE_CHANGE_AUTHORIZED=NO"
echo "MISSION_READ_REPOSITORY_CHANGE_AUTHORIZED=NO"
echo "SCHEMA_CHANGE_AUTHORIZED=NO"
echo "MIGRATION_CHANGE_AUTHORIZED=NO"

echo
echo "=== REQUIRED CLIENT FLOW ==="
echo "STEP_1=CONSUME_EXISTING_SHARED_ACTIVE_PROJECT_ID"
echo "STEP_2=PASS_project_id_TO_MISSION_CONTROL_PROVIDER"
echo "STEP_3=REQUEST_/api/mission-read/:projectId"
echo "STEP_4=SERVER_RESOLVES_EXACT_OPERATIONAL_PACKAGE_AUTHORITY"
echo "STEP_5=RENDER_RETURNED_MISSION_READ_MODEL"
echo "HARDCODED_corridor-smoke_MUST_BE_REMOVED=YES"
echo "CALLER_PACKAGE_ID_AS_SELECTION_AUTHORITY=NO"
echo "CLIENT_PACKAGE_VERSION_SELECTION=NO"
echo "NEWEST_PACKAGE_INFERENCE=NO"
echo "SUCCESSOR_VERSION_INFERENCE=NO"

echo
echo "=== PROVIDER CONTRACT ==="
echo "PROVIDER_INPUT=activeProjectId"
echo "PROVIDER_LAST_IDENTITY_IF_CACHED=projectId"
echo "PROJECT_CHANGE_MUST_TRIGGER_NEW_PROJECT_SCOPED_READ=YES"
echo "PROJECT_CHANGE_MUST_CLEAR_STALE_PREVIOUS_MISSION=YES"
echo "NO_ACTIVE_PROJECT=NO_MISSION"
echo "SERVER_404=NO_ACTIVE_MISSION"
echo "SERVER_409=FAIL_CLOSED_ERROR"
echo "SERVER_500=FAIL_CLOSED_ERROR"
echo "PROVIDER_MAY_SELECT_PACKAGE=NO"
echo "PROVIDER_MAY_MUTATE_OPERATIONAL_AUTHORITY=NO"

echo
echo "=== WORKSPACE CONTRACT ==="
echo "WORKSPACE_CONSUMES_SHARED_PROJECT_CONTEXT=YES"
echo "WORKSPACE_USES_ACTIVE_PROJECT_ID_FOR_MISSION_INTAKE=YES"
echo "WORKSPACE_HARDCODED_PACKAGE_FALLBACK=NO"
echo "WORKSPACE_NEWEST_PACKAGE_FALLBACK=NO"
echo "WORKSPACE_PACKAGE_SELECTION_AUTHORITY=NO"

echo
echo "=== AUTHORITY NON-ESCALATION ==="
echo "MISSION_CONTROL_SELECTS_ACTIVE_PROJECT=NO"
echo "MISSION_CONTROL_SELECTS_OPERATIONAL_PACKAGE=NO"
echo "MISSION_CONTROL_MUTATES_CANONICAL_PACKAGE=NO"
echo "MISSION_CONTROL_MUTATES_MISSION_PACKAGE_PROJECTION=NO"
echo "MISSION_CONTROL_MUTATES_OPERATIONAL_PACKAGE_AUTHORITY=NO"
echo "DELEGATION_CHANGE_AUTHORIZED=NO"
echo "VALIDATION_CHANGE_AUTHORIZED=NO"
echo "ROUTING_CHANGE_AUTHORIZED=NO"
echo "ASSIGNMENT_CHANGE_AUTHORIZED=NO"
echo "EXECUTION_CHANGE_AUTHORIZED=NO"

echo
echo "=== REQUIRED VALIDATION ==="
echo "TYPECHECK_REQUIRED=YES"
echo "PROJECT_SCOPED_CLIENT_ENDPOINT_TEST_REQUIRED=YES"
echo "ACTIVE_PROJECT_DRIVES_MISSION_READ_TEST_REQUIRED=YES"
echo "PROJECT_SWITCH_RELOAD_TEST_REQUIRED=YES"
echo "STALE_PREVIOUS_PROJECT_MISSION_CLEAR_TEST_REQUIRED=YES"
echo "NO_ACTIVE_PROJECT_STATE_TEST_REQUIRED=YES"
echo "NO_OPERATIONAL_AUTHORITY_404_TEST_REQUIRED=YES"
echo "IDENTITY_CONFLICT_FAIL_CLOSED_TEST_REQUIRED=YES"
echo "HARDCODED_corridor-smoke_ABSENT_TEST_REQUIRED=YES"
echo "PACKAGE_SELECTION_LOGIC_ABSENT_TEST_REQUIRED=YES"
echo "OPERATIONAL_AUTHORITY_STATE_UNCHANGED_TEST_REQUIRED=YES"
echo "DELEGATION_STATE_UNCHANGED_TEST_REQUIRED=YES"
echo "EXECUTION_STATE_UNCHANGED_TEST_REQUIRED=YES"

echo
echo "=== BUILD PROTOCOL ==="
echo "MAX_FAILED_BUILDS_PER_HYPOTHESIS=3"
echo "SPECULATIVE_LAYERING_ALLOWED=NO"
echo "REVERT_IF_FAILURE_DOES_NOT_POINT_TO_CONFIDENT_NEXT_STEP=YES"
echo "STABLE_BASE=5d62f34f"

echo
echo "=== CORRIDOR STATE ==="
echo "MISSION_CONTROL_INTAKE_IMPLEMENTATION_AUTHORIZED=YES"
echo "MISSION_CONTROL_INTAKE_IMPLEMENTATION_STARTED=NO"
echo "MISSION_CONTROL_PACKAGE_AUTHORITY=NONE"
echo "HANDOFF_VALIDATION_AND_PHASE_CLOSURE_STARTED=NO"
echo "PRODUCTION_CHANGE=NONE_YET"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=IMPLEMENT_ONLY_MINIMUM_MISSION_CONTROL_PROJECT_SCOPED_INTAKE_WIRING_AND_TARGETED_VALIDATION"
