#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

PROJECT_ID="hq"
PACKAGE_ID="pkg-ff156f5a-cd71-4cf9-8955-f3beaafb261c"
PACKAGE_VERSION="1"

echo "=== AUTHORIZE EXACT LIVE OPERATIONAL PACKAGE SELECTION ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PROJECT_BOUND_HANDOFF"
echo "IMPLEMENTATION_CLASSIFICATION_COMMIT=cf2dbbcf"
echo "PACKAGE_HANDOFF_CONTRACT_REMAINS_CLOSED=YES"

echo
echo "=== AUTHORIZED AUTHORITY EVENT ==="
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_EVENT=EXPLICIT_LIVE_OPERATIONAL_PACKAGE_SELECTION"
echo "AUTHORIZED_PROJECT_ID=${PROJECT_ID}"
echo "AUTHORIZED_PACKAGE_ID=${PACKAGE_ID}"
echo "AUTHORIZED_PACKAGE_VERSION=${PACKAGE_VERSION}"
echo "AUTHORIZED_WRITE_UNIT=selectOperationalPackageForProject"
echo "GENERAL_PACKAGE_SELECTION_AUTHORIZED=NO"
echo "OTHER_PROJECT_SELECTION_AUTHORIZED=NO"
echo "OTHER_PACKAGE_SELECTION_AUTHORIZED=NO"

echo
echo "=== REQUIRED PRECONDITIONS ==="
echo "REGISTERED_PROJECT_REQUIRED=YES"
echo "EXACT_CANONICAL_PACKAGE_REQUIRED=YES"
echo "canonical_approved_REQUIRED=YES"
echo "EXACT_PROJECT_PACKAGE_OWNERSHIP_MATCH_REQUIRED=YES"
echo "EXACT_DERIVED_MISSION_PACKAGE_PROJECTION_REQUIRED=YES"
echo "CURRENT_AUTHORITY_ROW_EXPECTED=NONE"
echo "SELECT_NEWEST_PACKAGE=NO"
echo "SUCCESSOR_VERSION_AUTO_ACTIVATION=NO"

echo
echo "=== AUTHORITY NON-ESCALATION ==="
echo "CANONICAL_PACKAGE_MUTATION_AUTHORIZED=NO"
echo "MISSION_PACKAGE_PROJECTION_MUTATION_AUTHORIZED=NO"
echo "DELEGATION_CREATION_AUTHORIZED=NO"
echo "VALIDATION_AUTHORITY_AUTHORIZED=NO"
echo "ROUTING_AUTHORITY_AUTHORIZED=NO"
echo "ASSIGNMENT_AUTHORITY_AUTHORIZED=NO"
echo "EXECUTION_AUTHORITY_AUTHORIZED=NO"
echo "MISSION_READ_INTEGRATION_AUTHORIZED=NO"
echo "MISSION_CONTROL_INTEGRATION_AUTHORIZED=NO"

echo
echo "=== REQUIRED VALIDATION AFTER SELECTION ==="
echo "AUTHORITY_ROW_COUNT_FOR_PROJECT_MUST_EQUAL=1"
echo "AUTHORITY_PROJECT_ID_MUST_EQUAL=${PROJECT_ID}"
echo "AUTHORITY_PACKAGE_ID_MUST_EQUAL=${PACKAGE_ID}"
echo "AUTHORITY_PACKAGE_VERSION_MUST_EQUAL=${PACKAGE_VERSION}"
echo "EXACT_CANONICAL_REFERENCE_MUST_REMAIN_VALID=YES"
echo "EXACT_MISSION_PROJECTION_MUST_REMAIN_PRESENT=YES"
echo "IDEMPOTENT_REPEAT_MUST_PRESERVE_BINDING=YES"
echo "DELEGATION_STATE_MUST_REMAIN_UNCHANGED=YES"
echo "EXECUTION_STATE_MUST_REMAIN_UNCHANGED=YES"

echo
echo "=== FAILURE / ROLLBACK BOUNDARY ==="
echo "PRECONDITION_FAILURE=FAIL_CLOSED"
echo "IDENTITY_MISMATCH=FAIL_CLOSED"
echo "UNEXPECTED_EXISTING_DIFFERENT_BINDING=STOP_BEFORE_MUTATION"
echo "AUTHORITY_SELECTION_FAILURE_MUST_NOT_MUTATE_CANONICAL_PACKAGE=YES"
echo "AUTHORITY_SELECTION_FAILURE_MUST_NOT_MUTATE_MISSION_PACKAGE_PROJECTION=YES"
echo "AUTHORITY_SELECTION_FAILURE_MUST_NOT_CREATE_DELEGATION=YES"
echo "AUTHORITY_SELECTION_FAILURE_MUST_NOT_CONFER_EXECUTION_AUTHORITY=YES"

echo
echo "=== CORRIDOR STATE ==="
echo "PROJECT_BOUND_HANDOFF_PERSISTENCE_UNIT=IMPLEMENTED_AND_VALIDATED"
echo "LIVE_OPERATIONAL_SELECTION_AUTHORIZED=YES"
echo "LIVE_OPERATIONAL_SELECTION_EXECUTED=NO"
echo "DOWNSTREAM_PROJECT_SCOPED_READ_HANDOFF_STARTED=NO"
echo "MISSION_CONTROL_INTAKE_STARTED=NO"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=EXECUTE_ONLY_THE_EXACT_AUTHORIZED_OPERATIONAL_PACKAGE_SELECTION_AND_VALIDATE_PERSISTED_AUTHORITY_STATE"
