#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE BOUNDED LIVE OPTION B VALIDATION ==="
echo "EXPECTED_HEAD_PREFIX=00ffa466c"
echo "DESIGN_COMMIT=00ffa466c3f01f1bd782f04948ff0ab985301c3c"
echo "IMPLEMENTATION_COMMIT=11fc6efda"
echo "MODE=COLLABORATION"
echo "PRODUCTION_POLICY_CHANGE=NO"
echo "GENERATION_POLICY_CHANGE=NO"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 00ffa466c* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== AUTHORIZATION ==="
echo "AUTHORIZED_VALIDATION=ONE_UNSEEDED_LIVE_TYPED_INPUT_INVOCATION"
echo "VALIDATION_SEED=NONE"
echo "RETRY_AUTHORIZED=NO"
echo "SECOND_OLLAMA_INVOCATION=NO"
echo "PROVENANCE_WEAKENING=NO"
echo "AUTOMATIC_REPAIR=NO"
echo "AUTHORITY_CHANGE=NO"
echo "IEL_SCHEMA_CHANGE=NO"

echo
echo "=== RESULT CLASSIFICATION ==="
echo "EXACT_TYPED_VALUE_PRESERVED=VALID_FIDELITY_RESULT"
echo "EXPLICIT_FIDELITY_MISMATCH_REJECTION=VALID_FIDELITY_RESULT"
echo "UNRELATED_PRE_FIDELITY_VALIDATION_FAILURE=INCONCLUSIVE"
echo "INCONCLUSIVE_RESULT_MUST_NOT_TRIGGER_BLIND_RETRY=YES"
echo "GENERAL_PRODUCTION_GENERATION_STABILITY_PROOF=NO"
echo "PACKAGE_SEMANTICS_CORRIDOR_CLOSURE_AUTOMATIC=NO"

echo
echo "NEXT_ACTION=RUN_EXACTLY_ONE_BOUNDED_LIVE_TYPED_INPUT_VALIDATION"

git diff --check

git add authorize-bounded-live-option-b-validation.sh
git commit -m "Authorize bounded live typed package semantics validation"
git push
