#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE PACKAGE SEMANTICS CONDITIONAL COMPLETENESS ==="
echo "EXPECTED_HEAD_PREFIX=66261460a"
echo "RECOVERY_POINT=DR_20260826_111719"
echo "SCOPE=MATILDA_PACKAGE_SEMANTICS_CONDITIONAL_COMPLETENESS"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORITY_MODEL_CHANGE=NO"
echo "SECOND_OLLAMA_INVOCATION=NO"
echo "HEURISTIC_EXTRACTION=NO"
echo "HISTORICAL_BACKFILL=NO"
echo "SIDEBAR_COMPACTNESS=SEPARATE_FOLLOWUP"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 66261460a* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== AUTHORIZED CONTRACT ==="
echo "TOP_LEVEL_packageSemantics_NULLABILITY=PRESERVE"
echo "INDIVIDUAL_FIELD_NULLABILITY=PRESERVE_WHEN_CURRENT_REQUEST_DOES_NOT_ESTABLISH_FIELD"
echo "CURRENT_REQUEST_EXPLICIT_FIELD_PRESERVATION=REQUIRED"
echo "UNSUPPORTED_FIELD_INVENTION=PROHIBITED"
echo "GENERIC_DEFAULTS=PROHIBITED"
echo "CROSS_TURN_FIELD_MERGE=PROHIBITED"
echo "VALIDATOR_GLOBAL_NON_NULL_REQUIREMENT=NO"

echo
echo "=== AUTHORIZED IMPLEMENTATION SURFACE ==="
echo "PRIMARY=scripts/utils/ollamaChat.ts_PROMPT_AUTHORSHIP_RULES"
echo "TEST=scripts/utils/ollamaChat.package-semantics-contract.test.ts"
echo "IEL_CHANGE=NO"
echo "LIVING_DRAFT_SYNTHESIS_CHANGE=NO"
echo "APPROVAL_READ_MODEL_CHANGE=NO"
echo "APPROVAL_UI_CHANGE=NO"

echo
echo "=== REQUIRED VALIDATION ==="
echo "PACKAGE_SEMANTICS_TESTS=REQUIRED"
echo "LIFECYCLE_REGRESSION_TESTS=REQUIRED"
echo "TYPESCRIPT_CHECK=REQUIRED"
echo "BUILD=REQUIRED"
echo "DIFF_CHECK=REQUIRED"
echo "LIVE_SEED_REVALIDATION=REQUIRED_AFTER_IMPLEMENTATION"

git diff --check

git add authorize-package-semantics-conditional-completeness.sh
git commit -m "Authorize package semantics conditional completeness"
git push
