#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE OPTION B TYPED USER PACKAGE SEMANTICS IMPLEMENTATION ==="
echo "EXPECTED_HEAD_PREFIX=e64a3cdfa"
echo "RECOVERY_POINT=DR_20260826_111719"
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != e64a3cdfa* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED DESIGN ==="
echo "DESIGN_COMMIT=e64a3cdfab73584cddce02569dd9f3322c13d176"
echo "TYPED_INPUT_OPTIONAL=YES"
echo "RAW_MESSAGE_RETAINED=YES"
echo "EXPLICIT_TYPED_VALUES_REQUIRE_EXACT_TRIMMED_FIDELITY=YES"
echo "MISMATCH_FAILS_CLOSED_BEFORE_IEL_PERSISTENCE=YES"
echo "HEURISTIC_EXTRACTION=NO"
echo "SECOND_OLLAMA_INVOCATION=NO"
echo "AUTOMATIC_REPAIR=NO"
echo "DOWNSTREAM_OVERWRITE=NO"
echo "AUTHORITY_MODEL_CHANGE=NO"
echo "UI_REDIRECT_OR_REDESIGN=NO"
echo "SIDEBAR_COMPACTNESS=SEPARATE"

echo
echo "=== IMPLEMENTATION AUTHORIZATION ==="
echo "AUTHORIZED_UNIT=OPTION_B_TYPED_USER_PACKAGE_SEMANTICS_FIDELITY"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_SURFACES=WORKFLOW_INPUT,OLLAMA_CONTEXT,PROMPT_TRANSPORT,TYPED_INPUT_VALIDATION,FIDELITY_VALIDATION,FOCUSED_TESTS"
echo "IEL_SCHEMA_CHANGE=NO"
echo "LIVING_DRAFT_CHANGE=NO"
echo "APPROVAL_AUTHORITY_CHANGE=NO"
echo "CANONICAL_PACKAGE_AUTHORITY_CHANGE=NO"
echo "DELEGATION_CHANGE=NO"
echo "GENERATION_POLICY_CHANGE=NO"
echo "HISTORICAL_BACKFILL=NO"

echo
echo "=== REQUIRED VALIDATION ==="
echo "ABSENT_TYPED_INPUT_PRESERVES_EXISTING_BEHAVIOR=REQUIRED"
echo "NULL_TYPED_INPUT_PRESERVES_EXISTING_BEHAVIOR=REQUIRED"
echo "EXPLICIT_expectedOutcome_PROMPT_TRANSPORT=REQUIRED"
echo "EXACT_MATCH_PASS=REQUIRED"
echo "BOUNDARY_WHITESPACE_NORMALIZATION_PASS=REQUIRED"
echo "NULL_OUTPUT_FAIL_CLOSED=REQUIRED"
echo "SEMANTICALLY_SIMILAR_NONIDENTICAL_OUTPUT_FAIL_CLOSED=REQUIRED"
echo "OMITTED_TYPED_FIELDS_NO_EQUALITY_REQUIREMENT=REQUIRED"
echo "MISMATCH_BEFORE_IEL_PERSISTENCE=REQUIRED"
echo "ONE_OLLAMA_INVOCATION=REQUIRED"
echo "PACKAGE_SEMANTICS_REGRESSION=REQUIRED"
echo "LIFECYCLE_REGRESSION=REQUIRED"
echo "SUPPORT_PROVENANCE_FAIL_CLOSED_REGRESSION=REQUIRED"
echo "TYPECHECK_BUILD_DIFF_CHECK=REQUIRED"

echo
echo "NEXT_ACTION=IMPLEMENT_AUTHORIZED_UNIT_ONLY"

git diff --check

git add authorize-option-b-typed-user-package-semantics-implementation.sh
git commit -m "Authorize typed user package semantics implementation"
git push
