#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="a1c249956"

git fetch origin "$BRANCH"
test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$EXPECTED_HEAD"

printf '\n====================================================\n'
printf ' AUTHORITATIVE ENVELOPE SEMANTICS CONTRACT — AUTHORIZATION\n'
printf '====================================================\n\n'

echo "PREDECESSOR_BOUNDARY=BOUNDED_ENVELOPE_CREATION"
echo "PREDECESSOR_STATUS=BLOCKED_ON_ARCHITECTURAL_GAP"
echo "SUCCESSOR_BOUNDARY=AUTHORITATIVE_ENVELOPE_SEMANTICS_CONTRACT"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_BY=marcela"
echo "AUTHORIZED_SCOPE=BOUNDED_AUTHORITATIVE_ENVELOPE_SEMANTICS_CONTRACT_IMPLEMENTATION"

printf '\n=== AUTHORIZED CONTRACT WORK ===\n'
echo "DEFINE_AUTHORITATIVE_OWNER_FOR_REQUIRED_CAPABILITIES=YES"
echo "DEFINE_AUTHORITATIVE_OWNER_FOR_OPERATIONAL_CORRIDOR=YES"
echo "DEFINE_ALLOWED_TRANSFORMATION_FROM_UPSTREAM_GOVERNANCE_DATA_IF_ANY=YES"
echo "PRESERVE_VALIDATION_AS_SEPARATE_AUTHORITY_STAGE=YES"
echo "PRESERVE_ENVELOPE_GATE_AS_SEPARATE_AUTHORITY_STAGE=YES"
echo "PRESERVE_ENVELOPE_CREATION_AS_SEPARATE_EXPLICIT_ACTION=YES"

printf '\n=== EXPRESSLY NOT AUTHORIZED ===\n'
echo "ENVELOPE_CREATION_IMPLEMENTATION=NO"
echo "LIVE_ENVELOPE_CREATION=NO"
echo "LIVE_GOVERNANCE_DATA_MUTATION=NO"
echo "AUTOMATIC_GATE_TO_ENVELOPE_TRANSITION=NO"
echo "LIFECYCLE_TRANSITION_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "DOWNSTREAM_EXECUTION_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"

printf '\n=== SEMANTIC SAFETY RULES ===\n'
echo "INVENT_VALUES_FROM_FIELD_NAME_SIMILARITY=NO"
echo "PROMOTE_TEST_LITERALS_TO_PRODUCTION_SEMANTICS=NO"
echo "PROMOTE_LEGACY_HARDCODED_VALUES=NO"
echo "PROMOTE_GATE_VALIDATION_ONLY_PLACEHOLDERS=NO"
echo "FAIL_CLOSED_IF_AUTHORITATIVE_OWNER_CANNOT_BE_DEFINED=YES"

printf '\n=== PRESERVED INVARIANTS ===\n'
echo "APPROVAL_NE_DELEGATION=YES"
echo "DELEGATION_NE_VALIDATION=YES"
echo "VALIDATION_NE_ENVELOPE_GATE=YES"
echo "ENVELOPE_GATE_NE_ENVELOPE=YES"
echo "ENVELOPE_NE_EXECUTION=YES"
echo "EXACT_LINEAGE_REQUIRED=YES"
echo "FAIL_CLOSED_BEHAVIOR_REQUIRED=YES"
echo "NO_GENERIC_SHELL=YES"
echo "NO_SELF_AUTHORIZATION=YES"

printf '\nAUTHORITATIVE_ENVELOPE_SEMANTICS_CONTRACT_IMPLEMENTATION_AUTHORIZED=YES\n'
