#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE PROJECT-SCOPED DELEGATION IMPLEMENTATION UNIT ==="

echo
echo "=== BASELINE ==="
printf "HEAD=" && git rev-parse --short=8 HEAD
printf "BRANCH=" && git branch --show-current
git status --short

echo
echo "=== VERIFIED READY-BOUNDED UNIT ==="
echo "UNIT_NAME=PROJECT_SCOPED_DELEGATION_REFERENCE"
echo "DATABASE_ENFORCED_PROJECT_SCOPED_DELEGATION=SCHEMA_FEASIBLE"
echo "REQUIRED_PARENT_ADDITION=UNIQUE_INDEX_ON_PROJECT_ID_PACKAGE_ID_PACKAGE_VERSION"
echo "REQUIRED_DELEGATION_ADDITION=PROJECT_ID"
echo "REQUIRED_NEW_DELEGATION_FK=(project_id,package_id,package_version)"
echo "CANONICAL_PRIMARY_KEY_CHANGE_REQUIRED=NO"
echo "CANONICAL_PROJECT_ID_NOT_NULL_CHANGE=NO"
echo "HISTORICAL_CANONICAL_PACKAGE_MUTATION_REQUIRED=NO"
echo "HISTORICAL_DELEGATION_REPARENTING_REQUIRED=NO"

echo
echo "=== AUTHORIZED IMPLEMENTATION SCOPE ==="
echo "SCHEMA_CHANGE_1=ADD_PARENT_UNIQUE_INDEX"
echo "SCHEMA_CHANGE_2=ADD_DELEGATION_PROJECT_ID"
echo "SCHEMA_CHANGE_3=DATABASE_ENFORCE_PROJECT_PACKAGE_VERSION_REFERENCE"
echo "RUNTIME_CHANGE_1=TRANSPORT_PROJECT_ID_THROUGH_DELEGATION_CONSUMER"
echo "RUNTIME_CHANGE_2=TRANSPORT_PROJECT_ID_THROUGH_DELEGATION_ENTRY_POINT"
echo "RUNTIME_CHANGE_3=VALIDATE_CANONICAL_PACKAGE_PROJECT_MATCH"
echo "RUNTIME_CHANGE_4=PERSIST_PROJECT_ID_ON_NEW_DELEGATIONS"

echo
echo "=== CONTAINMENT ==="
echo "VALIDATION_CHANGE=NONE"
echo "ENVELOPE_GATE_CHANGE=NONE"
echo "ENVELOPE_CHANGE=NONE"
echo "MISSION_READ_CHANGE=NONE"
echo "OPERATIONAL_INTAKE_CHANGE=NONE"
echo "ROUTING_CHANGE=NONE"
echo "ASSIGNMENT_CHANGE=NONE"
echo "EXECUTION_CHANGE=NONE"
echo "LEGACY_CORRIDOR_SMOKE_MUTATION=NO"
echo "LEGACY_CORRIDOR_SMOKE_REPARENTING=NO"
echo "KNOWN_DOWNSTREAM_FK_DEFECT_REOPENED=NO"

echo
echo "=== REQUIRED IMPLEMENTATION VALIDATION ==="
echo "VALIDATE_1=TYPECHECK"
echo "VALIDATE_2=DELEGATION_UNIT_TESTS"
echo "VALIDATE_3=PROJECT_MATCH_ACCEPTED"
echo "VALIDATE_4=CROSS_PROJECT_PACKAGE_REFERENCE_REJECTED"
echo "VALIDATE_5=MISSING_PROJECT_REJECTED"
echo "VALIDATE_6=CANONICAL_ROOT_REQUIREMENT_PRESERVED"
echo "VALIDATE_7=NO_NEW_DOWNSTREAM_AUTHORITY"
echo "VALIDATE_8=TARGETED_FOREIGN_KEY_CHECK"

echo
echo "=== AUTHORIZATION ==="
echo "IMPLEMENTATION_UNIT=READY_BOUNDED"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "IMPLEMENTATION_STARTED=NO"
echo "NEXT_ACTION=IMPLEMENT_ONLY_THE_PROJECT_SCOPED_DELEGATION_REFERENCE_UNIT_AND_STOP_ON_ANY_UNEXPECTED_SCHEMA_OR_LINEAGE_EXPANSION"
