#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE NARROW DELEGATION IMPORT RESOLUTION FIX ==="
echo "BASELINE_COMMIT=4d223db3"
echo "ESTABLISHED_FAILURE=TS_NODE_SOURCE_IMPORT_EXTENSION_MISMATCH"
echo "MISSING_CAPABILITY=NO"
echo "DELEGATION_GOVERNANCE_SEMANTICS_CHANGE=NO"
echo "FIX_SCOPE=MODULE_IMPORT_RESOLUTION_ONLY"
echo "AUTHORIZED_SOURCE_FILE=server/routes/governance-delegation-route.ts"
echo "AUTHORIZED_CHANGE_1=REMOVE_DOT_JS_FROM_production-delegation-consumer_IMPORT"
echo "AUTHORIZED_CHANGE_2=REMOVE_DOT_JS_FROM_production-delegation-entry-point_IMPORT"
echo "OTHER_SOURCE_CHANGES_AUTHORIZED=NO"
echo "IMPLEMENTATION_AUTHORIZED=YES_NARROWLY"
echo "ROLLBACK_BOUNDARY=REVERT_SINGLE_IMPORT_RESOLUTION_COMMIT_IF_SERVER_BOOT_OR_TESTS_FAIL"
echo "NEXT_ACTION=IMPLEMENT_EXACT_IMPORT_EXTENSION_FIX_AND_VALIDATE_SERVER_BOOT"
