#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AUTHORIZE ONE-TIME LIVE PACKAGE PROJECTION RECONCILIATION ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PACKAGE_HANDOFF_CONTRACT"
echo "RUNTIME_IMPLEMENTATION_COMMIT=2efe86d5"
echo "LIVE_RECONCILIATION_CLASSIFICATION_COMMIT=8704bd99"
echo "PROJECT_BOUND_HANDOFF_STARTED=NO"

echo
echo "=== AUTHORIZED RECONCILIATION ==="
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_UNIT=ONE_TIME_EXACT_EXISTING_CANONICAL_PACKAGE_PROJECTION_RECONCILIATION"
echo "AUTHORIZED_PROJECT_ID=hq"
echo "AUTHORIZED_PACKAGE_ID=pkg-ff156f5a-cd71-4cf9-8955-f3beaafb261c"
echo "AUTHORIZED_PACKAGE_VERSION=1"
echo "AUTHORIZED_ADAPTER=projectCanonicalPackageToMissionPackage"
echo "GENERAL_HISTORICAL_BACKFILL_AUTHORIZED=NO"
echo "OTHER_PACKAGE_RECONCILIATION_AUTHORIZED=NO"

echo
echo "=== REQUIRED PRECONDITIONS ==="
echo "EXACT_project_id+package_id+package_version_REQUIRED=YES"
echo "canonical_approved_REQUIRED=YES"
echo "CURRENT_TARGET_MUST_BE_ABSENT_OR_EXACT_IDEMPOTENT_MATCH=YES"
echo "CALLER_SUPPLIED_SEMANTIC_OVERRIDE=NO"
echo "SELECT_NEWEST_PACKAGE=NO"

echo
echo "=== AUTHORITY BOUNDARY ==="
echo "CANONICAL_PACKAGE_MUTATION=NO"
echo "NEW_CANONICAL_VERSION=NO"
echo "DELEGATION_CREATION=NO"
echo "VALIDATION_CHANGE=NO"
echo "MISSION_READ_CHANGE=NO"
echo "MISSION_CONTROL_CHANGE=NO"
echo "ROUTING_CHANGE=NO"
echo "ASSIGNMENT_CHANGE=NO"
echo "EXECUTION_CHANGE=NO"

echo
echo "=== FAILURE / ROLLBACK BOUNDARY ==="
echo "CONFLICTING_TARGET=FAIL_CLOSED"
echo "OVERWRITE_EXISTING_TARGET=NO"
echo "LEGACY_REPARENTING=NO"
echo "RETRY_MUST_BE_IDEMPOTENT=YES"
echo "CANONICAL_APPROVAL_REMAINS_DURABLE=YES"
echo "RECONCILIATION_FAILURE_DOES_NOT_REOPEN_RUNTIME_DESIGN=YES"

echo
echo "=== VALIDATION REQUIRED AFTER RECONCILIATION ==="
echo "TARGET_ROW_PRESENT=YES"
echo "TARGET_PROJECT_ID_MUST_EQUAL=hq"
echo "TARGET_PACKAGE_ID_MUST_EQUAL=pkg-ff156f5a-cd71-4cf9-8955-f3beaafb261c"
echo "TARGET_PACKAGE_VERSION_MUST_EQUAL=1"
echo "TARGET_CONVERSATION_ID_MUST_MATCH_CANONICAL=YES"
echo "TARGET_requested_outcome_MUST_MATCH_approved_expected_outcome=YES"
echo "UNUSED_LEGACY_FIELDS_MUST_BE_NULL=YES"
echo "DELEGATION_STATE_UNCHANGED=YES"
echo "EXECUTION_STATE_UNCHANGED=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=EXECUTE_ONE_TIME_EXACT_LIVE_RECONCILIATION_USING_EXISTING_PROJECTION_ADAPTER_AND_VERIFY_TARGET_STATE"
