#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== AWAIT APPROVALS VISUAL REVIEW ==="
echo "BASELINE_COMMIT=b5f9fa5f"
echo "CLIENT_BUILD=PASS"
echo "IMPLEMENTATION_STATE=PAUSED"
echo "FURTHER_UI_CHANGE_AUTHORIZED=NO"
echo "PACKAGES_TAB_REMOVAL_AUTHORIZED=NO"
echo "NEXT_ACTION=USER_RETURNS_APPROVALS_SCREENSHOT_OR_VISUAL_FEEDBACK"
