#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY EXECUTION APPROVAL AUTHORITY TRANSITION AND REUSE BOUNDARY ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "EXECUTION_APPROVAL_IMPLEMENTATION_AUTHORIZED=NO"
echo "ORCHESTRATOR_IMPLEMENTATION_AUTHORIZED=NO"
echo "ACTIVE_REPOSITORY_ENABLEMENT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="d27c6443c"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== INSPECT EXISTING MATILDA EXECUTION AUTHORIZATION ROUTE ==="
sed -n '1,260p' server/routes/matilda-execution-authorization-route.ts

echo
echo "=== INSPECT APPROVAL ARTIFACT BUILDER ==="
sed -n '1,320p' server/execution/build-approval-artifact.mjs

echo
echo "=== INSPECT EXECUTION APPROVAL GATE ==="
sed -n '1,480p' server/execution/execution-approval-gate.mjs

echo
echo "=== INSPECT GOVERNED PLANNING ROUTE ==="
sed -n '1,380p' server/routes/governed-planning-route.mjs

echo
echo "=== INSPECT CANONICAL PACKAGE APPROVAL CLIENT WRITE ==="
sed -n '120,190p' client/src/approvals/approvalRequestApi.ts
sed -n '145,190p' client/src/approvals/ApprovalsWorkspace.tsx

echo
echo "=== FIND EXECUTION APPROVAL / AUTHORIZATION DURABILITY ==="
git grep -n -I -E \
  'approval_required|approval_id|approval_status|execution.*approv|approved.*execution|execution.*authoriz|buildApprovalArtifact|evaluateExecutionApproval' \
  -- \
  server routes db client/src \
  ':!server/execution/smoke-test-*' \
  | sed -n '1,1200p' || true

echo
echo "=== FIND EXISTING USER-OWNED APPROVAL WRITE MECHANISMS ==="
git grep -n -I -E \
  'approveCanonicalPackage|canonical_approved|approved_by|approved_at|user_actor|actor_id|actor_type|decision.*approve|status.*approved' \
  -- \
  server routes db client/src \
  | sed -n '1,1200p' || true

echo
echo "=== REQUIRED AUTHORITY INVARIANTS ==="
echo "USER_IS_EXECUTION_APPROVAL_AUTHORITY=YES"
echo "MATILDA_MAY_REQUEST_OR_COMPILE_APPROVAL=YES"
echo "MATILDA_MAY_SELF_APPROVE=NO"
echo "CADE_MAY_SELF_APPROVE=NO"
echo "CANONICAL_PACKAGE_APPROVAL_DOES_NOT_IMPLY_EXECUTION_APPROVAL=YES"
echo "EXECUTION_APPROVAL_MUST_BIND_TO_EXACT_ENVELOPE=YES"
echo "EXECUTION_APPROVAL_MUST_BIND_TO_EXACT_SCOPE=YES"
echo "EXECUTION_APPROVAL_MUST_BIND_TO_VERSION_CONTROL_AUTHORIZATION=YES"
echo "EXECUTION_APPROVAL_MUST_BE_FAIL_CLOSED=YES"
echo "EXECUTION_APPROVAL_REPLAY_ACROSS_DIFFERENT_ENVELOPE=PROHIBITED"
echo "PARALLEL_GENERAL_APPROVAL_SYSTEM=PROHIBITED"

echo
echo "=== CLASSIFICATION QUESTIONS ==="
echo "QUESTION_1=DOES_MATILDA_EXECUTION_AUTHORIZATION_ROUTE_CREATE_ONLY_NONAUTHORITATIVE_OR_PLANNING_AUTHORIZATION"
echo "QUESTION_2=DOES_ANY_EXISTING_ROUTE_ACCEPT_EXPLICIT_USER_EXECUTION_APPROVAL"
echo "QUESTION_3=DOES_ANY_EXISTING_STORE_DURABLY_BIND_APPROVAL_ID_TO_ENVELOPE_ID"
echo "QUESTION_4=DOES_ANY_EXISTING_STORE_RECORD_USER_ACTOR_AND_APPROVAL_DECISION"
echo "QUESTION_5=CAN_EXISTING_APPROVAL_INFRASTRUCTURE_BE_REUSED_WITHOUT_CONFLATING_CANONICAL_PACKAGE_APPROVAL_AND_EXECUTION_APPROVAL"
echo "QUESTION_6=IS_A_NEW_EXECUTION_APPROVAL_TABLE_REQUIRED_OR_CAN_AN_EXISTING_GOVERNANCE_STORE_BE_EXTENDED"
echo "QUESTION_7=WHERE_MUST_MODEL_SELF_APPROVAL_BE_BLOCKED"
echo "QUESTION_8=WHAT_IS_THE_MINIMUM_WRITE_SURFACE_REQUIRED_FOR_APPROVAL_REQUIRED_TO_APPROVED"

echo
echo "=== BOUNDARIES ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_PROJECT_REGISTRY_WRITE=YES"
echo "NO_GIT_EFFECT=YES"
echo "NO_REMOTE_WRITE=YES"

echo
echo "=== NEXT DECISION ==="
echo "NEXT_ACTION=DETERMINE_EXACT_REUSE_BOUNDARY_AND_SMALLEST_EXECUTION_APPROVAL_WRITE_UNIT_FROM_REPOSITORY_EVIDENCE"
echo "IMPLEMENTATION_AUTHORIZED=NO"
