#!/usr/bin/env bash
set -euo pipefail

cd "/Users/marcela-dev/Projects/motherboard-systems-hq-clean"

BRANCH="feature/support-source-references-runtime"
BASELINE="39a2c8492"

git fetch origin "$BRANCH"

test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$BASELINE"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$BASELINE"
test -z "$(git diff --cached --name-only)"

echo "===== ATLAS UNIFIED PRE-EXECUTION OBSERVATION — CLASSIFICATION ====="
echo "MODE=READ_ONLY_COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CHECKPOINT=$(git rev-parse HEAD)"

echo
echo "===== CLASSIFICATION ====="
echo "PREEXECUTION_OBSERVATIONS_PARALLEL_TO_EXECUTION_EVENTS=YES"
echo "PREEXECUTION_AS_EXECUTION_EVENT=NO"
echo "AUTHORITY_STATE_COLLAPSE=FORBIDDEN"
echo "SOURCE_TYPE_ERASURE=FORBIDDEN"
echo "DIRECT_CAUSAL_GRAPH_REUSE=NOT_ESTABLISHED_SAFE"
echo "DIRECT_SESSION_CLUSTER_REUSE=NOT_ESTABLISHED_SAFE"

echo
echo "===== AUTHORITY MODEL ====="
echo "IEL_AUTHORITY=MATILDA_AUTHORED_INTERPRETIVE_EVIDENCE"
echo "LIVING_DRAFT_AUTHORITY=NON_AUTHORITATIVE"
echo "PENDING_APPROVAL_AUTHORITY=PENDING_TRANSITION"
echo "CANONICAL_PACKAGE_AUTHORITY=AUTHORITATIVE"

echo
echo "===== MINIMUM SAFE COMMON ENVELOPE ====="
echo "COMMON_FIELDS=SOURCE_KIND_AUTHORITY_STATUS_PROJECT_ID_CONVERSATION_ID_LINEAGE_ID_OBSERVED_AT"
echo "SOURCE_SPECIFIC_PAYLOADS=MUST_REMAIN_TYPED_AND_DISTINCT"
echo "SOURCE_TIMESTAMPS=MUST_REMAIN_PRESERVED"
echo "CHRONOLOGY_MUST_NOT_IMPLY_CAUSATION=YES"

echo
echo "===== NEXT UNIT ====="
echo "NEXT_UNIT=ATLAS_TYPED_PREEXECUTION_OBSERVATION_AGGREGATOR"
echo "PURPOSE=COMBINE_EXISTING_IEL_LIVING_DRAFT_PENDING_APPROVAL_AND_CANONICAL_OBSERVATIONS"
echo "DISCRIMINATED_UNION=YES"
echo "PROJECT_SCOPE=FAIL_CLOSED"
echo "AUTHORITY_STATUS=PRESERVED"
echo "CONVERSATION_IDENTITY=PRESERVED"
echo "LINEAGE_IDENTITY=PRESERVED"
echo "DETERMINISTIC_CHRONOLOGY=YES"
echo "EXECUTION_REASONER_CHANGE=NO"
echo "EXECUTION_EVENT_CHANGE=NO"
echo "NEW_MODEL_CALL=NO"
echo "NEW_PERSISTENCE=NO"
echo "ROUTE_CHANGE=NO"
echo "MATILDA_CHANGE=NO"

echo
echo "===== AUTHORIZATION GATE ====="
echo "IMPLEMENTATION_READINESS=READY_FOR_EXPLICIT_AUTHORIZATION"
echo "AUTHORIZATION_REQUIRED=YES"
echo "EXACT_AUTHORIZATION=I authorize implementation of the minimum Atlas typed pre-execution observation aggregator."

echo
echo "===== SAFETY BOUNDARY ====="
echo "DO_NOT_WIRE_PREEXECUTION_INTO_EXECUTION_CAUSAL_GRAPH=YES"
echo "DO_NOT_WIRE_PREEXECUTION_INTO_EXECUTION_SESSION_CLUSTER=YES"
echo "DO_NOT_COLLAPSE_AUTHORITY=YES"
echo "DOGFOOD_CLEANUP=FROZEN"
echo "IMPLEMENTATION=NONE"

echo
echo "===== WORKTREE ====="
git status --short
