#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY OPERATIONAL PACKAGE AUTHORITY PERSISTENCE SCHEMA AND UNIT ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PROJECT_BOUND_HANDOFF"
echo "RUNTIME_CONTRACT_COMMIT=230c09fa"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== ESTABLISHED CONTRACT ==="
echo "AUTHORITY_NAME=OPERATIONAL_PACKAGE_AUTHORITY"
echo "AUTHORITY_SCOPE=PROJECT_SCOPED"
echo "AUTHORITATIVE_BINDING=project_id+package_id+package_version"
echo "ONE_ACTIVE_OPERATIONAL_PACKAGE_PER_PROJECT=YES"
echo "EXPLICIT_SELECTION_REQUIRED=YES"
echo "SUCCESSOR_VERSION_AUTO_ACTIVATION=NO"
echo "MISSION_PACKAGE_PROJECTION_REQUIRED_BEFORE_SELECTION=YES"
echo "MISSION_READ_IS_CONSUMER_NOT_OWNER=YES"
echo "MISSION_CONTROL_IS_CONSUMER_NOT_OWNER=YES"

echo
echo "=== EXISTING DATABASE PRECEDENTS ==="
sqlite3 -header -column db/main.db "
SELECT name, sql
FROM sqlite_master
WHERE type = 'table'
  AND name IN (
    'project_registry',
    'matilda_active_conversation_context',
    'matilda_canonical_packages',
    'governance_packages'
  )
ORDER BY name;
"

echo
echo "=== REQUIRED CANONICAL COMPOSITE SUPPORT ==="
sqlite3 -header -column db/main.db "
PRAGMA index_list(matilda_canonical_packages);
"

echo
echo "=== MINIMUM PERSISTENCE SCHEMA ==="
echo "TABLE_NAME=operational_package_authority"
echo "PRIMARY_KEY=project_id"
echo "FIELDS_REQUIRED=project_id+package_id+package_version+selected_at"
echo "PROJECT_ID_NULLABLE=NO"
echo "PACKAGE_ID_NULLABLE=NO"
echo "PACKAGE_VERSION_NULLABLE=NO"
echo "SELECTED_AT_NULLABLE=NO"
echo "FOREIGN_KEY_PROJECT=project_registry(project_id)"
echo "FOREIGN_KEY_EXACT_CANONICAL_IDENTITY=(project_id,package_id,package_version)->matilda_canonical_packages(project_id,package_id,package_version)"
echo "CANONICAL_COMPOSITE_UNIQUE_INDEX_REQUIRED=YES"
echo "GENERAL_HISTORY_TABLE_REQUIRED=NO"
echo "AUDIT_HISTORY_BEYOND_CURRENT_selected_at=NOT_REQUIRED_BY_MINIMUM_CONTRACT"
echo "ONE_ROW_PER_PROJECT=YES"

echo
echo "=== WRITE UNIT ==="
echo "UNIT_NAME=selectOperationalPackageForProject"
echo "INPUT=project_id+package_id+package_version"
echo "PRECONDITION_REGISTERED_PROJECT=YES"
echo "PRECONDITION_EXACT_CANONICAL_PACKAGE_EXISTS=YES"
echo "PRECONDITION_CANONICAL_STATUS_canonical_approved=YES"
echo "PRECONDITION_PROJECT_PACKAGE_OWNERSHIP_MATCH=YES"
echo "PRECONDITION_EXACT_MISSION_PACKAGE_PROJECTION_EXISTS=YES"
echo "SAME_BINDING=IDEMPOTENT_SUCCESS"
echo "DIFFERENT_BINDING=EXPLICIT_REPLACEMENT"
echo "IMPLICIT_NEWEST_SELECTION=NO"
echo "CALLER_SEMANTIC_FIELDS_ACCEPTED=NO"

echo
echo "=== READ UNIT ==="
echo "UNIT_NAME=getOperationalPackageForProject"
echo "INPUT=project_id"
echo "OUTPUT=project_id+package_id+package_version+selected_at_OR_NULL"
echo "READ_MUTATION=NO"
echo "READ_NEWEST_INFERENCE=NO"
echo "READ_DELEGATION_INFERENCE=NO"
echo "READ_UI_SELECTION_INFERENCE=NO"

echo
echo "=== FAILURE CONTRACT ==="
echo "MISSING_PROJECT=FAIL_CLOSED"
echo "MISSING_CANONICAL_PACKAGE=FAIL_CLOSED"
echo "NON_APPROVED_CANONICAL_PACKAGE=FAIL_CLOSED"
echo "PROJECT_PACKAGE_OWNERSHIP_MISMATCH=FAIL_CLOSED"
echo "MISSING_MISSION_PACKAGE_PROJECTION=FAIL_CLOSED"
echo "FAILED_WRITE_MUTATES_CANONICAL_PACKAGE=NO"
echo "FAILED_WRITE_MUTATES_MISSION_PACKAGE_PROJECTION=NO"
echo "FAILED_WRITE_CREATES_DELEGATION=NO"
echo "FAILED_WRITE_CONFERS_EXECUTION_AUTHORITY=NO"

echo
echo "=== BOUNDED IMPLEMENTATION UNIT ==="
echo "SCHEMA_CHANGE_REQUIRED=YES"
echo "MIGRATION_REQUIRED=YES"
echo "NEW_PERSISTENCE_ADAPTER_REQUIRED=YES"
echo "MISSION_READ_CHANGE_REQUIRED_IN_THIS_UNIT=NO"
echo "MISSION_CONTROL_CHANGE_REQUIRED_IN_THIS_UNIT=NO"
echo "DELEGATION_CHANGE_REQUIRED=NO"
echo "VALIDATION_CHANGE_REQUIRED=NO"
echo "ROUTING_CHANGE_REQUIRED=NO"
echo "ASSIGNMENT_CHANGE_REQUIRED=NO"
echo "EXECUTION_CHANGE_REQUIRED=NO"
echo "AUTHORIZED_IMPLEMENTATION_UNIT_NOT_YET_GRANTED=YES"

echo
echo "=== REQUIRED VALIDATION IF AUTHORIZED ==="
echo "VALIDATION_1=TYPECHECK"
echo "VALIDATION_2=MIGRATION_APPLIES_CLEANLY"
echo "VALIDATION_3=VALID_EXACT_BINDING_ACCEPTED"
echo "VALIDATION_4=WRONG_PROJECT_BINDING_REJECTED"
echo "VALIDATION_5=NON_APPROVED_PACKAGE_REJECTED"
echo "VALIDATION_6=MISSING_MISSION_PROJECTION_REJECTED"
echo "VALIDATION_7=SAME_BINDING_IDEMPOTENT"
echo "VALIDATION_8=EXPLICIT_REPLACEMENT_UPDATES_ONLY_PROJECT_AUTHORITY_ROW"
echo "VALIDATION_9=SUCCESSOR_VERSION_DOES_NOT_AUTO_ACTIVATE"
echo "VALIDATION_10=DELEGATION_STATE_UNCHANGED"
echo "VALIDATION_11=EXECUTION_STATE_UNCHANGED"

echo
echo "=== DESIGN READINESS ==="
echo "PERSISTENCE_SCHEMA_DEFINED=YES"
echo "WRITE_UNIT_DEFINED=YES"
echo "READ_UNIT_DEFINED=YES"
echo "FAILURE_CONTRACT_DEFINED=YES"
echo "BOUNDARY_NON_ESCALATION_DEFINED=YES"
echo "MISSION_READ_INTEGRATION_DEFERRED_TO_LATER_UNIT=YES"
echo "PROJECT_BOUND_HANDOFF_IMPLEMENTATION_STARTED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=PRESENT_SEPARATE_IMPLEMENTATION_AUTHORIZATION_GATE_FOR_OPERATIONAL_PACKAGE_AUTHORITY_PERSISTENCE_AND_WRITE_READ_ADAPTER_ONLY"
