#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY CADE LOCAL COMMIT PATCH SET AND PROVENANCE CONTRACT ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "LOCAL_COMMIT_IMPLEMENTATION_AUTHORIZED=NO"
echo "REMOTE_PUSH_IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="42c8feef7"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== ESTABLISHED EXECUTION SURFACE FACTS ==="
echo "CADE_EXECUTOR_EXISTS=YES"
echo "CADE_EXECUTOR_CURRENT_ACTIONS=create_file,update_file,delete_file"
echo "CADE_EFFECT_MODULE_EXISTS=YES"
echo "CADE_PERSISTENT_EVENT_PATH_EXISTS=YES"
echo "EXECUTION_EVENT_AFFECTED_FILES_EXISTS=YES"
echo "ARGUMENT_ARRAY_GIT_PROCESS_PRECEDENT_EXISTS=YES"
echo "ENVELOPE_EXPECTED_HEAD_EXISTS=YES"
echo "ENVELOPE_ALLOWED_PATHS_EXISTS=YES"
echo "APPROVAL_VERSION_CONTROL_AUTHORIZATION_EXISTS=YES"

echo
echo "=== CRITICAL AUTHORITY GAP ==="
echo "APPROVAL_GATE_CURRENT_PHASE=governed_planning_only"
echo "APPROVAL_GATE_CURRENT_COMMIT_AUTHORIZED_OUTPUT=false"
echo "APPROVAL_GATE_CURRENT_PUSH_AUTHORIZED_OUTPUT=false"
echo "CADE_EXECUTOR_RECEIVES_ENVELOPE=NO"
echo "CADE_EXECUTOR_RECEIVES_APPROVAL_ARTIFACT=NO"
echo "CADE_EXECUTOR_RECEIVES_GOVERNED_VERSION_CONTROL_AUTHORIZATION=NO"
echo "DIRECT_ROUTE_CAN_CALL_CADE_EXECUTOR=YES"
echo "LOCAL_COMMIT_ACTION_SAFE_TO_ADD_DIRECTLY_TO_EXISTING_EXECUTOR=NO"
echo "REASON=EXISTING_EXECUTOR_CALL_SURFACE_DOES_NOT_PROVE_GOVERNED_COMMIT_AUTHORITY"

echo
echo "=== REQUIRED ARCHITECTURAL BOUNDARY ==="
echo "LOCAL_COMMIT_MUST_NOT_BE_REACHABLE_FROM_UNGOVERNED_GENERIC_CADE_ROUTE=YES"
echo "LOCAL_COMMIT_MUST_REQUIRE_GOVERNED_ENVELOPE=YES"
echo "LOCAL_COMMIT_MUST_REQUIRE_VALIDATED_APPROVAL_RESULT=YES"
echo "LOCAL_COMMIT_MUST_REQUIRE_COMMIT_AUTHORIZED_TRUE=YES"
echo "LOCAL_COMMIT_MUST_NOT_REQUIRE_GENERIC_MUTATION_AUTHORITY=YES"
echo "LOCAL_COMMIT_MUST_NOT_REQUIRE_GENERIC_SHELL_AUTHORITY=YES"
echo "LOCAL_COMMIT_MUST_NOT_IMPLY_PUSH_AUTHORITY=YES"
echo "PUSH_REMAINS_SEPARATE_SUCCESSOR_EFFECT=YES"

echo
echo "=== PROPOSED PATCH OWNERSHIP ==="
echo "PATCH_1=NEW_NARROW_CADE_VERSION_CONTROL_EFFECT_MODULE"
echo "PATCH_2=NEW_GOVERNED_LOCAL_COMMIT_ADAPTER_OR_EXECUTOR_ENTRYPOINT"
echo "PATCH_3=NARROW_EXECUTION_EVENT_TYPE_EXTENSION_IF_REQUIRED"
echo "PATCH_4=LOCAL_COMMIT_SMOKE_TEST"
echo "PATCH_5=APPROVAL_GATE_PHASE_TRANSITION_ONLY_IF_SEPARATELY_AUTHORIZED"
echo "EXISTING_GENERIC_CADE_ROUTE_CHANGE=NOT_RECOMMENDED"
echo "EXISTING_FILE_EFFECT_SEMANTICS_CHANGE=NO"
echo "REMOTE_PUSH_EFFECT=NO"

echo
echo "=== LOCAL COMMIT EFFECT INPUT CONTRACT ==="
echo "INPUT_REPO_PATH=REQUIRED"
echo "INPUT_BRANCH=REQUIRED"
echo "INPUT_EXPECTED_HEAD=REQUIRED"
echo "INPUT_ALLOWED_PATHS=REQUIRED"
echo "INPUT_COMMIT_MESSAGE=REQUIRED"
echo "INPUT_APPROVAL_ID=REQUIRED"
echo "INPUT_ENVELOPE_ID=REQUIRED"
echo "INPUT_EXECUTION_ID=REQUIRED"
echo "INPUT_COMMIT_AUTHORIZED_TRUE=REQUIRED"
echo "INPUT_PUSH_AUTHORIZED=IGNORED_FOR_LOCAL_COMMIT"
echo "INPUT_GENERIC_SHELL_AUTHORIZED=NOT_REQUIRED"

echo
echo "=== FAIL-CLOSED PRE-EFFECT CONTRACT ==="
echo "CHECK_REPO_PATH_RESOLVES_TO_EXPECTED_GIT_ROOT=REQUIRED"
echo "CHECK_CURRENT_HEAD_EQUALS_EXPECTED_HEAD=REQUIRED"
echo "CHECK_CURRENT_BRANCH_EQUALS_AUTHORIZED_BRANCH=REQUIRED"
echo "CHECK_TRACKED_DIRTY_PATHS_SUBSET_OF_ALLOWED_PATHS=REQUIRED"
echo "CHECK_PREEXISTING_STAGED_PATHS_SUBSET_OF_ALLOWED_PATHS=REQUIRED"
echo "CHECK_COMMIT_AUTHORIZED_TRUE=REQUIRED"
echo "CHECK_APPROVAL_ID_PRESENT=REQUIRED"
echo "CHECK_ENVELOPE_ID_PRESENT=REQUIRED"
echo "ANY_FAILURE_BEFORE_STAGING=NO_GIT_MUTATION"

echo
echo "=== BOUNDED GIT PROCESS CONTRACT ==="
echo "PROCESS_API=ARGUMENT_ARRAY_ONLY"
echo "SHELL_FALSE=REQUIRED"
echo "GIT_C_FLAG_OR_CWD_BOUND_REPOSITORY=REQUIRED"
echo "STAGING=EXPLICIT_PATH_ARGUMENTS_ONLY"
echo "GIT_ADD_DOT=PROHIBITED"
echo "GIT_ADD_ALL=PROHIBITED"
echo "GIT_COMMIT_A=PROHIBITED"
echo "FORCE_OPTIONS=PROHIBITED"
echo "REMOTE_OPERATION=PROHIBITED"
echo "COMMIT_MESSAGE_ARGUMENT=EXPLICIT"
echo "ARBITRARY_USER_SHELL_STRING=PROHIBITED"

echo
echo "=== POST-EFFECT VERIFICATION CONTRACT ==="
echo "VERIFY_POST_HEAD_DIFFERS_FROM_PRE_HEAD=REQUIRED"
echo "VERIFY_POST_HEAD_PARENT_EQUALS_EXPECTED_HEAD=REQUIRED"
echo "VERIFY_COMMITTED_PATHS_EQUAL_AUTHORIZED_STAGED_PATHS=REQUIRED"
echo "VERIFY_ACTIVE_BRANCH_UNCHANGED=REQUIRED"
echo "VERIFY_NO_REMOTE_OPERATION_OCCURRED=REQUIRED"

echo
echo "=== PROVENANCE CONTRACT ==="
echo "EVENT_ACTION=commit_changes"
echo "EVENT_PRE_HEAD=REQUIRED"
echo "EVENT_POST_HEAD=REQUIRED"
echo "EVENT_BRANCH=REQUIRED"
echo "EVENT_REPO_PATH=REQUIRED"
echo "EVENT_COMMITTED_FILES=REQUIRED"
echo "EVENT_APPROVAL_ID=REQUIRED"
echo "EVENT_ENVELOPE_ID=REQUIRED"
echo "EVENT_EXECUTION_ID=REQUIRED"
echo "EVENT_COMMIT_MESSAGE=REQUIRED"
echo "EVENT_REMOTE_EFFECT=false"
echo "EVENT_PUSH_EFFECT=false"

echo
echo "=== EVENT SCHEMA CLASSIFICATION ==="
echo "CURRENT_EVENT_SCHEMA_SUPPORTS_ACTION=YES"
echo "CURRENT_EVENT_SCHEMA_SUPPORTS_AFFECTED_FILES=YES"
echo "CURRENT_EVENT_SCHEMA_SUPPORTS_GENERIC_INPUT_OUTPUT=YES"
echo "PRE_HEAD_POST_HEAD_CAN_BE_RECORDED_IN_INPUT_OUTPUT=YES"
echo "EVENT_TYPE_EXTENSION_REQUIRED_FOR_FIRST_UNIT=NO"
echo "RECOMMEND_SCHEMA_EXPANSION_BEFORE_FIRST_EFFECT=NO"
echo "RATIONALE=USE_EXISTING_GENERIC_INPUT_OUTPUT_PROVENANCE_WITHOUT_UNNECESSARY_ATLAS_SCHEMA_CHANGE"

echo
echo "=== APPROVAL GATE BLOCKER ==="
echo "CURRENT_GATE_ALWAYS_FORCES_COMMIT_AUTHORIZED_FALSE=YES"
echo "CURRENT_GATE_ALWAYS_FORCES_PUSH_AUTHORIZED_FALSE=YES"
echo "LOCAL_COMMIT_EFFECT_IMPLEMENTABLE_BEHIND_CURRENT_GATE=NO"
echo "NEXT_REQUIRED_DECISION=DEFINE_NARROW_VERSION_CONTROL_EXECUTION_PHASE_TRANSITION"
echo "GENERIC_MUTATION_ENABLEMENT_REQUIRED=NO"
echo "GENERIC_SHELL_ENABLEMENT_REQUIRED=NO"
echo "AUTONOMOUS_EXECUTION_ENABLEMENT_REQUIRED=NO"

echo
echo "=== FAILURE CONTAINMENT ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_APPROVAL_GATE_EDIT=YES"
echo "NO_CADE_EXECUTOR_EDIT=YES"
echo "NO_GIT_EFFECT_EXECUTED=YES"
echo "NO_REMOTE_WRITE=YES"
echo "NO_AUTHORITY_EXPANSION=YES"

echo
echo "=== CLASSIFICATION ==="
echo "LOCAL_COMMIT_EFFECT_SHAPE=SUFFICIENTLY_CLASSIFIED"
echo "PROVENANCE_PATH=EXISTING_EXECUTION_EVENT_STORE"
echo "GENERIC_CADE_EXECUTOR_DIRECT_EXTENSION=REJECTED_FOR_FIRST_UNIT"
echo "BLOCKER=NARROW_GOVERNED_COMMIT_AUTHORITY_MUST_EXIST_BEFORE_EFFECT_IMPLEMENTATION"
echo "NEXT_ACTION=CLASSIFY_NARROW_VERSION_CONTROL_APPROVAL_GATE_TRANSITION_WITHOUT_ENABLING_GENERIC_MUTATION_OR_SHELL_AUTHORITY"
