#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY AND AUTHORIZE LOCAL COMMIT EFFECT UNIT ==="
echo "MODE=EXECUTION"
echo "APPROVAL_GATE_UNIT=CLOSED"
echo "LOCAL_COMMIT_EFFECT_IMPLEMENTATION=AUTHORIZED_BOUNDED_UNIT_ONLY"
echo "REMOTE_PUSH_EFFECT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="278095949"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== CLOSED PRECONDITION ==="
echo "APPROVAL_GATE_COMMIT=5fa936928"
echo "APPROVAL_GATE_CLOSURE_RECORD=278095949"
echo "COMMIT_AUTHORITY_CAN_BE_TRUE=YES"
echo "PUSH_AUTHORITY_REMAINS_FALSE=YES"
echo "GENERIC_MUTATION_AUTHORITY_REMAINS_FALSE=YES"
echo "GENERIC_SHELL_AUTHORITY_REMAINS_FALSE=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_REMAINS_FALSE=YES"

echo
echo "=== AUTHORIZED FIRST EFFECT UNIT ==="
echo "CAPABILITY=GOVERNED_LOCAL_GIT_COMMIT_ONLY"
echo "OWNER=CADE"
echo "REMOTE_EFFECT=NO"
echo "PUSH=NO"
echo "GENERIC_SHELL=NO"
echo "GENERIC_MUTATION_AUTHORITY=NO"
echo "AUTONOMOUS_EXECUTION=NO"

echo
echo "=== AUTHORIZED PATCH SURFACES ==="
echo "FILE_1=NEW server/cade/cade-version-control-effects.ts"
echo "FILE_2=NEW server/execution/cade-governed-commit-adapter.mjs_or_ts"
echo "FILE_3=NEW smoke test for governed local commit"
echo "FILE_4=ONLY_IF_REQUIRED server/cade/cade-event-wrapper.ts"
echo "GENERIC_CADE_EXECUTOR_CHANGE=PROHIBITED"
echo "GENERIC_CADE_ROUTE_CHANGE=PROHIBITED"
echo "APPROVAL_GATE_CHANGE=PROHIBITED"
echo "EXECUTION_SWITCH_CHANGE=PROHIBITED"
echo "GOVERNANCE_VALIDATOR_CHANGE=PROHIBITED"
echo "EVENT_SCHEMA_CHANGE=PROHIBITED_UNLESS_EXISTING_INPUT_OUTPUT_PROVENANCE_PROVES_INSUFFICIENT"

echo
echo "=== REQUIRED EFFECT INPUT ==="
echo "repo_path=REQUIRED"
echo "branch=REQUIRED"
echo "expected_head=REQUIRED"
echo "allowed_paths=REQUIRED"
echo "commit_message=REQUIRED"
echo "approval_id=REQUIRED"
echo "envelope_id=REQUIRED"
echo "execution_id=REQUIRED"
echo "commit_authorized=true_REQUIRED"
echo "push_authorized=false_REQUIRED"

echo
echo "=== REQUIRED PRE-EFFECT CHECKS ==="
echo "CHECK_1=RESOLVE_REPO_ROOT"
echo "CHECK_2=VERIFY_REPO_ROOT_EQUALS_AUTHORIZED_REPO_PATH"
echo "CHECK_3=VERIFY_HEAD_EQUALS_EXPECTED_HEAD"
echo "CHECK_4=VERIFY_BRANCH_EQUALS_AUTHORIZED_BRANCH"
echo "CHECK_5=VERIFY_TRACKED_DIRTY_PATHS_SUBSET_OF_ALLOWED_PATHS"
echo "CHECK_6=VERIFY_PREEXISTING_STAGED_PATHS_SUBSET_OF_ALLOWED_PATHS"
echo "CHECK_7=VERIFY_COMMIT_AUTHORIZED_TRUE"
echo "CHECK_8=VERIFY_PUSH_AUTHORIZED_FALSE"

echo
echo "=== REQUIRED PROCESS MODEL ==="
echo "API=execFile_or_execFileSync"
echo "COMMAND=git"
echo "ARGUMENT_ARRAY_ONLY=YES"
echo "shell=false"
echo "cwd=AUTHORIZED_REPO_PATH"
echo "ARBITRARY_SHELL_STRING=PROHIBITED"
echo "git_add_dot=PROHIBITED"
echo "git_add_all=PROHIBITED"
echo "git_commit_a=PROHIBITED"
echo "force=PROHIBITED"
echo "force_with_lease=PROHIBITED"
echo "REMOTE_COMMAND=PROHIBITED"

echo
echo "=== REQUIRED STAGING CONTRACT ==="
echo "STAGE_EXPLICIT_ALLOWED_CHANGED_PATHS_ONLY=YES"
echo "VERIFY_STAGED_SET_AFTER_ADD=YES"
echo "STAGED_SET_MUST_EQUAL_AUTHORIZED_COMMIT_SET=YES"
echo "UNRELATED_UNTRACKED_FILES_MAY_EXIST=YES"
echo "UNRELATED_UNTRACKED_FILES_MUST_NEVER_BE_STAGED=YES"
echo "UNAUTHORIZED_TRACKED_DIRTY_FILE=FAIL_CLOSED"

echo
echo "=== REQUIRED COMMIT CONTRACT ==="
echo "PRE_HEAD=CAPTURE"
echo "git_commit=EXPLICIT_MESSAGE_ARGUMENT"
echo "POST_HEAD=CAPTURE"
echo "POST_HEAD_MUST_DIFFER_FROM_PRE_HEAD=YES"
echo "POST_HEAD_PARENT_MUST_EQUAL_PRE_HEAD=YES"
echo "ACTIVE_BRANCH_MUST_REMAIN_AUTHORIZED_BRANCH=YES"
echo "COMMITTED_PATHS_MUST_EQUAL_STAGED_AUTHORIZED_PATHS=YES"

echo
echo "=== REQUIRED PROVENANCE ==="
echo "EVENT_ACTION=commit_changes"
echo "EVENT_INPUT.repo_path=YES"
echo "EVENT_INPUT.branch=YES"
echo "EVENT_INPUT.expected_head=YES"
echo "EVENT_INPUT.approval_id=YES"
echo "EVENT_INPUT.envelope_id=YES"
echo "EVENT_INPUT.execution_id=YES"
echo "EVENT_OUTPUT.pre_head=YES"
echo "EVENT_OUTPUT.post_head=YES"
echo "EVENT_OUTPUT.committed_files=YES"
echo "EVENT_OUTPUT.commit_message=YES"
echo "EVENT_OUTPUT.remote_effect=false"
echo "EVENT_OUTPUT.push_effect=false"
echo "EVENT_affectedFiles=COMMITTED_FILES"

echo
echo "=== REQUIRED TEST CASES ==="
echo "TEST_1=VALID_AUTHORIZED_LOCAL_COMMIT_SUCCEEDS_IN_TEMP_REPO"
echo "TEST_2=HEAD_MISMATCH_FAILS_BEFORE_STAGING"
echo "TEST_3=BRANCH_MISMATCH_FAILS_BEFORE_STAGING"
echo "TEST_4=UNAUTHORIZED_TRACKED_CHANGE_FAILS_CLOSED"
echo "TEST_5=UNRELATED_UNTRACKED_FILE_IS_NOT_STAGED"
echo "TEST_6=PREEXISTING_UNAUTHORIZED_STAGED_FILE_FAILS_CLOSED"
echo "TEST_7=COMMIT_AUTHORIZED_FALSE_FAILS_CLOSED"
echo "TEST_8=PUSH_AUTHORIZED_TRUE_FAILS_CLOSED"
echo "TEST_9=POST_HEAD_PARENT_EQUALS_EXPECTED_HEAD"
echo "TEST_10=NO_REMOTE_OPERATION"
echo "TEST_11=NO_GENERIC_SHELL"
echo "TEST_12=NO_GENERIC_CADE_ROUTE_REACHABILITY"

echo
echo "=== IMPLEMENTATION SAFETY ==="
echo "SMOKE_TEST_MUST_USE_TEMP_GIT_REPOSITORY=YES"
echo "SMOKE_TEST_MUST_NOT_TOUCH_ACTIVE_PROJECT_HISTORY=YES"
echo "PRODUCTION_LOCAL_COMMIT_EFFECT_MUST_NOT_BE_INVOKED_DURING_VALIDATION=YES"
echo "NO_REMOTE_WRITE_DURING_TESTS=YES"
echo "THREE_FAILED_HYPOTHESIS_RULE=ACTIVE"

echo
echo "=== AUTHORIZATION ==="
echo "LOCAL_COMMIT_EFFECT_UNIT_AUTHORIZED=YES"
echo "AUTHORIZATION_SCOPE=NEW_NARROW_EFFECT_AND_GOVERNED_ADAPTER_PLUS_TESTS_ONLY"
echo "PUSH_EFFECT_AUTHORIZED=NO"
echo "NEXT_ACTION=IMPLEMENT_AND_VALIDATE_GOVERNED_LOCAL_COMMIT_EFFECT_IN_TEMP_REPOSITORY"
