#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY DECISIONS LIST TITLE SOURCE ==="
echo "EXPECTED_HEAD_PREFIX=5436dcb04"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED TITLE SOURCE ==="
echo "DECISION_LIST_COMPONENT=DecisionListItem"
echo "DECISION_LIST_FILE=client/src/approvals/ApprovalsWorkspace.tsx"
echo "PRIMARY_DISPLAY_SOURCE=request.evidence.expected_outcome"
echo "FALLBACK_DISPLAY_SOURCE=request.evidence.interpreted_objective"
echo "TITLE_IS_SEPARATE_PERSISTED_FIELD=NO"
echo "TITLE_IS_CURRENTLY_PRESENTATION_DERIVED=YES"
echo "FULL_EXPECTED_OUTCOME_CURRENTLY_RENDERED_AS_HEADING=YES"
echo "INTERPRETED_OBJECTIVE_CURRENTLY_RENDERED_AS_SUMMARY=YES"

echo
echo "=== OWNERSHIP CLASSIFICATION ==="
echo "AUTHORITATIVE_EXPECTED_OUTCOME_SHOULD_BE_MUTATED_FOR_COMPACTNESS=NO"
echo "AUTHORITATIVE_INTERPRETED_OBJECTIVE_SHOULD_BE_MUTATED_FOR_COMPACTNESS=NO"
echo "DATA_MODEL_CHANGE_REQUIRED=NO"
echo "GENERATION_CONTRACT_CHANGE_REQUIRED=NO"
echo "PACKAGE_SEMANTICS_REOPEN_REQUIRED=NO"
echo "COMPACTNESS_CAN_REMAIN_PRESENTATION_OWNED=YES"

echo
echo "=== SAFE PRESENTATION BOUNDARY ==="
echo "TARGET=DECISION_LIST_ITEM_HEADING_ONLY"
echo "DETAIL_BRIEFING_EXPECTED_OUTCOME_REMAINS_FULL=YES"
echo "SUMMARY_REMAINS_FULL=YES"
echo "PERSISTED_DATA_REMAINS_UNCHANGED=YES"
echo "SEMANTIC_CONTENT_REMAINS_UNCHANGED=YES"
echo "APPROVAL_AUTHORITY_REMAINS_UNCHANGED=YES"
echo "PREFERRED_APPROACH=DERIVE_A_COMPACT_DISPLAY_LABEL_FROM_EXISTING_HEADING_TEXT_AT_RENDER_TIME"
echo "BLIND_CHARACTER_TRUNCATION_PREFERRED=NO"

echo
echo "=== IMPLEMENTATION GATE ==="
echo "UI_CHANGE_AUTHORIZED=NO"
echo "TITLE_GENERATION_CHANGE_AUTHORIZED=NO"
echo "NEXT_ACTION=DESIGN_EXACT_PRESENTATION_ONLY_COMPACT_TITLE_RULE_AND_TEST_BOUNDARY_BEFORE_IMPLEMENTATION_AUTHORIZATION"

git diff --check
git add classify-decisions-list-title-source.sh
git commit -m "Classify decisions list title source"
git push
