#!/usr/bin/env bash
set -euo pipefail

cd "/Users/marcela-dev/Projects/motherboard-systems-hq-clean"

BRANCH="feature/support-source-references-runtime"
BASELINE="956f88774"

git fetch origin "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$BASELINE"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$BASELINE"
test -z "$(git diff --cached --name-only)"

echo "===== ATLAS PRE-EXECUTION OBSERVATION CONTRACT — CLASSIFICATION ====="
echo "MODE=READ_ONLY_COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CHECKPOINT=$(git rev-parse HEAD)"

echo
echo "===== Q1 — OBSERVABLE PRE-EXECUTION FACT CLASSES ====="
echo "OBSERVE_IEL_IDENTITY=YES"
echo "OBSERVE_IEL_INTERPRETATION_EVENT=YES"
echo "OBSERVE_MATILDA_OBSERVATION=YES_AS_MATILDA_AUTHORED_INTERPRETATION"
echo "OBSERVE_INVESTIGATION_LIFECYCLE=YES_AS_MATILDA_AUTHORED_STATE"
echo "OBSERVE_PACKAGE_SEMANTICS=YES_AS_MATILDA_AUTHORED_STATE"
echo "OBSERVE_LIVING_DRAFT=YES_AS_NON_AUTHORITATIVE_DRAFT"
echo "OBSERVE_CANONICAL_PACKAGE=YES_AS_APPROVED_AUTHORITATIVE_STATE"
echo "OBSERVE_APPROVAL_TRANSITION=YES_AS_RECORDED_GOVERNANCE_FACT"

echo
echo "===== Q2 — FACT VS INTERPRETATION ====="
echo "DURABLE_FACTS=IDENTIFIERS_TIMESTAMPS_STATUS_LINEAGE_AUTHORITY_TRANSITIONS"
echo "MATILDA_INTERPRETATION=INTERPRETATION_EVENT_MATILDA_OBSERVATION_INVESTIGATION_LIFECYCLE_PACKAGE_SEMANTICS_CURRENT_INTERPRETATION"
echo "ATLAS_MUST_PRESERVE_SOURCE_AUTHORSHIP=YES"
echo "ATLAS_MUST_NOT_RECAST_INTERPRETATION_AS_OBJECTIVE_FACT=YES"

echo
echo "===== Q3 — IDENTITY ====="
echo "PROJECT_ID=PRESERVE"
echo "CONVERSATION_ID=PRESERVE"
echo "IEL_ENTRY_ID=PRESERVE"
echo "DRAFT_PACKAGE_ID=PRESERVE"
echo "DRAFT_REVISION_ID=PRESERVE_WHEN_PRESENT"
echo "LINEAGE_ID=PRESERVE"
echo "CANONICAL_PACKAGE_ID_AND_VERSION=PRESERVE_WHEN_PRESENT"

echo
echo "===== Q4 — AUTHORITY STATE ====="
echo "LIVING_DRAFT=NON_AUTHORITATIVE"
echo "IEL_INTERPRETATION=MATILDA_AUTHORED_NON_USER_AUTHORITY"
echo "CANONICAL_PACKAGE=AUTHORITATIVE_ONLY_AFTER_APPROVAL"
echo "ATLAS_MUST_NOT_COLLAPSE_DRAFT_AND_CANONICAL=YES"
echo "ATLAS_MUST_NOT_INFER_APPROVAL_FROM_DRAFT_EXISTENCE=YES"

echo
echo "===== Q5 — INVESTIGATION LIFECYCLE ====="
echo "INVESTIGATION_LIFECYCLE_ATLAS_VISIBLE=YES"
echo "VISIBILITY_CLASS=OBSERVED_MATILDA_AUTHORED_STATE"
echo "ATLAS_LIFECYCLE_AUTHORSHIP=NO"
echo "ATLAS_LIFECYCLE_TRANSITION_AUTHORITY=NO"

echo
echo "===== Q6 — INPUT MODEL ====="
echo "PREEXECUTION_OBSERVATIONS_SHOULD_NOT_BE_EXECUTION_EVENTS=YES"
echo "RECOMMENDED_BOUNDARY=DISTINCT_TYPED_PREEXECUTION_OBSERVATION_INPUT"
echo "EXECUTION_EVENT_TYPE_REUSE=NO"
echo "JOIN_FOR_REASONING=ONLY_AFTER_SOURCE_TYPE_AND_AUTHORITY_ARE_PRESERVED"

echo
echo "===== Q7 — MINIMUM OBSERVATION FIELDS ====="
echo "MINIMUM_FIELDS=OBSERVATION_ID_SOURCE_TYPE_TIMESTAMP_PROJECT_ID_CONVERSATION_ID_LINEAGE_ID_AUTHORITY_STATE_SOURCE_ACTOR_EVENT_TYPE_SOURCE_REFERENCE"
echo "OPTIONAL_SEMANTIC_PAYLOAD=SOURCE_TYPED_INTERPRETATION_OR_LIFECYCLE_OR_PACKAGE_STATE"
echo "CAUSAL_REASONING_REQUIRES_SOURCE_IDENTITY=YES"
echo "TRAJECTORY_REASONING_REQUIRES_CHRONOLOGY=YES"

echo
echo "===== Q8 — READ ONLY BRIDGE ====="
echo "READ_ONLY_BRIDGE_FEASIBLE_FROM_CURRENT_EVIDENCE=YES"
echo "SOURCE_STATE_MUTATION_REQUIRED=NO"
echo "DATABASE_SCHEMA_CHANGE_ESTABLISHED_AS_REQUIRED=NO"
echo "MATILDA_WRITE_PATH_CHANGE_ESTABLISHED_AS_REQUIRED=NO"

echo
echo "===== Q9 — EXISTING ATLAS REASONER COMPATIBILITY ====="
echo "DIRECT_SAFE_CONSUMPTION_BY_CURRENT_EXECUTION_EVENT_REASONER=NOT_ESTABLISHED"
echo "CURRENT_REASONER_EXPECTS_EXECUTION_EVENT_SEMANTICS=YES"
echo "CASTING_PREEXECUTION_STATE_TO_EXECUTION_EVENT=PROHIBITED"
echo "ADAPTER_OR_TYPED_UNIFIED_OBSERVATION_BOUNDARY_REQUIRES_INVESTIGATION=YES"

echo
echo "===== Q10 — REQUIRED REGRESSION CONTRACT ====="
echo "TEST_1=READ_ONLY_SOURCE_ACCESS"
echo "TEST_2=PROJECT_IDENTITY_PRESERVED"
echo "TEST_3=CONVERSATION_IDENTITY_PRESERVED"
echo "TEST_4=LINEAGE_PRESERVED"
echo "TEST_5=MATILDA_AUTHORSHIP_PRESERVED"
echo "TEST_6=DRAFT_NON_AUTHORITY_PRESERVED"
echo "TEST_7=CANONICAL_APPROVAL_AUTHORITY_PRESERVED"
echo "TEST_8=INVESTIGATION_LIFECYCLE_OBSERVED_WITHOUT_ATLAS_AUTHORSHIP"
echo "TEST_9=PREEXECUTION_OBSERVATION_NOT_MISCLASSIFIED_AS_EXECUTION_EVENT"
echo "TEST_10=EXISTING_EXECUTION_EVENT_BEHAVIOR_UNCHANGED"
echo "TEST_11=SOURCE_DATABASE_UNCHANGED_BY_ATLAS_READ"
echo "TEST_12=CHRONOLOGY_AND_SOURCE_REFERENCES_PRESERVED"

echo
echo "===== MINIMUM CONTRACT ====="
echo "CONTRACT_NAME=ATLAS_NON_AUTHORITATIVE_PREEXECUTION_OBSERVATION"
echo "SOURCE_OF_TRUTH=EXISTING_DURABLE_MATILDA_AND_GOVERNANCE_STATE"
echo "ATLAS_ROLE=READ_OBSERVE_DERIVE"
echo "ATLAS_WRITE_AUTHORITY=NONE"
echo "ATLAS_APPROVAL_AUTHORITY=NONE"
echo "ATLAS_EXECUTION_AUTHORITY=NONE"
echo "SOURCE_AUTHORSHIP_REQUIRED=YES"
echo "SOURCE_TYPE_REQUIRED=YES"
echo "AUTHORITY_STATE_REQUIRED=YES"
echo "IDENTITY_AND_LINEAGE_REQUIRED=YES"
echo "EXECUTION_EVENT_SEMANTICS_MUST_REMAIN_DISTINCT=YES"

echo
echo "===== CORRIDOR STATUS ====="
echo "ATLAS_PREEXECUTION_READ_MODEL_BOUNDARY=CLOSED"
echo "ATLAS_PREEXECUTION_OBSERVATION_CONTRACT=CLOSED"
echo "IMPLEMENTATION_READINESS=CONTRACT_DEFINED_BUT_IMPLEMENTATION_NOT_AUTHORIZED"
echo "NEXT_CORRIDOR=ATLAS_PREEXECUTION_TYPED_READ_MODEL_ADAPTER_BOUNDARY"
echo "NEXT_ACTION=INVESTIGATE_MINIMUM_TYPED_READ_MODEL_AND_INTEGRATION_SEAM_WITHOUT_IMPLEMENTATION"

echo
echo "===== SAFETY BOUNDARY ====="
echo "IMPLEMENTATION=NO"
echo "DATABASE_CHANGE=NO"
echo "MATILDA_AUTHORITY_CHANGE=NO"
echo "GOVERNANCE_AUTHORITY_CHANGE=NO"
echo "EXECUTION_AUTHORITY_CHANGE=NO"
echo "PRODUCTION_GENERATION_POLICY_CHANGE=NO"
echo "DOGFOOD_CLEANUP=FROZEN"

echo
echo "===== WORKTREE ====="
git status --short
