#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY MISSION CONTROL BLANK UI BUILD FAILURE ==="
echo "BASELINE_COMMIT=26a48298"
echo "OBSERVED_UI=BLANK_PAGE"
echo "PROJECT_CONTEXT_API=RESTORED"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED BUILD FAILURE ==="
echo "CLIENT_BUILD_STATUS=FAILED"
echo "FAILING_FILE=client/src/shell/MissionDashboardWorkspace.tsx"
echo "FAILURE_CLASS=INVALID_EMPTY_MISSION_PRESENTATION_MODEL"
echo "FIRST_ERROR=owner_null_not_assignable_to_string"
echo "ADDITIONAL_ERROR=EMPTY_MISSION_OBJECT_MISSING_REQUIRED_MISSION_PRESENTATION_FIELDS"
echo "ERROR_COUNT=8"
echo "BLANK_UI_HAS_CONCRETE_CLIENT_BUILD_DEFECT=YES"

echo
echo "=== REQUIRED MODEL CONTRACT ==="
sed -n '1,130p' client/src/mission-control/missionPresentationMapper.ts

echo
echo "=== CURRENT EMPTY-MISSION IMPLEMENTATION ==="
sed -n '350,470p' client/src/shell/MissionDashboardWorkspace.tsx

echo
echo "=== INTRODUCING CHANGE ==="
git log --oneline --all -- client/src/shell/MissionDashboardWorkspace.tsx | head -30
git blame -L 365,410 -- client/src/shell/MissionDashboardWorkspace.tsx || true

echo
echo "=== CLASSIFICATION BOUNDARY ==="
echo "PROJECT_CONTEXT_FAILURE_CURRENT_ROOT_CAUSE=NO"
echo "EXPRESS_RUNTIME_FAILURE_CURRENT_ROOT_CAUSE=NO"
echo "MISSION_PRESENTATION_EMPTY_STATE_IMPLEMENTATION_DEFECT=ESTABLISHED"
echo "MISSION_PRESENTATION_DOMAIN_SEMANTICS_CHANGE_REQUIRED=NO_EVIDENCE"
echo "FIX_SCOPE=EMPTY_STATE_MUST_SATISFY_EXISTING_MissionPresentationModel_CONTRACT"
echo "SPECULATIVE_FIELD_VALUES_ALLOWED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "NEXT_ACTION=DERIVE_VALID_EMPTY_MISSION_PRESENTATION_FROM_EXISTING_MODEL_CONTRACT_AND_MAPPER_SEMANTICS_BEFORE_AUTHORIZING_FIX"
