#!/usr/bin/env bash
set -euo pipefail

cd "/Users/marcela-dev/Projects/motherboard-systems-hq-clean"

BRANCH="feature/support-source-references-runtime"
BASELINE="7e85ab43b"

git fetch origin "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$BASELINE"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$BASELINE"
test -z "$(git diff --cached --name-only)"

echo "===== ATLAS PRE-EXECUTION — TYPED READ MODEL ADAPTER CLASSIFICATION ====="
echo "MODE=READ_ONLY_COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CHECKPOINT=$(git rev-parse HEAD)"

echo
echo "===== ESTABLISHED REPOSITORY EVIDENCE ====="
echo "CURRENT_ATLAS_PRIMARY_INPUT=ExecutionEvent[]"
echo "CURRENT_ATLAS_UNIFIED_ENGINE_INPUT=ExecutionEvent[]"
echo "CURRENT_ATLAS_RECONSTRUCTION_INPUT=ExecutionEvent[]"
echo "CURRENT_ATLAS_NARRATIVE_INPUT=ExecutionEvent[]"
echo "CURRENT_ATLAS_REASONING_MULTI_INPUT_SUPPORT=NO_EVIDENCE_ESTABLISHED"
echo "PREEXECUTION_CAST_TO_EXECUTION_EVENT=PROHIBITED"

echo
echo "===== EXISTING DURABLE PRE-EXECUTION READERS ====="
echo "IEL_READER=listInterpretationEvidenceLedgerEntries"
echo "IEL_EXACT_READER=readInterpretationEvidenceLedgerEntriesByIds"
echo "IEL_PROJECT_SCOPE_SUPPORTED=YES"
echo "IEL_CONVERSATION_SCOPE_SUPPORTED=YES"
echo "IEL_MATILDA_AUTHORSHIP_AVAILABLE=YES"
echo "IEL_INVESTIGATION_LIFECYCLE_AVAILABLE=YES"
echo "IEL_PACKAGE_SEMANTICS_AVAILABLE=YES"
echo "IEL_LINEAGE_REFERENCES_AVAILABLE=YES"
echo "IEL_SUPERSESSION_STATUS_AVAILABLE=YES"
echo "LIVING_DRAFT_PROJECT_READER=ESTABLISHED"
echo "LIVING_DRAFT_DETAIL_READER=ESTABLISHED"
echo "NEW_SOURCE_WRITE_PATH_REQUIRED=NO"

echo
echo "===== Q1 — NARROWEST READ-ONLY INPUT SEAM ====="
echo "NARROWEST_SEAM=BETWEEN_EXISTING_DURABLE_READERS_AND_ATLAS_REASONING"
echo "EXECUTION_EVENT_STORE_CHANGE_REQUIRED=NO"
echo "MATILDA_WORKFLOW_CHANGE_REQUIRED=NO"
echo "IEL_PERSISTENCE_CHANGE_REQUIRED=NO"
echo "PACKAGE_PERSISTENCE_CHANGE_REQUIRED=NO"

echo
echo "===== Q2 — READER REUSE ====="
echo "EXISTING_IEL_READERS_REUSABLE=YES"
echo "EXISTING_LIVING_DRAFT_READERS_REUSABLE=YES"
echo "READER_REUSE_REQUIRES_WRITE_PATH_CHANGE=NO"
echo "CANONICAL_PACKAGE_READER_EXACT_REUSE=REQUIRES_FOCUSED_CONFIRMATION_BEFORE_IMPLEMENTATION"

echo
echo "===== Q3 / Q4 — MINIMUM TYPED OBSERVATION ====="
echo "NEW_TYPED_PREEXECUTION_OBSERVATION_REQUIRED=YES"
echo "TYPE_MUST_BE_DISTINCT_FROM_EXECUTION_EVENT=YES"
echo "MINIMUM_DISCRIMINATOR=sourceType"
echo "SOURCE_TYPE_IEL=interpretation_evidence"
echo "SOURCE_TYPE_LIVING_DRAFT=living_draft"
echo "SOURCE_TYPE_CANONICAL_PACKAGE=canonical_package"
echo "SOURCE_TYPE_APPROVAL_TRANSITION=approval_transition"
echo "INVESTIGATION_LIFECYCLE=IEL_TYPED_PAYLOAD_NOT_SEPARATE_AUTHORSHIP"
echo "PACKAGE_SEMANTICS=IEL_TYPED_PAYLOAD_NOT_SEPARATE_AUTHORSHIP"

echo
echo "===== MINIMUM COMMON OBSERVATION SHAPE ====="
echo "FIELD_1=observationId"
echo "FIELD_2=sourceType"
echo "FIELD_3=timestamp"
echo "FIELD_4=projectId"
echo "FIELD_5=conversationId"
echo "FIELD_6=lineageId_or_lineageReferences"
echo "FIELD_7=authorityState"
echo "FIELD_8=sourceActor"
echo "FIELD_9=eventType"
echo "FIELD_10=sourceReference"
echo "FIELD_11=typedPayload"
echo "SOURCE_AUTHORSHIP_MUST_REMAIN_EXPLICIT=YES"

echo
echo "===== Q5 / Q6 — AUTHORITY AND LINEAGE PROJECTION ====="
echo "AUTHORITY_STATE_PROJECTED_IN_ADAPTER=YES"
echo "AUTHORITY_STATE_REINTERPRETED_BY_ADAPTER=NO"
echo "LIVING_DRAFT_AUTHORITY=NON_AUTHORITATIVE"
echo "IEL_AUTHORITY=MATILDA_AUTHORED_INTERPRETATION"
echo "CANONICAL_PACKAGE_AUTHORITY=AUTHORITATIVE_AFTER_RECORDED_APPROVAL"
echo "DRAFT_CANONICAL_COLLAPSE=PROHIBITED"
echo "LINEAGE_JOIN_BY_DURABLE_IDENTIFIERS_ONLY=YES"
echo "HEURISTIC_LINEAGE_INFERENCE=PROHIBITED"

echo
echo "===== Q7 — READ-ONLY / PROJECT SCOPE ====="
echo "ADAPTER_CAN_REMAIN_READ_ONLY=YES"
echo "ADAPTER_CAN_REMAIN_PROJECT_SCOPED=YES"
echo "SOURCE_DATABASE_MUTATION_REQUIRED=NO"
echo "DATABASE_SCHEMA_CHANGE_ESTABLISHED_AS_REQUIRED=NO"

echo
echo "===== Q8 / Q9 — REASONER INTEGRATION ====="
echo "CURRENT_REASONER_ACCEPTS_EXECUTION_EVENTS_ONLY=YES"
echo "DIRECT_PREEXECUTION_INPUT_TO_CURRENT_REASONER=UNSAFE"
echo "SMALLEST_SAFE_INTEGRATION=PARALLEL_TYPED_PREEXECUTION_OBSERVATION_CHANNEL"
echo "EXECUTION_EVENT_REASONING_PATH_PRESERVED=YES"
echo "UNIFIED_REASONING_OVER_BOTH_SOURCE_CLASSES=SUCCESSOR_REASONER_BOUNDARY_REQUIRING_SEPARATE_DESIGN"
echo "DO_NOT_MODIFY_CAUSAL_GRAPH_TO_FAKE_PREEXECUTION_EVENTS=YES"
echo "DO_NOT_MODIFY_SESSION_CLUSTER_TO_FAKE_PREEXECUTION_EVENTS=YES"
echo "DO_NOT_APPLY_EXECUTION_TEMPORAL_SEMANTICS_BLINDLY=YES"

echo
echo "===== Q10 — MINIMUM PROPOSED IMPLEMENTATION FILE SCOPE ====="
echo "PROPOSED_NEW_FILE_1=server/atlas/atlas-preexecution-observation.ts"
echo "PROPOSED_NEW_FILE_2=server/atlas/atlas-preexecution-read-adapter.ts"
echo "PROPOSED_TEST_FILE=server/atlas/atlas-preexecution-read-adapter.test.ts"
echo "EXISTING_IEL_READER_CHANGE=NOT_ESTABLISHED_AS_REQUIRED"
echo "EXISTING_LIVING_DRAFT_READER_CHANGE=NOT_ESTABLISHED_AS_REQUIRED"
echo "ATLAS_UNIFIED_ENGINE_CHANGE=NOT_AUTHORIZED_AND_NOT_REQUIRED_FOR_FIRST_ADAPTER_UNIT"
echo "EXECUTION_EVENT_TYPE_CHANGE=NO"
echo "EXECUTION_EVENT_STORE_CHANGE=NO"

echo
echo "===== REGRESSION SURFACE ====="
echo "REGRESSION_1=ADAPTER_IS_READ_ONLY"
echo "REGRESSION_2=PROJECT_SCOPE_PRESERVED"
echo "REGRESSION_3=CONVERSATION_IDENTITY_PRESERVED"
echo "REGRESSION_4=SOURCE_AUTHORSHIP_PRESERVED"
echo "REGRESSION_5=AUTHORITY_STATE_PRESERVED"
echo "REGRESSION_6=LINEAGE_PRESERVED"
echo "REGRESSION_7=INVESTIGATION_LIFECYCLE_PRESERVED_AS_MATILDA_AUTHORED"
echo "REGRESSION_8=PACKAGE_SEMANTICS_PRESERVED_AS_MATILDA_AUTHORED"
echo "REGRESSION_9=LIVING_DRAFT_REMAINS_NON_AUTHORITATIVE"
echo "REGRESSION_10=CANONICAL_PACKAGE_NOT_INFERRED_WITHOUT_APPROVAL"
echo "REGRESSION_11=NO_PREEXECUTION_OBSERVATION_BECOMES_EXECUTION_EVENT"
echo "REGRESSION_12=EXISTING_EXECUTION_EVENT_BEHAVIOR_UNCHANGED"

echo
echo "===== IMPLEMENTATION READINESS ====="
echo "TYPED_READ_MODEL_BOUNDARY=ESTABLISHED"
echo "READ_ONLY_ADAPTER_BOUNDARY=ESTABLISHED"
echo "MINIMUM_FIRST_IMPLEMENTATION_UNIT=ESTABLISHED"
echo "FULL_ATLAS_REASONER_INTEGRATION_BOUNDARY=NOT_YET_ESTABLISHED"
echo "IMPLEMENTATION_READINESS=READY_FOR_SEPARATE_MINIMUM_ADAPTER_AUTHORIZATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "===== CORRIDOR STATUS ====="
echo "ATLAS_PREEXECUTION_TYPED_READ_MODEL_ADAPTER_BOUNDARY=CLOSED"
echo "NEXT_CORRIDOR=ATLAS_PREEXECUTION_MINIMUM_READ_ADAPTER_IMPLEMENTATION_GATE"
echo "NEXT_ACTION=REQUEST_EXPLICIT_AUTHORIZATION_BEFORE_IMPLEMENTING_TYPED_READ_MODEL_AND_READ_ONLY_ADAPTER"

echo
echo "===== AUTHORIZATION GATE ====="
echo "EXACT_AUTHORIZATION=I authorize implementation of the minimum Atlas pre-execution typed read model and read-only adapter."

echo
echo "===== SAFETY BOUNDARY ====="
echo "MATILDA_AUTHORITY_CHANGE=NO"
echo "GOVERNANCE_AUTHORITY_CHANGE=NO"
echo "EXECUTION_AUTHORITY_CHANGE=NO"
echo "PRODUCTION_GENERATION_POLICY_CHANGE=NO"
echo "DOGFOOD_CLEANUP=FROZEN"
echo "SOURCE_CHANGE=NONE"
echo "DATABASE_CHANGE=NONE"
echo "STAGING=NONE"
echo "COMMIT=NONE"
echo "PUSH=NONE"

echo
echo "===== WORKTREE ====="
git status --short
