#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY PACKAGE SEMANTICS UNRESOLVED QUESTIONS OWNERSHIP ==="
echo "BASELINE_COMMIT=5189ea3b"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "RECOVERY_POINT=DR_20260826_092915"

echo
echo "=== VERIFIED SELECTION RULE ==="
echo "PACKAGE_SEMANTICS_SELECTION=NEWEST_ELIGIBLE_NON_NULL_ARTIFACT_WITHIN_EXACT_DRAFT_EVIDENCE_SET"
echo "FIELD_BY_FIELD_MERGE=NO"
echo "OLDER_ARTIFACT_NULL_FIELD_BACKFILL=NO"
echo "CROSS_PROJECT_SELECTION=NO"
echo "CROSS_CONVERSATION_SELECTION=NO"

echo
echo "=== INSPECT CURRENT UNRESOLVED QUESTIONS OWNERSHIP ==="
rg -n -C 16 \
  'unresolved_questions|unresolvedQuestions|matilda_observation|investigationLifecycle|createInterpretationEvidenceLedgerEntry|synthesizeLivingDraft' \
  db/matilda-interpretation-runtime.ts \
  db/matilda-draft-synthesis-runtime.ts \
  server/matilda-chat-workflow.ts \
  scripts/utils/ollamaChat.ts \
  2>/dev/null || true

echo
echo "=== OWNERSHIP QUESTIONS ==="
echo "QUESTION_1=IS_IEL_unresolved_questions_CURRENTLY_MATILDA_AUTHORED_OR_WORKFLOW_DERIVED"
echo "QUESTION_2=DOES_CURRENT_OLLAMA_RESPONSE_HAVE_AN_EXISTING_unresolvedQuestions_SOURCE"
echo "QUESTION_3=WOULD_packageSemantics.unresolvedQuestions_CREATE_DUPLICATE_SEMANTIC_OWNERSHIP"
echo "QUESTION_4=CAN_EXISTING_IEL_unresolved_questions_REMAIN_LEGACY_COMPATIBILITY_ONLY_WITHOUT_FEEDING_NEW_STRUCTURED_DRAFT_SEMANTICS"

echo
echo "=== TARGET ARCHITECTURAL PRINCIPLE ==="
echo "ONE_STRUCTURED_SEMANTIC_OWNER_PER_LIVING_DRAFT_FIELD=REQUIRED"
echo "ATOMIC_PACKAGE_SEMANTICS_ARTIFACT_SHOULD_NOT_BE_PARTIALLY_OVERRIDDEN=REQUIRED"
echo "LEGACY_DATA_MUST_NOT_BE_REINTERPRETED_OR_BACKFILLED=REQUIRED"
echo "MATILDA_AUTHORSHIP_MUST_REMAIN_EXPLICIT=REQUIRED"
echo "GENERIC_OR_HEURISTIC_FALLBACK=PROHIBITED"

echo
echo "=== IMPLEMENTATION BOUNDARY ==="
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "OLLAMA_SCHEMA_CHANGE_AUTHORIZED=NO"
echo "IEL_SCHEMA_CHANGE_AUTHORIZED=NO"
echo "WORKFLOW_TRANSPORT_CHANGE_AUTHORIZED=NO"
echo "SYNTHESIS_CHANGE_AUTHORIZED=NO"
echo "NEXT_ACTION=CLASSIFY_SINGLE_OWNER_FOR_UNRESOLVED_QUESTIONS_AND_THEN_DEFINE_FINAL_BOUNDED_IMPLEMENTATION_UNIT"
