#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY CADE VERSION CONTROL CONTRACT EXTENSION ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="e7e786810"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== ESTABLISHED EXISTING CONTRACT ==="
echo "PROJECT_TARGET_REPOSITORY=ESTABLISHED"
echo "PROJECT_TARGET_BRANCH=ESTABLISHED"
echo "MUTATION_SCOPE_ALLOWED_PATHS=ESTABLISHED"
echo "MUTATION_SCOPE_FORBIDDEN_PATHS=ESTABLISHED"
echo "VALIDATION_CONTRACT=ESTABLISHED"
echo "ROLLBACK_CONTRACT=ESTABLISHED"
echo "CADE_EXECUTOR_OWNERSHIP=ESTABLISHED"
echo "EXECUTION_AUTHORIZATION_MODEL=ESTABLISHED"

echo
echo "=== ABSENT REQUIRED VERSION CONTROL CONTRACT ==="
echo "EXPECTED_HEAD_OR_EQUIVALENT=ABSENT"
echo "VERSION_CONTROL_SPECIFIC_AUTHORIZATION=ABSENT"
echo "EXISTING_GENERIC_EXECUTION_AUTHORIZATION_IS_NOT_COMMIT_PUSH_AUTHORIZATION=YES"

echo
echo "=== MINIMUM EXTENSION CLASSIFICATION ==="
echo "EXTENSION_1=REPOSITORY_STATE_PRECONDITION"
echo "EXTENSION_1_REQUIRED_FIELD=EXPECTED_HEAD"
echo "EXTENSION_1_PURPOSE=FAIL_CLOSED_IF_REPOSITORY_MOVED_SINCE_APPROVAL"
echo
echo "EXTENSION_2=VERSION_CONTROL_AUTHORIZATION"
echo "EXTENSION_2_REQUIRED_CAPABILITIES=COMMIT_AND_PUSH"
echo "EXTENSION_2_MUST_BE_NARROW=YES"
echo "EXTENSION_2_MUST_NOT_ENABLE_GENERIC_SHELL=YES"
echo "EXTENSION_2_MUST_NOT_BE_IMPLIED_BY_MUTATION_AUTHORITY=YES"

echo
echo "=== REQUIRED EXECUTION INVARIANTS ==="
echo "CADE_OWNS_GOVERNED_COMMIT_PUSH_EXECUTION=YES"
echo "REPOSITORY_MUST_MATCH_PROJECT_TARGET=YES"
echo "BRANCH_MUST_MATCH_PROJECT_TARGET=YES"
echo "HEAD_MUST_MATCH_EXPECTED_HEAD=YES"
echo "DIRTY_PATHS_MUST_BE_SUBSET_OF_APPROVED_PATHS=YES"
echo "STAGING_APPROVED_PATHS_ONLY=YES"
echo "GIT_ADD_DOT=PROHIBITED"
echo "COMMIT_MESSAGE_MUST_BE_EXPLICIT_BOUNDED_INPUT=YES"
echo "PUSH_REMOTE_MUST_BE_EXPLICIT=YES"
echo "PUSH_BRANCH_MUST_MATCH_APPROVED_BRANCH=YES"
echo "FORCE_PUSH=PROHIBITED"
echo "GENERIC_SHELL_EXECUTION=PROHIBITED"
echo "FAIL_CLOSED_ON_REPOSITORY_DRIFT=YES"
echo "FAIL_CLOSED_ON_UNAPPROVED_DIRTY_FILES=YES"
echo "FAIL_CLOSED_ON_BRANCH_DRIFT=YES"
echo "FAIL_CLOSED_ON_HEAD_DRIFT=YES"

echo
echo "=== ACTION GRANULARITY ==="
echo "COMMIT_AND_PUSH_SHOULD_BE_SEPARATE_GOVERNED_STEPS=YES"
echo "RATIONALE=COMMIT_IS_LOCAL_STATE_TRANSITION_PUSH_IS_EXTERNAL_SIDE_EFFECT"
echo "PUSH_REQUIRES_SUCCESSFUL_GOVERNED_COMMIT=YES"
echo "PUSH_MUST_NOT_RUN_IF_COMMIT_VALIDATION_FAILS=YES"

echo
echo "=== CURRENT DETERMINATION ==="
echo "EXISTING_CONTRACT_SUFFICIENT_WITHOUT_EXTENSION=NO"
echo "SMALLEST_REQUIRED_EXTENSION_COUNT=2"
echo "GENERIC_SHELL_AUTHORITY_REQUIRED=NO"
echo "BROAD_AUTONOMOUS_AUTHORITY_REQUIRED=NO"
echo "CURRENT_SYSTEM_READY_FOR_COMMIT_PUSH_IMPLEMENTATION=NOT_YET"
echo "NEXT_ACTION=DESIGN_EXACT_TWO_FIELD_OR_SUBCONTRACT_EXTENSION_AND_VALIDATION_RULES"
echo "AUTOMATIC_IMPLEMENTATION=NO"
