#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY SEEDED EXPECTED OUTCOME GAP ==="
echo "RECOVERY_POINT=DR_20260826_111719"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== EVIDENCE-BASED CLASSIFICATION ==="
echo "MATILDA_AUTHORED_packageSemantics_expectedOutcome=NULL"
echo "IEL_PERSISTED_expectedOutcome=NULL"
echo "LIVING_DRAFT_expected_outcome=NULL"
echo "APPROVAL_PRESENTATION_FALLBACK=Not recorded."
echo "DOWNSTREAM_TRANSPORT_LOSS=NO"
echo "DRAFT_SYNTHESIS_LOSS=NO"
echo "APPROVAL_READ_MODEL_LOSS=NO"
echo "UI_BINDING_DEFECT=NO"
echo "FAILURE_LOCATION=MATILDA_PACKAGE_SEMANTICS_AUTHORSHIP"

echo
echo "=== IMPORTANT DISTINCTION ==="
echo "USER_SEED_INCLUDED_AN_EXPLICIT_EXPECTED_OUTCOME=YES"
echo "MODEL_RETURNED_expectedOutcome_NULL_DESPITE_REQUEST_SPECIFIC_EXPECTED_OUTCOME=YES"
echo "CURRENT_VALIDATOR_ALLOWS_expectedOutcome_NULL=YES"
echo "CURRENT_PIPELINE_CORRECTLY_PRESERVED_THAT_NULL=YES"
echo "NOT_RECORDED_IS_ACCURATE_RENDERING_OF_THE_PERSISTED_NULL=YES"

echo
echo "=== NEXT INVESTIGATION ==="
echo "QUESTION=SHOULD_expectedOutcome_REMAIN_INDIVIDUALLY_NULLABLE_WHEN_packageSemantics_IS_NON_NULL"
echo "LIKELY_BOUNDARY=PACKAGE_SEMANTICS_COMPLETENESS_CONTRACT"
echo "DO_NOT_PATCH_UI=YES"
echo "DO_NOT_SYNTHESIZE_EXPECTED_OUTCOME_HEURISTICALLY=YES"
echo "DO_NOT_BACKFILL_HISTORICAL_PACKAGES=YES"
echo "SIDEBAR_COMPACTNESS_REMAINS_SEPARATE_PRESENTATION_FOLLOWUP=YES"
echo "NEXT_ACTION=INSPECT_CURRENT_PACKAGE_SEMANTICS_NULLABILITY_CONTRACT_AND_DECIDE_WHETHER_A_NON_NULL_ARTIFACT_MUST_REQUIRE_expectedOutcome"
