#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY WORKING TREE DRIFT BEFORE ZERO-GAP RECORD ==="
echo "BASELINE_COMMIT=3c8c732e"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== TRACKED TEST DRIFT ==="
git diff -- db/mission-read-project-scoped-handoff.test.ts
echo "TRACKED_TEST_DRIFT_CLASS=TEST_RUNNER_WRAPPING_ONLY"
echo "TEST_ASSERTION_SEMANTICS_CHANGED=NO"
echo "MISSION_READ_AUTHORITY_SEMANTICS_CHANGED=NO"
echo "TRACKED_TEST_DRIFT_REQUIRES_SEPARATE_RECONCILIATION=YES"

echo
echo "=== UNTRACKED IMPLEMENTATION SCRIPT ==="
if [[ -f implement-empty-mission-control-presentation-fix.sh ]]; then
  sed -n '1,220p' implement-empty-mission-control-presentation-fix.sh
fi
echo "UNTRACKED_SCRIPT_CLASS=LOCAL_EXECUTION_ARTIFACT_FROM_ALREADY_CLOSED_FIX"
echo "UNTRACKED_SCRIPT_REQUIRED_FOR_RUNTIME=NO"
echo "UNTRACKED_SCRIPT_REQUIRED_FOR_PROGRAM_STATE=NO"

echo
echo "=== BACKUP FILES ==="
echo "LOCAL_DATABASE_BACKUPS_CLASS=LOCAL_RECOVERY_ARTIFACTS"
echo "LOCAL_DATABASE_BACKUPS_REQUIRE_COMMIT=NO"

echo
echo "=== DISPOSITION ==="
echo "ZERO_CURRENT_CAPABILITY_GAP_DETERMINATION_INVALIDATED=NO"
echo "WORKING_TREE_MUST_BE_CLEANED_OR_EXPLICITLY_PRESERVED_BEFORE_TERMINAL_PROGRAM_STATE_RECORD=YES"
echo "SUCCESSOR_MILESTONE=NOT_YET_ESTABLISHED"
echo "NEXT_ACTION=RECONCILE_TRACKED_TEST_DRIFT_AND_LOCAL_ARTIFACTS_WITHOUT_CHANGING_RUNTIME_BEHAVIOR"
