#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY UNIT A EXTERNAL INPUT COLLECTION STOP CONDITION ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

EXPECTED_HEAD_PREFIX="2f3f349c1"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED CHECKPOINT ==="
echo "CHECKPOINT_COMMIT=2f3f349c1f50b6d306a8bb571a9300893d32c9fc"
echo "UNIT_A_SOURCE_OF_TRUTH_CORRIDOR=CLOSED"
echo "UNIT_A_EXTERNAL_INPUT_COLLECTION_CORRIDOR=ACTIVE"

echo
echo "=== STOP REPEATING ANCHOR-ONLY COMMITS ==="
echo "ANCHOR_ONLY_COMMIT_LOOP_DETECTED=YES"
echo "NEW_EVIDENCE_ADDED_BY_PRIOR_ANCHOR_COMMITS=NO"
echo "REPEATING_CHECKPOINT_ONLY_COMMITS_SHOULD_STOP=YES"

echo
echo "=== CURRENT BLOCKERS REMAIN ==="
echo "TEAM_DOMAIN=REQUIRED_FROM_CLOUDFLARE_ZERO_TRUST_ACCOUNT_STATE"
echo "APPLICATION_AUDIENCE_TAG=REQUIRED_FROM_CLOUDFLARE_ACCESS_APPLICATION_STATE"
echo "ALLOWED_OPERATOR_IDENTITY_POLICY=UNSELECTED"
echo "ACCESS_POLICY_SCOPE=UNSELECTED"
echo "ORIGIN_BYPASS_BOUNDARY=REQUIRES_DEPLOYMENT_EVIDENCE"
echo "SAFE_NON_EXECUTION_VALIDATION_TARGET=UNDESIGNED"

echo
echo "=== CORRECT NEXT MOVE ==="
echo "NEXT_ACTION=OBTAIN_NEW_EXTERNAL_OR_USER_OWNED_EVIDENCE_BEFORE_ANY_FURTHER_REPOSITORY_COMMIT"
echo "NEXT_REPOSITORY_COMMIT_REQUIRES_NEW_SUBSTANTIVE_EVIDENCE=YES"
echo "IMPLEMENTATION_READINESS_REVIEW_ALLOWED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "AUTHENTICATION_IS_NOT_EXECUTION_APPROVAL=YES"
echo "AUTHENTICATION_IS_NOT_GIT_AUTHORITY=YES"
echo "CLIENT_SUPPLIED_ACTOR_REMAINS_UNTRUSTED=YES"
echo "MATILDA_SELF_APPROVAL=PROHIBITED"
echo "CADE_SELF_APPROVAL=PROHIBITED"
echo "EXECUTION_AUTHORIZATION_ROUTE_MUST_REMAIN_UNMOUNTED=YES"
echo "LOCAL_EXECUTION_AUTHORIZATION_REMAINS_DISABLED=YES"
echo "GENERIC_MUTATION_AUTHORITY=DISABLED"
echo "GENERIC_SHELL_AUTHORITY=DISABLED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=DISABLED"

echo
echo "=== SAFETY ==="
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_DNS_CHANGE=YES"
echo "NO_TUNNEL_CHANGE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
