#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="74edd327a"

git fetch origin "$BRANCH"
test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$EXPECTED_HEAD"

printf '\n=== MINIMUM OPERATOR VALIDATION ADAPTER CLASSIFICATION ===\n'
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "IMPLEMENTATION_PERFORMED=NO"
echo "CURRENT_EXECUTIVE_SURFACE=client/src/approvals/ApprovalsWorkspace.tsx"
echo "CURRENT_DELEGATION_ACTION=EXPLICIT_OPERATOR_ACTION"
echo "CURRENT_POST_DELEGATION_SURFACE=EXISTS"
echo "CURRENT_CLIENT_VALIDATION_ADAPTER=ABSENT"
echo "PRODUCTION_VALIDATION_ROUTE=POST_/api/governance/validation"
echo "PRODUCTION_VALIDATION_ROUTE_MOUNTED=YES"
echo "SERVER_ELIGIBILITY_ENFORCEMENT=EXISTS"
echo "LIVE_VALIDATION_INVOCATION_AUTHORIZED=NO"
echo "LIVE_GOVERNANCE_DATA_MUTATION_AUTHORIZED=NO"

printf '\n=== MINIMUM IMPLEMENTATION SURFACE ===\n'
echo "NEW_CLIENT_ADAPTER=client/src/approvals/governanceValidationApi.ts"
echo "NEW_CLIENT_ADAPTER_TEST=client/src/approvals/governanceValidationApi.test.ts"
echo "EXISTING_UI_TARGET=client/src/approvals/ApprovalsWorkspace.tsx"
echo "UI_LOCATION=EXISTING_DELEGATED_PACKAGE_SURFACE"
echo "ACTION_VISIBILITY=ONLY_AFTER_DELEGATION"
echo "ACTION_TRIGGER=EXPLICIT_OPERATOR_CLICK"
echo "AUTOMATIC_INVOCATION=NO"

printf '\n=== REQUEST IDENTITY ===\n'
echo "DELEGATION_ID=FROM_EXISTING_DELEGATED_PACKAGE_READ_MODEL"
echo "PACKAGE_ID=FROM_EXISTING_CANONICAL_PACKAGE_READ_MODEL"
echo "PACKAGE_VERSION=FROM_EXISTING_CANONICAL_PACKAGE_READ_MODEL"
echo "VALIDATION_RESULT_ID=GENERATED_ONLY_ON_EXPLICIT_OPERATOR_ACTION"
echo "VALIDATION_STATUS=EXPLICIT_ACTION_INPUT_NOT_LIFECYCLE_INFERENCE"

printf '\n=== AUTHORITY BOUNDARY ===\n'
echo "PRESERVE_EXISTING_PRODUCTION_ROUTE=YES"
echo "PRESERVE_EXISTING_ELIGIBILITY_GATE=YES"
echo "AUTO_ADVANCE=NO"
echo "SCHEDULER_AUTHORITY=NO"
echo "WORKER_AUTHORITY=NO"
echo "ORCHESTRATION_AUTHORITY=NO"
echo "ROUTING_AUTHORITY=NO"
echo "ASSIGNMENT_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "DOWNSTREAM_GOVERNANCE_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"

printf '\n=== IMPLEMENTATION QUESTION RESOLVED ===\n'
echo "MINIMUM_OPERATOR_ADAPTER=CLIENT_API_ADAPTER_PLUS_EXPLICIT_CONTROL_ON_EXISTING_DELEGATED_PACKAGE_SURFACE"
echo "SERVER_ROUTE_CHANGE_REQUIRED=NO"
echo "DATABASE_SCHEMA_CHANGE_REQUIRED=NO"
echo "LIVE_DATABASE_PROOF_REQUIRED=NO"
echo "NEXT_ACTION=IMPLEMENT_AND_TEST_BOUNDED_CLIENT_OPERATOR_ADAPTER"

printf '\n=== WORKTREE — PRESERVE ===\n'
git status --short

printf '\nMINIMUM_OPERATOR_VALIDATION_ADAPTER_CLASSIFICATION=COMPLETE\n'
