#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY MINIMUM PRODUCTION REACHABILITY UNIT ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "ACTIVE_PROJECT_LOCAL_COMMIT_EXECUTION_AUTHORIZED=NO"
echo "ACTIVE_PROJECT_REMOTE_PUSH_EXECUTION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="6540c7011"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== ESTABLISHED CURRENT STATE ==="
echo "LOCAL_COMMIT_EFFECT_IMPLEMENTED=YES"
echo "LOCAL_COMMIT_EFFECT_PRODUCTION_REACHABILITY=NO"
echo "REMOTE_PUSH_EFFECT_IMPLEMENTED=YES"
echo "REMOTE_PUSH_EFFECT_PRODUCTION_REACHABILITY=NO"
echo "PUSH_APPROVAL_PHASE_IMPLEMENTED=YES"
echo "GENERIC_CADE_EXECUTOR_DOES_NOT_RECEIVE_GOVERNED_ENVELOPE=YES"
echo "GENERIC_CADE_ROUTES_CALL_EXECUTE_CADE_ACTION_DIRECTLY=YES"
echo "GOVERNED_COMMIT_ADAPTER_HAS_NO_CANONICAL_RUNTIME_CALLER=YES"
echo "GOVERNED_PUSH_ADAPTER_HAS_NO_CANONICAL_RUNTIME_CALLER=YES"
echo "BUILD_APPROVAL_ARTIFACT_DEFAULT_STATUS=approval_required"
echo "APPROVAL_REQUIRED_TO_APPROVED_RUNTIME_TRANSITION=NOT_ESTABLISHED"
echo "USER_APPROVAL_TO_APPROVAL_ID_BINDING=NOT_ESTABLISHED"

echo
echo "=== CRITICAL PRODUCTION GAP ==="
echo "MISSING_BOUNDARY=CANONICAL_GOVERNED_VERSION_CONTROL_ORCHESTRATION"
echo "DIRECT_GENERIC_CADE_ROUTE_MUST_NOT_FILL_THIS_GAP=YES"
echo "GENERIC_ORCHESTRATION_ROUTE_EXECUTE_FLAG_MUST_NOT_FILL_THIS_GAP=YES"
echo "REASON=GENERIC_ROUTES_DO_NOT_CARRY_GOVERNED_ENVELOPE_APPROVAL_CORRELATION_OR_VERSION_CONTROL_PROVENANCE"

echo
echo "=== INSPECT CURRENT APPROVAL / DECISION SURFACES ==="
git grep -n -I -E \
  'approval_required|approved_by|approval_id|status.*approved|approve|approval artifact|approval_artifact|pending approval|pending_approval' \
  -- server routes app src 2>/dev/null \
  | sed -n '1,900p' || true

echo
echo "=== INSPECT CURRENT PROJECT REGISTRY IDENTITY SURFACES ==="
git grep -n -I -E \
  'repo_path|repository|repoUrl|repo_url|remote|branch|project_target|activeProjectId|project registry|project-registry' \
  -- server routes app src docs/governance 2>/dev/null \
  | sed -n '1,900p' || true

echo
echo "=== INSPECT CURRENT GOVERNED PIPELINE BUILDERS ==="
for f in \
  server/execution/build-execution-envelope-draft.mjs \
  server/execution/build-approval-artifact.mjs \
  server/execution/execution-approval-gate.mjs \
  server/execution/governance-validator.mjs \
  server/routes/governed-planning-route.mjs \
  server/cade/cade-event-wrapper.ts \
  server/events/execution-event-store.ts
do
  if [[ -f "${f}" ]]; then
    echo
    echo "--- ${f} ---"
    nl -ba "${f}" | sed -n '1,520p'
  fi
done

echo
echo "=== REQUIRED CANONICAL ORCHESTRATOR RESPONSIBILITIES ==="
echo "RESPONSIBILITY_1=ACCEPT_GOVERNED_ENVELOPE_NOT_RAW_GENERIC_ACTION"
echo "RESPONSIBILITY_2=REQUIRE_EXPLICIT_APPROVAL_BOUND_TO_ENVELOPE"
echo "RESPONSIBILITY_3=RUN_GOVERNANCE_VALIDATION"
echo "RESPONSIBILITY_4=RUN_COMMIT_APPROVAL_GATE"
echo "RESPONSIBILITY_5=CALL_GOVERNED_COMMIT_ADAPTER_ONLY_AFTER_COMMIT_AUTHORITY"
echo "RESPONSIBILITY_6=CAPTURE_LOCAL_COMMIT_RESULT"
echo "RESPONSIBILITY_7=CORRELATE_LOCAL_COMMIT_RESULT_TO_SAME_APPROVAL_AND_ENVELOPE"
echo "RESPONSIBILITY_8=RUN_PUSH_APPROVAL_GATE_WITH_LOCAL_COMMIT_PROOF"
echo "RESPONSIBILITY_9=CALL_GOVERNED_PUSH_ADAPTER_ONLY_AFTER_PUSH_AUTHORITY"
echo "RESPONSIBILITY_10=RECORD_AND_RETURN_RECONCILIATION_RESULT"

echo
echo "=== MINIMUM PRODUCTION REACHABILITY UNIT CANDIDATE ==="
echo "UNIT_NAME=GOVERNED_VERSION_CONTROL_ORCHESTRATOR"
echo "UNIT_TYPE=NEW_NARROW_RUNTIME_ENTRYPOINT"
echo "GENERIC_CADE_EXECUTOR_EXTENSION=NO"
echo "GENERIC_CADE_ROUTE_EXTENSION=NO"
echo "GENERIC_ORCHESTRATION_EXECUTE_FLAG_EXTENSION=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGE=NO"
echo "REMOTE_PUSH_EFFECT_CHANGE=NO"
echo "APPROVAL_GATE_SEMANTIC_CHANGE=NO"
echo "EXECUTION_SWITCH_CHANGE=NO"
echo "GOVERNANCE_VALIDATOR_CHANGE=NO"

echo
echo "=== MINIMUM REQUIRED INPUT CONTRACT ==="
echo "INPUT_ENVELOPE=REQUIRED"
echo "INPUT_APPROVAL_ARTIFACT=REQUIRED"
echo "INPUT_EXPLICIT_USER_APPROVAL_EVIDENCE=REQUIRED"
echo "INPUT_COMMIT_MESSAGE=REQUIRED_FOR_COMMIT"
echo "INPUT_EXPECTED_REMOTE_URL=REQUIRED_FOR_PUSH"
echo "INPUT_EXECUTION_ID=REQUIRED"
echo "RAW_ACTION_STRING_ROUTING=PROHIBITED"

echo
echo "=== REQUIRED APPROVAL CORRELATION ==="
echo "APPROVAL_ID_MUST_MATCH_GATE_OUTPUT=YES"
echo "ENVELOPE_ID_MUST_REMAIN_CONSTANT=YES"
echo "PROJECT_TARGET_MUST_REMAIN_CONSTANT=YES"
echo "COMMIT_APPROVAL_AND_PUSH_APPROVAL_MUST_SHARE_GOVERNED_LINEAGE=YES"
echo "PUSH_MUST_USE_ACTUAL_LOCAL_COMMIT_RESULT_NOT_RECONSTRUCTED_MODEL_TEXT=YES"
echo "APPROVAL_STATUS_MUST_BE_DURABLY_OR_EXPLICITLY_TRANSITIONED_TO_APPROVED=YES"
echo "MODEL_SELF_APPROVAL=PROHIBITED"

echo
echo "=== PROJECT IDENTITY REQUIREMENTS ==="
echo "REPOSITORY_PATH_MUST_DERIVE_FROM_REGISTERED_PROJECT_TARGET=YES"
echo "BRANCH_MUST_DERIVE_FROM_REGISTERED_PROJECT_TARGET=YES"
echo "REMOTE_NAME_MUST_BE_EXPLICITLY_AUTHORIZED=YES"
echo "REMOTE_URL_MUST_BE_OBSERVED_AND_MATCH_AUTHORIZED_PROJECT_IDENTITY=YES"
echo "MODEL_INFERRED_REPOSITORY_IDENTITY=PROHIBITED"

echo
echo "=== FIRST PRODUCTION-REACHABILITY TEST BOUNDARY ==="
echo "ACTIVE_REPOSITORY_WRITE_TEST=NOT_YET_AUTHORIZED"
echo "TEMP_REPOSITORY_END_TO_END_TEST=RECOMMENDED_FIRST"
echo "TEST_MUST_RUN_FULL_FLOW=ENVELOPE_TO_APPROVAL_TO_COMMIT_TO_PUSH_TO_PROVENANCE"
echo "TEST_MUST_NOT_USE_GENERIC_CADE_ROUTE=YES"
echo "TEST_MUST_NOT_USE_GENERIC_ORCHESTRATION_EXECUTE_FLAG=YES"

echo
echo "=== SEPARATE UNRESOLVED AUTHORITY QUESTION ==="
echo "EXPLICIT_USER_APPROVAL_RUNTIME_MECHANISM=NOT_YET_ESTABLISHED"
echo "THIS_MUST_BE_RESOLVED_BEFORE_ACTIVE_REPOSITORY_ENABLEMENT=YES"
echo "APPROVAL_UI_OR_API_MAY_ALREADY_EXIST=INSPECTION_REQUIRED"
echo "DO_NOT_INVENT_NEW_APPROVAL_STORE_UNLESS_EXISTING_SURFACES_PROVE_INSUFFICIENT=YES"

echo
echo "=== CLASSIFICATION ==="
echo "MINIMUM_PRODUCTION_REACHABILITY_UNIT=GOVERNED_VERSION_CONTROL_ORCHESTRATOR"
echo "ORCHESTRATOR_IMPLEMENTATION_AUTHORIZED=NO"
echo "ACTIVE_REPOSITORY_ENABLEMENT_AUTHORIZED=NO"
echo "GENERIC_ROUTE_VERSION_CONTROL_REACHABILITY=PROHIBITED"
echo "NEXT_ACTION=CLASSIFY_EXISTING_APPROVAL_TRANSITION_AND_PROJECT_IDENTITY_SOURCES_BEFORE_DESIGNING_ORCHESTRATOR_PATCH"
