#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY END-TO-END PACKAGE SEMANTICS TRANSPORT UNIT ==="
echo "BASELINE_COMMIT=$(git rev-parse --short HEAD)"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "RECOVERY_POINT=DR_20260826_092915"

echo
echo "=== VERIFIED PERSISTENCE PRECEDENT ==="
echo "DEDICATED_NULLABLE_IEL_JSON_COLUMN_PATTERN=CONFIRMED"
echo "PRECEDENT_COLUMN=investigation_lifecycle_json"
echo "CANDIDATE_COLUMN=package_semantics_json"
echo "HISTORICAL_ROWS=SQL_NULL_NO_BACKFILL"
echo "SUPPORTING_RAW_EVIDENCE_REPURPOSED=NO"
echo "ONE_WORKFLOW_ONE_IEL_ENTRY=PRESERVED"
echo "ONE_OLLAMA_INVOCATION=PRESERVED"

echo
echo "=== PROPOSED MODEL OUTPUT CONTRACT UNIT ==="
echo "OLLAMA_TOP_LEVEL_FIELD=packageSemantics"
echo "TOP_LEVEL_NULLABLE=YES"
echo "WHEN_PRESENT=VALIDATED_TYPED_MATILDA_AUTHORED_ARTIFACT"
echo "FIELDS=expectedOutcome,proposedWork,proposedArtifacts,inScope,outOfScope,constraints,unresolvedQuestions"
echo "FIELD_VALUES=trimmed_nonempty_string_or_null"
echo "MALFORMED_PRESENT_ARTIFACT=FAIL_CLOSED"
echo "HEURISTIC_DERIVATION_FROM_DURABLE_INTERPRETATION=NO"
echo "SECOND_MODEL_INVOCATION=NO"

echo
echo "=== PROPOSED WORKFLOW TRANSPORT UNIT ==="
echo "SOURCE=ollamaResult.packageSemantics"
echo "DESTINATION=createInterpretationEvidenceLedgerEntry.package_semantics"
echo "NEW_IEL_ENTRY_CREATED=NO"
echo "EXISTING_IEL_WRITE_OWNER=PRESERVED"
echo "MATILDA_OBSERVATION_SOURCE=durableInterpretation_UNCHANGED"
echo "INVESTIGATION_LIFECYCLE_TRANSPORT=UNCHANGED"
echo "SUPPORT_PROVENANCE_TRANSPORT=UNCHANGED"

echo
echo "=== PROPOSED IEL STORAGE / RECONSTRUCTION UNIT ==="
echo "INPUT_PROPERTY=package_semantics"
echo "STORED_COLUMN=package_semantics_json"
echo "SQL_NULL_MEANS=NO_PACKAGE_SEMANTICS_AUTHORED_FOR_ENTRY"
echo "NON_NULL_STORAGE=JSON_STRINGIFIED_VALIDATED_ARTIFACT"
echo "READ_PROPERTY=packageSemantics"
echo "READ_RECONSTRUCTION=JSON_PARSE_PLUS_SHARED_PACKAGE_SEMANTICS_VALIDATOR"
echo "MALFORMED_PERSISTED_JSON=FAIL_CLOSED"
echo "INVALID_PERSISTED_ARTIFACT=FAIL_CLOSED"

echo
echo "=== LIVING DRAFT CONSUMPTION BOUNDARY ==="
echo "CURRENT_INTERPRETATION=CONTINUE_AGGREGATING_matilda_observation"
echo "STATIC_GENERIC_STRUCTURED_FIELDS=TARGET_FOR_REMOVAL"
echo "VALIDATED_PACKAGE_SEMANTICS=ONLY_ALLOWED_REQUEST_SPECIFIC_STRUCTURED_SOURCE"
echo "GENERIC_FALLBACK_IF_NO_VALIDATED_SEMANTICS=NO"
echo "MISSING_SEMANTIC_FIELD=REMAIN_NULL"
echo "AUTHORITY_TRANSITION=UNCHANGED"

echo
echo "=== MULTI-ENTRY SELECTION QUESTION ==="
echo "MULTIPLE_IEL_ENTRIES_CAN_FEED_ONE_LIVING_DRAFT=YES"
echo "EACH_ENTRY_MAY_HAVE_packageSemantics_NULL_OR_NON_NULL=YES"
echo "SELECTION_RULE_NOT_YET_ESTABLISHED=YES"
echo "DO_NOT_MERGE_FIELD_VALUES_HEURISTICALLY=YES"
echo "DO_NOT_ASSUME_LATEST_ENTRY_WITHOUT_ORDER_EVIDENCE=YES"

echo
echo "=== INSPECT EXACT ORDER / DRAFT EVIDENCE ASSEMBLY ==="
rg -n -C 14 \
  'listInterpretationEvidenceLedgerEntries|ORDER BY created_at|evidence_entry_ids|synthesizeLivingDraft|runMatildaChatDraftIntegration|draft_package_updated|draft_package_id|lineage_id' \
  db/matilda-interpretation-runtime.ts \
  db/matilda-draft-synthesis-runtime.ts \
  db/matilda-chat-draft-integration.ts \
  server/matilda-chat-workflow.ts \
  2>/dev/null || true

echo
echo "=== REQUIRED NEXT DETERMINATION ==="
echo "QUESTION=FOR_A_LIVING_DRAFT_WITH_MULTIPLE_ELIGIBLE_IEL_ENTRIES_WHICH_SINGLE_VALIDATED_PACKAGE_SEMANTICS_ARTIFACT_GOVERNS_THE_CURRENT_STRUCTURED_DRAFT_FIELDS"
echo "CANDIDATE_RULE=NEWEST_ELIGIBLE_NON_NULL_ARTIFACT_WITHIN_EXACT_DRAFT_EVIDENCE_SET"
echo "CANDIDATE_RULE_STATUS=NOT_YET_CONFIRMED"
echo "FIELD_BY_FIELD_MERGE=NOT_AUTHORIZED"
echo "CROSS_CONVERSATION_SELECTION=PROHIBITED"
echo "CROSS_PROJECT_SELECTION=PROHIBITED"

echo
echo "=== IMPLEMENTATION BOUNDARY ==="
echo "OLLAMA_SCHEMA_CHANGE_AUTHORIZED=NO"
echo "PROMPT_CHANGE_AUTHORIZED=NO"
echo "VALIDATOR_IMPLEMENTATION_AUTHORIZED=NO"
echo "IEL_SCHEMA_CHANGE_AUTHORIZED=NO"
echo "WORKFLOW_TRANSPORT_CHANGE_AUTHORIZED=NO"
echo "SYNTHESIS_CHANGE_AUTHORIZED=NO"
echo "NEXT_ACTION=CLASSIFY_DETERMINISTIC_PACKAGE_SEMANTICS_SELECTION_RULE_FROM_EXISTING_IEL_ORDER_AND_DRAFT_EVIDENCE_LINEAGE_BEFORE_IMPLEMENTATION_AUTHORIZATION"
