#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY OPERATIONAL PACKAGE AUTHORITY PERSISTENCE OWNERSHIP ==="

echo
echo "=== BASELINE ==="
printf "HEAD=" && git rev-parse --short=8 HEAD
printf "BRANCH=" && git branch --show-current
git status --short

echo
echo "=== VERIFIED CONTRACT ==="
echo "AUTHORITY_NAME=OPERATIONAL_PACKAGE_AUTHORITY"
echo "AUTHORITY_SCOPE=PROJECT_SCOPED"
echo "AUTHORITATIVE_BINDING=(project_id,package_id,package_version)"
echo "ONE_ACTIVE_OPERATIONAL_PACKAGE_PER_PROJECT=YES"
echo "EXPLICIT_SELECTION_REQUIRED=YES"
echo "SUCCESSOR_VERSION_AUTO_ACTIVATION=NO"
echo "DELEGATION_REQUIRED_FOR_SELECTION=NO"

echo
echo "=== VERIFIED REPOSITORY PRECEDENTS ==="
echo "GLOBAL_ACTIVE_PROJECT_CONTEXT=ACTIVE_CONTEXT_SINGLETON"
echo "PROJECT_SCOPED_ACTIVE_CONVERSATION_CONTEXT=MATILDA_ACTIVE_CONVERSATION_CONTEXT"
echo "PROJECT_SCOPED_ACTIVE_CONVERSATION_KEY=PROJECT_ID_PRIMARY_KEY"
echo "CANONICAL_PACKAGE_IDENTITY=(PACKAGE_ID,PACKAGE_VERSION)"
echo "CANONICAL_PACKAGE_CARRIES_PROJECT_ID=YES"
echo "CANONICAL_PACKAGE_MUTATION_REQUIRED=NO"

echo
echo "=== RELEVANT SCHEMAS ==="
sqlite3 -header -column db/main.db "
SELECT name, sql
FROM sqlite_master
WHERE type = 'table'
  AND name IN (
    'project_registry',
    'active_context',
    'matilda_active_conversation_context',
    'matilda_canonical_packages',
    'governance_delegations'
  )
ORDER BY name;
"

echo
echo "=== CANONICAL PACKAGE / PROJECT MATCH ==="
sqlite3 -header -column db/main.db "
SELECT
  cp.package_id,
  cp.package_version,
  cp.project_id,
  cp.status,
  CASE WHEN pr.project_id IS NULL THEN 'NO' ELSE 'YES' END AS registered_project_exists
FROM matilda_canonical_packages cp
LEFT JOIN project_registry pr
  ON pr.project_id = cp.project_id
ORDER BY cp.created_at;
"

echo
echo "=== OWNERSHIP FALSIFICATION: PROJECT REGISTRY ==="
echo "QUESTION=SHOULD_OPERATIONAL_PACKAGE_AUTHORITY_BE_STORED_AS_A_COLUMN_ON_PROJECT_REGISTRY"
echo "RESULT=NO"
echo "REASON=PROJECT_REGISTRY_OWNS_PROJECT_REGISTRATION_AND_AVAILABILITY_NOT_PACKAGE_AUTHORITY"
echo "REASON=EMBEDDING_PACKAGE_VERSION_BINDING_WOULD_COUPLE_DISTINCT_AUTHORITY_TO_REGISTRATION_METADATA"

echo
echo "=== OWNERSHIP FALSIFICATION: ACTIVE PROJECT CONTEXT ==="
echo "QUESTION=SHOULD_OPERATIONAL_PACKAGE_AUTHORITY_REUSE_ACTIVE_CONTEXT"
echo "RESULT=NO"
echo "REASON=ACTIVE_CONTEXT_IS_GLOBAL_CURRENT_PROJECT_SELECTION"
echo "REASON=OPERATIONAL_PACKAGE_AUTHORITY_IS_ONE_BINDING_PER_PROJECT"
echo "REASON=PROJECT_SWITCHING_MUST_NOT_CHANGE_WHICH_PACKAGE_IS_OPERATIONALLY_AUTHORITATIVE_FOR_EACH_PROJECT"

echo
echo "=== OWNERSHIP FALSIFICATION: CANONICAL PACKAGE ROW ==="
echo "QUESTION=SHOULD_OPERATIONAL_AUTHORITY_BE_STORED_ON_MATILDA_CANONICAL_PACKAGES"
echo "RESULT=NO"
echo "REASON=CANONICAL_PACKAGE_IS_APPROVED_IMMUTABLE_ARTIFACT_IDENTITY"
echo "REASON=OPERATIONAL_SELECTION_IS_SEPARATE_MUTABLE_AUTHORITY_STATE"
echo "REASON=SUCCESSOR_VERSION_MUST_NOT_AUTO_ACTIVATE"

echo
echo "=== OWNERSHIP FALSIFICATION: DELEGATION ==="
echo "QUESTION=SHOULD_DELEGATION_OWN_OPERATIONAL_PACKAGE_AUTHORITY"
echo "RESULT=NO"
echo "REASON=DELEGATION_IS_A_SEPARATE_EXPLICIT_AUTHORITY_EVENT"
echo "REASON=OPERATIONAL_PACKAGE_SELECTION_DOES_NOT_REQUIRE_DELEGATION"
echo "REASON=SELECTION_MUST_NOT_CREATE_OR_MUTATE_DELEGATION"

echo
echo "=== POSITIVE PRECEDENT ==="
echo "PRECEDENT=MATILDA_ACTIVE_CONVERSATION_CONTEXT"
echo "STRUCTURAL_PROPERTY=PROJECT_ID_PRIMARY_KEY"
echo "STRUCTURAL_PROPERTY=EXPLICIT_PROJECT_SCOPED_CURRENT_BINDING"
echo "STRUCTURAL_PROPERTY=SOURCE_ACTION_UPDATED_AT_AUDIT_METADATA"
echo "REUSE_TABLE_DIRECTLY=NO"
echo "REUSE_PATTERN=YES"

echo
echo "=== OWNERSHIP CLASSIFICATION ==="
echo "OWNERSHIP_MODEL=DEDICATED_PROJECT_SCOPED_AUTHORITY_BOUNDARY"
echo "MINIMUM_PERSISTED_IDENTITY=(project_id,package_id,package_version)"
echo "PRIMARY_AUTHORITY_KEY=PROJECT_ID"
echo "PACKAGE_REFERENCE_TARGET=MATILDA_CANONICAL_PACKAGES"
echo "PROJECT_REFERENCE_TARGET=PROJECT_REGISTRY"
echo "DATABASE_ENFORCED_EXACT_PACKAGE_VERSION_REFERENCE=REQUIRED"
echo "DATABASE_ENFORCED_PROJECT_PACKAGE_OWNERSHIP_MATCH=REQUIRED_BUT_ENFORCEMENT_SHAPE_NOT_YET_CLASSIFIED"
echo "AUDIT_METADATA_REQUIRED=YES"
echo "AUTHORITY_SELECTION_RUNTIME_REQUIRED=YES_BUT_NOT_YET_DESIGNED"
echo "MISSION_READ_CONSUMPTION=DOWNSTREAM_CONSUMER_NOT_OWNER"
echo "DELEGATION_COUPLING=NONE"
echo "VALIDATION_COUPLING=NONE"
echo "EXECUTION_ACTIVATION=NONE"

echo
echo "=== SCOPE DETERMINATION ==="
echo "VERIFIED_OUTCOME=DEDICATED_PROJECT_SCOPED_OPERATIONAL_PACKAGE_AUTHORITY_BOUNDARY_IS_THE_COHERENT_OWNERSHIP_MODEL"
echo "VERIFIED_OUTCOME=PROJECT_ACTIVE_CONTEXT_AND_ACTIVE_CONVERSATION_ARE_STRUCTURAL_PRECEDENTS_NOT_REUSABLE_AUTHORITY_SURFACES"
echo "VERIFIED_OUTCOME=CANONICAL_PACKAGE_DELEGATION_AND_MISSION_READ_MUST_NOT_OWN_OPERATIONAL_PACKAGE_SELECTION"
echo "PARTIALLY_IMPLEMENTED=OPERATIONAL_PACKAGE_AUTHORITY"
echo "PROPOSED_IMPLEMENTATION=NONE"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "NEXT_DECISION=CLASSIFY_MINIMUM_DATABASE_CONSTRAINT_MODEL_FOR_PROJECT_TO_EXACT_CANONICAL_PACKAGE_VERSION_BINDING_WITH_PROJECT_OWNERSHIP_ENFORCED"
