#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY CLOUDFLARE ACCESS IDENTITY FEASIBILITY ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "AUTHORIZATION_COMPILATION_IMPLEMENTATION_AUTHORIZED=NO"
echo "ACTIVE_REPOSITORY_EXECUTION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="e65930d6a"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== CLOSED EVIDENCE FROM PRIOR INVESTIGATION ==="
echo "APPLICATION_DESIGN=LOCAL_PRIVACY_FIRST"
echo "REMOTE_ACCESS_DESIGN=OPTIONAL_SELECTIVE_TUNNELS"
echo "CLOUDFLARE_TUNNEL_USAGE_EVIDENCE=YES"
echo "APPLICATION_AUTH_MODEL=NONE_ESTABLISHED"
echo "PROXY_VERIFIED_IDENTITY_MODEL=NONE_ESTABLISHED"
echo "CLOUDFLARE_ACCESS_AUTH_MODEL=NONE_ESTABLISHED"
echo "CURRENT_OPERATOR_IDENTITY=NOT_SERVER_VERIFIED"
echo "REQUEST_BODY_authorization_actor=UNTRUSTED"
echo "TRUSTED_OPERATOR_IDENTITY_PREREQUISITE=OPEN"

echo
echo "=== CORRECT PRIOR SEARCH FAILURE ==="
echo "PRIOR_FAILURE_CLASS=GIT_PATHSPEC_EXCLUDE_SYNTAX_INCOMPATIBILITY"
echo "PRIOR_FAILURE_DOES_NOT_INVALIDATE_DEPLOYMENT_CLASSIFICATION=YES"
echo "RETRY_WITH_SIMPLE_TRACKED_FILE_SEARCH=YES"

echo
echo "=== SEARCH TRACKED REPOSITORY FOR CLOUDFLARE ACCESS CONFIGURATION ==="
git grep -n -I -E \
  'cloudflared|Cloudflare|CF-Access|Cf-Access|access application|access policy|zero trust|tunnel:' \
  -- . \
  | sed -n '1,1200p' || true

echo
echo "=== SEARCH FOR DEPLOYMENT CONFIG SURFACES ==="
find . \
  -path './.git' -prune -o \
  -path './node_modules' -prune -o \
  -type f \( \
    -name 'config.yml' -o \
    -name 'config.yaml' -o \
    -name '*cloudflare*' -o \
    -name '*cloudflared*' -o \
    -name '*tunnel*' -o \
    -name 'docker-compose*.yml' -o \
    -name 'docker-compose*.yaml' -o \
    -name 'Dockerfile*' -o \
    -name '*.service' \
  \) -print \
  | sort

echo
echo "=== INSPECT CLOUDFLARE-RELATED TRACKED FILES ==="
while IFS= read -r file; do
  [[ -n "${file}" ]] || continue
  echo
  echo "--- ${file} ---"
  sed -n '1,320p' "${file}"
done < <(
  git grep -l -I -E 'cloudflared|Cloudflare|CF-Access|Cf-Access|zero trust' -- . || true
)

echo
echo "=== INSPECT LOCAL CLOUDFLARED CONFIG METADATA IF PRESENT ==="
for candidate in \
  "${HOME}/.cloudflared/config.yml" \
  "${HOME}/.cloudflared/config.yaml"
do
  if [[ -f "${candidate}" ]]; then
    echo "LOCAL_CLOUDFLARED_CONFIG_PRESENT=${candidate}"
    sed -E \
      -e 's/(token:[[:space:]]*).*/\1<REDACTED>/' \
      -e 's/(secret:[[:space:]]*).*/\1<REDACTED>/' \
      -e 's/(credentials-file:[[:space:]]*).*/\1<REDACTED_PATH>/' \
      "${candidate}" \
      | sed -n '1,320p'
  fi
done

echo
echo "=== INSPECT CLOUDFLARED INSTALLATION AND TUNNEL METADATA ==="
if command -v cloudflared >/dev/null 2>&1; then
  echo "CLOUDFLARED_BINARY_PRESENT=YES"
  cloudflared --version || true

  echo
  echo "--- cloudflared tunnel list ---"
  cloudflared tunnel list 2>&1 | sed -n '1,240p' || true
else
  echo "CLOUDFLARED_BINARY_PRESENT=NO"
fi

echo
echo "=== CHECK FOR ACCESS-RELATED ENVIRONMENT NAMES WITHOUT VALUES ==="
env | cut -d= -f1 \
  | grep -E '^(CF_|CLOUDFLARE_|CLOUDFLARED_|ACCESS_)' \
  | sort \
  || true

echo
echo "=== ARCHITECTURAL FEASIBILITY CLASSIFICATION ==="
echo "CLOUDFLARE_TUNNEL_CAN_TRANSPORT_REQUESTS=ESTABLISHED"
echo "CLOUDFLARE_TUNNEL_ALONE_CAN_VERIFY_OPERATOR_IDENTITY=NO"
echo "CLOUDFLARE_ACCESS_CAN_THEORETICALLY_SUPPLY_PROXY_VERIFIED_IDENTITY=YES"
echo "EXISTING_CLOUDFLARE_ACCESS_CONFIGURATION_IN_THIS_PROJECT=NOT_YET_ESTABLISHED"
echo "APPLICATION_ACCOUNT_SYSTEM_REQUIRED_BEFORE_ACCESS_INVESTIGATION=NO"
echo "PARALLEL_APPLICATION_AUTH_SYSTEM_SHOULD_NOT_BE_CREATED_YET=YES"

echo
echo "=== REQUIRED TRUST CONTRACT IF CLOUDFLARE ACCESS IS USED ==="
echo "TRUST_SOURCE=CLOUDFLARE_ACCESS_OR_EQUIVALENT_VERIFIED_REVERSE_PROXY"
echo "SERVER_MUST_NOT_TRUST_RAW_authorization_actor=YES"
echo "SERVER_MUST_DERIVE_OPERATOR_FROM_VERIFIED_PROXY_ASSERTION=YES"
echo "DIRECT_BYPASS_TO_AUTHORIZATION_ENDPOINT_MUST_BE_PREVENTED=YES"
echo "IDENTITY_ASSERTION_VALIDATION_MUST_BE_SERVER_SIDE=YES"
echo "CLIENT_MUST_NOT_SELECT_AUTHORIZED_OPERATOR_IDENTITY=YES"
echo "EXISTING_USER_INTENT_AUTHORITY_MODEL_MUST_REMAIN_UNCHANGED=YES"
echo "THIS_IDENTITY_BOUNDARY_AUTHENTICATES_OPERATOR_IT_DOES_NOT_REPLACE_APPROVAL=YES"

echo
echo "=== DECISION GATE ==="
echo "IF_EXISTING_ACCESS_POLICY_AND_VERIFIED_IDENTITY_ASSERTION_FOUND=CLASSIFY_MINIMUM_PROXY_IDENTITY_PROPAGATION_BOUNDARY"
echo "IF_TUNNEL_EXISTS_WITHOUT_ACCESS_POLICY=CLASSIFY_CLOUDFLARE_ACCESS_CONFIGURATION_AS_INFRASTRUCTURE_PREREQUISITE"
echo "IF_DIRECT_LOCAL_AND_REMOTE_PATHS_MUST_BOTH_REMAIN_VALID=DEFINE_SINGLE_SERVER_VERIFIED_OPERATOR_IDENTITY_INTERFACE_BEFORE_IMPLEMENTATION"
echo "IF_NO_TRUSTED_PROXY_IDENTITY_CAN_BE_ESTABLISHED=RETURN_TO_SMALL_APPLICATION_OPERATOR_AUTH_OPTION"

echo
echo "=== PRESERVED EXECUTION BOUNDARIES ==="
echo "CANONICAL_PACKAGE_APPROVAL_UNCHANGED=YES"
echo "GOVERNANCE_ENVELOPE_UNCHANGED=YES"
echo "EXECUTION_AUTHORIZATION_RUNTIME_UNCHANGED=YES"
echo "EXECUTION_APPROVAL_GATE_UNCHANGED=YES"
echo "CADE_LOCAL_COMMIT_EFFECT_UNCHANGED=YES"
echo "CADE_REMOTE_PUSH_EFFECT_UNCHANGED=YES"
echo "GENERIC_CADE_ROUTE_UNCHANGED=YES"
echo "GENERIC_MUTATION_AUTHORITY_DISABLED=YES"
echo "GENERIC_SHELL_AUTHORITY_DISABLED=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_DISABLED=YES"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=USE_OBSERVED_CLOUDFLARE_CONFIGURATION_EVIDENCE_TO_SELECT_PROXY_IDENTITY_OR_INFRASTRUCTURE_PREREQUISITE_CORRIDOR"
