#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY OPTION B VALIDATION ORDER AND INTEGRATION GAP ==="
echo "EXPECTED_HEAD_PREFIX=addcd965f"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "SECOND_LIVE_INVOCATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != addcd965f* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED VALIDATION ORDER ==="
echo "PACKAGE_SEMANTICS_PARSE_AND_VALIDATION_BEFORE_SELECTED_CONTEXT_REJECTION=YES"
echo "PACKAGE_SEMANTICS_OBSERVER_BEFORE_SELECTED_CONTEXT_REJECTION=YES"
echo "SELECTED_CONTEXT_PROVENANCE_REJECTION_AFTER_PACKAGE_SEMANTICS_OBSERVER=YES"

echo
echo "=== OPTION B FIDELITY ENFORCEMENT ==="
echo "FIDELITY_FUNCTION_EXISTS=YES"
echo "FOCUSED_DIRECT_FUNCTION_TESTS_PASS=YES"
echo "OLLAMA_POST_PARSE_FIDELITY_ENFORCEMENT_CALL_VISIBLE_IN_INSPECTED_RUNTIME_ORDER=NO"
echo "FIDELITY_ENFORCEMENT_BEFORE_SELECTED_CONTEXT_REJECTION_ESTABLISHED=NO"
echo "OPTION_B_RUNTIME_INTEGRATION_COMPLETE_ESTABLISHED=NO"

echo
echo "=== LIVE RUN EVIDENCE LIMIT ==="
echo "LIVE_RUN_USED_TYPED_expectedOutcome=YES"
echo "LIVE_RUN_ATTACHED_PACKAGE_SEMANTICS_OBSERVER=NO"
echo "LIVE_RUN_FAILED_ON_UNSUPPLIED_SELECTED_CONTEXT_SEGMENT=YES"
echo "PRIOR_LIVE_RUN_CAN_NOW_RECOVER_OBSERVED_PACKAGE_SEMANTICS=NO"
echo "EXISTING_OBSERVER_CAPABILITY_COULD_HAVE_OBSERVED_PARSED_PACKAGE_SEMANTICS=YES"
echo "BUT_PRIOR_RUN_DID_NOT_CAPTURE_THAT_OBSERVATION=YES"
echo "PROVE_EXACT_TYPED_VALUE_WITHOUT_NEW_OLLAMA_INVOCATION=NO"

echo
echo "=== CLASSIFICATION ==="
echo "LIVE_OPTION_B_VALIDATION=INCONCLUSIVE"
echo "OPTION_B_IMPLEMENTATION_FAILURE_ESTABLISHED_BY_LIVE_RUN=NO"
echo "OPTION_B_RUNTIME_INTEGRATION_GAP_INDICATED_BY_CODE_ORDER=YES"
echo "GAP=FIDELITY_VALIDATOR_EXISTS_BUT_RUNTIME_ENFORCEMENT_CALL_IS_NOT_VISIBLE_IN_OLLAMA_POST_PARSE_PATH"
echo "DO_NOT_CLOSE_OPTION_B=YES"
echo "DO_NOT_CLOSE_PACKAGE_SEMANTICS_CORRIDOR=YES"
echo "DO_NOT_BLINDLY_RETRY_LIVE_RUN=YES"
echo "DO_NOT_WEAKEN_SELECTED_CONTEXT_VALIDATION=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=INSPECT_EXACT_RUNTIME_REFERENCES_TO_enforceMatildaUserPackageSemanticsFidelity_AND_CONFIRM_WHETHER_THE_FUNCTION_IS_CALLED_ANYWHERE"
echo "IF_NO_RUNTIME_CALL_EXISTS=CLASSIFY_AS_IMPLEMENTATION_INTEGRATION_DEFECT_AND_DESIGN_NARROW_REPAIR"
echo "IF_RUNTIME_CALL_EXISTS_ELSEWHERE=INSPECT_EXACT_ORDER_BEFORE_ANY_CHANGE"
echo "SOURCE_EDIT=NONE"

git diff --check

git add classify-option-b-validation-order-and-integration-gap.sh
git commit -m "Classify Option B runtime integration gap"
git push
