#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY OPERATIONAL PACKAGE AUTHORITY IMPLEMENTATION ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PROJECT_BOUND_HANDOFF"
echo "AUTHORIZATION_COMMIT=555d0d32"
echo "IMPLEMENTATION_COMMIT=d97f66cd"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== IMPLEMENTED SURFACES ==="
test -f drizzle/0011_operational_package_authority.sql
test -f db/operational-package-authority.ts
test -f db/operational-package-authority.test.ts
echo "SCHEMA_MIGRATION_FILE=PRESENT"
echo "WRITE_READ_ADAPTER=PRESENT"
echo "TARGETED_TEST_FILE=PRESENT"

echo
echo "=== LIVE SCHEMA ==="
sqlite3 -header -column db/main.db "
SELECT sql
FROM sqlite_master
WHERE type = 'table'
  AND name = 'operational_package_authority';
"

echo
echo "=== LIVE AUTHORITY STATE ==="
sqlite3 -header -column db/main.db "
SELECT
  project_id,
  package_id,
  package_version,
  selected_at
FROM operational_package_authority
ORDER BY project_id;
"

echo
echo "=== TARGETED FOREIGN KEY CHECK ==="
AUTHORITY_FK_COUNT="$(sqlite3 db/main.db "
SELECT COUNT(*)
FROM pragma_foreign_key_check
WHERE \"table\" = 'operational_package_authority';
")"
echo "OPERATIONAL_PACKAGE_AUTHORITY_FK_VIOLATIONS=${AUTHORITY_FK_COUNT}"

if [ "${AUTHORITY_FK_COUNT}" != "0" ]; then
  echo "IMPLEMENTATION_CLASSIFICATION=BLOCKED"
  echo "REASON=OPERATIONAL_PACKAGE_AUTHORITY_FOREIGN_KEY_VIOLATION"
  exit 1
fi

echo
echo "=== TYPECHECK ==="
npx tsc --noEmit --pretty false
echo "TYPECHECK=PASS"

echo
echo "=== TARGETED TESTS ==="
TEST_OUTPUT="$(npx tsx db/operational-package-authority.test.ts)"
printf '%s\n' "${TEST_OUTPUT}"

if [[ "${TEST_OUTPUT}" != *"Operational Package Authority targeted tests passed."* ]]; then
  echo "IMPLEMENTATION_CLASSIFICATION=BLOCKED"
  echo "REASON=TARGETED_TESTS_DID_NOT_REPORT_PASS"
  exit 1
fi

echo
echo "=== AUTHORITY BOUNDARY INSPECTION ==="
rg -n \
  'selectOperationalPackageForProject|getOperationalPackageForProject|operational_package_authority' \
  db server routes client/src \
  2>/dev/null || true

echo
echo "=== IMPLEMENTATION CLASSIFICATION ==="
echo "OPERATIONAL_PACKAGE_AUTHORITY_SCHEMA=IMPLEMENTED"
echo "EXACT_PROJECT_PACKAGE_VERSION_FOREIGN_KEY=IMPLEMENTED"
echo "ONE_ROW_PER_PROJECT=IMPLEMENTED"
echo "WRITE_ADAPTER=IMPLEMENTED"
echo "READ_ADAPTER=IMPLEMENTED"
echo "REGISTERED_PROJECT_PRECONDITION=IMPLEMENTED"
echo "EXACT_CANONICAL_IDENTITY_PRECONDITION=IMPLEMENTED"
echo "canonical_approved_PRECONDITION=IMPLEMENTED"
echo "MISSION_PACKAGE_PROJECTION_PRECONDITION=IMPLEMENTED"
echo "SAME_BINDING_IDEMPOTENCY=IMPLEMENTED"
echo "EXPLICIT_REPLACEMENT=IMPLEMENTED"
echo "SUCCESSOR_VERSION_AUTO_ACTIVATION=NO"
echo "TARGETED_VALIDATION=PASS"

echo
echo "=== NON-ESCALATION CLASSIFICATION ==="
echo "MISSION_READ_INTEGRATION=NOT_IMPLEMENTED"
echo "MISSION_CONTROL_INTEGRATION=NOT_IMPLEMENTED"
echo "DELEGATION_CHANGE=NO"
echo "VALIDATION_CHANGE=NO"
echo "ROUTING_CHANGE=NO"
echo "ASSIGNMENT_CHANGE=NO"
echo "EXECUTION_CHANGE=NO"
echo "CANONICAL_PACKAGE_MUTATION=NO"
echo "MISSION_PACKAGE_PROJECTION_MUTATION=NO"

echo
echo "=== LIVE SELECTION CLASSIFICATION ==="
LIVE_SELECTION_COUNT="$(sqlite3 db/main.db "
SELECT COUNT(*)
FROM operational_package_authority;
")"
echo "LIVE_OPERATIONAL_PACKAGE_SELECTION_COUNT=${LIVE_SELECTION_COUNT}"

if [ "${LIVE_SELECTION_COUNT}" != "0" ]; then
  echo "LIVE_SELECTION_STATE=UNEXPECTED_FOR_CURRENT_CHECKPOINT"
  exit 1
fi

echo "LIVE_OPERATIONAL_PACKAGE_SELECTION_PERFORMED=NO"
echo "CURRENT_APPROVED_PACKAGE_ELIGIBLE_FOR_SELECTION=YES"
echo "CURRENT_APPROVED_PACKAGE_OPERATIONALLY_SELECTED=NO"

echo
echo "=== CORRIDOR STATE ==="
echo "PROJECT_BOUND_HANDOFF_PERSISTENCE_UNIT=IMPLEMENTED_AND_VALIDATED"
echo "PROJECT_BOUND_HANDOFF_CORRIDOR=CANNOT_CLOSE_YET"
echo "REMAINING_BOUNDARY=EXPLICIT_LIVE_OPERATIONAL_PACKAGE_SELECTION_AND_DOWNSTREAM_PROJECT_SCOPED_READ_HANDOFF"
echo "MISSION_CONTROL_INTAKE_STARTED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=PRESENT_SEPARATE_AUTHORIZATION_GATE_FOR_EXACT_LIVE_OPERATIONAL_PACKAGE_SELECTION_ONLY"
