#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY SINGLE OLLAMA PACKAGE SEMANTICS BOUNDARY ==="
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED FINDINGS ==="
echo "SINGLE_OLLAMA_INVOCATION=YES"
echo "OLLAMA_RESULT_ALREADY_CARRIES_MULTIPLE_TYPED_SEMANTIC_OUTPUTS=YES"
echo "EXAMPLES=reply,durableInterpretation,investigationLifecycle,supportSourceReferences,evidenceSufficient"
echo "WORKFLOW_SEPARATES_REPLY_FROM_DURABLE_INTERPRETATION=YES"
echo "LIVING_DRAFT_SYNTHESIS_CURRENTLY_DERIVES_INTERPRETATION_FROM_IEL=YES"
echo "LIVING_DRAFT_STRUCTURED_PACKAGE_FIELDS_CURRENTLY_USE_STATIC_GENERIC_DEFAULTS=YES"
echo "GENERIC_FIELDS=proposed_work,proposed_artifacts,in_scope,out_of_scope,constraints,expected_outcome"
echo "UNRESOLVED_QUESTIONS_CURRENTLY_PERSISTED_AS_NULL_FROM_WORKFLOW=YES"

echo
echo "=== ARCHITECTURAL CLASSIFICATION ==="
echo "EXISTING_SINGLE_INVOCATION_CAN_THEORETICALLY_CARRY_ADDITIONAL_TYPED_MATILDA_AUTHORED_SEMANTICS=YES"
echo "SECOND_OLLAMA_INVOCATION_REQUIRED=NO"
echo "HEURISTIC_EXTRACTION_REQUIRED=NO"
echo "CURRENT_CONTRACT_ALREADY_HAS_PATTERN_FOR_OPTIONAL_TYPED_MODEL_AUTHORED_ARTIFACTS=YES"
echo "INVESTIGATION_LIFECYCLE_IS_EXISTING_PRECEDENT=YES"
echo "NEW_PACKAGE_SEMANTICS_CONTRACT_CURRENTLY_EXISTS=NO"
echo "CURRENT_LIVING_DRAFT_SYNTHESIS_CAN_CONSUME_SUCH_A_CONTRACT=NO_NOT_YET"
echo "IMPLEMENTATION_WOULD_REQUIRE_EXPLICIT_CONTRACT_AND_SYNTHESIS_CHANGES=YES"

echo
echo "=== IMPORTANT AUTHORITY BOUNDARY ==="
echo "MATILDA_MAY_AUTHOR_INTERPRETIVE_PACKAGE_SEMANTICS=ARCHITECTURALLY_COMPATIBLE"
echo "LIVING_DRAFT_REMAINS_NON_AUTHORITATIVE=REQUIRED"
echo "USER_APPROVAL_REMAINS_AUTHORITY_TRANSITION=REQUIRED"
echo "CANONICAL_PACKAGE_CREATION_AUTHORITY=UNCHANGED"
echo "ONE_USER_MESSAGE_ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=REQUIRED"
echo "FAIL_CLOSED_VALIDATION=REQUIRED"
echo "STATIC_DEFAULTS_MUST_NOT_BE_REPLACED_WITH_UNVALIDATED_FREEFORM_DATA=REQUIRED"

echo
echo "=== NEXT INVESTIGATION ==="
echo "QUESTION=WHAT_MINIMUM_TYPED_PACKAGE_SEMANTICS_ARTIFACT_SHOULD_THE_EXISTING_OLLAMA_RESPONSE_OPTIONALLY_RETURN"
echo "CANDIDATE_FIELDS=expectedOutcome,proposedWork,proposedArtifacts,inScope,outOfScope,constraints,unresolvedQuestions"
echo "REQUIREMENT=DETERMINE_FIELD_NULLABILITY_VALIDATION_PERSISTENCE_AND_FALLBACK_BEFORE_IMPLEMENTATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "OLLAMA_CONTRACT_CHANGE_AUTHORIZED=NO"
echo "SYNTHESIS_CHANGE_AUTHORIZED=NO"
echo "NEXT_ACTION=INSPECT_OLLAMA_CHAT_TYPE_SCHEMA_PARSER_AND_INVESTIGATION_LIFECYCLE_PRECEDENT_TO_DESIGN_MINIMUM_FAIL_CLOSED_PACKAGE_SEMANTICS_CONTRACT"
