#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY ACTUAL DEPLOYMENT TRUST MODEL AND OPERATOR BOUNDARY ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "AUTHORIZATION_COMPILATION_IMPLEMENTATION_AUTHORIZED=NO"
echo "ACTIVE_REPOSITORY_EXECUTION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="1b9686747"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== ESTABLISHED DEPLOYMENT FACTS ==="
echo "APPLICATION_DESIGN=LOCAL_PRIVACY_FIRST"
echo "REMOTE_ACCESS_DESIGN=OPTIONAL_SELECTIVE_TUNNELS"
echo "CLOUDFLARE_TUNNEL_USAGE_EVIDENCE=YES"
echo "APPLICATION_AUTH_DEPENDENCY_PRESENT=NO"
echo "SERVER_AUTH_MIDDLEWARE_PRESENT=NO"
echo "SERVER_VERIFIED_IDENTITY_HEADER_CONSUMER_PRESENT=NO"
echo "CLOUDFLARE_ACCESS_IDENTITY_HEADER_CONSUMER_PRESENT=NO"
echo "APPLICATION_SESSION_IDENTITY_PRESENT=NO"

echo
echo "=== TRUST DISTINCTION ==="
echo "CLOUDFLARE_TUNNEL_IS_CONNECTIVITY_NOT_IDENTITY=YES"
echo "TUNNEL_EXISTENCE_DOES_NOT_ESTABLISH_CLOUDFLARE_ACCESS_AUTHENTICATION=YES"
echo "REMOTE_ACCESS_EXISTENCE_DOES_NOT_ESTABLISH_OPERATOR_IDENTITY=YES"
echo "LOCAL_RUNTIME_POSSESSION_ALONE_DOES_NOT_PROVE_REQUEST_ACTOR_IDENTITY=YES"
echo "REQUEST_BODY_authorization_actor_REMAINS_UNTRUSTED=YES"

echo
echo "=== INSPECT ACTIVE DEPLOYMENT REFERENCES ==="
for f in \
  tools/deploy-ui.sh \
  scripts/bootstrap.sh \
  Motherboard_Project_Scope.txt \
  docs/NEXT_STEPS_MATILDA_CHAT_PHASE2.md \
  PHASE11_CONTAINER_STATUS_AFTER_REBUILD.md
do
  if [[ -f "${f}" ]]; then
    echo
    echo "--- ${f} ---"
    nl -ba "${f}" | sed -n '1,320p'
  fi
done

echo
echo "=== INSPECT CLOUDFLARE TUNNEL MAP ==="
if [[ -f /mnt/data/cloudflare-tunnel-map.txt ]]; then
  cat /mnt/data/cloudflare-tunnel-map.txt
else
  echo "CLOUDFLARE_TUNNEL_MAP_NOT_MOUNTED=YES"
fi

echo
echo "=== SEARCH FOR CLOUDFLARE ACCESS IDENTITY ==="
git grep -n -I -E \
  'CF-Access-Authenticated-User-Email|Cf-Access-Authenticated-User-Email|Cf-Access-Jwt-Assertion|CF_Authorization|access policy|access application|cloudflare access|zero trust' \
  -- \
  . \
  ':!node_modules' \
  ':!.git' \
  ':!_PRE_RESTORE_BROKEN_STATE' \
  ':!files/_PRE_RESTORE_BROKEN_STATE' \
  ':!snapshots' \
  ':!scripts_backup*' \
  || true

echo
echo "=== SEARCH FOR SINGLE-OPERATOR DECLARATIONS ==="
git grep -n -I -E \
  'single[- ]operator|sole operator|operator only|internal use|personal use|Marcela|primary operator|owner-operated|local operator' \
  -- \
  Motherboard_Project_Scope.txt \
  docs \
  server \
  routes \
  README* \
  2>/dev/null \
  | sed -n '1,900p' || true

echo
echo "=== CLASSIFICATION ==="
echo "CURRENT_APPLICATION_AUTH_MODEL=NONE_ESTABLISHED"
echo "CURRENT_PROXY_VERIFIED_IDENTITY_MODEL=NONE_ESTABLISHED"
echo "CURRENT_CLOUDFLARE_ACCESS_AUTH_MODEL=NONE_ESTABLISHED"
echo "CURRENT_REMOTE_CONNECTIVITY_MODEL=CLOUDFLARE_TUNNEL_OR_EQUIVALENT_OPTIONAL"
echo "CURRENT_OPERATOR_IDENTITY_MODEL=NOT_SERVER_VERIFIED"
echo "TRUSTED_OPERATOR_IDENTITY_PREREQUISITE_REMAINS_OPEN=YES"

echo
echo "=== MINIMUM NON-PARALLEL IDENTITY OPTIONS ==="
echo "OPTION_A=VERIFIED_REVERSE_PROXY_IDENTITY_PROPAGATION"
echo "OPTION_B=SMALL_APPLICATION_OPERATOR_AUTH_BOUNDARY"
echo "OPTION_C=LOCALHOST_ONLY_POSSESSION_TRUST"
echo "OPTION_A_PREFERRED_IF_EXISTING_CLOUDFLARE_ACCESS_CAN_BE_ESTABLISHED=YES"
echo "OPTION_B_REQUIRED_IF_REMOTE_ACCESS_CONTINUES_WITHOUT_VERIFIED_PROXY_IDENTITY=YES"
echo "OPTION_C_ONLY_VALID_IF_EXECUTION_AUTHORIZATION_ENDPOINT_IS_NETWORK_RESTRICTED_TO_TRUSTED_LOCAL_OPERATOR=YES"

echo
echo "=== SAFETY DETERMINATION ==="
echo "CURRENT_EXECUTION_AUTHORIZATION_ENDPOINT_SAFE_FOR_PRODUCTION_GIT_AUTHORITY=NO"
echo "REASON=NETWORK_CALLER_CAN_SUPPLY_authorization_actor_WITHOUT_SERVER_VERIFICATION"
echo "ACTIVE_REPOSITORY_ENABLEMENT_BEFORE_IDENTITY_BOUNDARY=PROHIBITED"
echo "DURABLE_EXECUTION_APPROVAL_WRITE_BEFORE_IDENTITY_BOUNDARY=PROHIBITED"
echo "AUTHORIZATION_ARTIFACT_COMPILATION_BEFORE_IDENTITY_BOUNDARY=PROHIBITED"

echo
echo "=== NEXT DECISION ==="
echo "NEXT_ACTION=CLASSIFY_WHETHER_EXISTING_CLOUDFLARE_DEPLOYMENT_CAN_SUPPORT_VERIFIED_ACCESS_IDENTITY_WITHOUT_NEW_APPLICATION_ACCOUNT_SYSTEM"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "EXECUTION_AUTHORIZATION_RUNTIME_UNCHANGED=YES"
echo "EXECUTION_APPROVAL_GATE_UNCHANGED=YES"
echo "CANONICAL_PACKAGE_APPROVAL_UNCHANGED=YES"
echo "GOVERNANCE_ENVELOPE_UNCHANGED=YES"
echo "CADE_COMMIT_EFFECT_UNCHANGED=YES"
echo "CADE_PUSH_EFFECT_UNCHANGED=YES"
echo "GENERIC_CADE_ROUTE_UNCHANGED=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
