#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY REMOTE PROXY IDENTITY VALIDATION AND LOCAL ACCESS DISPOSITION ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="67e668c0e"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== CLOSED REPOSITORY EVIDENCE ==="
echo "CANONICAL_OPERATOR_UI_ENTRYPOINT=/ui"
echo "REMOTE_OPERATOR_HOST_CANDIDATE=ui.marketingmother.org"
echo "REMOTE_TUNNEL_CANDIDATE=ui-server"
echo "EXECUTION_AUTHORIZATION_ROUTE_SOURCE_EXISTS=YES"
echo "EXECUTION_AUTHORIZATION_ROUTE_ACTIVE_MOUNT=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_PRODUCTION_REACHABILITY=NO"
echo "CLOUDFLARE_ACCESS_POLICY_CONFIGURED=NO_EVIDENCE"
echo "LOCAL_TRUSTED_OPERATOR_IDENTITY=NOT_ESTABLISHED"

echo
echo "=== CLOUDFLARE ACCESS VALIDATION CONTRACT ==="
echo "REMOTE_ASSERTION_HEADER=Cf-Access-Jwt-Assertion"
echo "REMOTE_ASSERTION_FORMAT=SIGNED_JWT"
echo "RAW_HEADER_PRESENCE_IS_SUFFICIENT=NO"
echo "SERVER_MUST_CRYPTOGRAPHICALLY_VALIDATE_ASSERTION=YES"
echo "VALIDATE_SIGNATURE=YES"
echo "VALIDATE_ISSUER=YES"
echo "VALIDATE_AUDIENCE=YES"
echo "VALIDATE_EXPIRATION=YES"
echo "VALIDATE_NOT_BEFORE=YES"
echo "JWKS_SOURCE=TEAM_DOMAIN_/cdn-cgi/access/certs"
echo "TEAM_DOMAIN_MUST_BE_CONFIGURATION_NOT_CLIENT_INPUT=YES"
echo "APPLICATION_AUDIENCE_MUST_BE_CONFIGURATION_NOT_CLIENT_INPUT=YES"
echo "MISSING_ASSERTION=FAIL_CLOSED"
echo "INVALID_SIGNATURE=FAIL_CLOSED"
echo "WRONG_ISSUER=FAIL_CLOSED"
echo "WRONG_AUDIENCE=FAIL_CLOSED"
echo "EXPIRED_ASSERTION=FAIL_CLOSED"
echo "NOT_YET_VALID_ASSERTION=FAIL_CLOSED"

echo
echo "=== NORMALIZED SERVER-VERIFIED OPERATOR IDENTITY ==="
echo "IDENTITY_SOURCE=VALIDATED_CLOUDFLARE_ACCESS_JWT"
echo "PRIMARY_STABLE_IDENTITY_CLAIM=sub"
echo "DISPLAY_OR_AUDIT_IDENTITY_CLAIM=email"
echo "EMAIL_MUST_NOT_BE_READ_FROM_UNVALIDATED_HEADER=YES"
echo "NORMALIZED_IDENTITY_SHAPE=provider,subject,email,issuer,audience,verified"
echo "NORMALIZED_verified=true_ONLY_AFTER_JWT_VALIDATION=YES"
echo "CLIENT_SUPPLIED_authorization_actor_IGNORED_AS_AUTHORITY=YES"
echo "AUTHENTICATION_DOES_NOT_EQUAL_EXECUTION_APPROVAL=YES"

echo
echo "=== SERVER PIPELINE OWNERSHIP ==="
echo "IDENTITY_DERIVATION_OWNER=DEDICATED_SERVER_MIDDLEWARE_OR_HELPER"
echo "IDENTITY_DERIVATION_MUST_OCCUR_BEFORE_EXECUTION_AUTHORIZATION_ROUTE=YES"
echo "EXECUTION_AUTHORIZATION_RUNTIME_MUST_RECEIVE_SERVER_DERIVED_ACTOR=YES"
echo "EXECUTION_AUTHORIZATION_RUNTIME_MUST_NOT_PARSE_CLOUDFLARE_HEADERS_DIRECTLY=YES"
echo "APPROVAL_ARTIFACT_MUST_NOT_PARSE_CLOUDFLARE_HEADERS_DIRECTLY=YES"
echo "CADE_MUST_NOT_PARSE_CLOUDFLARE_HEADERS=YES"
echo "GIT_EFFECT_MODULES_MUST_NOT_PARSE_CLOUDFLARE_HEADERS=YES"

echo
echo "=== LOCAL ACCESS DISPOSITION ==="
echo "LOCAL_/ui_ACCESS_MAY_REMAIN_AVAILABLE_FOR_NON_EXECUTION_UI_USE=YES"
echo "LOCAL_EXECUTION_AUTHORIZATION_IDENTITY=NOT_ESTABLISHED"
echo "LOCALHOST_POSSESSION_AS_EXECUTION_IDENTITY=NOT_AUTHORIZED"
echo "LOCAL_REQUEST_MAY_NOT_SYNTHESIZE_VERIFIED_OPERATOR=YES"
echo "LOCAL_REQUEST_MAY_NOT_REUSE_CLIENT_SUPPLIED_ACTOR=YES"
echo "INITIAL_EXECUTION_AUTHORIZATION_TRUST_MODE=VERIFIED_REMOTE_IDENTITY_ONLY"
echo "RATIONALE=AVOID_CREATING_SECOND_UNVERIFIED_OPERATOR_AUTHORITY_MODEL"
echo "FUTURE_LOCAL_EXECUTION_IDENTITY=SEPARATE_CLASSIFICATION_IF_REQUIRED"

echo
echo "=== ROUTE MOUNT CONSEQUENCE ==="
echo "EXECUTION_AUTHORIZATION_ROUTE_MUST_REMAIN_UNMOUNTED_NOW=YES"
echo "ROUTE_MOUNT_REQUIRES_SERVER_VERIFIED_IDENTITY_BOUNDARY_FIRST=YES"
echo "ROUTE_MOUNT_REQUIRES_CLOUDFLARE_ACCESS_POLICY_OR_EQUIVALENT_TRUST_BOUNDARY_FIRST=YES"
echo "ROUTE_MOUNT_DOES_NOT_GRANT_COMMIT_AUTHORITY_BY_ITSELF=YES"
echo "ROUTE_MOUNT_DOES_NOT_GRANT_PUSH_AUTHORITY_BY_ITSELF=YES"
echo "DURABLE_USER_APPROVAL_REMAINS_SEPARATE_SUCCESSOR_UNIT=YES"

echo
echo "=== DIRECT BYPASS POLICY ==="
echo "REMOTE_EXECUTION_AUTHORIZATION_WITHOUT_VALID_ACCESS_JWT=BLOCK"
echo "DIRECT_NETWORK_BYPASS_TO_EXECUTION_AUTHORIZATION=BLOCK"
echo "LOCAL_UNVERIFIED_EXECUTION_AUTHORIZATION=BLOCK"
echo "MODEL_OR_AGENT_SELF_ASSERTED_OPERATOR_IDENTITY=BLOCK"
echo "CLIENT_SELECTED_OPERATOR_IDENTITY=BLOCK"

echo
echo "=== PRESERVED AUTHORITY MODEL ==="
echo "USER_INTENT_AUTHORITY=UNCHANGED"
echo "MATILDA_INTERPRETATION_AUTHORITY=UNCHANGED"
echo "AUTHENTICATED_OPERATOR_IDENTITY_IS_NOT_INTENT=YES"
echo "AUTHENTICATED_OPERATOR_IDENTITY_IS_NOT_APPROVAL=YES"
echo "MATILDA_SELF_APPROVAL=PROHIBITED"
echo "CADE_SELF_APPROVAL=PROHIBITED"
echo "GENERIC_MUTATION_AUTHORITY=DISABLED"
echo "GENERIC_SHELL_AUTHORITY=DISABLED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=DISABLED"

echo
echo "=== MINIMUM NEXT IMPLEMENTATION PRECONDITION ==="
echo "PRECONDITION_1=CLOUDFLARE_ACCESS_APPLICATION_AND_POLICY_FOR_CANONICAL_REMOTE_ENTRYPOINT"
echo "PRECONDITION_2=KNOWN_TEAM_DOMAIN"
echo "PRECONDITION_3=KNOWN_APPLICATION_AUDIENCE_TAG"
echo "PRECONDITION_4=SERVER_SIDE_JWT_VALIDATION_DEPENDENCY_OR_EQUIVALENT_VERIFIER"
echo "PRECONDITION_5=DIRECT_BYPASS_POLICY"
echo "PRECONDITION_6=TEMP_OR_NON_PRODUCTION_VALIDATION_PATH"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_CLOUDFLARE_ACCESS_CONFIGURATION_UNIT_AND_SERVER_IDENTITY_VALIDATOR_AS_SEPARATE_ORDERED_UNITS"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_AUTHORIZED=NO"
echo "DURABLE_EXECUTION_APPROVAL_IMPLEMENTATION_AUTHORIZED=NO"
echo "ACTIVE_REPOSITORY_EXECUTION_AUTHORIZED=NO"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
