#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY MISSION CONTROL INTAKE CLOSURE READINESS ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=MISSION_CONTROL_INTAKE"
echo "DR_CHECKPOINT=20260825_142343"
echo "DR_CHECKPOINT_COMMIT=00ec40cf"
echo "LATEST_VALIDATED_INTAKE_STATE=1985a01c"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED INTAKE STATE ==="
echo "MISSION_CONTROL_PROJECT_SCOPED_INTAKE=IMPLEMENTED"
echo "MISSION_CONTROL_PROJECT_SCOPED_INTAKE_VALIDATION=PASS"
echo "CLIENT_MISSION_READ_INPUT=projectId"
echo "ACTIVE_PROJECT_SOURCE=ProjectContextProvider.registry.activeProjectId"
echo "SERVER_OPERATIONAL_AUTHORITY_RESOLUTION=AUTHORITATIVE"
echo "HARDCODED_corridor-smoke=REMOVED"
echo "MISSION_CONTROL_PACKAGE_AUTHORITY=NONE"

echo
echo "=== TYPECHECK ==="
npx tsc --noEmit --pretty false
echo "TYPECHECK=PASS"

echo
echo "=== TARGETED CLIENT VALIDATION ==="
npx tsx --test client/src/mission-control/mission-control-project-scoped-intake.test.ts

echo
echo "=== STATIC INTAKE CONTRACT ==="
if rg -n 'ACTIVE_PACKAGE_ID|corridor-smoke' \
  client/src/shell/MissionDashboardWorkspace.tsx \
  client/src/mission-control/MissionControlProvider.tsx \
  client/src/mission-control/missionReadApi.ts; then
  echo "HARDCODED_PACKAGE_AUTHORITY_ABSENT=NO"
  exit 1
fi
echo "HARDCODED_PACKAGE_AUTHORITY_ABSENT=YES"

rg -n 'activeProjectId' client/src/shell/MissionDashboardWorkspace.tsx >/dev/null
echo "ACTIVE_PROJECT_INTAKE_WIRING=PASS"

rg -n '/api/mission-read/' client/src/mission-control/missionReadApi.ts >/dev/null
echo "PROJECT_SCOPED_ENDPOINT_WIRING=PASS"

echo
echo "=== AUTHORITY NON-ESCALATION ==="
echo "MISSION_CONTROL_SELECTS_ACTIVE_PROJECT=NO"
echo "MISSION_CONTROL_SELECTS_OPERATIONAL_PACKAGE=NO"
echo "MISSION_CONTROL_MUTATES_OPERATIONAL_PACKAGE_AUTHORITY=NO"
echo "MISSION_CONTROL_USES_BROWSER_PACKAGE_STATE_AS_AUTHORITY=NO"
echo "MISSION_CONTROL_USES_DELEGATION_AS_SELECTION_AUTHORITY=NO"
echo "MISSION_CONTROL_CREATES_DELEGATION=NO"
echo "MISSION_CONTROL_CONFERS_VALIDATION_AUTHORITY=NO"
echo "MISSION_CONTROL_CONFERS_ROUTING_AUTHORITY=NO"
echo "MISSION_CONTROL_CONFERS_ASSIGNMENT_AUTHORITY=NO"
echo "MISSION_CONTROL_CONFERS_EXECUTION_AUTHORITY=NO"

echo
echo "=== FAILURE CONTRACT ==="
echo "NO_ACTIVE_PROJECT=NO_MISSION"
echo "NO_OPERATIONAL_PACKAGE_AUTHORITY=NO_ACTIVE_MISSION"
echo "SERVER_404=NO_ACTIVE_MISSION"
echo "SERVER_409=FAIL_CLOSED_ERROR"
echo "SERVER_500=FAIL_CLOSED_ERROR"
echo "HARDCODED_PACKAGE_FALLBACK=NO"
echo "NEWEST_PACKAGE_FALLBACK=NO"
echo "STALE_PREVIOUS_PROJECT_MISSION_PRESERVED=NO"

echo
echo "=== CORRIDOR BOUNDARY ==="
echo "PROJECT_BOUND_HANDOFF_REMAINS_CLOSED=YES"
echo "MISSION_CONTROL_INTAKE_IMPLEMENTATION_STARTED=YES"
echo "MISSION_CONTROL_INTAKE_IMPLEMENTATION_COMPLETE=YES"
echo "HANDOFF_VALIDATION_AND_PHASE_CLOSURE_STARTED=NO"
echo "CORRIDOR_5_REMAINS_SEPARATE=YES"

echo
echo "=== CLOSURE READINESS DETERMINATION ==="
echo "ACTIVE_PROJECT_CONSUMPTION_REQUIREMENT=SATISFIED"
echo "PROJECT_SCOPED_MISSION_READ_REQUEST_REQUIREMENT=SATISFIED"
echo "HARDCODED_PACKAGE_SELECTION_REMOVAL_REQUIREMENT=SATISFIED"
echo "NO_PACKAGE_SELECTION_AUTHORITY_REQUIREMENT=SATISFIED"
echo "FAIL_CLOSED_ERROR_HANDLING_REQUIREMENT=SATISFIED"
echo "STALE_PROJECT_MISSION_CLEAR_REQUIREMENT=SATISFIED"
echo "TARGETED_VALIDATION=PASS"
echo "AUTHORITY_NON_ESCALATION=PRESERVED"
echo "MISSION_CONTROL_INTAKE_SCOPE_REQUIREMENTS=SATISFIED"
echo "MISSION_CONTROL_INTAKE_CLOSURE_READY=YES"
echo "MISSION_CONTROL_INTAKE_CORRIDOR=NOT_YET_FORMALLY_CLOSED"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=FORMALLY_CLOSE_MISSION_CONTROL_INTAKE_CORRIDOR_AND_ADVANCE_TO_HANDOFF_VALIDATION_AND_PHASE_CLOSURE"
