#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY MINIMUM OPERATOR IDENTITY BOUNDARY FROM ENTRYPOINT EVIDENCE ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "DURABLE_EXECUTION_AUTHORIZATION_IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="2d98684b8"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== ESTABLISHED ENTRYPOINT EVIDENCE ==="
echo "CANONICAL_UI_GOVERNANCE_DOC_DECLARES_/ui_SOLE_VALID_ENTRYPOINT=YES"
echo "ACTIVE_SERVER_INDEX_DEFINES_/ui_OPERATOR_COCKPIT=YES"
echo "ACTIVE_SERVER_PORT_DEFAULT=3000"
echo "TRACKED_REMOTE_UI_HOSTNAME=ui.marketingmother.org"
echo "UI_DEPLOY_TOOL_TUNNEL_TARGET=http://localhost:59272"
echo "UI_DEPLOY_TOOL_TUNNEL_NAME=ui-server"
echo "EXECUTION_AUTHORIZATION_ROUTE_SOURCE_EXISTS=YES"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNTED_IN_ACTIVE_server/index.ts=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_CURRENT_PRODUCTION_REACHABILITY=NOT_ESTABLISHED"
echo "LOCALHOST_3000_RUNTIME_AUTHORITY=HISTORICALLY_AMBIGUOUS"
echo "CLOUDFLARE_ACCESS_IDENTITY=NOT_ESTABLISHED"

echo
echo "=== CRITICAL CLASSIFICATION ==="
echo "CANONICAL_OPERATOR_UI_ENTRYPOINT=/ui"
echo "CANONICAL_REMOTE_OPERATOR_HOST_CANDIDATE=ui.marketingmother.org"
echo "CANONICAL_REMOTE_TUNNEL_CANDIDATE=ui-server"
echo "EXECUTION_AUTHORIZATION_ENDPOINT_SHOULD_NOT_BE_TREATED_AS_ACTIVE_PRODUCTION_SURFACE=YES"
echo "IDENTITY_BOUNDARY_DOES_NOT_NEED_TO_WRAP_AN_UNMOUNTED_EXECUTION_ROUTE_YET=YES"
echo "FIRST_IDENTITY_BOUNDARY_SHOULD_ATTACH_TO_CANONICAL_OPERATOR_REQUEST_PATH=YES"

echo
echo "=== SINGLE NORMALIZED OPERATOR IDENTITY MODEL ==="
echo "MODEL_NAME=SERVER_VERIFIED_OPERATOR_IDENTITY"
echo "MODEL_PURPOSE=AUTHENTICATE_REQUESTING_OPERATOR_ONLY"
echo "MODEL_IS_EXECUTION_APPROVAL=NO"
echo "MODEL_IS_INTENT_AUTHORITY=NO"
echo "MODEL_IS_MATILDA_INTERPRETATION_AUTHORITY=NO"
echo "MODEL_MUST_NOT_BE_CLIENT_ASSERTED=YES"

echo
echo "=== REMOTE INPUT MODE ==="
echo "REMOTE_ENTRYPOINT=ui.marketingmother.org"
echo "REMOTE_TRANSPORT=ui-server_CLOUDFLARE_TUNNEL"
echo "REMOTE_REQUIRED_TRUST_LAYER=CLOUDFLARE_ACCESS_OR_EQUIVALENT_VERIFIED_PROXY"
echo "REMOTE_REQUIRED_ASSERTION=SERVER_VALIDATED_PROXY_IDENTITY"
echo "RAW_PROXY_HEADER_WITHOUT_VALIDATION_TRUSTED=NO"
echo "REMOTE_DIRECT_BYPASS_MUST_FAIL_CLOSED=YES"

echo
echo "=== LOCAL INPUT MODE ==="
echo "LOCAL_ENTRYPOINT=/ui_ON_CANONICAL_APPLICATION_RUNTIME"
echo "LOCAL_IDENTITY_MODE=NOT_YET_ESTABLISHED"
echo "LOCALHOST_POSSESSION_ALONE_AS_IDENTITY=NOT_YET_AUTHORIZED"
echo "LOCAL_REQUEST_MUST_NOT_SYNTHESIZE_OPERATOR_IDENTITY=YES"
echo "LOCAL_MODE_MAY_NOT_BYPASS_REMOTE_TRUST_RULES_FOR_EXECUTION_AUTHORIZATION_WITHOUT_SEPARATE_CLASSIFICATION=YES"

echo
echo "=== ROUTE REACHABILITY CONSEQUENCE ==="
echo "EXECUTION_AUTHORIZATION_ROUTE_MUST_REMAIN_UNMOUNTED_UNTIL_TRUSTED_OPERATOR_IDENTITY_BOUNDARY_EXISTS=YES"
echo "MOUNTING_EXECUTION_AUTHORIZATION_ROUTE_IS_SEPARATE_FUTURE_UNIT=YES"
echo "MOUNTING_ROUTE_DOES_NOT_AUTOMATICALLY_AUTHORIZE_COMMIT_OR_PUSH=YES"
echo "DURABLE_EXECUTION_APPROVAL_IMPLEMENTATION_MUST_WAIT_FOR_IDENTITY_BOUNDARY=YES"
echo "ACTIVE_REPOSITORY_ENABLEMENT_MUST_WAIT_FOR_IDENTITY_BOUNDARY_AND_DURABLE_APPROVAL=YES"

echo
echo "=== INSPECT AUTHORITATIVE /ui GOVERNANCE ==="
for f in \
  docs/PHASE_GOVERNANCE_CONTRACT_v1.md \
  ops/SAFE_MIGRATION_SNAPSHOT.md \
  ops/UI_FINAL_LOCK.md \
  server/ui-route.ts \
  tools/deploy-ui.sh
do
  if [[ -f "${f}" ]]; then
    echo
    echo "--- ${f} ---"
    nl -ba "${f}" | sed -n '1,260p'
  fi
done

echo
echo "=== INSPECT NAMED LOCAL CLOUDFLARE CONFIGS FOR HOST/SERVICE ONLY ==="
for f in \
  "${HOME}/.cloudflared/ui-server.yml" \
  "${HOME}/.cloudflared/matilda.yml"
do
  if [[ -f "${f}" ]]; then
    echo
    echo "--- ${f} ---"
    grep -E '^[[:space:]]*(tunnel|hostname|service):' "${f}" \
      | sed -E 's/(credentials-file:).*/\1 <REDACTED_PATH>/I' \
      || true
  fi
done

echo
echo "=== VERIFY EXECUTION AUTHORIZATION ROUTE IS NOT ACTIVE-MOUNTED ==="
if grep -q 'matilda-execution-authorization-route' server/index.ts; then
  echo "ACTIVE_SERVER_IMPORTS_EXECUTION_AUTHORIZATION_ROUTE=YES"
else
  echo "ACTIVE_SERVER_IMPORTS_EXECUTION_AUTHORIZATION_ROUTE=NO"
fi

if grep -q '/api/matilda/execution-authorization' server/index.ts; then
  echo "ACTIVE_SERVER_DIRECTLY_DEFINES_EXECUTION_AUTHORIZATION_PATH=YES"
else
  echo "ACTIVE_SERVER_DIRECTLY_DEFINES_EXECUTION_AUTHORIZATION_PATH=NO"
fi

echo
echo "=== SMALLEST NEXT DESIGN QUESTION ==="
echo "QUESTION_1=WHAT_EXACT_CLOUDFLARE_ACCESS_ASSERTION_SHOULD_THE_SERVER_VALIDATE"
echo "QUESTION_2=WHERE_SHOULD_SERVER_VERIFIED_OPERATOR_IDENTITY_BE_DERIVED_IN_THE_EXPRESS_REQUEST_PIPELINE"
echo "QUESTION_3=HOW_TO_FAIL_CLOSED_FOR_REMOTE_REQUESTS_WITHOUT_VALID_ASSERTION"
echo "QUESTION_4=WHETHER_LOCAL_OPERATOR_REQUESTS_REQUIRE_A_SEPARATE_VERIFIED_INPUT_OR_SHOULD_EXECUTION_AUTHORIZATION_BE_REMOTE_TRUST_BOUNDARY_ONLY_INITIALLY"
echo "QUESTION_5=HOW_TO_KEEP_AUTHENTICATION_SEPARATE_FROM_USER_EXECUTION_APPROVAL"

echo
echo "=== CURRENT DETERMINATION ==="
echo "MINIMUM_IDENTITY_BOUNDARY_CLASSIFIED=PARTIALLY"
echo "REMOTE_CANONICAL_ENTRYPOINT=SUFFICIENTLY_CLASSIFIED"
echo "REMOTE_TRUST_MECHANISM=CLOUDFLARE_ACCESS_REQUIRED_BUT_NOT_CONFIGURED"
echo "LOCAL_TRUST_MECHANISM=UNRESOLVED"
echo "EXECUTION_AUTHORIZATION_ROUTE_ACTIVE_REACHABILITY=NO"
echo "NEXT_ACTION=CLASSIFY_REMOTE_PROXY_IDENTITY_VALIDATION_CONTRACT_AND_LOCAL_ACCESS_DISPOSITION"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "CANONICAL_PACKAGE_APPROVAL_UNCHANGED=YES"
echo "GOVERNANCE_ENVELOPE_UNCHANGED=YES"
echo "EXECUTION_AUTHORIZATION_RUNTIME_UNCHANGED=YES"
echo "EXECUTION_APPROVAL_GATE_UNCHANGED=YES"
echo "CADE_LOCAL_COMMIT_EFFECT_UNCHANGED=YES"
echo "CADE_REMOTE_PUSH_EFFECT_UNCHANGED=YES"
echo "GENERIC_CADE_ROUTE_UNCHANGED=YES"
echo "GENERIC_MUTATION_AUTHORITY_DISABLED=YES"
echo "GENERIC_SHELL_AUTHORITY_DISABLED=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_DISABLED=YES"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
