#!/usr/bin/env bash
set -euo pipefail

cd "/Users/marcela-dev/Projects/motherboard-systems-hq-clean"

BRANCH="feature/support-source-references-runtime"
BASELINE="24cefee47"

git fetch origin "$BRANCH"

test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$BASELINE"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$BASELINE"
test -z "$(git diff --cached --name-only)"

echo "===== ATLAS OPERATOR PRESENTATION CLASSIFICATION ====="
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "BASELINE=$BASELINE"

echo
echo "===== VERIFIED EVIDENCE ====="
echo "EXISTING_ATLAS_STATUS_CARD=YES"
echo "ATLAS_STATUS_CARD_CURRENTLY_SUBSYSTEM_HEALTH_ORIENTED=YES"
echo "OBSERVATIONAL_WORKSPACE_EXISTS=YES"
echo "EXECUTION_INSPECTOR_EXISTS=YES"
echo "ACTIVE_PROJECT_UI_SOURCE=ESTABLISHED"
echo "ACTIVE_PROJECT_UI_SOURCE_DETAIL=/events/projects -> state.activeProject"
echo "ACTIVE_CONVERSATION_UI_SOURCE=NOT_ESTABLISHED_BY_CURRENT_INSPECTION"
echo "PREEXECUTION_ENDPOINT_REQUIRES_PROJECT_ID=YES"
echo "PREEXECUTION_ENDPOINT_REQUIRES_CONVERSATION_ID=YES"

echo
echo "===== PRESENTATION BOUNDARY ====="
echo "SAFE_TO_CALL_PREEXECUTION_FROM_UI_NOW=NO"
echo "BLOCKER=NO_VERIFIED_ACTIVE_CONVERSATION_ID_SOURCE"
echo "MISSING_SCOPE_INFERENCE=FORBIDDEN"
echo "HARDCODE_CONVERSATION_ID=FORBIDDEN"
echo "PROJECT_ONLY_QUERY=FORBIDDEN"
echo "ATLAS_STATUS_CARD_INTEGRATION=NOT_YET_JUSTIFIED"
echo "EXECUTION_INSPECTOR_INTEGRATION=FORBIDDEN"
echo "SEPARATE_PREEXECUTION_OPERATOR_SURFACE=PLAUSIBLE_BUT_NOT_AUTHORIZED"
echo "UI_IMPLEMENTATION_READINESS=BLOCKED_ON_CONVERSATION_SCOPE_SOURCE"

echo
echo "===== SEMANTIC PRESENTATION CONTRACT ====="
echo "SOURCE_KIND_MUST_REMAIN_VISIBLE=YES"
echo "AUTHORITY_STATUS_MUST_REMAIN_VISIBLE=YES"
echo "CHRONOLOGY_MUST_BE_LABELED_AS_OBSERVED_SEQUENCE=YES"
echo "CHRONOLOGY_AS_CAUSATION=FORBIDDEN"
echo "LINEAGE_GROUPING_MUST_REMAIN_EXPLICIT_ONLY=YES"
echo "MATILDA_AUTHORED_EVIDENCE_LABEL_MUST_BE_PRESERVED=YES"
echo "LIVING_DRAFT_NON_AUTHORITY_MUST_BE_PRESERVED=YES"
echo "PENDING_APPROVAL_STATUS_MUST_NOT_IMPLY_APPROVAL=YES"
echo "CANONICAL_PACKAGE_AUTHORITY_MUST_NOT_BE_COLLAPSED_WITH_DRAFT=YES"
echo "RAW_OBSERVATIONS_VS_GROUPED_SEQUENCE=PRESENTATION_CHOICE_DEFERRED"

echo
echo "===== SCOPE-FIRST DETERMINATION ====="
echo "NEXT_QUESTION=WHERE_DOES_CURRENT_UI_OBTAIN_OR_OWN_ACTIVE_CONVERSATION_ID"
echo "NEXT_ACTION=INVESTIGATE_ACTIVE_CONVERSATION_IDENTITY_BOUNDARY"
echo "IMPLEMENTATION=NONE"
echo "UI_CHANGE=NONE"
echo "ROUTE_CHANGE=NONE"
echo "REASONER_CHANGE=NONE"
echo "AGGREGATOR_CHANGE=NONE"
echo "MATILDA_CHANGE=NONE"
echo "DATABASE_CHANGE=NONE"
echo "DOGFOOD_CLEANUP=FROZEN"

echo
echo "===== TARGETED CONVERSATION ID SEARCH ====="
grep -RniE -B25 -A80 \
  'conversationId|conversation_id|activeConversation|currentConversation|conversation-id|conversation_id' \
  public server \
  --include='*.js' \
  --include='*.ts' \
  --include='*.html' \
  2>/dev/null | head -n 3000 || true

echo
echo "===== WORKTREE ====="
git status --short
