#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY CANONICAL OPERATOR ENTRYPOINT AND SINGLE IDENTITY INTERFACE ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "DURABLE_EXECUTION_AUTHORIZATION_IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="98807aebb"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED BASELINE ==="
echo "CLOUDFLARE_TUNNEL_LAYER=TRANSPORT_ONLY"
echo "CLOUDFLARE_ACCESS_LAYER=NOT_ESTABLISHED"
echo "TRUSTED_OPERATOR_IDENTITY_PREREQUISITE=OPEN"
echo "APPLICATION_ACCOUNT_SYSTEM_REQUIRED_NOW=NO"
echo "EXECUTION_AUTHORIZATION_COMPILATION_MUST_WAIT=YES"
echo "ACTIVE_REPOSITORY_ENABLEMENT_MUST_WAIT=YES"

echo
echo "=== INSPECT LOCAL NAMED TUNNEL CONFIGS ==="
for candidate in \
  "${HOME}/.cloudflared/matilda.yml" \
  "${HOME}/.cloudflared/ui-server.yml"
do
  if [[ -f "${candidate}" ]]; then
    echo
    echo "--- ${candidate} ---"
    sed -E \
      -e 's/(token:[[:space:]]*).*/\1<REDACTED>/I' \
      -e 's/(secret:[[:space:]]*).*/\1<REDACTED>/I' \
      -e 's/(credentials-file:[[:space:]]*).*/\1<REDACTED_PATH>/I' \
      "${candidate}" \
      | sed -n '1,320p'
  fi
done

echo
echo "=== INSPECT TRACKED OPERATOR HOSTNAME REFERENCES ==="
git grep -n -I -E \
  'ui\.marketingmother\.org|marketingmother\.org|matilda.*host|host.*matilda|operator cockpit|Motherboard Systems HQ|/ui|dashboard' \
  -- \
  server \
  routes \
  client/src \
  docs \
  tools \
  Motherboard_Project_Scope.txt \
  2>/dev/null \
  | sed -n '1,1400p' || true

echo
echo "=== INSPECT ACTIVE SERVER ROUTE MOUNTING ==="
nl -ba server/index.ts | sed -n '1,220p'

echo
echo "=== INSPECT EXECUTION AUTHORIZATION ROUTE MOUNT REACHABILITY ==="
git grep -n -I \
  'matilda-execution-authorization-route' \
  -- server routes \
  || true

git grep -n -I \
  '/api/matilda/execution-authorization' \
  -- server routes client/src \
  || true

echo
echo "=== INSPECT DIRECT LOCAL ACCESS SURFACES ==="
git grep -n -I -E \
  'localhost:3000|127\.0\.0\.1:3000|localhost:59272|127\.0\.0\.1:59272|0\.0\.0\.0:3000|/ui' \
  -- \
  server \
  client/src \
  docs \
  tools \
  '*.md' \
  '*.txt' \
  2>/dev/null \
  | sed -n '1,1200p' || true

echo
echo "=== ENTRYPOINT CLASSIFICATION QUESTIONS ==="
echo "QUESTION_1=DOES_ui-server_CONFIG_DECLARE_THE_CURRENT_OPERATOR_HOSTNAME"
echo "QUESTION_2=DOES_matilda_CONFIG_DECLARE_A_SEPARATE_AGENT_SPECIFIC_REMOTE_ENTRYPOINT"
echo "QUESTION_3=IS_SERVER_INDEX_PORT_3000_THE_CANONICAL_BACKEND_FOR_THE_OPERATOR_UI"
echo "QUESTION_4=IS_EXECUTION_AUTHORIZATION_ROUTE_CURRENTLY_MOUNTED_IN_THE_ACTIVE_SERVER_ENTRYPOINT"
echo "QUESTION_5=CAN_ONE_OPERATOR_IDENTITY_INTERFACE_SERVE_BOTH_VERIFIED_REMOTE_AND_TRUSTED_LOCAL_REQUESTS"

echo
echo "=== SINGLE IDENTITY INTERFACE CONTRACT ==="
echo "INTERFACE_ROLE=SERVER_VERIFIED_OPERATOR_IDENTITY"
echo "INTERFACE_MUST_NOT_GRANT_EXECUTION_APPROVAL_BY_ITSELF=YES"
echo "INTERFACE_MUST_NOT_ACCEPT_CLIENT_SELECTED_ACTOR=YES"
echo "REMOTE_IDENTITY_SOURCE_MUST_BE_VALIDATED_PROXY_ASSERTION=YES"
echo "LOCAL_IDENTITY_SOURCE_MUST_BE_EXPLICITLY_CLASSIFIED_BEFORE_USE=YES"
echo "REMOTE_AND_LOCAL_REQUESTS_MUST_NORMALIZE_TO_ONE_OPERATOR_IDENTITY_SHAPE=YES"
echo "EXECUTION_AUTHORIZATION_MUST_CONSUME_NORMALIZED_SERVER_VERIFIED_IDENTITY=YES"
echo "MATILDA_SELF_AUTHORIZATION=PROHIBITED"
echo "CADE_SELF_AUTHORIZATION=PROHIBITED"

echo
echo "=== DECISION RULES ==="
echo "IF_ui-server_IS_CANONICAL_OPERATOR_HOST=CLASSIFY_ACCESS_BOUNDARY_ON_ui-server_ENTRYPOINT"
echo "IF_MOTHERBOARD_BACKEND_HAS_SEPARATE_CANONICAL_HOST=USE_THAT_HOST_INSTEAD"
echo "IF_EXECUTION_AUTHORIZATION_ROUTE_IS_NOT_MOUNTED=DO_NOT_TREAT_IT_AS_PRODUCTION_REACHABLE"
echo "IF_LOCAL_AND_REMOTE_ACCESS_BOTH_REQUIRED=CLASSIFY_ONE_NORMALIZED_OPERATOR_IDENTITY_INTERFACE_WITH_TWO_VERIFIED_INPUT_MODES"
echo "IF_LOCAL_TRUST_CANNOT_BE_VERIFIED=REMOTE_VERIFIED_ACCESS_ONLY_FOR_EXECUTION_AUTHORIZATION"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "CANONICAL_PACKAGE_APPROVAL_UNCHANGED=YES"
echo "GOVERNANCE_ENVELOPE_UNCHANGED=YES"
echo "EXECUTION_AUTHORIZATION_RUNTIME_UNCHANGED=YES"
echo "EXECUTION_APPROVAL_GATE_UNCHANGED=YES"
echo "CADE_LOCAL_COMMIT_EFFECT_UNCHANGED=YES"
echo "CADE_REMOTE_PUSH_EFFECT_UNCHANGED=YES"
echo "GENERIC_CADE_ROUTE_UNCHANGED=YES"
echo "GENERIC_MUTATION_AUTHORITY_DISABLED=YES"
echo "GENERIC_SHELL_AUTHORITY_DISABLED=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_DISABLED=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=USE_OBSERVED_ENTRYPOINT_AND_ROUTE_MOUNT_EVIDENCE_TO_CLASSIFY_THE_MINIMUM_OPERATOR_IDENTITY_BOUNDARY"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
