#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY HANDOFF VALIDATION AND PHASE CLOSURE SCOPE ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=HANDOFF_VALIDATION_AND_PHASE_CLOSURE"
echo "MISSION_CONTROL_INTAKE_CLOSURE_COMMIT=a7eb61ef"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED PREDECESSOR CORRIDORS ==="
echo "CORRIDOR_1=OPERATIONAL_PACKAGE_AUTHORITY"
echo "CORRIDOR_1_STATUS=CLOSED"
echo "CORRIDOR_2=PACKAGE_HANDOFF_CONTRACT"
echo "CORRIDOR_2_STATUS=CLOSED"
echo "CORRIDOR_3=PROJECT_BOUND_HANDOFF"
echo "CORRIDOR_3_STATUS=CLOSED"
echo "CORRIDOR_4=MISSION_CONTROL_INTAKE"
echo "CORRIDOR_4_STATUS=CLOSED"

echo
echo "=== CORRIDOR 5 PURPOSE ==="
echo "PURPOSE_1=VALIDATE_END_TO_END_AUTHORITATIVE_HANDOFF_CHAIN"
echo "PURPOSE_2=VERIFY_EXACT_IDENTITY_CONTINUITY_ACROSS_BOUNDARIES"
echo "PURPOSE_3=VERIFY_FAIL_CLOSED_BEHAVIOR_AND_NON_ESCALATION"
echo "PURPOSE_4=VERIFY_MISSION_CONTROL_REMAINS_READ_ONLY_CONSUMER"
echo "PURPOSE_5=DETERMINE_PHASE_CLOSURE_READINESS"
echo "NEW_RUNTIME_CAPABILITY_REQUIRED=NOT_ESTABLISHED"

echo
echo "=== END-TO-END IDENTITY CONTRACT ==="
echo "CANONICAL_PACKAGE_IDENTITY=project_id+package_id+package_version"
echo "OPERATIONAL_AUTHORITY_IDENTITY=project_id+package_id+package_version"
echo "MISSION_PROJECTION_IDENTITY=project_id+package_id+package_version"
echo "MISSION_READ_IDENTITY=project_id+package_id+package_version"
echo "MISSION_CONTROL_INPUT_IDENTITY=project_id"
echo "MISSION_CONTROL_PACKAGE_SELECTION_AUTHORITY=NONE"
echo "SERVER_RESOLVES_OPERATIONAL_PACKAGE_AUTHORITY=YES"

echo
echo "=== LIVE HANDOFF STATE ==="
sqlite3 -header -column db/main.db "
SELECT
  a.project_id,
  a.package_id,
  a.package_version,
  a.selected_at,
  c.status AS canonical_status,
  g.project_id AS mission_project_id,
  g.package_id AS mission_package_id,
  g.package_version AS mission_package_version
FROM operational_package_authority a
JOIN matilda_canonical_packages c
  ON c.project_id = a.project_id
 AND c.package_id = a.package_id
 AND c.package_version = a.package_version
JOIN governance_packages g
  ON g.project_id = a.project_id
 AND g.package_id = a.package_id
 AND g.package_version = a.package_version
ORDER BY a.project_id;
"

echo
echo "=== SERVER HANDOFF CONTRACT ==="
rg -n -C 12 \
  'projectId|getOperationalPackageForProject|package_version|identity mismatch|projection is missing' \
  routes/api-mission-read.ts \
  db/mission-read-repository.ts \
  2>/dev/null || true

echo
echo "=== CLIENT INTAKE CONTRACT ==="
rg -n -C 12 \
  'activeProjectId|loadMission|clearMission|getMissionReadModel|/api/mission-read/' \
  client/src/shell/MissionDashboardWorkspace.tsx \
  client/src/mission-control/MissionControlProvider.tsx \
  client/src/mission-control/missionReadApi.ts \
  2>/dev/null || true

echo
echo "=== VALIDATION REQUIREMENTS TO CLASSIFY ==="
echo "VALIDATION_1=TYPECHECK"
echo "VALIDATION_2=OPERATIONAL_AUTHORITY_EXACT_LIVE_BINDING"
echo "VALIDATION_3=CANONICAL_TO_MISSION_PROJECTION_IDENTITY_MATCH"
echo "VALIDATION_4=PROJECT_SCOPED_SERVER_AUTHORITY_RESOLUTION"
echo "VALIDATION_5=MISSION_READ_EXACT_VERSION_LOOKUP"
echo "VALIDATION_6=MISSION_CONTROL_PROJECT_SCOPED_REQUEST"
echo "VALIDATION_7=HARDCODED_PACKAGE_AUTHORITY_ABSENT"
echo "VALIDATION_8=NO_NEWEST_OR_SUCCESSOR_INFERENCE"
echo "VALIDATION_9=FAIL_CLOSED_MISSING_OR_MISMATCHED_STATE"
echo "VALIDATION_10=NO_AUTHORITY_MUTATION_DURING_READ"
echo "VALIDATION_11=MISSION_CONTROL_NON_ESCALATION"
echo "VALIDATION_12=PREDECESSOR_CORRIDOR_CLOSURE_EVIDENCE_PRESENT"

echo
echo "=== PHASE-CLOSURE QUESTIONS ==="
echo "QUESTION_1=DOES_THE_FULL_HANDOFF_CHAIN_PRESERVE_EXACT_IDENTITY"
echo "QUESTION_2=DOES_ANY_LAYER_REINTRODUCE_PACKAGE_SELECTION_OUTSIDE_OPERATIONAL_AUTHORITY"
echo "QUESTION_3=DO_FAILURE_PATHS_REMAIN_FAIL_CLOSED"
echo "QUESTION_4=DOES_MISSION_CONTROL_REMAIN_READ_ONLY"
echo "QUESTION_5=IS_ANY_ADDITIONAL_PRODUCTION_IMPLEMENTATION_REQUIRED_BEFORE_PHASE_CLOSURE"
echo "QUESTION_6=ARE_ALL_FIVE_CORRIDOR_REQUIREMENTS_SATISFIED"

echo
echo "=== AUTHORITY NON-ESCALATION ==="
echo "MISSION_CONTROL_SELECTS_ACTIVE_PROJECT=NO"
echo "MISSION_CONTROL_SELECTS_OPERATIONAL_PACKAGE=NO"
echo "MISSION_READ_SELECTS_OPERATIONAL_PACKAGE=NO"
echo "DELEGATION_SELECTS_OPERATIONAL_PACKAGE=NO"
echo "ROUTING_AUTHORITY=NO"
echo "ASSIGNMENT_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"

echo
echo "=== CURRENT SCOPE DETERMINATION ==="
echo "HANDOFF_VALIDATION_AND_PHASE_CLOSURE_CORRIDOR=ACTIVE"
echo "CORRIDOR_5_IMPLEMENTATION_STARTED=NO"
echo "PHASE_CLOSURE_STARTED=NO"
echo "VALIDATION_FIRST=YES"
echo "ADDITIONAL_IMPLEMENTATION_REQUIREMENT=TO_BE_DETERMINED_FROM_EVIDENCE"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_EXACT_END_TO_END_VALIDATION_UNIT_AND_PHASE_CLOSURE_CRITERIA_BEFORE_ANY_IMPLEMENTATION"
