#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY OPTION B RUNTIME INTEGRATION DEFECT ==="
echo "EXPECTED_HEAD_PREFIX=90b8ef305"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "SECOND_LIVE_INVOCATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 90b8ef305* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED EVIDENCE ==="
echo "FIDELITY_FUNCTION_DEFINITION_EXISTS=YES"
echo "FOCUSED_FIDELITY_TESTS_EXIST=YES"
echo "OLLAMA_CHAT_SYMBOL_REFERENCE_COUNT=1"
echo "ONLY_RUNTIME_SOURCE_REFERENCE_IS_FUNCTION_DEFINITION=YES"
echo "RUNTIME_CALL_TO_FIDELITY_ENFORCEMENT=NO"
echo "POST_PARSE_FIDELITY_CALL=NO"
echo "CALL_BEFORE_SELECTED_CONTEXT_REJECTION=NO"
echo "NON_DEFINITION_CALLS_ARE_TEST_OR_SCRIPT_ONLY=YES"

echo
echo "=== DEFECT CLASSIFICATION ==="
echo "OPTION_B_RUNTIME_INTEGRATION_DEFECT=CONFIRMED"
echo "DEFECT=FIDELITY_VALIDATOR_WAS_IMPLEMENTED_AND_TESTED_BUT_NOT_WIRED_INTO_ollamaChat_RUNTIME_PATH"
echo "STATIC_DIRECT_FUNCTION_TESTS_COULD_NOT_ESTABLISH_RUNTIME_INTEGRATION=YES"
echo "PRIOR_LIVE_VALIDATION_INCONCLUSIVE_RESULT_REMAINS_VALID=YES"
echo "PRIOR_LIVE_RUN_DID_NOT_TEST_ACTIVE_FIDELITY_ENFORCEMENT=YES"
echo "OPTION_B_RUNTIME_COMPLETE=NO"
echo "PACKAGE_SEMANTICS_CORRIDOR_CLOSED=NO"

echo
echo "=== FAILURE CONTAINMENT ==="
echo "THIS_IS_IMPLEMENTATION_DEFECT_DISCOVERY_NOT_NEW_GENERATION_FAILURE=YES"
echo "BLIND_LIVE_RETRY=NO"
echo "SECOND_LIVE_INVOCATION=NO"
echo "WEAKEN_SELECTED_CONTEXT_VALIDATION=NO"
echo "WEAKEN_SUPPORT_PROVENANCE_VALIDATION=NO"
echo "HEURISTIC_EXTRACTION=NO"
echo "SECOND_OLLAMA_MODEL_CALL=NO"
echo "AUTHORITY_MODEL_CHANGE=NO"

echo
echo "=== NARROW REPAIR BOUNDARY ==="
echo "REPAIR_TARGET=scripts/utils/ollamaChat.ts_POST_PARSE_PATH"
echo "REQUIRED_CALL=enforceMatildaUserPackageSemanticsFidelity_validatedUserPackageSemantics_result.packageSemantics"
echo "REQUIRED_ORDER=AFTER_parseStructuredResponse_AND_BEFORE_SELECTED_CONTEXT_PROVENANCE_REJECTION"
echo "OBSERVER_ORDER_MUST_BE_REVIEWED_BEFORE_PLACEMENT=YES"
echo "IEL_CHANGE=NO"
echo "WORKFLOW_INPUT_CHANGE=NO"
echo "PROMPT_CHANGE=NO"
echo "LIVING_DRAFT_CHANGE=NO"
echo "APPROVAL_UI_CHANGE=NO"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=DESIGN_EXACT_ONE_CALL_RUNTIME_REPAIR_AND_REQUIRED_INTEGRATION_TEST_BEFORE_IMPLEMENTATION_AUTHORIZATION"
echo "SOURCE_EDIT=NONE"

git diff --check

git add classify-option-b-runtime-integration-defect-confirmed.sh
git commit -m "Confirm Option B runtime integration defect"
git push
