#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY SMALLEST PROVEN PRE-ORCHESTRATOR GAP ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "ORCHESTRATOR_IMPLEMENTATION_AUTHORIZED=NO"
echo "ACTIVE_REPOSITORY_ENABLEMENT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="9ee13fd29"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== ESTABLISHED APPROVAL FACTS ==="
echo "CANONICAL_PACKAGE_APPROVAL_REQUEST_READ_MODEL_EXISTS=YES"
echo "CANONICAL_PACKAGE_APPROVAL_REQUEST_STATUS=pending"
echo "CANONICAL_PACKAGE_APPROVAL_DECISION=approve_canonical_package"
echo "CANONICAL_PACKAGE_APPROVAL_REQUEST_REPOSITORY=READ_ONLY"
echo "EXECUTION_APPROVAL_ARTIFACT_BUILDER_EXISTS=YES"
echo "EXECUTION_APPROVAL_ARTIFACT_DEFAULT_STATUS=approval_required"
echo "EXECUTION_APPROVAL_GATE_REQUIRES_STATUS_approved=YES"

echo
echo "=== CRITICAL AUTHORITY DISTINCTION ==="
echo "CANONICAL_PACKAGE_APPROVAL_AUTHORITY_IS_NOT_EXECUTION_APPROVAL_AUTHORITY=YES"
echo "DO_NOT_REUSE_CANONICAL_PACKAGE_APPROVAL_AS_GIT_EXECUTION_APPROVAL_WITHOUT_EXPLICIT_CONTRACT=YES"
echo "DO_NOT_TREAT_APPROVAL_REQUEST_READ_MODEL_AS_EXECUTION_AUTHORIZATION=YES"

echo
echo "=== UNRESOLVED EXECUTION AUTHORITY GAP ==="
echo "EXECUTION_USER_APPROVAL_WRITE_PATH=NOT_ESTABLISHED"
echo "EXECUTION_APPROVAL_REQUIRED_TO_APPROVED_TRANSITION=NOT_ESTABLISHED"
echo "EXECUTION_APPROVAL_DURABLE_STATE=NOT_ESTABLISHED"
echo "EXECUTION_APPROVAL_USER_ACTOR_BINDING=NOT_ESTABLISHED"
echo "EXECUTION_APPROVAL_ENVELOPE_BINDING_AT_WRITE_TIME=NOT_ESTABLISHED"
echo "MODEL_SELF_APPROVAL_PREVENTION_AT_WRITE_BOUNDARY=NOT_ESTABLISHED"
echo "AUTHORITY_GAP_EXISTS=YES"

echo
echo "=== PROJECT IDENTITY GAP ==="
echo "EXISTING_PROJECT_REGISTRY_MUST_BE_REUSED=YES"
echo "AUTHORITATIVE_repo_path_SOURCE=PARTIALLY_ESTABLISHED"
echo "AUTHORITATIVE_branch_SOURCE=NOT_ESTABLISHED"
echo "AUTHORITATIVE_remote_name_SOURCE=NOT_ESTABLISHED"
echo "AUTHORITATIVE_remote_url_SOURCE=NOT_ESTABLISHED"
echo "EXECUTION_PROJECT_TARGET_REGISTRY_DERIVATION=NOT_ESTABLISHED"
echo "PROJECT_IDENTITY_GAP_EXISTS=YES"

echo
echo "=== SMALLEST PROVEN PRE-ORCHESTRATOR UNITS ==="
echo "UNIT_A=EXECUTION_APPROVAL_AUTHORITY_TRANSITION"
echo "UNIT_A_PURPOSE=EXPLICIT_USER_OWNED_APPROVAL_REQUIRED_TO_APPROVED_TRANSITION"
echo "UNIT_A_MUST_BIND=approval_id,envelope_id,user_actor,scope,version_control_authorization"
echo "UNIT_A_MODEL_SELF_APPROVAL=PROHIBITED"
echo "UNIT_A_FAIL_CLOSED=YES"

echo "UNIT_B=PROJECT_REGISTRY_GIT_TARGET_IDENTITY"
echo "UNIT_B_PURPOSE=REGISTERED_PROJECT_BECOMES_AUTHORITATIVE_GIT_TARGET_SOURCE"
echo "UNIT_B_REQUIRED_IDENTITY=repo_path,branch,remote_name,remote_url"
echo "UNIT_B_MODEL_INFERENCE=PROHIBITED"
echo "UNIT_B_PARALLEL_REGISTRY=PROHIBITED"

echo
echo "=== ORDERING DETERMINATION ==="
echo "ORCHESTRATOR_BEFORE_UNIT_A=PROHIBITED"
echo "ORCHESTRATOR_BEFORE_UNIT_B=PROHIBITED"
echo "ACTIVE_REPOSITORY_WRITE_BEFORE_BOTH_CLOSE=PROHIBITED"
echo "RECOMMENDED_NEXT_UNIT=EXECUTION_APPROVAL_AUTHORITY_TRANSITION"
echo "RATIONALE=USER_EXECUTION_AUTHORITY_MUST_EXIST_BEFORE_PRODUCTION_GIT_EFFECTS_CAN_BE_GOVERNED"

echo
echo "=== INSPECT APPROVAL WRITE-PATH REUSE CANDIDATES ==="
git grep -n -I -E \
  'approve_canonical_package|canonical_approved|createCanonicalPackage|approveCanonical|router\.post|app\.post' \
  -- \
  client/src/approvals \
  routes \
  db \
  server \
  ':!server/execution/smoke-test-*' \
  | sed -n '1,900p' || true

echo
echo "=== INSPECT PROJECT REGISTRY IDENTITY SURFACE ==="
sed -n '80,190p' server/project-registry.mjs
sed -n '410,535p' server/project-registry.mjs

echo
echo "=== BOUNDARIES ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_PROJECT_REGISTRY_WRITE=YES"
echo "NO_GIT_EFFECT=YES"
echo "NO_REMOTE_WRITE=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_EXACT_EXECUTION_APPROVAL_AUTHORITY_TRANSITION_CONTRACT_AND_REUSE_BOUNDARY"
echo "IMPLEMENTATION_AUTHORIZED=NO"
