#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY LIVE MIGRATION BOUNDARY ==="
echo "IMPLEMENTATION_COMMIT=5b9082f2"
echo "CLASSIFICATION_COMMIT=6a3251cc"
echo "CODE_COMPLETE_VALIDATED=YES"
echo "LIVE_DATABASE_MIGRATION_APPLIED=NO"
echo "KNOWN_DOWNSTREAM_LEGACY_ROOT_DEFECT=STILL_SEPARATE"
echo "CORRIDOR_CLOSED=NO"
echo "LIVE_MIGRATION_AUTHORIZED=NO"
echo "NEXT_ACTION=COLLABORATE_ON_LIVE_MIGRATION_DECISION"
