#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY ORDERED CLOUDFLARE ACCESS AND SERVER IDENTITY UNITS ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="753977007"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED CURRENT CONTRACT ==="
echo "REMOTE_OPERATOR_ENTRYPOINT=/ui"
echo "REMOTE_HOST_CANDIDATE=ui.marketingmother.org"
echo "REMOTE_TUNNEL_CANDIDATE=ui-server"
echo "EXECUTION_AUTHORIZATION_ROUTE_ACTIVE_MOUNT=NO"
echo "INITIAL_EXECUTION_AUTHORIZATION_TRUST_MODE=VERIFIED_REMOTE_IDENTITY_ONLY"
echo "REMOTE_ASSERTION_HEADER=Cf-Access-Jwt-Assertion"
echo "REMOTE_ASSERTION_MUST_BE_CRYPTOGRAPHICALLY_VALIDATED=YES"
echo "CLIENT_SUPPLIED_authorization_actor_IS_AUTHORITY=NO"

echo
echo "=== ORDERED UNIT A — CLOUDFLARE ACCESS INFRASTRUCTURE ==="
echo "UNIT_A_NAME=CLOUDFLARE_ACCESS_APPLICATION_AND_POLICY"
echo "UNIT_A_OWNER=INFRASTRUCTURE"
echo "UNIT_A_PURPOSE=AUTHENTICATE_OPERATOR_BEFORE_REQUEST_REACHES_PROTECTED_SERVER_BOUNDARY"
echo "UNIT_A_REQUIRED_OUTPUT_1=KNOWN_TEAM_DOMAIN"
echo "UNIT_A_REQUIRED_OUTPUT_2=KNOWN_APPLICATION_AUDIENCE_TAG"
echo "UNIT_A_REQUIRED_OUTPUT_3=ACCESS_POLICY_BOUND_TO_CANONICAL_REMOTE_ENTRYPOINT"
echo "UNIT_A_REQUIRED_OUTPUT_4=VERIFIED_PROXY_ASSERTION_AVAILABLE_TO_ORIGIN"
echo "UNIT_A_REQUIRED_OUTPUT_5=DIRECT_REMOTE_BYPASS_POLICY"
echo "UNIT_A_DOES_NOT_GRANT_EXECUTION_APPROVAL=YES"
echo "UNIT_A_DOES_NOT_GRANT_GIT_COMMIT_OR_PUSH_AUTHORITY=YES"

echo
echo "=== ORDERED UNIT B — SERVER IDENTITY VALIDATOR ==="
echo "UNIT_B_NAME=SERVER_VERIFIED_OPERATOR_IDENTITY_VALIDATOR"
echo "UNIT_B_OWNER=SERVER_REQUEST_BOUNDARY"
echo "UNIT_B_REQUIRES_UNIT_A=YES"
echo "UNIT_B_VALIDATES_SIGNATURE=YES"
echo "UNIT_B_VALIDATES_ISSUER=YES"
echo "UNIT_B_VALIDATES_AUDIENCE=YES"
echo "UNIT_B_VALIDATES_EXPIRATION=YES"
echo "UNIT_B_VALIDATES_NOT_BEFORE=YES"
echo "UNIT_B_NORMALIZES_IDENTITY=provider,subject,email,issuer,audience,verified"
echo "UNIT_B_FAILS_CLOSED_ON_MISSING_OR_INVALID_ASSERTION=YES"
echo "UNIT_B_MUST_NOT_TRUST_RAW_EMAIL_HEADER=YES"
echo "UNIT_B_MUST_NOT_ACCEPT_CLIENT_SELECTED_ACTOR=YES"
echo "UNIT_B_DOES_NOT_GRANT_EXECUTION_APPROVAL=YES"

echo
echo "=== ORDERING CONTRACT ==="
echo "UNIT_A_BEFORE_UNIT_B=REQUIRED"
echo "UNIT_B_BEFORE_EXECUTION_AUTHORIZATION_ROUTE_MOUNT=REQUIRED"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_BEFORE_DURABLE_APPROVAL_COMPILATION=NOT_AUTOMATIC"
echo "DURABLE_USER_APPROVAL_REMAINS_SEPARATE_SUCCESSOR_UNIT=YES"
echo "ACTIVE_REPOSITORY_ENABLEMENT_REMAINS_LATER_SUCCESSOR=YES"

echo
echo "=== VALIDATION REQUIREMENTS BEFORE ANY IMPLEMENTATION AUTHORIZATION ==="
echo "VERIFY_CANONICAL_REMOTE_HOST=YES"
echo "VERIFY_TEAM_DOMAIN=YES"
echo "VERIFY_APPLICATION_AUDIENCE_TAG=YES"
echo "VERIFY_ACCESS_POLICY_SCOPE=YES"
echo "VERIFY_ORIGIN_CANNOT_BE_REMOTELY_BYPASSED=YES"
echo "VERIFY_TEMP_OR_NON_PRODUCTION_VALIDATION_PATH=YES"
echo "VERIFY_LOCAL_/ui_REMAINS_NON_EXECUTION_CAPABLE=YES"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "USER_INTENT_AUTHORITY_UNCHANGED=YES"
echo "MATILDA_INTERPRETATION_AUTHORITY_UNCHANGED=YES"
echo "AUTHENTICATION_IS_NOT_APPROVAL=YES"
echo "MATILDA_SELF_APPROVAL=PROHIBITED"
echo "CADE_SELF_APPROVAL=PROHIBITED"
echo "EXECUTION_APPROVAL_GATE_UNCHANGED=YES"
echo "CADE_LOCAL_COMMIT_EFFECT_UNCHANGED=YES"
echo "CADE_REMOTE_PUSH_EFFECT_UNCHANGED=YES"
echo "GENERIC_MUTATION_AUTHORITY_DISABLED=YES"
echo "GENERIC_SHELL_AUTHORITY_DISABLED=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_DISABLED=YES"

echo
echo "=== CURRENT DETERMINATION ==="
echo "UNIT_A_CLASSIFIED=YES"
echo "UNIT_B_CLASSIFIED=YES"
echo "ORDERING_CLASSIFIED=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "NEXT_ACTION=INSPECT_EXACT_UNIT_A_CONFIGURATION_INPUTS_BEFORE_AUTHORIZING_ANY_CLOUDFLARE_ACCESS_CHANGE"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
