#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY EMPTY MISSION CONTROL RENDERING GAP ==="
echo "CLOSED_MILESTONE=MISSION_CONTROL_PROJECT_CONTEXT_ALIGNMENT"
echo "CURRENT_BASELINE_COMMIT=72a80e8b"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== OBSERVED UI CONTRACT ==="
echo "NOT_FOUND_STATE=CURRENTLY_REPLACES_ENTIRE_DASHBOARD"
echo "EXPECTED_EMPTY_PIPELINE_BEHAVIOR=KEEP_TELEMETRY_CARDS_VISIBLE_WITH_EMPTY_OR_IDLE_CONTENT"
echo "MISSION_CONTROL_SHELL_SHOULD_EXIST_WITHOUT_ACTIVE_MISSION=YES"

echo
echo "=== REPOSITORY EVIDENCE ==="
rg -n -C 10 \
  'status === "not_found"|No mission is currently in progress|mission-dashboard__composition|ExecutiveBriefCard|MissionStatusCard|MissionProgressCard' \
  client/src/shell/MissionDashboardWorkspace.tsx \
  2>/dev/null || true

echo
echo "=== CLASSIFICATION ==="
echo "GAP_CLASS=MISSION_CONTROL_EMPTY_STATE_PRESENTATION"
echo "AUTHORITY_GAP=NO"
echo "PACKAGE_SELECTION_GAP=NO"
echo "MISSION_READ_GAP=NO"
echo "TELEMETRY_RENDERING_GAP=YES"
echo "CLOSED_MILESTONE_ARCHITECTURAL_CONTRACT_INVALIDATED=NO"
echo "FOLLOW_UP_UI_RUNTIME_FIX_REQUIRED=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=DESIGN_MINIMUM_EMPTY_MISSION_PRESENTATION_FIX_WITHOUT_CHANGING_AUTHORITY_OR_HANDOFF_CONTRACTS"
