#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY TRUSTED USER APPROVAL AND AUTHORIZATION COMPILATION BOUNDARY ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="2d2a7b3f7"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== INSPECT AUTHENTICATION AND TRUSTED ACTOR SURFACES ==="
git grep -n -I -E \
  'req\.user|request\.user|res\.locals|session|authenticated|authentication|authorization_actor|actor_id|user_id|currentUser|current_user' \
  -- server routes db client/src \
  | sed -n '1,1400p' || true

echo
echo "=== INSPECT EXECUTION AUTHORIZATION CALLERS ==="
git grep -n -I -E \
  'execution-authorization|createExecutionAuthorization|execution_authorized|authorization_id' \
  -- server routes db client/src \
  | sed -n '1,1200p' || true

echo
echo "=== INSPECT EXECUTION PREVIEW / CONFIRMATION / PLAN LINEAGE ==="
git grep -n -I -E \
  'confirmation_id|preview_id|execution_plan_id|execution preview|execution confirmation|execution plan' \
  -- server routes db client/src \
  | sed -n '1,1400p' || true

echo
echo "=== INSPECT APPROVAL ARTIFACT CONSUMERS ==="
git grep -n -I -E \
  'approval_artifact|approval_id|approval_status|commit_authorized|push_authorized|governed_version_control_commit|governed_version_control_push' \
  -- server/execution server/cade routes \
  | sed -n '1,1600p' || true

echo
echo "=== INSPECT CANONICAL GOVERNANCE ENVELOPE READ SURFACES ==="
git grep -n -I -E \
  'governance_envelopes|envelope_id|package_version|delegation_id' \
  -- db server \
  | sed -n '1,1600p' || true

echo
echo "=== CLASSIFICATION QUESTIONS ==="
echo "QUESTION_1=WHAT_SERVER_VERIFIED_IDENTITY_CAN_AUTHOR_EXECUTION_APPROVAL"
echo "QUESTION_2=WHETHER_CURRENT_EXECUTION_AUTHORIZATION_ROUTE_HAS_ANY_TRUSTED_ACTOR_SOURCE"
echo "QUESTION_3=WHETHER_CONFIRMATION_PREVIEW_AND_PLAN_IDS_ARE_DURABLE_AUTHORITATIVE_INPUTS"
echo "QUESTION_4=HOW_DURABLE_AUTHORIZATION_COMPILES_TO_EXISTING_EXECUTION_APPROVAL_ARTIFACT"
echo "QUESTION_5=WHETHER_COMPILATION_CAN_REUSE_EXISTING_APPROVAL_GATE_WITHOUT_SEMANTIC_CHANGE"

echo
echo "=== REQUIRED TRUST BOUNDARY ==="
echo "REQUEST_BODY_AUTHORIZATION_ACTOR_IS_NOT_AUTHORITY=YES"
echo "USER_APPROVAL_MUST_ORIGINATE_FROM_SERVER_VERIFIED_IDENTITY_OR_EXISTING_TRUSTED_SESSION=YES"
echo "IF_NO_VERIFIED_IDENTITY_SURFACE_EXISTS_IMPLEMENTATION_MUST_STOP=YES"
echo "NO_SYNTHETIC_USER_IDENTITY=YES"
echo "NO_HARDCODED_MARCELA_IDENTITY=YES"
echo "NO_CLIENT_ASSERTED_ACTOR_AS_AUTHORITY=YES"

echo
echo "=== REQUIRED COMPILATION BOUNDARY ==="
echo "DURABLE_EXECUTION_AUTHORIZATION_IS_SOURCE_OF_TRUTH=YES"
echo "EXECUTION_APPROVAL_ARTIFACT_IS_DERIVED=YES"
echo "DERIVED_ARTIFACT_MUST_REFERENCE_DURABLE_AUTHORIZATION_ID=YES"
echo "DERIVED_ARTIFACT_MUST_REFERENCE_EXACT_ENVELOPE_ID=YES"
echo "DERIVED_ARTIFACT_MUST_NOT_EXPAND_COMMIT_SCOPE=YES"
echo "DERIVED_ARTIFACT_MUST_NOT_EXPAND_PUSH_SCOPE=YES"
echo "DERIVED_ARTIFACT_MUST_NOT_EXPAND_REPOSITORY_SCOPE=YES"
echo "DERIVED_ARTIFACT_MUST_NOT_EXPAND_PATH_SCOPE=YES"
echo "APPROVAL_GATE_REMAINS_FINAL_FAIL_CLOSED_AUTHORITY_CHECK=YES"

echo
echo "=== PRESERVED ARCHITECTURAL BOUNDARIES ==="
echo "CANONICAL_PACKAGE_APPROVAL_REMAINS_SEPARATE=YES"
echo "GOVERNANCE_ENVELOPE_SEMANTICS_UNCHANGED=YES"
echo "CADE_EFFECT_IMPLEMENTATIONS_UNCHANGED=YES"
echo "GENERIC_CADE_ROUTE_UNCHANGED=YES"
echo "GENERIC_MUTATION_AUTHORITY_DISABLED=YES"
echo "GENERIC_SHELL_AUTHORITY_DISABLED=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_DISABLED=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=USE_REPOSITORY_EVIDENCE_TO_DETERMINE_IF_TRUSTED_USER_IDENTITY_AND_EXISTING_LINEAGE_ARE_SUFFICIENT_FOR_A_SINGLE_DURABLE_AUTHORIZATION_IMPLEMENTATION_UNIT"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_GIT_EFFECT=YES"
echo "NO_REMOTE_WRITE=YES"
