#!/usr/bin/env bash
set -euo pipefail

cd "/Users/marcela-dev/Projects/motherboard-systems-hq-clean"

BRANCH="feature/support-source-references-runtime"
BASELINE="02acd8674"

git fetch origin "$BRANCH"

test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$BASELINE"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$BASELINE"
test -z "$(git diff --cached --name-only)"

echo "===== MINIMUM ATLAS PRE-EXECUTION REASONING CONTRACT ====="
echo "MODE=READ_ONLY_CLASSIFICATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CHECKPOINT=$(git rev-parse HEAD)"

echo
echo "===== VERIFIED INPUT CONTRACT ====="
grep -nE \
  'export type|sourceKind|authorityStatus|projectId|conversationId|lineageId|observedAt|aggregateAtlasPreExecutionObservationRecords' \
  server/atlas/atlas-preexecution-observation-aggregator.ts || true

echo
echo "===== EXISTING EXECUTION REASONING BOUNDARY ====="
grep -nE \
  'ExecutionEvent|reconstructWhy|buildCausalGraph|pruneCausalGraph|causalChain|reasonOverSessions|clusterSessions' \
  server/atlas/atlas-reconstruction-model.ts \
  server/atlas/session-aware-reasoner.ts \
  server/atlas/session-cluster.ts \
  server/atlas/causal-graph.ts \
  2>/dev/null || true

echo
echo "===== CLASSIFICATION ====="
echo "PREEXECUTION_REASONING_INPUT=TYPED_PREEXECUTION_OBSERVATIONS"
echo "EXECUTION_EVENT_INPUT=NO"
echo "EXECUTION_REASONER_REUSE=NO"
echo "MODEL_CALL_REQUIRED=NO"
echo "DETERMINISTIC_REASONING=YES"
echo "NEW_PERSISTENCE_REQUIRED=NO"
echo "ROUTE_CHANGE_REQUIRED=NO"
echo "AUTHORITY_MUTATION=NO"

echo
echo "===== SAFE DERIVATIONS ====="
echo "SAFE_1=SOURCE_PRESENCE"
echo "SAFE_2=DETERMINISTIC_CHRONOLOGY"
echo "SAFE_3=SHARED_EXPLICIT_LINEAGE"
echo "SAFE_4=SHARED_EXPLICIT_CONVERSATION"
echo "SAFE_5=OBSERVED_AUTHORITY_STATUS"
echo "SAFE_6=OBSERVED_SOURCE_STATUS"
echo "SAFE_7=AUTHORITY_SEQUENCE_WITHIN_EXPLICIT_LINEAGE"
echo "SAFE_8=SOURCE_SEQUENCE_WITHIN_EXPLICIT_LINEAGE"

echo
echo "===== FORBIDDEN DERIVATIONS ====="
echo "FORBIDDEN_1=CHRONOLOGY_AS_CAUSATION"
echo "FORBIDDEN_2=PENDING_STATE_AS_APPROVAL"
echo "FORBIDDEN_3=LIVING_DRAFT_AS_AUTHORITY"
echo "FORBIDDEN_4=NONCANONICAL_SOURCE_AS_CANONICAL"
echo "FORBIDDEN_5=MATILDA_INTERPRETATION_AS_DURABLE_FACT"
echo "FORBIDDEN_6=PREEXECUTION_STATE_AS_EXECUTION"
echo "FORBIDDEN_7=TEMPORAL_PROXIMITY_AS_INTENT"
echo "FORBIDDEN_8=MISSING_LINEAGE_AS_LINEAGE_RELATIONSHIP"
echo "FORBIDDEN_9=MISSING_CONVERSATION_AS_CONVERSATION_RELATIONSHIP"
echo "FORBIDDEN_10=AUTHORITY_SEQUENCE_AS_CAUSAL_TRANSITION"

echo
echo "===== MINIMUM SAFE OUTPUT ====="
echo "OUTPUT=LINEAGE_GROUPED_STRUCTURAL_SEQUENCE"
echo "OUTPUT_IS_CAUSAL_EXPLANATION=NO"
echo "OUTPUT_IS_EXECUTION_HISTORY=NO"
echo "OUTPUT_IS_APPROVAL_DECISION=NO"
echo "OUTPUT_IS_AUTHORITY_DECISION=NO"
echo "OUTPUT_IS_MATILDA_INTERPRETATION=NO"
echo "OUTPUT_IS_DETERMINISTIC_STRUCTURAL_DERIVATION=YES"

echo
echo "===== Q1-Q8 DETERMINATION ====="
echo "Q1=SOURCE_LINEAGE_CONVERSATION_CHRONOLOGY_AND_AUTHORITY_SEQUENCE_ONLY"
echo "Q2=YES_SEPARATE_FROM_RUN_ATLAS_INTELLIGENCE"
echo "Q3=YES_DETERMINISTIC_WITHOUT_MODEL_CALL"
echo "Q4=EXPLICIT_SHARED_IDENTITIES_AND_ORDER_WITHOUT_CAUSATION"
echo "Q5=REPORT_OBSERVED_AUTHORITY_SEQUENCE_WITHOUT_GRANTING_OR_INFERRING_AUTHORITY"
echo "Q6=PRESERVE_IEL_AS_MATILDA_AUTHORED_INTERPRETIVE_EVIDENCE_DISTINCT_FROM_DURABLE_FACT"
echo "Q7=PURE_LINEAGE_GROUPED_STRUCTURAL_SEQUENCE"
echo "Q8=YES_EXISTING_EXECUTION_ANALYSIS_CAN_REMAIN_UNTOUCHED"

echo
echo "===== FIRST IMPLEMENTATION UNIT ====="
echo "UNIT=PURE_PREEXECUTION_STRUCTURAL_REASONER"
echo "INPUT=ATLAS_TYPED_PREEXECUTION_OBSERVATIONS"
echo "SIDE_EFFECTS=NONE"
echo "MODEL_CALLS=NONE"
echo "PERSISTENCE=NONE"
echo "EXECUTION_EVENT_COERCION=NONE"
echo "EXECUTION_REASONER_CHANGE=NONE"
echo "ROUTE_WIRING=NONE"
echo "MATILDA_CHANGE=NONE"
echo "AUTHORITY_CHANGE=NONE"

echo
echo "===== STOP BOUNDARY ====="
echo "SOURCE_CHANGE=NONE"
echo "DATABASE_CHANGE=NONE"
echo "ROUTE_CHANGE=NONE"
echo "REASONER_CHANGE=NONE"
echo "MATILDA_CHANGE=NONE"
echo "EXECUTION_EVENT_CHANGE=NONE"
echo "IMPLEMENTATION=NONE"
echo "MINIMUM_REASONING_CONTRACT=CLASSIFIED"
echo "NEXT_ACTION=REQUEST_EXPLICIT_AUTHORIZATION_FOR_PURE_PREEXECUTION_STRUCTURAL_REASONER"
echo "DOGFOOD_CLEANUP=FROZEN"

echo
echo "===== WORKTREE ====="
git status --short
