#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY OPERATIONAL PACKAGE AUTHORITY MINIMUM SEMANTIC CONTRACT ==="

echo
echo "=== BASELINE ==="
printf "HEAD=" && git rev-parse --short=8 HEAD
printf "BRANCH=" && git branch --show-current
git status --short

echo
echo "=== ESTABLISHED INPUT ==="
echo "DISTINCT_ARCHITECTURAL_CAPABILITY=OPERATIONAL_PACKAGE_AUTHORITY"
echo "AUTHORITY_GAP=VERIFIED"
echo "PERSISTED_OPERATIONAL_PACKAGE_SELECTION_AUTHORITY=ABSENT"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== RELEVANT IDENTITY CONTRACT ==="
sed -n '1,180p' docs/governance/CANONICAL_PACKAGE_VERSION_IDENTITY_CONTRACT_2026-08-21.md

echo
echo "=== ACTIVE PROJECT AUTHORITY PRECEDENT ==="
sed -n '86,130p' server/project-registry.mjs
sed -n '892,970p' server/project-registry.mjs

echo
echo "=== DELEGATION EXACT-VERSION BOUNDARY ==="
rg -n -C 14 \
  'Delegation authorizes one exact|package_id, package_version|never transfers automatically|successor Canonical Package version' \
  docs/governance/CANONICAL_PACKAGE_VERSION_IDENTITY_CONTRACT_2026-08-21.md \
  docs/governance/CANONICAL_DELEGATION_SPECIFICATION.md \
  2>/dev/null | head -n 1400 || true

echo
echo "=== SEARCH FOR AUTHORITY/SELECTION SEMANTICS ==="
rg -n -C 12 \
  --hidden \
  --glob '!node_modules/**' \
  --glob '!.git/**' \
  --glob '!snapshots/**' \
  --glob '!scripts_backup*/**' \
  --glob '!*.bak' \
  'active_context|setActiveProject|current_project_id|operational.*package|active.*package|current.*package|select.*package|nominate.*package|authoritative.*package' \
  server db client/src docs/governance \
  2>/dev/null | head -n 3200 || true

echo
echo "=== MINIMUM SEMANTIC CONTRACT CLASSIFICATION ==="
echo "AUTHORITY_NAME=OPERATIONAL_PACKAGE_AUTHORITY"
echo "AUTHORITY_SCOPE=PROJECT_SCOPED"
echo "AUTHORITATIVE_BINDING=(project_id,package_id,package_version)"
echo "PACKAGE_IDENTITY_REQUIREMENT=EXACT_CANONICAL_PACKAGE_VERSION"
echo "PACKAGE_MUST_BE_CANONICAL_APPROVED=YES"
echo "PACKAGE_PROJECT_MUST_MATCH_AUTHORITY_PROJECT=YES"
echo "SUCCESSOR_VERSION_AUTO_ACTIVATION=NO"
echo "DELEGATION_REQUIRED_FOR_SELECTION=NO"
echo "DELEGATION_CREATED_BY_SELECTION=NO"
echo "GOVERNANCE_VALIDATION_CREATED_BY_SELECTION=NO"
echo "ENVELOPE_CREATED_BY_SELECTION=NO"
echo "ROUTING_CREATED_BY_SELECTION=NO"
echo "ASSIGNMENT_CREATED_BY_SELECTION=NO"
echo "EXECUTION_CREATED_BY_SELECTION=NO"

echo
echo "=== AUTHORITY BEHAVIOR ==="
echo "ONE_ACTIVE_OPERATIONAL_PACKAGE_PER_PROJECT=YES"
echo "SELECTION_MUST_BE_EXPLICIT=YES"
echo "SELECTION_MUST_BE_PERSISTED=YES"
echo "SELECTION_MUST_BE_AUDITABLE=YES"
echo "RESELECTION_ALLOWED=YES"
echo "RESELECTION_REPLACES_ACTIVE_BINDING_NOT_PACKAGE_HISTORY=YES"
echo "PACKAGE_VERSION_IMMUTABILITY_PRESERVED=YES"
echo "CANONICAL_LINEAGE_IMMUTABILITY_PRESERVED=YES"
echo "NO_VALID_SELECTION_BEHAVIOR=NO_OPERATIONAL_MISSION_SELECTED"

echo
echo "=== PRECEDENT DETERMINATION ==="
echo "PROJECT_ACTIVE_CONTEXT_PATTERN=STRUCTURALLY_RELEVANT_PRECEDENT"
echo "PROJECT_ACTIVE_CONTEXT_AUTHORITY_REUSE=NOT_AUTOMATICALLY_AUTHORIZED"
echo "RATIONALE=OPERATIONAL_PACKAGE_AUTHORITY_REQUIRES_DISTINCT_PACKAGE_VERSION_IDENTITY_AND_SEMANTICS"

echo
echo "=== BOUNDARY DETERMINATION ==="
echo "CANONICAL_APPROVAL=ESTABLISHES_AUTHORITATIVE_PACKAGE_VERSION"
echo "OPERATIONAL_PACKAGE_AUTHORITY=SELECTS_WHICH_AUTHORITATIVE_PACKAGE_VERSION_IS_OPERATIONALLY_CURRENT_FOR_A_PROJECT"
echo "DELEGATION=SEPARATE_DOWNSTREAM_AUTHORIZATION"
echo "MISSION_READ_MODEL=CONSUMER_OF_OPERATIONAL_SELECTION_NOT_SELECTION_AUTHORITY"

echo
echo "=== SCOPE DETERMINATION ==="
echo "MINIMUM_SEMANTIC_CONTRACT=CLASSIFIED"
echo "NEW_GOVERNANCE_AUTHORITY_REQUIRED=YES"
echo "IMPLEMENTATION_SHAPE=NOT_YET_DETERMINED"
echo "SCHEMA_CHANGE=NOT_AUTHORIZED"
echo "API_CHANGE=NOT_AUTHORIZED"
echo "MISSION_CONTROL_CHANGE=NOT_AUTHORIZED"
echo "PROPOSED_IMPLEMENTATION=NONE"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "NEXT_DECISION=INVESTIGATE_MINIMUM_PERSISTENCE_AND_OWNERSHIP_BOUNDARY_FOR_OPERATIONAL_PACKAGE_AUTHORITY"
