#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY ACTIVE PROJECT FAILURE LAYER ==="
echo "BASELINE_COMMIT=3d543ee0"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED PERSISTENCE STATE ==="
echo "ACTIVE_CONTEXT_PRESENT=YES"
echo "ACTIVE_PROJECT_ID=executive-agent-suite"
echo "ACTIVE_PROJECT_REGISTERED=YES"
echo "ACTIVE_PROJECT_AVAILABLE=YES"
echo "ACTIVE_PROJECT_ELIGIBLE=YES"
echo "DIRECT_SERVER_REGISTRY_STATE_HAS_ACTIVE_PROJECT=YES"

echo
echo "=== VERIFIED RUNTIME FAILURE ==="
echo "HTTP_PROJECT_REGISTRY_ENDPOINT_STATUS=000"
echo "HTTP_PROJECT_REGISTRY_ENDPOINT_REACHABLE=NO"
echo "SERVER_LISTENING_ON_127_0_0_1_3000=NO"
echo "CLIENT_PROJECT_CONTEXT_PROVIDER_CAN_COMPLETE_INITIAL_FETCH=NO"

echo
echo "=== CAUSAL CLASSIFICATION ==="
echo "ROOT_CAUSE_LAYER=RUNNING_SERVER_OR_ROUTE_AVAILABILITY"
echo "ACTIVE_PROJECT_PERSISTENCE_GAP=NO"
echo "PROJECT_CONTEXT_DATA_MODEL_GAP=NO"
echo "MISSION_CONTROL_LOCAL_GAP=NO"
echo "APPROVALS_LOCAL_GAP=NO"
echo "MISSION_CONTROL_PREPARING_STATE_CAUSE=PROJECT_CONTEXT_FETCH_CANNOT_COMPLETE"
echo "APPROVALS_NO_ACTIVE_PROJECT_CAUSE=REGISTRY_REMAINS_NULL_WHILE_PROJECT_REGISTRY_ENDPOINT_IS_UNREACHABLE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=RECONCILE_WHY_THE_EXPECTED_APPLICATION_SERVER_OR_API_ORIGIN_IS_NOT_REACHABLE_FROM_THE_RUNNING_UI_BEFORE_ANY_CLIENT_IMPLEMENTATION_CHANGE"
