#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY IDEMPOTENT POST-APPROVAL PROJECTION TRIGGER ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PACKAGE_HANDOFF_CONTRACT"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== TARGET SCHEMA COMPATIBILITY ==="
echo "governance_packages_REQUIRED_FIELDS=package_id+package_version+created_at"
echo "MISSION_READ_REQUIRED_IDENTITY=package_id+package_version+project_id+conversation_id"
echo "MISSION_READ_REQUIRED_SEMANTIC_FIELD=requested_outcome"
echo "CANONICAL_SOURCE_HAS_package_id=YES"
echo "CANONICAL_SOURCE_HAS_package_version=YES"
echo "CANONICAL_SOURCE_HAS_project_id=YES"
echo "CANONICAL_SOURCE_HAS_conversation_id=YES"
echo "CANONICAL_SOURCE_HAS_approved_expected_outcome=YES"
echo "UNUSED_LEGACY_FIELDS_NULLABLE=YES"
echo "INVENTED_LEGACY_FIELD_VALUES_REQUIRED=NO"
echo "TARGET_SCHEMA_RECONCILIATION_REQUIRED_FOR_MINIMUM_PROJECTION=NO"
echo "MINIMUM_DERIVED_MISSION_READ_PROJECTION_SCHEMA_COMPATIBLE=YES"

echo
echo "=== PRIMARY KEY / IDEMPOTENCY CONTRACT ==="
sqlite3 -header -column db/main.db '
SELECT
  name,
  type,
  "notnull",
  pk
FROM pragma_table_info("governance_packages")
ORDER BY cid;
'

echo
echo "=== CANONICAL APPROVAL IDENTITY CONTRACT ==="
sqlite3 -header -column db/main.db '
SELECT
  package_id,
  package_version,
  project_id,
  conversation_id,
  status,
  approved_expected_outcome,
  created_at
FROM matilda_canonical_packages
ORDER BY created_at DESC
LIMIT 10;
'

echo
echo "=== EXISTING DUPLICATE / UPSERT SEMANTICS ==="
rg -n -C 16 \
  'INSERT INTO governance_packages|ON CONFLICT|INSERT OR|createGovernancePackage' \
  db/governance-runtime.ts \
  server/package \
  2>/dev/null || true

echo
echo "=== APPROVAL TRANSACTION BOUNDARY ==="
sed -n '195,375p' db/matilda-canonical-package-runtime.ts

echo
echo "=== APPROVAL ROUTE BOUNDARY ==="
sed -n '1,100p' server/routes/matilda-canonical-package-route.ts

echo
echo "=== CALLER / TRIGGER SEARCH ==="
rg -n -C 10 \
  'canonical-package|createCanonicalPackageFromApprovedSummary|canonical_approved' \
  server client db \
  2>/dev/null || true

echo
echo "=== IDEMPOTENCY CLASSIFICATION ==="
echo "TARGET_PRIMARY_KEY=package_id+package_version"
echo "CANONICAL_SOURCE_IDENTITY_INCLUDES=project_id+package_id+package_version"
echo "PROJECTION_TARGET_DUPLICATE_IDENTITY_CAN_BE_DETECTED=YES"
echo "PROJECTION_MUST_NOT_SELECT_NEWEST_CANONICAL_PACKAGE=YES"
echo "PROJECTION_MUST_USE_EXACT_APPROVED_IDENTITY=YES"
echo "PROJECTION_MUST_VERIFY_EXISTING_TARGET_MATCHES_CANONICAL_IDENTITY=YES"
echo "PROJECTION_MUST_FAIL_CLOSED_IF_EXISTING_TARGET_CONFLICTS_WITH_CANONICAL_IDENTITY=YES"
echo "PROJECTION_MAY_TREAT_EXACT_EXISTING_DERIVED_RECORD_AS_IDEMPOTENT_SUCCESS=YES"
echo "PROJECTION_MUST_NOT_OVERWRITE_INDEPENDENT_LEGACY_RECORD_WITH_DIFFERENT_PROVENANCE=YES"

echo
echo "=== TRIGGER SEMANTICS ==="
echo "APPROVAL_IS_THE_EVENT_THAT_ESTABLISHES_AUTHORITATIVE_CANONICAL_PACKAGE=YES"
echo "PROJECTION_BEFORE_APPROVAL_ALLOWED=NO"
echo "PROJECTION_FROM_CALLER_SUPPLIED_SEMANTICS_ALLOWED=NO"
echo "PROJECTION_INPUT_AFTER_APPROVAL=EXACT_RETURNED_project_id+package_id+package_version"
echo "SEPARATE_OPERATOR_SELECTION_OF_PACKAGE_REQUIRED=NO"
echo "UI_PACKAGE_PREFERENCE_AS_TRIGGER_AUTHORITY=NO"
echo "DELEGATION_AS_PROJECTION_TRIGGER=NO"
echo "MISSION_CONTROL_AS_PROJECTION_TRIGGER=NO"
echo "POST_APPROVAL_PROJECTION_IS_NEAREST_SEMANTIC_TRIGGER=YES"
echo "POST_APPROVAL_PROJECTION_MUST_REMAIN_NON_AUTHORITY_CONFERRING=YES"
echo "POST_APPROVAL_PROJECTION_MUST_NOT_IMPLY_DELEGATION=YES"
echo "POST_APPROVAL_PROJECTION_MUST_NOT_IMPLY_EXECUTION=YES"

echo
echo "=== TRANSACTION / FAILURE BOUNDARY ==="
echo "AUTOMATIC_POST_APPROVAL_TRIGGER_IMPLEMENTATION_AUTHORIZED=NO"
echo "ATOMIC_APPROVAL_PLUS_PROJECTION_REQUIRED=NOT_YET_ESTABLISHED"
echo "PROJECTION_FAILURE_MUST_NOT_SILENTLY_CREATE_PARTIAL_AUTHORITATIVE_HANDOFF=YES"
echo "RETRY_SEMANTICS_MUST_BE_IDEMPOTENT=YES"
echo "EXACT_FAILURE_OWNERSHIP_REQUIRES_IMPLEMENTATION_UNIT_DESIGN=YES"

echo
echo "=== PACKAGE HANDOFF CONTRACT DETERMINATION ==="
echo "PACKAGE_HANDOFF_SOURCE=EXACT_canonical_approved_PACKAGE"
echo "PACKAGE_HANDOFF_TARGET=governance_packages_DERIVED_MISSION_READ_PROJECTION"
echo "PACKAGE_HANDOFF_MINIMUM_FIELDS=package_id+package_version+project_id+conversation_id+requested_outcome+created_at"
echo "PACKAGE_HANDOFF_UNUSED_LEGACY_FIELDS=NULL"
echo "PACKAGE_HANDOFF_TRIGGER_CLASS=POST_APPROVAL_PROJECTION"
echo "PACKAGE_HANDOFF_IDEMPOTENCY_CLASS=EXACT_IDENTITY_MATCH_OR_FAIL_CLOSED"
echo "PACKAGE_HANDOFF_CONFERS_NEW_AUTHORITY=NO"
echo "PACKAGE_HANDOFF_CONTRACT_SEMANTICS=CLASSIFIED"
echo "PROJECT_BOUND_HANDOFF_STARTED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "QUESTION=WHAT_IS_THE_MINIMUM_FAILURE_SAFE_IMPLEMENTATION_UNIT_FOR_PROJECTING_THE_EXACT_APPROVED_CANONICAL_PACKAGE_AFTER_APPROVAL_WITHOUT_COUPLING_AUTHORITY_OR_OVERWRITING_LEGACY_PACKAGE_PROVENANCE"
echo "NEXT_ACTION=DESIGN_BOUNDED_FAILURE_SAFE_POST_APPROVAL_PROJECTION_UNIT_WITHOUT_IMPLEMENTATION"
