#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY REMOTE PUSH SUCCESSOR UNIT ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "REMOTE_PUSH_EFFECT_IMPLEMENTATION_AUTHORIZED=NO"
echo "PUSH_AUTHORITY_TRANSITION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="693d3c9f6"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== CLOSED PREDECESSOR BOUNDARY ==="
echo "LOCAL_COMMIT_EFFECT_UNIT=CLOSED"
echo "LOCAL_COMMIT_EFFECT_COMMIT=5e46709dc"
echo "LOCAL_COMMIT_CLOSURE_COMMIT=693d3c9f6"
echo "GENERIC_CADE_ROUTE_REACHABILITY=NO"
echo "REMOTE_PUSH_EFFECT=NOT_ENABLED"
echo "GENERIC_SHELL_AUTHORITY=DISABLED"
echo "GENERIC_MUTATION_AUTHORITY=DISABLED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=DISABLED"

echo
echo "=== INSPECT CURRENT VERSION CONTROL EFFECT ==="
nl -ba server/cade/cade-version-control-effects.ts | sed -n '1,520p'

echo
echo "=== INSPECT GOVERNED LOCAL COMMIT ADAPTER ==="
nl -ba server/execution/cade-governed-commit-adapter.ts | sed -n '1,420p'

echo
echo "=== INSPECT APPROVAL GATE PUSH BOUNDARY ==="
grep -n -C 10 -E \
  'governed_version_control_commit|commit_authorized|push_authorized|PUSH_AUTHORITY_DISABLED' \
  server/execution/execution-approval-gate.mjs \
  | sed -n '1,320p'

echo
echo "=== INSPECT REMOTE / BRANCH VERIFICATION PRECEDENT ==="
git grep -n -I -E \
  'remote get-url|ls-remote|rev-parse.*origin|git.*push|push_authorized|remote_effect|push_effect' \
  -- server routes docs \
  | sed -n '1,620p' || true

echo
echo "=== SUCCESSOR UNIT CANDIDATE ==="
echo "CAPABILITY=GOVERNED_REMOTE_PUSH_ONLY"
echo "OWNER=CADE"
echo "PRECONDITION=SUCCESSFUL_GOVERNED_LOCAL_COMMIT"
echo "PUSH_MUST_NOT_CREATE_LOCAL_COMMIT=YES"
echo "PUSH_MUST_NOT_STAGE_FILES=YES"
echo "PUSH_MUST_NOT_MODIFY_WORKTREE=YES"
echo "PUSH_MUST_NOT_USE_GENERIC_SHELL=YES"

echo
echo "=== REQUIRED PUSH AUTHORITY CONTRACT ==="
echo "commit_authorized=true_REQUIRED"
echo "push_authorized=true_REQUIRED"
echo "GENERIC_MUTATION_AUTHORIZED=false_REQUIRED"
echo "SHELL_EXECUTION_AUTHORIZED=false_REQUIRED"
echo "AUTONOMOUS_EXECUTION_AUTHORIZED=false_REQUIRED"
echo "APPROVAL_ID_REQUIRED=YES"
echo "ENVELOPE_ID_REQUIRED=YES"
echo "EXECUTION_ID_REQUIRED=YES"
echo "REMOTE_REQUIRED=YES"
echo "BRANCH_REQUIRED=YES"

echo
echo "=== REQUIRED PRE-PUSH STATE ==="
echo "LOCAL_COMMIT_SUCCESS_REQUIRED=YES"
echo "EXPECTED_POST_COMMIT_HEAD_REQUIRED=YES"
echo "CURRENT_HEAD_MUST_EQUAL_EXPECTED_POST_COMMIT_HEAD=YES"
echo "CURRENT_BRANCH_MUST_EQUAL_AUTHORIZED_BRANCH=YES"
echo "REPOSITORY_ROOT_MUST_EQUAL_AUTHORIZED_REPO_PATH=YES"
echo "WORKTREE_TRACKED_STATE_MUST_NOT_HAVE_UNAUTHORIZED_DRIFT=YES"
echo "STAGED_SET_MUST_BE_EMPTY_OR_EXPLICITLY_PROVEN_EXPECTED=YES"

echo
echo "=== REQUIRED REMOTE CONTRACT ==="
echo "REMOTE_NAME_MUST_EQUAL_APPROVED_REMOTE=YES"
echo "REMOTE_URL_MUST_BE_OBSERVED_BEFORE_PUSH=YES"
echo "REMOTE_URL_MUST_MATCH_AUTHORIZED_REPOSITORY_IDENTITY=YES"
echo "TARGET_REF=refs/heads/AUTHORIZED_BRANCH"
echo "FORCE=PROHIBITED"
echo "FORCE_WITH_LEASE=PROHIBITED"
echo "DELETE_REMOTE_REF=PROHIBITED"
echo "SET_UPSTREAM=NOT_REQUIRED_FOR_FIRST_UNIT"
echo "ARBITRARY_REFSPEC=PROHIBITED"

echo
echo "=== REQUIRED PROCESS MODEL ==="
echo "PROCESS_API=execFile_or_execFileSync"
echo "COMMAND=git"
echo "ARGUMENT_ARRAY_ONLY=YES"
echo "shell=false"
echo "cwd=AUTHORIZED_REPO_PATH"
echo "PUSH_COMMAND_SHAPE=git push REMOTE HEAD:refs/heads/BRANCH"
echo "REMOTE_COMMANDS_OTHER_THAN_REQUIRED_VERIFICATION_AND_PUSH=PROHIBITED"

echo
echo "=== REQUIRED POST-PUSH VERIFICATION ==="
echo "VERIFY_REMOTE_HEAD_REQUIRED=YES"
echo "REMOTE_HEAD_MUST_EQUAL_LOCAL_POST_COMMIT_HEAD=YES"
echo "VERIFY_LOCAL_HEAD_UNCHANGED=YES"
echo "VERIFY_LOCAL_BRANCH_UNCHANGED=YES"
echo "VERIFY_NO_ADDITIONAL_LOCAL_COMMIT=YES"
echo "VERIFY_NO_FORCE_PUSH=YES"

echo
echo "=== REQUIRED PROVENANCE ==="
echo "EVENT_ACTION=push_changes"
echo "EVENT_INPUT.repo_path=YES"
echo "EVENT_INPUT.branch=YES"
echo "EVENT_INPUT.remote=YES"
echo "EVENT_INPUT.approval_id=YES"
echo "EVENT_INPUT.envelope_id=YES"
echo "EVENT_INPUT.execution_id=YES"
echo "EVENT_INPUT.expected_local_head=YES"
echo "EVENT_OUTPUT.pre_remote_head=YES"
echo "EVENT_OUTPUT.post_remote_head=YES"
echo "EVENT_OUTPUT.local_head=YES"
echo "EVENT_OUTPUT.remote_effect=true"
echo "EVENT_OUTPUT.push_effect=true"
echo "EVENT_OUTPUT.force_effect=false"

echo
echo "=== FAILURE BOUNDARIES ==="
echo "MISSING_PUSH_AUTHORITY=FAIL_CLOSED"
echo "LOCAL_HEAD_MISMATCH=FAIL_CLOSED"
echo "BRANCH_MISMATCH=FAIL_CLOSED"
echo "REMOTE_MISMATCH=FAIL_CLOSED"
echo "REMOTE_URL_IDENTITY_MISMATCH=FAIL_CLOSED"
echo "PREEXISTING_UNAUTHORIZED_TRACKED_DRIFT=FAIL_CLOSED"
echo "PREEXISTING_UNEXPECTED_STAGING=FAIL_CLOSED"
echo "PUSH_FAILURE=FAIL_CLOSED"
echo "REMOTE_HEAD_VERIFICATION_FAILURE=FAIL_CLOSED"
echo "LOCAL_STATE_CHANGE_DURING_PUSH=FAIL_CLOSED"

echo
echo "=== REQUIRED TEST STRATEGY ==="
echo "TEST_REPOSITORY=TEMP_LOCAL_GIT_REMOTE"
echo "NETWORK_REMOTE_REQUIRED=NO"
echo "TEST_1=AUTHORIZED_PUSH_TO_TEMP_BARE_REMOTE_SUCCEEDS"
echo "TEST_2=MISSING_PUSH_AUTHORITY_FAILS"
echo "TEST_3=HEAD_MISMATCH_FAILS"
echo "TEST_4=BRANCH_MISMATCH_FAILS"
echo "TEST_5=REMOTE_NAME_MISMATCH_FAILS"
echo "TEST_6=REMOTE_URL_MISMATCH_FAILS"
echo "TEST_7=FORCE_OPTION_UNAVAILABLE"
echo "TEST_8=REMOTE_HEAD_EQUALS_LOCAL_HEAD_AFTER_PUSH"
echo "TEST_9=LOCAL_HEAD_UNCHANGED_BY_PUSH"
echo "TEST_10=NO_GENERIC_SHELL"
echo "TEST_11=NO_GENERIC_CADE_ROUTE_REACHABILITY"

echo
echo "=== AUTHORITY SEPARATION ==="
echo "PUSH_APPROVAL_TRANSITION_MUST_BE_SEPARATE_FROM_PUSH_EFFECT=YES"
echo "PUSH_EFFECT_MUST_NOT_BE_IMPLEMENTED_BEFORE_PUSH_AUTHORITY_TRANSITION_VALIDATES=YES"
echo "LOCAL_COMMIT_APPROVAL_PHASE_MUST_REMAIN_STABLE=YES"
echo "LOCAL_COMMIT_EFFECT_MUST_REMAIN_STABLE=YES"
echo "GENERIC_CADE_EXECUTOR_CHANGE=NOT_RECOMMENDED"
echo "GENERIC_CADE_ROUTE_CHANGE=PROHIBITED"

echo
echo "=== CLASSIFICATION ==="
echo "REMOTE_PUSH_SUCCESSOR_UNIT=ARCHITECTURALLY_SUPPORTED"
echo "NEXT_UNIT_A=NARROW_PUSH_APPROVAL_GATE_TRANSITION"
echo "NEXT_UNIT_B=GOVERNED_REMOTE_PUSH_EFFECT"
echo "UNIT_A_MUST_CLOSE_BEFORE_UNIT_B=YES"
echo "PUSH_IMPLEMENTATION_AUTHORIZED=NO"
echo "NEXT_ACTION=CLASSIFY_AND_AUTHORIZE_NARROW_PUSH_APPROVAL_GATE_TRANSITION_ONLY"
