#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY APPROVALS INFORMATION FOR USER-FRIENDLY RECOMPOSITION ==="
echo "BASELINE_COMMIT=3227a61c"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== PRIMARY DECISION INFORMATION ==="
echo "KEEP_PROMINENT=interpreted_objective"
echo "KEEP_PROMINENT=expected_outcome"
echo "KEEP_PROMINENT=proposed_work"
echo "KEEP_PROMINENT=in_scope"
echo "KEEP_PROMINENT=out_of_scope"
echo "KEEP_PROMINENT=constraints"
echo "KEEP_PROMINENT=unresolved_questions_WHEN_PRESENT"
echo "KEEP_PROMINENT=approve_action"
echo "KEEP_PROMINENT=request_changes_action"

echo
echo "=== SECONDARY CONTEXT ==="
echo "KEEP_BUT_DEEMPHASIZE=proposed_artifacts"
echo "KEEP_BUT_DEEMPHASIZE=current_state_to_proposed_state_transition"
echo "KEEP_BUT_DEEMPHASIZE=source_draft_status"
echo "KEEP_BUT_DEEMPHASIZE=updated_timestamp"
echo "KEEP_BUT_DEEMPHASIZE=artifact_position"

echo
echo "=== TECHNICAL DETAIL ==="
echo "COLLAPSE_BY_DEFAULT=approval_request_id"
echo "COLLAPSE_BY_DEFAULT=draft_package_id"
echo "COLLAPSE_BY_DEFAULT=conversation_id"
echo "COLLAPSE_BY_DEFAULT=lineage_id"
echo "COLLAPSE_BY_DEFAULT=evidence_entry_ids"

echo
echo "=== REDUNDANCY / NOISE CANDIDATES ==="
echo "SIMPLIFY=REPEATED_PENDING_AND_NEEDS_REVIEW_BADGES"
echo "SIMPLIFY=REPEATED_APPROVE_CANONICAL_PACKAGE_LANGUAGE"
echo "SIMPLIFY=REPEATED_AUTHORITY_BOUNDARY_EXPLANATIONS"
echo "SIMPLIFY=ARTIFACT_SWITCHER_IF_TWO_PANEL_LIST_ALREADY_PROVIDES_SELECTION"
echo "SIMPLIFY=EXECUTIVE_QUESTION_IF_IT_ONLY_RESTATES_THE_DECISION"
echo "SIMPLIFY=PACKAGE_ID_NOTICE_IF_TECHNICAL_DETAILS_RETAIN_IDENTITY"

echo
echo "=== RECOMPOSITION TARGET ==="
echo "TARGET_SHELL=PACKAGES_TWO_PANEL_LIST_AND_DETAIL"
echo "LEFT_PANEL=COMPACT_APPROVAL_QUEUE"
echo "RIGHT_PANEL=DECISION_BRIEF"
echo "RIGHT_PANEL_ORDER=OBJECTIVE_OUTCOME_WORK_SCOPE_CONSTRAINTS_OPEN_QUESTIONS_ACTIONS"
echo "TECHNICAL_METADATA=COLLAPSED"
echo "AUTHORITY_BOUNDARY=ONE_CLEAR_CONCISE_NOTICE"
echo "DECISION_ACTIONS=VISIBLE_WITHOUT_SCROLLING_PAST_TECHNICAL_DETAIL"
echo "REMOVE_PACKAGES_TAB=DEFER_UNTIL_RECOMPOSED_APPROVALS_IS_VALIDATED"

echo
echo "NEXT_ACTION=COLLABORATIVELY_REVIEW_THIS_INFORMATION_HIERARCHY_BEFORE_ANY_REACT_CHANGE"
