#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY BOUNDED GIT EFFECT IMPLEMENTATION UNIT ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "GIT_EFFECT_IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="f24ec71f7"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== CURRENT CONTRACT CHECKPOINT ==="
echo "CONTRACT_COMMIT=024d849e3"
echo "VALIDATION_RECORD_COMMIT=f24ec71f7"
echo "CONTRACT_STATUS=CLOSED"
echo "CADE_GIT_EXECUTION_CAPABILITY=NOT_ENABLED"

echo
echo "=== INSPECT CURRENT CADE EXECUTION SURFACES ==="
for f in \
  server/cade/cade-executor.ts \
  server/execution/execution-approval-gate.mjs \
  server/execution/build-approval-artifact.mjs \
  server/contracts/execution-envelope.v1.mjs
do
  echo
  echo "--- ${f} ---"
  if [[ -f "${f}" ]]; then
    sed -n '1,260p' "${f}"
  else
    echo "MISSING=${f}"
  fi
done

echo
echo "=== SEARCH EXISTING PROCESS / GIT EXECUTION PRIMITIVES ==="
grep -RInE \
  'node:child_process|child_process|execFile|execSync|spawnSync|spawn\(|git[[:space:]]+(add|commit|push|status|rev-parse|diff)' \
  server \
  --exclude-dir=node_modules \
  --exclude='*.map' \
  | sed -n '1,320p' || true

echo
echo "=== SEARCH EXECUTION EVENT / PROVENANCE SURFACES ==="
grep -RInE \
  'execution.event|execution_event|executionEvents|provenance|expected_head|version_control_authorization|commit_authorized|push_authorized' \
  server \
  docs/governance \
  --exclude-dir=node_modules \
  | sed -n '1,360p' || true

echo
echo "=== REQUIRED BOUNDED EFFECT SEMANTICS ==="
echo "OWNER=CADE"
echo "PROCESS_MODEL=ARGUMENT_ARRAY_ONLY"
echo "SHELL_FALSE_REQUIRED=YES"
echo "GENERIC_SHELL_AUTHORITY_REQUIRED=NO"
echo "EXPECTED_HEAD_PRECONDITION_REQUIRED=YES"
echo "REPOSITORY_MATCH_REQUIRED=YES"
echo "BRANCH_MATCH_REQUIRED=YES"
echo "APPROVED_TRACKED_PATH_SET_REQUIRED=YES"
echo "GIT_ADD_DOT_PROHIBITED=YES"
echo "FORCE_PUSH_PROHIBITED=YES"
echo "FORCE_WITH_LEASE_PROHIBITED=YES"
echo "COMMIT_AND_PUSH_SEPARATE_STEPS=YES"
echo "PUSH_REQUIRES_COMMIT_SUCCESS=YES"
echo "PUSH_REQUIRES_VALIDATION_SUCCESS=YES"
echo "REMOTE_HEAD_VERIFICATION_REQUIRED=YES"

echo
echo "=== CANDIDATE FIRST EFFECT UNIT ==="
echo "CANDIDATE=GOVERNED_LOCAL_COMMIT_ONLY"
echo "REMOTE_PUSH_INCLUDED=NO"
echo "FILESYSTEM_MUTATION_SCOPE=AUTHORIZED_TRACKED_PATHS_ONLY"
echo "UNAPPROVED_TRACKED_DIRTY_FILE_BEHAVIOR=FAIL_CLOSED"
echo "UNTRACKED_UNRELATED_FILE_BEHAVIOR=PERMITTED_BUT_NEVER_STAGED"
echo "VERSION_CONTROL_AUTHORIZATION_COMMIT_REQUIRED=YES"
echo "VERSION_CONTROL_AUTHORIZATION_PUSH_REQUIRED=NO"
echo "GENERIC_MUTATION_AUTHORIZATION_IMPLIED=NO"
echo "GENERIC_SHELL_AUTHORIZATION_IMPLIED=NO"

echo
echo "=== REQUIRED PRE-COMMIT CHECK SEQUENCE ==="
echo "CHECK_1=REPO_ROOT_MATCH"
echo "CHECK_2=EXPECTED_HEAD_MATCH"
echo "CHECK_3=ACTIVE_BRANCH_MATCH"
echo "CHECK_4=TRACKED_DIRTY_SET_WITHIN_AUTHORIZED_PATHS"
echo "CHECK_5=NO_PREEXISTING_UNAUTHORIZED_STAGED_PATHS"
echo "CHECK_6=STAGE_EXPLICIT_AUTHORIZED_PATHS_ONLY"
echo "CHECK_7=VERIFY_STAGED_SET_EXACTLY"
echo "CHECK_8=CREATE_COMMIT_WITH_ARGUMENT_ARRAY_PROCESS"
echo "CHECK_9=VERIFY_NEW_HEAD_AND_PARENT"
echo "CHECK_10=RECORD_EXECUTION_PROVENANCE"

echo
echo "=== FAILURE BOUNDARIES ==="
echo "HEAD_MISMATCH=FAIL_CLOSED"
echo "BRANCH_MISMATCH=FAIL_CLOSED"
echo "UNAUTHORIZED_TRACKED_CHANGE=FAIL_CLOSED"
echo "UNAUTHORIZED_STAGED_PATH=FAIL_CLOSED"
echo "COMMIT_COMMAND_FAILURE=FAIL_CLOSED"
echo "POST_COMMIT_HEAD_VERIFICATION_FAILURE=FAIL_CLOSED"
echo "PUSH_ATTEMPT_IN_FIRST_UNIT=PROHIBITED"

echo
echo "=== ARCHITECTURAL CLASSIFICATION ==="
echo "FIRST_GIT_EFFECT_SHOULD_BE_LOCAL_COMMIT_ONLY=RECOMMENDED"
echo "PUSH_SHOULD_BE_SUCCESSOR_UNIT=RECOMMENDED"
echo "LEGACY_DIRECT_GIT_ROUTE_REACTIVATION=PROHIBITED"
echo "EFFIE_EXECUTION_AUTHORITY=NONE"
echo "MISSION_CONTROL_WRITE_AUTHORITY=NONE"
echo "CONTRACT_BOUNDARIES_MUST_REMAIN_UNCHANGED=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=INSPECT_EXACT_CADE_EXECUTOR_AND_EXECUTION_EVENT_EXTENSION_POINTS_BEFORE_AUTHORIZING_LOCAL_COMMIT_IMPLEMENTATION"
