#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY ACTIVE PROJECT SOURCE AND MISSION CONTROL INTAKE UNIT ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=MISSION_CONTROL_INTAKE"
echo "PROJECT_BOUND_HANDOFF_CLOSURE_COMMIT=5d62f34f"
echo "LATEST_DR=20260825_141501"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== ACTIVE PROJECT AUTHORITY SOURCE ==="
echo "PROJECT_CONTEXT_PROVIDER=client/src/project-context/ProjectContextProvider.tsx"
echo "PROJECT_CONTEXT_CONSUMER_HOOK=client/src/project-context/useProjectContext.ts"
echo "PROJECT_CONTEXT_REGISTRY_ACTIVE_ID=registry.activeProjectId"
echo "ACTIVE_PROJECT_SOURCE_CLASS=SHARED_PROJECT_CONTEXT"
echo "ACTIVE_PROJECT_SELECTION_OWNED_BY_MISSION_CONTROL=NO"

echo
echo "=== VERIFY PROJECT CONTEXT SOURCE ==="
rg -n -C 18 \
  'activeProjectId|activeProject|ProjectContextProvider|useProjectContext' \
  client/src/project-context \
  2>/dev/null || true

echo
echo "=== VERIFY EXISTING PROJECT-SCOPED CONSUMER PRECEDENTS ==="
rg -n -C 12 \
  'registry\?\.activeProjectId|registry\?\.activeProject\?\.projectId|useProjectContext\(\)' \
  client/src/matilda-chat/MatildaConversationProvider.tsx \
  client/src/packages/PackageReadProvider.tsx \
  client/src/shell/PlaceholderWorkspace.tsx \
  2>/dev/null || true

echo
echo "=== CURRENT MISSION CONTROL SURFACES ==="
sed -n '1,260p' client/src/mission-control/missionReadApi.ts
sed -n '1,340p' client/src/mission-control/MissionControlProvider.tsx
sed -n '1,300p' client/src/shell/MissionDashboardWorkspace.tsx

echo
echo "=== SERVER CONTRACT CONFIRMATION ==="
sed -n '1,180p' routes/api-mission-read.ts

echo
echo "=== ACTIVE PROJECT SOURCE DETERMINATION ==="
echo "ACTIVE_PROJECT_IDENTITY_ALREADY_EXISTS_CLIENT_SIDE=YES"
echo "AUTHORITATIVE_CLIENT_SOURCE=ProjectContextProvider.registry.activeProjectId"
echo "MISSION_CONTROL_MAY_CONSUME_EXISTING_ACTIVE_PROJECT_ID=YES"
echo "MISSION_CONTROL_MAY_SET_ACTIVE_PROJECT_ID=NO"
echo "MISSION_CONTROL_NEEDS_NEW_PROJECT_SELECTION_STATE=NO"
echo "MISSION_CONTROL_NEEDS_NEW_PACKAGE_SELECTION_STATE=NO"

echo
echo "=== MINIMUM CLIENT API CONTRACT ==="
echo "MISSION_READ_CLIENT_INPUT_BEFORE=packageId"
echo "MISSION_READ_CLIENT_INPUT_AFTER=projectId"
echo "MISSION_READ_ENDPOINT=/api/mission-read/:projectId"
echo "MISSION_READ_CLIENT_MUST_NOT_SEND_PACKAGE_ID=YES"
echo "MISSION_READ_CLIENT_MUST_NOT_SELECT_PACKAGE_VERSION=YES"
echo "MISSION_READ_CLIENT_MUST_NOT_INFER_NEWEST_PACKAGE=YES"
echo "SERVER_REMAINS_OPERATIONAL_AUTHORITY_RESOLVER=YES"

echo
echo "=== MINIMUM PROVIDER CONTRACT ==="
echo "MISSION_CONTROL_PROVIDER_INPUT=activeProjectId_FROM_ProjectContext"
echo "PROVIDER_LAST_IDENTITY_CACHE_IF_RETAINED=projectId_NOT_packageId"
echo "PROVIDER_REFRESH_TRIGGER=activeProjectId_CHANGE"
echo "PROVIDER_LOAD_CALL=loadMission(activeProjectId)"
echo "PROVIDER_NO_ACTIVE_PROJECT_STATE=NO_MISSION"
echo "PROVIDER_404_STATE=NO_ACTIVE_MISSION"
echo "PROVIDER_IDENTITY_CONFLICT=ERROR_FAIL_CLOSED"
echo "PROVIDER_PACKAGE_SELECTION_LOGIC=NONE"

echo
echo "=== MINIMUM WORKSPACE CONTRACT ==="
echo "HARDCODED_corridor-smoke_REMOVAL_REQUIRED=YES"
echo "WORKSPACE_MUST_READ_ACTIVE_PROJECT_FROM_SHARED_CONTEXT=YES"
echo "WORKSPACE_MAY_SELECT_PACKAGE=NO"
echo "WORKSPACE_MAY_FALL_BACK_TO_HARDCODED_PACKAGE=NO"
echo "WORKSPACE_MAY_FALL_BACK_TO_NEWEST_PACKAGE=NO"
echo "NO_ACTIVE_PROJECT_PRESENTATION=EMPTY_OR_NO_MISSION_STATE"

echo
echo "=== EXACT BOUNDED IMPLEMENTATION SURFACES ==="
echo "SURFACE_1=client/src/mission-control/missionReadApi.ts"
echo "SURFACE_2=client/src/mission-control/MissionControlProvider.tsx"
echo "SURFACE_3=client/src/shell/MissionDashboardWorkspace.tsx"
echo "SURFACE_4=TARGETED_CLIENT_TESTS_IF_EXISTING_TEST_ARCHITECTURE_SUPPORTS_THESE_SURFACES"
echo "ProjectContextProvider_CHANGE_REQUIRED=NO"
echo "PackageReadProvider_CHANGE_REQUIRED=NO"
echo "SERVER_ROUTE_CHANGE_REQUIRED=NO"
echo "MISSION_READ_REPOSITORY_CHANGE_REQUIRED=NO"
echo "SCHEMA_CHANGE_REQUIRED=NO"
echo "MIGRATION_CHANGE_REQUIRED=NO"

echo
echo "=== FAILURE CONTRACT ==="
echo "MISSING_ACTIVE_PROJECT=NO_MISSION_INTAKE"
echo "SERVER_404_NO_OPERATIONAL_AUTHORITY=NO_ACTIVE_MISSION"
echo "SERVER_409_IDENTITY_CONFLICT=FAIL_CLOSED_ERROR"
echo "SERVER_500=FAIL_CLOSED_ERROR"
echo "PACKAGE_ID_BROWSER_FALLBACK=NO"
echo "HARDCODED_PACKAGE_FALLBACK=NO"
echo "NEWEST_PACKAGE_FALLBACK=NO"
echo "STALE_PREVIOUS_PROJECT_MISSION_PRESERVED_AFTER_PROJECT_SWITCH=NO"

echo
echo "=== AUTHORITY NON-ESCALATION ==="
echo "MISSION_CONTROL_SELECTS_ACTIVE_PROJECT=NO"
echo "MISSION_CONTROL_SELECTS_OPERATIONAL_PACKAGE=NO"
echo "MISSION_CONTROL_MUTATES_OPERATIONAL_PACKAGE_AUTHORITY=NO"
echo "MISSION_CONTROL_CREATES_DELEGATION=NO"
echo "MISSION_CONTROL_CONFERS_VALIDATION_AUTHORITY=NO"
echo "MISSION_CONTROL_CONFERS_ROUTING_AUTHORITY=NO"
echo "MISSION_CONTROL_CONFERS_ASSIGNMENT_AUTHORITY=NO"
echo "MISSION_CONTROL_CONFERS_EXECUTION_AUTHORITY=NO"

echo
echo "=== REQUIRED VALIDATION IF AUTHORIZED ==="
echo "VALIDATION_1=TYPECHECK"
echo "VALIDATION_2=MISSION_READ_CLIENT_CALLS_PROJECT_SCOPED_ENDPOINT"
echo "VALIDATION_3=ACTIVE_PROJECT_ID_DRIVES_MISSION_READ_REQUEST"
echo "VALIDATION_4=HARDCODED_corridor-smoke_REMOVED_FROM_MISSION_CONTROL_INTAKE"
echo "VALIDATION_5=PROJECT_SWITCH_RELOADS_MISSION_BY_NEW_PROJECT_ID"
echo "VALIDATION_6=NO_ACTIVE_PROJECT_CLEARS_MISSION_STATE"
echo "VALIDATION_7=NO_OPERATIONAL_AUTHORITY_PRESENTS_NO_ACTIVE_MISSION"
echo "VALIDATION_8=IDENTITY_CONFLICT_FAILS_CLOSED"
echo "VALIDATION_9=NO_PACKAGE_SELECTION_LOGIC_ADDED"
echo "VALIDATION_10=NO_OPERATIONAL_AUTHORITY_MUTATION"
echo "VALIDATION_11=NO_DELEGATION_OR_EXECUTION_AUTHORITY_CHANGE"

echo
echo "=== SCOPE DETERMINATION ==="
echo "ACTIVE_PROJECT_AUTHORITY_SOURCE=CLASSIFIED"
echo "ACTIVE_PROJECT_AUTHORITY_SOURCE_VALUE=ProjectContextProvider.registry.activeProjectId"
echo "MISSION_CONTROL_INTAKE_IMPLEMENTATION_UNIT=BOUNDED_AND_CLASSIFIED"
echo "MISSION_CONTROL_INTAKE_IMPLEMENTATION_STARTED=NO"
echo "MISSION_CONTROL_PACKAGE_AUTHORITY=NONE"
echo "SERVER_PROJECT_BOUND_HANDOFF_REMAINS_AUTHORITATIVE=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=PRESENT_SEPARATE_AUTHORIZATION_GATE_FOR_MINIMUM_MISSION_CONTROL_PROJECT_SCOPED_INTAKE_WIRING_ONLY"
