#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY FIRST CADE VERSION CONTROL IMPLEMENTATION UNIT ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="89f0fb13a"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== EVIDENCE-BASED ANSWER ==="
echo "FIRST_UNIT_CAN_BE_PATCHED_WITHOUT_ENABLING_EXECUTION=YES"
echo "EXISTING_PLANNING_ONLY_BEHAVIOR_CAN_BE_PRESERVED=YES"
echo "GIT_SIDE_EFFECTS_REQUIRED=NO"
echo "CADE_EXECUTOR_CHANGE_REQUIRED_IN_FIRST_UNIT=NO"
echo "GENERIC_MUTATION_AUTHORITY_CHANGE_REQUIRED=NO"
echo "GENERIC_SHELL_AUTHORITY_CHANGE_REQUIRED=NO"
echo "AUTONOMOUS_AUTHORITY_CHANGE_REQUIRED=NO"

echo
echo "=== FIRST IMPLEMENTATION UNIT ==="
echo "UNIT_NAME=CADE_VERSION_CONTROL_CONTRACT_AND_AUTHORIZATION_SEMANTICS"
echo "UNIT_PURPOSE=ESTABLISH_FAIL_CLOSED_CONTRACT_BEFORE_ANY_GIT_EXECUTION"
echo "UNIT_EXECUTION_MODE=NON_MUTATING"
echo "UNIT_REMOTE_SIDE_EFFECTS=NONE"

echo
echo "=== EXACT PATCH SET ==="
echo "PATCH_1=server/contracts/execution-envelope.v1.mjs"
echo "PATCH_1_CHANGE=ADD_OPTIONAL_PROJECT_TARGET_EXPECTED_HEAD_DEFAULT_NULL"
echo "PATCH_1_COMPATIBILITY=ORDINARY_PLANNING_ENVELOPES_REMAIN_VALID"

echo "PATCH_2=server/execution/build-execution-envelope-draft.mjs"
echo "PATCH_2_CHANGE=TRANSPORT_PROJECT_TARGET_EXPECTED_HEAD_WHEN_SUPPLIED"
echo "PATCH_2_DEFAULT=NULL"

echo "PATCH_3=server/execution/build-approval-artifact.mjs"
echo "PATCH_3_CHANGE=ADD_VERSION_CONTROL_AUTHORIZATION_SUBCONTRACT"
echo "PATCH_3_DEFAULT_COMMIT_AUTHORIZED=false"
echo "PATCH_3_DEFAULT_PUSH_AUTHORIZED=false"
echo "PATCH_3_DEFAULT_REMOTE=origin"
echo "PATCH_3_DEFAULT_BRANCH=null"

echo "PATCH_4=server/execution/execution-approval-gate.mjs"
echo "PATCH_4_CHANGE=NORMALIZE_VERSION_CONTROL_AUTHORIZATION_WITH_FALSE_DEFAULTS"
echo "PATCH_4_CHANGE_2=PRESERVE_PLANNING_ONLY_OUTPUT"
echo "PATCH_4_CHANGE_3=DO_NOT_ENABLE_COMMIT_OR_PUSH"
echo "PATCH_4_CHANGE_4=DO_NOT_MAP_VERSION_CONTROL_AUTHORIZATION_TO_SHELL_AUTHORITY"

echo "PATCH_5=server/guards/validate-execution-envelope.mjs"
echo "PATCH_5_CHANGE=VALIDATE_EXPECTED_HEAD_SHAPE_WHEN_PRESENT"
echo "PATCH_5_CHANGE_2=DO_NOT_REQUIRE_EXPECTED_HEAD_FOR_ORDINARY_PLANNING_ENVELOPES"

echo "PATCH_6=server/execution/governance-validator.mjs"
echo "PATCH_6_CHANGE=PRESERVE_CURRENT_DRY_RUN_ONLY_GOVERNANCE"
echo "PATCH_6_CHANGE_2=NO_VERSION_CONTROL_EXECUTION_AUTHORITY"

echo
echo "=== EXPECTED_HEAD CONDITIONAL REQUIREMENT ==="
echo "EXPECTED_HEAD_GLOBAL_REQUIRED=NO"
echo "EXPECTED_HEAD_REQUIRED_FOR_ORDINARY_PLANNING=NO"
echo "EXPECTED_HEAD_REQUIRED_FOR_FUTURE_CADE_COMMIT=YES"
echo "EXPECTED_HEAD_REQUIRED_FOR_FUTURE_CADE_PUSH=YES"
echo "RATIONALE=BACKWARD_COMPATIBILITY_AND_SCOPE_SEPARATION"

echo
echo "=== VERSION CONTROL AUTHORIZATION SHAPE ==="
echo "SUBCONTRACT=version_control_authorization"
echo "FIELD_1=commit_authorized:boolean"
echo "FIELD_2=push_authorized:boolean"
echo "FIELD_3=remote:string_or_null"
echo "FIELD_4=branch:string_or_null"
echo "DEFAULT_COMMIT_AUTHORIZED=false"
echo "DEFAULT_PUSH_AUTHORIZED=false"
echo "COMMIT_DOES_NOT_IMPLY_PUSH=YES"
echo "PUSH_DOES_NOT_IMPLY_SHELL=YES"
echo "MUTATION_DOES_NOT_IMPLY_COMMIT=YES"
echo "EXECUTION_AUTHORIZED_DOES_NOT_IMPLY_COMMIT=YES"

echo
echo "=== FIRST UNIT TEST SURFACES ==="
echo "TEST_FILE_1=server/execution/smoke-test-envelope-draft.mjs"
echo "TEST_FILE_2=server/execution/smoke-test-approval-gate.mjs"
echo "TEST_FILE_3=server/execution/smoke-test-governed-planning-pipeline.mjs"
echo "NEW_TEST_RECOMMENDED=server/execution/smoke-test-version-control-contract.mjs"

echo
echo "=== REQUIRED TEST CASES ==="
echo "TEST_1=ORDINARY_PLANNING_ENVELOPE_WITHOUT_EXPECTED_HEAD_STILL_VALID"
echo "TEST_2=EXPECTED_HEAD_WHEN_PRESENT_IS_PRESERVED"
echo "TEST_3=MALFORMED_EXPECTED_HEAD_FAILS_CLOSED"
echo "TEST_4=APPROVAL_ARTIFACT_DEFAULT_COMMIT_AUTHORIZED_FALSE"
echo "TEST_5=APPROVAL_ARTIFACT_DEFAULT_PUSH_AUTHORIZED_FALSE"
echo "TEST_6=COMMIT_AUTHORIZED_TRUE_DOES_NOT_IMPLY_PUSH_AUTHORIZED_TRUE"
echo "TEST_7=VERSION_CONTROL_AUTHORIZATION_DOES_NOT_ENABLE_SHELL"
echo "TEST_8=VERSION_CONTROL_AUTHORIZATION_DOES_NOT_ENABLE_MUTATION"
echo "TEST_9=PLANNING_PIPELINE_REMAINS_GOVERNED_PLANNING_ONLY"
echo "TEST_10=NO_GIT_COMMAND_EXECUTED"

echo
echo "=== TEST COMMANDS FOR IMPLEMENTATION UNIT ==="
echo "TEST_COMMAND_1=node server/execution/smoke-test-envelope-draft.mjs"
echo "TEST_COMMAND_2=node server/execution/smoke-test-approval-gate.mjs"
echo "TEST_COMMAND_3=node server/execution/smoke-test-governed-planning-pipeline.mjs"
echo "TEST_COMMAND_4=node server/execution/smoke-test-version-control-contract.mjs"
echo "TEST_COMMAND_5=npx tsc --noEmit"

echo
echo "=== EXPLICITLY OUT OF SCOPE ==="
echo "OUT_OF_SCOPE_1=server/cade/cade-executor.ts"
echo "OUT_OF_SCOPE_2=NEW_GIT_EFFECT"
echo "OUT_OF_SCOPE_3=git_add"
echo "OUT_OF_SCOPE_4=git_commit"
echo "OUT_OF_SCOPE_5=git_push"
echo "OUT_OF_SCOPE_6=REMOTE_WRITE"
echo "OUT_OF_SCOPE_7=LEGACY_CADE_ROUTER"
echo "OUT_OF_SCOPE_8=EFFIE"
echo "OUT_OF_SCOPE_9=GENERIC_SHELL"
echo "OUT_OF_SCOPE_10=ROUTING_REWRITE"

echo
echo "=== FAILURE CONTAINMENT ==="
echo "PATCH_MUST_PRESERVE_ALL_EXISTING_PLANNING_SMOKES=YES"
echo "ANY_EXISTING_PLANNING_REGRESSION=REVERT"
echo "ANY_AUTHORITY_ESCALATION=REVERT"
echo "ANY_GIT_SIDE_EFFECT=REVERT"
echo "THREE_FAILED_HYPOTHESIS_RULE=ACTIVE"

echo
echo "=== CURRENT DETERMINATION ==="
echo "FIRST_IMPLEMENTATION_UNIT_EXACTLY_CLASSIFIED=YES"
echo "FIRST_IMPLEMENTATION_UNIT_LOW_RISK=YES"
echo "FIRST_IMPLEMENTATION_UNIT_ENABLES_COMMIT_PUSH=NO"
echo "FIRST_IMPLEMENTATION_UNIT_PREPARES_COMMIT_PUSH_CONTRACT=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "NEXT_ACTION=AUTHORIZE_AND_APPLY_CONTRACT_ONLY_IMPLEMENTATION_UNIT"
