#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY NARROW VERSION CONTROL APPROVAL TRANSITION ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "APPROVAL_GATE_IMPLEMENTATION_AUTHORIZED=NO"
echo "LOCAL_COMMIT_EFFECT_IMPLEMENTATION_AUTHORIZED=NO"
echo "REMOTE_PUSH_IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="76edca0c4"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== CURRENT APPROVAL GATE STATE ==="
grep -n -C 6 -E \
  'execution_phase|commit_authorized|push_authorized|mutation_authorized|shell_execution_authorized|autonomous_execution_authorized' \
  server/execution/execution-approval-gate.mjs \
  | sed -n '1,260p'

echo
echo "=== CURRENT EXECUTION SWITCH CONTRACT ==="
nl -ba server/execution/matilda-execution-switch-evaluator.ts \
  | sed -n '1,280p'

echo
echo "=== CURRENT APPROVAL ARTIFACT CONTRACT ==="
nl -ba server/execution/build-approval-artifact.mjs \
  | sed -n '1,240p'

echo
echo "=== GOVERNANCE VALIDATOR CURRENT AUTHORITY ==="
nl -ba server/execution/governance-validator.mjs \
  | sed -n '1,320p'

echo
echo "=== GOVERNED PLANNING ROUTE ==="
nl -ba server/routes/governed-planning-route.mjs \
  | sed -n '1,320p'

echo
echo "=== SEARCH APPROVAL GATE CALLERS ==="
git grep -n -I -E \
  'evaluateExecutionApproval|buildApprovalArtifact|governed_planning_only|version_control_authorization' \
  -- server routes \
  | sed -n '1,620p' || true

echo
echo "=== REQUIRED NARROW TRANSITION ==="
echo "CURRENT_PHASE=governed_planning_only"
echo "CANDIDATE_SUCCESSOR_PHASE=governed_version_control_commit"
echo "SUCCESSOR_SCOPE=LOCAL_COMMIT_ONLY"
echo "COMMIT_AUTHORIZED_CAN_BECOME_TRUE=YES"
echo "PUSH_AUTHORIZED_MUST_REMAIN_FALSE=YES"
echo "MUTATION_AUTHORIZED_MUST_REMAIN_FALSE=YES"
echo "SHELL_EXECUTION_AUTHORIZED_MUST_REMAIN_FALSE=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORIZED_MUST_REMAIN_FALSE=YES"

echo
echo "=== REQUIRED INPUT CONDITIONS ==="
echo "GOVERNANCE_OK_REQUIRED=YES"
echo "DELEGATED_ENVELOPE_REQUIRED=YES"
echo "APPROVAL_PRESENT_REQUIRED=YES"
echo "APPROVAL_STATUS_APPROVED_OR_EQUIVALENT_REQUIRED=YES"
echo "REQUESTED_COMMIT_AUTHORIZED_TRUE_REQUIRED=YES"
echo "REQUESTED_PUSH_AUTHORIZED_FALSE_REQUIRED=YES"
echo "EXPECTED_HEAD_REQUIRED=YES"
echo "BRANCH_REQUIRED=YES"
echo "REPO_PATH_REQUIRED=YES"
echo "ALLOWED_PATHS_NONEMPTY_REQUIRED=YES"
echo "GENERIC_MUTATION_FALSE_REQUIRED=YES"
echo "GENERIC_SHELL_FALSE_REQUIRED=YES"
echo "AUTONOMOUS_FALSE_REQUIRED=YES"

echo
echo "=== FAIL-CLOSED AUTHORITY RULES ==="
echo "MISSING_EXPECTED_HEAD=BLOCK_COMMIT_AUTHORITY"
echo "MISSING_BRANCH=BLOCK_COMMIT_AUTHORITY"
echo "MISSING_REPO_PATH=BLOCK_COMMIT_AUTHORITY"
echo "EMPTY_ALLOWED_PATHS=BLOCK_COMMIT_AUTHORITY"
echo "PUSH_REQUESTED_TRUE=BLOCK_FIRST_LOCAL_COMMIT_PHASE"
echo "GENERIC_MUTATION_TRUE=BLOCK"
echo "GENERIC_SHELL_TRUE=BLOCK"
echo "AUTONOMOUS_TRUE=BLOCK"
echo "GOVERNANCE_FAILURE=BLOCK"
echo "UNDELEGATED_ENVELOPE=BLOCK"
echo "APPROVAL_ABSENT=BLOCK"

echo
echo "=== EXECUTION SWITCH RELATIONSHIP ==="
echo "EXECUTION_SWITCH_STATE_GRAPH_REMAINS_CANONICAL=YES"
echo "VERSION_CONTROL_PHASE_MUST_NOT_BYPASS_EXECUTION_SWITCH=YES"
echo "COMMIT_AUTHORIZATION_IS_CAPABILITY_SPECIFIC=YES"
echo "COMMIT_AUTHORIZATION_IS_NOT_GENERIC_EXECUTABLE_AUTHORITY=YES"
echo "NO_DIRECT_EXECUTABLE_ASSIGNMENT=YES"

echo
echo "=== PROPOSED APPROVAL OUTPUT SHAPE ==="
echo "execution_phase=governed_version_control_commit"
echo "mutation_authorized=false"
echo "shell_execution_authorized=false"
echo "autonomous_execution_authorized=false"
echo "version_control_authorization.commit_authorized=true"
echo "version_control_authorization.push_authorized=false"
echo "version_control_authorization.remote=origin_or_approved_remote"
echo "version_control_authorization.branch=approved_branch"

echo
echo "=== TRACE REQUIREMENTS ==="
echo "TRACE_APPROVAL_ARTIFACT_NORMALIZED=REQUIRED"
echo "TRACE_GOVERNANCE_VALIDATED=REQUIRED"
echo "TRACE_DELEGATION_VALIDATED=REQUIRED"
echo "TRACE_VERSION_CONTROL_COMMIT_AUTHORITY_GRANTED=REQUIRED"
echo "TRACE_PUSH_AUTHORITY_BLOCKED=REQUIRED"
echo "TRACE_GENERIC_MUTATION_AUTHORITY_BLOCKED=REQUIRED"
echo "TRACE_SHELL_AUTHORITY_BLOCKED=REQUIRED"
echo "TRACE_AUTONOMOUS_AUTHORITY_BLOCKED=REQUIRED"

echo
echo "=== FIRST PATCH CANDIDATE ==="
echo "PATCH_FILE_1=server/execution/execution-approval-gate.mjs"
echo "PATCH_FILE_2=server/execution/smoke-test-version-control-contract.mjs"
echo "PATCH_FILE_3=OPTIONAL_NEW_DEDICATED_APPROVAL_SMOKE_IF_NEEDED"
echo "BUILD_APPROVAL_ARTIFACT_CHANGE_EXPECTED=NO_UNLESS_APPROVED_STATUS_SEMANTICS_REQUIRE_IT"
echo "EXECUTION_SWITCH_CHANGE_EXPECTED=NO"
echo "GOVERNANCE_VALIDATOR_CHANGE_EXPECTED=NO"
echo "CADE_EXECUTOR_CHANGE=NO"
echo "GIT_EFFECT_MODULE_CHANGE=NO"

echo
echo "=== IMPLEMENTATION SEPARATION ==="
echo "UNIT_A=NARROW_APPROVAL_GATE_COMMIT_AUTHORITY"
echo "UNIT_B=LOCAL_COMMIT_EFFECT"
echo "UNIT_C=REMOTE_PUSH_EFFECT"
echo "UNIT_A_MUST_VALIDATE_BEFORE_UNIT_B=YES"
echo "UNIT_B_MUST_VALIDATE_BEFORE_UNIT_C=YES"

echo
echo "=== FAILURE CONTAINMENT ==="
echo "NO_APPROVAL_GATE_EDIT=YES"
echo "NO_EXECUTION_SWITCH_EDIT=YES"
echo "NO_GOVERNANCE_VALIDATOR_EDIT=YES"
echo "NO_CADE_EXECUTOR_EDIT=YES"
echo "NO_GIT_EFFECT_EXECUTED=YES"
echo "NO_REMOTE_WRITE=YES"

echo
echo "=== CLASSIFICATION ==="
echo "NARROW_COMMIT_APPROVAL_TRANSITION=ARCHITECTURALLY_SUPPORTED"
echo "GENERIC_EXECUTION_AUTHORITY_EXPANSION_REQUIRED=NO"
echo "LOCAL_COMMIT_EFFECT_CAN_REMAIN_SEPARATE=YES"
echo "PUSH_REMAINS_SUCCESSOR_UNIT=YES"
echo "NEXT_ACTION=AUTHORIZE_AND_IMPLEMENT_NARROW_APPROVAL_GATE_COMMIT_AUTHORITY_UNIT_ONLY"
