#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== DELEGATION CORRIDOR CURRENT-STATE RECONCILIATION ==="

echo
echo "=== BASELINE ==="
printf "HEAD=" && git rev-parse --short=8 HEAD
printf "BRANCH=" && git branch --show-current
git status --short

echo
echo "=== AUTHORITATIVE CORRIDOR HISTORY ==="
echo "PRODUCTION_DELEGATION_PACKAGE_ROOT_RECONCILIATION_IMPLEMENTATION_STATUS=COMPLETE_AND_VALIDATED"
echo "CORRIDOR_CLOSURE_DOCUMENT=docs/governance/PRODUCTION_DELEGATION_PACKAGE_ROOT_RECONCILIATION_CLOSURE_2026-08-23.md"
echo "DO_NOT_REOPEN_COMPLETED_IMPLEMENTATION_CORRIDOR=YES"

echo
echo "=== VERIFY CLOSURE EVIDENCE ==="
rg -n -C 12 \
  'Status: COMPLETE_AND_VALIDATED|Production Delegation is now rooted in the authoritative Canonical Package identity|package_id, package_version' \
  docs/governance/PRODUCTION_DELEGATION_PACKAGE_ROOT_RECONCILIATION_CLOSURE_2026-08-23.md

echo
echo "=== DISTINGUISH RUNTIME CAPABILITY FROM AUTHORITY EVENT ==="
echo "CANONICAL_DELEGATION_RUNTIME_REANCHOR_IMPLEMENTED=YES"
echo "CANONICAL_DELEGATION_RUNTIME_REANCHOR_VALIDATED=YES"
echo "LIVE_CANONICAL_PACKAGE_CURRENTLY_HAS_DELEGATION=NO"
echo "REASON=EXPLICIT_OPERATOR_DELEGATION_HAS_NOT_OCCURRED_FOR_CURRENT_CANONICAL_PACKAGE"
echo "ABSENT_LIVE_DELEGATION_MEANS_RUNTIME_IMPLEMENTATION_INCOMPLETE=NO"
echo "ABSENT_LIVE_DELEGATION_MEANS_AUTHORITY_EVENT_PENDING=YES"

echo
echo "=== LIVE CANONICAL PACKAGE STATE ==="
sqlite3 -header -column db/main.db "
SELECT
  cp.package_id,
  cp.package_version,
  cp.status,
  CASE WHEN d.delegation_id IS NULL THEN 'NO' ELSE 'YES' END AS delegation_present,
  d.delegation_id,
  d.authorization_state
FROM matilda_canonical_packages cp
LEFT JOIN governance_delegations d
  ON d.package_id = cp.package_id
 AND d.package_version = cp.package_version
ORDER BY cp.created_at;
"

echo
echo "=== CORRECTED ACTIVE-HANDOFF CLASSIFICATION ==="
echo "COMPLETED_CORRIDOR=PRODUCTION_DELEGATION_PACKAGE_ROOT_RECONCILIATION"
echo "COMPLETED_CORRIDOR_REOPENED=NO"
echo "CURRENT_CANONICAL_PACKAGE_STATE=PENDING_EXPLICIT_OPERATOR_DELEGATION"
echo "CURRENT_RUNTIME_BLOCKER_TO_DELEGATION=NONE_ESTABLISHED"
echo "DELEGATION_AUTHORITY_EVENT_COMPLETED=NO"
echo "DELEGATION_AUTHORITY_EVENT_MAY_BE_INVOKED_AUTOMATICALLY=NO"
echo "GOVERNANCE_VALIDATION_MAY_BEGIN_BEFORE_DELEGATION=NO"

echo
echo "=== DOWNSTREAM RECONCILIATION DISPOSITION ==="
echo "VALIDATION_GATE_ENVELOPE_ROOT_DEFECT=VERIFIED_REAL"
echo "DOWNSTREAM_RECONCILIATION_REQUIRED_BEFORE_CURRENT_OPERATOR_DELEGATION=NO"
echo "DOWNSTREAM_RECONCILIATION=SEPARATELY_DEFERRED_SUCCESSOR_PIPELINE_WORK"
echo "HISTORICAL_LEGACY_LINEAGE_MUST_REMAIN_TRUTHFUL=YES"
echo "NEW_CANONICAL_DOWNSTREAM_LINEAGE_MUST_EVENTUALLY_BE_DATABASE_ENFORCEABLE=YES"

echo
echo "=== SCOPE DETERMINATION ==="
echo "VERIFIED_OUTCOME=DELEGATION_REANCHOR_RUNTIME_IS_ALREADY_COMPLETE_AND_VALIDATED"
echo "VERIFIED_OUTCOME=CURRENT_CANONICAL_PACKAGE_HAS_NO_DELEGATION_BECAUSE_EXPLICIT_OPERATOR_AUTHORITY_EVENT_IS_PENDING"
echo "VERIFIED_OUTCOME=DO_NOT_CONFUSE_PENDING_AUTHORITY_EVENT_WITH_INCOMPLETE_RUNTIME_IMPLEMENTATION"
echo "VERIFIED_OUTCOME=DO_NOT_REOPEN_PRODUCTION_DELEGATION_PACKAGE_ROOT_RECONCILIATION"
echo "DEFERRED_SUCCESSOR_CORRIDOR=VALIDATION_GATE_ENVELOPE_CANONICAL_LINEAGE_RECONCILIATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "NEXT_DECISION=DETERMINE_WHETHER_OPERATOR_NOW_WANTS_TO_EXPLICITLY_DELEGATE_THE_EXISTING_CANONICAL_PACKAGE_OR_LEAVE_IT_PENDING_DELEGATION"
