#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY UNIT A EXTERNAL INPUT COLLECTION BOUNDARY ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="bddb1445c"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED SOURCE-OF-TRUTH CLASSIFICATION ==="
echo "TEAM_DOMAIN_SOURCE=CLOUDFLARE_ZERO_TRUST_ACCOUNT_CONFIGURATION"
echo "APPLICATION_AUDIENCE_TAG_SOURCE=CLOUDFLARE_ACCESS_APPLICATION_CONFIGURATION"
echo "ALLOWED_OPERATOR_IDENTITY_SOURCE=EXPLICIT_USER_POLICY_DECISION_PLUS_VERIFIED_IDENTITY_VALUE"
echo "ACCESS_POLICY_SCOPE_SOURCE=EXPLICIT_USER_ARCHITECTURAL_DECISION"
echo "DIRECT_REMOTE_BYPASS_POLICY_SOURCE=DEPLOYMENT_NETWORK_CONFIGURATION"
echo "NON_PRODUCTION_VALIDATION_PATH_SOURCE=REPOSITORY_AND_DEPLOYMENT_VALIDATION_DESIGN"

echo
echo "=== INPUT COLLECTION OWNERSHIP ==="
echo "EXTERNAL_FACT_1_TEAM_DOMAIN=READ_ONLY_EXTERNAL_EVIDENCE_REQUIRED"
echo "EXTERNAL_FACT_2_APPLICATION_AUDIENCE_TAG=READ_ONLY_EXTERNAL_EVIDENCE_REQUIRED_WHEN_APPLICATION_EXISTS"
echo "USER_DECISION_1_ALLOWED_OPERATOR_IDENTITY=EXPLICIT"
echo "USER_DECISION_2_ACCESS_POLICY_SCOPE=EXPLICIT"
echo "ENGINEERING_EVIDENCE_1_ORIGIN_BYPASS_BOUNDARY=REQUIRED"
echo "ENGINEERING_DESIGN_1_SAFE_VALIDATION_TARGET=REQUIRED"

echo
echo "=== NO-FURTHER-REPOSITORY-INFERENCE DETERMINATION ==="
echo "ADDITIONAL_REPOSITORY_SEARCH_CAN_RESOLVE_TEAM_DOMAIN=NO"
echo "ADDITIONAL_REPOSITORY_SEARCH_CAN_RESOLVE_AUDIENCE_TAG=NO"
echo "ADDITIONAL_REPOSITORY_SEARCH_CAN_CHOOSE_OPERATOR_IDENTITY=NO"
echo "ADDITIONAL_REPOSITORY_SEARCH_CAN_CHOOSE_POLICY_SCOPE=NO"
echo "REPEATING_LOCAL_SEARCH_WOULD_ADD_CONFIDENCE=NO"
echo "STOP_REPEATING_REPOSITORY_DISCOVERY_FOR_EXTERNAL_VALUES=YES"

echo
echo "=== PRE-IMPLEMENTATION COLLECTION SEQUENCE ==="
echo "STEP_1=OBTAIN_TEAM_DOMAIN_FROM_AUTHORITATIVE_CLOUDFLARE_ACCOUNT_STATE"
echo "STEP_2=RECORD_EXPLICIT_ALLOWED_OPERATOR_IDENTITY_POLICY"
echo "STEP_3=RECORD_EXPLICIT_ACCESS_SCOPE_POLICY"
echo "STEP_4=CLASSIFY_ORIGIN_BYPASS_BOUNDARY"
echo "STEP_5=DESIGN_SAFE_NON_EXECUTION_VALIDATION_TARGET"
echo "STEP_6=ONLY_THEN_REVIEW_UNIT_A_IMPLEMENTATION_READINESS"
echo "APPLICATION_AUDIENCE_TAG_MAY_BE_CREATED_OR_READ_AS_PART_OF_ACCESS_APPLICATION_CONFIGURATION=YES"

echo
echo "=== USER DECISION OPTIONS — NOT SELECTED HERE ==="
echo "ALLOWED_OPERATOR_POLICY_OPTION_A=SINGLE_VERIFIED_OPERATOR_IDENTITY"
echo "ALLOWED_OPERATOR_POLICY_OPTION_B=BOUNDED_VERIFIED_IDENTITY_SET"
echo "POLICY_SCOPE_OPTION_A=WHOLE_CANONICAL_REMOTE_OPERATOR_HOST"
echo "POLICY_SCOPE_OPTION_B=BOUNDED_EXECUTION_APPROVAL_SURFACE"
echo "POLICY_SCOPE_SELECTION_MUST_NOT_BE_INFERRED=YES"

echo
echo "=== CURRENT BLOCKER ==="
echo "UNIT_A_CONFIGURATION_SOURCE_OF_TRUTH_CLASSIFIED=YES"
echo "UNIT_A_IMPLEMENTATION_READY=NO"
echo "BLOCKER_CLASS=EXTERNAL_FACTS_PLUS_USER_OWNED_POLICY_DECISIONS"
echo "THIS_IS_NOT_A_CODE_DEFECT=YES"
echo "THIS_IS_NOT_A_GIT_DEFECT=YES"
echo "THIS_IS_NOT_A_CLOUDFLARE_TUNNEL_FAILURE=YES"

echo
echo "=== CORRIDOR STATUS ==="
echo "UNIT_A_SOURCE_OF_TRUTH_CORRIDOR=CLOSED"
echo "UNIT_A_EXTERNAL_INPUT_COLLECTION_CORRIDOR=ACTIVE"
echo "NEXT_ACTION=COLLECT_AUTHORITATIVE_CLOUDFLARE_ACCOUNT_FACTS_AND_EXPLICIT_USER_POLICY_DECISIONS"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "AUTHENTICATION_IS_NOT_EXECUTION_APPROVAL=YES"
echo "AUTHENTICATION_IS_NOT_GIT_AUTHORITY=YES"
echo "CLIENT_SUPPLIED_ACTOR_REMAINS_UNTRUSTED=YES"
echo "MATILDA_SELF_APPROVAL=PROHIBITED"
echo "CADE_SELF_APPROVAL=PROHIBITED"
echo "GENERIC_MUTATION_AUTHORITY=DISABLED"
echo "GENERIC_SHELL_AUTHORITY=DISABLED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=DISABLED"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_DNS_CHANGE=YES"
echo "NO_TUNNEL_CHANGE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
