#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY CLOUDFLARE ACCESS AS INFRASTRUCTURE PREREQUISITE ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "AUTHORIZATION_COMPILATION_IMPLEMENTATION_AUTHORIZED=NO"
echo "ACTIVE_REPOSITORY_EXECUTION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="0ab6c1987"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED OBSERVED STATE ==="
echo "CLOUDFLARED_BINARY_PRESENT=YES"
echo "NAMED_TUNNELS_PRESENT=YES"
echo "TUNNELS_HAVE_ACTIVE_CONNECTIONS=NO_AT_INSPECTION_TIME"
echo "LOCAL_CLOUDFLARED_CREDENTIAL_FILES_PRESENT=YES"
echo "LOCAL_CLOUDFLARED_NAMED_CONFIG_FILES_PRESENT=YES"
echo "GENERIC_config.yml_OR_config.yaml_PRESENT=NO"
echo "PM2_CLOUDFLARE_PROCESS_METADATA_PRESENT=NO_AT_INSPECTION_TIME"
echo "CLOUDFLARE_ACCESS_POLICY_EVIDENCE=NONE_FOUND"
echo "CLOUDFLARE_ACCESS_IDENTITY_HEADER_CONSUMER=NONE_FOUND"
echo "SERVER_VERIFIED_PROXY_IDENTITY=NOT_ESTABLISHED"
echo "REQUEST_BODY_authorization_actor_REMAINS_UNTRUSTED=YES"

echo
echo "=== INFRASTRUCTURE CLASSIFICATION ==="
echo "CLOUDFLARE_TUNNEL_LAYER=TRANSPORT_ONLY"
echo "CLOUDFLARE_ACCESS_LAYER=NOT_ESTABLISHED"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_IS_SEPARATE_INFRASTRUCTURE_PREREQUISITE=YES"
echo "APPLICATION_AUTH_IMPLEMENTATION_REQUIRED_NOW=NO"
echo "PARALLEL_APPLICATION_ACCOUNT_SYSTEM_REQUIRED_NOW=NO"
echo "TRUSTED_OPERATOR_IDENTITY_PREREQUISITE_REMAINS_OPEN=YES"
echo "EXECUTION_AUTHORIZATION_COMPILATION_MUST_WAIT=YES"
echo "ACTIVE_REPOSITORY_ENABLEMENT_MUST_WAIT=YES"

echo
echo "=== SECURITY FINDING ==="
echo "TRACKED_CLOUDFLARE_API_CREDENTIAL_MATERIAL_DISCOVERED=YES"
echo "CREDENTIAL_ROTATION_IS_SEPARATE_SECURITY_REMEDIATION=YES"
echo "DO_NOT_REPRINT_CREDENTIAL=YES"
echo "DO_NOT_COUPLE_CREDENTIAL_ROTATION_TO_IDENTITY_CORRIDOR=YES"

echo
echo "=== REQUIRED FUTURE ACCESS TRUST CONTRACT ==="
echo "ACCESS_POLICY_MUST_AUTHENTICATE_OPERATOR_BEFORE_REQUEST_REACHES_EXECUTION_AUTHORIZATION_BOUNDARY=YES"
echo "SERVER_MUST_VALIDATE_TRUSTED_PROXY_ASSERTION=YES"
echo "SERVER_MUST_DERIVE_OPERATOR_IDENTITY_FROM_VALIDATED_ASSERTION=YES"
echo "CLIENT_SUPPLIED_OPERATOR_IDENTITY_MUST_NOT_GRANT_AUTHORITY=YES"
echo "DIRECT_NETWORK_BYPASS_OF_TRUST_BOUNDARY_MUST_FAIL_CLOSED=YES"
echo "IDENTITY_AUTHENTICATION_AND_EXECUTION_APPROVAL_REMAIN_DISTINCT=YES"
echo "USER_INTENT_AUTHORITY_REMAINS_WITH_USER=YES"
echo "MATILDA_MUST_NOT_SELF_AUTHORIZE=YES"
echo "CADE_MUST_NOT_SELF_AUTHORIZE=YES"

echo
echo "=== SMALLEST NEXT INFRASTRUCTURE QUESTION ==="
echo "QUESTION_1=WHICH_EXISTING_NAMED_TUNNEL_OR_HOSTNAME_IS_THE_CANONICAL_MOTHERBOARD_OPERATOR_ENTRYPOINT"
echo "QUESTION_2=WHETHER_CLOUDFLARE_ACCESS_CAN_BE_BOUND_ONLY_TO_THAT_ENTRYPOINT"
echo "QUESTION_3=WHAT_VERIFIED_IDENTITY_ASSERTION_CLOUDFLARE_ACCESS_WOULD_PRESENT_TO_THE_SERVER"
echo "QUESTION_4=HOW_DIRECT_LOCAL_ACCESS_IS_HANDLED_WITHOUT_CREATING_A_SECOND_OPERATOR_AUTHORITY_MODEL"
echo "QUESTION_5=WHETHER_EXECUTION_AUTHORIZATION_ENDPOINT_SHOULD_BE_REACHABLE_ONLY_BEHIND_THE_VERIFIED_OPERATOR_BOUNDARY"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_CANONICAL_OPERATOR_ENTRYPOINT_AND_SINGLE_IDENTITY_INTERFACE_BEFORE_ANY_CLOUDFLARE_ACCESS_CONFIGURATION_OR_SERVER_IDENTITY_IMPLEMENTATION"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "DURABLE_EXECUTION_AUTHORIZATION_IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "CANONICAL_PACKAGE_APPROVAL_UNCHANGED=YES"
echo "GOVERNANCE_ENVELOPE_UNCHANGED=YES"
echo "EXECUTION_AUTHORIZATION_RUNTIME_UNCHANGED=YES"
echo "EXECUTION_APPROVAL_GATE_UNCHANGED=YES"
echo "CADE_LOCAL_COMMIT_EFFECT_UNCHANGED=YES"
echo "CADE_REMOTE_PUSH_EFFECT_UNCHANGED=YES"
echo "GENERIC_CADE_ROUTE_UNCHANGED=YES"
echo "GENERIC_MUTATION_AUTHORITY_DISABLED=YES"
echo "GENERIC_SHELL_AUTHORITY_DISABLED=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_DISABLED=YES"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_CREDENTIAL_ROTATION=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
