#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY TRUSTED IDENTITY BOUNDARY AS PRODUCTION PREREQUISITE ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="6e47a6b78"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED EVIDENCE ==="
echo "SERVER_VERIFIED_USER_IDENTITY_SEARCH_RESULT=NONE_FOUND"
echo "AUTH_MIDDLEWARE_OR_SESSION_IDENTITY_SEARCH_RESULT=NONE_FOUND"
echo "EXECUTION_AUTHORIZATION_ROUTE_ACCEPTS_authorization_actor_FROM_REQUEST_BODY=YES"
echo "EXECUTION_AUTHORIZATION_RUNTIME_RETURNS_status_execution_authorized=YES"
echo "EXECUTION_AUTHORIZATION_RUNTIME_IS_DURABLE_PERSISTENCE=NO_EVIDENCE"
echo "PREVIEW_CONFIRMATION_PLAN_LINEAGE_EXISTS=YES"

echo
echo "=== TRUST DETERMINATION ==="
echo "TRUSTED_SERVER_VERIFIED_USER_IDENTITY_SOURCE=ABSENT_ON_INSPECTED_SURFACE"
echo "REQUEST_BODY_authorization_actor_IS_UNTRUSTED_INPUT=YES"
echo "REQUEST_BODY_authorization_actor_CAN_AUTHOR_EXECUTION=NO"
echo "CURRENT_EXECUTION_AUTHORIZATION_ROUTE_IS_PRODUCTION_TRUST_BOUNDARY_READY=NO"
echo "CURRENT_EXECUTION_AUTHORIZATION_RUNTIME_IS_SUFFICIENT_PRODUCTION_AUTHORITY=NO"

echo
echo "=== IMPORTANT CORRECTION ==="
echo "DURABLE_EXECUTION_AUTHORIZATION_RUNTIME_EXISTS=NOT_ESTABLISHED"
echo "CURRENT_RUNTIME_GENERATES_AUTHORIZATION_OBJECT=YES"
echo "CURRENT_RUNTIME_DATABASE_PERSISTENCE=NOT_OBSERVED"
echo "DO_NOT_DESCRIBE_IN_MEMORY_AUTHORIZATION_OBJECT_AS_DURABLE=YES"

echo
echo "=== ARCHITECTURAL CLASSIFICATION ==="
echo "IDENTITY_BOUNDARY_IS_SEPARATE_PREREQUISITE=YES"
echo "AUTHORIZATION_COMPILATION_UNIT_MUST_WAIT=YES"
echo "ACTIVE_REPOSITORY_ENABLEMENT_MUST_WAIT=YES"
echo "END_TO_END_GOVERNED_GIT_PRODUCTION_REACHABILITY_MUST_WAIT=YES"
echo "NO_PARALLEL_AUTH_SYSTEM=YES"
echo "NO_SYNTHETIC_IDENTITY=YES"
echo "NO_HARDCODED_OPERATOR_IDENTITY=YES"
echo "NO_CLIENT_ASSERTED_IDENTITY_AS_AUTHORITY=YES"

echo
echo "=== NEXT INVESTIGATION TARGET ==="
echo "TARGET=EXISTING_APPLICATION_DEPLOYMENT_AND_ACCESS_TRUST_MODEL"
echo "QUESTION_1=IS_APPLICATION_CURRENTLY_SINGLE_OPERATOR_WITH_EXTERNAL_ACCESS_CONTROL"
echo "QUESTION_2=IS_TRUSTED_IDENTITY_EXPECTED_FROM_PLATFORM_PROXY_OR_DEPLOYMENT_BOUNDARY"
echo "QUESTION_3=IS_AN_APPLICATION_AUTHENTICATION_LAYER_ALREADY_PLANNED_OR_PRESENT_OUTSIDE_INSPECTED_SERVER_SURFACES"
echo "QUESTION_4=WHAT_IS_SMALLEST_NON_PARALLEL_SERVER_VERIFIED_OPERATOR_IDENTITY_BOUNDARY"
echo "QUESTION_5=CAN_EXISTING_DEPLOYMENT_IDENTITY_BE_PROPAGATED_WITHOUT_CREATING_A_SECOND_AUTHORITY_MODEL"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "CANONICAL_PACKAGE_APPROVAL_UNCHANGED=YES"
echo "GOVERNANCE_ENVELOPE_UNCHANGED=YES"
echo "EXECUTION_APPROVAL_GATE_UNCHANGED=YES"
echo "CADE_COMMIT_EFFECT_UNCHANGED=YES"
echo "CADE_PUSH_EFFECT_UNCHANGED=YES"
echo "GENERIC_CADE_ROUTE_UNCHANGED=YES"
echo "GENERIC_MUTATION_AUTHORITY_DISABLED=YES"
echo "GENERIC_SHELL_AUTHORITY_DISABLED=YES"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_DISABLED=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=INVESTIGATE_EXISTING_DEPLOYMENT_AND_ACCESS_TRUST_MODEL_BEFORE_DESIGNING_IDENTITY_IMPLEMENTATION"
echo "IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "AUTHORIZATION_COMPILATION_IMPLEMENTATION_AUTHORIZED=NO"
echo "ACTIVE_REPOSITORY_EXECUTION_AUTHORIZED=NO"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_EFFECT=YES"
