#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY EXISTING CANONICAL PACKAGE PROJECTION RECONCILIATION ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PACKAGE_HANDOFF_CONTRACT"
echo "IMPLEMENTATION_COMMIT=2efe86d5"
echo "RUNTIME_CLASSIFICATION_COMMIT=5a160858"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED CURRENT STATE ==="
echo "PACKAGE_HANDOFF_CONTRACT_DESIGN=CLOSED"
echo "PACKAGE_HANDOFF_CONTRACT_RUNTIME_IMPLEMENTED=YES"
echo "PACKAGE_HANDOFF_CONTRACT_TARGETED_VALIDATION=PASS"
echo "POST_APPROVAL_PROJECTION_PATH=IMPLEMENTED"
echo "PROJECT_BOUND_HANDOFF_STARTED=NO"

echo
echo "=== LIVE CANONICAL PACKAGE WITHOUT PROJECTION ==="
sqlite3 -header -column db/main.db '
SELECT
  c.project_id,
  c.package_id,
  c.package_version,
  c.status,
  c.conversation_id,
  c.approved_expected_outcome,
  c.created_at,
  CASE
    WHEN g.package_id IS NULL THEN "MISSING"
    ELSE "PRESENT"
  END AS projection_state
FROM matilda_canonical_packages c
LEFT JOIN governance_packages g
  ON g.package_id = c.package_id
 AND g.package_version = c.package_version
WHERE c.status = "canonical_approved"
ORDER BY c.created_at DESC;
'

echo
echo "=== RECONCILIATION BOUNDARY ==="
echo "CURRENT_APPROVED_PACKAGE_PRE_DATES_PROJECTION_RUNTIME=YES"
echo "CURRENT_MISSING_PROJECTION_IS_HISTORICAL_STATE_GAP=YES"
echo "POST_APPROVAL_RUNTIME_DEFECT_ESTABLISHED=NO"
echo "NEW_SCHEMA_REQUIRED=NO"
echo "NEW_MIGRATION_REQUIRED=NO"
echo "MISSION_READ_CHANGE_REQUIRED=NO"
echo "MISSION_CONTROL_CHANGE_REQUIRED=NO"
echo "DELEGATION_CHANGE_REQUIRED=NO"
echo "HISTORICAL_PACKAGE_MUTATION_REQUIRED=NO"
echo "DERIVED_TARGET_MATERIALIZATION_REQUIRED_FOR_CURRENT_APPROVED_PACKAGE=YES"

echo
echo "=== AUTHORITY PRESERVATION ==="
echo "CANONICAL_PACKAGE_REMAINS_AUTHORITATIVE=YES"
echo "RECONCILIATION_MUST_USE_EXACT_project_id+package_id+package_version=YES"
echo "RECONCILIATION_MUST_REQUIRE_canonical_approved=YES"
echo "RECONCILIATION_MUST_USE_EXISTING_PROJECTION_ADAPTER=YES"
echo "RECONCILIATION_MUST_NOT_CREATE_NEW_CANONICAL_VERSION=YES"
echo "RECONCILIATION_MUST_NOT_SELECT_NEWEST_PACKAGE=YES"
echo "RECONCILIATION_MUST_NOT_CREATE_DELEGATION=YES"
echo "RECONCILIATION_MUST_NOT_CONFER_EXECUTION_AUTHORITY=YES"

echo
echo "=== SCOPE DETERMINATION ==="
echo "BACKFILL_CLASS=ONE_TIME_EXACT_EXISTING_CANONICAL_PACKAGE_RECONCILIATION"
echo "GENERAL_HISTORICAL_BACKFILL_AUTHORIZED=NO"
echo "ONE_TIME_LIVE_RECONCILIATION_AUTHORIZED=NO"
echo "PACKAGE_HANDOFF_CONTRACT_FULL_CLOSURE_BLOCKED_BY_LIVE_STATE=YES"
echo "BLOCKER=EXISTING_APPROVED_CANONICAL_PACKAGE_HAS_NO_DERIVED_MISSION_READ_PROJECTION"

echo
echo "=== NEXT GATE ==="
echo "NEXT_ACTION=PRESENT_BOUNDED_AUTHORIZATION_GATE_FOR_ONE_TIME_EXACT_LIVE_PACKAGE_PROJECTION_RECONCILIATION"
echo "AUTHORIZED_SCOPE_IF_GRANTED=PROJECT_EXISTING_APPROVED_PACKAGE_USING_EXISTING_PROJECTION_ADAPTER_ONLY"
echo "PROJECT_BOUND_HANDOFF_STARTED=NO"
