#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="668485416"

git fetch origin "$BRANCH"
test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$EXPECTED_HEAD"

printf '\n====================================================\n'
printf ' EXPLICIT OPERATOR ENVELOPE ACTION — TARGET CLASSIFICATION\n'
printf '====================================================\n\n'

GATE_API="client/src/approvals/governanceEnvelopeGateApi.ts"
GATE_TEST="client/src/approvals/governanceEnvelopeGateApi.test.ts"
WORKSPACE="client/src/approvals/ApprovalsWorkspace.tsx"
ENVELOPE_ROUTE="server/routes/governance-envelope-route.ts"
ENVELOPE_CONSUMER="server/envelope/production-envelope-consumer.ts"

for target in \
  "$GATE_API" \
  "$GATE_TEST" \
  "$WORKSPACE" \
  "$ENVELOPE_ROUTE" \
  "$ENVELOPE_CONSUMER"
do
  test -f "$target"
done

printf '\n=== VERIFIED CLIENT SEAM ===\n'
grep -Fq '): Promise<unknown>' "$GATE_API"
grep -Fq 'return payload;' "$GATE_API"
grep -Fq 'await postGovernanceEnvelopeGate({' "$WORKSPACE"
grep -Fq 'gate_id: crypto.randomUUID(),' "$WORKSPACE"
grep -Fq 'setEnvelopeGateComplete(true);' "$WORKSPACE"

echo "GATE_API_RETURNS_UNTYPED_PAYLOAD=YES"
echo "WORKSPACE_GENERATES_GATE_ID=YES"
echo "WORKSPACE_DISCARDS_GATE_SUCCESS_PAYLOAD=YES"
echo "EXACT_SUCCESSFUL_GATE_ID_CURRENTLY_RETAINED=NO"
echo "EXISTING_ENVELOPE_CLIENT_API=NO"

printf '\n=== VERIFIED SERVER SEAM ===\n'
grep -Fq 'consumeProductionEnvelopeEntryPoint(' "$ENVELOPE_ROUTE"
grep -Fq 'resolveGovernanceEnvelopeSemantics' "$ENVELOPE_CONSUMER"

echo "GOVERNANCE_ENVELOPE_ROUTE_EXISTS=YES"
echo "PRODUCTION_ENVELOPE_CONSUMER_EXISTS=YES"
echo "AUTHORITATIVE_SEMANTIC_RESOLUTION_ALREADY_SERVER_OWNED=YES"
echo "SERVER_ROUTE_CHANGE_REQUIRED=NO"
echo "PRODUCTION_CONSUMER_CHANGE_REQUIRED=NO"
echo "DATABASE_CHANGE_REQUIRED=NO"
echo "SCHEMA_CHANGE_REQUIRED=NO"

printf '\n=== EXACT IMPLEMENTATION TARGETS ===\n'
echo "TARGET_1=client/src/approvals/governanceEnvelopeGateApi.ts"
echo "TARGET_1_PURPOSE=RETURN_TYPED_SUCCESS_PAYLOAD_AND_EXACT_PERSISTED_GATE_ID"
echo "TARGET_2=client/src/approvals/governanceEnvelopeGateApi.test.ts"
echo "TARGET_2_PURPOSE=VERIFY_EXACT_SUCCESSFUL_GATE_ID_RETENTION"
echo "TARGET_3=client/src/approvals/governanceEnvelopeApi.ts"
echo "TARGET_3_PURPOSE=ADD_NARROW_EXISTING_ENVELOPE_ROUTE_CLIENT"
echo "TARGET_4=client/src/approvals/governanceEnvelopeApi.test.ts"
echo "TARGET_4_PURPOSE=VERIFY_EXACT_LINEAGE_POST_AND_FAILURE_SURFACING"
echo "TARGET_5=client/src/approvals/ApprovalsWorkspace.tsx"
echo "TARGET_5_PURPOSE=RETAIN_EXACT_GATE_ID_AND_ADD_SEPARATE_EXPLICIT_CREATE_ENVELOPE_ACTION"

printf '\n=== REQUIRED OPERATOR FLOW ===\n'
echo "VALIDATION_ACTION_REMAINS_SEPARATE=YES"
echo "ENVELOPE_GATE_ACTION_REMAINS_SEPARATE=YES"
echo "ENVELOPE_CREATION_ACTION_REMAINS_SEPARATE=YES"
echo "CREATE_ENVELOPE_AVAILABLE_BEFORE_GATE_SUCCESS=NO"
echo "CREATE_ENVELOPE_REQUIRES_EXPLICIT_OPERATOR_CLICK=YES"
echo "EXACT_VALIDATION_RESULT_ID_REUSED=YES"
echo "EXACT_SUCCESSFUL_ENVELOPE_GATE_ID_REUSED=YES"
echo "EXACT_PACKAGE_ID_REUSED=YES"
echo "EXACT_PACKAGE_VERSION_REUSED=YES"
echo "EXACT_DELEGATION_ID_REUSED=YES"

printf '\n=== SEMANTIC AUTHORITY ===\n'
echo "CALLER_REQUIRED_CAPABILITIES_AUTHORITATIVE=NO"
echo "CALLER_OPERATIONAL_CORRIDOR_AUTHORITATIVE=NO"
echo "SERVER_CONSUMER_AUTHORITATIVE_SEMANTIC_RESOLUTION=YES"
echo "LATEST_VALIDATION_LOOKUP=PROHIBITED"
echo "LATEST_GATE_LOOKUP=PROHIBITED"

printf '\n=== AUTHORITY BOUNDARY ===\n'
echo "AUTOMATIC_GATE_TO_ENVELOPE_TRANSITION=NO"
echo "AUTOMATIC_ENVELOPE_CREATION=NO"
echo "LIFECYCLE_TRANSITION_AUTHORITY=NO"
echo "ROUTING_AUTHORITY=NO"
echo "ASSIGNMENT_AUTHORITY=NO"
echo "SCHEDULING_AUTHORITY=NO"
echo "WORKER_CLAIM_AUTHORITY=NO"
echo "ORCHESTRATION_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "DOWNSTREAM_EXECUTION_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"
echo "NO_GENERIC_SHELL=YES"
echo "NO_SELF_AUTHORIZATION=YES"

printf '\n=== FAILURE CONTAINMENT ===\n'
echo "IMPLEMENTATION_FAILED_ATTEMPTS=1"
echo "THIS_ACTION=CLASSIFICATION_ONLY"
echo "THIS_ACTION_COUNTS_AS_IMPLEMENTATION_ATTEMPT=NO"
echo "THREE_FAILURE_REVERT_THRESHOLD_REACHED=NO"
echo "SPECULATIVE_PATCH_LAYERING=PROHIBITED"

printf '\n=== READINESS ===\n'
echo "EXACT_EDIT_TARGETS_CLASSIFIED=YES"
echo "IMPLEMENTATION_AUTHORIZATION_ALREADY_PRESENT=YES"
echo "NEXT_ACTION=IMPLEMENT_CLIENT_EXPLICIT_OPERATOR_ENVELOPE_ACTION"
echo "IMPLEMENTATION_ATTEMPT_NUMBER=2"
echo "AUTOMATIC_ADVANCE=NO"

printf '\nEXPLICIT_OPERATOR_ENVELOPE_ACTION_TARGET_CLASSIFICATION=COMPLETE\n'
