#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY PACKAGE SEMANTICS UNKNOWN-FIELD VALIDATOR GAP ==="
echo "EXPECTED_HEAD_PREFIX=ae11e597f"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != ae11e597f* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED CONTRACT ==="
echo "PACKAGE_SEMANTICS_FIELD_COUNT=7"
echo "SCHEMA_additionalProperties_false=YES"
echo "SCHEMA_UNKNOWN_FIELDS_ALLOWED=NO"

echo
echo "=== VERIFIED RUNTIME VALIDATOR ==="
echo "SHARED_VALIDATOR=validateMatildaPackageSemanticsArtifact"
echo "REQUIRED_FIELD_TYPE_AND_EMPTY_VALIDATION=YES"
echo "UNKNOWN_KEY_REJECTION_VISIBLE=NO"
echo "RUNTIME_SCHEMA_PARITY_FOR_additionalProperties_false=NO"

echo
echo "=== IEL BOUNDARY ==="
echo "IEL_WRITE_REUSES_SHARED_VALIDATOR=YES"
echo "IEL_RECONSTRUCTION_REUSES_SHARED_VALIDATOR=YES"
echo "THEREFORE_UNKNOWN_FIELD_GAP_PROPAGATES_TO_IEL_WRITE_AND_RECONSTRUCTION=YES"
echo "SEPARATE_IEL_FIX_REQUIRED=NO"

echo
echo "=== TEST COVERAGE ==="
echo "PACKAGE_SEMANTICS_UNKNOWN_FIELD_FAIL_CLOSED_TEST=ABSENT"
echo "TYPED_USER_PACKAGE_SEMANTICS_UNKNOWN_FIELD_TEST=EXISTS_BUT_IS_SEPARATE_CONTRACT"
echo "CURRENT_PACKAGE_SEMANTICS_TESTS_DO_NOT_ESTABLISH_UNKNOWN_FIELD_REJECTION=YES"

echo
echo "=== DEFECT CLASSIFICATION ==="
echo "PACKAGE_SEMANTICS_UNKNOWN_FIELD_VALIDATOR_GAP=CONFIRMED"
echo "DEFECT=RUNTIME_SHARED_VALIDATOR_DOES_NOT_ENFORCE_BOUNDED_SEVEN_FIELD_KEY_SET"
echo "SCHEMA_RUNTIME_PARITY_DEFECT=YES"
echo "FAIL_CLOSED_CONTRACT_INCOMPLETE=YES"
echo "PACKAGE_SEMANTICS_CORRIDOR_CLOSED=NO"

echo
echo "=== NARROW REPAIR BOUNDARY ==="
echo "PRIMARY_SURFACE=scripts/utils/ollamaChat.ts_SHARED_PACKAGE_SEMANTICS_VALIDATOR"
echo "TEST_SURFACE=scripts/utils/ollamaChat.package-semantics-contract.test.ts"
echo "REPAIR=REJECT_ANY_KEY_OUTSIDE_THE_EXISTING_SEVEN_FIELD_SET"
echo "IEL_CHANGE=NO"
echo "WORKFLOW_CHANGE=NO"
echo "PROMPT_CHANGE=NO"
echo "LIVING_DRAFT_CHANGE=NO"
echo "APPROVAL_UI_CHANGE=NO"
echo "AUTHORITY_MODEL_CHANGE=NO"
echo "GENERATION_POLICY_CHANGE=NO"
echo "HISTORICAL_BACKFILL=NO"

echo
echo "=== REQUIRED REPAIR VALIDATION ==="
echo "VALID_SEVEN_FIELD_ARTIFACT_PASSES=REQUIRED"
echo "UNKNOWN_EIGHTH_FIELD_FAILS_CLOSED=REQUIRED"
echo "IEL_WRITE_INHERITS_UNKNOWN_FIELD_REJECTION=REQUIRED"
echo "IEL_RECONSTRUCTION_INHERITS_UNKNOWN_FIELD_REJECTION=REQUIRED"
echo "PACKAGE_SEMANTICS_REGRESSION=REQUIRED"
echo "OPTION_B_FIDELITY_REGRESSION=REQUIRED"
echo "LIFECYCLE_REGRESSION=REQUIRED"
echo "TYPECHECK_BUILD_DIFF_CHECK=REQUIRED"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=DESIGN_EXACT_SHARED_VALIDATOR_UNKNOWN_KEY_REJECTION_BEFORE_IMPLEMENTATION_AUTHORIZATION"
echo "SOURCE_EDIT=NONE"

git diff --check

git add classify-package-semantics-unknown-field-validator-gap.sh
git commit -m "Confirm package semantics unknown-field validator gap"
git push
