#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY REMAINING AUTHORITATIVE MISSION PACKAGE HANDOFF CORRIDORS ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "PROJECT_SCOPED_DELEGATION_CORRIDOR=CLOSED"
echo "KNOWN_DOWNSTREAM_LEGACY_ROOT_DEFECT=SEPARATELY_DEFERRED"
echo
echo "REMAINING_CORRIDOR_1=PACKAGE_HANDOFF_CONTRACT"
echo "REMAINING_CORRIDOR_2=PROJECT_BOUND_HANDOFF"
echo "REMAINING_CORRIDOR_3=MISSION_CONTROL_INTAKE"
echo "REMAINING_CORRIDOR_4=HANDOFF_VALIDATION_AND_PHASE_CLOSURE"
echo
echo "NEXT_ACTIVE_CORRIDOR=PACKAGE_HANDOFF_CONTRACT"
echo "SELECTION_BASIS=EARLIEST_REMAINING_UNCLOSED_PHASE_CORRIDOR"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "NEXT_ACTION=INVESTIGATE_PACKAGE_HANDOFF_CONTRACT_BOUNDARY"
