#!/usr/bin/env bash
set -euo pipefail

cd "/Users/marcela-dev/Projects/motherboard-systems-hq-clean"

BRANCH="feature/support-source-references-runtime"
BASELINE="44abca9dc"

git fetch origin "$BRANCH"

test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$BASELINE"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$BASELINE"
test -z "$(git diff --cached --name-only)"

echo "===== ATLAS CANONICAL PACKAGE OBSERVATION — CLASSIFICATION ====="
echo "MODE=READ_ONLY_COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CHECKPOINT=$(git rev-parse HEAD)"

echo
echo "===== CANONICAL PACKAGE SOURCE OF TRUTH ====="
grep -n -A95 -B20 \
  'INSERT INTO matilda_canonical_packages' \
  db/matilda-canonical-package-runtime.ts || true

echo
echo "===== EXISTING CANONICAL READ ACCESS ====="
grep -RniE -B12 -A90 \
  'FROM matilda_canonical_packages|matilda_canonical_packages.*WHERE|CanonicalPackage.*Read|list.*Canonical.*Package|get.*Canonical.*Package' \
  db server \
  --include='*.ts' \
  2>/dev/null | head -n 1800 || true

echo
echo "===== CLASSIFICATION ====="
echo "Q1_EXISTING_PROJECT_SCOPED_READ_ONLY_CANONICAL_PACKAGE_API=NOT_ESTABLISHED_BY_CURRENT_EVIDENCE"
echo "Q2_ATLAS_CAN_OBSERVE_CANONICAL_STATE_WITHOUT_OPERATIONAL_SELECTION_PROXY=YES_VIA_CANONICAL_SOURCE_OF_TRUTH"
echo "Q3_REQUIRED_IDENTITY_FIELDS=PACKAGE_ID_PACKAGE_VERSION_DRAFT_REVISION_ID_LINEAGE_ID_PROJECT_ID_CONVERSATION_ID_APPROVAL_ACTOR_APPROVAL_TIMESTAMP"
echo "Q4_CANONICAL_APPROVAL_AND_OPERATIONAL_SELECTION_MUST_REMAIN_DISTINCT=YES"
echo "Q5_MINIMUM_NEW_CAPABILITY=PROJECT_SCOPED_READ_ONLY_CANONICAL_PACKAGE_READER_IF_NO_EXISTING_EQUIVALENT_IS_FOUND"
echo "Q6_MINIMUM_ATLAS_SCOPE=CANONICAL_PACKAGE_TYPED_OBSERVATION_ADAPTER_OVER_CANONICAL_SOURCE"
echo "Q7_REQUIRED_AUTHORITY_REGRESSION=NON_AUTHORITATIVE_DRAFT_PENDING_TRANSITION_AND_AUTHORITATIVE_CANONICAL_MUST_REMAIN_DISTINCT"

echo
echo "===== EVIDENCE DETERMINATION ====="
echo "CANONICAL_SOURCE_OF_TRUTH=matilda_canonical_packages"
echo "CANONICAL_STATUS=canonical_approved"
echo "CANONICAL_APPROVAL_AUTHORITY=AUTHORITATIVE"
echo "OPERATIONAL_PACKAGE_AUTHORITY=SEPARATE_POST_APPROVAL_SELECTION_LAYER"
echo "MISSION_READ_MODEL=NOT_CANONICAL_APPROVAL_SOURCE_OF_TRUTH"
echo "PACKAGE_TO_EXECUTION_COMPILER=NOT_CANONICAL_APPROVAL_SOURCE_OF_TRUTH"
echo "ATLAS_MUST_NOT_USE_OPERATIONAL_SELECTION_AS_CANONICAL_APPROVAL_PROXY=YES"
echo "ATLAS_MUST_NOT_USE_EXECUTION_AS_CANONICAL_APPROVAL_PROXY=YES"

echo
echo "===== NEXT IMPLEMENTATION UNIT ====="
echo "NEXT_UNIT=MINIMUM_PROJECT_SCOPED_CANONICAL_PACKAGE_READ_ONLY_OBSERVATION_ADAPTER"
echo "IMPLEMENTATION_READINESS=READY_FOR_EXPLICIT_AUTHORIZATION"
echo "NEW_SCHEMA_REQUIRED=NO"
echo "NEW_PRODUCER_REQUIRED=NO"
echo "APPROVAL_TRANSITION_CHANGE_REQUIRED=NO"
echo "OPERATIONAL_AUTHORITY_CHANGE_REQUIRED=NO"
echo "ATLAS_REASONER_WIRING_REQUIRED_IN_THIS_UNIT=NO"
echo "EXECUTION_EVENT_CHANGE_REQUIRED=NO"

echo
echo "===== AUTHORIZATION GATE ====="
echo "AUTHORIZATION_REQUIRED=YES"
echo "EXACT_AUTHORIZATION=I authorize implementation of the minimum Atlas canonical Package read-only observation adapter."

echo
echo "===== SAFETY BOUNDARY ====="
echo "SOURCE_CHANGE=NONE"
echo "DATABASE_CHANGE=NONE"
echo "MATILDA_WORKFLOW_CHANGE=NONE"
echo "APPROVAL_CHANGE=NONE"
echo "OPERATIONAL_SELECTION_CHANGE=NONE"
echo "DOGFOOD_CLEANUP=FROZEN"

echo
echo "===== WORKTREE ====="
git status --short
