#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY MISSION CONTROL INTAKE SCOPE ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "PREVIOUS_CORRIDOR=PROJECT_BOUND_HANDOFF"
echo "PREVIOUS_CORRIDOR_CLOSURE_COMMIT=5d62f34f"
echo "ACTIVE_CORRIDOR=MISSION_CONTROL_INTAKE"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== ESTABLISHED UPSTREAM CONTRACT ==="
echo "PROJECT_BOUND_HANDOFF_CORRIDOR=CLOSED"
echo "OPERATIONAL_PACKAGE_AUTHORITY=ESTABLISHED"
echo "OPERATIONAL_IDENTITY=project_id+package_id+package_version"
echo "PROJECT_SCOPED_SERVER_READ_HANDOFF=ESTABLISHED"
echo "MISSION_READ_SELECTS_PACKAGE=NO"
echo "MISSION_CONTROL_SELECTS_PACKAGE=NO"

echo
echo "=== CURRENT MISSION CONTROL CLIENT STATE ==="
rg -n -C 18 \
  'ACTIVE_PACKAGE_ID|getMissionReadModel\(|loadMission\(|lastPackageId|MissionReadNotFoundError' \
  client/src/shell/MissionDashboardWorkspace.tsx \
  client/src/mission-control/MissionControlProvider.tsx \
  client/src/mission-control/missionReadApi.ts \
  2>/dev/null || true

echo
echo "=== CURRENT SERVER MISSION READ ROUTE ==="
sed -n '1,180p' routes/api-mission-read.ts

echo
echo "=== ACTIVE PROJECT CLIENT SURFACE ==="
rg -n -C 12 \
  'activeProject|activeProjectId|projectId|project_id|ProjectContext|useProject' \
  client/src \
  2>/dev/null || true

echo
echo "=== MISSION CONTROL INTAKE QUESTIONS ==="
echo "QUESTION_1=WHAT_EXISTING_CLIENT_SOURCE_OWNS_ACTIVE_PROJECT_IDENTITY"
echo "QUESTION_2=CAN_MISSION_CONTROL_CONSUME_ACTIVE_PROJECT_ID_WITHOUT_GAINING_PROJECT_SELECTION_AUTHORITY"
echo "QUESTION_3=WHAT_MINIMUM_CLIENT_API_CHANGE_REPLACES_PACKAGE_ID_WITH_PROJECT_ID"
echo "QUESTION_4=WHAT_MINIMUM_PROVIDER_STATE_CHANGE_REPLACES_LAST_PACKAGE_ID_WITH_LAST_PROJECT_ID"
echo "QUESTION_5=CAN_HARDCODED_corridor-smoke_BE_REMOVED_WITHOUT_ADDING_ANY_PACKAGE_SELECTION_LOGIC"
echo "QUESTION_6=WHAT_FAIL_CLOSED_UI_STATE_REPRESENTS_NO_OPERATIONAL_MISSION_FOR_ACTIVE_PROJECT"

echo
echo "=== INTAKE AUTHORITY BOUNDARY ==="
echo "MISSION_CONTROL_ROLE=READ_ONLY_CONSUMER"
echo "MISSION_CONTROL_MAY_CONSUME_ACTIVE_PROJECT_ID=YES"
echo "MISSION_CONTROL_MAY_SELECT_ACTIVE_PROJECT=NO"
echo "MISSION_CONTROL_MAY_SELECT_PACKAGE=NO"
echo "MISSION_CONTROL_MAY_REPLACE_OPERATIONAL_PACKAGE_AUTHORITY=NO"
echo "MISSION_CONTROL_MAY_USE_BROWSER_PACKAGE_STATE_AS_AUTHORITY=NO"
echo "MISSION_CONTROL_MAY_USE_DELEGATION_AS_PACKAGE_SELECTION_AUTHORITY=NO"
echo "MISSION_CONTROL_MAY_CREATE_DELEGATION=NO"
echo "MISSION_CONTROL_MAY_ROUTE=NO"
echo "MISSION_CONTROL_MAY_ASSIGN=NO"
echo "MISSION_CONTROL_MAY_EXECUTE=NO"

echo
echo "=== EXPECTED MINIMUM INTAKE FLOW ==="
echo "FLOW_1=READ_EXISTING_ACTIVE_PROJECT_IDENTITY"
echo "FLOW_2=REQUEST_MISSION_READ_BY_project_id"
echo "FLOW_3=SERVER_RESOLVES_OPERATIONAL_PACKAGE_AUTHORITY"
echo "FLOW_4=SERVER_RETURNS_EXACT_OPERATIONAL_MISSION_READ_MODEL"
echo "FLOW_5=MISSION_CONTROL_PRESENTS_RETURNED_READ_MODEL"
echo "CLIENT_PACKAGE_SELECTION_STEP=NONE"

echo
echo "=== LIKELY IMPLEMENTATION SURFACES TO CLASSIFY ==="
echo "SURFACE_A=client/src/mission-control/missionReadApi.ts"
echo "SURFACE_B=client/src/mission-control/MissionControlProvider.tsx"
echo "SURFACE_C=client/src/shell/MissionDashboardWorkspace.tsx"
echo "ACTIVE_PROJECT_SOURCE=REQUIRES_REPOSITORY_EVIDENCE"
echo "SERVER_ROUTE_CHANGE=NOT_EXPECTED_UNLESS_EVIDENCE_REVEALS_CONTRACT_DEFECT"
echo "SCHEMA_CHANGE=NO"
echo "MIGRATION_CHANGE=NO"

echo
echo "=== FAILURE CONTRACT ==="
echo "NO_ACTIVE_PROJECT=NO_MISSION_INTAKE"
echo "NO_OPERATIONAL_PACKAGE_AUTHORITY=NO_ACTIVE_MISSION"
echo "MISSION_READ_404=NO_ACTIVE_MISSION"
echo "MISSION_READ_IDENTITY_CONFLICT=ERROR_FAIL_CLOSED"
echo "PACKAGE_ID_FALLBACK=NOT_ALLOWED"
echo "HARDCODED_PACKAGE_FALLBACK=NOT_ALLOWED"
echo "NEWEST_PACKAGE_FALLBACK=NOT_ALLOWED"

echo
echo "=== CURRENT SCOPE DETERMINATION ==="
echo "MISSION_CONTROL_INTAKE_CORRIDOR=ACTIVE"
echo "MISSION_CONTROL_INTAKE_IMPLEMENTATION=NOT_STARTED"
echo "CLIENT_MUST_TRANSITION_FROM_PACKAGE_ID_INPUT_TO_PROJECT_ID_INPUT=YES"
echo "MISSION_CONTROL_PACKAGE_AUTHORITY=NONE"
echo "ACTIVE_PROJECT_AUTHORITY_SOURCE=TO_BE_CLASSIFIED_FROM_REPOSITORY_EVIDENCE"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_EXISTING_ACTIVE_PROJECT_CLIENT_SOURCE_AND_EXACT_MINIMUM_MISSION_CONTROL_INTAKE_IMPLEMENTATION_UNIT"
