#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY MOTHERBOARD SYSTEMS HQ GITHUB WRITE CAPABILITY ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "WRITE_TEST=NO"
echo "EXPECTED_HEAD_PREFIX=84a68a6d8"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 84a68a6d8* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== EVIDENCE-BASED CLASSIFICATION ==="
echo "HOST_GIT_CAPABILITY=ESTABLISHED"
echo "CADE_RUNTIME_FILE_MUTATION_PRIMITIVES=ESTABLISHED"
echo "CADE_RUNTIME_REACHABILITY=ESTABLISHED"
echo "RUNTIME_GIT_COMMIT_PRIMITIVE=NOT_ESTABLISHED"
echo "RUNTIME_GIT_PUSH_PRIMITIVE=NOT_ESTABLISHED"
echo "COMMIT_TS_EXISTS=YES"
echo "COMMIT_TS_RUNTIME_REACHABILITY=NOT_ESTABLISHED"
echo "GOVERNED_MUTATION_AUTHORITY=CURRENTLY_DISABLED"
echo "GOVERNED_SHELL_EXECUTION_AUTHORITY=CURRENTLY_DISABLED"
echo "GOVERNED_AUTONOMOUS_EXECUTION_AUTHORITY=CURRENTLY_DISABLED"

echo
echo "=== CAPABILITY LEVELS ==="
echo "LEVEL_A_HOST_REPOSITORY_CAN_USE_GIT=YES"
echo "LEVEL_B_MOTHERBOARD_RUNTIME_CAN_INVOKE_GIT_OR_GITHUB_WRITE_PRIMITIVE=NO_EVIDENCE"
echo "LEVEL_C_MOTHERBOARD_HAS_GOVERNED_AUTHORITY_PATH_TO_COMMIT=NO"
echo "LEVEL_D_MOTHERBOARD_HAS_GOVERNED_AUTHORITY_PATH_TO_PUSH_TO_GITHUB=NO"

echo
echo "=== IMPORTANT DISTINCTION ==="
echo "CADE_CAN_CREATE_UPDATE_DELETE_FILES=YES"
echo "CADE_CAN_COMMIT_THOSE_CHANGES_THROUGH_CURRENT_GOVERNED_RUNTIME=NO_EVIDENCE"
echo "CADE_CAN_PUSH_THOSE_CHANGES_TO_GITHUB_THROUGH_CURRENT_GOVERNED_RUNTIME=NO_EVIDENCE"
echo "OPERATOR_COMMIT_AND_PUSH_SCRIPTS_DO_NOT_CONSTITUTE_RUNTIME_CAPABILITY=YES"

echo
echo "=== FINAL DETERMINATION ==="
echo "MOTHERBOARD_ALREADY_CAPABLE_OF_EDITING_FILES=YES"
echo "MOTHERBOARD_ALREADY_CAPABLE_OF_GOVERNED_GIT_COMMIT=NO"
echo "MOTHERBOARD_ALREADY_CAPABLE_OF_GOVERNED_GITHUB_PUSH=NO"
echo "MISSING_BOUNDARY=RUNTIME_REACHABLE_GOVERNED_REPOSITORY_VERSION_CONTROL_EXECUTION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "NO_WRITE_TEST_PERFORMED=YES"
