#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY FINAL PACKAGE SEMANTICS OWNERSHIP BOUNDARY ==="
echo "BASELINE_COMMIT=8ae5c306"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "RECOVERY_POINT=DR_20260826_092915"

echo
echo "=== VERIFIED CURRENT UNRESOLVED QUESTIONS STATE ==="
echo "IEL_SCHEMA_HAS_unresolved_questions=YES"
echo "IEL_CREATE_INPUT_ACCEPTS_unresolved_questions=YES"
echo "CURRENT_CHAT_WORKFLOW_WRITES_unresolved_questions=NULL"
echo "CURRENT_OLLAMA_RESPONSE_HAS_INDEPENDENT_unresolvedQuestions_FIELD=NO"
echo "CURRENT_DRAFT_SYNTHESIS_READS_IEL_unresolved_questions=YES"
echo "CURRENT_ACTIVE_MATILDA_AUTHORED_UNRESOLVED_QUESTIONS_SOURCE=NONE"

echo
echo "=== OWNERSHIP DETERMINATION ==="
echo "PACKAGE_SEMANTICS_unresolvedQuestions_SINGLE_STRUCTURED_OWNER=YES"
echo "DUPLICATE_ACTIVE_SEMANTIC_OWNERSHIP_CREATED=NO"
echo "LEGACY_IEL_unresolved_questions_COLUMN_REMOVAL_REQUIRED=NO"
echo "LEGACY_IEL_DATA_BACKFILL_REQUIRED=NO"
echo "LEGACY_IEL_DATA_REINTERPRETATION_ALLOWED=NO"
echo "NEW_PACKAGE_SEMANTICS_SHOULD_NOT_BE_FIELD_MERGED_WITH_IEL_unresolved_questions=YES"

echo
echo "=== FINAL PACKAGE SEMANTICS ARTIFACT ==="
echo "FIELD=expectedOutcome"
echo "FIELD=proposedWork"
echo "FIELD=proposedArtifacts"
echo "FIELD=inScope"
echo "FIELD=outOfScope"
echo "FIELD=constraints"
echo "FIELD=unresolvedQuestions"
echo "AUTHOR=MATILDA"
echo "AUTHORITY=INTERPRETIVE_NON_AUTHORITATIVE"
echo "ATOMIC_ARTIFACT=YES"
echo "FIELD_BY_FIELD_CROSS_TURN_MERGE=NO"

echo
echo "=== SELECTION RULE ==="
echo "SOURCE=EXACT_LIVING_DRAFT_EVIDENCE_SET"
echo "SELECT=NEWEST_ELIGIBLE_NON_NULL_PACKAGE_SEMANTICS_ARTIFACT"
echo "CROSS_PROJECT_SELECTION=PROHIBITED"
echo "CROSS_CONVERSATION_SELECTION=PROHIBITED"
echo "OLDER_ARTIFACT_NULL_FIELD_BACKFILL=PROHIBITED"
echo "GENERIC_OR_HEURISTIC_SYNTHESIS=PROHIBITED_WHEN_VALID_PACKAGE_SEMANTICS_EXISTS"

echo
echo "=== LEGACY COMPATIBILITY BOUNDARY ==="
echo "IEL_unresolved_questions_COLUMN=PRESERVE"
echo "CURRENT_WORKFLOW_WRITE_BEHAVIOR=REMAIN_NULL_UNLESS_SEPARATELY_AUTHORIZED"
echo "HISTORICAL_ROWS=PRESERVE_AS_IS"
echo "PACKAGE_SEMANTICS_MUST_NOT_OVERWRITE_LEGACY_IEL_COLUMN=YES"
echo "LIVING_DRAFT_PACKAGE_SEMANTICS_SOURCE=NEW_TYPED_ARTIFACT_WHEN_PRESENT"
echo "LEGACY_IEL_unresolved_questions_NOT_A_PACKAGE_SEMANTICS_FALLBACK=YES"

echo
echo "=== FINAL BOUNDED IMPLEMENTATION UNIT ==="
echo "CHANGE_1=ADD_OPTIONAL_TYPED_packageSemantics_TO_EXISTING_OLLAMA_STRUCTURED_RESPONSE"
echo "CHANGE_2=ADD_FAIL_CLOSED_PACKAGE_SEMANTICS_VALIDATOR"
echo "CHANGE_3=TRANSPORT_VALIDATED_packageSemantics_THROUGH_EXISTING_SINGLE_WORKFLOW"
echo "CHANGE_4=PERSIST_PACKAGE_SEMANTICS_AS_TYPED_JSON_ON_IEL_ENTRY"
echo "CHANGE_5=RECONSTRUCT_PACKAGE_SEMANTICS_FAIL_CLOSED_ON_IEL_READ"
echo "CHANGE_6=SELECT_NEWEST_ELIGIBLE_NON_NULL_ARTIFACT_FROM_EXACT_DRAFT_EVIDENCE_SET"
echo "CHANGE_7=SYNTHESIZE_STRUCTURED_LIVING_DRAFT_FIELDS_FROM_SELECTED_ATOMIC_ARTIFACT"
echo "CHANGE_8=PRESERVE_current_interpretation_FROM_EXISTING_matilda_observation_SYNTHESIS"
echo "CHANGE_9=PRESERVE_LEGACY_IEL_unresolved_questions_WITHOUT_REINTERPRETATION"

echo
echo "=== ARCHITECTURAL INVARIANTS ==="
echo "ONE_USER_MESSAGE_ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=REQUIRED"
echo "REPLY_AND_DURABLE_INTERPRETATION_REMAIN_DISTINCT=REQUIRED"
echo "LIVING_DRAFT_REMAINS_NON_AUTHORITATIVE=REQUIRED"
echo "USER_APPROVAL_REMAINS_AUTHORITY_TRANSITION=REQUIRED"
echo "CANONICAL_PACKAGE_PIPELINE=UNCHANGED"
echo "FAIL_CLOSED_VALIDATION=REQUIRED"
echo "NO_SECOND_OLLAMA_INVOCATION=REQUIRED"
echo "NO_HEURISTIC_EXTRACTION=REQUIRED"

echo
echo "=== AUTHORIZATION BOUNDARY ==="
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "OLLAMA_CONTRACT_CHANGE_AUTHORIZED=NO"
echo "IEL_SCHEMA_CHANGE_AUTHORIZED=NO"
echo "WORKFLOW_TRANSPORT_CHANGE_AUTHORIZED=NO"
echo "SYNTHESIS_CHANGE_AUTHORIZED=NO"
echo "FINAL_BOUNDED_IMPLEMENTATION_UNIT_DEFINED=YES"
echo "NEXT_ACTION=USER_REVIEW_AND_EXPLICIT_AUTHORIZATION_OF_FINAL_PACKAGE_SEMANTICS_IMPLEMENTATION_UNIT"
