#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY EXISTING EXECUTION AUTHORIZATION GAP ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="8f4d38363"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== EVIDENCE-BASED CLASSIFICATION ==="
echo "EXISTING_EXECUTION_AUTHORIZATION_RUNTIME_PRESENT=YES"
echo "EXISTING_EXECUTION_AUTHORIZATION_ROUTE_PRESENT=YES"
echo "EXECUTION_AUTHORIZATION_DURABLE_STORE_PRESENT=NO"
echo "EXECUTION_AUTHORIZATION_IS_IN_MEMORY_RETURN_OBJECT_ONLY=YES"
echo "EXECUTION_AUTHORIZATION_ROUTE_ACCEPTS_CALLER_SUPPLIED_AUTHORIZATION_ACTOR=YES"
echo "ROUTE_PROVES_CALLER_IS_USER=NO"
echo "ROUTE_PROVES_EXPLICIT_USER_APPROVAL=NO"
echo "AUTHORIZATION_BINDS_CONFIRMATION_ID=YES"
echo "AUTHORIZATION_BINDS_PREVIEW_ID=YES"
echo "AUTHORIZATION_BINDS_EXECUTION_PLAN_ID=YES"
echo "AUTHORIZATION_BINDS_PACKAGE_ID=YES"
echo "AUTHORIZATION_BINDS_LINEAGE_ID=YES"
echo "AUTHORIZATION_BINDS_ENVELOPE_ID=NO"
echo "AUTHORIZATION_BINDS_VERSION_CONTROL_SCOPE=NO"
echo "AUTHORIZATION_RECORDS_CALLER_SUPPLIED_ACTOR_STRING=YES"
echo "AUTHORIZATION_RECORDS_VERIFIED_USER_ACTOR_PROVENANCE=NO"
echo "CLIENT_UI_EXECUTION_AUTHORIZATION_REACHABILITY_OBSERVED=NO"
echo "NON_ROUTE_CALLERS_OF_CREATE_EXECUTION_AUTHORIZATION=NO"
echo "EXISTING_RUNTIME_IS_CANONICAL_DURABLE_APPROVAL_STORE=NO"
echo "EXISTING_RUNTIME_IS_SUFFICIENT_FOR_GOVERNED_GIT_EXECUTION=NO"

echo
echo "=== IMPORTANT ARCHITECTURAL DETERMINATION ==="
echo "DO_NOT_CREATE_PARALLEL_GENERAL_APPROVAL_SYSTEM=YES"
echo "REUSE_EXISTING_EXECUTION_AUTHORIZATION_CONCEPT=YES"
echo "CURRENT_EXECUTION_AUTHORIZATION_IMPLEMENTATION_REQUIRES_HARDENING=YES"
echo "CANONICAL_PACKAGE_APPROVAL_REMAINS_DISTINCT=YES"
echo "PREVIEW_CONFIRMATION_REMAINS_DISTINCT_FROM_EXECUTION_APPROVAL=YES"

echo
echo "=== SMALLEST PROVEN GAP ==="
echo "GAP_1=DURABLE_EXECUTION_APPROVAL_RECORD"
echo "GAP_2=TRUSTED_EXPLICIT_USER_APPROVAL_TRANSITION"
echo "GAP_3=EXACT_BINDING_TO_EXECUTION_ENVELOPE_AND_SCOPE"
echo "GAP_4=VERSION_CONTROL_AUTHORIZATION_BINDING"
echo "GAP_5=COMPILE_DURABLE_USER_APPROVAL_INTO_EXISTING_EXECUTION_APPROVAL_ARTIFACT"
echo "GAP_6=FAIL_CLOSED_REPLAY_AND_LINEAGE_VALIDATION"

echo
echo "=== INSPECT EXISTING GOVERNANCE PERSISTENCE FOR REUSE ==="
sed -n '250,330p' db/governance-runtime.ts
sed -n '1040,1205p' db/governance-runtime.ts

echo
echo "=== FIND EXISTING PERSISTENCE NEAR ENVELOPE AUTHORITY ==="
git grep -n -I -E \
  'CREATE TABLE|INSERT INTO|UPDATE .*status|envelope_id|approval_id|authorized_by|approved_by|actor' \
  -- \
  db/governance-runtime.ts \
  db/*approval*.ts \
  db/*authorization*.ts \
  server/execution \
  | sed -n '1,1200p' || true

echo
echo "=== NEXT CLASSIFICATION QUESTION ==="
echo "QUESTION=CAN_EXISTING_GOVERNANCE_PERSISTENCE_BE_EXTENDED_AS_THE_DURABLE_EXECUTION_APPROVAL_RECORD_WITHOUT_CREATING_A_PARALLEL_AUTHORITY_SYSTEM"
echo "NEXT_ACTION=CLASSIFY_DURABLE_EXECUTION_APPROVAL_PERSISTENCE_REUSE_BOUNDARY"

echo
echo "=== BOUNDARIES ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_GIT_EFFECT=YES"
echo "NO_REMOTE_WRITE=YES"
