#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY BOUNDED PROJECT-SCOPED READ HANDOFF UNIT ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PROJECT_BOUND_HANDOFF"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== ESTABLISHED AUTHORITY STATE ==="
echo "OPERATIONAL_PACKAGE_AUTHORITY=IMPLEMENTED"
echo "LIVE_OPERATIONAL_PACKAGE_SELECTION=ESTABLISHED"
echo "AUTHORITY_SCOPE=PROJECT"
echo "AUTHORITY_IDENTITY=project_id+package_id+package_version"
echo "SUCCESSOR_VERSION_AUTO_ACTIVATION=NO"

echo
echo "=== CURRENT READ GAP ==="
echo "MISSION_READ_CURRENT_INPUT=package_id"
echo "MISSION_READ_CURRENT_PACKAGE_LOOKUP=package_id_ONLY"
echo "MISSION_READ_CURRENT_OPERATIONAL_AUTHORITY_RESOLUTION=NONE"
echo "MISSION_READ_CURRENT_EXACT_VERSION_REQUIREMENT=NO"
echo "MISSION_CONTROL_CURRENT_PACKAGE_SELECTION=HARDCODED_NONAUTHORITATIVE_PACKAGE_ID"
echo "MISSION_CONTROL_INTAKE_STARTED=NO"

echo
echo "=== BOUNDED IMPLEMENTATION UNIT ==="
echo "UNIT=SERVER_SIDE_PROJECT_SCOPED_OPERATIONAL_AUTHORITY_TO_MISSION_READ_HANDOFF"
echo "ENTRY_IDENTITY=project_id"
echo "AUTHORITY_SOURCE=operational_package_authority"
echo "AUTHORITY_RESULT=EXACT_project_id+package_id+package_version"
echo "MISSION_READ_LOOKUP_REQUIRED=EXACT_project_id+package_id+package_version"
echo "MISSION_READ_MUST_VERIFY_DERIVED_PROJECTION=YES"
echo "MISSION_READ_MUST_PRESERVE_EXACT_SELECTED_VERSION=YES"
echo "MISSION_READ_MUST_NOT_SELECT_NEWEST_PACKAGE=YES"
echo "MISSION_READ_MUST_NOT_INFER_SUCCESSOR_VERSION=YES"
echo "MISSION_READ_MUST_NOT_ACCEPT_CALLER_PACKAGE_ID_AS_SELECTION_AUTHORITY=YES"
echo "MISSION_READ_MUST_NOT_USE_DELEGATION_AS_SELECTION_AUTHORITY=YES"

echo
echo "=== SERVER OWNERSHIP CLASSIFICATION ==="
echo "OPERATIONAL_AUTHORITY_READ_OWNER=db/operational-package-authority.ts"
echo "MISSION_EVIDENCE_READ_OWNER=db/mission-read-repository.ts"
echo "PROJECT_SCOPED_HTTP_BOUNDARY_OWNER=routes/api-mission-read.ts"
echo "AUTHORITY_RESOLUTION_SHOULD_OCCUR_SERVER_SIDE=YES"
echo "ROUTE_MAY_RESOLVE_project_id_TO_EXACT_OPERATIONAL_IDENTITY=YES"
echo "REPOSITORY_MUST_RECEIVE_EXACT_RESOLVED_IDENTITY=YES"
echo "REPOSITORY_MUST_NOT_OWN_OPERATIONAL_SELECTION=YES"
echo "REPOSITORY_MUST_NOT_MUTATE_OPERATIONAL_AUTHORITY=YES"

echo
echo "=== REQUIRED FAILURE CONTRACT ==="
echo "MISSING_project_id=FAIL_CLOSED"
echo "NO_OPERATIONAL_PACKAGE_FOR_PROJECT=NO_ACTIVE_MISSION"
echo "MISSING_EXACT_MISSION_PACKAGE_PROJECTION=FAIL_CLOSED"
echo "PROJECT_IDENTITY_MISMATCH=FAIL_CLOSED"
echo "PACKAGE_IDENTITY_MISMATCH=FAIL_CLOSED"
echo "PACKAGE_VERSION_IDENTITY_MISMATCH=FAIL_CLOSED"
echo "CALLER_PACKAGE_OVERRIDE=NOT_ALLOWED"
echo "IMPLICIT_NEWEST_PACKAGE_FALLBACK=NOT_ALLOWED"
echo "IMPLICIT_SUCCESSOR_VERSION_FALLBACK=NOT_ALLOWED"

echo
echo "=== AUTHORITY NON-ESCALATION ==="
echo "CANONICAL_PACKAGE_MUTATION=NO"
echo "MISSION_PACKAGE_PROJECTION_MUTATION=NO"
echo "OPERATIONAL_PACKAGE_AUTHORITY_MUTATION=NO"
echo "DELEGATION_CREATION=NO"
echo "VALIDATION_AUTHORITY=NO"
echo "ROUTING_AUTHORITY=NO"
echo "ASSIGNMENT_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"

echo
echo "=== CORRIDOR BOUNDARY ==="
echo "MISSION_CONTROL_UI_CHANGE=OUT_OF_SCOPE"
echo "MISSION_CONTROL_PROVIDER_CHANGE=OUT_OF_SCOPE"
echo "MISSION_CONTROL_WORKSPACE_CHANGE=OUT_OF_SCOPE"
echo "CLIENT_OPERATIONAL_SELECTION_CHANGE=OUT_OF_SCOPE"
echo "MISSION_CONTROL_INTAKE_STARTED=NO"
echo "MISSION_CONTROL_INTAKE_REMAINS_SEPARATE_CORRIDOR=YES"

echo
echo "=== MINIMUM IMPLEMENTATION SURFACES ==="
echo "SURFACE_1=db/mission-read-repository.ts"
echo "SURFACE_2=routes/api-mission-read.ts"
echo "SURFACE_3=TARGETED_SERVER_SIDE_TESTS"
echo "db/operational-package-authority.ts_CHANGE_REQUIRED=NO_UNLESS_READ_CONTRACT_DEFECT_IS_DISCOVERED"
echo "SCHEMA_CHANGE_REQUIRED=NO"
echo "MIGRATION_CHANGE_REQUIRED=NO"

echo
echo "=== REQUIRED VALIDATION ==="
echo "TYPECHECK_REQUIRED=YES"
echo "PROJECT_WITH_EXACT_OPERATIONAL_BINDING_READS_SELECTED_PACKAGE=YES"
echo "EXACT_SELECTED_PACKAGE_VERSION_PRESERVED=YES"
echo "UNSELECTED_PROJECT_RETURNS_NO_ACTIVE_MISSION=YES"
echo "MISSING_SELECTED_PROJECTION_FAILS_CLOSED=YES"
echo "WRONG_PROJECT_IDENTITY_FAILS_CLOSED=YES"
echo "WRONG_PACKAGE_VERSION_FAILS_CLOSED=YES"
echo "NEWER_CANONICAL_VERSION_DOES_NOT_AUTO_ACTIVATE=YES"
echo "DELEGATION_STATE_UNCHANGED=YES"
echo "OPERATIONAL_AUTHORITY_STATE_UNCHANGED=YES"
echo "EXECUTION_STATE_UNCHANGED=YES"

echo
echo "=== SCOPE DETERMINATION ==="
echo "MINIMUM_IMPLEMENTATION_UNIT=BOUNDED_AND_CLASSIFIED"
echo "SERVER_SIDE_PROJECT_SCOPED_READ_HANDOFF_REQUIRED=YES"
echo "CLIENT_MISSION_CONTROL_INTAKE_REQUIRED_FOR_THIS_UNIT=NO"
echo "PROJECT_BOUND_HANDOFF_CORRIDOR=CANNOT_CLOSE_BEFORE_IMPLEMENTATION_AND_VALIDATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=PRESENT_AUTHORIZATION_GATE_FOR_BOUNDED_SERVER_SIDE_PROJECT_SCOPED_READ_HANDOFF_ONLY"
