#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY PACKAGE HANDOFF CAPABILITY EXISTENCE ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PACKAGE_HANDOFF_CONTRACT"
echo "PROJECT_SCOPED_DELEGATION_CORRIDOR=CLOSED"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED AUTHORITY ROOTS ==="
echo "CANONICAL_PACKAGE_ROOT=matilda_canonical_packages"
echo "CANONICAL_APPROVAL_STATUS=canonical_approved"
echo "DELEGATION_ROOT=governance_delegations"
echo "MISSION_READ_ROOT=governance_packages"

echo
echo "=== VERIFIED IDENTITY MODELS ==="
echo "CANONICAL_IDENTITY=project_id+package_id+package_version"
echo "DELEGATION_IDENTITY=project_id+package_id+package_version"
echo "MISSION_READ_IDENTITY=package_id_WITH_PROJECT_ID_AND_PACKAGE_VERSION_PROJECTED_FROM_GOVERNANCE_PACKAGES"

echo
echo "=== VERIFIED CURRENT RUNTIME BEHAVIOR ==="
echo "GOVERNANCE_PACKAGE_CREATION_IS_DISTINCT_FROM_CANONICAL_PACKAGE_APPROVAL=YES"
echo "MISSION_READ_LOADS_FROM_GOVERNANCE_PACKAGES=YES"
echo "MISSION_READ_DOES_NOT_SELECT_FROM_matilda_canonical_packages=YES"
echo "MISSION_READ_SELECTION_REQUIRES_CALLER_SUPPLIED_PACKAGE_ID=YES"
echo "MISSION_CONTROL_PROVIDER_ACCEPTS_CALLER_SUPPLIED_PACKAGE_ID=YES"
echo "MISSION_DASHBOARD_CURRENT_PACKAGE_SELECTION=HARDCODED_corridor-smoke"
echo "DELEGATION_REQUIRES_EXISTING_CANONICAL_PACKAGE=YES"
echo "DELEGATION_IS_EXPLICIT_AUTHORITY_EVENT=YES"
echo "DELEGATION_AUTOMATICALLY_MATERIALIZES_GOVERNANCE_PACKAGE=NO"

echo
echo "=== HANDOFF CAPABILITY TEST ==="
CANONICAL_TO_GOVERNANCE_BRIDGE_MATCHES="$(
  rg -n \
    'matilda_canonical_packages.*governance_packages|governance_packages.*matilda_canonical_packages|INSERT INTO governance_packages.*matilda_canonical_packages|createGovernancePackage\(.*canonical|canonical.*createGovernancePackage' \
    db server \
    2>/dev/null | wc -l | tr -d ' '
)"
echo "DIRECT_CANONICAL_TO_GOVERNANCE_PACKAGE_BRIDGE_MATCHES=${CANONICAL_TO_GOVERNANCE_BRIDGE_MATCHES}"

HANDOFF_ARTIFACT_MATCHES="$(
  rg -n \
    'handoff[_ -]?(artifact|package|contract|record)|package[_ -]?handoff|handoff[_ -]?eligib' \
    db server client \
    2>/dev/null | wc -l | tr -d ' '
)"
echo "EXPLICIT_HANDOFF_ARTIFACT_MATCHES=${HANDOFF_ARTIFACT_MATCHES}"

echo
echo "=== CLASSIFICATION ==="
echo "AUTHORITATIVE_CANONICAL_PACKAGE_CAPABILITY=EXISTS"
echo "PROJECT_SCOPED_DELEGATION_CAPABILITY=EXISTS"
echo "LEGACY_OPERATIONAL_GOVERNANCE_PACKAGE_CAPABILITY=EXISTS"
echo "AUTHORITATIVE_PACKAGE_HANDOFF_CAPABILITY=NOT_ESTABLISHED_BY_REPOSITORY_EVIDENCE"
echo "EXPLICIT_HANDOFF_ARTIFACT=NOT_ESTABLISHED"
echo "CANONICAL_TO_MISSION_READ_AUTHORITY_BRIDGE=NOT_ESTABLISHED"
echo "MISSION_READ_CURRENTLY_CONSUMES_CANONICAL_PACKAGE_DIRECTLY=NO"
echo "GOVERNANCE_PACKAGES_CAN_BE_CLASSIFIED_AS_AUTHORITATIVE_HANDOFF_PROJECTION=NO_EVIDENCE"
echo "DELEGATION_CAN_BE_RECLASSIFIED_AS_HANDOFF_ARTIFACT=NO"
echo "PACKAGE_HANDOFF_CONTRACT_GAP=ESTABLISHED"
echo "PROJECT_BOUND_HANDOFF_MAY_BEGIN=NO"
echo "MISSION_CONTROL_IMPLEMENTATION_AUTHORIZED=NO"
echo "KNOWN_DOWNSTREAM_LEGACY_ROOT_DEFECT_REOPENED=NO"

echo
echo "=== NEXT ARCHITECTURAL QUESTION ==="
echo "QUESTION=WHAT_IS_THE_MINIMUM_AUTHORITATIVE_HANDOFF_CONTRACT_THAT_PROJECTS_AN_APPROVED_CANONICAL_PACKAGE_INTO_A_PROJECT_BOUND_MISSION_IDENTITY_WITHOUT_CONFERRING_DELEGATION_OR_DOWNSTREAM_EXECUTION_AUTHORITY"
echo "NEXT_ACTION=DEFINE_MINIMUM_PACKAGE_HANDOFF_CONTRACT_SEMANTICS_AND_OWNERSHIP_BEFORE_ANY_IMPLEMENTATION"
