#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLASSIFY APPROVALS GENERIC CONTENT ROOT CAUSE ==="
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "RECOVERY_POINT=DR_20260826_092915"

echo
echo "=== VERIFIED ROOT CAUSE ==="
echo "REACT_PRESENTATION_DEFECT=NO"
echo "APPROVAL_READ_MODEL_DEFECT=NO"
echo "RECONCILED_INTENT_MAPPING_DEFECT=NO"
echo "GENERIC_CONTENT_ORIGIN=db/matilda-draft-synthesis-runtime.ts"
echo "CURRENT_INTERPRETATION=REQUEST_SPECIFIC"
echo "PROPOSED_WORK=STATIC_GENERIC_STRING"
echo "PROPOSED_ARTIFACTS=STATIC_GENERIC_STRING"
echo "IN_SCOPE=STATIC_GENERIC_STRING"
echo "OUT_OF_SCOPE=STATIC_GENERIC_STRING"
echo "CONSTRAINTS=STATIC_GENERIC_STRING"
echo "EXPECTED_OUTCOME=STATIC_GENERIC_STRING"

echo
echo "=== VERIFIED TRANSPORT ==="
echo "LIVING_DRAFT_PERSISTS_SYNTHESIS_FIELDS=YES"
echo "RECONCILED_INTENT_COPIES_LIVING_DRAFT_FIELDS=YES"
echo "APPROVAL_REQUEST_EXPOSES_RECONCILED_FIELDS=YES"
echo "APPROVALS_REACT_DISPLAYS_EXPOSED_FIELDS=YES"
echo "CONTENT_COHERENCE_GAP_ORIGINATES_UPSTREAM=YES"

echo
echo "=== ARCHITECTURAL BOUNDARY ==="
echo "DO_NOT_FIX_IN_REACT=YES"
echo "DO_NOT_INVENT_REQUEST_SPECIFIC_CONTENT_IN_APPROVAL_READ_MODEL=YES"
echo "DO_NOT_CHANGE_AUTHORITY_MODEL=YES"
echo "DO_NOT_CHANGE_APPROVAL_BEHAVIOR=YES"
echo "SYNTHESIS_CHANGE_AUTHORIZED=NO"
echo "PACKAGE_TAB_REMOVAL_AUTHORIZED=NO"

echo
echo "=== NEXT INVESTIGATION ==="
echo "QUESTION=WHAT_EXISTING_MATILDA_AUTHORED_EVIDENCE_CAN_POPULATE_REQUEST_SPECIFIC_LIVING_DRAFT_FIELDS_WITHOUT_INVENTING_NEW_AUTHORITY_OR_ADDING_AN_UNSUPPORTED_GENERATION_STEP"

echo
echo "=== RELEVANT SYNTHESIS AND EVIDENCE SOURCES ==="
rg -n -C 8 \
  'current_interpretation|durableInterpretation|proposed_work|proposed_artifacts|in_scope|out_of_scope|constraints|expected_outcome|unresolved_questions|evidence_entry_ids|synthesize|Living Draft' \
  db/matilda-draft-synthesis-runtime.ts \
  db/matilda-living-draft-runtime.ts \
  db/matilda-reconciled-intent-runtime.ts \
  server routes \
  -g '*.ts' -g '*.tsx' \
  2>/dev/null || true

echo
echo "NEXT_ACTION=CLASSIFY_EXISTING_MATILDA_AUTHORED_SOURCE_MATERIAL_FOR_REQUEST_SPECIFIC_LIVING_DRAFT_FIELD_SYNTHESIS_BEFORE_ANY_IMPLEMENTATION_AUTHORIZATION"
