#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== CLOSE DECISIONS LIST TITLE COMPACTNESS FOLLOWUP ==="
echo "EXPECTED_HEAD_PREFIX=4a5186575"
echo "RECOVERY_POINT=DR_20260826_173929"
echo "IMPLEMENTATION_COMMIT=6af4a07a6aad0bd89aca7ed6fa86325841a3042f"
echo "VERIFICATION_COMMIT=4a5186575"
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 4a5186575* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED CLOSURE BASIS ==="
echo "DECISION_LIST_TITLES_COMPACT=YES"
echo "MAX_DISPLAY_CHARACTERS=64"
echo "WHOLE_WORD_BOUNDARY_PREFERRED=YES"
echo "ELLIPSIS_ON_SHORTENING=YES"
echo "HEADING_MAX_LINES=2"
echo "FULL_EXPECTED_OUTCOME_IN_DETAIL=PRESERVED"
echo "INTERPRETED_OBJECTIVE_SUMMARY=PRESERVED"
echo "PERSISTED_DATA_UNCHANGED=YES"
echo "PACKAGE_SEMANTICS_UNCHANGED=YES"
echo "APPROVAL_AUTHORITY_UNCHANGED=YES"
echo "FOCUSED_TESTS=5_PASS"
echo "APPROVALS_API_REGRESSION=PASS"
echo "TYPECHECK=PASS"
echo "BUILD=PASS"
echo "DIFF_CHECK=PASS"

echo
echo "=== FORMAL CLOSURE ==="
echo "DECISIONS_LIST_TITLE_COMPACTNESS_FOLLOWUP=CLOSED"
echo "FURTHER_TITLE_COMPACTNESS_IMPLEMENTATION_REQUIRED=NO"
echo "RECOVERY_CHECKPOINT=DR_20260826_173929"
echo "NEXT_ACTION=RETURN_TO_PARENT_SCOPE_AND_IDENTIFY_NEXT_OPEN_FOLLOWUP_OR_CORRIDOR_BEFORE_IMPLEMENTATION"

git diff --check
git add close-decisions-list-title-compactness-followup.sh
git commit -m "Close decisions list title compactness followup"
git push
