#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== COLLECT NEXT UNIT A INPUTS ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

EXPECTED_HEAD_PREFIX="fc51f8af9"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED COLLECTION CHECKPOINT ==="
echo "CHECKPOINT_COMMIT=fc51f8af9a2916b4ee4a86ecc29c6c0dcccd0c1d"
echo "ANCHOR_ONLY_LOOP_STOPPED=YES"
echo "NEXT_REPOSITORY_COMMIT_REQUIRES_NEW_SUBSTANTIVE_EVIDENCE=YES"

echo
echo "=== REQUIRED USER POLICY INPUTS ==="
echo "DECISION_1_ALLOWED_OPERATOR_IDENTITY_POLICY=UNSELECTED"
echo "  A=SINGLE_VERIFIED_OPERATOR_IDENTITY"
echo "  B=BOUNDED_VERIFIED_IDENTITY_SET"
echo "DECISION_2_ACCESS_POLICY_SCOPE=UNSELECTED"
echo "  A=WHOLE_ui.marketingmother.org_OPERATOR_HOST"
echo "  B=BOUNDED_EXECUTION_APPROVAL_SURFACE"

echo
echo "=== REQUIRED EXTERNAL FACT ==="
echo "TEAM_DOMAIN=READ_FROM_CLOUDFLARE_ZERO_TRUST_ACCOUNT_STATE"
echo "APPLICATION_AUDIENCE_TAG=DEFER_UNTIL_ACCESS_APPLICATION_EXISTS_OR_IS_CONFIGURED"

echo
echo "=== ENGINEERING EVIDENCE STILL REQUIRED ==="
echo "ORIGIN_BYPASS_BOUNDARY=UNVERIFIED"
echo "SAFE_NON_EXECUTION_VALIDATION_TARGET=UNDESIGNED"

echo
echo "=== STOP CONDITION ==="
echo "NO_FURTHER_REPOSITORY_COMMIT_UNTIL_NEW_SUBSTANTIVE_INPUT_EXISTS=YES"
echo "IMPLEMENTATION_READINESS_REVIEW_ALLOWED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== USER ACTION REQUIRED ==="
echo "PROVIDE_TEAM_DOMAIN_AND_EXPLICIT_A_OR_B_SELECTION_FOR_DECISION_1_AND_DECISION_2"
