#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== COLLECT UNIT A EXTERNAL INPUTS CHECKPOINT ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="d3fc83feb"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED CORRIDOR STATE ==="
echo "UNIT_A_SOURCE_OF_TRUTH_CORRIDOR=CLOSED"
echo "UNIT_A_EXTERNAL_INPUT_COLLECTION_CORRIDOR=ACTIVE"
echo "UNIT_A_IMPLEMENTATION_READY=NO"
echo "BLOCKER_CLASS=EXTERNAL_FACTS_PLUS_USER_OWNED_POLICY_DECISIONS"

echo
echo "=== EXTERNAL FACTS STILL REQUIRED ==="
echo "TEAM_DOMAIN=REQUIRED_FROM_AUTHORITATIVE_CLOUDFLARE_ACCOUNT_STATE"
echo "APPLICATION_AUDIENCE_TAG=REQUIRED_WHEN_ACCESS_APPLICATION_EXISTS"
echo "ORIGIN_BYPASS_BOUNDARY=REQUIRES_DEPLOYMENT_EVIDENCE"

echo
echo "=== EXPLICIT USER DECISIONS STILL REQUIRED ==="
echo "ALLOWED_OPERATOR_IDENTITY_POLICY=UNSELECTED"
echo "ACCESS_POLICY_SCOPE=UNSELECTED"
echo "ALLOWED_OPERATOR_POLICY_OPTION_A=SINGLE_VERIFIED_OPERATOR_IDENTITY"
echo "ALLOWED_OPERATOR_POLICY_OPTION_B=BOUNDED_VERIFIED_IDENTITY_SET"
echo "POLICY_SCOPE_OPTION_A=WHOLE_CANONICAL_REMOTE_OPERATOR_HOST"
echo "POLICY_SCOPE_OPTION_B=BOUNDED_EXECUTION_APPROVAL_SURFACE"

echo
echo "=== ENGINEERING DESIGN STILL REQUIRED ==="
echo "SAFE_NON_EXECUTION_VALIDATION_TARGET=UNRESOLVED"
echo "EXECUTION_AUTHORIZATION_ROUTE_MUST_REMAIN_UNMOUNTED=YES"
echo "LOCAL_EXECUTION_AUTHORIZATION_REMAINS_DISABLED=YES"

echo
echo "=== COLLECTION RULE ==="
echo "DO_NOT_GUESS_EXTERNAL_FACTS=YES"
echo "DO_NOT_GUESS_USER_POLICY_DECISIONS=YES"
echo "DO_NOT_REPEAT_REPOSITORY_SEARCH_FOR_EXTERNAL_VALUES=YES"
echo "DO_NOT_IMPLEMENT_UNTIL_REQUIRED_INPUTS_ARE_COLLECTED_AND_REVIEWED=YES"

echo
echo "=== NEXT REQUIRED INTERACTION ==="
echo "NEXT_ACTION=OBTAIN_AUTHORITATIVE_CLOUDFLARE_ACCOUNT_FACTS_AND_RECORD_USER_POLICY_SELECTIONS"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "AUTHENTICATION_IS_NOT_EXECUTION_APPROVAL=YES"
echo "AUTHENTICATION_IS_NOT_GIT_AUTHORITY=YES"
echo "CLIENT_SUPPLIED_ACTOR_REMAINS_UNTRUSTED=YES"
echo "MATILDA_SELF_APPROVAL=PROHIBITED"
echo "CADE_SELF_APPROVAL=PROHIBITED"
echo "GENERIC_MUTATION_AUTHORITY=DISABLED"
echo "GENERIC_SHELL_AUTHORITY=DISABLED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=DISABLED"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_DNS_CHANGE=YES"
echo "NO_TUNNEL_CHANGE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
