#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== COLLECT NEXT UNIT A INPUTS ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

EXPECTED_HEAD_PREFIX="4ae8f3081"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED STOP CONDITION ==="
echo "CHECKPOINT_COMMIT=4ae8f30811cb05f2607fce3a7991cd1eeefcd448"
echo "ANCHOR_ONLY_LOOP_STOPPED=YES"
echo "NEXT_REPOSITORY_COMMIT_REQUIRES_NEW_SUBSTANTIVE_EVIDENCE=YES"

echo
echo "=== USER INPUTS TO COLLECT ==="
echo "DECISION_1_ALLOWED_OPERATOR_IDENTITY_POLICY:"
echo "  A=SINGLE_VERIFIED_OPERATOR_IDENTITY"
echo "  B=BOUNDED_VERIFIED_IDENTITY_SET"
echo
echo "DECISION_2_ACCESS_POLICY_SCOPE:"
echo "  A=WHOLE_ui.marketingmother.org_OPERATOR_HOST"
echo "  B=BOUNDED_EXECUTION_APPROVAL_SURFACE"

echo
echo "=== EXTERNAL FACT TO COLLECT ==="
echo "TEAM_DOMAIN=READ_FROM_CLOUDFLARE_ZERO_TRUST_ACCOUNT_STATE"
echo "APPLICATION_AUDIENCE_TAG=DEFER_UNTIL_ACCESS_APPLICATION_EXISTS_OR_IS_CONFIGURED"

echo
echo "=== ENGINEERING EVIDENCE STILL NEEDED ==="
echo "ORIGIN_BYPASS_BOUNDARY=UNVERIFIED"
echo "SAFE_NON_EXECUTION_VALIDATION_TARGET=UNDESIGNED"

echo
echo "=== NEXT ACTION ==="
echo "PROVIDE_TEAM_DOMAIN_AND_EXPLICIT_SELECTIONS_FOR_DECISION_1_AND_DECISION_2"
echo "DO_NOT_COMMIT_THIS_COLLECTION_STEP=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"
