#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== DEFINE MINIMUM PACKAGE HANDOFF CONTRACT SEMANTICS ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PACKAGE_HANDOFF_CONTRACT"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFIED GAP ==="
echo "DIRECT_CANONICAL_TO_GOVERNANCE_PACKAGE_BRIDGE_MATCHES=0"
echo "AUTHORITATIVE_PACKAGE_HANDOFF_CAPABILITY=NOT_ESTABLISHED"
echo "CANONICAL_TO_MISSION_READ_AUTHORITY_BRIDGE=NOT_ESTABLISHED"

echo
echo "=== MINIMUM CONTRACT SEMANTICS ==="
echo "HANDOFF_SOURCE=APPROVED_CANONICAL_PACKAGE"
echo "HANDOFF_SOURCE_TABLE=matilda_canonical_packages"
echo "HANDOFF_SOURCE_REQUIRED_STATUS=canonical_approved"
echo "HANDOFF_IDENTITY=project_id+package_id+package_version"
echo "HANDOFF_MUST_PRESERVE_EXACT_PACKAGE_VERSION=YES"
echo "HANDOFF_MUST_PRESERVE_PROJECT_ID=YES"
echo "HANDOFF_MUST_NOT_SELECT_NEWEST_PACKAGE=YES"
echo "HANDOFF_MUST_NOT_USE_PROJECT_ID_ALONE=YES"
echo "HANDOFF_MUST_NOT_USE_UI_PREFERENCE_AS_AUTHORITY=YES"

echo
echo "=== AUTHORITY BOUNDARY ==="
echo "HANDOFF_CONFERS_DELEGATION_AUTHORITY=NO"
echo "HANDOFF_CONFERS_VALIDATION_AUTHORITY=NO"
echo "HANDOFF_CONFERS_ROUTING_AUTHORITY=NO"
echo "HANDOFF_CONFERS_ASSIGNMENT_AUTHORITY=NO"
echo "HANDOFF_CONFERS_EXECUTION_AUTHORITY=NO"
echo "DELEGATION_REMAINS_DISTINCT_EXPLICIT_AUTHORITY_EVENT=YES"
echo "MISSION_CONTROL_REMAINS_READ_ONLY=YES"

echo
echo "=== OWNERSHIP CLASSIFICATION ==="
echo "HANDOFF_OWNERSHIP_LAYER=UNRESOLVED_PENDING_REPOSITORY_OWNERSHIP_PROBE"
echo "MISSION_READ_CAN_OWN_HANDOFF_SELECTION=NO"
echo "MISSION_CONTROL_CAN_OWN_HANDOFF_SELECTION=NO"
echo "DELEGATION_CAN_OWN_HANDOFF_SELECTION=NO"
echo "GOVERNANCE_PACKAGES_CAN_BE_ASSUMED_HANDOFF_STORE=NO"

echo
echo "=== NEXT REQUIRED EVIDENCE ==="
echo "QUESTION=WHICH_EXISTING_SERVER_OR_PERSISTENCE_BOUNDARY_IS_THE_NEAREST_VALID_OWNER_FOR_MATERIALIZING_OR_PROJECTING_THIS_EXACT_APPROVED_CANONICAL_IDENTITY"
echo "PROJECT_BOUND_HANDOFF_STARTED=NO"
echo "NEXT_ACTION=INVESTIGATE_HANDOFF_OWNERSHIP_WITHOUT_IMPLEMENTATION"
