#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== DESIGN MINIMUM CANONICAL-TO-GOVERNANCE PACKAGE PROJECTION BOUNDARY ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PACKAGE_HANDOFF_CONTRACT"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== ESTABLISHED SOURCE AUTHORITY ==="
echo "SOURCE_TABLE=matilda_canonical_packages"
echo "SOURCE_STATUS_REQUIRED=canonical_approved"
echo "SOURCE_IDENTITY=project_id+package_id+package_version"
echo "SOURCE_SEMANTICS=approved_interpretation+approved_work+approved_artifacts+approved_scope+approved_constraints+approved_expected_outcome"
echo "CALLER_SUPPLIED_CANONICAL_SEMANTICS_ALLOWED=NO"

echo
echo "=== ESTABLISHED DOWNSTREAM READ REQUIREMENT ==="
echo "MISSION_READ_DURABLE_SOURCE=governance_packages"
echo "MISSION_READ_REQUIRES_package_id=YES"
echo "MISSION_READ_REQUIRES_package_version=YES"
echo "MISSION_READ_PROJECTS_project_id=YES"
echo "MISSION_READ_PROJECTS_conversation_id=YES"
echo "MISSION_READ_PROJECTS_requested_outcome=YES"

echo
echo "=== MINIMUM PROJECTION CONTRACT ==="
echo "BOUNDARY_NAME=CANONICAL_PACKAGE_TO_MISSION_PACKAGE_PROJECTION"
echo "INPUT=EXACT_project_id+package_id+package_version"
echo "INPUT_MUST_RESOLVE_ONE_CANONICAL_ROW=YES"
echo "INPUT_MUST_MATCH_canonical_approved=YES"
echo "PROJECT_ID_MUST_MATCH_CANONICAL_ROW=YES"
echo "PACKAGE_ID_MUST_MATCH_CANONICAL_ROW=YES"
echo "PACKAGE_VERSION_MUST_MATCH_CANONICAL_ROW=YES"
echo "PROJECTION_MUST_BE_DERIVED_ONLY_FROM_CANONICAL_ROW=YES"
echo "PROJECTION_MUST_NOT_ACCEPT_SEMANTIC_OVERRIDE=YES"
echo "PROJECTION_MUST_FAIL_CLOSED_ON_MISSING_CANONICAL_ROW=YES"
echo "PROJECTION_MUST_FAIL_CLOSED_ON_STATUS_MISMATCH=YES"
echo "PROJECTION_MUST_FAIL_CLOSED_ON_IDENTITY_MISMATCH=YES"

echo
echo "=== TARGET FIELD MAPPING TO EXISTING MISSION SOURCE ==="
echo "governance_packages.package_id=canonical.package_id"
echo "governance_packages.package_version=canonical.package_version"
echo "governance_packages.project_id=canonical.project_id"
echo "governance_packages.conversation_id=canonical.conversation_id"
echo "governance_packages.requested_outcome=canonical.approved_expected_outcome"
echo "governance_packages.scope=canonical.approved_scope"
echo "governance_packages.constraints=canonical.approved_constraints"
echo "governance_packages.context=DERIVED_FROM_CANONICAL_APPROVED_INTERPRETATION_IF_REQUIRED_BY_EXISTING_SCHEMA"
echo "governance_packages.containment=REQUIRES_EXACT_MAPPING_CLASSIFICATION"
echo "governance_packages.success_criteria=REQUIRES_EXACT_MAPPING_CLASSIFICATION"
echo "governance_packages.style_presentation_intent=REQUIRES_EXACT_MAPPING_CLASSIFICATION"
echo "governance_packages.exclusions=REQUIRES_EXACT_MAPPING_CLASSIFICATION"

echo
echo "=== AUTHORITY PRESERVATION ==="
echo "NEW_PACKAGE_AUTHORITY_ROOT_CREATED=NO"
echo "governance_packages_AUTHORITY_CLASS=DERIVED_MISSION_READ_PROJECTION_IF_IMPLEMENTED"
echo "CANONICAL_AUTHORITY_REMAINS_matilda_canonical_packages=YES"
echo "DELEGATION_AUTHORITY_CONFERRED=NO"
echo "VALIDATION_AUTHORITY_CONFERRED=NO"
echo "ROUTING_AUTHORITY_CONFERRED=NO"
echo "ASSIGNMENT_AUTHORITY_CONFERRED=NO"
echo "EXECUTION_AUTHORITY_CONFERRED=NO"
echo "MISSION_CONTROL_AUTHORITY_CONFERRED=NO"

echo
echo "=== OWNERSHIP BOUNDARY ==="
echo "PROJECTION_SOURCE_OWNER=CANONICAL_APPROVAL_PERSISTENCE"
echo "PROJECTION_TARGET_ADAPTER=EXISTING_governance_packages_PERSISTENCE_SURFACE"
echo "CURRENT_CREATE_GOVERNANCE_PACKAGE_ROUTE_REUSED_UNCHANGED=NO"
echo "CURRENT_CALLER_SUPPLIED_WRITE_PATH_RECLASSIFIED_AS_CANONICAL_HANDOFF=NO"
echo "NEW_BOUNDED_PROJECTION_ADAPTER_REQUIRED=LIKELY"
echo "PROJECTION_TRIGGER=REQUIRES_SEPARATE_CLASSIFICATION"
echo "AUTOMATIC_POST_APPROVAL_TRIGGER_ASSUMED=NO"
echo "EXPLICIT_OPERATOR_TRIGGER_ASSUMED=NO"

echo
echo "=== UNRESOLVED FIELD MAPPING ==="
echo "QUESTION_1=WHAT_CANONICAL_FIELDS_MAP_TO_containment"
echo "QUESTION_2=WHAT_CANONICAL_FIELDS_MAP_TO_success_criteria"
echo "QUESTION_3=WHAT_CANONICAL_FIELDS_MAP_TO_style_presentation_intent"
echo "QUESTION_4=WHAT_CANONICAL_FIELDS_MAP_TO_exclusions"
echo "QUESTION_5=ARE_ANY_OF_THESE_TARGET_FIELDS_LEGACY_ONLY_AND_OPTIONAL_FOR_AUTHORITATIVE_MISSION_READ"

echo
echo "=== SCOPE DETERMINATION ==="
echo "PACKAGE_HANDOFF_CONTRACT_GAP=CONFIRMED"
echo "MINIMUM_PROJECTION_BOUNDARY=DEFINED"
echo "PROJECTION_FIELD_MAPPING=PARTIALLY_DEFINED"
echo "PROJECTION_TRIGGER=UNRESOLVED"
echo "PROJECT_BOUND_HANDOFF_STARTED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "NEXT_ACTION=CLASSIFY_EXACT_FIELD_MAPPING_AND_TRIGGER_SEMANTICS_BEFORE_PRESENTING_ANY_IMPLEMENTATION_UNIT"
