#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== DESIGN PACKAGE SEMANTICS CONDITIONAL COMPLETENESS ==="
echo "EXPECTED_HEAD_PREFIX=782d46ccf"
echo "RECOVERY_POINT=DR_20260826_111719"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 782d46ccf* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== PROPOSED CONTRACT ==="
echo "PACKAGE_SEMANTICS_TOP_LEVEL_NULLABILITY=PRESERVE"
echo "INDIVIDUAL_FIELD_NULLABILITY=PRESERVE_WHEN_CURRENT_REQUEST_DOES_NOT_ESTABLISH_FIELD"
echo "CURRENT_REQUEST_EXPLICIT_FIELD_PRESERVATION=REQUIRED"
echo "UNSUPPORTED_FIELD_INVENTION=PROHIBITED"
echo "GENERIC_DEFAULTS=PROHIBITED"
echo "HEURISTIC_EXTRACTION=PROHIBITED"
echo "CROSS_TURN_FIELD_MERGE=PROHIBITED"

echo
echo "=== EXPECTED OUTCOME CASE ==="
echo "IF_CURRENT_REQUEST_EXPLICITLY_STATES_EXPECTED_OUTCOME=packageSemantics.expectedOutcome_MUST_BE_NON_NULL_AND_REQUEST_SPECIFIC"
echo "IF_CURRENT_REQUEST_DOES_NOT_ESTABLISH_EXPECTED_OUTCOME=packageSemantics.expectedOutcome_MAY_BE_NULL"
echo "VALIDATOR_GLOBAL_NON_NULL_REQUIREMENT=NO"
echo "UI_FALLBACK_CHANGE=NO"

echo
echo "=== LIKELY IMPLEMENTATION SURFACE ==="
echo "PRIMARY_SURFACE=scripts/utils/ollamaChat.ts_PROMPT_AUTHORSHIP_RULES"
echo "TEST_SURFACE=scripts/utils/ollamaChat.package-semantics-contract.test.ts"
echo "IEL_CHANGE=NO"
echo "LIVING_DRAFT_SYNTHESIS_CHANGE=NO"
echo "APPROVAL_READ_MODEL_CHANGE=NO"
echo "APPROVAL_UI_CHANGE=NO"
echo "AUTHORITY_MODEL_CHANGE=NO"
echo "SECOND_OLLAMA_INVOCATION=NO"

echo
echo "=== VALIDATION TARGET ==="
echo "TEST_1=PROMPT_REQUIRES_PRESERVATION_OF_EXPLICIT_CURRENT_REQUEST_PACKAGE_SEMANTICS"
echo "TEST_2=PROMPT_PROHIBITS_INVENTING_UNESTABLISHED_FIELDS"
echo "TEST_3=EXISTING_NULLABILITY_CONTRACT_REMAINS_VALID"
echo "TEST_4=EXISTING_PACKAGE_SEMANTICS_SUITE_PASSES"
echo "TEST_5=LIFECYCLE_REGRESSION_SUITE_PASSES"
echo "TEST_6=TYPECHECK_AND_BUILD_PASS"

echo
echo "=== DECISION GATE ==="
echo "DESIGN_STATUS=READY_FOR_USER_REVIEW"
echo "IMPLEMENTATION_STARTED=NO"
echo "NEXT_ACTION=AUTHORIZE_OR_REVISE_NARROW_PROMPT_CONTRACT_CHANGE"

git diff --check

git add design-package-semantics-conditional-completeness.sh
git commit -m "Design package semantics conditional completeness"
git push
