#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== DETERMINE CANONICAL EXECUTION APPROVAL PERSISTENCE OWNER ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "IMPLEMENTATION_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="c4ac7fb51"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== INSPECT COMPLETE EXISTING EXECUTION AUTHORIZATION RUNTIME ==="
cat db/matilda-execution-authorization-runtime.ts

echo
echo "=== INSPECT EXECUTION AUTHORIZATION ROUTE ==="
cat server/routes/matilda-execution-authorization-route.ts

echo
echo "=== INSPECT GOVERNANCE ENVELOPE TYPE DEFINITIONS ==="
sed -n '130,215p' db/governance-runtime.ts

echo
echo "=== INSPECT GOVERNANCE ENVELOPE PERSISTENCE OWNERSHIP ==="
sed -n '270,325p' db/governance-runtime.ts
sed -n '1070,1195p' db/governance-runtime.ts

echo
echo "=== INSPECT EXISTING MATILDA DURABLE RUNTIME PATTERNS ==="
sed -n '1,190p' db/matilda-envelope-runtime.ts
sed -n '1,165p' db/matilda-routing-runtime.ts

echo
echo "=== FIND EXECUTION AUTHORIZATION TEST COVERAGE ==="
git grep -n -I -E \
  'createExecutionAuthorization|execution-authorization|authorization_actor|authorization_state' \
  -- \
  '*.test.ts' \
  '*.test.mjs' \
  server \
  db \
  client/src \
  | sed -n '1,1000p' || true

echo
echo "=== FIND DATABASE OWNERSHIP RELATIONSHIPS ==="
git grep -n -I -E \
  'governance_envelopes|matilda_execution|execution_authorization|authorization_state' \
  -- \
  db \
  server \
  | sed -n '1,1200p' || true

echo
echo "=== OWNERSHIP CLASSIFICATION ==="
echo "GOVERNANCE_RUNTIME_OWNS_CANONICAL_ENVELOPE_PERSISTENCE=YES"
echo "MATILDA_EXECUTION_AUTHORIZATION_RUNTIME_OWNS_EXISTING_EXECUTION_AUTHORIZATION_CONCEPT=YES"
echo "EXISTING_EXECUTION_AUTHORIZATION_RUNTIME_IS_CURRENTLY_NON_DURABLE=YES"
echo "EXISTING_EXECUTION_AUTHORIZATION_RUNTIME_IS_ALREADY_SEPARATE_FROM_CANONICAL_PACKAGE_APPROVAL=YES"
echo "EXECUTION_APPROVAL_SHOULD_REMAIN_SEPARATE_FROM_CANONICAL_PACKAGE_APPROVAL=YES"
echo "NEW_PARALLEL_GENERAL_APPROVAL_SYSTEM_REQUIRED=NO"

echo
echo "=== PREFERRED OWNERSHIP DETERMINATION ==="
echo "CANONICAL_PERSISTENCE_OWNER=db/matilda-execution-authorization-runtime.ts"
echo "PERSISTENCE_MODEL=DEDICATED_DURABLE_EXECUTION_AUTHORIZATION_RECORD"
echo "FOREIGN_AUTHORITY_ANCHOR=governance_envelopes.envelope_id"
echo "GOVERNANCE_ENVELOPE_TABLE_SHOULD_NOT_ABSORB_USER_APPROVAL_COLUMNS=YES"

echo
echo "=== MINIMUM DURABLE SCHEMA CLASSIFICATION ==="
echo "TABLE=matilda_execution_authorizations"
echo "FIELD_1=authorization_id_PRIMARY_KEY"
echo "FIELD_2=envelope_id_FOREIGN_KEY_REQUIRED"
echo "FIELD_3=package_id_REQUIRED"
echo "FIELD_4=package_version_REQUIRED"
echo "FIELD_5=delegation_or_lineage_id_REQUIRED"
echo "FIELD_6=authorization_state_REQUIRED"
echo "FIELD_7=authorization_actor_REQUIRED"
echo "FIELD_8=authorization_timestamp_REQUIRED"
echo "FIELD_9=commit_authorized_REQUIRED_BOOLEAN"
echo "FIELD_10=push_authorized_REQUIRED_BOOLEAN"
echo "FIELD_11=repo_path_NULLABLE_UNLESS_VERSION_CONTROL"
echo "FIELD_12=branch_NULLABLE_UNLESS_VERSION_CONTROL"
echo "FIELD_13=remote_NULLABLE_UNLESS_PUSH"
echo "FIELD_14=expected_head_NULLABLE_UNLESS_VERSION_CONTROL"
echo "FIELD_15=allowed_paths_NULLABLE_UNLESS_COMMIT"
echo "FIELD_16=created_at_REQUIRED"

echo
echo "=== MINIMUM INVARIANTS ==="
echo "AUTHORIZATION_MUST_REFERENCE_EXISTING_GOVERNANCE_ENVELOPE=YES"
echo "AUTHORIZATION_ENVELOPE_PACKAGE_ID_MUST_MATCH=YES"
echo "AUTHORIZATION_ENVELOPE_PACKAGE_VERSION_MUST_MATCH=YES"
echo "AUTHORIZATION_MUST_FAIL_CLOSED_ON_SCOPE_MISMATCH=YES"
echo "PUSH_AUTHORIZATION_REQUIRES_COMMIT_AUTHORIZATION=YES"
echo "COMMIT_AUTHORIZATION_REQUIRES_REPO_BRANCH_HEAD_AND_ALLOWED_PATHS=YES"
echo "PUSH_AUTHORIZATION_REQUIRES_REMOTE=YES"
echo "AUTHORIZATION_ACTOR_MUST_NOT_BE_TRUSTED_FROM_UNVERIFIED_BODY_STRING=YES"
echo "DURABLE_RECORD_MUST_BE_SOURCE_FOR_EXISTING_APPROVAL_ARTIFACT=YES"
echo "APPROVAL_ARTIFACT_MUST_NOT_EXPAND_DURABLE_SCOPE=YES"
echo "REPLAY_WITH_DIFFERENT_ENVELOPE_OR_SCOPE_MUST_FAIL_CLOSED=YES"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "CANONICAL_PACKAGE_APPROVAL_CHANGE_REQUIRED=NO"
echo "GOVERNANCE_ENVELOPE_SEMANTICS_CHANGE_REQUIRED=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGE_REQUIRED=NO"
echo "REMOTE_PUSH_EFFECT_CHANGE_REQUIRED=NO"
echo "GENERIC_CADE_ROUTE_CHANGE_REQUIRED=NO"
echo "GENERIC_MUTATION_AUTHORITY_CHANGE_REQUIRED=NO"
echo "GENERIC_SHELL_AUTHORITY_CHANGE_REQUIRED=NO"
echo "AUTONOMOUS_EXECUTION_AUTHORITY_CHANGE_REQUIRED=NO"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_TRUSTED_USER_APPROVAL_TRANSITION_AND_DURABLE_AUTHORIZATION_COMPILATION_BOUNDARY"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_DATABASE_SCHEMA_WRITE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_GIT_EFFECT=YES"
echo "NO_REMOTE_WRITE=YES"
