# Use the official lightweight Python image
FROM python:3.12-alpine

# Set the working directory inside the container
WORKDIR /app
RUN apk add --no-cache gcc libc-dev

# Copy the requirements file and install dependencies
COPY ops-stream/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the main application code
COPY ops-stream/ops_stream.py /app/

# Define the default command to run the application
CMD ["python", "ops_stream.py"]
