#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="782645c97"

UI="client/src/approvals/ApprovalsWorkspace.tsx"
API="client/src/approvals/governanceEnvelopeGateApi.ts"
TEST="client/src/approvals/governanceEnvelopeGateApi.test.ts"

TARGETS=(
  "$UI"
  "$API"
  "$TEST"
)

git fetch origin "$BRANCH"

test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$EXPECTED_HEAD"

printf '\n====================================================\n'
printf ' EXPLICIT OPERATOR ENVELOPE GATE — ATTEMPT 1 TARGET GUARD\n'
printf '====================================================\n\n'

echo "CURRENT_HEAD=$EXPECTED_HEAD"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "IMPLEMENTATION_ATTEMPT=1"
echo "TARGET_COUNT=3"

printf '\n=== TARGET BASELINE ===\n'

test -f "$UI"
test -z "$(git status --porcelain -- "$UI")"
echo "TRACKED_TARGET_CLEAN=$UI"
echo "BASELINE_BLOB_$UI=$(git rev-parse "HEAD:$UI")"

test ! -e "$API"
test -z "$(git status --porcelain -- "$API")"
echo "EXPECTED_NEW_TARGET_ABSENT=$API"

test ! -e "$TEST"
test -z "$(git status --porcelain -- "$TEST")"
echo "EXPECTED_NEW_TARGET_ABSENT=$TEST"

printf '\n=== FIXED ATOMIC TARGET SET ===\n'
printf '%s\n' "${TARGETS[@]}"

printf '\n=== IMPLEMENTATION CONTRACT ===\n'
echo "RETAIN_SUCCESSFUL_VALIDATION_IDENTITY_IN_LOCAL_UI_STATE=YES"
echo "VALIDATION_RESULT_ID_MUST_BE_THE_ID_USED_BY_SUCCESSFUL_VALIDATION_POST=YES"
echo "PACKAGE_ID_MUST_MATCH_SUCCESSFUL_VALIDATION=YES"
echo "PACKAGE_VERSION_MUST_MATCH_SUCCESSFUL_VALIDATION=YES"
echo "DELEGATION_ID_MUST_MATCH_SUCCESSFUL_VALIDATION=YES"
echo "GATE_ACTION_VISIBLE_ONLY_AFTER_SUCCESSFUL_OPERATOR_VALIDATION=YES"
echo "GATE_ACTION_REQUIRES_SEPARATE_OPERATOR_CLICK=YES"
echo "GATE_CLIENT_POSTS_EXISTING_API_ROUTE=/api/governance/envelope-gate"
echo "GATE_CLIENT_MUST_VALIDATE_REQUIRED_IDENTITY_BEFORE_FETCH=YES"

printf '\n=== EXCLUDED CHANGES ===\n'
echo "SERVER_CHANGE=NO"
echo "DATABASE_CHANGE=NO"
echo "SCHEMA_CHANGE=NO"
echo "ENTRY_POINT_CHANGE=NO"
echo "ELIGIBILITY_CHANGE=NO"
echo "VALIDATION_ROUTE_CHANGE=NO"
echo "AUTOMATIC_VALIDATION_TO_GATE_TRANSITION=NO"
echo "AUTOMATIC_GATE_CREATION=NO"
echo "AUTOMATIC_ENVELOPE_CREATION=NO"

printf '\n=== SUCCESS CONTRACT ===\n'
echo "VALIDATION_AND_GATE_ACTIONS_REMAIN_SEPARATE=YES"
echo "GATE_ACTION_UNAVAILABLE_BEFORE_SUCCESSFUL_VALIDATION=YES"
echo "EXACT_SUCCESSFUL_VALIDATION_LINEAGE_POSTED_TO_GATE=YES"
echo "INVALID_GATE_IDENTITY_REJECTED_BEFORE_FETCH=YES"
echo "GATE_ROUTE_FAILURE_SURFACED_TO_OPERATOR=YES"
echo "OPERATOR_CLICK_REQUIRED=YES"
echo "ENVELOPE_CREATION_AUTHORITY=NONE"
echo "EXECUTION_AUTHORITY=NONE"
echo "DOWNSTREAM_AUTHORITY=NONE"
echo "NEW_AUTHORITY=NONE"

printf '\n=== FAILURE CONTAINMENT ===\n'
echo "CURRENT_HYPOTHESIS_FAILED_ATTEMPTS=0"
echo "MAX_FAILED_ATTEMPTS_BEFORE_REVERT=3"
echo "ON_FAILURE=RESTORE_ONLY_THREE_ATTEMPT_TARGETS"
echo "PRESERVE_UNRELATED_WORKTREE=YES"
echo "STAGE_ONLY_EXPLICIT_TARGETS=YES"
echo "GIT_ADD_DOT=PROHIBITED"
echo "SPECULATIVE_PATCH_LAYERING=PROHIBITED"

printf '\n=== AUTHORITY BOUNDARY ===\n'
echo "LIVE_GATE_INVOCATION=NO"
echo "LIVE_GOVERNANCE_DATA_MUTATION=NO"
echo "LIFECYCLE_TRANSITION_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "DOWNSTREAM_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"

printf '\n=== PRESERVED UNRELATED WORKTREE ===\n'
git status --short

printf '\n=== NEXT ACTION ===\n'
echo "NEXT_ACTION=BEGIN_ATOMIC_EXPLICIT_OPERATOR_ENVELOPE_GATE_UI_ATTEMPT_1"
echo "IMPLEMENTATION_PERFORMED=NO"

printf '\nEXPLICIT_OPERATOR_ENVELOPE_GATE_ATTEMPT_1_TARGET_GUARD=PASS\n'
