#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="65f654a85"

git fetch origin "$BRANCH"
test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$EXPECTED_HEAD"

UI="client/src/approvals/ApprovalsWorkspace.tsx"
API="client/src/approvals/governanceValidationApi.ts"
TEST="client/src/approvals/governanceValidationApi.test.ts"

printf '\n=== EXPLICIT OPERATOR VALIDATION — ATTEMPT 1 GUARD ===\n'
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "CURRENT_HYPOTHESIS=MINIMUM_CLIENT_OPERATOR_VALIDATION_ADAPTER"
echo "ATTEMPT=1"
echo "EXPECTED_NEW_FILES=2"
echo "EXPECTED_EXISTING_FILES_MODIFIED=1"
echo "SERVER_CHANGE=NO"
echo "DATABASE_CHANGE=NO"
echo "LIVE_VALIDATION_INVOCATION=NO"
echo "LIVE_GOVERNANCE_DATA_MUTATION=NO"
echo "AUTO_ADVANCE=NO"
echo "DOWNSTREAM_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"

printf '\n=== VERIFIED REQUEST CONTRACT ===\n'
echo "ENDPOINT=POST_/api/governance/validation"
echo "VALIDATION_RESULT_ID=GENERATED_ON_EXPLICIT_CLICK"
echo "PACKAGE_ID=FROM_CANONICAL_PACKAGE_READ_MODEL"
echo "PACKAGE_VERSION=FROM_CANONICAL_PACKAGE_READ_MODEL"
echo "DELEGATION_ID=FROM_DELEGATED_READ_MODEL"
echo "VALIDATION_STATUS=MUST_BE_EXPLICIT_OPERATOR_INPUT"
echo "ELIGIBILITY_REMAINS_SERVER_ENFORCED=YES"

printf '\n=== VERIFIED UI CONTRACT ===\n'
echo "UI_TARGET=$UI"
echo "VISIBILITY=DELEGATED_PACKAGE_ONLY"
echo "TRIGGER=EXPLICIT_OPERATOR_CLICK"
echo "AUTOMATIC_INVOCATION=NO"
echo "EXISTING_DELEGATION_ACTION_PRESERVED=YES"

printf '\n=== TARGET BASELINE GUARD ===\n'
test -f "$UI"
test -z "$(git diff -- "$UI")"
test ! -e "$API"
test ! -e "$TEST"

echo "TRACKED_UI_BLOB=$(git rev-parse HEAD:"$UI")"
echo "EXPECTED_NEW=$API"
echo "EXPECTED_NEW=$TEST"

printf '\n=== REQUIRED CLIENT ADAPTER BEHAVIOR ===\n'
echo "REQUIRE_NONEMPTY_VALIDATION_RESULT_ID=YES"
echo "REQUIRE_NONEMPTY_PACKAGE_ID=YES"
echo "REQUIRE_POSITIVE_INTEGER_PACKAGE_VERSION=YES"
echo "REQUIRE_NONEMPTY_DELEGATION_ID=YES"
echo "REQUIRE_NONEMPTY_VALIDATION_STATUS=YES"
echo "POST_ONLY_AFTER_LOCAL_INPUT_VALIDATION=YES"
echo "FAIL_CLOSED_ON_NON_OK_RESPONSE=YES"
echo "NO_AUTHORITY_SYNTHESIS=YES"

printf '\n=== REQUIRED VALIDATION GATES ===\n'
echo "GATE_1=git_diff_check"
echo "GATE_2=root_npm_run_check"
echo "GATE_3=repository_native_tsx_adapter_tests"
echo "GATE_4=client_npm_run_build"
echo "ALL_GATES_REQUIRED_BEFORE_IMPLEMENTATION_COMMIT=YES"

printf '\n=== FAILURE CONTAINMENT ===\n'
echo "ON_FAILURE=RESTORE_ONLY_EXISTING_UI_TARGET_AND_REMOVE_ONLY_TWO_NEW_FILES"
echo "UNRELATED_WORKTREE=PRESERVE"
echo "GIT_ADD_DOT=PROHIBITED"
echo "MAX_FAILED_ATTEMPTS_PER_HYPOTHESIS=3"

printf '\n=== IMPLEMENTATION DECISION ===\n'
echo "ATTEMPT_1_IS_JUSTIFIED=YES"
echo "NEXT_ACTION=IMPLEMENT_THREE_FILE_BOUNDED_CLIENT_CHANGE"
echo "IMPLEMENTATION_PERFORMED=NO"

printf '\n=== PRESERVED WORKTREE ===\n'
git status --short

printf '\nEXPLICIT_OPERATOR_VALIDATION_ATTEMPT_1_GUARD=PASS\n'
