#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== HOLD APPROVALS UI FOR LIVE VISUAL REVIEW ==="
echo "BASELINE_COMMIT=5569e633"
echo "CLIENT_BUILD=PASS"
echo "IMPLEMENTATION_STATE=PAUSED_FOR_VISUAL_REVIEW"
echo "FURTHER_UI_CHANGE_AUTHORIZED=NO"
echo "PACKAGES_TAB_REMOVAL_AUTHORIZED=NO"

echo
echo "=== REVIEW REQUEST ==="
echo "COMPARE=PACKAGES_VS_APPROVALS"
echo "CHECK=OVERALL_VISUAL_CALM"
echo "CHECK=LEFT_PANEL_DENSITY"
echo "CHECK=RIGHT_PANEL_SPACING"
echo "CHECK=SECTION_HIERARCHY"
echo "CHECK=DECISION_ACTION_VISIBILITY"
echo "CHECK=TECHNICAL_DETAIL_DEEMPHASIS"
echo "CHECK=WHETHER_APPROVALS_NOW_FEELS_CLOSER_TO_PACKAGES"

echo
echo "NEXT_ACTION=USER_RETURNS_SCREENSHOT_OR_VISUAL_FEEDBACK_BEFORE_ANY_FURTHER_IMPLEMENTATION"
