#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== IDENTIFY AUTHORITATIVE UNIT A CONFIGURATION SOURCES ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="18fcfc624"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED READINESS GAP ==="
echo "UNIT_A_IMPLEMENTATION_READY=NO"
echo "CANONICAL_REMOTE_HOST=ui.marketingmother.org"
echo "CANONICAL_TUNNEL=ui-server"
echo "TEAM_DOMAIN=UNRESOLVED"
echo "APPLICATION_AUDIENCE_TAG=UNRESOLVED"
echo "ALLOWED_OPERATOR_IDENTITY=UNRESOLVED"
echo "ACCESS_POLICY_SCOPE=UNRESOLVED"
echo "DIRECT_REMOTE_BYPASS_POLICY=UNRESOLVED"
echo "NON_PRODUCTION_VALIDATION_PATH=UNRESOLVED"

echo
echo "=== AUTHORITATIVE SOURCE CLASSIFICATION ==="
echo "TEAM_DOMAIN_SOURCE=CLOUDFLARE_ZERO_TRUST_ACCOUNT_CONFIGURATION"
echo "APPLICATION_AUDIENCE_TAG_SOURCE=CLOUDFLARE_ACCESS_APPLICATION_CONFIGURATION"
echo "ALLOWED_OPERATOR_IDENTITY_SOURCE=USER_OWNED_POLICY_DECISION_PLUS_VERIFIED_IDENTITY_PROVIDER_VALUE"
echo "ACCESS_POLICY_SCOPE_SOURCE=USER_OWNED_ARCHITECTURAL_DECISION_FOR_CANONICAL_REMOTE_OPERATOR_SURFACE"
echo "DIRECT_REMOTE_BYPASS_POLICY_SOURCE=DEPLOYMENT_NETWORK_AND_ORIGIN_CONFIGURATION"
echo "NON_PRODUCTION_VALIDATION_PATH_SOURCE=REPOSITORY_AND_DEPLOYMENT_VALIDATION_DESIGN"

echo
echo "=== REPOSITORY CAN ESTABLISH LOCALLY ==="
echo "REPOSITORY_CAN_ESTABLISH_CANONICAL_HOST=YES"
echo "REPOSITORY_CAN_ESTABLISH_CANONICAL_TUNNEL=YES"
echo "REPOSITORY_CAN_ESTABLISH_EXECUTION_ROUTE_CURRENTLY_UNMOUNTED=YES"
echo "REPOSITORY_CAN_ESTABLISH_TEAM_DOMAIN=NO"
echo "REPOSITORY_CAN_ESTABLISH_ACCESS_AUDIENCE_TAG=NO"
echo "REPOSITORY_CAN_CHOOSE_ALLOWED_OPERATOR_IDENTITY_WITHOUT_USER_INPUT=NO"
echo "REPOSITORY_CAN_ESTABLISH_LIVE_ACCESS_POLICY=NO"

echo
echo "=== USER / INFRASTRUCTURE OWNED INPUTS ==="
echo "INPUT_1_TEAM_DOMAIN=READ_FROM_CLOUDFLARE_ZERO_TRUST"
echo "INPUT_2_APPLICATION_AUDIENCE_TAG=READ_FROM_ACCESS_APPLICATION_AFTER_OR_DURING_CONFIGURATION"
echo "INPUT_3_ALLOWED_OPERATOR_IDENTITY=EXPLICIT_USER_POLICY_INPUT_REQUIRED"
echo "INPUT_4_ACCESS_POLICY_SCOPE=EXPLICIT_USER_ARCHITECTURAL_INPUT_REQUIRED"
echo "INPUT_5_BYPASS_POLICY=INFRASTRUCTURE_CONFIGURATION_EVIDENCE_REQUIRED"
echo "INPUT_6_VALIDATION_PATH=COLLABORATIVE_DESIGN_REQUIRED"

echo
echo "=== NON-INFERENCE RULES ==="
echo "DO_NOT_DERIVE_TEAM_DOMAIN_FROM_marketingmother.org=YES"
echo "DO_NOT_DERIVE_TEAM_DOMAIN_FROM_TUNNEL_UUID=YES"
echo "DO_NOT_INVENT_ACCESS_AUDIENCE_TAG=YES"
echo "DO_NOT_INVENT_OPERATOR_EMAIL=YES"
echo "DO_NOT_ASSUME_WHOLE_SITE_POLICY_SCOPE=YES"
echo "DO_NOT_ASSUME_ORIGIN_BYPASS_IS_BLOCKED=YES"
echo "DO_NOT_MOUNT_EXECUTION_AUTHORIZATION_ROUTE_FOR_TESTING=YES"

echo
echo "=== MINIMUM NEXT EVIDENCE NEEDED ==="
echo "EVIDENCE_1=AUTHORITATIVE_CLOUDFLARE_TEAM_DOMAIN"
echo "EVIDENCE_2=INTENDED_ALLOWED_OPERATOR_IDENTITY"
echo "EVIDENCE_3=INTENDED_ACCESS_POLICY_SCOPE_FOR_ui.marketingmother.org"
echo "EVIDENCE_4=ORIGIN_BYPASS_CONFIGURATION_OR_PROVABLE_BOUNDARY"
echo "EVIDENCE_5=SAFE_NON_EXECUTION_VALIDATION_TARGET"

echo
echo "=== CORRIDOR STATUS ==="
echo "UNIT_A_CONFIGURATION_SOURCE_OF_TRUTH_CLASSIFIED=YES"
echo "UNIT_A_IMPLEMENTATION_READINESS=BLOCKED_ON_EXTERNAL_AND_USER_OWNED_INPUTS"
echo "UNIT_A_CORRIDOR_CLOSED=NO"
echo "NEXT_ACTION=COLLECT_AUTHORITATIVE_EXTERNAL_AND_USER_OWNED_INPUTS_BEFORE_IMPLEMENTATION_READINESS_REVIEW"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "AUTHENTICATION_IS_NOT_EXECUTION_APPROVAL=YES"
echo "AUTHENTICATION_IS_NOT_GIT_AUTHORITY=YES"
echo "CLIENT_SUPPLIED_ACTOR_REMAINS_UNTRUSTED=YES"
echo "MATILDA_SELF_APPROVAL=PROHIBITED"
echo "CADE_SELF_APPROVAL=PROHIBITED"
echo "GENERIC_MUTATION_AUTHORITY=DISABLED"
echo "GENERIC_SHELL_AUTHORITY=DISABLED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=DISABLED"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_DNS_CHANGE=YES"
echo "NO_TUNNEL_CHANGE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
