#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== INSPECT PACKAGE SEMANTICS LIVE REVALIDATION SEAMS AFTER RG ERROR ==="
echo "RECOVERY_POINT=DR_20260826_111719"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "PRIOR_INSPECTION_FAILURE=RG_REGEX_PARSE_ERROR"
echo "FAILURE_CLASS=MECHANICAL_INSPECTION_COMMAND_ERROR"
echo "PACKAGE_SEMANTICS_SOURCE_CHANGE=NONE"

echo
echo "=== EXISTING VALIDATION GENERATION SEED REFERENCES ==="
rg -n -C 5 'validationGenerationSeed' scripts || true

echo
echo "=== EXISTING FIXED SEED REFERENCES ==="
rg -n -C 5 '424242' scripts || true

echo
echo "=== EXISTING UNSEEDED RUNNER REFERENCES ==="
rg -n -C 5 'unseeded' scripts || true

echo
echo "=== EXISTING FIXTURE REFERENCES ==="
rg -n -C 5 'fixture' scripts || true

echo
echo "=== EXISTING OLLAMA CALL REFERENCES ==="
rg -n -C 5 -F 'ollamaChat(' scripts || true

echo
echo "=== PARSED SUPPORT OBSERVER REFERENCES ==="
rg -n -C 8 'observeParsedSupportSourceReferences' \
  scripts/utils/ollamaChat.ts \
  scripts/utils/ollamaChat.support-validation-observer.test.ts \
  || true

echo
echo "=== PACKAGE SEMANTICS PARSE / RETURN REGION ==="
sed -n '787,860p' scripts/utils/ollamaChat.ts
sed -n '1380,1405p' scripts/utils/ollamaChat.ts

echo
echo "=== REVALIDATION CLASSIFICATION TARGET ==="
echo "QUESTION_1=DOES_EXISTING_DIAGNOSTIC_SEED_ALLOW_BOUNDED_AUTHORSHIP_OBSERVATION_WITHOUT_PRODUCTION_POLICY_CLAIM"
echo "QUESTION_2=DOES_EXISTING_OBSERVER_SEAM_EXPOSE_PARSED_OUTPUT_BEFORE_SUPPORT_PROVENANCE_REJECTION"
echo "QUESTION_3=IS_THERE_ALREADY_A_RUNNER_OR_FIXTURE_APPROPRIATE_FOR_PACKAGE_SEMANTICS_AUTHORSHIP_REVALIDATION"
echo "QUESTION_4=CAN_LIVE_PRODUCTION_REVALIDATION_REMAIN_SEPARATE_FROM_DIAGNOSTIC_AUTHORSHIP_VALIDATION"
echo "WEAKEN_FAIL_CLOSED_VALIDATION=NO"
echo "ADD_PRODUCTION_RETRY=NO"
echo "PRODUCTION_SAMPLING_POLICY_CHANGE=NO"
echo "NEXT_ACTION=SELECT_EXISTING_VALIDATION_SEAM_ONLY_AFTER_THIS_OUTPUT_IDENTIFIES_ONE_UNAMBIGUOUSLY"

git diff --check
