#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== INSPECT MISSION CONTROL MILESTONE SCOPE ==="
echo "MILESTONE=MISSION_CONTROL_PROJECT_CONTEXT_ALIGNMENT"
echo "CLOSED_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "POST_PHASE_DR=20260825_143436"
echo "IMPLEMENTATION_AUTHORIZED=NO"

rg -n -C 4 \
  'PROJECT_SCOPED_MISSION_CONTROL_RUNTIME_IMPLEMENTATION|MISSION_CONTROL_PROJECT_CONTEXT_ALIGNMENT|milestone.*closure|milestone.*complete|runtime implementation' \
  docs scripts \
  2>/dev/null || true

echo "NEXT_ACTION=CLASSIFY_RUNTIME_IMPLEMENTATION_REQUIREMENT_OR_MILESTONE_CLOSURE"
