#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== PACKAGES VS APPROVALS UI INSPECTION ==="
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== PACKAGES REACT SHAPE ==="
echo "WORKSPACE=client/src/packages/PackagesWorkspace.tsx"
echo "LAYOUT=HEADER_PLUS_NOTICE_PLUS_TWO_PANEL_LIST_AND_DETAIL"
echo "VISUAL_DENSITY=LOWER"
echo "PRIMARY_INTERACTION=SELECT_PACKAGE_THEN_READ_DETAIL"
echo "DETAIL_PRESENTATION=COMPACT"
echo "LIST_PRESENTATION=TITLE_SUMMARY_STATUS_UPDATED"
echo "WHY_IT_FEELS_CLEANER=FEWER_NESTED_SECTIONS_AND_FEWER_SIMULTANEOUS_DECISION_CONTROLS"

echo
echo "=== APPROVALS REACT SHAPE ==="
echo "WORKSPACE=client/src/approvals/ApprovalsWorkspace.tsx"
echo "LAYOUT=EXECUTIVE_INBOX_PLUS_ARTIFACT_SWITCHER_PLUS_LONG_EXECUTIVE_BRIEFING_PLUS_DECISION_ACTIONS"
echo "VISUAL_DENSITY=HIGHER"
echo "PRIMARY_INTERACTION=REVIEW_AND_DECIDE"
echo "DETAIL_PRESENTATION=LONG_FORM"
echo "WHY_IT_FEELS_BUSIER=MANY_STACKED_BRIEFING_SECTIONS_PLUS_STATE_TRANSITION_PLUS_EVIDENCE_PLUS_TECHNICAL_DETAILS_PLUS_DECISION_CONTROLS"

echo
echo "=== UX DIRECTION ==="
echo "PACKAGES_AND_APPROVALS_FUNCTIONALLY_OVERLAP=YES_AT_REVIEW_SURFACE_LEVEL"
echo "APPROVALS_HAS_ADDITIONAL_REQUIRED_CAPABILITY=YES_DECISION_ACTION"
echo "PACKAGES_VISUAL_SHELL_WORTH_PRESERVING=YES"
echo "REMOVE_PACKAGES_TAB_NOW=NOT_YET_AUTHORIZED"
echo "PREFERRED_DIRECTION=KEEP_APPROVALS_CAPABILITY_BUT_RECOMPOSE_IT_USING_PACKAGES_VISUAL_HIERARCHY"
echo "DO_NOT_LOSE=APPROVE_ACTION"
echo "DO_NOT_LOSE=AUTHORITY_BOUNDARY"
echo "DO_NOT_LOSE=DECISION_RELEVANT_SCOPE_AND_CONSTRAINT_INFORMATION"
echo "LIKELY_SIMPLIFY=TECHNICAL_IDS"
echo "LIKELY_SIMPLIFY=RAW_EVIDENCE_IDS"
echo "LIKELY_SIMPLIFY=REPEATED_STATUS_AND_STATE_LANGUAGE"
echo "LIKELY_COLLAPSE=LOW_PRIORITY_TECHNICAL_METADATA"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=REVIEW_APPROVAL_DETAIL_INFORMATION_FIELD_BY_FIELD_AND_CLASSIFY_EACH_AS_PRIMARY_DECISION_INFORMATION_SECONDARY_CONTEXT_TECHNICAL_DETAIL_OR_REMOVABLE_REDUNDANCY"
