#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== INSPECT EXACT CLOUDFLARE ACCESS UNIT A CONFIGURATION INPUTS ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="8b7213e10"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED UNIT ORDER ==="
echo "UNIT_A=CLOUDFLARE_ACCESS_APPLICATION_AND_POLICY"
echo "UNIT_B=SERVER_VERIFIED_OPERATOR_IDENTITY_VALIDATOR"
echo "UNIT_A_BEFORE_UNIT_B=REQUIRED"
echo "UNIT_B_BEFORE_EXECUTION_AUTHORIZATION_ROUTE_MOUNT=REQUIRED"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== CANONICAL REMOTE HOST EVIDENCE ==="
git grep -n -I -E \
  'ui\.marketingmother\.org|marketingmother\.org|ui-server' \
  -- \
  tools \
  server \
  docs \
  ops \
  Motherboard_Project_Scope.txt \
  2>/dev/null \
  | sed -n '1,800p' || true

echo
echo "=== LOCAL CLOUDFLARED ui-server CONFIG — NONSECRET FIELDS ONLY ==="
if [[ -f "${HOME}/.cloudflared/ui-server.yml" ]]; then
  grep -E '^[[:space:]]*(tunnel|hostname|service):' "${HOME}/.cloudflared/ui-server.yml" || true
else
  echo "UI_SERVER_CONFIG_PRESENT=NO"
fi

echo
echo "=== CLOUDFLARE ACCOUNT / TEAM DOMAIN ENVIRONMENT NAMES ONLY ==="
env | cut -d= -f1 \
  | grep -E '^(CF_|CLOUDFLARE_|ACCESS_)' \
  | sort \
  || true

echo
echo "=== SEARCH REPOSITORY FOR TEAM DOMAIN / ACCESS AUDIENCE REFERENCES ==="
git grep -n -I -E \
  'team domain|team_domain|TEAM_DOMAIN|audience tag|audience_tag|AUDIENCE_TAG|CF_ACCESS_AUD|CLOUDFLARE_ACCESS_AUD|Cf-Access-Jwt-Assertion|cdn-cgi/access/certs' \
  -- . \
  | sed -n '1,800p' || true

echo
echo "=== CLOUDFLARE ACCESS LOCAL CONFIG SURFACE INVENTORY ==="
if [[ -d "${HOME}/.cloudflared" ]]; then
  find "${HOME}/.cloudflared" -maxdepth 2 -type f \
    \( -name '*.yml' -o -name '*.yaml' -o -name '*.json' \) \
    -print \
    | sed "s#${HOME}#~#" \
    | sort
else
  echo "CLOUDFLARED_CONFIG_DIRECTORY_PRESENT=NO"
fi

echo
echo "=== UNIT A REQUIRED INPUTS ==="
echo "INPUT_1_CANONICAL_REMOTE_HOST=ui.marketingmother.org"
echo "INPUT_2_CANONICAL_TUNNEL=ui-server"
echo "INPUT_3_TEAM_DOMAIN=UNRESOLVED"
echo "INPUT_4_APPLICATION_AUDIENCE_TAG=UNRESOLVED"
echo "INPUT_5_ALLOWED_OPERATOR_IDENTITY=UNRESOLVED"
echo "INPUT_6_ACCESS_POLICY_SCOPE=UNRESOLVED"
echo "INPUT_7_DIRECT_REMOTE_BYPASS_POLICY=UNRESOLVED"
echo "INPUT_8_NON_PRODUCTION_VALIDATION_PATH=UNRESOLVED"

echo
echo "=== DECISION RULE ==="
echo "IF_TEAM_DOMAIN_AND_AUDIENCE_AND_OPERATOR_POLICY_ARE_OBSERVED=CLASSIFY_UNIT_A_IMPLEMENTATION_READINESS"
echo "IF_ANY_REQUIRED_INPUT_REMAINS_UNRESOLVED=STOP_BEFORE_CLOUDFLARE_ACCESS_CONFIGURATION"
echo "DO_NOT_GUESS_TEAM_DOMAIN=YES"
echo "DO_NOT_GUESS_AUDIENCE_TAG=YES"
echo "DO_NOT_GUESS_OPERATOR_EMAIL_OR_IDENTITY=YES"
echo "DO_NOT_CREATE_ACCESS_POLICY_WITHOUT_EXPLICIT_SCOPE=YES"
echo "DO_NOT_CHANGE_TUNNEL_OR_DNS=YES"

echo
echo "=== SECURITY SEPARATION ==="
echo "CLOUDFLARE_ACCESS_AUTHENTICATION_IS_NOT_EXECUTION_APPROVAL=YES"
echo "CLOUDFLARE_ACCESS_AUTHENTICATION_IS_NOT_GIT_AUTHORITY=YES"
echo "SERVER_IDENTITY_VALIDATION_REMAINS_UNIT_B=YES"
echo "DURABLE_EXECUTION_APPROVAL_REMAINS_LATER_UNIT=YES"
echo "ACTIVE_REPOSITORY_ENABLEMENT_REMAINS_LATER_UNIT=YES"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_UNIT_A_IMPLEMENTATION_READINESS_FROM_OBSERVED_CONFIGURATION_INPUTS"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_DNS_CHANGE=YES"
echo "NO_TUNNEL_CHANGE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
