#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== APPROVALS LIVE VISUAL REVIEW READY ==="
echo "BASELINE_COMMIT=2cc559a1"
echo "CLIENT_BUILD=PASS"
echo "LEGACY_ARTIFACT_SWITCHER=REMOVED"
echo "OBSOLETE_NAVIGATION=REMOVED"
echo "PACKAGES_TAB_REMOVAL_AUTHORIZED=NO"
echo "FURTHER_IMPLEMENTATION_AUTHORIZED=NO_UNTIL_VISUAL_REVIEW"

echo
echo "=== WORKING TREE NOTE ==="
echo "TRACKED_DRIFT=NONE_EXPECTED"
echo "UNTRACKED_RECOVERY_ARTIFACTS=INTENTIONALLY_PRESERVED"
echo "UNTRACKED_IMPLEMENTATION_SCRIPTS=LOCAL_ONLY"

echo
echo "NEXT_ACTION=USER_OPENS_APPROVALS_AND_PACKAGES_AND_RETURNS_SCREENSHOTS_OR_VISUAL_FEEDBACK"
