#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== PRESENT BOUNDED PROJECT-SCOPED DELEGATION IMPLEMENTATION UNIT ==="

echo
echo "=== BASELINE ==="
printf "HEAD=" && git rev-parse --short=8 HEAD
printf "BRANCH=" && git branch --show-current
git status --short

echo
echo "=== VERIFIED CLASSIFICATION INPUT ==="
echo "DATABASE_ENFORCED_PROJECT_SCOPED_DELEGATION=SCHEMA_FEASIBLE"
echo "REQUIRED_PARENT_ADDITION=UNIQUE_INDEX_ON_PROJECT_ID_PACKAGE_ID_PACKAGE_VERSION"
echo "REQUIRED_DELEGATION_ADDITION=PROJECT_ID"
echo "REQUIRED_NEW_DELEGATION_FK=(project_id,package_id,package_version)"
echo "CANONICAL_PACKAGE_PRIMARY_KEY_CHANGE_REQUIRED=NO"
echo "CANONICAL_PACKAGE_PROJECT_ID_NOT_NULL_MIGRATION_REQUIRED=NO"
echo "HISTORICAL_CANONICAL_PACKAGE_MUTATION_REQUIRED=NO"
echo "HISTORICAL_DELEGATION_REPARENTING_REQUIRED=NO"
echo "APPLICATION_ONLY_PROJECT_SCOPE_CHECK_PREFERRED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== BOUNDED IMPLEMENTATION UNIT ==="
echo "UNIT_NAME=PROJECT_SCOPED_DELEGATION_REFERENCE"
echo "PURPOSE=EXTEND_EXISTING_DELEGATION_REFERENCE_TO_INCLUDE_DATABASE_ENFORCED_PROJECT_OWNERSHIP"
echo "AUTHORITY_SEMANTICS=UNCHANGED"
echo "NEW_AUTHORITY_INTRODUCED=NO"

echo
echo "=== SCHEMA UNIT ==="
echo "CHANGE_1=ADD_UNIQUE_INDEX_ON_matilda_canonical_packages(project_id,package_id,package_version)"
echo "CHANGE_2=ADD_project_id_TO_governance_delegations"
echo "CHANGE_3=REBUILD_governance_delegations_WITH_COMPOSITE_FK(project_id,package_id,package_version)"
echo "PROJECT_ID_FOREIGN_KEY_TO_PROJECT_REGISTRY=RECOMMENDED_IF_MIGRATION_CAN_PRESERVE_CURRENT_HISTORICAL_TRUTH"
echo "CANONICAL_PRIMARY_KEY_CHANGE=NO"
echo "CANONICAL_PROJECT_ID_NOT_NULL_CHANGE=NO"

echo
echo "=== RUNTIME UNIT ==="
echo "CHANGE_4=ADD_project_id_TO_CreateGovernanceDelegationInput"
echo "CHANGE_5=ADD_project_id_TO_CreatedGovernanceDelegation"
echo "CHANGE_6=TRANSPORT_project_id_THROUGH_PRODUCTION_DELEGATION_CONSUMER"
echo "CHANGE_7=TRANSPORT_project_id_THROUGH_PRODUCTION_DELEGATION_ENTRY_POINT"
echo "CHANGE_8=VALIDATE_CANONICAL_PACKAGE_BY_project_id_package_id_package_version"
echo "CHANGE_9=PERSIST_project_id_ON_NEW_DELEGATION_ROWS"

echo
echo "=== FAIL-CLOSED CONTRACT ==="
echo "REQUIRE_project_id=YES"
echo "REQUIRE_package_id=YES"
echo "REQUIRE_package_version=YES"
echo "REQUIRE_CANONICAL_PACKAGE_EXISTS=YES"
echo "REQUIRE_CANONICAL_PACKAGE_PROJECT_MATCH=YES"
echo "REQUIRE_EXPLICIT_AUTHORIZATION_STATE=YES"
echo "REQUIRE_EXPLICIT_DELEGATED_BY=YES"
echo "ON_PROJECT_PACKAGE_MISMATCH=REJECT"
echo "ON_MISSING_CANONICAL_ROOT=REJECT"
echo "ON_INVALID_PROJECT_SCOPE=REJECT"

echo
echo "=== HISTORICAL PRESERVATION ==="
echo "LEGACY_CORRIDOR_SMOKE_DELEGATION_MUTATION=NO"
echo "LEGACY_CORRIDOR_SMOKE_REPARENTING=NO"
echo "HISTORICAL_CANONICAL_PACKAGE_BACKFILL=NO"
echo "HISTORICAL_TRUTH_PRESERVED=YES"
echo "NEW_PROJECT_SCOPED_ENFORCEMENT_APPLIES_TO_NEW_CANONICAL_DELEGATIONS=YES"

echo
echo "=== DOWNSTREAM CONTAINMENT ==="
echo "VALIDATION_CHANGE=NONE"
echo "ENVELOPE_GATE_CHANGE=NONE"
echo "ENVELOPE_CHANGE=NONE"
echo "MISSION_READ_CHANGE=NONE"
echo "OPERATIONAL_INTAKE_CHANGE=NONE"
echo "ROUTING_CHANGE=NONE"
echo "ASSIGNMENT_CHANGE=NONE"
echo "EXECUTION_CHANGE=NONE"

echo
echo "=== REQUIRED VALIDATION IF AUTHORIZED ==="
echo "VALIDATE_1=TYPECHECK"
echo "VALIDATE_2=DELEGATION_UNIT_TESTS"
echo "VALIDATE_3=PROJECT_MATCH_ACCEPTED"
echo "VALIDATE_4=CROSS_PROJECT_PACKAGE_REFERENCE_REJECTED"
echo "VALIDATE_5=MISSING_PROJECT_REJECTED"
echo "VALIDATE_6=EXISTING_CANONICAL_ROOT_REQUIREMENT_PRESERVED"
echo "VALIDATE_7=NO_NEW_DOWNSTREAM_AUTHORITY"
echo "VALIDATE_8=TARGETED_FOREIGN_KEY_CHECK"
echo "VALIDATE_9=KNOWN_PREEXISTING_DOWNSTREAM_FK_DEFECT_REMAINS_SEPARATELY_CLASSIFIED"

echo
echo "=== ROLLBACK BOUNDARY ==="
echo "ROLLBACK_UNIT=PROJECT_SCOPED_DELEGATION_SCHEMA_AND_RUNTIME_EXTENSION_ONLY"
echo "ROLLBACK_MUST_NOT_TOUCH_CANONICAL_PACKAGE_CONTENT=YES"
echo "ROLLBACK_MUST_NOT_TOUCH_VALIDATION_GATE_ENVELOPE=YES"
echo "ROLLBACK_MUST_NOT_TOUCH_MISSION_CONTROL=YES"

echo
echo "=== IMPLEMENTATION AUTHORIZATION GATE ==="
echo "IMPLEMENTATION_UNIT=READY_BOUNDED"
echo "IMPLEMENTATION_STARTED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION_BEFORE_IMPLEMENTING_THIS_UNIT"
