#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== PROPOSE APPROVALS RIGHT-PANEL STRUCTURE ==="
echo "BASELINE_COMMIT=978a286b"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== ALWAYS VISIBLE ==="
echo "HEADER=TITLE_PLUS_SINGLE_NEEDS_REVIEW_BADGE"
echo "SUMMARY=OBJECTIVE"
echo "APPROVAL_EFFECT=LIVING_DRAFT_TO_CANONICAL_PACKAGE"
echo "EXPECTED_OUTCOME=VISIBLE"
echo "PROPOSED_WORK=VISIBLE"
echo "DELIVERABLES=VISIBLE_IF_PRESENT"
echo "SCOPE=IN_SCOPE_PLUS_OUT_OF_SCOPE"
echo "CONSTRAINTS=VISIBLE_IF_PRESENT"
echo "OPEN_QUESTIONS=VISIBLE_IF_PRESENT"
echo "DECISION_ACTIONS=APPROVE_PLUS_REQUEST_CHANGES"

echo
echo "=== COLLAPSED BY DEFAULT ==="
echo "TECHNICAL_DETAILS=YES"
echo "TECHNICAL_DETAIL=APPROVAL_REQUEST_ID"
echo "TECHNICAL_DETAIL=DRAFT_PACKAGE_ID"
echo "TECHNICAL_DETAIL=CONVERSATION_ID"
echo "TECHNICAL_DETAIL=LINEAGE_ID"
echo "TECHNICAL_DETAIL=SUPPORTING_EVIDENCE_IDS"
echo "TECHNICAL_DETAIL=SOURCE_DRAFT_STATUS"

echo
echo "=== REMOVE FROM PRIMARY COMPOSITION ==="
echo "REMOVE=TOP_ARTIFACT_SWITCHER"
echo "REMOVE=SECOND_PENDING_BADGE"
echo "REMOVE=REPEATED_APPROVE_CANONICAL_PACKAGE_LABELS"
echo "REMOVE=PROMINENT_SELECTED_ARTIFACT_ID_NOTICE"
echo "REMOVE=SEPARATE_EXECUTIVE_QUESTION_IF_REDUNDANT_WITH_APPROVAL_EFFECT"
echo "REMOVE=REPEATED_AUTHORITY_BOUNDARY_COPY"

echo
echo "=== VISUAL STRUCTURE ==="
echo "SHELL=PACKAGES_STYLE_TWO_PANEL_LAYOUT"
echo "LEFT_PANEL=APPROVAL_QUEUE_USING_COMPACT_PACKAGE_STYLE_CARDS"
echo "RIGHT_PANEL=SPACIOUS_DECISION_BRIEF"
echo "SECTION_COUNT=MINIMIZED"
echo "NESTED_BORDERS=MINIMIZED"
echo "TECHNICAL_METADATA=ONE_DISCLOSURE_AT_BOTTOM"
echo "DECISION_ACTIONS=VISIBLE_BEFORE_TECHNICAL_DISCLOSURE"
echo
echo "NEXT_ACTION=USER_REVIEW_OF_THIS_EXACT_VISIBLE_VS_COLLAPSED_STRUCTURE_BEFORE_IMPLEMENTATION_AUTHORIZATION"
