#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== RECONCILE CONFIRMED DELEGATION PERSISTENCE BINDING DEFECT ==="

echo
echo "=== VERIFIED DEFECT ==="
echo "SQL_REQUIRES_PROJECT_ID=YES"
echo "RUN_BINDING_INCLUDES_PROJECT_ID=NO"
echo "PERSISTENCE_BINDING_DEFECT=CONFIRMED"
echo "TYPECHECK_DETECTION=NO"
echo "EXISTING_TARGETED_TESTS_USE_INJECTED_PERSISTENCE=YES"

echo
echo "=== SCOPE ==="
echo "DEFECT_LOCATION=db/governance-runtime.ts:createGovernanceDelegation"
echo "MINIMUM_CODE_FIX=ADD_PROJECT_ID_TO_EXISTING_SQL_BINDING_OBJECT"
echo "SCHEMA_CHANGE_REQUIRED=NO"
echo "MIGRATION_CHANGE_REQUIRED=NO"
echo "ROUTE_CONTRACT_CHANGE_REQUIRED=NO"
echo "ENTRY_POINT_CONTRACT_CHANGE_REQUIRED=NO"
echo "CONSUMER_CONTRACT_CHANGE_REQUIRED=NO"
echo "DOWNSTREAM_LEGACY_ROOT_DEFECT_REOPENED=NO"

echo
echo "=== REQUIRED VALIDATION BEFORE RECLOSURE ==="
echo "VALIDATION_1=TYPECHECK"
echo "VALIDATION_2=EXISTING_DELEGATION_TARGETED_TESTS"
echo "VALIDATION_3=DIRECT_CREATE_GOVERNANCE_DELEGATION_PERSISTENCE_TEST"
echo "VALIDATION_4=VERIFY_PROJECT_ID_PERSISTED"
echo "VALIDATION_5=VERIFY_CROSS_PROJECT_REFERENCE_REJECTED"

echo
echo "=== CORRIDOR STATE RECONCILIATION ==="
echo "PROJECT_SCOPED_DELEGATION_PREVIOUS_CLOSURE=REOPENED_FOR_BOUNDED_DEFECT_CORRECTION"
echo "LIVE_PROJECT_SCOPED_SCHEMA=REMAINS_ACTIVE"
echo "LIVE_MIGRATION_RESULT=NOT_REVERTED"
echo "HISTORICAL_UNROOTED_DELEGATION_PRESERVATION=NOT_INVALIDATED"
echo "PACKAGE_HANDOFF_CONTRACT_INVESTIGATION=PAUSED"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "NEXT_ACTION=AUTHORIZE_MINIMUM_BINDING_FIX_AND_DIRECT_PERSISTENCE_REGRESSION_TEST"
