#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== RECORD UNIT A EXTERNAL INPUT COLLECTION STATUS ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

EXPECTED_HEAD_PREFIX="47952d2be"
CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED CHECKPOINT ==="
echo "CHECKPOINT_COMMIT=47952d2befcaf510091f62f9a2e0b68987743f59"
echo "UNIT_A_SOURCE_OF_TRUTH_CORRIDOR=CLOSED"
echo "UNIT_A_EXTERNAL_INPUT_COLLECTION_CORRIDOR=ACTIVE"

echo
echo "=== REQUIRED EXTERNAL FACTS ==="
echo "TEAM_DOMAIN=REQUIRED_FROM_CLOUDFLARE_ZERO_TRUST_ACCOUNT_STATE"
echo "APPLICATION_AUDIENCE_TAG=REQUIRED_FROM_CLOUDFLARE_ACCESS_APPLICATION_STATE"
echo "ORIGIN_BYPASS_BOUNDARY=REQUIRES_DEPLOYMENT_EVIDENCE"

echo
echo "=== REQUIRED USER DECISIONS ==="
echo "ALLOWED_OPERATOR_IDENTITY_POLICY=UNSELECTED"
echo "ACCESS_POLICY_SCOPE=UNSELECTED"
echo "NO_DEFAULT_SELECTION_MAY_BE_INFERRED=YES"

echo
echo "=== REQUIRED ENGINEERING DESIGN ==="
echo "SAFE_NON_EXECUTION_VALIDATION_TARGET=UNDESIGNED"
echo "EXECUTION_AUTHORIZATION_ROUTE_MUST_REMAIN_UNMOUNTED=YES"
echo "LOCAL_EXECUTION_AUTHORIZATION_REMAINS_DISABLED=YES"

echo
echo "=== CURRENT DETERMINATION ==="
echo "REPOSITORY_DISCOVERY_COMPLETE_FOR_EXTERNAL_VALUES=YES"
echo "UNIT_A_IMPLEMENTATION_READY=NO"
echo "IMPLEMENTATION_READINESS_REVIEW_ALLOWED=NO"
echo "NEXT_ACTION=COLLECT_AUTHORITATIVE_EXTERNAL_FACTS_AND_EXPLICIT_USER_POLICY_DECISIONS"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "AUTHENTICATION_IS_NOT_EXECUTION_APPROVAL=YES"
echo "AUTHENTICATION_IS_NOT_GIT_AUTHORITY=YES"
echo "CLIENT_SUPPLIED_ACTOR_REMAINS_UNTRUSTED=YES"
echo "MATILDA_SELF_APPROVAL=PROHIBITED"
echo "CADE_SELF_APPROVAL=PROHIBITED"
echo "GENERIC_MUTATION_AUTHORITY=DISABLED"
echo "GENERIC_SHELL_AUTHORITY=DISABLED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=DISABLED"

echo
echo "=== SAFETY ==="
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_DNS_CHANGE=YES"
echo "NO_TUNNEL_CHANGE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
