#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== RECORD PACKAGE SEMANTICS VALUE FIDELITY DECISION GATE ==="
echo "EXPECTED_HEAD_PREFIX=995af9aaf"
echo "RECOVERY_POINT=DR_20260826_111719"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 995af9aaf* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED ARCHITECTURAL FINDING ==="
echo "CURRENT_WORKFLOW_INPUT=RAW_MESSAGE_ONLY"
echo "TYPED_USER_PACKAGE_SEMANTICS_INPUT=ABSENT"
echo "DETERMINISTIC_EXPLICIT_FIELD_VALUE_FIDELITY_WITH_CURRENT_INPUT_MODEL=NO"
echo "PROMPT_ONLY_GUARANTEE=NO"
echo "HEURISTIC_EXTRACTION_REQUIRED_IF_DERIVING_FIELDS_FROM_RAW_TEXT=YES"
echo "HEURISTIC_EXTRACTION_AUTHORIZED=NO"
echo "SECOND_OLLAMA_INVOCATION_AUTHORIZED=NO"

echo
echo "=== DECISION GATE ==="
echo "OPTION_A=ACCEPT_MODEL_LEVEL_SEMANTIC_FIDELITY_WITH_RAW_MESSAGE_ONLY"
echo "OPTION_B=REQUIRE_DETERMINISTIC_EXPLICIT_FIELD_FIDELITY_AND_DESIGN_OPTIONAL_TYPED_USER_PACKAGE_SEMANTICS_INPUT"
echo "OPTION_B_IS_AN_ARCHITECTURAL_CHANGE=YES"
echo "OPTION_B_IMPLEMENTATION_AUTHORIZED=NO"
echo "OPTION_A_OR_B_USER_SELECTION_REQUIRED=YES"

echo
echo "=== PRESERVED INVARIANTS ==="
echo "USER_INTENT_AUTHORITY=UNCHANGED"
echo "MATILDA_INTERPRETATION_AUTHORITY=UNCHANGED"
echo "LIVING_DRAFT_AUTHORITY=NON_AUTHORITATIVE"
echo "APPROVAL_TRANSITION=UNCHANGED"
echo "ONE_USER_MESSAGE_ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=UNCHANGED"
echo "SIDEBAR_COMPACTNESS=SEPARATE_FOLLOWUP"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=WAIT_FOR_USER_DECISION_BETWEEN_OPTION_A_AND_OPTION_B_BEFORE_DESIGN_OR_IMPLEMENTATION"

git diff --check

git add record-package-semantics-value-fidelity-decision-gate.sh
git commit -m "Record package semantics value fidelity decision gate"
git push
