#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== RECORD UNIT A EXTERNAL INPUT COLLECTION STATUS ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "CLOUDFLARE_ACCESS_CONFIGURATION_AUTHORIZED=NO"
echo "SERVER_IDENTITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXECUTION_AUTHORIZATION_ROUTE_MOUNT_AUTHORIZED=NO"

EXPECTED_HEAD_PREFIX="ebe5e3957"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED REMOTE CHECKPOINT ==="
echo "CHECKPOINT_COMMIT=ebe5e395797476880af56ad4bb33f595b20bd31d"
echo "CHECKPOINT_MESSAGE=Record Unit A external input collection status"
echo "UNIT_A_SOURCE_OF_TRUTH_CORRIDOR=CLOSED"
echo "UNIT_A_EXTERNAL_INPUT_COLLECTION_CORRIDOR=ACTIVE"

echo
echo "=== CURRENT BLOCKERS ==="
echo "AUTHORITATIVE_CLOUDFLARE_TEAM_DOMAIN=MISSING"
echo "ACCESS_APPLICATION_AUDIENCE_TAG=MISSING_OR_NOT_YET_CREATED"
echo "ALLOWED_OPERATOR_IDENTITY_POLICY=UNSELECTED"
echo "ACCESS_POLICY_SCOPE=UNSELECTED"
echo "ORIGIN_BYPASS_BOUNDARY=UNVERIFIED"
echo "SAFE_NON_EXECUTION_VALIDATION_TARGET=UNDESIGNED"

echo
echo "=== NEXT REQUIRED INTERACTION ==="
echo "NEXT_ACTION=OBTAIN_EXTERNAL_CLOUDFLARE_FACTS_AND_EXPLICIT_USER_POLICY_DECISIONS"
echo "REPOSITORY_DISCOVERY_COMPLETE_FOR_EXTERNAL_VALUES=YES"
echo "IMPLEMENTATION_READINESS_REVIEW_ALLOWED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== PRESERVED BOUNDARIES ==="
echo "AUTHENTICATION_IS_NOT_EXECUTION_APPROVAL=YES"
echo "AUTHENTICATION_IS_NOT_GIT_AUTHORITY=YES"
echo "EXECUTION_AUTHORIZATION_ROUTE_MUST_REMAIN_UNMOUNTED=YES"
echo "LOCAL_EXECUTION_AUTHORIZATION_REMAINS_DISABLED=YES"
echo "GENERIC_MUTATION_AUTHORITY=DISABLED"
echo "GENERIC_SHELL_AUTHORITY=DISABLED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=DISABLED"

echo
echo "=== SAFETY ==="
echo "NO_PRODUCTION_FILE_EDIT=YES"
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_DNS_CHANGE=YES"
echo "NO_TUNNEL_CHANGE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
echo "NO_REMOTE_RUNTIME_WRITE=YES"
