#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== RECONCILE NEXT CANONICAL PHASE OR MILESTONE ==="
echo "CURRENT_MILESTONE=MISSION_CONTROL_PROJECT_CONTEXT_ALIGNMENT"
echo "CLOSED_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "PHASE_CLOSURE_COMMIT=18de0d2a"
echo "POST_PHASE_DR=20260825_143436"
echo "POST_PHASE_DR_COMMIT=8536f37d"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== VERIFY CURRENT REPOSITORY STATE ==="
git status --short

echo
echo "=== SEARCH CANONICAL MILESTONE / PHASE DOCUMENTATION ==="
rg -n -C 10 \
  'MISSION_CONTROL_PROJECT_CONTEXT_ALIGNMENT|AUTHORITATIVE_MISSION_PACKAGE_HANDOFF|PROJECT_SCOPED_MISSION_READ_RUNTIME|phase|corridor|milestone' \
  . \
  -g '*.md' \
  -g '*.txt' \
  -g '*.sh' \
  -g '!node_modules/**' \
  -g '!.git/**' \
  2>/dev/null || true

echo
echo "=== SEARCH SUCCESSOR / DEFERRED SCOPE SIGNALS ==="
rg -n -C 10 \
  'NEXT_PHASE|NEXT_MILESTONE|successor|deferred|remaining scope|future phase|phase closure|milestone closure' \
  . \
  -g '*.md' \
  -g '*.txt' \
  -g '*.sh' \
  -g '!node_modules/**' \
  -g '!.git/**' \
  2>/dev/null || true

echo
echo "=== RECONCILIATION QUESTIONS ==="
echo "QUESTION_1=DOES_REPOSITORY_EVIDENCE_DEFINE_A_SUCCESSOR_PHASE_WITHIN_MISSION_CONTROL_PROJECT_CONTEXT_ALIGNMENT"
echo "QUESTION_2=IF_NO_SUCCESSOR_PHASE_EXISTS_IS_THE_MILESTONE_ITSELF_CLOSURE_READY"
echo "QUESTION_3=DO_ANY_DEFERRED_ITEMS_REMAIN_IN_SCOPE_FOR_THIS_MILESTONE"
echo "QUESTION_4=ARE_ANY_REMAINING_ITEMS_EXPLICITLY_SEPARATE_FUTURE_MILESTONES"
echo "QUESTION_5=DOES_ANY_SUCCESSOR_REQUIRE_NEW_AUTHORITY_OR_RUNTIME_CAPABILITY"
echo "QUESTION_6=IS_ADDITIONAL_IMPLEMENTATION_AUTHORIZATION_REQUIRED"

echo
echo "=== CURRENT BOUNDARY ==="
echo "AUTHORITATIVE_MISSION_PACKAGE_HANDOFF_PHASE=CLOSED"
echo "ALL_FIVE_PHASE_CORRIDORS_CLOSED=YES"
echo "END_TO_END_HANDOFF_VALIDATION=PASS"
echo "MISSION_CONTROL_REMAINS_READ_ONLY_CONSUMER=YES"
echo "NEXT_PHASE=NOT_YET_ESTABLISHED"
echo "NEXT_MILESTONE=NOT_YET_ESTABLISHED"
echo "MILESTONE_CLOSURE_READY=NOT_YET_CLASSIFIED"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_SUCCESSOR_PHASE_OR_MILESTONE_CLOSURE_FROM_REPOSITORY_EVIDENCE_ONLY"
