#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== RECORD POST DECISIONS TITLE COMPACTNESS CHECKPOINT ==="
echo "EXPECTED_HEAD_PREFIX=86f805580"
echo "RECOVERY_POINT=DR_20260826_173929"
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

CURRENT_HEAD="$(git rev-parse HEAD)"
if [[ "${CURRENT_HEAD}" != 86f805580* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED CLOSED FOLLOWUP ==="
echo "DECISIONS_LIST_TITLE_COMPACTNESS_FOLLOWUP=CLOSED"
echo "CLOSURE_COMMIT=86f805580d07f2c3d7efc6ec7e40ff955547a072"
echo "IMPLEMENTATION_COMMIT=6af4a07a6aad0bd89aca7ed6fa86325841a3042f"
echo "VERIFICATION_COMMIT=4a5186575"
echo "RECOVERY_CHECKPOINT=DR_20260826_173929"
echo "MAX_DISPLAY_CHARACTERS=64"
echo "HEADING_MAX_LINES=2"
echo "FULL_EXPECTED_OUTCOME_IN_DETAIL=PRESERVED"
echo "PACKAGE_SEMANTICS_UNCHANGED=YES"
echo "APPROVAL_AUTHORITY_UNCHANGED=YES"
echo "FURTHER_TITLE_COMPACTNESS_IMPLEMENTATION_REQUIRED=NO"

echo
echo "=== CONTROL BOUNDARY ==="
echo "PACKAGE_SEMANTICS_CORRIDOR=CLOSED"
echo "AUTHORITATIVE_MISSION_PACKAGE_HANDOFF_PHASE=CLOSED"
echo "DECISIONS_TITLE_FOLLOWUP=CLOSED"
echo "CURRENT_NEXT_SCOPE=NOT_YET_CLASSIFIED"
echo "AUTOMATIC_IMPLEMENTATION=NO"
echo "NEXT_ACTION=IDENTIFY_NEXT_OPEN_FOLLOWUP_OR_CANONICAL_CORRIDOR_FROM_PARENT_SCOPE_BEFORE_IMPLEMENTATION"

git diff --check
git add record-post-decisions-title-compactness-checkpoint.sh
git commit -m "Record post decisions title compactness checkpoint"
git push
