#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== RECONCILE PROJECT-BOUND HANDOFF RUNTIME CONTRACT ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=PROJECT_BOUND_HANDOFF"
echo "PACKAGE_HANDOFF_CONTRACT_REMAINS_CLOSED=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== ESTABLISHED CURRENT RUNTIME ==="
echo "CANONICAL_AUTHORITY_ROOT=matilda_canonical_packages"
echo "CANONICAL_REQUIRED_STATUS=canonical_approved"
echo "CANONICAL_IDENTITY=project_id+package_id+package_version"
echo "MISSION_PACKAGE_PROJECTION_ROOT=governance_packages"
echo "MISSION_PACKAGE_PROJECTION_IS_DERIVED_READ_MODEL=YES"
echo "POST_APPROVAL_PROJECTION_RUNTIME=IMPLEMENTED"
echo "LIVE_EXISTING_CANONICAL_PACKAGE_PROJECTION=RECONCILED"
echo "DEDICATED_OPERATIONAL_PACKAGE_AUTHORITY_RUNTIME=ABSENT"
echo "MISSION_READ_REQUIRES_CALLER_SUPPLIED_PACKAGE_ID=YES"

echo
echo "=== MINIMUM WRITE CONTRACT ==="
echo "AUTHORITY_NAME=OPERATIONAL_PACKAGE_AUTHORITY"
echo "AUTHORITY_SCOPE=PROJECT_SCOPED"
echo "AUTHORITATIVE_BINDING=project_id+package_id+package_version"
echo "WRITE_INPUT=EXACT_project_id+package_id+package_version"
echo "WRITE_MUST_REQUIRE_EXISTING_CANONICAL_PACKAGE=YES"
echo "WRITE_MUST_REQUIRE_canonical_approved=YES"
echo "WRITE_MUST_REQUIRE_PROJECT_PACKAGE_OWNERSHIP_MATCH=YES"
echo "WRITE_MUST_REQUIRE_EXISTING_DERIVED_MISSION_PACKAGE_PROJECTION=YES"
echo "WRITE_MUST_PRESERVE_EXACT_PACKAGE_VERSION=YES"
echo "WRITE_MUST_NOT_SELECT_NEWEST_PACKAGE=YES"
echo "WRITE_MUST_NOT_ACCEPT_UI_SELECTION_AS_AUTHORITY=YES"
echo "WRITE_MUST_BE_EXPLICIT_AUTHORITY_EVENT=YES"
echo "ONE_ACTIVE_OPERATIONAL_PACKAGE_PER_PROJECT=YES"
echo "SUCCESSOR_VERSION_AUTO_ACTIVATION=NO"
echo "SAME_EXACT_BINDING_RETRY=IDEMPOTENT_SUCCESS"
echo "DIFFERENT_BINDING_FOR_SAME_PROJECT=EXPLICIT_REPLACEMENT_EVENT_REQUIRED"
echo "AUDIT_METADATA_REQUIRED=YES"

echo
echo "=== AUTHORITY NON-ESCALATION ==="
echo "CANONICAL_PACKAGE_MUTATION=NO"
echo "MISSION_PACKAGE_PROJECTION_MUTATION=NO"
echo "DELEGATION_CREATION=NO"
echo "VALIDATION_AUTHORITY=NO"
echo "ROUTING_AUTHORITY=NO"
echo "ASSIGNMENT_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "MISSION_CONTROL_SELECTION_AUTHORITY=NO"

echo
echo "=== MINIMUM READ CONTRACT ==="
echo "READ_INPUT=project_id"
echo "READ_OUTPUT=EXACT_ACTIVE_project_id+package_id+package_version_OR_NULL"
echo "READ_MUST_NOT_SELECT_NEWEST_CANONICAL_PACKAGE=YES"
echo "READ_MUST_NOT_SELECT_NEWEST_GOVERNANCE_PACKAGE=YES"
echo "READ_MUST_NOT_USE_UI_SELECTION=YES"
echo "READ_MUST_NOT_USE_DELEGATION_AS_SELECTION=YES"
echo "READ_MUST_NOT_MUTATE_AUTHORITY=YES"
echo "READ_OWNER=DEDICATED_OPERATIONAL_PACKAGE_AUTHORITY_PERSISTENCE_BOUNDARY"

echo
echo "=== MISSION READ INTEGRATION BOUNDARY ==="
echo "MISSION_READ_CURRENT_API=CALLER_SUPPLIED_package_id"
echo "MISSION_READ_CURRENT_REPOSITORY_LOOKUP=governance_packages_BY_package_id"
echo "MISSION_READ_OWNS_OPERATIONAL_SELECTION=NO"
echo "MISSION_READ_MAY_RECEIVE_RESOLVED_EXACT_OPERATIONAL_IDENTITY=YES"
echo "MISSION_READ_PROJECT_SCOPED_AUTHORITY_RESOLUTION_REQUIRED_FOR_PROJECT_BOUND_HANDOFF=YES"
echo "MISSION_READ_INTEGRATION_IMPLEMENTATION_AUTHORIZED=NO"
echo "MISSION_CONTROL_CHANGE_AUTHORIZED=NO"

echo
echo "=== PERSISTENCE CONTRACT ==="
echo "DEDICATED_PERSISTENCE_REQUIRED=YES"
echo "PERSISTED_FIELDS_MINIMUM=project_id+package_id+package_version+selected_at"
echo "PROJECT_ID_UNIQUENESS_REQUIRED=YES"
echo "EXACT_CANONICAL_VERSION_REFERENCE_REQUIRED=YES"
echo "PROJECT_PACKAGE_OWNERSHIP_DATABASE_ENFORCEMENT_REQUIRED=YES"
echo "NULL_PROJECT_CANONICAL_COMPATIBILITY_MUST_NOT_WEAKEN_PROJECT_BOUND_AUTHORITY=YES"
echo "governance_packages_MUST_NOT_BECOME_SELECTION_AUTHORITY=YES"
echo "governance_delegations_MUST_NOT_BECOME_SELECTION_AUTHORITY=YES"

echo
echo "=== FAILURE CONTRACT ==="
echo "MISSING_CANONICAL_PACKAGE=FAIL_CLOSED"
echo "NON_APPROVED_CANONICAL_PACKAGE=FAIL_CLOSED"
echo "PROJECT_PACKAGE_OWNERSHIP_MISMATCH=FAIL_CLOSED"
echo "MISSING_MISSION_PACKAGE_PROJECTION=FAIL_CLOSED"
echo "IDENTITY_MISMATCH=FAIL_CLOSED"
echo "IMPLICIT_SUCCESSOR_SELECTION=FAIL_CLOSED"
echo "AUTHORITY_WRITE_FAILURE_MUST_NOT_MUTATE_CANONICAL_PACKAGE=YES"
echo "AUTHORITY_WRITE_FAILURE_MUST_NOT_CREATE_DELEGATION=YES"
echo "AUTHORITY_WRITE_FAILURE_MUST_NOT_CONFER_EXECUTION_AUTHORITY=YES"

echo
echo "=== CURRENT LIVE PACKAGE ELIGIBILITY CHECK ==="
sqlite3 -header -column db/main.db '
SELECT
  c.project_id,
  c.package_id,
  c.package_version,
  c.status,
  CASE
    WHEN g.package_id IS NOT NULL
     AND g.package_version = c.package_version
     AND g.project_id = c.project_id
    THEN "ELIGIBLE_FOR_EXPLICIT_OPERATIONAL_SELECTION"
    ELSE "NOT_ELIGIBLE"
  END AS project_bound_handoff_eligibility
FROM matilda_canonical_packages c
LEFT JOIN governance_packages g
  ON g.package_id = c.package_id
 AND g.package_version = c.package_version
WHERE c.status = "canonical_approved"
ORDER BY c.created_at DESC;
'

echo
echo "=== RECONCILIATION DETERMINATION ==="
echo "PREVIOUS_OPERATIONAL_PACKAGE_AUTHORITY_DESIGN_COMPATIBLE_WITH_CURRENT_PACKAGE_HANDOFF_RUNTIME=YES"
echo "PACKAGE_HANDOFF_PROJECTION_REPLACES_OPERATIONAL_PACKAGE_AUTHORITY=NO"
echo "PACKAGE_HANDOFF_PROJECTION_SATISFIES_REQUIRED_PRECONDITION_FOR_OPERATIONAL_SELECTION=YES"
echo "MINIMUM_PROJECT_BOUND_HANDOFF_WRITE_CONTRACT=DEFINED"
echo "MINIMUM_PROJECT_BOUND_HANDOFF_READ_CONTRACT=DEFINED"
echo "AUTHORITY_NON_ESCALATION_BOUNDARY=DEFINED"
echo "FAILURE_CONTRACT=DEFINED"
echo "PERSISTENCE_REQUIREMENT=DEFINED"
echo "MISSION_READ_INTEGRATION_BOUNDARY=DEFINED_BUT_NOT_IMPLEMENTED"
echo "PROJECT_BOUND_HANDOFF_IMPLEMENTATION_STARTED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=CLASSIFY_MINIMUM_DEDICATED_OPERATIONAL_PACKAGE_AUTHORITY_PERSISTENCE_SCHEMA_AND_BOUNDED_IMPLEMENTATION_UNIT_BEFORE_AUTHORIZATION"
