#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="c877ec618"

git fetch origin "$BRANCH"
test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$EXPECTED_HEAD"

printf '\n====================================================\n'
printf ' LIVE ENVELOPE CREATION VALIDATION — AUTHORIZED\n'
printf '====================================================\n\n'

echo "CURRENT_BOUNDARY=LIVE_ENVELOPE_CREATION_VALIDATION"
echo "AUTHORIZED_BY=marcela"
echo "LIVE_ENVELOPE_CREATION_VALIDATION_AUTHORIZED=YES"
echo "AUTHORIZED_ATTEMPT_COUNT=1"
echo "AUTHORIZED_TARGET=ONE_EXACT_ALREADY_GOVERNED_LINEAGE"

printf '\n=== AUTHORIZED LIVE EFFECT ===\n'
echo "ONE_LIVE_ENVELOPE_CREATION_ATTEMPT=YES"
echo "LIVE_GOVERNANCE_DB_MUTATION_FOR_AUTHORIZED_ENVELOPE=YES"
echo "EXACT_PACKAGE_LINEAGE_REQUIRED=YES"
echo "EXACT_DELEGATION_LINEAGE_REQUIRED=YES"
echo "EXACT_VALIDATION_LINEAGE_REQUIRED=YES"
echo "EXACT_OPEN_ENVELOPE_GATE_LINEAGE_REQUIRED=YES"
echo "VALIDATION_PASSED_REQUIRED=YES"
echo "GATE_OPEN_REQUIRED=YES"
echo "AUTHORITATIVE_VALIDATION_SEMANTICS_REQUIRED=YES"
echo "EXPLICIT_OPERATOR_ACTION_REQUIRED=YES"

printf '\n=== AUTHORITY REMAINS EXCLUDED ===\n'
echo "AUTOMATIC_GATE_TO_ENVELOPE_TRANSITION=NO"
echo "AUTOMATIC_ENVELOPE_CREATION=NO"
echo "LIFECYCLE_TRANSITION_AUTHORITY=NO"
echo "ROUTING_AUTHORITY=NO"
echo "ASSIGNMENT_AUTHORITY=NO"
echo "SCHEDULING_AUTHORITY=NO"
echo "WORKER_CLAIM_AUTHORITY=NO"
echo "ORCHESTRATION_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "DOWNSTREAM_EXECUTION_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"
echo "GENERIC_SHELL_AUTHORITY=NO"
echo "SELF_AUTHORIZATION=NO"

printf '\n=== FAILURE CONTAINMENT ===\n'
echo "FAIL_CLOSED_ON_LINEAGE_DRIFT=YES"
echo "FAIL_CLOSED_ON_VALIDATION_STATUS_DRIFT=YES"
echo "FAIL_CLOSED_ON_GATE_STATUS_DRIFT=YES"
echo "FAIL_CLOSED_ON_SEMANTIC_GAP=YES"
echo "SECOND_LIVE_ATTEMPT_WITHOUT_NEW_AUTHORIZATION=PROHIBITED"
echo "SUCCESSOR_MUTATION_AUTHORIZED=NO"
echo "AUTOMATIC_ADVANCE=PROHIBITED"

printf '\n=== NEXT ACTION ===\n'
echo "NEXT_ACTION=IDENTIFY_ONE_EXACT_ELIGIBLE_LIVE_LINEAGE_BEFORE_MUTATION"
echo "IDENTIFICATION_ACTION=READ_ONLY"
echo "LIVE_MUTATION_DURING_IDENTIFICATION=NO"

printf '\nONE_LIVE_ENVELOPE_CREATION_VALIDATION_AUTHORIZATION=RECORDED\n'
