#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== REFINE APPROVALS INFORMATION HIERARCHY PLAN ==="
echo "BASELINE_COMMIT=fded7019"
echo "RECOVERY_POINT=DR_20260826_092915"
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PACKAGES_TAB_REMOVAL_AUTHORIZED=NO"

echo
echo "=== LEFT PANEL TARGET ==="
echo "PRIMARY=HUMAN_READABLE_PACKAGE_TITLE_OR_OBJECTIVE"
echo "SECONDARY=SHORT_SUMMARY"
echo "STATUS=SINGLE_NEEDS_REVIEW_BADGE"
echo "TIMESTAMP=KEEP"
echo "HIDE_FROM_PRIMARY=ARTIFACT_NUMBER"
echo "HIDE_FROM_PRIMARY=CONVERSATION_ID"
echo "HIDE_FROM_PRIMARY=REPEATED_APPROVE_CANONICAL_PACKAGE_COPY"

echo
echo "=== RIGHT PANEL TARGET ==="
echo "HEADER=HUMAN_PACKAGE_TITLE_PLUS_SINGLE_NEEDS_REVIEW_BADGE"
echo "SUMMARY=OBJECTIVE_OR_EXPECTED_OUTCOME"
echo "APPROVAL_EFFECT=SMALL_INLINE_LIVING_DRAFT_TO_CANONICAL_NOTICE"
echo "MOVE_TO_TECHNICAL_DETAILS=SELECTED_ARTIFACT_ID"
echo "MOVE_TO_TECHNICAL_DETAILS=ARTIFACT_POSITION"
echo "MOVE_TO_TECHNICAL_DETAILS=SOURCE_DRAFT_STATUS"
echo "COMBINE=EXPECTED_OUTCOME_PROPOSED_WORK_DELIVERABLES_INTO_ONE_WHAT_YOU_ARE_APPROVING_SECTION"
echo "KEEP=SCOPE_TWO_COLUMN"
echo "KEEP_IF_PRESENT=CONSTRAINTS"
echo "KEEP_IF_PRESENT=OPEN_QUESTIONS"
echo "KEEP=APPROVE_AND_REQUEST_CHANGES"
echo "TECHNICAL_DETAILS=COLLAPSED"

echo
echo "=== DESIGN GOAL ==="
echo "GOAL=MAKE_APPROVALS_READ_LIKE_A_HUMAN_DECISION_BRIEF_NOT_A_SYSTEM_RECORD"
echo "NEXT_ACTION=INSPECT_CURRENT_REACT_FIELD_BINDINGS_FOR_THIS_EXACT_RECOMPOSITION_BEFORE_AUTHORIZING_IMPLEMENTATION"
