#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

SOURCE_SCRIPT="inspect-atlas-matilda-dogfood-cleanup-dependencies.sh"
OUTPUT="/tmp/atlas-matilda-dogfood-dependency-map.txt"

test -f "$SOURCE_SCRIPT"

printf '\n=== TOOLING FAILURE CLASSIFICATION ===\n'
echo "PREVIOUS_FAILURE=SCRIPT_NOT_EXECUTABLE"
echo "PRODUCT_HYPOTHESIS_FAILURE=NO"
echo "DEPENDENCY_INSPECTION_PREVIOUSLY_EXECUTED=NO"
echo "CLEANUP_AUTHORIZED=NO"
echo "DATABASE_MUTATION_AUTHORIZED=NO"
echo "ATLAS_QA_EVIDENCE_DELETION_AUTHORIZED=NO"

printf '\n=== RUN SAME READ-ONLY INVESTIGATION THROUGH BASH ===\n'
bash "$SOURCE_SCRIPT" | tee "$OUTPUT"

printf '\n=== EXTRACT CLEANUP DECISION SIGNALS ===\n'
grep -E \
'DOGFOOD_REFERENCE_TABLE=|DOGFOOD_REFERENCE_ROW_COUNT=|DOGFOOD_MATCHING_TABLES=|DOGFOOD_TOTAL_MATCHING_ROWS=|ATLAS_TABLES=|ATLAS_DOGFOOD_ROW_COUNT=|CURRENT_ATLAS_SCOPED_READBACK_COUNT=|DIRECT_MATILDA_RUNTIME_REFERENCES=|STATIC_READ_PATH_CLASS=|DELETION_SAFETY=|PREFERRED_CLEANUP_MODEL=|DOGFOOD_DEPENDENCY_MAPPING=|CLEANUP_EXECUTED=|ATLAS_QA_EVIDENCE_DELETED=|DATABASE_MUTATED=|PRODUCT_CODE_CHANGED=|AUTHORITY_CHANGE=|NEXT_ACTION=|CLEAR_STOPPING_POINT=' \
"$OUTPUT"

printf '\n=== STOP ===\n'
echo "NEXT_ACTION=USE_RESULTS_ABOVE_TO_CLASSIFY_DOGFOOD_ROWS"
