#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== COLLABORATIVE REVIEW OF APPROVALS INFORMATION HIERARCHY ==="
echo "BASELINE_COMMIT=ff7e4420"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"

echo
echo "=== PROPOSED USER-FACING RIGHT-PANEL ORDER ==="
echo "1=WHAT_IS_THIS"
echo "2=WHAT_WILL_HAPPEN_IF_I_APPROVE"
echo "3=WHAT_WORK_IS_PROPOSED"
echo "4=WHAT_IS_IN_AND_OUT_OF_SCOPE"
echo "5=WHAT_CONSTRAINTS_OR_OPEN_QUESTIONS_EXIST"
echo "6=DECISION_ACTIONS"
echo "7=OPTIONAL_TECHNICAL_DETAILS"

echo
echo "=== PROPOSED LABEL TRANSLATIONS ==="
echo "interpreted_objective=Objective"
echo "expected_outcome=Expected outcome"
echo "proposed_work=Proposed work"
echo "proposed_artifacts=Deliverables"
echo "in_scope=In scope"
echo "out_of_scope=Out of scope"
echo "constraints=Constraints"
echo "unresolved_questions=Open questions"
echo "source_draft_status=Draft status"
echo "current_state_to_proposed_state_transition=Approval effect"

echo
echo "=== PRESENTATION RECOMMENDATIONS ==="
echo "OBJECTIVE_AND_EXPECTED_OUTCOME=TOP_SUMMARY_BLOCK"
echo "PROPOSED_WORK_AND_DELIVERABLES=ONE_WORK_SECTION"
echo "IN_SCOPE_AND_OUT_OF_SCOPE=SIDE_BY_SIDE_WHERE_SPACE_ALLOWS"
echo "CONSTRAINTS_AND_OPEN_QUESTIONS=ONE_RISK_AND_CLARITY_SECTION"
echo "APPROVAL_EFFECT=ONE_COMPACT_NOTICE"
echo "APPROVE_AND_REQUEST_CHANGES=ALWAYS_VISIBLE_NEAR_PRIMARY_CONTENT"
echo "TECHNICAL_IDENTIFIERS=DISCLOSURE_ONLY"
echo "RAW_EVIDENCE_IDS=TECHNICAL_DISCLOSURE_ONLY"
echo "REPEATED_PENDING_BADGES=REMOVE_REDUNDANCY"
echo "ARTIFACT_SWITCHER=REMOVE_IF_LEFT_PANEL_SELECTION_REPLACES_IT"

echo
echo "=== INFORMATION THAT SHOULD NOT DISAPPEAR ==="
echo "KEEP=OBJECTIVE"
echo "KEEP=EXPECTED_OUTCOME"
echo "KEEP=PROPOSED_WORK"
echo "KEEP=DELIVERABLES"
echo "KEEP=SCOPE"
echo "KEEP=CONSTRAINTS"
echo "KEEP=OPEN_QUESTIONS_WHEN_PRESENT"
echo "KEEP=APPROVAL_EFFECT"
echo "KEEP=APPROVE_ACTION"
echo "KEEP=REQUEST_CHANGES_ACTION"
echo "KEEP=TECHNICAL_LINEAGE_BUT_COLLAPSED"

echo
echo "=== CURRENT RECOMMENDATION ==="
echo "RECOMMENDATION=MAKE_APPROVALS_FEEL_LIKE_A_DECISION_BRIEF_NOT_A_SYSTEM_DIAGNOSTIC"
echo "PACKAGES_VISUAL_HIERARCHY=USE_AS_PRESENTATION_MODEL"
echo "APPROVALS_DATA_AND_AUTHORITY=RETAIN"
echo "PACKAGES_TAB_REMOVAL=ONLY_AFTER_NEW_APPROVALS_SURFACE_IS_VALIDATED"
echo "NEXT_ACTION=USER_REVIEW_OF_LABELS_ORDER_AND_VISIBLE_VS_COLLAPSED_INFORMATION"
