#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== FINAL MILESTONE DR ==="
echo "MILESTONE=MISSION_CONTROL_PROJECT_CONTEXT_ALIGNMENT"
echo "MILESTONE_CLOSURE_COMMIT=5191d545"
echo "MILESTONE_STATUS=CLOSED"
echo "PHASE_1=PROJECT_SCOPED_MISSION_READ_RUNTIME"
echo "PHASE_1_STATUS=CLOSED"
echo "PHASE_2=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "PHASE_2_STATUS=CLOSED"
echo "END_TO_END_PROJECT_SCOPED_MISSION_HANDOFF=PASS"
echo "MISSION_CONTROL_REMAINS_READ_ONLY_CONSUMER=YES"
echo "FAIL_CLOSED_BOUNDARIES=PRESERVED"
echo "AUTHORITY_NON_ESCALATION=PRESERVED"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "NEXT_ACTION_AFTER_DR=RECONCILE_SUCCESSOR_MILESTONE_SEPARATELY"

dr
