#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== DR CHECKPOINT ==="
echo "ACTIVE_PHASE=AUTHORITATIVE_MISSION_PACKAGE_HANDOFF"
echo "ACTIVE_CORRIDOR=MISSION_CONTROL_INTAKE"
echo "LATEST_VALIDATED_INTAKE_STATE=1985a01c"
echo "MISSION_CONTROL_PROJECT_SCOPED_INTAKE_VALIDATION=PASS"
echo "MISSION_CONTROL_INTAKE_FORMALLY_CLOSED=NO"
echo "NEXT_ACTION_AFTER_DR=CLASSIFY_MISSION_CONTROL_INTAKE_CLOSURE_READINESS"

dr
