#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== SEED PACKAGE SEMANTICS LIVE TEST — ATTEMPT 2 ==="
echo "FAILURE_1=INVALID_TYPESCRIPT_IMPORT"
echo "FAILURE_2=NONEXISTENT_CONVERSATION_ID"
echo "CURRENT_HYPOTHESIS=CREATE_REAL_PROJECT_CONVERSATION_BEFORE_RUNNING_WORKFLOW"
echo "DIRECT_DB_SEED=NO"
echo "HISTORICAL_BACKFILL=NO"
echo "AUTHORITY_TRANSITION=NO"

npx tsx seed-package-semantics-live-test.ts

echo
echo "SEED_COMPLETE=YES"
echo "EXPECTED_RESULT=FRESH_REQUEST_SPECIFIC_LIVING_DRAFT_CREATED_THROUGH_NORMAL_MATILDA_WORKFLOW"
echo "NEXT_ACTION=INSPECT_NEW_LIVING_DRAFT_THEN_MOVE_IT_THROUGH_NORMAL_APPROVAL_FLOW"
