#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "=== STOP REDUNDANT VISUAL REVIEW CHECKPOINTING ==="
echo "CURRENT_BASELINE=38ec6cee"
echo "IMPLEMENTATION_STATE=PAUSED_FOR_VISUAL_REVIEW"
echo "FURTHER_UI_CHANGE_AUTHORIZED=NO"
echo "PACKAGES_TAB_REMOVAL_AUTHORIZED=NO"
echo "ADDITIONAL_CHECKPOINT_COMMITS_REQUIRED=NO"
echo "NEXT_ACTION=OPEN_UPDATED_APPROVALS_UI_AND_RETURN_SCREENSHOT_OR_VISUAL_FEEDBACK"
