#!/usr/bin/env bash
set -euo pipefail

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="298ebb613"
CONTRACT="docs/governance/AUTHORITATIVE_ENVELOPE_SEMANTICS_CONTRACT.md"

git fetch origin "$BRANCH"

test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$EXPECTED_HEAD"
test -f "$CONTRACT"

printf '\n====================================================\n'
printf ' AUTHORITATIVE ENVELOPE SEMANTICS CONTRACT — VERIFY\n'
printf '====================================================\n\n'

git diff --check -- "$CONTRACT"

grep -Fq 'AUTHORITATIVE_REQUIRED_CAPABILITIES_OWNER=GOVERNANCE_VALIDATION_RESULT_CAPABILITY_REQUIREMENTS' "$CONTRACT"
grep -Fq 'AUTHORITATIVE_OPERATIONAL_CORRIDOR_OWNER=GOVERNANCE_VALIDATION_RESULT_OPERATIONAL_REQUIREMENTS' "$CONTRACT"
grep -Fq 'TRANSFORMATION_CLASS=LOSSLESS_TRIM_ONLY' "$CONTRACT"
grep -Fq 'SPECULATIVE_MAPPING=PROHIBITED' "$CONTRACT"
grep -Fq 'ENVELOPE_CREATION_AUTHORIZED=NO' "$CONTRACT"
grep -Fq 'LIVE_GOVERNANCE_MUTATION_AUTHORIZED=NO' "$CONTRACT"
grep -Fq 'EXECUTION_AUTHORITY=NO' "$CONTRACT"
grep -Fq 'NEW_AUTHORITY=NO' "$CONTRACT"

printf '\n=== VERIFIED SEMANTIC OWNERSHIP ===\n'
echo "REQUIRED_CAPABILITIES_OWNER=GOVERNANCE_VALIDATION_RESULT_CAPABILITY_REQUIREMENTS"
echo "OPERATIONAL_CORRIDOR_OWNER=GOVERNANCE_VALIDATION_RESULT_OPERATIONAL_REQUIREMENTS"
echo "TRANSFORMATION=LOSSLESS_TRIM_ONLY"
echo "EXACT_VALIDATION_LINEAGE_REQUIRED=YES"
echo "SPECULATIVE_MAPPING=PROHIBITED"

printf '\n=== VERIFIED AUTHORITY BOUNDARY ===\n'
echo "ENVELOPE_CREATION_AUTHORIZED=NO"
echo "LIVE_GOVERNANCE_MUTATION_AUTHORIZED=NO"
echo "AUTOMATIC_GATE_TO_ENVELOPE_TRANSITION=NO"
echo "LIFECYCLE_TRANSITION_AUTHORITY=NO"
echo "EXECUTION_AUTHORITY=NO"
echo "DOWNSTREAM_EXECUTION_AUTHORITY=NO"
echo "NEW_AUTHORITY=NO"

printf '\n====================================================\n'
printf ' AUTHORITATIVE ENVELOPE SEMANTICS CONTRACT — CLOSED\n'
printf '====================================================\n\n'

echo "CONTRACT_COMMIT=$EXPECTED_HEAD"
echo "AUTHORITATIVE_SEMANTIC_OWNERSHIP_GAP=RESOLVED"
echo "AUTHORITATIVE_ENVELOPE_SEMANTICS_CONTRACT=CLOSED"
echo "PREVIOUS_ENVELOPE_CREATION_BLOCKER=RESOLVED"
echo "NEXT_BOUNDARY=BOUNDED_ENVELOPE_CREATION_IMPLEMENTATION_REAUTHORIZATION"
echo "NEXT_BOUNDARY_AUTHORIZED=NO"
echo "AUTOMATIC_ADVANCE=PROHIBITED"

printf '\nAUTHORITATIVE_ENVELOPE_SEMANTICS_CONTRACT_VERIFICATION=PASS\n'
