#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="d9c59a07c"
CLOSURE_DOC="docs/checkpoints/EXECUTIVE_DELEGATION_DECISION_ADAPTER_CLOSURE.md"

git fetch origin "$BRANCH"

test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$EXPECTED_HEAD"
test "$(git rev-parse HEAD)" = "$(git rev-parse "origin/$BRANCH")"

grep -q '^CORRIDOR_STATUS=CLOSED$' "$CLOSURE_DOC"
grep -q '^EXECUTIVE_DELEGATION_DECISION_ADAPTER=VALIDATED$' "$CLOSURE_DOC"
grep -q '^NEXT_ACTION=AWAIT_NEW_USER_SELECTED_OBJECTIVE$' "$CLOSURE_DOC"
grep -q '^BEHAVIORAL_CERTIFICATION_COMPLETE=YES$' "$CLOSURE_DOC"
grep -q '^DATABASE_SCHEMA_MUTATION_PERFORMED=NO$' "$CLOSURE_DOC"
grep -q '^PRODUCTION_DATABASE_MUTATION_PERFORMED=NO$' "$CLOSURE_DOC"
grep -q '^NEW_SEMANTIC_AUTHORITY_INTRODUCED=NO$' "$CLOSURE_DOC"
grep -q '^DOWNSTREAM_EXECUTION_AUTHORITY_INTRODUCED=NO$' "$CLOSURE_DOC"

echo "EXECUTIVE_DELEGATION_CORRIDOR_CLOSURE=VERIFIED"
echo "HEAD=$EXPECTED_HEAD"
echo "CORRIDOR_STATUS=CLOSED"
echo "NEXT_ACTION=AWAIT_NEW_USER_SELECTED_OBJECTIVE"
