#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

echo "=== VERIFY UNIT A STOP CONDITION ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

EXPECTED_HEAD_PREFIX="69ae4e13c"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP: unexpected HEAD ${CURRENT_HEAD}"
  exit 1
fi

echo
echo "=== VERIFIED STATE ==="
echo "ANCHOR_ONLY_LOOP_STOPPED=YES"
echo "UNIT_A_SOURCE_OF_TRUTH_CORRIDOR=CLOSED"
echo "UNIT_A_EXTERNAL_INPUT_COLLECTION_CORRIDOR=ACTIVE"
echo "NEXT_REPOSITORY_COMMIT_REQUIRES_NEW_SUBSTANTIVE_EVIDENCE=YES"

echo
echo "=== REMAINING BLOCKERS ==="
echo "TEAM_DOMAIN=REQUIRED_FROM_CLOUDFLARE_ZERO_TRUST_ACCOUNT_STATE"
echo "APPLICATION_AUDIENCE_TAG=REQUIRED_FROM_CLOUDFLARE_ACCESS_APPLICATION_STATE"
echo "ALLOWED_OPERATOR_IDENTITY_POLICY=UNSELECTED"
echo "ACCESS_POLICY_SCOPE=UNSELECTED"
echo "ORIGIN_BYPASS_BOUNDARY=REQUIRES_DEPLOYMENT_EVIDENCE"
echo "SAFE_NON_EXECUTION_VALIDATION_TARGET=UNDESIGNED"

echo
echo "=== NEXT ACTION ==="
echo "NEXT_ACTION=NO_FURTHER_REPOSITORY_CHANGE_UNTIL_NEW_EXTERNAL_OR_USER_OWNED_EVIDENCE_EXISTS"
echo "IMPLEMENTATION_READINESS_REVIEW_ALLOWED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"

echo
echo "=== SAFETY ==="
echo "NO_CLOUDFLARE_CONFIGURATION_WRITE=YES"
echo "NO_AUTH_IMPLEMENTATION=YES"
echo "NO_ROUTE_MOUNT_CHANGE=YES"
echo "NO_APPROVAL_WRITE=YES"
echo "NO_EXECUTION_AUTHORIZATION_WRITE=YES"
echo "NO_VERSION_CONTROL_RUNTIME_EFFECT=YES"
