#!/bin/bash

set -euo pipefail

echo "PHASE 487 — DOCKER PRUNE TIERS (READ-ONLY HELPER)"
echo ""
echo "Protected volume:"
echo "  motherboard_systems_hq_pgdata"
echo ""
echo "Allowed tiers:"
echo ""
echo "Tier 1 — Build cache only"
echo "  docker builder prune"
echo ""
echo "Tier 1 aggressive"
echo "  docker builder prune -a"
echo ""
echo "Tier 2 — Exited containers only"
echo "  docker container prune"
echo ""
echo "Tier 3 — Unused images only"
echo "  docker image prune -a"
echo ""
echo "Tier 4 — Combined non-volume prune"
echo "  docker system prune -a"
echo ""
echo "Forbidden:"
echo "  docker system prune -a --volumes"
echo "  docker volume prune"
echo "  docker volume rm motherboard_systems_hq_pgdata"
echo ""
echo "Required order:"
echo "  1) Tier 1"
echo "  2) Re-check Docker health"
echo "  3) Tier 2 if still needed"
echo "  4) Re-check Docker health"
echo "  5) Tier 3 if still needed"
echo "  6) Tier 4 only if explicitly chosen"
