import fs from "fs";
import path from "path";

/**
 * Cade Skill: createFile
 * Usage: runSkill("createFile", { filename: "delegated.txt", content: "Generated by Cade." })
 */
export default async function run(params: { filename: string; content?: string }): Promise<string> {
  const filePath = path.join(process.cwd(), "memory", params.filename);
  fs.writeFileSync(filePath, params.content || "Generated by Cade 🧠", "utf8");
  return `✅ Cade created file at ${filePath}`;
}
