#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=EXECUTIVE_MISSION_OVERVIEW' \
  'CORRIDOR=EXECUTIVE_OVERVIEW_VALIDATION_AND_CLOSURE' \
  'PRE_IMPLEMENTATION_CHECKPOINT=1d8e7805' \
  'IMPLEMENTATION_SCOPE=MISSION_READ_PROJECTION_AND_EXECUTIVE_PRESENTATION_MAPPING_ONLY' \
  'MISSION_OBJECTIVE_SOURCE=GOVERNANCE_PACKAGES_REQUESTED_OUTCOME' \
  'MISSION_TITLE_SOURCE=HUMAN_READABLE_REQUESTED_OUTCOME' \
  'MISSION_STATE_SOURCE=AUTHORITATIVE_GOVERNANCE_PERSISTENCE_ONLY' \
  'PIPELINE_BOUNDARY=GOVERNANCE_MOVEMENT_ONLY' \
  'DEPARTMENT_OR_AGENT_INFERENCE=PROHIBITED' \
  'NEW_SEMANTIC_AUTHORITY=PROHIBITED' \
  'NEW_PERSISTENCE=PROHIBITED' \
  'CONVERSATION_ENGINE_CHANGE=PROHIBITED' \
  'RENDERER_SEMANTIC_AUTHORITY=PROHIBITED' \
  'ROLLBACK_CHECKPOINT=1d8e7805' \
  'IMPLEMENTATION_AUTHORIZED=YES' \
  'NEXT_UNIT=BOUNDED_EXECUTIVE_MISSION_OVERVIEW_IMPLEMENTATION'
