#!/usr/bin/env bash
set -euo pipefail

echo "=== AUTHORIZE BOUNDED PROMPT PRESENTATION DIAGNOSTIC IMPLEMENTATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor f4087ac7 HEAD

readiness="scripts/classify-prompt-presentation-diagnostic-runner-implementation-readiness.sh"
test -f "$readiness"

grep -q 'DIAGNOSTIC_RUNNER_IMPLEMENTATION_READINESS=' "$readiness"
grep -q '^READY$' <(awk '/DIAGNOSTIC_RUNNER_IMPLEMENTATION_READINESS=/{getline; print}' "$readiness")
grep -q 'PRODUCTION_REMEDY_READINESS=' "$readiness"
grep -q '^NOT_READY$' <(awk '/PRODUCTION_REMEDY_READINESS=/{getline; print}' "$readiness")
grep -q 'NEXT_ACTION=' "$readiness"
grep -q '^IMPLEMENT_BOUNDED_VALIDATION_ONLY_PROMPT_PRESENTATION_DIAGNOSTIC$' \
  <(awk '/NEXT_ACTION=/{getline; print}' "$readiness")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

UNIT=
BOUNDED_VALIDATION_ONLY_PROMPT_PRESENTATION_DIAGNOSTIC

READINESS=
CONFIRMED

AUTHORIZED_IMPLEMENTATION_SCOPE=
REQUEST_SCOPED_VALIDATION_ONLY_PRESENTATION_VARIANT_SELECTOR
BOUNDED_NON_PRODUCTION_AB_DIAGNOSTIC_RUNNER

AUTHORIZED_PRESENTATION_VARIANT=
EXPLICIT_PARENT_SUPPORT_AND_CHILD_SELECTION_SEPARATION

PRODUCTION_DEFAULT=
MUST_REMAIN_BIT_FOR_BIT_BEHAVIORALLY_UNCHANGED_WHEN_DIAGNOSTIC_SELECTOR_IS_ABSENT

SEMANTIC_CONTRACT=
UNCHANGED

STRUCTURED_RESPONSE_SCHEMA=
UNCHANGED

SUPPORT_PROVENANCE_RULE=
UNCHANGED

SELECTED_CONTEXT_SEGMENT_RULE=
UNCHANGED

FAIL_CLOSED_VALIDATION=
UNCHANGED

MODEL=
UNCHANGED

VALIDATION_FIXED_SEED=
424242

VALIDATION_FIXED_SEED_SCOPE=
DIAGNOSTIC_ONLY

ONE_INVOCATION_PER_RUN=
PRESERVED

RETRY=
NONE

ROLLBACK_BOUNDARY=
REMOVE_DIAGNOSTIC_PRESENTATION_SELECTOR_AND_RUNNER

PRODUCTION_PROMPT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

DIAGNOSTIC_IMPLEMENTATION_AUTHORIZED=
YES

PRODUCTION_REMEDY_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

NEXT_ACTION=
IMPLEMENT_BOUNDED_VALIDATION_ONLY_PROMPT_PRESENTATION_DIAGNOSTIC
MAP
