#!/usr/bin/env bash
set -euo pipefail

echo "=== AUTHORIZE BOUNDED UNSEEDED PRESENTATION VALIDATION IMPLEMENTATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"

readiness="scripts/classify-bounded-unseeded-presentation-validation-implementation-readiness.sh"
test -f "$readiness"

grep -q 'VALIDATION_IMPLEMENTATION_READINESS=' "$readiness"
grep -q '^READY$' \
  <(awk '/VALIDATION_IMPLEMENTATION_READINESS=/{getline; print}' "$readiness")

grep -q 'PRODUCTION_REMEDY_READINESS=' "$readiness"
grep -q '^NOT_READY$' \
  <(awk '/PRODUCTION_REMEDY_READINESS=/{getline; print}' "$readiness")

grep -q 'NEXT_ACTION=' "$readiness"
grep -q '^IMPLEMENT_BOUNDED_UNSEEDED_EXPERIMENTAL_PRESENTATION_VALIDATION$' \
  <(awk '/NEXT_ACTION=/{getline; print}' "$readiness")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

AUTHORIZED_UNIT=
BOUNDED_UNSEEDED_EXPERIMENTAL_PRESENTATION_VALIDATION

AUTHORIZED_IMPLEMENTATION_SCOPE=
BOUNDED_VALIDATION_RUNNER_ONLY

TEST_ARM=
EXPERIMENTAL_PRESENTATION_ONLY

PRESENTATION_VARIANT=
EXPLICIT_PARENT_CHILD_SEPARATION

RUN_COUNT=
10

GENERATION_SEED=
ABSENT

EXECUTION_MODE=
SEQUENTIAL

ONE_INVOCATION_PER_RUN=
PRESERVED

RETRY=
NONE

EXISTING_RUNTIME_SEAM=
REUSED

NEW_RUNTIME_SEAM=
NOT_AUTHORIZED

PRODUCTION_DEFAULT=
UNCHANGED

SEMANTIC_CONTRACT=
UNCHANGED

STRUCTURED_RESPONSE_SCHEMA=
UNCHANGED

SUPPORT_PROVENANCE_RULES=
UNCHANGED

SELECTED_CONTEXT_SEGMENT_RULES=
UNCHANGED

FAIL_CLOSED_VALIDATION=
UNCHANGED

MODEL=
UNCHANGED

PRODUCTION_PROMPT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

PRODUCTION_REMEDY_AUTHORIZED=
NO

VALIDATION_IMPLEMENTATION_AUTHORIZED=
YES

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

ROLLBACK_BOUNDARY=
REMOVE_UNSEEDED_VALIDATION_RUNNER_ONLY

NEXT_ACTION=
IMPLEMENT_BOUNDED_UNSEEDED_EXPERIMENTAL_PRESENTATION_VALIDATION
MAP
