#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=bd6a6a93' \
  'MODE=COLLABORATION' \
  'ISSUE_RESOLVED=NO' \
  'ROOT_CAUSE_CLASSIFIED=YES' \
  'BOUNDED_FIX_DEFINED=YES' \
  'IMPLEMENTATION_READY=YES' \
  'IMPLEMENTATION_STARTED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION_TO_IMPLEMENT_PROMPT_CONTRACT_FIX'

printf '\n=== VERIFIED FIX BOUNDARY ===\n'
printf '%s\n' \
  'CHANGE_OWNER=scripts/utils/ollamaChat.ts_PROMPT_CONSTRUCTION' \
  'VALIDATOR_CHANGE=NO' \
  'VALIDATOR_WEAKENING=NO' \
  'GENERATION_POLICY_CHANGE=NO' \
  'MODEL_CHANGE=NO' \
  'RETRY_CHANGE=NO' \
  'PERSISTENCE_CHANGE=NO' \
  'AUTHORITY_CHANGE=NO' \
  'ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=PRESERVED'

printf '\n=== REQUIRED IMPLEMENTATION OUTCOME ===\n'
printf '%s\n' \
  'EMPTY_HISTORY_ALLOWED_CONVERSATION_SUPPORT_SET=EXPLICITLY_EMPTY' \
  'MODEL_MUST_RETURN_NO_CONVERSATION_TURN_REFERENCE_WHEN_SET_EMPTY=YES' \
  'NONEMPTY_HISTORY_MUST_USE_ONLY_EXACT_SUPPLIED_SOURCE_TURN_IDS=YES' \
  'INVENTED_CONVERSATION_SOURCE_IDS_MUST_CONTINUE_FAILING_CLOSED=YES'

printf '\n=== WORKTREE ===\n'
git status --short
