#!/usr/bin/env bash
set -euo pipefail

echo "=== AUTHORIZE EXPERIMENTAL PRESENTATION PRODUCTION PROMOTION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor a74c474c HEAD
test -z "$(git status --porcelain)"

readiness="scripts/classify-experimental-presentation-production-promotion-implementation-readiness.sh"
test -f "$readiness"

grep -q 'PRODUCTION_PROMOTION_IMPLEMENTATION_READINESS=' "$readiness"
grep -q '^READY$' \
  <(awk '/PRODUCTION_PROMOTION_IMPLEMENTATION_READINESS=/{getline; print}' "$readiness")

grep -q 'PRODUCTION_REMEDY_AUTHORIZATION_REQUIRED=' "$readiness"
grep -q '^YES$' \
  <(awk '/PRODUCTION_REMEDY_AUTHORIZATION_REQUIRED=/{getline; print}' "$readiness")

grep -q 'NEXT_ACTION=' "$readiness"
grep -q '^AUTHORIZE_EXPERIMENTAL_PRESENTATION_PRODUCTION_PROMOTION$' \
  <(awk '/NEXT_ACTION=/{getline; print}' "$readiness")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

AUTHORIZED_UNIT=
EXPERIMENTAL_PRESENTATION_PRODUCTION_PROMOTION

AUTHORIZED_INTERVENTION=
MAKE_EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION_THE_DEFAULT_PRODUCTION_PROMPT_PRESENTATION

AUTHORIZED_IMPLEMENTATION_SURFACE=
scripts/utils/ollamaChat.ts

AUTHORIZED_CHANGE_CLASS=
PROMPT_PRESENTATION_STRUCTURE_ONLY

SEMANTIC_CONTRACT_CHANGE=
NOT_AUTHORIZED

STRUCTURED_RESPONSE_SCHEMA_CHANGE=
NOT_AUTHORIZED

SUPPORT_PROVENANCE_RULE_CHANGE=
NOT_AUTHORIZED

SELECTED_CONTEXT_SEGMENT_RULE_CHANGE=
NOT_AUTHORIZED

FAIL_CLOSED_VALIDATOR_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=
MUST_REMAIN_PRESERVED

REPLY_AND_DURABLE_INTERPRETATION_SEPARATION=
MUST_REMAIN_PRESERVED

IEL_PERSISTENCE_BOUNDARY=
MUST_REMAIN_PRESERVED

CONVERSATION_CONTEXT_BOUNDARY=
MUST_REMAIN_PRESERVED

PRIOR_INVESTIGATION_LIFECYCLE_BOUNDARY=
MUST_REMAIN_PRESERVED

LIVING_DRAFT_DERIVATION_BOUNDARY=
MUST_REMAIN_PRESERVED

APPROVAL_PIPELINE_AUTHORITY_BOUNDARY=
MUST_REMAIN_PRESERVED

ROLLBACK_BOUNDARY=
RESTORE_PRE_PROMOTION_DEFAULT_PRESENTATION_PATH_WITHOUT_REMOVING_VALIDATION_EVIDENCE_OR_DIAGNOSTIC_RUNNERS

REQUIRED_POST_IMPLEMENTATION_VALIDATION=
TARGETED_TYPESCRIPT_VALIDATION
DETERMINISTIC_EXISTING_REGRESSION_SUITE
PRODUCTION_BEHAVIORAL_UNSEEDED_SAMPLE

PRODUCTION_PROMOTION_IMPLEMENTATION_AUTHORIZED=
YES

PRODUCTION_REMEDY_AUTHORIZED=
YES_BOUNDED_TO_PROMPT_PRESENTATION_STRUCTURE

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

CORRIDOR_1_STATUS=
ACTIVE

NEXT_ACTION=
IMPLEMENT_EXPERIMENTAL_PRESENTATION_PRODUCTION_PROMOTION
MAP
