#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=DELEGATION_WORKSPACE' \
  'ACTIVE_CORRIDOR=REQUEST_CHANGES_PERSISTENCE' \
  'READINESS_CHECKPOINT=f6c364a2' \
  'STATUS=READY_BOUNDED' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'IMPLEMENTATION_STARTED=NO' \
  'NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION'

git status --short
