#!/usr/bin/env bash
set -euo pipefail

echo "=== CAPTURE PROGRAM RECONCILIATION FINAL CHECKPOINT ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 32c26bba HEAD

closure="scripts/close-conversation-engine-program-reconciliation-milestone.sh"
test -f "$closure"

grep -q 'MILESTONE_STATUS=' "$closure"
grep -q 'CLOSED' "$closure"
grep -q 'MILESTONE_CLOSURE_CLASSIFICATION=' "$closure"
grep -q 'COMPLETE_WITH_NO_EVIDENCE_SUPPORTED_RUNTIME_SUCCESSOR_ESTABLISHED' "$closure"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

CLOSED_MILESTONE=
CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION

CLOSURE_COMMIT=
32c26bba

MILESTONE_STATUS=
CLOSED

PHASE_1_STATUS=
COMPLETE

CURRENT_UNRESOLVED_CAPABILITY_GAPS=
ZERO_ON_CURRENT_INVENTORIED_SURFACE

CURRENT_SUCCESSOR_PRIORITY=
NONE_ESTABLISHED

NEXT_RUNTIME_IMPLEMENTATION_MILESTONE=
NONE_ESTABLISHED

PRODUCTION_GENERATION_INSTABILITY=
PRESERVED_AS_KNOWN_DEFERRED_CONDITION

PRODUCTION_GENERATION_POLICY=
UNCHANGED_UNCONFIGURED_UNSEEDED

PRODUCTION_CHANGE=
NONE

NEXT_ACTION=
RUN_DR_AND_RECORD_FINAL_CHECKPOINT
MAP
