#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OUT="/tmp/matilda-controlled-comparison-output.txt"
pbpaste > "$OUT"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=d36eb4fe' \
  'ISSUE_RESOLVED=NO' \
  'ACTION=CAPTURE_ORIGINAL_CONTROLLED_COMPARISON_OUTPUT_FROM_CLIPBOARD'

printf '\n=== CAPTURED OUTPUT MARKERS ===\n'
grep -nE \
  'CONTROLLED RUN|COMPARISON SUMMARY|ACCEPTANCE BOUNDARY|PRIMARY_CONTROL_CRITERION|COMPARATIVE_CRITERION|accepted|failureClass|ISSUE_RESOLVED' \
  "$OUT" || true

printf '\n=== COMPLETION CLASSIFICATION ===\n'
if grep -q '=== COMPARISON SUMMARY ===' "$OUT" &&
   grep -q '=== ACCEPTANCE BOUNDARY ===' "$OUT"; then
  printf '%s\n' \
    'CONTROLLED_COMPARISON_OUTPUT_CAPTURED=YES' \
    'FINAL_COMPARISON_SUMMARY_CAPTURED=YES' \
    'NEXT_ACTION=CLASSIFY_COMPLETED_COMPARISON_RESULT'
else
  printf '%s\n' \
    'CONTROLLED_COMPARISON_OUTPUT_CAPTURED=PARTIAL_OR_MISSING' \
    'FINAL_COMPARISON_SUMMARY_CAPTURED=NO' \
    'NEXT_ACTION=COPY_FROM_CONTROLLED_RUN_1_THROUGH_FINAL_ACCEPTANCE_BOUNDARY_IN_ORIGINAL_TTYS168_AND_RERUN_THIS_SCRIPT'
fi

printf '\n=== FULL CAPTURE ===\n'
cat "$OUT"

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'NEW_EXPERIMENT=NO' \
  'PRODUCTION_CHANGE=NO' \
  'VALIDATOR_CHANGE=NO' \
  'GENERATION_POLICY_CHANGE=NO'

printf '\n=== WORKTREE ===\n'
git status --short
