#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=80f5b080' \
  'ISSUE_RESOLVED=NO' \
  'LIVE_BACKEND_API=PASS' \
  'TURN_PERSISTENCE=PASS' \
  'UNSUPPLIED_REFERENCE_REJECTION=NOT_OBSERVED_ON_LATEST_LIVE_API_PASS' \
  'DASHBOARD_CLIENT_5173=HEALTHY_VIA_LOCALHOST' \
  'DASHBOARD_CLIENT_BINDING=IPV6_LOCALHOST' \
  'PREVIOUS_127_0_0_1_CLIENT_HEALTH_CHECK=FALSE_NEGATIVE' \
  'NEXT_ACTION=VERIFY_DASHBOARD_PROXY_CHAT_VIA_LOCALHOST_5173' \
  'DELEGATION_WORKSPACE=PAUSED' \
  'SAFE_TO_STEP_AWAY=YES'

printf '\n=== WORKTREE ===\n'
git status --short
