#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="8c9f8d90f67a1d8c77ed9fa6d0b42cdccb1e3b80"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD" ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — MINIMUM ACTIVATION OWNER CLASSIFICATION ==="
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo "RECOVERY_POINT=DR_20260827_140611"
echo

echo "=== EVIDENCE-BASED CANDIDATE DETERMINATION ==="
echo "CANDIDATE_A_PEC_RUNTIME_BINDER=REJECT"
echo "CANDIDATE_A_REASON=OWNS_TASK_GRAPH_BINDING_NOT_PRODUCTION_EXECUTION_AUTHORITY_COMPOSITION"
echo
echo "CANDIDATE_C_GOVERNANCE_ENVELOPE_ENTRY_POINT=REJECT"
echo "CANDIDATE_C_REASON=EXPLICITLY_CREATES_CANONICAL_ENVELOPE_WITH_EXECUTION_AND_ORCHESTRATION_DISABLED"
echo
echo "CANDIDATE_D_GOVERNED_PLANNING_PIPELINE=REJECT"
echo "CANDIDATE_D_REASON=EXPLICIT_PLANNING_ONLY_BOUNDARY_MUST_NOT_BE_COLLAPSED_INTO_PRODUCTION_EXECUTION"
echo
echo "CANDIDATE_B_NEW_NARROW_PRODUCTION_EXECUTION_ENTRY_POINT=SELECT"
echo "CANDIDATE_B_REASON=SMALLEST_COHERENT_OWNER_THAT_CAN_COMPOSE_EXISTING_VERIFIED_COMPONENTS_WITHOUT_REDEFINING_THEIR_AUTHORITY"
echo

echo "=== EXISTING PRODUCTION ENTRY-POINT BOUNDARIES ==="
echo "PACKAGE_ENTRY_POINT_EXECUTION_AUTHORIZED=NO"
echo "DELEGATION_ENTRY_POINT_EXECUTION_AUTHORIZED=NO"
echo "VALIDATION_ENTRY_POINT_EXECUTION_AUTHORIZED=NO"
echo "ENVELOPE_GATE_ENTRY_POINT_EXECUTION_AUTHORIZED=NO"
echo "ENVELOPE_ENTRY_POINT_EXECUTION_AUTHORIZED=NO"
echo "LIFECYCLE_ENTRY_POINT_EXECUTION_AUTHORIZED=NO"
echo "EXISTING_CANONICAL_GOVERNANCE_ENTRY_POINTS_MUST_REMAIN_NON_EXECUTING=YES"
echo

echo "=== SELECTED OWNER ==="
echo "ACTIVATION_OWNER=NEW_NARROW_PRODUCTION_EXECUTION_ENTRY_POINT"
echo "OWNER_ROLE=COMPOSITION_ONLY"
echo "OWNER_CREATES_AUTHORITY=NO"
echo "OWNER_CREATES_APPROVAL=NO"
echo "OWNER_CREATES_PACKAGE=NO"
echo "OWNER_REBUILDS_CANONICAL_ENVELOPE=NO"
echo "OWNER_USES_GENERIC_CADE_EXECUTOR=NO"
echo "OWNER_USES_GENERIC_SHELL=NO"
echo "OWNER_ENABLES_SCHEDULER=NO"
echo "OWNER_ENABLES_AUTONOMY=NO"
echo

echo "=== REQUIRED INPUTS ==="
echo "INPUT_1=AUTHORITATIVE_CANONICAL_EXECUTION_ENVELOPE"
echo "INPUT_2=DURABLE_USER_EXECUTION_AUTHORIZATION"
echo "INPUT_3=AUTHORITATIVE_EXECUTION_APPROVAL_ARTIFACT"
echo "INPUT_4=CALLER_SUPPLIED_EXECUTION_ID"
echo "INPUT_5=REQUESTED_VERSION_CONTROL_EFFECT_SCOPE"
echo

echo "=== REQUIRED COMPOSITION ==="
echo "STEP_1=VERIFY_CANONICAL_ENVELOPE_AND_GOVERNANCE_LINEAGE"
echo "STEP_2=VERIFY_DURABLE_USER_EXECUTION_AUTHORIZATION"
echo "STEP_3=EVALUATE_EXISTING_EXECUTION_APPROVAL_GATE"
echo "STEP_4=REQUIRE_EXISTING_COMMIT_AUTHORITY_IF_COMMIT_REQUESTED"
echo "STEP_5=CALL_EXISTING_GOVERNED_CADE_COMMIT_ADAPTER"
echo "STEP_6=RETURN_AFTER_COMMIT_IF_PUSH_NOT_REQUESTED"
echo "STEP_7=REEVALUATE_EXISTING_APPROVAL_GATE_WITH_CORRELATED_LOCAL_COMMIT_PROOF"
echo "STEP_8=REQUIRE_SEPARATELY_PROVEN_PUSH_AUTHORITY"
echo "STEP_9=CALL_EXISTING_GOVERNED_CADE_PUSH_ADAPTER"
echo "STEP_10=RETURN_CORRELATED_EFFECT_PROOFS"
echo

echo "=== FAIL-CLOSED BOUNDARY ==="
echo "FAIL_IF=CANONICAL_ENVELOPE_INVALID_OR_LINEAGE_MISMATCH"
echo "FAIL_IF=USER_EXECUTION_AUTHORIZATION_ABSENT_OR_INVALID"
echo "FAIL_IF=APPROVAL_GATE_NOT_OK"
echo "FAIL_IF=COMMIT_REQUESTED_WITHOUT_COMMIT_AUTHORITY"
echo "FAIL_IF=COMMIT_EFFECT_FAILS"
echo "FAIL_IF=PUSH_REQUESTED_WITHOUT_CORRELATED_SUCCESSFUL_LOCAL_COMMIT"
echo "FAIL_IF=PUSH_AUTHORITY_NOT_SEPARATELY_PROVEN"
echo "FAIL_IF=PUSH_EFFECT_FAILS"
echo "FAIL_IF=REPOSITORY_STATE_OR_AUTHORIZED_BRANCH_REMOTE_MISMATCH"
echo

echo "=== REACHABILITY BOUNDARY ==="
echo "NEW_OWNER_ROUTE_MOUNT_REQUIRED_IN_SAME_IMPLEMENTATION_UNIT=NO"
echo "NEW_OWNER_MAY_BE_IMPLEMENTED_UNMOUNTED=YES"
echo "PRODUCTION_REACHABILITY_REQUIRES_SEPARATE_EXPLICIT_DECISION=YES"
echo "UNMOUNTED_OWNER_ALONE_SATISFIES_PHASE_1_PRODUCTION_REACHABILITY_OUTCOME=NO"
echo

echo "=== MINIMUM IMPLEMENTATION DETERMINATION ==="
echo "MINIMUM_IMPLEMENTATION_UNIT=BOUNDED_PRODUCTION_EXECUTION_ENTRY_POINT_PLUS_TESTS"
echo "EXISTING_AUTHORITY_MODELS_REUSED=YES"
echo "EXISTING_GOVERNED_GIT_EFFECTS_REUSED=YES"
echo "EXISTING_CANONICAL_LINEAGE_REUSED=YES"
echo "NEW_AUTHORITY_REQUIRED=NO"
echo "NEW_GIT_PRIMITIVE_REQUIRED=NO"
echo "NEW_APPROVAL_MODEL_REQUIRED=NO"
echo

echo "=== CORRIDOR 6 STATUS ==="
echo "CORRIDOR_6=SELF_IMPROVEMENT_EXECUTION_ACTIVATION_CLOSURE"
echo "CORRIDOR_6_STATUS=IMPLEMENTATION_SCOPE_DETERMINED"
echo "PHASE_1_STATUS=ACTIVE"
echo "IMPLEMENTATION_REQUIRED=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "NO_IMPLEMENTATION_PERFORMED=YES"
echo "NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION_FOR_BOUNDED_PRODUCTION_EXECUTION_ENTRY_POINT_IMPLEMENTATION"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
