#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="22222df1b"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — NEW ROUTE RUNTIME BOUNDARY CLASSIFICATION ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo "PRIOR_FAILED_HYPOTHESIS_SEQUENCE=CLOSED"
echo

echo "=== VERIFIED REASSESSMENT FACTS ==="
echo "SOURCE_APPROVAL_GATE_IMPORT=PASS"
echo "COMPILED_APPROVAL_GATE_ARTIFACT=ABSENT"
echo "PRODUCTION_EXECUTION_ENTRY_POINT_PRESENT=YES"
echo "PRODUCTION_EXECUTION_EFFECTS_REQUIRE_EXPLICIT_APPROVAL_EVALUATOR_BINDING=YES"
echo "DURABLE_APPROVAL_READER_PRESENT=YES"
echo "DURABLE_EXECUTION_SCOPE_READER_PRESENT=YES"
echo "DURABLE_GOVERNANCE_READ_CHAIN_PRESENT=YES"
echo "ROUTE_IMPLEMENTATION_PRESENT=NO"
echo "ROUTE_MOUNTED=NO"
echo "PRODUCTION_REACHABILITY_CHANGED=NO"
echo

echo "=== DIRECT RUNTIME BOUNDARY ==="
echo "PREVIOUS_ASSUMPTION_SOURCE_APPROVAL_GATE_IS_BROKEN=NOT_SUPPORTED_BY_CURRENT_STABLE_BASE"
echo "CURRENT_SOURCE_APPROVAL_GATE_RUNTIME=AVAILABLE_UNDER_REPOSITORY_TSX_RUNTIME"
echo "TEMP_EXTERNAL_SOURCE_TREE_RECONSTRUCTION_REQUIRED=NO"
echo "TEMP_IMPORT_REWRITING_REQUIRED=NO"
echo "TEST_HARNESS_FILE_URI_ADAPTATION_REQUIRED=NO"
echo

echo "=== ROUTE COMPOSITION OWNERSHIP ==="
echo "Q1_IS_UNMOUNTED_ROUTE_STILL_MINIMUM_SAFE_OWNER=YES"
echo "Q2_CAN_ROUTE_BE_TESTED_WITHOUT_EXTERNAL_TEMP_RUNTIME=YES"
echo "Q3_SHOULD_APPROVAL_GATE_BE_ROUTE_DEPENDENCY=YES_FOR_EXPLICIT_COMPOSITION_AND_TEST_ISOLATION"
echo "Q4_DOES_DEPENDENCY_INJECTION_PRESERVE_APPROVAL_SEMANTICS=YES_IF_DEFAULT_BINDING_IS_EXISTING_EVALUATOR"
echo "Q5_DEFAULT_PRODUCTION_BINDING_REQUIRES_SEPARATE_RUNTIME_REPAIR=NO_EVIDENCE_ESTABLISHED"
echo "Q6_CAN_UNMOUNTED_ROUTE_AND_SERVER_MOUNT_REMAIN_SEPARATE=YES"
echo

echo "=== MINIMUM NEW ROUTE DESIGN ==="
echo "ROUTE_ROLE=READ_VALIDATE_RECONSTRUCT_COMPILE_BIND_AND_INVOKE"
echo "ROUTE_INPUT_AUTHORITY=IDENTIFIERS_AND_REQUESTED_EFFECTS_ONLY"
echo "APPROVAL_SOURCE=DURABLE_GOVERNANCE_EXECUTION_APPROVAL"
echo "EXECUTION_SCOPE_SOURCE=DURABLE_GOVERNANCE_EXECUTION_SCOPE"
echo "GOVERNANCE_SOURCE=DURABLE_DELEGATION_VALIDATION_GATE_ENVELOPE_CHAIN"
echo "APPROVAL_COMPILER=compilePersistedExecutionApproval"
echo "APPROVAL_EVALUATOR=evaluateExecutionApproval"
echo "EXECUTION_ENTRY_POINT=executeProductionExecutionEntryPoint"
echo
echo "DEPENDENCY_INJECTION_BOUNDARY="
echo "  approval_reader"
echo "  execution_scope_reader"
echo "  governance_chain_reader"
echo "  approval_compiler"
echo "  approval_evaluator"
echo "  execution_entry_point"
echo

echo "=== TEST MODEL ==="
echo "TEST_RUNTIME=REPOSITORY_NATIVE_TSX"
echo "EXTERNAL_TEMP_COPY=NO"
echo "IMPORT_REWRITE=NO"
echo "REAL_GIT_EFFECTS=NO"
echo "IN_MEMORY_DATABASE=YES"
echo "INJECTED_EXECUTION_ENTRY_POINT=YES"
echo "INJECTED_APPROVAL_EVALUATOR_ALLOWED_FOR_ISOLATED_ROUTE_TESTS=YES"
echo "DEFAULT_APPROVAL_EVALUATOR_MUST_REMAIN_EXISTING_EVALUATE_EXECUTION_APPROVAL=YES"
echo

echo "=== INPUT FAIL-CLOSED POLICY ==="
echo "ALLOW_APPROVAL_ID=YES"
echo "ALLOW_ENVELOPE_ID=YES"
echo "ALLOW_EXECUTION_ID=YES"
echo "ALLOW_COMMIT_REQUESTED=YES"
echo "ALLOW_PUSH_REQUESTED=YES"
echo "ALLOW_COMMIT_MESSAGE=YES_IF_COMMIT_REQUESTED"
echo "ALLOW_EXPECTED_REMOTE_URL=YES_IF_PUSH_REQUESTED"
echo "CLIENT_APPROVED_BY=REJECT"
echo "CLIENT_COMMIT_AUTHORIZED=REJECT"
echo "CLIENT_PUSH_AUTHORIZED=REJECT"
echo "CLIENT_PACKAGE_AUTHORITY=REJECT"
echo "CLIENT_ENVELOPE_CONTENT=REJECT"
echo "CLIENT_GOVERNANCE_ARTIFACT=REJECT"
echo "CLIENT_DELEGATION_STATE=REJECT"
echo

echo "=== AUTHORITY / REACHABILITY BOUNDARY ==="
echo "NEW_AUTHORITY_CREATED=NO"
echo "GENERIC_CADE_REACHABILITY=NO"
echo "GENERIC_MUTATION_AUTHORITY=NO"
echo "GENERIC_SHELL_AUTHORITY=NO"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=NO"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "SERVER_INDEX_CHANGE_AUTHORIZED=NO"
echo

echo "=== AUTHORIZATION STATUS ==="
echo "PRIOR_UNMOUNTED_ROUTE_USER_AUTHORIZATION_EXISTS=YES"
echo "PRIOR_ROUTE_AUTHORIZATION_SURVIVED_ROLLBACK=YES"
echo "NEW_RUNTIME_REPAIR_UNIT_REQUIRED=NO"
echo "NEW_ROUTE_SCOPE_EXPANSION_REQUIRED=NO"
echo "IMPLEMENTATION_MAY_RESUME_ONLY_WITHIN_PREVIOUSLY_AUTHORIZED_UNMOUNTED_ROUTE_SCOPE=YES"
echo

echo "=== RESULT ==="
echo "NEW_ROUTE_RUNTIME_BOUNDARY_CLASSIFIED=YES"
echo "MINIMUM_SAFE_ROUTE_MODEL=UNMOUNTED_DEPENDENCY_INJECTED_COMPOSITION_ROUTE"
echo "PREVIOUS_TEMP_RUNTIME_HYPOTHESES=RETIRED"
echo "CORRIDOR_6_STATUS=ACTIVE"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=RESUME_PREVIOUSLY_AUTHORIZED_UNMOUNTED_ROUTE_IMPLEMENTATION_USING_REPOSITORY_NATIVE_RUNTIME_AND_DEPENDENCY_INJECTION"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
