#!/usr/bin/env bash
set -euo pipefail

cd "/Users/marcela-dev/Projects/motherboard-systems-hq-clean"

BRANCH="feature/support-source-references-runtime"
BASELINE="711dfc3e0"
WORKFLOW="server/matilda-chat-workflow.ts"
COMPOSER="server/matilda-conversation-context-runtime.ts"
INTEGRATION_TEST="server/matilda-chat-workflow.explicit-target.integration.test.ts"

git fetch origin "$BRANCH"
test "$(git rev-parse --short=9 HEAD)" = "$BASELINE"
test "$(git rev-parse --short=9 "origin/$BRANCH")" = "$BASELINE"
test -z "$(git diff --cached --name-only)"

echo "===== SEMANTIC HISTORY — EXACT BACKFILL LOOP CLASSIFICATION ====="
echo "MODE=READ_ONLY_CLASSIFICATION"
echo "BATCH_SIZE=20"
echo "HARD_SCAN_CEILING=75"
echo "TARGET_SELECTED_HISTORY=20"

echo
echo "===== VERIFIED COMPOSER PROPERTIES ====="
grep -n -A90 -B10 \
  'export function composeMatildaConversationContext' \
  "$COMPOSER"

echo
echo "===== VERIFIED WORKFLOW INSERTION REGION ====="
sed -n '175,260p' "$WORKFLOW"

echo
echo "===== VERIFIED INTEGRATION HARNESS SETUP ====="
sed -n '1,380p' "$INTEGRATION_TEST"

echo
echo "===== LOOP CLASSIFICATION ====="
echo "Q1_COMPOSER_SIDE_EFFECTS=NONE_OBSERVED"
echo "Q2_STOP_CONDITION=SELECTED_HISTORY_LENGTH_GTE_20"
echo "Q3_SCAN_COUNTER=RAW_TURNS_RETRIEVED"
echo "Q4_HARD_STOP=RAW_TURNS_SCANNED_GTE_75"
echo "Q5_PAGE_CURSOR=OLDEST_RETRIEVED_PAGE_TURN_CREATED_AT_PLUS_TURN_ID"
echo "Q6_NEXT_PAGE_SIZE=MIN_20_OR_REMAINING_SCAN_CAPACITY"
echo "Q7_EXHAUSTION_SIGNAL=PAGE_LENGTH_LT_REQUESTED_PAGE_SIZE"
echo "Q8_ACCUMULATION_ORDER=OLDER_PAGE_PREPENDED_TO_EXISTING_NEWER_TURNS"
echo "Q9_FINAL_SELECTED_BOUND=NEWEST_20_ELIGIBLE_AFTER_COMPOSITION"
echo "Q10_IEL_LOOKUP=FINAL_ACCUMULATED_TURN_IDS"
echo "Q11_LIFECYCLE_SELECTION=UNCHANGED"
echo "Q12_PROJECT_CONTEXT_RETRIEVAL=ONCE"
echo "Q13_OLLAMA_INVOCATION=ONCE"

echo
echo "===== IMPORTANT ORDERING BOUNDARY ====="
echo "PRIOR_USER_MESSAGE_SOURCE=NEWEST_ACCUMULATED_TURN"
echo "DO_NOT_REPLACE_PRIOR_USER_MESSAGE_WITH_OLDEST_BACKFILLED_TURN=YES"
echo "GLOBAL_ACCUMULATION_CHRONOLOGY=OLDEST_TO_NEWEST"
echo "FINAL_HISTORY_CHRONOLOGY=OLDEST_TO_NEWEST"
echo "FINAL_HISTORY_SELECTION=NEWEST_20_ELIGIBLE"

echo
echo "===== REGRESSION TEST INSERTION ====="
echo "PRIMARY_TEST=$INTEGRATION_TEST"
echo "TEST_1=MORE_THAN_20_RAW_TURNS_WITH_RECENT_INELIGIBLE_HISTORY_TRIGGERS_BACKFILL"
echo "TEST_2=NEWEST_20_ELIGIBLE_TURNS_RECOVERED_WITHIN_75_SCAN_BOUND"
echo "TEST_3=SCAN_NEVER_EXCEEDS_75"
echo "TEST_4=DUPLICATE_TIMESTAMP_CURSOR_BOUNDARY_DOES_NOT_DUPLICATE_OR_SKIP"
echo "TEST_5=FINAL_SELECTED_HISTORY_CHRONOLOGY_PRESERVED"
echo "TEST_6=PRIOR_SUPPORT_PROVENANCE_REMAINS_NEWEST_SELECTED_HISTORY_TURN"
echo "TEST_7=OLLAMA_INVOCATION_COUNT_EQUALS_1"
echo "TEST_8=EXHAUSTED_HISTORY_STOPS_BEFORE_75"

echo
echo "===== IMMUTABLE CONTRACTS ====="
echo "AUTHORITY_ADMISSION_CHANGE=NO"
echo "CONTAMINATION_ADMISSION_CHANGE=NO"
echo "SEMANTIC_RANKING=NO"
echo "READER_CHANGE=NO"
echo "IEL_SCHEMA_CHANGE=NO"
echo "PERSISTENCE_SCHEMA_CHANGE=NO"
echo "OLLAMA_CHANGE=NO"
echo "ONE_MESSAGE_ONE_WORKFLOW=YES"
echo "ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=YES"

echo
echo "===== IMPLEMENTATION READINESS QUESTION ====="
echo "QUESTION=DO_VERIFIED_SOURCE_AND_TEST_HARNESS_SUPPORT_THIS_LOOP_WITHOUT_NEW_ARCHITECTURAL_SURFACE"
echo "NEXT_ACTION=IF_YES_IMPLEMENT_WORKFLOW_BACKFILL_AND_BEHAVIORAL_REGRESSION_TESTS_WITHIN_AUTHORIZED_POLICY"

echo
echo "SOURCE_CHANGE=NONE"
echo "STAGING=NONE"
echo "COMMIT=NONE"
echo "PUSH=NONE"

echo
echo "===== WORKTREE ====="
git status --short
