#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 — BOUNDED CLOSURE READINESS CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor c0be30e9 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-bounded-closure-readiness\.sh$|^ M scripts/classify-phase-3-bounded-closure-readiness\.sh$' ||
  true
)"
test -z "$unexpected"

npx tsx --test scripts/utils/ollamaChat.explanation-status.test.ts
npx tsx --test scripts/utils/ollamaChat.reasoning-status-surfacing.test.ts
bash scripts/guard-ollama-response-contract.sh
git diff --check

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
STATUS=BOUNDED_CLOSURE_READINESS_CLASSIFIED

CORRIDOR_1=CLASSIFICATION_RULE
CORRIDOR_1_STATUS=CLOSED

CORRIDOR_2=BEHAVIOR_VALIDATION
CORRIDOR_2_STATUS=DEFERRED_WITH_EXPLICIT_UNRESOLVED_BEHAVIORAL_RELIABILITY_LIMIT

CORRIDOR_3=SURFACING_CONTRACT
CORRIDOR_3_STATUS=CLOSED
CORRIDOR_3_DR=20260818_100454

CORRIDOR_4=PRODUCTION_VALIDATION_AND_CLOSURE
CORRIDOR_4_CONTRACT_INTEGRITY=VALIDATED

CLASSIFICATION_CONTRACT=PASS
SURFACING_CONTRACT=PASS
RESPONSE_CONTRACT_GUARD=PASS
INVESTIGATION_LIFECYCLE_GUARD=PASS
SINGLE_OLLAMA_INVOCATION=PRESERVED
PRODUCTION_VALIDATION_SEED=ABSENT
FAIL_CLOSED_VALIDATION=PRESERVED
VISIBLE_REASONING_STATUS_LABEL=NO

MODEL_BEHAVIORAL_RELIABILITY=NOT_ESTABLISHED
FOURTH_MODEL_VALIDATION_ATTEMPT=NOT_RUN
REASONING_STATUS_DEFECT_ESTABLISHED=NO
FAIL_CLOSED_VALIDATOR_MALFUNCTION_ESTABLISHED=NO

PHASE_3_FULL_BEHAVIORAL_RELIABILITY_CLOSURE=NOT_JUSTIFIED
PHASE_3_BOUNDED_CLOSURE=READY
PHASE_3_CLOSURE_CONDITION=EXPLICITLY_CARRY_FORWARD_CORRIDOR_2_DEFERRED_BEHAVIORAL_RELIABILITY_LIMIT
PRODUCTION_CHANGE=NONE
DR_NOW=NO
NEXT_ACTION=CLOSE_CORRIDOR_4_AND_PHASE_3_WITH_SINGLE_CANONICAL_DR_PRESERVING_THE_DEFERRED_RELIABILITY_LIMIT
MAP
