#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD_PREFIX="cc4fea97d"
CURRENT_HEAD="$(git rev-parse HEAD)"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "EXPECTED_HEAD_PREFIX=${EXPECTED_HEAD_PREFIX}"
  echo "CURRENT_HEAD=${CURRENT_HEAD}"
  exit 1
fi

echo "=== CORRIDOR 6 — APPROVAL PERSISTENCE INSERTION BOUNDARY CLASSIFICATION ==="
echo "MODE=EXECUTION"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo

echo "=== VERIFIED DATABASE OWNERSHIP ==="
echo "GOVERNANCE_DATABASE_OWNER=db/governance-runtime.ts"
echo "GOVERNANCE_DATABASE_PATH=db/main.db"
echo "GOVERNANCE_TABLE_INITIALIZER=ensureGovernanceRuntimeTables"
echo "NEW_DATABASE_OWNER_REQUIRED=NO"
echo "EXISTING_GOVERNANCE_SCHEMA_EXTENSION_AVAILABLE=YES"
echo

echo "=== VERIFIED ENVELOPE BINDING ==="
echo "GOVERNANCE_ENVELOPE_IS_DURABLE=YES"
echo "ENVELOPE_PRIMARY_ID=envelope_id"
echo "ENVELOPE_PACKAGE_BINDING=package_id_plus_package_version"
echo "APPROVAL_WRITE_CAN_VALIDATE_EXACT_ENVELOPE_BEFORE_INSERT=YES"
echo "APPROVAL_REPLAY_ACROSS_DIFFERENT_ENVELOPE_MUST_FAIL=YES"
echo

echo "=== VERIFIED APPROVAL WRITE MODEL ==="
echo "APPROVAL_RECORD_MODEL=IMMUTABLE_INSERT_ONLY"
echo "APPROVAL_ID_PRIMARY_KEY=YES"
echo "APPROVAL_STATUS_REQUIRED=approved"
echo "APPROVED_BY_REQUIRED=YES"
echo "APPROVED_AT_REQUIRED=YES"
echo "COMMIT_AUTHORIZED_EXPLICIT=YES"
echo "PUSH_AUTHORIZED_EXPLICIT=YES"
echo "PUSH_IMPLIED_BY_COMMIT=NO"
echo "USER_OWNED_DECISION_REQUIRED=YES"
echo "MATILDA_SELF_APPROVAL=FORBIDDEN"
echo "CADE_SELF_APPROVAL=FORBIDDEN"
echo

echo "=== VERIFIED READER MODEL ==="
echo "READER_MODE=READ_ONLY_FAIL_CLOSED"
echo "READER_LOOKUP=approval_id_plus_envelope_id"
echo "ZERO_MATCH=FAIL_CLOSED"
echo "ENVELOPE_MISMATCH=FAIL_CLOSED"
echo "PACKAGE_OR_VERSION_MISMATCH=FAIL_CLOSED"
echo "NON_APPROVED_STATUS=FAIL_CLOSED"
echo "AMBIGUOUS_MATCH=FAIL_CLOSED"
echo

echo "=== VERIFIED COMPILER MODEL ==="
echo "COMPILER_TARGET=EXISTING_EXECUTION_APPROVAL_ARTIFACT_SHAPE"
echo "COMPILER_CREATES_AUTHORITY=NO"
echo "COMPILER_REINTERPRETS_USER_INTENT=NO"
echo "COMPILER_OUTPUT_LIMITED_TO_EXISTING_GATE_FIELDS=YES"
echo "EXISTING_EXECUTION_APPROVAL_GATE_REUSED=YES"
echo

echo "=== VERIFIED TEST ISOLATION ==="
echo "IN_MEMORY_SQLITE_PATTERN_EXISTS=YES"
echo "TEMPORARY_DATABASE_PATTERN_EXISTS=YES"
echo "ACTIVE_DB_MAIN_DB_MUTATION_REQUIRED_FOR_TESTS=NO"
echo "SELECTED_TEST_PATTERN=IN_MEMORY_SQLITE_DEPENDENCY_INJECTION"
echo

echo "=== IMPLEMENTATION TARGET CLASSIFICATION ==="
echo "TARGET_1=db/governance-runtime.ts"
echo "TARGET_2=server/execution/compile-persisted-execution-approval.mjs"
echo "TARGET_3=TARGETED_TEST_FILES"
echo "SCHEMA_ADDITION=GOVERNANCE_EXECUTION_APPROVALS_TABLE"
echo "WRITE_UNIT=USER_OWNED_APPROVED_EXECUTION_APPROVAL_INSERT"
echo "READ_UNIT=FAIL_CLOSED_APPROVAL_ID_AND_ENVELOPE_READER"
echo "COMPILER_UNIT=PERSISTED_RECORD_TO_EXISTING_GATE_ARTIFACT"
echo

echo "=== STILL EXCLUDED ==="
echo "EXECUTION_ROUTE_CHANGE=NO"
echo "ROUTE_MOUNT_CHANGE=NO"
echo "PRODUCTION_REACHABILITY_CHANGE=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGE=NO"
echo "REMOTE_PUSH_EFFECT_CHANGE=NO"
echo "GENERIC_CADE_CHANGE=NO"
echo "SCHEDULER_OR_AUTONOMY_CHANGE=NO"
echo "PARALLEL_APPROVAL_SYSTEM=NO"
echo "CORRIDOR_2_REOPEN=NO"
echo

echo "=== IMPLEMENTATION DETERMINATION ==="
echo "Q1_NEW_TABLE_WITHIN_EXISTING_GOVERNANCE_OWNER=YES"
echo "Q2_EXISTING_VALIDATION_HELPERS_REUSABLE=YES"
echo "Q3_EXACT_ENVELOPE_BINDING_VALIDATABLE=YES"
echo "Q4_IMMUTABLE_INSERT_ONLY_RECORD=YES"
echo "Q5_FAIL_CLOSED_APPROVAL_AND_ENVELOPE_READER=YES"
echo "Q6_EXISTING_GATE_SHAPE_COMPILER=YES"
echo "Q7_ISOLATED_TEST_PATTERN_AVAILABLE=YES"
echo
echo "IMPLEMENTATION_BOUNDARY_CONFIRMED=YES"
echo "SPECULATIVE_SCHEMA_PATCHING_REQUIRED=NO"
echo "AUTHORIZED_IMPLEMENTATION_MAY_PROCEED=YES"
echo "NEXT_ACTION=IMPLEMENT_APPROVAL_PERSISTENCE_WRITE_READER_COMPILER_AND_TARGETED_TESTS"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
