#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'COMPLETED_PHASE=EXECUTIVE_MISSION_OVERVIEW' \
  'SUCCESSOR_PHASE=DELEGATION_WORKSPACE' \
  'SUCCESSOR_CLASSIFICATION_COMMIT=4d9e8ae1' \
  'MODE=COLLABORATION' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'PURPOSE=CLASSIFY_EXISTING_DELEGATION_WORKSPACE_CAPABILITY_BEFORE_DEFINING_CORRIDORS'

printf '\n=== DELEGATION WORKSPACE ARCHITECTURE ===\n'
sed -n '1,180p' docs/architecture/EXECUTIVE_WORKSPACE_MODEL.md

printf '\n=== EXECUTIVE INBOX AUTHORITY BOUNDARY ===\n'
cat docs/architecture/EXECUTIVE_CLIENT_SERVER_AUTHORITY_BOUNDARY.md

printf '\n=== EXISTING EXECUTIVE INBOX RUNTIME CHECKPOINTS ===\n'
for file in \
  docs/checkpoints/EXECUTIVE_INBOX_APPROVAL_RUNTIME_COMPLETE.md \
  docs/checkpoints/EXECUTIVE_INBOX_BACKEND_RECOVERY_DR_20260801_174748.md
do
  if [ -f "$file" ]; then
    echo "=== $file ==="
    cat "$file"
  fi
done

printf '\n=== EXECUTIVE INBOX CLIENT SURFACE ===\n'
find client/src -type f \
  \( -iname '*Inbox*' -o -iname '*Approval*' -o -iname '*Delegation*' \) \
  -print | sort

printf '\n=== EXECUTIVE INBOX SERVER AND ROUTE SURFACE ===\n'
grep -Rni --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=.next \
  -E 'Executive Inbox|executive-inbox|approval request|ApprovalRequest|request changes|governance_delegations' \
  server routes db client/src 2>/dev/null | head -320

printf '\n=== EXISTING CAPABILITY CLASSIFICATION ===\n'
printf '%s\n' \
  'DELEGATION_WORKSPACE_IS_GREENFIELD=NO' \
  'EXECUTIVE_INBOX_ALREADY_EXISTS=YES' \
  'APPROVAL_RUNTIME_ALREADY_EXISTS=YES' \
  'AUTHORITATIVE_BACKEND_ROUTE_PREVIOUSLY_RECOVERED=YES' \
  'REQUEST_CHANGES_ARCHITECTURE_EXISTS=YES' \
  'MISSION_CONTROL_AND_DELEGATION_RESPONSIBILITIES=MUST_REMAIN_SEPARATE' \
  'DELEGATION_REMAINS_USER_INITIATED=YES' \
  'OPENING_OR_REVIEWING_MESSAGE_MUTATES_STATE=NO' \
  'ONLY_EXPLICIT_AUTHORIZATION_MUTATES_ORGANIZATIONAL_STATE=YES' \
  'NEW_SEMANTIC_AUTHORITY_MAY_NOT_BE_INVENTED=YES' \
  'NEXT_STEP=RECONCILE_EXISTING_EXECUTIVE_INBOX_AGAINST_DELEGATION_WORKSPACE_TARGET'

printf '\n=== PROVISIONAL CORRIDOR CANDIDATES ===\n'
printf '%s\n' \
  'C1=EXISTING_EXECUTIVE_INBOX_RECONCILIATION' \
  'C2=DELEGATION_DECISION_PROJECTION' \
  'C3=EXPLICIT_DELEGATION_AUTHORIZATION' \
  'C4=REQUEST_CHANGES_AND_ORIGINATING_CONVERSATION_HANDOFF' \
  'C5=PROJECT_SCOPE_AND_MISSION_CONTROL_HANDOFF' \
  'C6=DELEGATION_WORKSPACE_VALIDATION_AND_CLOSURE' \
  'CORRIDOR_MAP_STATUS=PROVISIONAL_PENDING_REPOSITORY_RECONCILIATION'

printf '\n=== WORKTREE ===\n'
git status --short
