#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY CORRIDOR 4: CONSTRAINT PRESERVATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 17ffaa57 HEAD
test -z "$(git status --porcelain)"

source_file="scripts/record-corridor-3-dr-closure-and-enter-corridor-4.sh"
test -f "$source_file"

for invariant in \
  FAIL_CLOSED_VALIDATION \
  SUPPORT_PROVENANCE_CONTRACT \
  SELECTED_CONTEXT_SEGMENT_CONTRACT \
  USER_INTENT_AUTHORITY \
  MATILDA_INTERPRETATION_AUTHORITY \
  REPLY_AND_DURABLE_INTERPRETATION_SEPARATION \
  WORKFLOW_OWNED_IEL_PERSISTENCE \
  CONVERSATION_CONTEXT_BOUNDARY \
  PRIOR_INVESTIGATION_LIFECYCLE_CONTEXT_BOUNDARY \
  LIVING_DRAFT_DERIVATION_BOUNDARY \
  APPROVAL_PIPELINE_AUTHORITY_BOUNDARY \
  ONE_USER_MESSAGE_ONE_WORKFLOW \
  ONE_WORKFLOW_ONE_OLLAMA_INVOCATION
do
  grep -q "^${invariant}=$" "$source_file"
  grep -q '^MUST_REMAIN_PRESERVED$' \
    <(awk -v key="${invariant}=" '$0 == key {getline; print}' "$source_file")
done

cat <<'MAP'
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

CORRIDOR_4=
CONSTRAINT_PRESERVATION

CURRENT_PRODUCTION_INTERVENTION=
EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION_AS_PRODUCTION_DEFAULT

FAIL_CLOSED_VALIDATION=
PRESERVED

SUPPORT_PROVENANCE_CONTRACT=
PRESERVED

SELECTED_CONTEXT_SEGMENT_CONTRACT=
PRESERVED

USER_INTENT_AUTHORITY=
PRESERVED

MATILDA_INTERPRETATION_AUTHORITY=
PRESERVED

REPLY_AND_DURABLE_INTERPRETATION_SEPARATION=
PRESERVED

WORKFLOW_OWNED_IEL_PERSISTENCE=
PRESERVED

CONVERSATION_CONTEXT_BOUNDARY=
PRESERVED

PRIOR_INVESTIGATION_LIFECYCLE_CONTEXT_BOUNDARY=
PRESERVED

LIVING_DRAFT_DERIVATION_BOUNDARY=
PRESERVED

APPROVAL_PIPELINE_AUTHORITY_BOUNDARY=
PRESERVED

ONE_USER_MESSAGE_ONE_WORKFLOW=
PRESERVED

ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=
PRESERVED

MODEL_CHANGE=
NONE

GENERATION_POLICY_CHANGE=
NONE

VALIDATOR_CHANGE=
NONE

RETRY_OR_SECOND_MODEL_CALL=
NONE

CONSTRAINT_PRESERVATION_CLASSIFICATION=
COMPLETE

NEW_PRODUCTION_CHANGE=
NONE

IMPLEMENTATION_AUTHORIZED=
NO_NEW_IMPLEMENTATION

CORRIDOR_4_STATUS=
READY_FOR_CLOSURE

DR_REQUIRED_BEFORE_NEXT_CORRIDOR=
YES

NEXT_ACTION=
STOP_FOR_CORRIDOR_4_DR_CHECKPOINT
MAP
