#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — BEHAVIOR VALIDATION SURFACE CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 4fc39c85 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-2-validation-surface\.sh$|^ M scripts/classify-phase-3-corridor-2-validation-surface\.sh$' ||
  true
)"
test -z "$unexpected"

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION
STATUS=ACTIVE

EXISTING_LIVE_HARNESS=REASONING_COMPOSITION_EXPLANATION_REQUEST_CASE
EXISTING_FIXED_SEED_HARNESS=REASONING_COMPOSITION_EXPLANATION_REQUEST_CASE
EXISTING_CLOSURE_VALIDATOR=REASONING_COMPOSITION_NOT_REASONING_STATUS_CLASSIFICATION

CURRENT_LIVE_CASE_EXPECTS=RECOMMENDED
OPTIONAL_DEFAULT_LIVE_CASE=NOT_ESTABLISHED
MATERIAL_DECISION_IMPACT_RECOMMENDED_CASE=NEEDS_EXPLICIT_VALIDATION
FALSE_POSITIVE_RECOMMENDED_CASE=NOT_ESTABLISHED

VALIDATION_GAP=ESTABLISHED
NEW_RUNTIME_CAPABILITY_REQUIRED=NO
PRODUCTION_PROMPT_CHANGE_REQUIRED=NO
STRUCTURED_ARTIFACT_CHANGE_REQUIRED=NO

REQUIRED_NEXT_VALIDATION=
ADD_BOUNDED_REASONING_STATUS_BEHAVIOR_CASES_FOR_OPTIONAL_DEFAULT_RECOMMENDED_THRESHOLD_AND_FALSE_POSITIVE_REJECTION

FIXED_SEED_ROLE=
DIAGNOSTIC_REPEATABILITY_ONLY_NOT_PRODUCTION_POLICY

DR_NOW=NO
NEXT_ACTION=BUILD_BOUNDED_BEHAVIOR_VALIDATION_HARNESS
MAP
