#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

expected_head="cfc6609e"

echo "=== CLASSIFY CANONICAL PHASE 2 DISPOSITION ==="

if [[ "$(git rev-parse --short=8 HEAD)" != "$expected_head" ]]; then
  echo "STOP: HEAD no longer matches protected Corridor 5 checkpoint $expected_head."
  exit 1
fi

unexpected="$(
  git status --short |
  grep -vE '^\?\? scripts/classify-canonical-phase-2-disposition\.sh$|^ M scripts/classify-canonical-phase-2-disposition\.sh$' ||
  true
)"

if [[ -n "$unexpected" ]]; then
  echo "STOP: unexpected working-tree changes."
  printf '%s\n' "$unexpected"
  exit 1
fi

echo "PROTECTED_BASELINE_DR=20260812_154816"

for signal in \
  'CORRIDOR=PRODUCTION_SAMPLING_POLICY' \
  'CORRIDOR=OLLAMA_GENERATION_CONTROLS' \
  'CORRIDOR=VALIDATION_VS_PRODUCTION_CONTROLS' \
  'CORRIDOR=REQUEST_VS_SHARED_POLICY' \
  'CORRIDOR=AUTHORIZATION_AND_SEMANTIC_PRESERVATION'
do
  grep -q "$signal" docs/architecture/CONVERSATION_ENGINE_GENERATION_STABILITY.md
done

grep -q 'PRODUCTION_GENERATION_POLICY_NECESSITY=NOT_ESTABLISHED' \
  docs/architecture/CONVERSATION_ENGINE_GENERATION_STABILITY.md

grep -q 'SEMANTICALLY_SAFE_PRODUCTION_POLICY=NOT_ESTABLISHED' \
  docs/architecture/CONVERSATION_ENGINE_GENERATION_STABILITY.md

grep -q 'PRODUCTION_POLICY_AUTHORIZATION=NOT_GRANTED' \
  docs/architecture/CONVERSATION_ENGINE_GENERATION_STABILITY.md

grep -q 'PRODUCTION_IMPLEMENTATION_AUTHORIZATION=NOT_GRANTED' \
  docs/architecture/CONVERSATION_ENGINE_GENERATION_STABILITY.md

if grep -q 'validationGenerationSeed' server/matilda-chat-workflow.ts; then
  echo "STOP: production workflow now supplies validationGenerationSeed."
  exit 1
fi

cat <<'FINDINGS'

MILESTONE=CONVERSATION_ENGINE_GENERATION_STABILITY
PHASE=GENERATION_POLICY_AND_CONTROL_BOUNDARY
PHASE_NUMBER=2

CANONICAL_CORRIDOR_COUNT=5
CANONICAL_CORRIDOR_STATUS=ALL_COMPLETE

PRODUCTION_GENERATION_POLICY_NECESSITY=NOT_ESTABLISHED
SEMANTICALLY_SAFE_PRODUCTION_POLICY=NOT_ESTABLISHED
PRODUCTION_GENERATION_POLICY=NOT_SELECTED
PRODUCTION_GENERATION_POLICY_CHANGE=NONE
PRODUCTION_IMPLEMENTATION=NONE

FIXED_SEED_PRODUCTION_PROMOTION=DEFERRED
MATILDA_SEMANTIC_AUTHORSHIP=PRESERVED
FAIL_CLOSED_SEMANTIC_VALIDATION=PRESERVED
CURRENT_PRODUCTION_BASELINE=UNCONFIGURED_UNSEEDED_GENERATION

PHASE_2_DISPOSITION=COMPLETE_WITH_NO_PRODUCTION_POLICY_IMPLEMENTATION
PHASE_2_STATUS=CLOSED

NEXT_PHASE=PRODUCTION_STABILITY_VALIDATION_AND_CLOSURE
NEXT_PHASE_NUMBER=3
PHASE_3_IMPLEMENTATION_AUTHORIZED=NO
NEXT_ACTION=RUN_FINAL_PHASE_2_DR_THEN_RECONCILE_PHASE_3_STARTING_BOUNDARY
FINDINGS
