#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — VALIDATION-ONLY OBSERVER IMPLEMENTATION READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 4d106e98 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-2-validation-only-observer-implementation-readiness\.sh$|^ M scripts/classify-phase-3-corridor-2-validation-only-observer-implementation-readiness\.sh$' ||
  true
)"
test -z "$unexpected"

grep -q 'observeValidatedSelectedContextSegments' scripts/utils/ollamaChat.ts
grep -q 'observeParsedSupportSourceReferences' scripts/utils/ollamaChat.ts
grep -q 'parseStructuredResponse(rawResponse)' scripts/utils/ollamaChat.ts

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION
STATUS=ACTIVE

CLASSIFIED_SURFACE=
OPTIONAL_VALIDATION_ONLY_PRE_MEMBERSHIP_SELECTED_CONTEXT_OBSERVER

PROPOSED_CALLBACK=
observeParsedSelectedContextSegments

IMPLEMENTATION_SEAM_1=
ADD_OPTIONAL_CALLBACK_TO_OLLAMA_CHAT_CONTEXT

IMPLEMENTATION_SEAM_2=
INVOKE_CALLBACK_ON_RESULT_SELECTED_CONTEXT_SEGMENTS_IMMEDIATELY_AFTER_PARSE_STRUCTURED_RESPONSE

IMPLEMENTATION_SEAM_3=
ADD_TARGETED_TEST_PROVING_CALLBACK_FIRES_BEFORE_INVALID_SELECTED_CONTEXT_MEMBERSHIP_THROWS

PRODUCTION_WORKFLOW_REFERENCE_ALLOWED=
NO

CALLBACK_REQUIRED_IN_PRODUCTION=
NO

FAIL_CLOSED_MEMBERSHIP_VALIDATION=
MUST_REMAIN_UNCHANGED

VALIDATED_SELECTED_CONTEXT_OBSERVER=
MUST_REMAIN_UNCHANGED

STRUCTURED_SCHEMA=
MUST_REMAIN_UNCHANGED

PROMPT=
MUST_REMAIN_UNCHANGED

RETRY_POLICY=
MUST_REMAIN_UNCHANGED

MODEL_INVOCATION_COUNT=
MUST_REMAIN_UNCHANGED

ROLLBACK=
REMOVE_OPTIONAL_CALLBACK_CALLBACK_INVOCATION_AND_TARGETED_TEST

IMPLEMENTATION_READINESS=
READY

IMPLEMENTATION_AUTHORIZED=
NO

THIRD_BEHAVIOR_VALIDATION_ATTEMPT=
NOT_AUTHORIZED

DR_NOW=
NO

NEXT_ACTION=
AWAIT_EXPLICIT_IMPLEMENTATION_AUTHORIZATION_FOR_BOUNDED_DIAGNOSTIC_OBSERVER
MAP
