#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=871b77a2' \
  'ACTION=CLASSIFY_EXISTING_OLLAMA_DURATION_TELEMETRY' \
  'NEW_OLLAMA_INVOCATION=NO' \
  'PRODUCTION_CHANGE=NO'

printf '\n=== VERIFIED TELEMETRY ===\n'
printf '%s\n' \
  'OLLAMA_SERVER_AVAILABLE=YES' \
  'OLLAMA_SERVER_LISTENING_127_0_0_1_11434=YES' \
  'OLLAMA_TIMING_TELEMETRY_AVAILABLE=YES' \
  'PROMPT_EVALUATION_TIMING_AVAILABLE=YES' \
  'TOKEN_GENERATION_TIMING_AVAILABLE=YES' \
  'TOTAL_REQUEST_TIMING_AVAILABLE=YES'

printf '\n=== OBSERVED TIMING PATTERN ===\n'
printf '%s\n' \
  'OBSERVED_PROMPT_TOKENS_APPROX_3722_TO_4147=YES' \
  'OBSERVED_PROMPT_EVAL_SECONDS_APPROX_10_TO_11=YES' \
  'OBSERVED_GENERATION_RATE_APPROX_33_TO_34_TOKENS_PER_SECOND=YES' \
  'OBSERVED_COMPLETED_GENERATIONS_APPROX_1336_TO_1393_TOKENS=YES' \
  'OBSERVED_COMPLETED_TOTAL_SECONDS_APPROX_50_TO_53=YES' \
  'OBSERVED_LATER_GENERATIONS_EXCEEDED_1400_DECODED_TOKENS=YES'

printf '\n=== CAUSAL CLASSIFICATION ===\n'
printf '%s\n' \
  'PROMPT_EVALUATION_ALONE_NEAR_60_SECOND_TIMEOUT=NO' \
  'RESPONSE_GENERATION_CONSUMES_MAJORITY_OF_OBSERVED_REQUEST_DURATION=YES' \
  'NORMAL_OBSERVED_REQUESTS_CAN_APPROACH_60_SECOND_CLIENT_TIMEOUT=YES' \
  'SMALL_ADDITIONAL_RESPONSE_LENGTH_OR_RUNTIME_VARIANCE_CAN_PLAUSIBLY_CROSS_TIMEOUT=YES' \
  'POST_FIX_PROMPT_SIZE_AS_PRIMARY_TIMEOUT_CAUSE_SUPPORTED=NO' \
  'GENERATION_DURATION_AS_IMMEDIATE_TIMEOUT_MECHANISM_SUPPORTED=YES' \
  'WHY_POST_FIX_RUNS_GENERATED_LONG_ENOUGH_TO_TIMEOUT=NOT_ESTABLISHED' \
  'SUPPORT_REFERENCE_FIX_VALIDATED=NO' \
  'SUPPORT_REFERENCE_FIX_DISPROVEN=NO' \
  'THIRD_IDENTICAL_VALIDATION_JUSTIFIED=NO'

printf '\n=== IMPORTANT CONTRACT LIMIT ===\n'
printf '%s\n' \
  'OLLAMA_API_RESPONSE_TYPE_CURRENTLY_CAPTURES_TIMING_FIELDS=NO' \
  'TIMING_EVIDENCE_SOURCE=EXISTING_OLLAMA_SERVER_LOG' \
  'POST_FIX_TIMEOUT_REQUEST_TO_EXACT_SERVER_TASK_MAPPING_ESTABLISHED=NO' \
  'CAUSAL_SCOPE=TIMEOUT_MECHANISM_NOT_ROOT_CAUSE'

printf '\n=== NEXT BOUNDED CLASS ===\n'
printf '%s\n' \
  'NEXT_ACTION=CORRELATE_POST_FIX_VALIDATION_TIMESTAMPS_WITH_EXISTING_OLLAMA_SERVER_LOG_TASKS_WITHOUT_GENERATION' \
  'PURPOSE=DETERMINE_WHETHER_THE_TWO_TIMEOUT_REQUESTS_CAN_BE_IDENTIFIED_AND_WHETHER_SERVER_LOGS_SHOW_PROMPT_EVAL_AND_DECODE_PROGRESS_AT_ABORT' \
  'THIRD_OLLAMA_INVOCATION_AUTHORIZED=NO' \
  'TIMEOUT_CHANGE_AUTHORIZED=NO' \
  'PROMPT_CHANGE_AUTHORIZED=NO' \
  'MODEL_CHANGE_AUTHORIZED=NO'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'OLLAMA_GENERATION_STARTED=NO' \
  'TIMEOUT_CHANGED=NO' \
  'MODEL_CHANGED=NO' \
  'VALIDATOR_CHANGED=NO' \
  'PROMPT_CHANGED=NO' \
  'GENERATION_POLICY_CHANGED=NO'

git status --short
