#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="b6cf9cde9"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — MINIMUM EXECUTION ENVELOPE DURABILITY UNIT CLASSIFICATION ==="
echo "MODE=COLLABORATION"
echo "ROUTE_IMPLEMENTATION_AUTHORIZED=YES_BUT_PAUSED"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo

echo "=== VERIFIED EXISTING AUTHORITY ==="
echo "CANONICAL_PACKAGE_APPROVED_SCOPE_DURABLE=YES"
echo "CANONICAL_PACKAGE_APPROVED_CONSTRAINTS_DURABLE=YES"
echo "CANONICAL_PACKAGE_APPROVED_EXPECTED_OUTCOME_DURABLE=YES"
echo "EXECUTION_APPROVAL_BRANCH_DURABLE=YES"
echo "EXECUTION_APPROVAL_REMOTE_DURABLE=YES"
echo "EXECUTION_APPROVAL_SCOPE_DURABLE=YES"
echo "DELEGATION_AUTHORIZATION_STATE_DURABLE=YES"
echo "DELEGATED_BY_DURABLE=YES"
echo

echo "=== VERIFIED NON-SOLUTION ==="
echo "PACKAGE_TO_EXECUTION_COMPILER_ROLE=TASK_GRAPH_COMPILER"
echo "PACKAGE_TO_EXECUTION_COMPILER_DEFINES_MUTATION_SCOPE_MAPPING=NO"
echo "PACKAGE_TO_EXECUTION_COMPILER_DEFINES_REPO_TARGET_MAPPING=NO"
echo "APPROVED_SCOPE_TO_ALLOWED_PATHS_COMPILER_ESTABLISHED=NO"
echo "APPROVED_CONSTRAINTS_TO_FORBIDDEN_PATHS_COMPILER_ESTABLISHED=NO"
echo "APPROVED_SCOPE_IS_STRUCTURED_ALLOWED_PATHS=NO"
echo "EXECUTION_APPROVAL_SCOPE_IS_STRUCTURED_MUTATION_SCOPE=NO"
echo

echo "=== VERIFIED MISSING EXECUTION AUTHORITY FIELDS ==="
echo "REPO_PATH_DURABLE_CANONICAL_SOURCE=ABSENT_FROM_CURRENT_EVIDENCE"
echo "EXPECTED_HEAD_DURABLE_CANONICAL_SOURCE=ABSENT_FROM_CURRENT_EVIDENCE"
echo "ALLOWED_PATHS_DURABLE_CANONICAL_SOURCE=ABSENT_FROM_CURRENT_EVIDENCE"
echo "FORBIDDEN_PATHS_DURABLE_CANONICAL_SOURCE=ABSENT_FROM_CURRENT_EVIDENCE"
echo "SCOPE_CONSTRAINTS_STRUCTURED_DURABLE_SOURCE=ABSENT_FROM_CURRENT_EVIDENCE"
echo
echo "BRANCH_NEW_DURABILITY_REQUIRED=NO"
echo "REMOTE_NEW_DURABILITY_REQUIRED=NO"
echo "DELEGATION_STATE_NEW_DURABILITY_REQUIRED=NO"
echo "DELEGATED_BY_NEW_DURABILITY_REQUIRED=NO"
echo

echo "=== AUTHORITY BOUNDARY ==="
echo "CANONICAL_PACKAGE_SCOPE_MUST_NOT_BE_REINTERPRETED_AS_FILE_PATH_AUTHORITY=YES"
echo "EXECUTION_APPROVAL_SCOPE_TEXT_MUST_NOT_BE_REINTERPRETED_AS_FILE_PATH_AUTHORITY=YES"
echo "PROCESS_CWD_MUST_NOT_BECOME_REPO_AUTHORITY=YES"
echo "CURRENT_GIT_HEAD_MUST_NOT_BECOME_APPROVED_EXPECTED_HEAD=YES"
echo "CLIENT_ROUTE_INPUT_MUST_NOT_CREATE_MISSING_AUTHORITY=YES"
echo "PLANNING_DRAFT_DEFAULTS_MUST_NOT_CREATE_EXECUTION_AUTHORITY=YES"
echo

echo "=== MINIMUM NEW DURABILITY UNIT ==="
echo "UNIT_REQUIRED=YES"
echo "UNIT_NAME=EXECUTION_ENVELOPE_VERSION_CONTROL_AND_MUTATION_SCOPE_DURABILITY"
echo "PURPOSE=PERSIST_EXPLICIT_USER_APPROVED_EXECUTION_TARGET_AND_MUTATION_BOUNDARY_BEFORE_GIT_EFFECTS"
echo "MINIMUM_FIELD_1=repo_path"
echo "MINIMUM_FIELD_2=expected_head"
echo "MINIMUM_FIELD_3=allowed_paths"
echo "MINIMUM_FIELD_4=forbidden_paths"
echo "MINIMUM_FIELD_5=scope_constraints"
echo
echo "MUST_BIND_TO=envelope_id"
echo "MUST_BIND_TO_PACKAGE=package_id_plus_package_version"
echo "MUST_CORRELATE_APPROVED_BRANCH=YES"
echo "MUST_NOT_IMPLY_PUSH=YES"
echo "MUST_BE_USER_OWNED_APPROVAL_DECISION=YES"
echo "MUST_BE_DURABLE_BEFORE_EXECUTION=YES"
echo "MUST_BE_FAIL_CLOSED_ON_MISSING_OR_MISMATCH=YES"
echo "MUST_PREVENT_REPLAY_ACROSS_ENVELOPES=YES"
echo

echo "=== INSERTION PRINCIPLE ==="
echo "PARALLEL_GENERAL_APPROVAL_SYSTEM=PROHIBITED"
echo "NEW_GENERIC_EXECUTION_AUTHORITY_SYSTEM=PROHIBITED"
echo "PREFERRED_OWNER=EXISTING_GOVERNANCE_EXECUTION_APPROVAL_DOMAIN"
echo "PREFERRED_SHAPE=NARROW_EXTENSION_OR_CORRELATED_DURABLE_EXECUTION_SCOPE_RECORD"
echo "EXACT_SCHEMA_NOT_YET_AUTHORIZED=YES"
echo

echo "=== CURRENT AUTHORIZATION EFFECT ==="
echo "EXISTING_UNMOUNTED_ROUTE_AUTHORIZATION_COVERS_NEW_DURABILITY_UNIT=NO"
echo "SEPARATE_IMPLEMENTATION_AUTHORIZATION_REQUIRED=YES"
echo "AUTHORIZED_ROUTE_IMPLEMENTATION_REMAINS_PAUSED=YES"
echo
echo "ROUTE_FILE_CREATED=NO"
echo "NEW_PERSISTENCE_CREATED=NO"
echo "SERVER_INDEX_CHANGED=NO"
echo "PRODUCTION_REACHABILITY_CHANGED=NO"
echo "GIT_EFFECT_CHANGED=NO"
echo

echo "=== CLASSIFICATION RESULT ==="
echo "MINIMUM_MISSING_DURABILITY_SURFACE_CLASSIFIED=YES"
echo "CORRIDOR_6_STATUS=AWAITING_EXECUTION_ENVELOPE_DURABILITY_IMPLEMENTATION_AUTHORIZATION"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=REQUEST_EXPLICIT_AUTHORIZATION_FOR_BOUNDED_EXECUTION_ENVELOPE_VERSION_CONTROL_AND_MUTATION_SCOPE_DURABILITY_UNIT_PLUS_TARGETED_TESTS"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
