#!/usr/bin/env bash
set -euo pipefail

echo "=== POST PHASE 3 — SUCCESSOR SCOPE CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor e180af7c HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-post-phase-3-successor-scope\.sh$|^ M scripts/classify-post-phase-3-successor-scope\.sh$' ||
  true
)"
test -z "$unexpected"

grep -Fq 'PHASE_3_STATUS=CLOSED_BOUNDED' scripts/record-phase-3-dr-protection-and-reconcile-successor-scope.sh
grep -Fq 'PHASE_3_CANONICAL_DR=20260818_102518' scripts/record-phase-3-dr-protection-and-reconcile-successor-scope.sh
grep -Fq 'CORRIDOR_2_STATUS=DEFERRED_WITH_EXPLICIT_UNRESOLVED_BEHAVIORAL_RELIABILITY_LIMIT' scripts/record-phase-3-dr-protection-and-reconcile-successor-scope.sh
grep -Fq 'GENERATION_STABILITY_MILESTONE=COMPLETE' scripts/reconcile-post-generation-stability-successor-scope.sh
grep -Fq 'GENERATION_STABILITY_REOPENED=' scripts/reconcile-post-generation-stability-successor-scope.sh
grep -Fq 'GENERATION_STABILITY=ALREADY_CLOSED' scripts/recover-successor-selection-from-semantic-history-closure-evidence.sh

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
PHASE_3_STATUS=CLOSED_BOUNDED
PHASE_3_DR=20260818_102518
PHASE_3_REOPENED=NO

DEFERRED_ITEM=REASONING_STATUS_MODEL_BEHAVIORAL_RELIABILITY
DEFERRED_ITEM_STATUS=REMAINS_SEPARATELY_DEFERRED
DEFERRED_ITEM_CAUSE=CROSS_CUTTING_SELECTED_CONTEXT_GENERATION_BEHAVIOR_PREVENTED_CLEAN_OBSERVATION

CONVERSATION_ENGINE_GENERATION_STABILITY_MILESTONE=ALREADY_CLOSED
GENERATION_STABILITY_REOPENED=NO
DEFERRED_ITEM_ASSIGNED_TO_REOPENED_GENERATION_STABILITY_MILESTONE=NO

RATIONALE=THE_DEFERRED_REASONING_STATUS_RELIABILITY_LIMIT_IS_GENERATION_RELIABILITY_RELATED_BUT_EXISTING_PROGRAM_EVIDENCE_MARKS_THE_GENERATION_STABILITY_MILESTONE_COMPLETE_AND_NOT_REOPENED__THEREFORE_THIS_ITEM_MUST_REMAIN_EXPLICITLY_DEFERRED_UNTIL_A_NEWLY_AUTHORIZED_SUCCESSOR_SCOPE_IS_ESTABLISHED

THREE_FAILED_VALIDATION_ATTEMPTS=PRESERVED
FOURTH_REPLAY_AUTHORIZED=NO
FAIL_CLOSED_VALIDATION_MUST_REMAIN_UNCHANGED=YES

NEW_MILESTONE_ESTABLISHED=NO
NEW_CORRIDOR_ESTABLISHED=NO
IMPLEMENTATION_AUTHORIZED=NO
PRODUCTION_CHANGE=NONE
DR_NOW=NO

SUCCESSOR_SCOPE_CLASSIFICATION=SEPARATELY_DEFERRED_CROSS_CUTTING_REASONING_STATUS_BEHAVIORAL_RELIABILITY_LIMIT
NEXT_ACTION=RECONCILE_CURRENT_PROGRAM_PRIORITY_AND_SELECT_THE_NEXT_REPOSITORY_SUPPORTED_SUCCESSOR_WITHOUT_REOPENING_PHASE_3_OR_GENERATION_STABILITY
MAP
