#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PRODUCTION FAILURE BASELINE AGAINST CURRENT VALIDATED STATE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 242ce743 HEAD
test -z "$(git status --porcelain)"

corridor2="scripts/enter-production-failure-baseline-corridor.sh"
test -f "$corridor2"

grep -q 'CORRIDOR_2_STATUS=' "$corridor2"
grep -q '^ACTIVE$' \
  <(awk '/CORRIDOR_2_STATUS=/{getline; print}' "$corridor2")

grep -q 'PRE_REMEDY_FAILURE_TARGET=' "$corridor2"
grep -q '^INVALID_MODEL_AUTHORED_PROJECT_CONTEXT_SUPPORT_PROVENANCE$' \
  <(awk '/PRE_REMEDY_FAILURE_TARGET=/{getline; print}' "$corridor2")

grep -q 'CURRENT_POST_REMEDY_BEHAVIORAL_EVIDENCE=' "$corridor2"
grep -q '^10_OF_10_SEMANTIC_PASS$' \
  <(awk '/CURRENT_POST_REMEDY_BEHAVIORAL_EVIDENCE=/{getline; print}' "$corridor2")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

CORRIDOR_2=
PRODUCTION_FAILURE_BASELINE

PRE_REMEDY_CANONICAL_FAILURE=
INVALID_MODEL_AUTHORED_PROJECT_CONTEXT_SUPPORT_PROVENANCE

PRE_REMEDY_BASELINE_STATE=
MATERIAL_PRODUCTION_INSTABILITY_WITH_ROUTINE_FAIL_CLOSED_OR_RUNTIME_REJECTION

PRE_REMEDY_BASELINE_PRESERVED=
YES

CURRENT_PRODUCTION_INTERVENTION=
EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION_AS_PRODUCTION_DEFAULT

POST_REMEDY_SEMANTIC_PASSES=
10_OF_10

POST_REMEDY_UNSUPPORTED_PROVENANCE_FAILURES=
0_OF_10

POST_REMEDY_FAIL_CLOSED_OR_RUNTIME_REJECTIONS=
0_OF_10

DETERMINISTIC_REGRESSION=
127_OF_127_PASS

BASELINE_TO_CURRENT_STATE_COMPARISON=
ESTABLISHED_FAILURE_PRESENT_PRE_REMEDY_AND_NOT_OBSERVED_ON_VALIDATED_POST_REMEDY_SURFACE

BASELINE_REWRITTEN_BY_POST_REMEDY_SUCCESS=
NO

CURRENT_FAILURE_BASELINE_STATUS=
HISTORICAL_PRE_REMEDY_REFERENCE_BASELINE

CURRENT_PRODUCTION_STATE_STATUS=
VALIDATED_POST_REMEDY_SUCCESS_ON_TESTED_SURFACE

PRODUCTION_FAILURE_BASELINE_CLASSIFICATION=
COMPLETE

NEW_PRODUCTION_CHANGE=
NONE

IMPLEMENTATION_AUTHORIZED=
NO_NEW_IMPLEMENTATION

CORRIDOR_2_STATUS=
READY_FOR_CLOSURE

DR_REQUIRED_BEFORE_NEXT_CORRIDOR=
YES

NEXT_ACTION=
STOP_FOR_CORRIDOR_2_DR_CHECKPOINT
MAP
