#!/usr/bin/env bash
set -euo pipefail

EXPECTED_HEAD="60625f49e"
CURRENT_HEAD="$(git rev-parse HEAD)"

echo "EXPECTED_HEAD_PREFIX=${EXPECTED_HEAD}"
echo "CURRENT_HEAD=${CURRENT_HEAD}"
[[ "${CURRENT_HEAD}" == ${EXPECTED_HEAD}* ]]

echo "=== VERIFIED BUILD FACTS ==="
echo "TS_COMPILER_EMITS_TS_EXECUTION_MODULES_TO_DIST=YES"
echo "MATILDA_EXECUTION_SWITCH_EVALUATOR_DIST_JS=YES"
echo "GOVERNED_COMMIT_ADAPTER_DIST_JS=YES"
echo "GOVERNED_PUSH_ADAPTER_DIST_JS=YES"
echo "PRODUCTION_EXECUTION_ENTRY_POINT_DIST_JS=YES"
echo "EXECUTION_APPROVAL_GATE_DIST_MJS=NO"
echo "PRODUCTION_GOVERNANCE_COMPOSITION_DIST_MJS=NO"

echo "=== STRATEGY CLASSIFICATION ==="
echo "FAILED_HYPOTHESIS=SOURCE_MJS_COMPOSITION_IMPORTED_FROM_COMPILED_SERVER"
echo "ROOT_RUNTIME_MISMATCH=MJS_PRODUCTION_FILES_ARE_NOT_EMITTED_BY_TSC"
echo "MINIMUM_SAFE_STRATEGY=MOVE_PRODUCTION_RUNTIME_SEAM_TO_TSC_EMITTED_TYPESCRIPT"
echo "REQUIRED_UNIT_1=TYPESCRIPT_APPROVAL_GATE_PRODUCTION_EQUIVALENT_OR_TS_SAFE_WRAPPER"
echo "REQUIRED_UNIT_2=TYPESCRIPT_PRODUCTION_GOVERNANCE_COMPOSITION"
echo "REQUIRED_UNIT_3=COMPILED_DIST_RUNTIME_VERIFICATION_BEFORE_ROUTE_MOUNT"
echo "ROUTE_MOUNT_CHANGE_REQUIRED_NOW=NO"
echo "GENERIC_CADE_CHANGE_REQUIRED=NO"
echo "SHELL_MUTATION_SCHEDULER_AUTONOMY_CHANGE_REQUIRED=NO"
echo "AUTHORITY_MODEL_CHANGE_REQUIRED=NO"
echo "CORRIDOR_6_STATUS=ACTIVE"
echo "PHASE_1_STATUS=ACTIVE"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
