#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

RUNNER_PID=71378
OLLAMA_PID=801
LLAMA_PID=71392

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=a62d58d0' \
  'ISSUE_RESOLVED=NO' \
  'UNSEEDED_ARM_COMPLETE=YES' \
  'CONTROLLED_ARM_COMPLETE=UNKNOWN' \
  'ACTION=CLASSIFY_LIVE_CONTROLLED_GENERATION_PROGRESS_WITHOUT_INTERRUPTION'

printf '\n=== CURRENT PROCESS ACTIVITY ===\n'
ps -p "$RUNNER_PID","$OLLAMA_PID","$LLAMA_PID" \
  -o pid=,ppid=,etime=,state=,%cpu=,%mem=,command= || true

printf '\n=== OLLAMA ACTIVE MODEL STATE ===\n'
ollama ps || true

printf '\n=== CONNECTION STATE ===\n'
RUNNER_CONNECTION="$(
  lsof -nP -p "$RUNNER_PID" -iTCP 2>/dev/null |
    grep '11434' || true
)"
LLAMA_CONNECTION="$(
  lsof -nP -p "$LLAMA_PID" -iTCP 2>/dev/null |
    grep 'ESTABLISHED' || true
)"
printf '%s\n' "$RUNNER_CONNECTION"
printf '%s\n' "$LLAMA_CONNECTION"

printf '\n=== CLASSIFICATION ===\n'
if ! ps -p "$RUNNER_PID" >/dev/null 2>&1; then
  printf '%s\n' \
    'COMPARISON_PROCESS_ACTIVE=NO' \
    'CONTROLLED_ARM_PROGRESS_STATE=PROCESS_TERMINATED_SINCE_LAST_OBSERVATION' \
    'NEXT_ACTION=CAPTURE_EXISTING_TERMINAL_OUTPUT_BEFORE_ANY_RECOVERY'
elif [[ -n "$RUNNER_CONNECTION" ]] && [[ -n "$LLAMA_CONNECTION" ]]; then
  printf '%s\n' \
    'COMPARISON_PROCESS_ACTIVE=YES' \
    'OLLAMA_CONNECTION_ACTIVE=YES' \
    'CONTROLLED_ARM_CURRENTLY_WAITING_ON_OR_RECEIVING_OLLAMA_GENERATION=YES' \
    'STALLED_PROCESS_ESTABLISHED=NO' \
    'PROCESS_TERMINATION_JUSTIFIED=NO' \
    'NEXT_ACTION=ALLOW_EXISTING_AUTHORIZED_CONTROLLED_ARM_TO_COMPLETE_AND_CAPTURE_REMAINING_TERMINAL_OUTPUT'
else
  printf '%s\n' \
    'COMPARISON_PROCESS_ACTIVE=YES' \
    'OLLAMA_CONNECTION_ACTIVE=NO' \
    'CONTROLLED_ARM_PROGRESS_STATE=AMBIGUOUS' \
    'STALLED_PROCESS_ESTABLISHED=NO' \
    'PROCESS_TERMINATION_JUSTIFIED=NO' \
    'NEXT_ACTION=INSPECT_RUNNER_EVENT_LOOP_AND_OLLAMA_REQUEST_STATE_BEFORE_RECOVERY'
fi

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'PROCESS_TERMINATED=NO' \
  'NEW_EXPERIMENT_STARTED=NO' \
  'PRODUCTION_CHANGE=NO' \
  'VALIDATOR_CHANGE=NO' \
  'GENERATION_POLICY_CHANGE=NO' \
  'DATABASE_WRITE=NO'

printf '\n=== WORKTREE ===\n'
git status --short
