#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY EXPERIMENTAL PRESENTATION PRODUCTION REGRESSION VALIDATION BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 279eadd2 HEAD
test -z "$(git status --porcelain)"

results="scripts/classify-bounded-unseeded-presentation-validation-results.sh"
test -f "$results"

grep -q 'SEMANTIC_RESULT=' "$results"
grep -q '^10_OF_10_PASS$' <(awk '/SEMANTIC_RESULT=/{getline; print}' "$results")
grep -q 'UNSUPPLIED_SUPPORT_FAILURE_RESULT=' "$results"
grep -q '^0_OF_10$' <(awk '/UNSUPPLIED_SUPPORT_FAILURE_RESULT=/{getline; print}' "$results")
grep -q 'PRODUCTION_REGRESSION_VALIDATION=' "$results"
grep -q '^STILL_REQUIRED$' <(awk '/PRODUCTION_REGRESSION_VALIDATION=/{getline; print}' "$results")
grep -q 'PRODUCTION_REMEDY_READINESS=' "$results"
grep -q '^ADVANCED_BUT_NOT_COMPLETE$' <(awk '/PRODUCTION_REMEDY_READINESS=/{getline; print}' "$results")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

BOUNDARY_UNIT=
EXPERIMENTAL_PRESENTATION_PRODUCTION_REGRESSION_VALIDATION_BOUNDARY

EVIDENCE_ENTERING_BOUNDARY=
FIXED_SEED_CONTROL_0_OF_10_AND_EXPERIMENTAL_10_OF_10
UNSEEDED_EXPERIMENTAL_10_OF_10
ZERO_UNSUPPLIED_SUPPORT_FAILURES_ON_UNSEEDED_EXPERIMENTAL_SURFACE
SEMANTIC_RELIABILITY_WITH_9_UNIQUE_OUTPUT_FINGERPRINTS

INTERVENTION_CANDIDATE=
EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION

PRODUCTION_REGRESSION_VALIDATION_PURPOSE=
VERIFY_THAT_PROMOTING_THE_PRESENTATION_STRUCTURE_DOES_NOT_BREAK_ESTABLISHED_CONVERSATION_ENGINE_CONTRACTS_OR_RUNTIME_BEHAVIOR

REQUIRED_VALIDATION_SCOPE=
DETERMINISTIC_EXISTING_REGRESSION_SUITE
PROMPT_AND_RESPONSE_SCHEMA_CONTRACTS
SUPPORT_PROVENANCE_FAIL_CLOSED_CONTRACT
SELECTED_CONTEXT_SEGMENT_CONTRACT
REPLY_AND_DURABLE_INTERPRETATION_SEPARATION
IEL_PERSISTENCE_BOUNDARY
CONVERSATION_CONTEXT_BOUNDARY
PRIOR_INVESTIGATION_LIFECYCLE_BOUNDARY
ONE_WORKFLOW_ONE_OLLAMA_INVOCATION_DEFAULT
LIVING_DRAFT_DERIVATION_BOUNDARY
APPROVAL_PIPELINE_AUTHORITY_BOUNDARY

PRODUCTION_BEHAVIORAL_SAMPLE_AFTER_PROMOTION=
REQUIRED_BEFORE_FINAL_RELIABILITY_CLOSURE

PRODUCTION_BEHAVIORAL_SAMPLE_GENERATION_STATE=
UNSEEDED

PRODUCTION_BEHAVIORAL_SAMPLE_RETRY=
NONE

PRODUCTION_BEHAVIORAL_SAMPLE_MODEL=
UNCHANGED

FAIL_CLOSED_VALIDATION=
MUST_REMAIN_UNCHANGED

SUPPORT_PROVENANCE_RULES=
MUST_REMAIN_UNCHANGED

SELECTED_CONTEXT_SEGMENT_RULES=
MUST_REMAIN_UNCHANGED

STRUCTURED_RESPONSE_SCHEMA=
MUST_REMAIN_UNCHANGED

MODEL=
MUST_REMAIN_UNCHANGED

GENERATION_POLICY=
MUST_REMAIN_UNCHANGED

RETRY_OR_SECOND_MODEL_CALL=
NOT_PERMITTED

PRODUCTION_PROMPT_PROMOTION=
POTENTIALLY_JUSTIFIED_BY_CURRENT_EVIDENCE_BUT_NOT_YET_AUTHORIZED

PRODUCTION_REMEDY_READINESS=
READY_FOR_IMPLEMENTATION_READINESS_CLASSIFICATION

PRODUCTION_PROMPT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

PRODUCTION_CHANGE=
NONE

CORRIDOR_1_STATUS=
ACTIVE

NEXT_ACTION=
CLASSIFY_EXPERIMENTAL_PRESENTATION_PRODUCTION_PROMOTION_IMPLEMENTATION_READINESS
MAP
