#!/usr/bin/env bash
set -euo pipefail

EXPECTED_HEAD="70a67d84abfdfc87ab5519840af9f3b3e7fc3565"
CURRENT_HEAD="$(git rev-parse HEAD)"

echo "EXPECTED_HEAD=${EXPECTED_HEAD}"
echo "CURRENT_HEAD=${CURRENT_HEAD}"
test "${CURRENT_HEAD}" = "${EXPECTED_HEAD}"

echo "DASHBOARD_RUNTIME_RECOVERY=VERIFIED"
echo "FAILED_MOUNT_RUNTIME_CLASS=SOURCE_MJS_DEPENDENCY_RESOLUTION_FROM_COMPILED_SERVER"
echo "COMPILED_RUNTIME_SAFE_MOUNT_BOUNDARY=REQUIRES_DIST_RESOLVABLE_EXECUTION_COMPOSITION"
echo "CORRIDOR_6_STATUS=ACTIVE"
echo "PHASE_1_STATUS=ACTIVE"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "NEXT_MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
