#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OLLAMA="scripts/utils/ollamaChat.ts"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=bdba10cb' \
  'ISSUE_RESOLVED=NO' \
  'ACTION=CLASSIFY_MINIMUM_SUPPORT_REFERENCE_PROMPT_PRESENTATION_FIX' \
  'NEW_OLLAMA_INVOCATION=NO'

printf '\n=== CURRENT PARENT SOURCE PRESENTATION ===\n'
sed -n '751,870p' "$OLLAMA"

printf '\n=== CURRENT STRUCTURED OUTPUT CONTRACT ===\n'
sed -n '70,96p' "$OLLAMA"
sed -n '895,910p' "$OLLAMA"

printf '\n=== CLASSIFICATION ===\n'
printf '%s\n' \
  'ROOT_FAILURE_PATTERN=MODEL_SERIALIZES_COMBINED_PATH_COLON_LINE_INTO_RELATIVE_PATH_FIELD' \
  'VALIDATOR_EXPECTATION=RAW_RELATIVE_PATH_PLUS_SEPARATE_LINE_NUMBER' \
  'VALIDATOR_MALFUNCTION_ESTABLISHED=NO' \
  'PROMPT_PRESENTATION_AMBIGUITY_ESTABLISHED=YES' \
  'MINIMUM_SAFE_FIX_SURFACE=scripts/utils/ollamaChat.ts' \
  'MINIMUM_SAFE_FIX_CLASS=PRESENT_PARENT_SUPPORT_IDENTITY_AS_SEPARATE_STRUCTURED_FIELDS' \
  'REQUIRED_PRESENTATION_1=relativePath_EQUALS_RAW_REPOSITORY_PATH_ONLY' \
  'REQUIRED_PRESENTATION_2=lineNumber_EQUALS_INTEGER_ONLY' \
  'REQUIRED_PRESENTATION_3=DO_NOT_INSTRUCT_MODEL_TO_COPY_COMBINED_PATH_COLON_LINE_INTO_RELATIVE_PATH' \
  'HUMAN_READABLE_COMBINED_IDENTITY_MAY_REMAIN_DIAGNOSTIC_ONLY=YES' \
  'OUTPUT_SCHEMA_CHANGE_REQUIRED=NO' \
  'VALIDATOR_CHANGE_REQUIRED=NO' \
  'VALIDATOR_WEAKENING_REQUIRED=NO' \
  'MODEL_CHANGE_REQUIRED=NO' \
  'RETRY_CHANGE_REQUIRED=NO' \
  'GENERATION_POLICY_CHANGE_REQUIRED=NO' \
  'PRODUCTION_PROMPT_CHANGE_REQUIRED=YES' \
  'IMPLEMENTATION_AUTHORIZED=NO'

printf '\n=== PROPOSED BOUNDED IMPLEMENTATION ===\n'
printf '%s\n' \
  'CHANGE_1=RENDER_PARENT_SUPPORT_SOURCE_AS_EXPLICIT_relativePath_FIELD_AND_lineNumber_FIELD' \
  'CHANGE_2=STATE_relativePath_MUST_NOT_INCLUDE_COLON_LINE_SUFFIX' \
  'CHANGE_3=PRESERVE_EXISTING_SUPPORT_SOURCE_REFERENCE_SCHEMA' \
  'CHANGE_4=PRESERVE_EXISTING_FAIL_CLOSED_MEMBERSHIP_VALIDATION' \
  'CHANGE_5=PRESERVE_EXISTING_SELECTED_CONTEXT_CHILD_IDENTITY_CONTRACT' \
  'CHANGE_6=NO_DATABASE_OR_PERSISTENCE_CHANGE'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'PRODUCTION_PROMPT_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_CHANGE_AUTHORIZED=NO' \
  'NEW_VALIDATION_RUN_AUTHORIZED=NO' \
  'NEXT_ACTION=AWAIT_EXPLICIT_AUTHORIZATION_TO_IMPLEMENT_BOUNDED_PROMPT_PRESENTATION_FIX'

printf '\n=== WORKTREE ===\n'
git status --short
