#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=EXECUTIVE_MISSION_OVERVIEW' \
  'ACTIVE_CORRIDOR=MISSION_STATE_PROJECTION' \
  'CORRIDOR_1_DR=20260818_193830' \
  'CURRENT_CHECKPOINT=a6f96790' \
  'DELEGATION_AUTHORIZED_VALUE=AUTHORIZED' \
  'VALIDATION_PASSED_VALUE=VALIDATION_PASSED' \
  'ENVELOPE_GATE_OPEN_VALUE=OPEN' \
  'ENVELOPE_CREATED_VALUE=ENVELOPE_CREATED' \
  'ASSIGNED_VALUE=ASSIGNED' \
  'STATE_PRECEDENCE=PACKAGE_THEN_DELEGATION_THEN_VALIDATION_THEN_GATE_THEN_ENVELOPE_THEN_ASSIGNMENT' \
  'PACKAGE_ONLY_STAGE=AWAITING_DELEGATION' \
  'AUTHORIZED_DELEGATION_STAGE=GOVERNANCE_VALIDATION' \
  'PASSED_VALIDATION_STAGE=ENVELOPE_GATE' \
  'OPEN_GATE_WITHOUT_ENVELOPE_STAGE=ENVELOPE_GATE' \
  'ENVELOPE_CREATED_STAGE=ENVELOPE_CREATED' \
  'ASSIGNED_LIFECYCLE_STAGE=ASSIGNED' \
  'CONTRADICTORY_OR_INCOMPLETE_LINEAGE=UNKNOWN_WITH_INTEGRITY_WARNING' \
  'NEW_SEMANTIC_AUTHORITY_REQUIRED=NO' \
  'NEW_PERSISTENCE_REQUIRED=NO' \
  'IMPLEMENTATION_BOUNDARY=MISSION_READ_REPOSITORY_AND_ASSEMBLER_ONLY' \
  'IMPLEMENTATION_READINESS=READY_BOUNDED' \
  'NEXT_ACTION=IMPLEMENT_MISSION_STATE_PROJECTION'

printf '\n=== VERIFY GOVERNING VALUES ===\n'
grep -n -E 'VALIDATION_PASSED|OPEN|AUTHORIZED' db/governance-lifecycle-enforcement.ts

printf '\n=== VERIFY CURRENT ASSEMBLER GAP ===\n'
grep -n -E 'AWAITING_DELEGATION|GOVERNANCE_VALIDATION|ENVELOPE_GATE|ENVELOPE_CREATED|ASSIGNED' \
  db/mission-read-model-assembler.ts || true

printf '\n=== WORKTREE ===\n'
git status --short
