#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 3 — SURFACING CONTRACT EVIDENCE CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 4df17d03 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-3-surfacing-contract-from-evidence\.sh$|^ M scripts/classify-phase-3-corridor-3-surfacing-contract-from-evidence\.sh$' ||
  true
)"
test -z "$unexpected"

grep -Fq "const conversationalReply =" server/matilda-chat-workflow.ts
grep -Fq "ollamaResult.reply;" server/matilda-chat-workflow.ts
grep -Fq "assistant_reply:" server/matilda-chat-workflow.ts
grep -Fq "return result.reply;" routes/matilda.ts
grep -Fq "explanationStatus" scripts/utils/ollamaChat.ts

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_3=SURFACING_CONTRACT
STATUS=SURFACING_BOUNDARY_CLASSIFIED_FROM_REPOSITORY_EVIDENCE

REPOSITORY_EVIDENCE=
OLLAMA_RESULT_REPLY_IS_ALREADY_THE_USER_VISIBLE_CONVERSATIONAL_REPLY

WORKFLOW_REPLY_SOURCE=
OLLAMA_RESULT_REPLY

PERSISTED_ASSISTANT_REPLY_SOURCE=
SAME_CONVERSATIONAL_REPLY

DIRECT_ROUTE_REPLY_SOURCE=
OLLAMA_RESULT_REPLY

EXPLANATION_STATUS_EXTERNAL_UI_CONSUMPTION=
NONE_ESTABLISHED

EXPLANATION_STATUS_EXTERNAL_WORKFLOW_CONSUMPTION=
NONE_ESTABLISHED

SEPARATE_UI_SURFACING_LAYER_REQUIRED=
NO

SEPARATE_WORKFLOW_COMPOSITION_LAYER_REQUIRED=
NO

NEW_RUNTIME_SEAM_REQUIRED=
NO

NEW_STRUCTURED_ARTIFACT_REQUIRED=
NO

MODEL_INVOCATION_COUNT_CHANGE_REQUIRED=
NO

SMALLEST_SURFACING_CONTRACT=
COUPLE_EXISTING_EXPLANATION_STATUS_SELECTION_TO_EXISTING_REPLY_COMPOSITION_INSIDE_THE_SINGLE_OLLAMA_PROMPT

OPTIONAL_SURFACING=
CONCISE_ANSWER_FIRST_WITH_ONLY_SUPPORTING_REASONING_NEEDED_FOR_THE_IMMEDIATE_INTERACTION

RECOMMENDED_SURFACING=
CONCISE_ANSWER_FIRST_THEN_ENOUGH_SUPPORTING_REASONING_TO_PRESERVE_A_MATERIAL_BOUNDARY_UNCERTAINTY_TRADEOFF_OR_EVIDENCE_INTERPRETATION_THAT_COULD_CHANGE_THE_USERS_NEXT_DECISION

MANDATORY_VISIBLE_REASONING_STATUS_LABEL=
NO

STATUS_FIELD_USER_VISIBLE_BY_DEFAULT=
NO

BOUNDED_PRODUCTION_PROMPT_CHANGE_REQUIRED=
YES

CORRIDOR_2_RELIABILITY_LIMIT=
PRESERVED

DO_NOT_CLAIM=
OPTIONAL_OR_RECOMMENDED_MODEL_BEHAVIOR_IS_PRODUCTION_RELIABLE

IMPLEMENTATION_REQUIRED=
YES_BOUNDED_TO_EXISTING_REPLY_COMPOSITION_PROMPT_CONTRACT

IMPLEMENTATION_AUTHORIZED=
NO

PRODUCTION_CHANGE=
NONE

DR_NOW=
NO

NEXT_ACTION=
CLASSIFY_BOUNDED_CORRIDOR_3_IMPLEMENTATION_READINESS_WITH_EXACT_PROMPT_SURFACE_AND_ROLLBACK_BOUNDARY
MAP
