#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 1 — BOUNDED IMPLEMENTATION READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor a4d7b49c HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-reasoning-status-implementation-readiness\.sh$|^ M scripts/classify-phase-3-reasoning-status-implementation-readiness\.sh$' ||
  true
)"
test -z "$unexpected"

classifier="scripts/classify-phase-3-classification-rule.sh"
adapter="scripts/utils/ollamaChat.ts"

test -f "$classifier"
test -f "$adapter"

grep -q 'CANONICAL_CLASSIFICATION_SEMANTICS=' "$classifier"
grep -q 'PRESERVE_V3_OPTIONAL_DEFAULT_AND_MATERIAL_DECISION_IMPACT_THRESHOLD' "$classifier"
grep -q 'CLASSIFICATION_SEMANTIC_GAP=' "$classifier"
grep -q 'ESTABLISHED' "$classifier"
grep -q 'NEW_STRUCTURED_ARTIFACT_REQUIRED=' "$classifier"
grep -q 'NEW_RUNTIME_SEAM_REQUIRED=' "$classifier"
grep -q 'NEW_AUTHORITY_BOUNDARY_REQUIRED=' "$classifier"

grep -q 'explanationStatus: MatildaExplanationStatus;' "$adapter"
grep -q 'enum: \["optional", "recommended"\]' "$adapter"
grep -q 'Ollama returned an invalid explanation status.' "$adapter"

cat <<'MAP'
PHASE=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_1=CLASSIFICATION_RULE
CORRIDOR_1_ARCHITECTURAL_STATUS=RESOLVED
CORRIDOR_1_DR_CHECKPOINT=20260817_110833
CORRIDOR_1_DR_PROTECTED_COMMIT=a4d7b49c

IMPLEMENTATION_READINESS=READY_FOR_BOUNDED_IMPLEMENTATION

SMALLEST_SAFE_IMPLEMENTATION_SURFACE=
EXISTING_OLLAMA_PROMPT_EXPLANATION_STATUS_SELECTION_INSTRUCTIONS_ONLY

REQUIRED_SEMANTIC_RULE=
OPTIONAL_IS_DEFAULT_AND_RECOMMENDED_ONLY_WHEN_SKIPPING_SUPPORTING_REASONING_IS_LIKELY_TO_MATERIALLY_AFFECT_THE_USERS_NEXT_ENGINEERING_DECISION

RECOMMENDED_TRIGGER_FACTORS=
ARCHITECTURAL_NUANCE_IMPLEMENTATION_BOUNDARIES_SIGNIFICANT_UNCERTAINTY_COMPETING_INTERPRETATIONS_OR_EVIDENCE_INTERPRETATION_THAT_MATERIALLY_AFFECTS_THE_CONCLUSION

NON_TRIGGERS=
EVIDENCE_EXISTS_WORK_WAS_SUBSTANTIAL_OR_ADDITIONAL_EXPLANATION_IS_AVAILABLE

STRUCTURED_RESPONSE_SCHEMA_CHANGE=NONE
NEW_STRUCTURED_ARTIFACT=NONE
NEW_RUNTIME_SEAM=NONE
NEW_AUTHORITY_BOUNDARY=NONE
WORKFLOW_CHANGE=NONE
PERSISTENCE_CHANGE=NONE
MODEL_CHANGE=NONE
GENERATION_POLICY_CHANGE=NONE
RETRY_OR_SECOND_MODEL_CALL=NONE
MANDATORY_USER_FACING_REASONING_STATUS_LINE=NOT_REQUIRED

PRESERVE=
MATILDA_SEMANTIC_AUTHORSHIP
ONE_WORKFLOW_ONE_OLLAMA_INVOCATION
EXISTING_RESPONSE_COMPOSITION
EXISTING_FAIL_CLOSED_VALIDATION
EXISTING_EXPLANATION_STATUS_ENUM

REQUIRED_VALIDATION=
PROMPT_CONTRACT_TEST_PLUS_OPTIONAL_AND_RECOMMENDED_BEHAVIORAL_VALIDATION

ROLLBACK_BOUNDARY=
REVERT_ONLY_THE_NEW_EXPLANATION_STATUS_SELECTION_INSTRUCTIONS_AND_ASSOCIATED_TEST_COVERAGE

IMPLEMENTATION_AUTHORIZED=NO
PRODUCTION_CHANGE=NONE
NEXT_ACTION=AWAIT_EXPLICIT_IMPLEMENTATION_AUTHORIZATION
MAP
