#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PHASE 3 CORRIDOR 1 — PRODUCTION STABILITY CONTRACT RECONCILIATION ==="

contract="scripts/define-phase-3-production-stability-validation-contract.sh"

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor d8256e8d HEAD
test -f "$contract"

echo
echo "=== VERIFY CONTRACT SEMANTIC COMPATIBILITY ==="

grep -q 'PRODUCTION_BASELINE=' "$contract"
grep -q 'UNSEEDED' "$contract"
grep -q 'NO_EXPLICIT_TEMPERATURE' "$contract"
grep -q 'NO_EXPLICIT_TOP_P' "$contract"
grep -q 'NO_EXPLICIT_TOP_K' "$contract"
grep -q 'ONE_OLLAMA_INVOCATION' "$contract"
grep -q 'DETERMINISTIC_FAIL_CLOSED_VALIDATION_PRESERVED' "$contract"
grep -q '10_SEQUENTIAL_IDENTICAL_INVOCATIONS' "$contract"
grep -q 'NO_RETRY_OF_FAILED_RUN' "$contract"
grep -q 'SEED=' "$contract"
grep -q 'ABSENT' "$contract"
grep -q 'Do not substitute seeded diagnostic evidence for production evidence.' "$contract"
grep -q 'PRODUCTION_IMPLEMENTATION_AUTHORIZED=' "$contract"
grep -q 'PRODUCTION_GENERATION_POLICY_CHANGE_AUTHORIZED=' "$contract"
grep -q 'PRODUCTION_CHANGE=' "$contract"

echo "CONTRACT_PRODUCTION_BASELINE=SEMANTICALLY_COMPATIBLE"
echo "CONTRACT_VALIDATION_SURFACE=EXISTING_ADAPTIVE_DETAIL_MIXED_CONTENT_LIVE_FIXTURE"
echo "CONTRACT_SAMPLE_MODE=UNSEEDED_ONLY"
echo "CONTRACT_SAMPLE_SIZE=10_SEQUENTIAL_IDENTICAL_INVOCATIONS"
echo "CONTRACT_RETRY_POLICY=NONE"
echo "CONTRACT_SEEDED_DIAGNOSTIC_SUBSTITUTION=PROHIBITED"
echo "CONTRACT_PRODUCTION_POLICY_CHANGE=NONE"

echo
echo "=== VERIFY STALE EXECUTION ASSUMPTION ==="

grep -q 'expected_head="7d9e1d77"' "$contract"

if git merge-base --is-ancestor 7d9e1d77 HEAD; then
  echo "LEGACY_CONTRACT_CHECKPOINT_ANCESTRY=PRESENT"
else
  echo "LEGACY_CONTRACT_CHECKPOINT_ANCESTRY=NOT_PRESENT"
fi

if [[ "$(git rev-parse --short=8 HEAD)" = "7d9e1d77" ]]; then
  echo "LEGACY_EXACT_HEAD_GUARD=CURRENTLY_SATISFIED"
else
  echo "LEGACY_EXACT_HEAD_GUARD=CURRENTLY_UNSATISFIED"
fi

cat <<'MAP'

MILESTONE=CONVERSATION_ENGINE_GENERATION_STABILITY
PHASE=PRODUCTION_STABILITY_VALIDATION_AND_CLOSURE
CORRIDOR=PRODUCTION_STABILITY_CONTRACT

RECONCILIATION_FINDING=
  CONTRACT_SEMANTICS_COMPATIBLE_WITH_CURRENT_CANONICAL_PHASE_3_STATE

EXECUTABLE_ARTIFACT_FINDING=
  LEGACY_EXACT_HEAD_GUARD_IS_STALE

STALE_ASSUMPTION=
  expected_head_7d9e1d77

CURRENT_CANONICAL_STARTING_BOUNDARY=
  d8256e8d

CURRENT_PRODUCTION_BASELINE=
  UNCHANGED_UNCONFIGURED_UNSEEDED_GENERATION

PRODUCTION_POLICY_CHANGE_REQUIRED=
  NO

SEMANTIC_CONTRACT_CHANGE_REQUIRED=
  NO

VALIDATION_CONTRACT_CHANGE_REQUIRED=
  NO

BOUNDED_RECONCILIATION_REQUIRED=
  YES

BOUNDED_RECONCILIATION_SURFACE=
  REPLACE_LEGACY_EXACT_HEAD_EXECUTION_GUARD_WITH_CURRENT_CANONICAL_ANCESTRY_GUARD

MATILDA_SEMANTIC_AUTHORSHIP_CHANGE=
  NONE

FAIL_CLOSED_VALIDATION_CHANGE=
  NONE

OLLAMA_INVOCATION_COUNT_CHANGE=
  NONE

GENERATION_POLICY_CHANGE=
  NONE

CORRIDOR_1_STATUS=
  NOT_YET_COMPLETE

BLOCKER=
  EXISTING_CONTRACT_ARTIFACT_CANNOT_EXECUTE_ON_CURRENT_CANONICAL_ANCESTRY_WITH_LEGACY_EXACT_HEAD_GUARD

NEXT_ACTION=
  RECONCILE_CONTRACT_EXECUTION_GUARD_ONLY
MAP
