#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=EXECUTIVE_MISSION_OVERVIEW' \
  'CORRIDOR=MISSION_IDENTITY_AND_OBJECTIVE' \
  'MISSION_OBJECTIVE_AUTHORITY=GOVERNANCE_PACKAGE_REQUESTED_OUTCOME' \
  'MISSION_OBJECTIVE_REPOSITORY_CAPABILITY=EXISTS' \
  'MISSION_OBJECTIVE_MISSION_READ_PROJECTION=MISSING' \
  'MISSION_TITLE_CONTRACT=HUMAN_READABLE_REQUESTED_OUTCOME_PER_PRESENTATION_SPEC' \
  'DISTINCT_AUTHORITATIVE_MISSION_TITLE_FIELD=NOT_ESTABLISHED' \
  'NEW_SEMANTIC_AUTHORITY_REQUIRED=NO' \
  'NEW_PERSISTENCE_REQUIRED=NO' \
  'GAP_CLASS=MISSION_READ_PROJECTION_AND_PRESENTATION_MAPPING' \
  'RENDERER_SEMANTIC_AUTHORITY=NOT_ALLOWED' \
  'CORRIDOR_1_CLASSIFICATION=READY_FOR_BOUNDED_IMPLEMENTATION_PLANNING' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'NEXT_CORRIDOR=MISSION_STATE_PROJECTION'
