#!/usr/bin/env bash
set -euo pipefail

echo "=== POST PHASE 3 — DEFERRED WORK DISPOSITION CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 1a66141c HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-post-phase-3-deferred-work-disposition\.sh$|^ M scripts/classify-post-phase-3-deferred-work-disposition\.sh$' ||
  true
)"
test -z "$unexpected"

test -f scripts/reconcile-current-deferred-work-inventory.sh
test -f scripts/classify-deferred-work-inventory.sh
test -f scripts/reconcile-current-successor-priority-boundary.sh
test -f scripts/classify-post-phase-3-successor-scope.sh
test -f scripts/reconcile-post-phase-3-broader-program-state-and-deferred-work.sh

echo "=== CURRENT RECONCILED INVENTORY ==="
sed -n '50,135p' scripts/reconcile-current-deferred-work-inventory.sh
echo "=== CURRENT SUCCESSOR BOUNDARY ==="
sed -n '49,105p' scripts/reconcile-current-successor-priority-boundary.sh

cat <<'MAP'
PROGRAM=MATILDA_CONVERSATION_ENGINE
STATUS=POST_PHASE_3_DEFERRED_WORK_DISPOSITION_CLASSIFIED

PHASE_3_STATUS=CLOSED_BOUNDED
PHASE_3_DR=20260818_102518
PHASE_3_REOPENED=NO

GENERATION_STABILITY_STATUS=ALREADY_CLOSED
GENERATION_STABILITY_REOPENED=NO

REASONING_STATUS_MODEL_BEHAVIORAL_RELIABILITY=
SEPARATELY_DEFERRED
REASONING_STATUS_RELIABILITY_REPLAY_AUTHORIZED=
NO

COMPLETED_ITEMS=
REMOVE_FROM_SUCCESSOR_CONSIDERATION

STALE_OR_ALREADY_CLOSED_DEFERRED_ITEMS=
NON_SUCCESSOR

DEFERRED_ITEMS_WITH_REQUIREMENT_OR_CHANGE_REQUIREMENT_NOT_ESTABLISHED=
NON_CAPABILITY_CONDITION_UNTIL_NEW_EVIDENCE_ESTABLISHES_A_REQUIREMENT

REASONING_STATUS_BEHAVIORAL_RELIABILITY_LIMIT=
SEPARATELY_DEFERRED_CROSS_CUTTING_CONDITION

CURRENT_GENUINE_UNRESOLVED_RUNTIME_CAPABILITY_GAPS=
ZERO

EVIDENCE_SUPPORTED_SUCCESSOR_CANDIDATE=
NONE_ESTABLISHED

NEW_MILESTONE_JUSTIFIED=
NO

NEW_CORRIDOR_JUSTIFIED=
NO

IMPLEMENTATION_READINESS=
NOT_APPLICABLE

IMPLEMENTATION_AUTHORIZED=
NO

PRODUCTION_CHANGE=
NONE

DR_NOW=
NO

PROGRAM_DISPOSITION=
CURRENT_RUNTIME_CAPABILITY_PROGRAM_HAS_NO_EVIDENCE_SUPPORTED_SUCCESSOR_ON_THE_RECONCILED_INVENTORY__PRESERVE_SEPARATELY_DEFERRED_REASONING_STATUS_BEHAVIORAL_RELIABILITY_WITHOUT_REOPENING_CLOSED_MILESTONES

NEXT_ACTION=
CLASSIFY_WHETHER_CURRENT_MATILDA_CONVERSATION_ENGINE_RUNTIME_MILESTONE_SEQUENCE_IS_COMPLETE_PENDING_ONLY_SEPARATELY_DEFERRED_NON_BLOCKING_WORK
MAP
