#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=aab16dc2' \
  'ISSUE_RESOLVED=NO' \
  'MODE=COLLABORATION_DIAGNOSTIC' \
  'FIX_AUTHORIZED=NO' \
  'TARGET=CLASSIFY_CURRENT_FAILURE_CLASS_WITHOUT_LAYERING_ANOTHER_FIX'

printf '\n=== VERIFIED EVIDENCE ===\n'
printf '%s\n' \
  'DASHBOARD_PROXY_REACHES_BACKEND=YES' \
  'PROXY_TRANSPORT_FAILURE_ESTABLISHED=NO' \
  'PRIOR_SUCCESSFUL_TURN_EXISTS=YES' \
  'OBSERVED_FAILURE_CLASS_1=OLLAMA_CHAT_TIMEOUT' \
  'OBSERVED_FAILURE_CLASS_2=UNSUPPLIED_PROJECT_CONTEXT_SUPPORT_REFERENCE' \
  'PREVIOUS_CONVERSATION_SUPPORT_FAILURE=NOT_CURRENT_FAILURE' \
  'PREVIOUS_SELECTED_CONTEXT_FAILURE=NOT_CURRENT_FAILURE'

printf '\n=== CURRENT FAILURE CLASSIFICATION ===\n'
printf '%s\n' \
  'SINGLE_DETERMINISTIC_ROOT_CAUSE_ESTABLISHED=NO' \
  'FAILURES_VARY_ACROSS_IDENTICAL_OR_EQUIVALENT_REQUEST_PATHS=YES' \
  'CURRENT_EVIDENCE_MATCHES_PREVIOUSLY_ESTABLISHED_GENERATION_INSTABILITY=YES' \
  'FAIL_CLOSED_VALIDATOR_MALFUNCTION_ESTABLISHED=NO' \
  'PROJECT_CONTEXT_VALIDATOR_CORRECTLY_REJECTED_UNSUPPLIED_REFERENCE=YES' \
  'ADDITIONAL_REFERENCE_SPECIFIC_PROMPT_FIX_JUSTIFIED=NO' \
  'SPECULATIVE_FIX_LAYERING_PROHIBITED=YES'

printf '\n=== BUILD PROTOCOL DECISION ===\n'
printf '%s\n' \
  'CURRENT_HYPOTHESIS=REFERENCE_SPECIFIC_PROMPT_CONSTRAINT_FIXES' \
  'CONFIDENT_NEXT_FIX_AVAILABLE=NO' \
  'CONTINUE_FIXING_UNDER_CURRENT_HYPOTHESIS=NO' \
  'REVERT_REQUIRED_BEFORE_DIFFERENT_SOLUTION_CLASS=YES' \
  'REVERT_TARGET=LAST_KNOWN_STABLE_RUNTIME_BEFORE_EMPTY_HISTORY_PROMPT_FIX' \
  'REVERT_NOT_EXECUTED=YES' \
  'NEXT_ACTION=IDENTIFY_EXACT_PRE_FIX_STABLE_COMMIT_AND_REVERT_BOUNDARY'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'VALIDATOR_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_WEAKENING_AUTHORIZED=NO' \
  'GENERATION_POLICY_CHANGE_AUTHORIZED=NO' \
  'MODEL_CHANGE_AUTHORIZED=NO' \
  'RETRY_CHANGE_AUTHORIZED=NO' \
  'TIMEOUT_CHANGE_AUTHORIZED=NO' \
  'PERSISTENCE_CHANGE_AUTHORIZED=NO'

printf '\n=== RESOLUTION STATUS ===\n'
printf '%s\n' \
  'ISSUE_RESOLVED=NO' \
  'REASON=MULTIPLE_GENERATION_FAILURE_CLASSES_REMAIN_OBSERVED_ON_DASHBOARD_PATH'

printf '\n=== WORKTREE ===\n'
git status --short
