#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY RELIABLE PRODUCTION COLLABORATION CONSTRAINT PRESERVATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor f8f8f530 HEAD

ownership="scripts/investigate-production-collaboration-failure-ownership.sh"
starting_boundary="scripts/open-reliable-production-collaboration-starting-boundary.sh"
contract="scripts/investigate-collaboration-reliability-contract.sh"

for artifact in "$ownership" "$starting_boundary" "$contract"; do
  test -f "$artifact"
  echo "PRESENT=$artifact"
done

echo
echo "=== VERIFY CORRIDOR 3 CLOSURE ==="
grep -q 'CORRIDOR_3_STATUS=' "$ownership"
grep -q '^COMPLETE$' <(awk '/CORRIDOR_3_STATUS=/{getline; print}' "$ownership")
grep -q 'NEXT_CORRIDOR=' "$ownership"
grep -q '^CONSTRAINT_PRESERVATION$' <(awk '/NEXT_CORRIDOR=/{getline; print}' "$ownership")
echo "CORRIDOR_3_CLOSURE=CONFIRMED"

echo
echo "=== VERIFY STARTING INVARIANTS ==="
grep -q 'FAIL_CLOSED_VALIDATION=' "$starting_boundary"
grep -q 'MUST_BE_PRESERVED' "$starting_boundary"
grep -q 'MATILDA_SEMANTIC_AUTHORSHIP=' "$starting_boundary"
grep -q 'ONE_OLLAMA_INVOCATION=' "$starting_boundary"
echo "STARTING_INVARIANTS=CONFIRMED"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_1=
STARTING_BOUNDARY_AND_RELIABILITY_BASELINE

CORRIDOR_4=
CONSTRAINT_PRESERVATION

CORRIDOR_PURPOSE=
CLASSIFY_WHICH_EXISTING_ARCHITECTURAL_AND_SEMANTIC_BOUNDARIES_MUST_SURVIVE_ANY_LATER_RELIABILITY_INTERVENTION

IMMUTABLE_PRESERVATION_REQUIREMENTS=
USER_INTENT_AUTHORITY
MATILDA_INTERPRETATION_AUTHORITY
REPLY_AND_DURABLE_INTERPRETATION_SEPARATION
WORKFLOW_OWNED_IEL_PERSISTENCE
CONVERSATION_CONTEXT_BOUNDARY
PROJECT_CONTEXT_PROVENANCE_BOUNDARY
PRIOR_INVESTIGATION_LIFECYCLE_CONTEXT_BOUNDARY
FAIL_CLOSED_STRUCTURED_RESPONSE_VALIDATION
UNSUPPORTED_PROVENANCE_REJECTION
LIVING_DRAFT_DERIVATION_FROM_IEL
APPROVAL_PIPELINE_AUTHORITY_BOUNDARY

ONE_USER_MESSAGE_TO_ONE_WORKFLOW=
MUST_BE_PRESERVED

ONE_WORKFLOW_TO_ONE_OLLAMA_INVOCATION=
PRESERVE_BY_DEFAULT

ONE_OLLAMA_INVOCATION_CHANGE=
REQUIRES_SEPARATE_EVIDENCE_SUPPORTED_CLASSIFICATION_AND_EXPLICIT_AUTHORIZATION

FAIL_CLOSED_VALIDATION=
MUST_NOT_BE_WEAKENED

SEMANTIC_ACCEPTANCE_CONTRACT=
MUST_NOT_BE_BYPASSED

PROJECT_CONTEXT_SUPPORT_PROVENANCE=
MUST_REMAIN_EXACT_AND_FAIL_CLOSED

MATILDA_SEMANTIC_AUTHORSHIP=
MUST_BE_PRESERVED

DETERMINISTIC_RUNTIME_GUARDS=
MUST_BE_PRESERVED_UNLESS_SPECIFIC_MALFUNCTION_IS_ESTABLISHED

CURRENT_VALIDATOR_MALFUNCTION=
NOT_ESTABLISHED

CURRENT_RUNTIME_REGRESSION=
NOT_ESTABLISHED

CURRENT_CONTEXT_TRANSPORT_MALFUNCTION=
NOT_ESTABLISHED

CURRENT_FAILURE_OWNER=
MODEL_GENERATION_LAYER

PERMITTED_FUTURE_INVESTIGATION_CLASSES=
PROMPT_OR_RESPONSE_CONTRACT_PRESENTATION
MODEL_CAPABILITY
GENERATION_CONTROL_OR_SAMPLING_POLICY
OTHER_BOUNDED_GENERATION_INPUT_CONDITIONS

NOT_PERMITTED_WITHOUT_NEW_EVIDENCE_AND_AUTHORIZATION=
VALIDATOR_WEAKENING
UNSUPPORTED_PROVENANCE_ACCEPTANCE
SILENT_SEMANTIC_MUTATION
AUTOMATIC_RETRY
SECOND_MODEL_INVOCATION
MODEL_REPLACEMENT
PRODUCTION_FIXED_SEED
OTHER_PRODUCTION_GENERATION_POLICY_CHANGE

CONSTRAINT_CLASSIFICATION=
RELIABILITY_REMEDY_MUST_TARGET_GENERATION_LAYER_WITHOUT_DEGRADING_EXISTING_SEMANTIC_AND_AUTHORITY_GUARDS

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

CORRIDOR_4_STATUS=
COMPLETE

NEXT_CORRIDOR=
INTERVENTION_BOUNDARY

NEXT_ACTION=
CLASSIFY_EVIDENCE_SUPPORTED_RELIABILITY_INTERVENTION_BOUNDARY
MAP
