#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY DIAGNOSTIC TYPECHECK BLOCKER ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 59f93d00 HEAD

echo "=== CURRENT WORKTREE ==="
git status --short

echo "=== VERIFY DIAGNOSTIC PARTIAL IMPLEMENTATION ==="
test -f scripts/run-bounded-prompt-presentation-diagnostic.ts
grep -q 'validationPromptPresentationVariant' scripts/utils/ollamaChat.ts
grep -q 'Validation-only project-context identity presentation:' scripts/utils/ollamaChat.ts
echo "DIAGNOSTIC_SURFACES=PRESENT"

echo "=== VERIFY TYPECHECK ERROR SURFACE ==="
grep -n 'reconstructWhy' routes/atlas/why.ts || true
grep -n 'function reconstructWhy\|const reconstructWhy\|export.*reconstructWhy' server/atlas/atlas-reconstruction-model.ts || true

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

BLOCKER=
PRE_EXISTING_REPOSITORY_TYPECHECK_ERROR

TYPECHECK_ERROR=
ROUTES_ATLAS_WHY_TS2554_EXPECTED_2_ARGUMENTS_GOT_3

DIAGNOSTIC_IMPLEMENTATION_CAUSED_ERROR=
NO_EVIDENCE_ESTABLISHED

KNOWN_PRIOR_ERROR_MATCH=
YES

DIAGNOSTIC_SURFACES_CREATED=
YES

PRODUCTION_CHANGE=
NONE

DIAGNOSTIC_COMMIT_ALLOWED=
NO_UNTIL_CURRENT_PARTIAL_IMPLEMENTATION_STATE_IS_CLASSIFIED_AND_VALIDATED_WITH_A_TARGETED_CHECK

FULL_REPOSITORY_TYPECHECK_AS_DIAGNOSTIC_GATE=
BLOCKED_BY_PRE_EXISTING_UNRELATED_ERROR

NEXT_SAFE_VALIDATION=
RUN_TARGETED_TYPESCRIPT_OR_REPOSITORY_TESTS_FOR_OLLAMA_CHAT_AND_DIAGNOSTIC_RUNNER_WITHOUT_MODIFYING_ATLAS

ATLAS_FIX_AUTHORIZED=
NO

ROLLBACK_REQUIRED=
NO

FAILED_DIAGNOSTIC_IMPLEMENTATION_HYPOTHESIS_COUNT=
1

NEXT_ACTION=
TARGETED_VALIDATE_DIAGNOSTIC_SURFACES_WITHOUT_TOUCHING_PRE_EXISTING_ATLAS_ERROR
MAP
