#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="93d44c641"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — EXACT UNMOUNTED ROUTE BINDING CLASSIFICATION ==="
echo "MODE=EXECUTION"
echo "PRODUCTION_CHANGE=NONE"
echo

echo "=== VERIFIED DURABLE INPUT BINDINGS ==="
echo "APPROVAL_READER=loadGovernanceExecutionApproval"
echo "APPROVAL_LOOKUP=approval_id_plus_envelope_id"
echo "APPROVAL_FAIL_CLOSED=YES"
echo "EXECUTION_SCOPE_READER=loadGovernanceExecutionScope"
echo "EXECUTION_SCOPE_LOOKUP=approval_id_plus_envelope_id"
echo "EXECUTION_SCOPE_FAIL_CLOSED=YES"
echo "PACKAGE_LINEAGE_REVALIDATED=YES"
echo "APPROVED_BRANCH_SOURCE=EXECUTION_APPROVAL"
echo "REPO_PATH_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "EXPECTED_HEAD_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "ALLOWED_PATHS_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "FORBIDDEN_PATHS_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "SCOPE_CONSTRAINTS_SOURCE=DURABLE_EXECUTION_SCOPE"
echo

echo "=== VERIFIED APPROVAL BINDINGS ==="
echo "APPROVAL_COMPILER=compilePersistedExecutionApproval"
echo "APPROVAL_GATE=evaluateExecutionApproval"
echo "GOVERNANCE_VALIDATION_REQUIRED=YES"
echo "INITIAL_PUSH_AUTHORITY_REJECTED_BY_ENTRY_POINT=YES"
echo "PUSH_REQUIRES_LOCAL_COMMIT_PROOF=YES"
echo "PUSH_REQUIRES_SECOND_GATE_EVALUATION=YES"
echo "COMMIT_DOES_NOT_IMPLY_PUSH=YES"
echo

echo "=== VERIFIED EXECUTION BINDING ==="
echo "EXECUTION_ENTRY_POINT=executeProductionExecutionEntryPoint"
echo "EXECUTION_ID_CALLER_SUPPLIED=YES"
echo "COMMIT_RESULT_SYNTHESIS_ALLOWED=NO"
echo "PUSH_RESULT_SYNTHESIS_ALLOWED=NO"
echo "REAL_GIT_EFFECTS_IN_ROUTE_TESTS=PROHIBITED"
echo

echo "=== CANONICAL ENVELOPE RECONSTRUCTION CONTRACT ==="
echo "ENVELOPE_ID_SOURCE=REQUEST_IDENTITY_ONLY"
echo "PACKAGE_ID_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "PACKAGE_VERSION_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "REPO_PATH_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "EXPECTED_HEAD_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "BRANCH_SOURCE=DURABLE_EXECUTION_APPROVAL"
echo "ALLOWED_PATHS_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "FORBIDDEN_PATHS_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "SCOPE_CONSTRAINTS_SOURCE=DURABLE_EXECUTION_SCOPE"
echo "CLIENT_FULL_ENVELOPE_AUTHORITY=PROHIBITED"
echo "PROCESS_CWD_AUTHORITY=PROHIBITED"
echo "CURRENT_GIT_HEAD_AUTHORITY=PROHIBITED"
echo

echo "=== DELEGATION / GOVERNANCE BOUNDARY ==="
echo "DELEGATION_STATE_MUST_COME_FROM_EXISTING_GOVERNANCE_PERSISTENCE=YES"
echo "DELEGATED_BY_MUST_COME_FROM_EXISTING_GOVERNANCE_PERSISTENCE=YES"
echo "ROUTE_MUST_NOT_SYNTHESIZE_DELEGATION=YES"
echo "ROUTE_MUST_NOT_SYNTHESIZE_GOVERNANCE_VALIDATION=YES"
echo

echo "=== IMPLEMENTATION SHAPE ==="
echo "ROUTE_OWNER=NEW_DEDICATED_UNMOUNTED_EXECUTION_ROUTE"
echo "ROUTE_CREATES_AUTHORITY=NO"
echo "ROUTE_CREATES_APPROVAL=NO"
echo "ROUTE_CREATES_SCOPE=NO"
echo "ROUTE_CREATES_PACKAGE=NO"
echo "ROUTE_CREATES_DELEGATION=NO"
echo "ROUTE_CREATES_ENVELOPE_AUTHORITY=NO"
echo "ROUTE_ROLE=READ_VALIDATE_RECONSTRUCT_COMPILE_BIND_AND_INVOKE"
echo "DEPENDENCY_INJECTION_REQUIRED_FOR_TARGETED_TESTS=YES"
echo

echo "=== AUTHORIZATION BOUNDARY ==="
echo "UNMOUNTED_ROUTE_IMPLEMENTATION_AUTHORIZED=YES"
echo "SERVER_INDEX_ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGES_AUTHORIZED=NO"
echo "REMOTE_PUSH_EFFECT_CHANGES_AUTHORIZED=NO"
echo "GENERIC_CADE_CHANGES_AUTHORIZED=NO"
echo "GENERIC_SHELL_AUTHORITY_AUTHORIZED=NO"
echo "GENERIC_MUTATION_AUTHORITY_AUTHORIZED=NO"
echo "SCHEDULER_OR_AUTONOMY_AUTHORIZED=NO"
echo

echo "=== CLASSIFICATION RESULT ==="
echo "EXACT_ROUTE_BINDINGS_CLASSIFIED=YES"
echo "UNMOUNTED_ROUTE_IMPLEMENTATION_READY=YES"
echo "CORRIDOR_6_STATUS=UNMOUNTED_DEDICATED_EXECUTION_ROUTE_IMPLEMENTATION_READY"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=IMPLEMENT_PREVIOUSLY_AUTHORIZED_UNMOUNTED_DEDICATED_EXECUTION_ROUTE_AND_TARGETED_TESTS"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
