#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="baa5dbf09"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — PREEXISTING EXECUTION APPROVAL TRANSITION GAP ==="
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_CHANGE=NONE"
echo

echo "=== CORRIDOR 2 PRESERVED ==="
echo "CORRIDOR_2=DURABLE_USER_EXECUTION_AUTHORIZATION"
echo "CORRIDOR_2_STATUS=CLOSED"
echo "CURRENT_USER_MESSAGE_DURABLY_PERSISTED=YES"
echo "CURRENT_USER_MESSAGE_IS_USER_INTENT_AUTHORITY_EVIDENCE=YES"
echo "DUPLICATE_USER_AUTHORIZATION_ARTIFACT_REQUIRED=NO"
echo "CORRIDOR_2_REOPEN_REQUIRED=NO"
echo

echo "=== EXISTING EXECUTION APPROVAL CAPABILITY ==="
echo "EXECUTION_APPROVAL_ARTIFACT_BUILDER_EXISTS=YES"
echo "EXECUTION_APPROVAL_GATE_EXISTS=YES"
echo "COMMIT_APPROVAL_GATE_CAPABILITY_EXISTS=YES"
echo "PUSH_APPROVAL_GATE_CAPABILITY_EXISTS=YES"
echo "APPROVAL_BUILDER_DEFAULT_STATUS=APPROVAL_REQUIRED"
echo "APPROVAL_BUILDER_DEFAULT_APPROVED_BY=NULL"
echo "APPROVAL_GATE_CONSUMES_STATUS_APPROVED=YES"
echo "APPROVAL_GATE_CREATES_APPROVED_STATUS=NO"
echo "APPROVAL_GATE_CREATES_USER_AUTHORITY=NO"
echo

echo "=== HISTORICAL REUSE-BOUNDARY DETERMINATION ==="
echo "APPROVAL_SOURCE_CLASSIFICATION_COMMIT=9ee13fd29"
echo "APPROVAL_REUSE_BOUNDARY_COMMIT=48d8c7b7a"
echo "HISTORICAL_CLASSIFICATION_FOUND_COMPLETE_APPROVAL_TRANSITION_OWNER=NO"
echo "HISTORICAL_CLASSIFICATION_REQUIRED_SMALLEST_APPROVAL_WRITE_UNIT_DETERMINATION=YES"
echo "USER_IS_EXECUTION_APPROVAL_AUTHORITY=YES"
echo "MATILDA_SELF_APPROVAL=FORBIDDEN"
echo "CADE_SELF_APPROVAL=FORBIDDEN"
echo "CANONICAL_PACKAGE_APPROVAL_IMPLIES_EXECUTION_APPROVAL=NO"
echo

echo "=== INPUT B CLASSIFICATION ==="
echo "INPUT_B=AUTHORITATIVE_APPROVED_EXECUTION_APPROVAL"
echo "INPUT_B_STATUS=PREEXISTING_CAPABILITY_GAP_CONFIRMED"
echo "MISSING_CAPABILITY=USER_OWNED_APPROVAL_REQUIRED_TO_APPROVED_TRANSITION"
echo "MISSING_DURABILITY=EXACT_APPROVAL_ID_TO_ENVELOPE_AND_SCOPE_BINDING"
echo "MISSING_READABILITY=FAIL_CLOSED_APPROVED_EXECUTION_ARTIFACT_READER"
echo "MISSING_COMPOSITION=COMPILE_APPROVED_USER_DECISION_INTO_EXISTING_EXECUTION_APPROVAL_ARTIFACT"
echo

echo "=== NOT MISSING ==="
echo "USER_INTENT_AUTHORITY_MISSING=NO"
echo "CANONICAL_PACKAGE_AUTHORITY_MISSING=NO"
echo "EXECUTION_ENVELOPE_MISSING=NO"
echo "APPROVAL_GATE_MISSING=NO"
echo "COMMIT_AUTHORITY_GATE_MISSING=NO"
echo "PUSH_AUTHORITY_GATE_MISSING=NO"
echo "LOCAL_COMMIT_EFFECT_MISSING=NO"
echo "REMOTE_PUSH_EFFECT_MISSING=NO"
echo "BOUNDED_EXECUTION_COMPOSITION_MISSING=NO"
echo

echo "=== ARCHITECTURAL BOUNDARY ==="
echo "NEW_GENERAL_APPROVAL_SYSTEM_REQUIRED=NO"
echo "PARALLEL_APPROVAL_SYSTEM_PROHIBITED=YES"
echo "EXISTING_EXECUTION_APPROVAL_CONCEPT_MUST_BE_REUSED=YES"
echo "APPROVAL_TRANSITION_MUST_BIND_EXACT_ENVELOPE=YES"
echo "APPROVAL_TRANSITION_MUST_BIND_EXACT_VERSION_CONTROL_SCOPE=YES"
echo "APPROVAL_TRANSITION_MUST_RECORD_USER_OWNED_DECISION=YES"
echo "APPROVAL_REPLAY_ACROSS_DIFFERENT_ENVELOPE=PROHIBITED"
echo "MODEL_OR_AGENT_SELF_APPROVAL=PROHIBITED"
echo

echo "=== CORRIDOR 6 CONSEQUENCE ==="
echo "DEDICATED_EXECUTION_ROUTE_IMPLEMENTATION_READY=NO"
echo "PRODUCTION_REACHABILITY_MUST_WAIT_FOR_APPROVAL_TRANSITION=YES"
echo "ROUTE_MOUNT_MUST_WAIT_FOR_APPROVAL_TRANSITION=YES"
echo "FIRST_UPSTREAM_BLOCKER=EXECUTION_APPROVAL_TRANSITION"
echo "CORRIDOR_6_STATUS=OPEN_PREEXISTING_EXECUTION_APPROVAL_TRANSITION_GAP"
echo "PHASE_1_STATUS=ACTIVE"
echo

echo "=== NEXT ACTION ==="
echo "NEXT_TARGET=SMALLEST_NON_DUPLICATIVE_EXECUTION_APPROVAL_TRANSITION_UNIT"
echo "NEXT_DECISION=CLASSIFY_EXACT_PERSISTENCE_REUSE_WRITE_AND_READ_BOUNDARY"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "NO_IMPLEMENTATION_PERFORMED=YES"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
