#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=DELEGATION_WORKSPACE' \
  'ACTIVE_CORRIDOR=REQUEST_CHANGES_PERSISTENCE' \
  'CURRENT_CHECKPOINT=bffc7ad4' \
  'MODE=COLLABORATION' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'PURPOSE=CLASSIFY_REQUEST_CHANGES_SHARED_WORKFLOW_CALL_SEAM'

printf '\n=== WORKFLOW INPUT CONTRACT ===\n'
sed -n '35,125p' server/matilda-chat-workflow.ts

printf '\n=== WORKFLOW PERSISTENCE SEQUENCE ===\n'
sed -n '230,345p' server/matilda-chat-workflow.ts

printf '\n=== EXISTING CHAT ROUTE INVOCATION ===\n'
sed -n '185,245p' routes/api-chat.ts

printf '\n=== APPROVAL REQUEST ID CONSTRUCTION ===\n'
sed -n '105,145p' db/approval-request-model-assembler.ts

printf '\n=== APPROVAL REQUEST API ROUTE ===\n'
sed -n '1,260p' routes/api-approval-request.ts

printf '\n=== EXPLICIT TARGET CONVERSATION CONTRACT ===\n'
grep -n -A45 -B15 \
  'export function createMatildaConversationTurn' \
  db/matilda-conversation-runtime.ts

printf '\n=== ACTIVE CONVERSATION MUTATION CHECK ===\n'
grep -n -E \
  'setActiveMatildaConversation|getOrCreateActiveMatildaConversation|conversation_id' \
  server/matilda-chat-workflow.ts | head -220

printf '\n=== CALL SEAM CLASSIFICATION ===\n'
printf '%s\n' \
  'SHARED_WORKFLOW_ENTRY_POINT=runMatildaConversationWorkflow' \
  'WORKFLOW_ACCEPTS_PROJECT_ID=YES' \
  'WORKFLOW_ACCEPTS_EXPLICIT_CONVERSATION_ID=YES' \
  'EXPLICIT_TARGET_CONVERSATION_RUNTIME=SUPPORTED' \
  'EXPLICIT_TARGET_PRESERVES_ACTIVE_CONVERSATION=VERIFIED_BY_EXISTING_TEST' \
  'REQUEST_CHANGES_ROUTE=NEW_THIN_ORCHESTRATION_ROUTE_REQUIRED' \
  'ROUTE_INPUT=APPROVAL_REQUEST_ID_AND_FEEDBACK' \
  'ROUTE_RESOLVES_RUNTIME_IDENTITIES=SERVER_SIDE' \
  'ROUTE_CALLS_SHARED_WORKFLOW=YES' \
  'SEPARATE_INTERPRETATION_PATH=PROHIBITED' \
  'SEPARATE_FEEDBACK_PERSISTENCE=PROHIBITED' \
  'APPROVAL_REQUEST_MUTATION=PROHIBITED' \
  'DOWNSTREAM_AUTHORITY_GRANTED=NO'

printf '\n=== IMPLEMENTATION READINESS ===\n'
echo 'EXACT_SHARED_WORKFLOW_CALL_SEAM=CONFIRMED'
echo 'ACTIVE_CONVERSATION_PRESERVATION=CONFIRMED'
echo 'NEW_SEMANTIC_AUTHORITY_REQUIRED=NO'
echo 'NEW_PERSISTENCE_REQUIRED=NO'
echo 'CORRIDOR_1_IMPLEMENTATION_READINESS=READY_BOUNDED'
echo 'IMPLEMENTATION_STARTED=NO'
echo 'NEXT_ACTION=DEFINE_BOUNDED_REQUEST_CHANGES_ROUTE_AND_CLIENT_INTEGRATION_UNIT'

printf '\n=== WORKTREE ===\n'
git status --short
