#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 3 — IMPLEMENTATION READINESS CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 635fec8a HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-3-implementation-readiness\.sh$|^ M scripts/classify-phase-3-corridor-3-implementation-readiness\.sh$' ||
  true
)"
test -z "$unexpected"

grep -Fq 'For explanationStatus:' scripts/utils/ollamaChat.ts
grep -Fq 'Set explanationStatus to optional by default.' scripts/utils/ollamaChat.ts
grep -Fq "Set explanationStatus to recommended only when skipping supporting reasoning is likely to materially affect the user's next engineering decision." scripts/utils/ollamaChat.ts
grep -Fq 'For reply:' scripts/utils/ollamaChat.ts
grep -Fq 'Lead with a concise natural-language summary' scripts/utils/ollamaChat.ts
grep -Fq 'After the opening summary, include only the supporting detail needed for the current interaction.' scripts/utils/ollamaChat.ts

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_3=SURFACING_CONTRACT
STATUS=IMPLEMENTATION_READINESS_CLASSIFIED

IMPLEMENTATION_SURFACE=
SCRIPTS_UTILS_OLLAMACHAT_TS_PROMPT_ONLY

EXACT_SEAM=
EXPLANATION_STATUS_INSTRUCTIONS_ADJACENT_TO_REPLY_COMPOSITION_INSTRUCTIONS

REQUIRED_CHANGE=
ADD_BOUNDED_REPLY_COMPOSITION_RULES_THAT_CONDITION_SUPPORTING_DETAIL_ON_EXPLANATION_STATUS_WITHOUT_EXPOSING_THE_STATUS_FIELD

OPTIONAL_REPLY_RULE=
WHEN_EXPLANATION_STATUS_IS_OPTIONAL_KEEP_THE_REPLY_CONCISE_AND_INCLUDE_ONLY_SUPPORTING_REASONING_NEEDED_FOR_THE_IMMEDIATE_INTERACTION

RECOMMENDED_REPLY_RULE=
WHEN_EXPLANATION_STATUS_IS_RECOMMENDED_KEEP_THE_CONCISE_ANSWER_FIRST_THEN_INCLUDE_ENOUGH_SUPPORTING_REASONING_TO_PRESERVE_THE_MATERIAL_ARCHITECTURAL_BOUNDARY_IMPLEMENTATION_BOUNDARY_UNCERTAINTY_TRADEOFF_OR_EVIDENCE_INTERPRETATION_THAT_COULD_CHANGE_THE_USERS_NEXT_DECISION

VISIBLE_REASONING_STATUS_LABEL=
FORBIDDEN_BY_THIS_SURFACING_CONTRACT

STATUS_FIELD_USER_VISIBLE=
NO

UI_CHANGE=
NO

WORKFLOW_CHANGE=
NO

SCHEMA_CHANGE=
NO

NEW_RUNTIME_SEAM=
NO

MODEL_INVOCATION_COUNT_CHANGE=
NO

RETRY_CHANGE=
NO

FAIL_CLOSED_VALIDATION_CHANGE=
NO

DURABLE_INTERPRETATION_CHANGE=
NO

INVESTIGATION_LIFECYCLE_CHANGE=
NO

SUPPORT_PROVENANCE_CHANGE=
NO

ROLLBACK_BOUNDARY=
REMOVE_ONLY_THE_NEW_BOUNDED_REPLY_COMPOSITION_LINES_AND_THEIR_TARGETED_PROMPT_CONTRACT_TEST_ASSERTIONS

TARGETED_TEST_REQUIRED=
YES

TARGETED_TEST_SCOPE=
ASSERT_OPTIONAL_AND_RECOMMENDED_SURFACING_INSTRUCTIONS_EXIST__ASSERT_NO_MANDATORY_VISIBLE_REASONING_STATUS_LABEL__PRESERVE_EXISTING_RESPONSE_CONTRACT_GUARDS

CORRIDOR_2_RELIABILITY_LIMIT=
PRESERVED

DO_NOT_CLAIM=
MODEL_BEHAVIORAL_RELIABILITY

IMPLEMENTATION_READINESS=
READY

IMPLEMENTATION_AUTHORIZED=
NO

PRODUCTION_CHANGE=
NONE

DR_NOW=
NO

NEXT_REQUIRED_EVENT=
EXPLICIT_USER_IMPLEMENTATION_AUTHORIZATION
MAP
