#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY BOUNDED PROMPT DIAGNOSTIC STOP CAUSE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor cc6404f0 HEAD

implementation_unit="scripts/implement-bounded-validation-only-prompt-presentation-diagnostic.sh"
runner="scripts/run-bounded-prompt-presentation-diagnostic.ts"
ollama="scripts/utils/ollamaChat.ts"

test -f "$implementation_unit"

echo "=== OBSERVED STATE ==="
git status --short

if [[ -f "$runner" ]]; then
  echo "RUNNER_FILE=PRESENT"
else
  echo "RUNNER_FILE=ABSENT"
fi

if grep -q 'validationPromptPresentationVariant' "$ollama"; then
  echo "OLLAMA_DIAGNOSTIC_MARKER=PRESENT"
else
  echo "OLLAMA_DIAGNOSTIC_MARKER=ABSENT"
fi

if grep -q 'test -z "$(git status --porcelain)"' "$implementation_unit"; then
  echo "IMPLEMENTATION_UNIT_CLEAN_WORKTREE_GUARD=PRESENT"
else
  echo "IMPLEMENTATION_UNIT_CLEAN_WORKTREE_GUARD=ABSENT"
fi

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

UNIT=
BOUNDED_VALIDATION_ONLY_PROMPT_PRESENTATION_DIAGNOSTIC

STOP_CAUSE=
IMPLEMENTATION_UNIT_ABORTED_ON_CLEAN_WORKTREE_GUARD_BECAUSE_THE_IMPLEMENTATION_UNIT_FILE_ITSELF_WAS_UNTRACKED

EVIDENCE=
UNTRACKED_IMPLEMENTATION_UNIT_PRESENT
RUNNER_FILE_ABSENT
OLLAMA_DIAGNOSTIC_MARKERS_ABSENT
AUTHORIZATION_ANCESTOR_PRESENT

IMPLEMENTATION_BODY_EXECUTED=
NO

PARTIAL_RUNTIME_EDIT=
NO

PARTIAL_RUNNER_CREATION=
NO

PRODUCTION_CHANGE=
NONE

FAILURE_CLASS=
ORCHESTRATION_GUARD_CONFLICT_NOT_IMPLEMENTATION_LOGIC_FAILURE

FAILED_IMPLEMENTATION_HYPOTHESIS_COUNT=
1

ROLLBACK_REQUIRED=
NO

SAFE_NEXT_STEP=
COMMIT_THE_IMPLEMENTATION_UNIT_AS_A_CHECKPOINT_THEN_EXECUTE_IT_FROM_A_CLEAN_WORKTREE

DIAGNOSTIC_IMPLEMENTATION_AUTHORIZATION=
REMAINS_VALID

PRODUCTION_REMEDY_AUTHORIZATION=
NO

NEXT_ACTION=
COMMIT_IMPLEMENTATION_UNIT_AND_RETRY_ONCE_FROM_CLEAN_WORKTREE
MAP
