#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — OBSERVABILITY READINESS CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 6992ec23 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-2-prevalidation-observability-boundary\.sh$|^\?\? scripts/investigate-phase-3-corridor-2-prevalidation-selected-context-observability\.sh$|^\?\? scripts/investigate-phase-3-corridor-2-selected-context-identity\.sh$|^\?\? scripts/classify-phase-3-corridor-2-observability-readiness\.sh$' ||
  true
)"
test -z "$unexpected"

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION
STATUS=ACTIVE

OBSERVABILITY_PREREQUISITE_CHECKS=ALL_PASS
PREVIOUS_CLASSIFICATION_FAILURE_CAUSE=WORKTREE_GUARD_ONLY
SEMANTIC_PREREQUISITE_FAILURE=NO

PARSED_SELECTED_CONTEXT_AVAILABLE_BEFORE_MEMBERSHIP_VALIDATION=YES
VALIDATED_SELECTED_CONTEXT_OBSERVER_EXISTS=YES
PRE_MEMBERSHIP_SELECTED_CONTEXT_OBSERVER_EXISTS=NO
PARSED_SUPPORT_REFERENCE_PRE_VALIDATION_OBSERVER_EXISTS=YES

DIAGNOSTIC_OBSERVABILITY_GAP=ESTABLISHED
THIRD_BEHAVIOR_VALIDATION_ATTEMPT=NOT_AUTHORIZED
FAILED_VALIDATION_ATTEMPTS=2

BOUNDED_DIAGNOSTIC_OBSERVER_READINESS=READY_FOR_CLASSIFICATION
PRODUCTION_SEMANTIC_CHANGE_REQUIRED=NO
FAIL_CLOSED_VALIDATION_CHANGE_REQUIRED=NO
STRUCTURED_SCHEMA_CHANGE_REQUIRED=NO
PROMPT_CHANGE_REQUIRED=NO
MODEL_INVOCATION_COUNT_CHANGE_REQUIRED=NO

DR_NOW=NO
NEXT_ACTION=CLASSIFY_SMALLEST_VALIDATION_ONLY_PRE_MEMBERSHIP_SELECTED_CONTEXT_OBSERVER_SURFACE
MAP
