#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY SELECTED INTERVENTION SUFFICIENCY AND PHASE 2 CLOSURE READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 1d49faf6 HEAD
test -z "$(git status --porcelain)"

entry="scripts/enter-intervention-selection-and-implementation-readiness-corridor.sh"
test -f "$entry"

grep -q 'SELECTED_INTERVENTION_STATUS=' "$entry"
grep -q '^IMPLEMENTED_AND_VALIDATED$' \
  <(awk '/SELECTED_INTERVENTION_STATUS=/{getline; print}' "$entry")

grep -q 'ADDITIONAL_INTERVENTION_CLASS_REQUIRED=' "$entry"
grep -q '^NO_CURRENT_EVIDENCE_SUPPORTED_REQUIREMENT$' \
  <(awk '/ADDITIONAL_INTERVENTION_CLASS_REQUIRED=/{getline; print}' "$entry")

grep -q 'DETERMINISTIC_REGRESSION=' "$entry"
grep -q '^127_OF_127_PASS$' \
  <(awk '/DETERMINISTIC_REGRESSION=/{getline; print}' "$entry")

grep -q 'POST_PROMOTION_UNSEEDED_BEHAVIORAL_VALIDATION=' "$entry"
grep -q '^10_OF_10_SEMANTIC_PASS$' \
  <(awk '/POST_PROMOTION_UNSEEDED_BEHAVIORAL_VALIDATION=/{getline; print}' "$entry")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_5=
INTERVENTION_SELECTION_AND_IMPLEMENTATION_READINESS

SELECTED_INTERVENTION=
EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION_AS_PRODUCTION_DEFAULT

SELECTED_INTERVENTION_IMPLEMENTATION=
COMPLETE

SELECTED_INTERVENTION_VALIDATION=
COMPLETE

DETERMINISTIC_REGRESSION=
127_OF_127_PASS

POST_PROMOTION_PRODUCTION_BEHAVIORAL_VALIDATION=
10_OF_10_SEMANTIC_PASS

UNSUPPLIED_SUPPORT_FAILURES=
0_OF_10

FAIL_CLOSED_OR_RUNTIME_REJECTIONS=
0_OF_10

SEMANTIC_RELIABILITY_DESPITE_OUTPUT_VARIANCE=
ESTABLISHED_ON_TESTED_PRODUCTION_SURFACE

GENERATION_CONTROL_INTERVENTION=
NOT_REQUIRED_BY_CURRENT_EVIDENCE

MODEL_CAPABILITY_INTERVENTION=
NOT_REQUIRED_BY_CURRENT_EVIDENCE

OTHER_BOUNDED_GENERATION_INPUT_INTERVENTION=
NOT_REQUIRED_BY_CURRENT_EVIDENCE

FAIL_CLOSED_VALIDATION=
PRESERVED

SUPPORT_PROVENANCE_CONTRACT=
PRESERVED

SELECTED_CONTEXT_SEGMENT_CONTRACT=
PRESERVED

STRUCTURED_RESPONSE_SCHEMA=
PRESERVED

MODEL=
UNCHANGED

GENERATION_POLICY=
UNCHANGED

RETRY_OR_SECOND_MODEL_CALL=
NONE

ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=
PRESERVED

SELECTED_INTERVENTION_SUFFICIENCY=
ESTABLISHED_FOR_CURRENT_RELIABILITY_FAILURE_TARGET_ON_TESTED_PRODUCTION_SURFACE

ADDITIONAL_INTERVENTION_REQUIRED=
NO_CURRENT_EVIDENCE_SUPPORTED_REQUIREMENT

CORRIDOR_5_STATUS=
READY_FOR_CLOSURE

PHASE_2_CLOSURE_READINESS=
READY

NEW_PRODUCTION_CHANGE=
NONE

NEXT_ACTION=
CLOSE_INTERVENTION_SELECTION_CORRIDOR_AND_PHASE_2
MAP
