#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="e26a16122"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — MINIMUM SAFE PRODUCTION REACHABILITY SURFACE CLASSIFICATION ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "ROUTE_IMPLEMENTATION_AUTHORIZED=NO"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo

echo "=== CURRENT VERIFIED CAPABILITY ==="
echo "BOUNDED_EXECUTION_ENTRY_POINT_EXISTS=YES"
echo "DURABLE_EXECUTION_APPROVAL_EXISTS=YES"
echo "FAIL_CLOSED_APPROVAL_READER_EXISTS=YES"
echo "APPROVAL_COMPILER_EXISTS=YES"
echo "GOVERNED_COMMIT_EFFECT_EXISTS=YES"
echo "GOVERNED_PUSH_EFFECT_EXISTS=YES"
echo "PRODUCTION_CALLER_EXISTS=NO"
echo

echo "=== EXISTING ROUTE DISPOSITIONS ==="
echo "CANONICAL_PACKAGE_ROUTE=REJECT"
echo "CANONICAL_PACKAGE_ROUTE_REASON=PACKAGE_APPROVAL_MUST_NOT_IMPLY_EXECUTION_APPROVAL_OR_EXECUTION"
echo
echo "GOVERNANCE_DELEGATION_ROUTE=REJECT"
echo "GOVERNANCE_DELEGATION_ROUTE_REASON=DELEGATION_ROUTE_EXPLICITLY_DENIES_EXECUTION_AND_DOWNSTREAM_AUTHORITY"
echo
echo "LEGACY_EXECUTION_AUTHORIZATION_ROUTE=REJECT"
echo "LEGACY_EXECUTION_AUTHORIZATION_ROUTE_REASON=LEGACY_ROUTE_CREATES_NONCANONICAL_IN_MEMORY_AUTHORIZATION_AND_DOES_NOT_USE_DURABLE_EXECUTION_APPROVAL"
echo
echo "INTERNAL_CALLER_ONLY=REJECT"
echo "INTERNAL_CALLER_ONLY_REASON=DOES_NOT_CREATE_OPERATOR_REACHABLE_PRODUCTION_ACTIVATION_SURFACE"
echo

echo "=== SELECTED MINIMUM SAFE SURFACE ==="
echo "SELECTED_SURFACE=NEW_DEDICATED_EXECUTION_ROUTE"
echo "SELECTION_STATUS=CONFIRMED_BY_CURRENT_REPOSITORY_EVIDENCE"
echo "NEW_AUTHORITY_CREATED_BY_ROUTE=NO"
echo "APPROVAL_CREATED_BY_ROUTE=NO"
echo "ENVELOPE_CREATED_BY_ROUTE=NO"
echo "DELEGATION_CREATED_BY_ROUTE=NO"
echo "CANONICAL_PACKAGE_CREATED_BY_ROUTE=NO"
echo
echo "ROUTE_PURPOSE=COMPOSE_EXISTING_DURABLE_APPROVAL_WITH_EXISTING_BOUNDED_EXECUTION_ENTRY_POINT"
echo "ROUTE_MUST_FAIL_CLOSED=YES"
echo

echo "=== MINIMUM ROUTE INPUT CONTRACT ==="
echo "INPUT_APPROVAL_ID=REQUIRED"
echo "INPUT_ENVELOPE_ID=REQUIRED"
echo "INPUT_EXECUTION_ID=REQUIRED"
echo "INPUT_COMMIT_REQUESTED=REQUIRED_BOOLEAN"
echo "INPUT_PUSH_REQUESTED=REQUIRED_BOOLEAN"
echo "INPUT_COMMIT_MESSAGE=REQUIRED_WHEN_COMMIT_REQUESTED"
echo "INPUT_EXPECTED_REMOTE_URL=REQUIRED_WHEN_PUSH_REQUESTED"
echo
echo "CLIENT_SUPPLIED_APPROVED_BY=PROHIBITED_AS_AUTHORITY_SOURCE"
echo "CLIENT_SUPPLIED_COMMIT_AUTHORIZED=PROHIBITED_AS_AUTHORITY_SOURCE"
echo "CLIENT_SUPPLIED_PUSH_AUTHORIZED=PROHIBITED_AS_AUTHORITY_SOURCE"
echo "CLIENT_SUPPLIED_PACKAGE_AUTHORITY=PROHIBITED"
echo "CLIENT_SUPPLIED_ENVELOPE_CONTENT=PROHIBITED"
echo

echo "=== REQUIRED ROUTE COMPOSITION ==="
echo "STEP_1=LOAD_EXACT_DURABLE_EXECUTION_APPROVAL_BY_APPROVAL_ID_AND_ENVELOPE_ID"
echo "STEP_2=FAIL_CLOSED_IF_APPROVAL_MISSING_EXPIRED_MISMATCHED_OR_REPLAYED"
echo "STEP_3=LOAD_OR_RECONSTRUCT_EXACT_CANONICAL_GOVERNANCE_ENVELOPE"
echo "STEP_4=COMPILE_PERSISTED_APPROVAL_TO_EXISTING_EXECUTION_APPROVAL_GATE_SHAPE"
echo "STEP_5=BIND_EXISTING_EXECUTION_APPROVAL_EVALUATOR"
echo "STEP_6=CALL_EXISTING_BOUNDED_PRODUCTION_EXECUTION_ENTRY_POINT"
echo "STEP_7=RETURN_EXISTING_CORRELATED_COMMIT_AND_PUSH_PROOFS_WITH_EXECUTION_ID"
echo

echo "=== PROOF / OUTPUT CONTRACT ==="
echo "OUTPUT_EXECUTION_ID=REQUIRED"
echo "OUTPUT_COMMIT_REQUESTED=REQUIRED"
echo "OUTPUT_PUSH_REQUESTED=REQUIRED"
echo "OUTPUT_COMMIT_RESULT=RETURN_EXISTING_RESULT_OR_NULL"
echo "OUTPUT_PUSH_RESULT=RETURN_EXISTING_RESULT_OR_NULL"
echo "ROUTE_MAY_SYNTHESIZE_COMMIT_PROOF=NO"
echo "ROUTE_MAY_SYNTHESIZE_PUSH_PROOF=NO"
echo "COMMIT_IMPLIES_PUSH=NO"
echo

echo "=== SERVER REACHABILITY BOUNDARY ==="
echo "DEDICATED_ROUTE_FILE_REQUIRED=YES_IF_LATER_AUTHORIZED"
echo "SERVER_INDEX_MOUNT_REQUIRED=YES_IF_LATER_AUTHORIZED"
echo "ROUTE_IMPLEMENTATION_AND_ROUTE_MOUNT_ARE_SEPARATE_CHANGE_UNITS=YES"
echo "ROUTE_IMPLEMENTATION_ALONE_CREATES_PRODUCTION_REACHABILITY=NO"
echo "SERVER_MOUNT_CREATES_OPERATOR_REACHABILITY=YES"
echo

echo "=== STILL PROHIBITED ==="
echo "GENERIC_CADE_ROUTE_REACHABILITY=PROHIBITED"
echo "GENERIC_SHELL_AUTHORITY=PROHIBITED"
echo "GENERIC_MUTATION_AUTHORITY=PROHIBITED"
echo "AUTONOMOUS_EXECUTION_AUTHORITY=PROHIBITED"
echo "SCHEDULER_AUTHORITY=PROHIBITED"
echo "MODEL_SELF_APPROVAL=PROHIBITED"
echo "CADE_SELF_APPROVAL=PROHIBITED"
echo "CANONICAL_PACKAGE_APPROVAL_AS_EXECUTION_APPROVAL=PROHIBITED"
echo

echo "=== CLASSIFICATION RESULT ==="
echo "Q1_EXISTING_SAFE_MOUNTED_ROUTE_EXISTS=NO"
echo "Q2_EXISTING_ROUTE_COMPILES_DURABLE_APPROVAL_AND_CALLS_BOUNDED_ENTRY_POINT=NO"
echo "Q3_LEGACY_EXECUTION_AUTHORIZATION_ROUTE_SAFE_FOR_REUSE=NO"
echo "Q4_NEW_DEDICATED_EXECUTION_ROUTE_IS_MINIMUM_SAFE_SURFACE=YES"
echo "Q5_MINIMUM_INPUT_CONTRACT_CLASSIFIED=YES"
echo "Q6_MINIMUM_OUTPUT_PROOF_CONTRACT_CLASSIFIED=YES"
echo "Q7_SERVER_MOUNT_CHANGE_REQUIRED_FOR_REACHABILITY=YES"
echo

echo "=== NEXT GATE ==="
echo "MINIMUM_SAFE_PRODUCTION_REACHABILITY_SURFACE_CLASSIFIED=YES"
echo "ROUTE_IMPLEMENTATION_READY_FOR_SEPARATE_AUTHORIZATION=YES"
echo "ROUTE_IMPLEMENTATION_AUTHORIZED=NO"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo
echo "CORRIDOR_6=SELF_IMPROVEMENT_EXECUTION_ACTIVATION_CLOSURE"
echo "CORRIDOR_6_STATUS=AWAITING_DEDICATED_EXECUTION_ROUTE_IMPLEMENTATION_AUTHORIZATION"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=REQUEST_EXPLICIT_AUTHORIZATION_FOR_UNMOUNTED_DEDICATED_EXECUTION_ROUTE_PLUS_TARGETED_TESTS_ONLY"
echo

echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
