#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — PRE-VALIDATION OBSERVABILITY BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-2-prevalidation-observability-boundary\.sh$|^ M scripts/classify-phase-3-corridor-2-prevalidation-observability-boundary\.sh$' ||
  true
)"
test -z "$unexpected"

grep -q 'observeValidatedSelectedContextSegments' scripts/utils/ollamaChat.ts
grep -q 'observeParsedSupportSourceReferences' scripts/utils/ollamaChat.ts
grep -q 'parseStructuredResponse(rawResponse)' scripts/utils/ollamaChat.ts
grep -q 'Ollama returned a selected context segment that was not supplied in this invocation.' scripts/utils/ollamaChat.ts

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION
STATUS=ACTIVE

PARSED_SELECTED_CONTEXT_AVAILABLE_BEFORE_MEMBERSHIP_VALIDATION=YES
EXISTING_SELECTED_CONTEXT_OBSERVER=VALIDATED_ONLY
EXISTING_SELECTED_CONTEXT_PRE_VALIDATION_OBSERVER=NO
EXISTING_SUPPORT_REFERENCE_PRE_VALIDATION_OBSERVER=YES

FAILURE_LOCATION=
AFTER_STRUCTURED_PARSE_BEFORE_VALIDATED_SELECTED_CONTEXT_OBSERVER

CURRENT_DIAGNOSTIC_GAP=
MODEL_AUTHORED_SELECTED_CONTEXT_IDENTITY_CANNOT_BE_OBSERVED_THROUGH_EXISTING_SELECTED_CONTEXT_OBSERVER_WHEN_MEMBERSHIP_VALIDATION_FAILS

THIRD_BEHAVIOR_VALIDATION_ATTEMPT=NOT_AUTHORIZED
FAILED_HYPOTHESIS_COUNT=2

DIAGNOSTIC_OBSERVABILITY_REQUIRED_BEFORE_THIRD_ATTEMPT=YES
PRODUCTION_SEMANTIC_CHANGE_REQUIRED=NO
FAIL_CLOSED_VALIDATION_CHANGE_REQUIRED=NO
STRUCTURED_SCHEMA_CHANGE_REQUIRED=NO
PROMPT_CHANGE_REQUIRED=NO
MODEL_INVOCATION_COUNT_CHANGE_REQUIRED=NO

NEXT_ACTION=
CLASSIFY_BOUNDED_VALIDATION_ONLY_PRE_MEMBERSHIP_SELECTED_CONTEXT_OBSERVER_IMPLEMENTATION_READINESS

DR_NOW=NO
MAP
