#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — VALIDATION-ONLY OBSERVER SURFACE CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor f19a8acd HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-2-validation-only-observer-surface\.sh$|^ M scripts/classify-phase-3-corridor-2-validation-only-observer-surface\.sh$' ||
  true
)"
test -z "$unexpected"

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION
STATUS=ACTIVE

CURRENT_DIAGNOSTIC_GAP=
MODEL_AUTHORED_SELECTED_CONTEXT_IDENTITY_IS_PARSED_BUT_NOT_OBSERVABLE_BEFORE_FAIL_CLOSED_MEMBERSHIP_VALIDATION

SMALLEST_SAFE_SURFACE=
OPTIONAL_VALIDATION_ONLY_CALLBACK_ON_OLLAMA_CHAT_CONTEXT

PROPOSED_CALLBACK=
observeParsedSelectedContextSegments

CALLBACK_INPUT=
READONLY_PARSED_SELECTED_CONTEXT_SEGMENTS

INVOCATION_LOCATION=
IMMEDIATELY_AFTER_PARSE_STRUCTURED_RESPONSE_AND_BEFORE_SELECTED_CONTEXT_MEMBERSHIP_VALIDATION

PRODUCTION_WORKFLOW_USAGE=
ABSENT

PRODUCTION_SEMANTIC_EFFECT=
NONE

FAIL_CLOSED_MEMBERSHIP_VALIDATION=
UNCHANGED

STRUCTURED_SCHEMA=
UNCHANGED

PROMPT=
UNCHANGED

MODEL_INVOCATION_COUNT=
UNCHANGED

RETRY_POLICY=
UNCHANGED

VALIDATED_SELECTED_CONTEXT_OBSERVER=
UNCHANGED

ROLLBACK_SURFACE=
OLLAMA_CHAT_CONTEXT_OPTIONAL_CALLBACK_PLUS_SINGLE_PRE_VALIDATION_CALLBACK_INVOCATION_PLUS_TARGETED_TEST

IMPLEMENTATION_REQUIRED=
YES_BOUNDED_DIAGNOSTIC_ONLY

IMPLEMENTATION_AUTHORIZED=
NO

THIRD_BEHAVIOR_VALIDATION_ATTEMPT=
NOT_AUTHORIZED

DR_NOW=
NO

NEXT_ACTION=
CLASSIFY_BOUNDED_IMPLEMENTATION_READINESS_FOR_VALIDATION_ONLY_PRE_MEMBERSHIP_SELECTED_CONTEXT_OBSERVER
MAP
