#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=f342389e' \
  'ISSUE_RESOLVED=NO' \
  'RECOVERY_CLASS=ORIGINAL_CONTROLLED_OUTPUT_RECOVERY' \
  'ORIGINAL_OUTPUT_RECOVERED=NO' \
  'CONTROLLED_ARM_COMPLETION_ESTABLISHED=NO' \
  'COMPARISON_RESULT_CLASSIFIABLE=NO'

printf '\n=== RECOVERY READINESS ===\n'
printf '%s\n' \
  'ORIGINAL_TTYS168_OUTPUT_REQUIRED=YES' \
  'REPLACEMENT_EXPERIMENT_ALLOWED=NO' \
  'PRODUCTION_CHANGE_ALLOWED=NO' \
  'VALIDATOR_CHANGE_ALLOWED=NO' \
  'NEXT_ACTION=ATTEMPT_DIRECT_RECOVERY_OF_TTYS168_SCROLLBACK_OR_TERMINAL_HISTORY_ONLY'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'NO_NEW_OLLAMA_INVOCATION=YES' \
  'NO_PROCESS_RESTART=YES' \
  'NO_PRODUCTION_MUTATION=YES'

printf '\n=== WORKTREE ===\n'
git status --short
