#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="b89396dba"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — DURABLE EXECUTION ENVELOPE RECONSTRUCTION GAP ==="
echo "MODE=EXECUTION"
echo "ROUTE_IMPLEMENTATION_AUTHORIZED=YES"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo

echo "=== VERIFIED PERSISTENCE BOUNDARY ==="
echo "GOVERNANCE_ENVELOPE_DURABLE_IDENTITY_EXISTS=YES"
echo "GOVERNANCE_ENVELOPE_PERSISTS_PACKAGE_LINEAGE=YES"
echo "GOVERNANCE_ENVELOPE_PERSISTS_DELEGATION_ID=YES"
echo "GOVERNANCE_ENVELOPE_PERSISTS_VALIDATION_ID=YES"
echo "GOVERNANCE_ENVELOPE_PERSISTS_GATE_ID=YES"
echo "GOVERNANCE_ENVELOPE_PERSISTS_VALIDATION_STATUS=YES"
echo "GOVERNANCE_ENVELOPE_PERSISTS_LIFECYCLE_STATE=YES"
echo
echo "GOVERNANCE_ENVELOPE_PERSISTS_PROJECT_TARGET=NO"
echo "GOVERNANCE_ENVELOPE_PERSISTS_REPO_PATH=NO"
echo "GOVERNANCE_ENVELOPE_PERSISTS_BRANCH=NO"
echo "GOVERNANCE_ENVELOPE_PERSISTS_EXPECTED_HEAD=NO"
echo "GOVERNANCE_ENVELOPE_PERSISTS_MUTATION_SCOPE=NO"
echo "GOVERNANCE_ENVELOPE_PERSISTS_ALLOWED_PATHS=NO"
echo "GOVERNANCE_ENVELOPE_PERSISTS_FORBIDDEN_PATHS=NO"
echo "GOVERNANCE_ENVELOPE_PERSISTS_FULL_DELEGATION_AUTHORIZATION=NO"
echo

echo "=== VERIFIED COMPILER BOUNDARY ==="
echo "EXECUTION_ENVELOPE_CONTRACT=createExecutionEnvelope"
echo "CREATE_EXECUTION_ENVELOPE_SOURCE=CALLER_SUPPLIED_INPUT"
echo "CREATE_EXECUTION_ENVELOPE_IS_DURABLE_READER=NO"
echo
echo "PLANNING_DRAFT_BUILDER=buildExecutionEnvelopeDraft"
echo "PLANNING_DRAFT_BUILDER_ROLE=GOVERNED_PLANNING_DRAFT"
echo "PLANNING_DRAFT_RUNTIME_EXECUTION_AUTHORIZATION=FALSE"
echo "PLANNING_DRAFT_PROJECT_TARGET_SOURCE=CALLER_INPUT_WITH_PROCESS_DEFAULTS"
echo "PLANNING_DRAFT_MUTATION_SCOPE_SOURCE=CALLER_INPUT"
echo "PLANNING_DRAFT_DELEGATION_STATE_DEFAULT=DELEGATED_PLANNING_ONLY"
echo "PLANNING_DRAFT_SAFE_AS_DURABLE_EXECUTION_RECONSTRUCTION_SOURCE=NO"
echo

echo "=== EXECUTION GATE REQUIREMENTS ==="
echo "APPROVAL_GATE_REQUIRES_PROJECT_TARGET_REPO_PATH=YES"
echo "APPROVAL_GATE_REQUIRES_PROJECT_TARGET_BRANCH=YES"
echo "APPROVAL_GATE_REQUIRES_EXPECTED_HEAD_FOR_COMMIT=YES"
echo "APPROVAL_GATE_REQUIRES_ALLOWED_PATHS_FOR_COMMIT=YES"
echo "APPROVAL_GATE_REQUIRES_DELEGATED_ENVELOPE=YES"
echo "GOVERNED_GIT_ADAPTERS_DEPEND_ON_THESE_FIELDS=YES"
echo

echo "=== CLASSIFICATION ==="
echo "Q1_REQUIRED_EXECUTION_FIELDS_DIRECTLY_PERSISTED=NO"
echo "Q2_CANONICAL_DURABLE_RECONSTRUCTION_SOURCE_ESTABLISHED=NO"
echo "Q3_EXISTING_DURABLE_FULL_EXECUTION_ENVELOPE_COMPILER_ESTABLISHED=NO"
echo "Q4_SAFE_REUSE_WITHOUT_DUPLICATING_OR_INVENTING_SEMANTICS=NO"
echo "Q5_REQUIRED_EXECUTION_FIELDS_CURRENTLY_LACK_ESTABLISHED_DURABLE_CANONICAL_SOURCE=YES"
echo
echo "NARROW_READ_ONLY_READER_ALONE_SUFFICIENT=NO"
echo "AUTHORIZED_ROUTE_CAN_BE_IMPLEMENTED_SAFELY_NOW=NO"
echo "REASON=READER_WOULD_HAVE_TO_INVENT_OR_ACCEPT_NONAUTHORITATIVE_EXECUTION_SCOPE_AND_PROJECT_TARGET_FIELDS"
echo

echo "=== FAILURE CONTAINMENT ==="
echo "DO_NOT_INVENT_REPO_PATH=YES"
echo "DO_NOT_INVENT_BRANCH=YES"
echo "DO_NOT_CAPTURE_CURRENT_HEAD_AS_AUTHORITY=YES"
echo "DO_NOT_INVENT_ALLOWED_PATHS=YES"
echo "DO_NOT_REUSE_PLANNING_DRAFT_AS_EXECUTION_AUTHORITY=YES"
echo "DO_NOT_ACCEPT_CLIENT_SUPPLIED_ENVELOPE_CONTENT_AS_AUTHORITY=YES"
echo "DO_NOT_WEAKEN_APPROVAL_GATE=YES"
echo "DO_NOT_IMPLEMENT_ROUTE_AROUND_MISSING_DURABLE_FIELDS=YES"
echo

echo "=== IMPLEMENTATION AUTHORIZATION EFFECT ==="
echo "EXISTING_ROUTE_IMPLEMENTATION_AUTHORIZATION_REMAINS_BOUNDED=YES"
echo "AUTHORIZATION_DOES_NOT_COVER_NEW_EXECUTION_ENVELOPE_PERSISTENCE=YES"
echo "AUTHORIZATION_DOES_NOT_COVER_NEW_AUTHORITY_SOURCE=YES"
echo "AUTHORIZED_IMPLEMENTATION_PAUSED_ON_NEW_EVIDENCE=YES"
echo

echo "=== NEXT BOUNDARY ==="
echo "NEXT_TARGET=IDENTIFY_EXISTING_DURABLE_CANONICAL_SOURCES_FOR_PROJECT_TARGET_MUTATION_SCOPE_AND_DELEGATION_AUTHORIZATION_OR_CONFIRM_PERSISTENCE_GAP"
echo "IF_NO_EXISTING_SOURCE=CLASSIFY_MINIMUM_EXECUTION_ENVELOPE_DURABILITY_UNIT_FOR_SEPARATE_AUTHORIZATION"
echo
echo "ROUTE_FILE_CREATED=NO"
echo "SERVER_INDEX_CHANGED=NO"
echo "PRODUCTION_REACHABILITY_CHANGED=NO"
echo "GIT_EFFECT_CHANGED=NO"
echo "CORRIDOR_6_STATUS=OPEN_DURABLE_EXECUTION_ENVELOPE_GAP"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=INVESTIGATE_DURABLE_AUTHORITATIVE_SOURCE_OF_REQUIRED_EXECUTION_ENVELOPE_FIELDS"
echo

echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
