#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY CORRIDOR 5 AND PHASE CLOSURE READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 3eeccb63 HEAD
test -z "$(git status --porcelain)"

source_file="scripts/enter-intervention-boundary-corridor.sh"
test -f "$source_file"

for required in \
  PROMPT_OR_RESPONSE_PRESENTATION \
  GENERATION_CONTROLS_OR_SAMPLING_POLICY \
  MODEL_CAPABILITY \
  OTHER_BOUNDED_GENERATION_INPUT_CONDITIONS
do
  grep -q "^${required}$" "$source_file"
done

grep -q '^SPECULATIVE_LAYERING=$' "$source_file"
grep -q '^NOT_ALLOWED$' <(awk '/SPECULATIVE_LAYERING=/{getline; print}' "$source_file")

grep -q '^PRODUCTION_REMEDY_SELECTED=$' "$source_file"
grep -q '^NO$' <(awk '/PRODUCTION_REMEDY_SELECTED=/{getline; print}' "$source_file")

cat <<'MAP'
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE=
STARTING_BOUNDARY_AND_RELIABILITY_BASELINE

CORRIDOR_5=
INTERVENTION_BOUNDARY

PRIMARY_FAILURE_OWNER_CLASS=
MODEL_GENERATION_LAYER

INTERVENTION_CLASS_1=
PROMPT_OR_RESPONSE_PRESENTATION

INTERVENTION_CLASS_2=
GENERATION_CONTROLS_OR_SAMPLING_POLICY

INTERVENTION_CLASS_3=
MODEL_CAPABILITY

INTERVENTION_CLASS_4=
OTHER_BOUNDED_GENERATION_INPUT_CONDITIONS

INTERVENTION_ORDER=
PREFER_SMALLEST_EVIDENCE_SUPPORTED_CHANGE_BEFORE_BROADER_GENERATION_OR_MODEL_CHANGES

FAIL_CLOSED_VALIDATION=
PRESERVED_AS_REQUIRED_CONSTRAINT

SUPPORT_PROVENANCE_CONTRACT=
PRESERVED_AS_REQUIRED_CONSTRAINT

AUTHORITY_BOUNDARIES=
PRESERVED_AS_REQUIRED_CONSTRAINT

ARCHITECTURAL_INVARIANTS=
PRESERVED_AS_REQUIRED_CONSTRAINT

SPECULATIVE_LAYERING=
PROHIBITED

PRODUCTION_REMEDY_SELECTED=
NO

INTERVENTION_BOUNDARY_CLASSIFICATION=
COMPLETE

CORRIDOR_5_STATUS=
READY_FOR_CLOSURE

PHASE_CORRIDOR_COUNT=
5

PHASE_DIAGNOSIS_DEFINED=
YES

PHASE_FAILURE_BASELINE_DEFINED=
YES

PHASE_FAILURE_OWNERSHIP_DEFINED=
YES

PHASE_CONSTRAINTS_DEFINED=
YES

PHASE_INTERVENTION_BOUNDARY_DEFINED=
YES

PHASE_CLOSURE_READINESS=
ESTABLISHED

NEW_PRODUCTION_CHANGE=
NONE

IMPLEMENTATION_AUTHORIZED=
NO_NEW_IMPLEMENTATION

DR_REQUIRED_BEFORE_PHASE_CLOSURE=
YES

NEXT_ACTION=
STOP_FOR_CORRIDOR_5_AND_PHASE_DR_CHECKPOINT
MAP
