#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=54aa3fe7' \
  'ISSUE_RESOLVED=NO' \
  'UNSEEDED_ARM_COMPLETE=YES' \
  'CONTROLLED_ARM_COMPLETE=UNKNOWN' \
  'OBSERVATION_STATE=REPEATED_ACTIVE_OLLAMA_CONNECTION_WITHOUT_NEW_CONTROLLED_RESULT_OUTPUT'

printf '\n=== CURRENT PROCESS STATE ===\n'
pgrep -af 'run-dashboard-generation-control-comparison|tsx' || true

printf '\n=== CURRENT OLLAMA CONNECTION ===\n'
lsof -nP -p 71378 -iTCP 2>/dev/null | grep '11434' || true
ollama ps || true

printf '\n=== CLASSIFICATION ===\n'
printf '%s\n' \
  'ACTIVE_PROCESS_CONFIRMED=YES' \
  'ACTIVE_OLLAMA_CONNECTION_CONFIRMED=YES' \
  'CONTROLLED_RESULT_PROGRESS_CONFIRMED=NO' \
  'STALLED_PROCESS_ESTABLISHED=NO' \
  'PROCESS_TERMINATION_JUSTIFIED=NO' \
  'REPEATED_INSPECTION_ADDS_NEW_CAUSAL_EVIDENCE=NO' \
  'NEXT_ACTION=RETURN_TO_TTYS168_AND_CAPTURE_THE_EXISTING_RUN_OUTPUT_WHEN_THE_CURRENT_INVOCATION_RETURNS;DO_NOT_CREATE_FURTHER_INSPECTION_CHECKPOINTS'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'NEW_EXPERIMENT=NO' \
  'PROCESS_KILL=NO' \
  'PRODUCTION_CHANGE=NO' \
  'VALIDATOR_CHANGE=NO' \
  'GENERATION_POLICY_CHANGE=NO'

printf '\n=== WORKTREE ===\n'
git status --short
