#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PRODUCTION BEHAVIORAL RELIABILITY CONFIRMATION SUFFICIENCY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor e30ee03c HEAD
test -z "$(git status --porcelain)"

corridor2="scripts/close-reliability-contract-reconciliation-and-enter-production-behavioral-reliability-confirmation.sh"
test -f "$corridor2"

grep -q 'CORRIDOR_2_STATUS=' "$corridor2"
grep -q '^ACTIVE$' \
  <(awk '/CORRIDOR_2_STATUS=/{getline; print}' "$corridor2")

grep -q 'EXISTING_POST_PROMOTION_BEHAVIORAL_EVIDENCE=' "$corridor2"
grep -q '^10_OF_10_SEMANTIC_PASS$' \
  <(awk '/EXISTING_POST_PROMOTION_BEHAVIORAL_EVIDENCE=/{getline; print}' "$corridor2")

grep -q 'EXISTING_UNSUPPORTED_PROVENANCE_FAILURES=' "$corridor2"
grep -q '^0_OF_10$' \
  <(awk '/EXISTING_UNSUPPORTED_PROVENANCE_FAILURES=/{getline; print}' "$corridor2")

grep -q 'EXISTING_FAIL_CLOSED_OR_RUNTIME_REJECTIONS=' "$corridor2"
grep -q '^0_OF_10$' \
  <(awk '/EXISTING_FAIL_CLOSED_OR_RUNTIME_REJECTIONS=/{getline; print}' "$corridor2")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION
PHASE_3=
PRODUCTION_RELIABILITY_VALIDATION_AND_MILESTONE_CLOSURE
CORRIDOR_2=
PRODUCTION_BEHAVIORAL_RELIABILITY_CONFIRMATION
VALIDATION_TARGET=
ORDINARY_UNSEEDED_PRODUCTION_BEHAVIOR_REMAINS_USABLE_SEMANTICALLY_VALID_AND_FREE_OF_ESTABLISHED_UNSUPPORTED_PROVENANCE_FAILURE
AVAILABLE_POST_PROMOTION_SAMPLE=
10_SEQUENTIAL_UNSEEDED_RUNS
SEMANTIC_PASSES=
10_OF_10
UNSUPPORTED_PROVENANCE_FAILURES=
0_OF_10
FAIL_CLOSED_OR_RUNTIME_REJECTIONS=
0_OF_10
UNIQUE_EXACT_OUTPUT_FINGERPRINTS=
10_OF_10
SEMANTIC_RELIABILITY_DESPITE_OUTPUT_VARIANCE=
ESTABLISHED_ON_TESTED_PRODUCTION_SURFACE
ADDITIONAL_BEHAVIORAL_SAMPLE_REQUIRED=
NO_CURRENT_EVIDENCE_SUPPORTED_REQUIREMENT
ADDITIONAL_VALIDATION_GAP=
NONE_ESTABLISHED
BEHAVIORAL_RELIABILITY_CONFIRMATION=
SUFFICIENT_ON_CURRENT_EVIDENCE
NEW_PRODUCTION_CHANGE=
NONE
IMPLEMENTATION_AUTHORIZED=
NO_NEW_IMPLEMENTATION
CORRIDOR_2_STATUS=
READY_FOR_CLOSURE
NEXT_ACTION=
CLOSE_PRODUCTION_BEHAVIORAL_RELIABILITY_CONFIRMATION_AND_ENTER_FAIL_CLOSED_AND_PROVENANCE_CONTRACT_CONFIRMATION
MAP
