#!/bin/bash
set -euo pipefail

cd /Users/marcela-dev/Projects/motherboard-systems-hq-clean

BRANCH="feature/support-source-references-runtime"
EXPECTED_HEAD="$(git rev-parse HEAD)"
REVERT="1c6780fe787a72bb339825a27fd73dd64b16c6ee"

echo "=== EMPTY-HISTORY REVERT — FINAL CAUSALITY CLASSIFICATION ==="

test "$(git rev-parse --abbrev-ref HEAD)" = "$BRANCH"
test -z "$(git diff --cached --name-only)"

REVERT_SCRIPT="$(git show "$REVERT":scripts/revert-matilda-empty-history-prompt-fix.sh)"

printf '%s\n' "$REVERT_SCRIPT" | grep -q 'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503'
printf '%s\n' "$REVERT_SCRIPT" | grep -q 'ISSUE_RESOLVED=NO'
printf '%s\n' "$REVERT_SCRIPT" | grep -q 'MODE=BOUNDED_RUNTIME_REVERT'
printf '%s\n' "$REVERT_SCRIPT" | grep -q 'REVERT_SCOPE=ONE_FILE'
printf '%s\n' "$REVERT_SCRIPT" | grep -q 'REVERT_SOURCE_COMMIT=09342faa'

echo "REVERT_CHECKPOINT=MATILDA_UI_SMOKE_TEST_503"
echo "ISSUE_RESOLVED_AT_REVERT=NO"
echo "REVERT_MODE=BOUNDED_RUNTIME_REVERT"
echo "REVERT_SCOPE=ONE_FILE"
echo "REVERT_TARGET=scripts/utils/ollamaChat.ts"
echo

if printf '%s\n' "$REVERT_SCRIPT" | \
  grep -qiE 'caused.*503|503.*caused|regression.*prompt|prompt.*regression|fix.*caused|introduced.*503'; then
  echo "EXPLICIT_PROMPT_FIX_CAUSATION=PRESENT"
else
  echo "EXPLICIT_PROMPT_FIX_CAUSATION=ABSENT"
fi

echo
echo "=== CLASSIFICATION ==="
echo "PRIOR_PROMPT_FIX_CLASSIFICATION=PROMPT_ONLY"
echo "PRIOR_REVERT_CLASSIFICATION=BASELINE_RESTORATION_DURING_UNRESOLVED_503"
echo "PRIOR_REVERT_PROVES_PROMPT_FIX_CAUSED_503=NO"
echo "PRIOR_REVERT_DISQUALIFIES_DYNAMIC_SCHEMA_BOUNDING=NO"
echo "DYNAMIC_SCHEMA_BOUNDING_PREVIOUSLY_ATTEMPTED=NO_EVIDENCE"
echo
echo "CURRENT_PROMPT_CONSTRAINT=EXPLICIT"
echo "CURRENT_EMPTY_HISTORY_ALLOWED_CONVERSATION_IDS=EMPTY"
echo "CURRENT_RAW_MODEL_FABRICATION=PROVEN"
echo "CURRENT_VALIDATOR_FAIL_CLOSED=CORRECT"
echo "CURRENT_PARSER_DEFECT_EVIDENCED=NO"
echo "CURRENT_STATIC_SCHEMA_PERMITS_CONVERSATION_TURN=YES"
echo
echo "HYPOTHESIS_STATUS=SUPPORTED_FOR_BOUNDED_IMPLEMENTATION_PROPOSAL"
echo "PROPOSED_SMALLEST_FIX=INVOCATION_RELATIVE_OUTPUT_SCHEMA_EXCLUDES_CONVERSATION_TURN_WHEN_ALLOWED_ID_UNIVERSE_IS_EMPTY"
echo "PRESERVE_PROJECT_CONTEXT_RUNTIME_PROVENANCE=YES"
echo "PRESERVE_FAIL_CLOSED_VALIDATION=YES"
echo "PRESERVE_AUTHORITY_MODEL=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo

echo "=== SAFETY ==="
test "$(git rev-parse HEAD)" = "$EXPECTED_HEAD"
test -z "$(git diff --cached --name-only)"
echo "CODE_MUTATION=NONE"
echo "DATABASE_MUTATION=NONE"
echo "COMMIT_PERFORMED=NO"
echo "PUSH_PERFORMED=NO"
