#!/usr/bin/env bash
set -euo pipefail

EXPECTED_HEAD="091f2cacd645ed8ea5b639e26ce7ff726c476cfa"
CURRENT_HEAD="$(git rev-parse HEAD)"

echo "EXPECTED_HEAD=${EXPECTED_HEAD}"
echo "CURRENT_HEAD=${CURRENT_HEAD}"
test "${CURRENT_HEAD}" = "${EXPECTED_HEAD}"

echo "FAILED_HYPOTHESIS_1=SOURCE_MJS_COMPOSITION_IMPORTED_FROM_COMPILED_SERVER"
echo "FAILED_HYPOTHESIS_2=TYPESCRIPT_COMPOSITION_WITH_EXISTING_ROUTE_RUNTIME_GRAPH"
echo "KNOWN_NONEMITTED_RUNTIME_DEPENDENCY=COMPILE_PERSISTED_EXECUTION_APPROVAL_MJS"
echo "THIRD_HYPOTHESIS_BOUNDARY=CONVERT_ONLY_REACHABLE_NONEMITTED_RUNTIME_SEAMS_REQUIRED_BY_GOVERNANCE_EXECUTION_ROUTE"
echo "FIRST_REQUIRED_CONVERSION=COMPILE_PERSISTED_EXECUTION_APPROVAL_MJS_TO_TSC_EMITTED_TYPESCRIPT"
echo "APPROVAL_GATE_CONVERSION_REQUIRED_FOR_CURRENT_UNMOUNTED_ROUTE_GRAPH=NO"
echo "PRODUCTION_COMPOSITION_CONVERSION_REQUIRED_BEFORE_MOUNT=YES"
echo "ROUTE_MOUNT_INCLUDED=NO"
echo "AUTHORITY_MODEL_CHANGE_INCLUDED=NO"
echo "GENERIC_CADE_CHANGE_INCLUDED=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CORRIDOR_6_STATUS=ACTIVE"
echo "PHASE_1_STATUS=ACTIVE"
echo "PRODUCTION_CHANGE=NONE"
