#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=8e5b70a4' \
  'ISSUE_RESOLVED=NO' \
  'ACTION=CLASSIFY_POST_FIX_TIMEOUT_RUNTIME_EVIDENCE' \
  'NEW_OLLAMA_INVOCATION=NO' \
  'PRODUCTION_CHANGE=NO'

printf '\n=== VERIFIED TIMEOUT CONTRACT ===\n'
printf '%s\n' \
  'OLLAMA_TIMEOUT_MS=60000' \
  'TIMEOUT_SCOPE=ENTIRE_FETCH_GENERATION_AND_RESPONSE_RETURN' \
  'ABORT_CONTROLLER_ENFORCES_TIMEOUT=YES' \
  'PARSED_OUTPUT_AVAILABLE_BEFORE_RESPONSE_RETURN=NO'

printf '\n=== VERIFIED RUNTIME STATE ===\n'
printf '%s\n' \
  'OLLAMA_SERVER_RUNNING=YES' \
  'GEMMA3_4B_MODEL_LOADED=YES' \
  'MODEL_CONTEXT_WINDOW=131072' \
  'ACTIVE_VALIDATION_REQUEST_AT_INSPECTION_TIME=NO' \
  'POST_FIX_TIMEOUT_COUNT=2'

printf '\n=== RESOURCE EVIDENCE ===\n'
printf '%s\n' \
  'SYSTEM_LOAD_EXTREME=NO' \
  'MEMORY_PRESSURE_SIGNAL_PRESENT=YES' \
  'SIGNIFICANT_COMPRESSION_AND_SWAP_ACTIVITY_PRESENT=YES' \
  'RESOURCE_PRESSURE_AS_TIMEOUT_CAUSE_ESTABLISHED=NO'

printf '\n=== CAUSAL CLASSIFICATION ===\n'
printf '%s\n' \
  'SUPPORT_REFERENCE_FIX_VALIDATED=NO' \
  'SUPPORT_REFERENCE_FIX_DISPROVEN=NO' \
  'VALIDATOR_FAILURE_CAUSED_TIMEOUT=NO_EVIDENCE' \
  'PROMPT_SERIALIZATION_FAILURE_CAUSED_TIMEOUT=NO_EVIDENCE' \
  'OLLAMA_SERVICE_UNAVAILABLE=NO' \
  'HARD_60_SECOND_GENERATION_BOUNDARY_CONFIRMED=YES' \
  'GENERATION_EXCEEDED_60_SECONDS_IN_TWO_POST_FIX_ATTEMPTS=YES' \
  'WHY_GENERATION_EXCEEDED_60_SECONDS=NOT_ESTABLISHED' \
  'THIRD_IDENTICAL_VALIDATION_JUSTIFIED=NO'

printf '\n=== NEXT INVESTIGATION CLASS ===\n'
printf '%s\n' \
  'NEXT_ACTION=CLASSIFY_REQUEST_SIZE_AND_PROMPT_TOKEN_LOAD_WITHOUT_RUNNING_OLLAMA' \
  'PURPOSE=DETERMINE_WHETHER_POST_FIX_PROMPT_AND_EXISTING_CONTEXT_CREATE_A_MATERIAL_GENERATION_LOAD_CHANGE_RELATIVE_TO_PRE_FIX_SUCCESSFUL_RESPONSES' \
  'TIMEOUT_CHANGE_AUTHORIZED=NO' \
  'MODEL_CHANGE_AUTHORIZED=NO' \
  'PROMPT_CHANGE_AUTHORIZED=NO'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'THIRD_OLLAMA_INVOCATION=NO' \
  'TIMEOUT_CHANGED=NO' \
  'MODEL_CHANGED=NO' \
  'VALIDATOR_CHANGED=NO' \
  'PROMPT_CHANGED=NO' \
  'GENERATION_POLICY_CHANGED=NO'

printf '\n=== WORKTREE ===\n'
git status --short
