#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=d2190917' \
  'ISSUE_RESOLVED=NO' \
  'ACTION=CLASSIFY_TIMEOUT_POLICY_AND_RESPONSE_LENGTH_BOUNDARY' \
  'NEW_OLLAMA_INVOCATION=NO' \
  'PRODUCTION_CHANGE=NO'

printf '\n=== VERIFIED RUNTIME EVIDENCE ===\n'
printf '%s\n' \
  'CLIENT_TIMEOUT_MS=60000' \
  'PRE_FIX_COMPLETED_REQUEST_1_SERVER_DURATION_APPROX_SECONDS=54.21' \
  'PRE_FIX_COMPLETED_REQUEST_2_SERVER_DURATION_APPROX_SECONDS=56.38' \
  'POST_FIX_TIMEOUT_REQUEST_1_SERVER_DURATION_APPROX_SECONDS=60.00' \
  'POST_FIX_TIMEOUT_REQUEST_2_SERVER_DURATION_APPROX_SECONDS=60.00' \
  'POST_FIX_REQUESTS_ACTIVE_AT_ABORT=YES' \
  'POST_FIX_LAST_OBSERVED_DECODED_TOKENS_APPROX=1416_AND_1431' \
  'PROMPT_EVAL_SECONDS_APPROX=10_TO_11' \
  'GENERATION_RATE_TOKENS_PER_SECOND_APPROX=33_TO_34'

printf '\n=== TIMEOUT POLICY CLASSIFICATION ===\n'
printf '%s\n' \
  'CURRENT_TIMEOUT_HAS_LESS_THAN_6_SECONDS_MARGIN_OVER_OBSERVED_PRE_FIX_COMPLETIONS=YES' \
  'CURRENT_TIMEOUT_ABORTS_OTHERWISE_ACTIVE_GENERATION=YES' \
  'CURRENT_TIMEOUT_CAN_PREVENT_STRUCTURED_RESPONSE_COMPLETION=YES' \
  'CURRENT_60_SECOND_TIMEOUT_COMPATIBLE_WITH_ALL_OBSERVED_NORMAL_GENERATION_VARIANCE=NO' \
  'TIMEOUT_BOUNDARY_TOO_CLOSE_TO_OBSERVED_GENERATION_DURATION=YES' \
  'TIMEOUT_POLICY_IS_A_RUNTIME_RELIABILITY_CONSTRAINT=YES'

printf '\n=== IMPORTANT CAUSAL LIMIT ===\n'
printf '%s\n' \
  'TIMEOUT_POLICY_CAUSED_SUPPORT_REFERENCE_SERIALIZATION_DEFECT=NO' \
  'TIMEOUT_POLICY_EXPLAINS_POST_FIX_OUTPUT_NOT_REACHING_VALIDATOR=YES' \
  'WHY_POST_FIX_OUTPUTS_REQUIRE_MORE_GENERATION_TOKENS_THAN_PRE_FIX_OUTPUTS=NOT_ESTABLISHED' \
  'SUPPORT_REFERENCE_FIX_VALIDATED=NO' \
  'SUPPORT_REFERENCE_FIX_DISPROVEN=NO'

printf '\n=== RESPONSE LENGTH BOUNDARY ===\n'
printf '%s\n' \
  'EXPLICIT_MODEL_OUTPUT_TOKEN_LIMIT_ESTABLISHED=NO' \
  'STRUCTURED_RESPONSE_CAN_EXCEED_1400_DECODED_TOKENS=YES' \
  'RESPONSE_LENGTH_REDUCTION_AS_REMEDY_ESTABLISHED=NO' \
  'MODEL_CHANGE_AS_REMEDY_ESTABLISHED=NO' \
  'RETRY_AS_REMEDY_ESTABLISHED=NO'

printf '\n=== IMPLEMENTATION READINESS ===\n'
printf '%s\n' \
  'TIMEOUT_POLICY_CHANGE_CAUSALLY_SUPPORTED_AS_NEXT_RUNTIME_INTERVENTION=YES' \
  'MINIMUM_CHANGE_CLASS=INCREASE_EXISTING_OLLAMA_CLIENT_TIMEOUT_ONLY' \
  'VALIDATOR_CHANGE_REQUIRED=NO' \
  'PROMPT_CHANGE_REQUIRED=NO' \
  'MODEL_CHANGE_REQUIRED=NO' \
  'RETRY_CHANGE_REQUIRED=NO' \
  'DATABASE_CHANGE_REQUIRED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'VALIDATION_AFTER_IMPLEMENTATION_AUTHORIZED=NO' \
  'EXPLICIT_USER_AUTHORIZATION_REQUIRED=YES'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'TIMEOUT_CHANGED=NO' \
  'THIRD_OLLAMA_INVOCATION=NO' \
  'MODEL_CHANGED=NO' \
  'VALIDATOR_CHANGED=NO' \
  'VALIDATOR_WEAKENED=NO' \
  'PROMPT_CHANGED=NO' \
  'GENERATION_POLICY_CHANGED=NO'

printf '\n=== NEXT ACTION ===\n'
printf '%s\n' \
  'NEXT_ACTION=OPEN_BOUNDED_OLLAMA_TIMEOUT_CHANGE_AUTHORIZATION_GATE' \
  'PROPOSED_SCOPE=CHANGE_ONLY_THE_EXISTING_OLLAMA_CLIENT_TIMEOUT_WITH_ROLLBACK_BOUNDARY_AND_SEPARATE_POST_CHANGE_VALIDATION_AUTHORIZATION'

printf '\n=== WORKTREE ===\n'
git status --short
