#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OLLAMA="scripts/utils/ollamaChat.ts"
RUNNER="scripts/run-dashboard-generation-control-comparison.ts"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=eccbb7ca' \
  'ISSUE_RESOLVED=NO' \
  'ACTION=CLASSIFY_MINIMUM_SUPPORT_REFERENCE_OBSERVABILITY_CHANGE' \
  'NEW_OLLAMA_INVOCATION=NO'

printf '\n=== EXISTING OBSERVABILITY SEAM ===\n'
grep -nE \
  'observeParsedSupportSourceReferences|parsedSupport|parsedSupportReferenceCount' \
  "$OLLAMA" "$RUNNER" || true

printf '\n=== VALIDATION ORDER ===\n'
grep -n -A20 -B10 'observeParsedSupportSourceReferences' "$OLLAMA" || true

printf '\n=== RUN RECORD SHAPE ===\n'
sed -n '35,65p' "$RUNNER"
sed -n '290,345p' "$RUNNER"

printf '\n=== CLASSIFICATION ===\n'
printf '%s\n' \
  'PROMPT_VALIDATOR_IDENTITY_SHAPE_ALIGNMENT=ESTABLISHED' \
  'VALIDATOR_MALFUNCTION_ESTABLISHED=NO' \
  'EXISTING_PARSED_SUPPORT_REFERENCE_OBSERVER=YES' \
  'OBSERVER_EXECUTES_BEFORE_PROJECT_CONTEXT_MEMBERSHIP_REJECTION=YES' \
  'CURRENT_RUNNER_CAPTURES_REFERENCE_COUNT_ONLY=YES' \
  'NEW_PRODUCTION_OBSERVABILITY_SEAM_REQUIRED=NO' \
  'MINIMUM_CHANGE_SURFACE=VALIDATION_RUNNER_ONLY' \
  'MINIMUM_CHANGE=ADD_PARSED_SUPPORT_REFERENCE_VALUES_TO_VALIDATION_RUN_RECORD' \
  'PRODUCTION_RUNTIME_SEMANTICS_CHANGE_REQUIRED=NO' \
  'VALIDATOR_CHANGE_REQUIRED=NO' \
  'PROMPT_CHANGE_REQUIRED=NO' \
  'MODEL_CHANGE_REQUIRED=NO' \
  'GENERATION_POLICY_CHANGE_REQUIRED=NO' \
  'NEXT_EVIDENCE=EXACT_MODEL_AUTHORED_SUPPORT_REFERENCE_VALUES_AND_COMPARISON_TO_SUPPLIED_PARENT_IDENTITIES' \
  'IMPLEMENTATION_AUTHORIZED=NO'

printf '\n=== PROPOSED BOUNDED IMPLEMENTATION SURFACE ===\n'
printf '%s\n' \
  'FILE=scripts/run-dashboard-generation-control-comparison.ts' \
  'CHANGE_1=EXTEND_RUN_RECORD_WITH_PARSED_SUPPORT_REFERENCE_VALUES' \
  'CHANGE_2=SERIALIZE_ALREADY_OBSERVED_PARSED_SUPPORT_REFERENCES_ON_ACCEPTED_AND_REJECTED_RUNS' \
  'CHANGE_3=DO_NOT_MODIFY_OLLAMA_CHAT_VALIDATION_OR_PROMPT' \
  'CHANGE_4=DO_NOT_PERSIST_TO_DATABASE' \
  'CHANGE_5=DO_NOT_START_NEW_OLLAMA_INVOCATION_WITHOUT_SEPARATE_AUTHORIZATION'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'PRODUCTION_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_WEAKENING_AUTHORIZED=NO' \
  'PROMPT_CHANGE_AUTHORIZED=NO' \
  'NEW_EXPERIMENT_AUTHORIZED=NO' \
  'NEXT_ACTION=AWAIT_EXPLICIT_AUTHORIZATION_TO_IMPLEMENT_VALIDATION_RUNNER_OBSERVABILITY_ONLY'

printf '\n=== WORKTREE ===\n'
git status --short
