#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="aa5cd6cee"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — GOVERNANCE READER IMPLEMENTATION CONTRACT ==="
echo "MODE=EXECUTION"
echo "PRODUCTION_CHANGE=NONE"
echo

echo "=== VERIFIED SUCCESS SEMANTICS ==="
echo "DELEGATION_SUCCESS_STATUS=AUTHORIZED"
echo "VALIDATION_SUCCESS_STATUS=VALIDATION_PASSED"
echo "ENVELOPE_GATE_SUCCESS_STATUS=OPEN"
echo "STATUS_NORMALIZATION=TRIM_UPPERCASE_SPACES_AND_HYPHENS_TO_UNDERSCORES"
echo "SOURCE_OF_TRUTH=db/governance-lifecycle-enforcement.ts"
echo

echo "=== HELPER OWNERSHIP ==="
echo "EXISTING_STATUS_HELPERS_EXPORTED=NO"
echo "READER_MUST_NOT_WEAKEN_LIFECYCLE_SEMANTICS=YES"
echo "READER_MAY_REUSE_EXPORTED_LIFECYCLE_ASSERTIONS=YES"
echo "DELEGATION_ASSERTION=assertValidationEligible"
echo "VALIDATION_AND_GATE_ASSERTION=assertEnvelopeCreationEligible"
echo

echo "=== READER ARCHITECTURE ==="
echo "OWNER=EXISTING_GOVERNANCE_PERSISTENCE_DOMAIN"
echo "IMPLEMENTATION_SHAPE=NARROW_READ_ONLY_ADAPTER_WITH_INJECTED_DATABASE"
echo "PRODUCTION_DATABASE_HARDCODED_IN_NEW_READER=NO"
echo "TEST_DATABASE=:memory:"
echo "NEW_WRITE_PATH=NO"
echo "NEW_TABLE=NO"
echo "NEW_AUTHORITY=NO"
echo

echo "=== EXACT LOOKUP CONTRACT ==="
echo "DELEGATION_LOOKUP=delegation_id_plus_package_id_plus_package_version"
echo "VALIDATION_LOOKUP=validation_result_id_plus_delegation_id_plus_package_id_plus_package_version"
echo "GATE_LOOKUP=envelope_gate_id_plus_validation_result_id_plus_delegation_id_plus_package_id_plus_package_version"
echo "ENVELOPE_LOOKUP=envelope_id_plus_gate_validation_delegation_package_lineage"
echo "LIMIT_ONE_WITHOUT_EXACT_IDENTITY=PROHIBITED"
echo "LATEST_ROW_AS_AUTHORITY=PROHIBITED"
echo

echo "=== FAIL-CLOSED CONTRACT ==="
echo "MISSING_ARTIFACT=REJECT"
echo "AMBIGUOUS_ARTIFACT=REJECT"
echo "PACKAGE_LINEAGE_MISMATCH=REJECT"
echo "DELEGATION_LINEAGE_MISMATCH=REJECT"
echo "VALIDATION_LINEAGE_MISMATCH=REJECT"
echo "GATE_LINEAGE_MISMATCH=REJECT"
echo "DELEGATION_NOT_AUTHORIZED=REJECT"
echo "VALIDATION_NOT_PASSED=REJECT"
echo "GATE_NOT_OPEN=REJECT"
echo "SYNTHESIZED_GOVERNANCE_SUCCESS=PROHIBITED"
echo

echo "=== TARGETED TEST REQUIREMENTS ==="
echo "TEST_1=READ_EXACT_AUTHORIZED_CORRELATED_GOVERNANCE_CHAIN"
echo "TEST_2=REJECT_UNAUTHORIZED_DELEGATION"
echo "TEST_3=REJECT_FAILED_VALIDATION"
echo "TEST_4=REJECT_CLOSED_GATE"
echo "TEST_5=REJECT_LINEAGE_MISMATCH_OR_REPLAY"
echo "TEST_6=REJECT_MISSING_ARTIFACT"
echo "PRODUCTION_DB_USED_BY_TESTS=NO"
echo

echo "=== PRESERVED AUTHORIZATION BOUNDARY ==="
echo "GOVERNANCE_READ_UNIT_IMPLEMENTATION_AUTHORIZED=YES"
echo "UNMOUNTED_ROUTE_IMPLEMENTATION=SEPARATELY_AUTHORIZED_AND_PAUSED"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "GIT_EFFECT_CHANGES_AUTHORIZED=NO"
echo "GENERIC_CADE_CHANGES_AUTHORIZED=NO"
echo "GENERIC_SHELL_OR_MUTATION_AUTHORITY_AUTHORIZED=NO"
echo "SCHEDULER_OR_AUTONOMY_AUTHORIZED=NO"
echo

echo "=== RESULT ==="
echo "GOVERNANCE_READER_IMPLEMENTATION_CONTRACT_CLASSIFIED=YES"
echo "AUTHORIZED_IMPLEMENTATION_READY=YES"
echo "CORRIDOR_6_STATUS=GOVERNANCE_READ_UNIT_IMPLEMENTATION_READY"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=IMPLEMENT_AUTHORIZED_GOVERNANCE_READ_ONLY_ADAPTER_AND_TARGETED_TESTS"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
