#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PROGRAM RECONCILIATION PHASE 1 DISPOSITION AND SUCCESSOR DECISION BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor d93f3776 HEAD

priority="scripts/reconcile-current-successor-priority-boundary.sh"
prior_program_state="scripts/reconcile-successor-capability-and-program-priority-state.sh"

test -f "$priority"
test -f "$prior_program_state"

echo "=== VERIFY CURRENT PHASE 1 CLOSURE ==="
grep -q 'PRIORITY_BOUNDARY_STATUS=' "$priority"
grep -q 'COMPLETE' "$priority"
grep -q 'PHASE_1_STATUS=' "$priority"
grep -q 'COMPLETE' "$priority"
grep -q 'CURRENT_GENUINE_UNRESOLVED_CAPABILITY_GAPS=' "$priority"
grep -q 'ZERO_ON_CURRENT_INVENTORIED_SURFACE' "$priority"
grep -q 'SUCCESSOR_PRIORITY=' "$priority"
grep -q 'NONE_ESTABLISHED_ON_CURRENT_INVENTORIED_SURFACE' "$priority"
grep -q 'NEXT_MILESTONE_CANDIDATE=' "$priority"
grep -q 'NONE_ESTABLISHED' "$priority"
echo "CURRENT_PHASE_1_CLOSURE=CONFIRMED"

echo
echo "=== VERIFY PRIOR CORRECTED PROGRAM-STATE DOCTRINE ==="
grep -q 'CROSS_TURN_TRANSITION_VALIDATION=' "$prior_program_state"
grep -q 'ALREADY_IMPLEMENTED_AND_VALIDATED' "$prior_program_state"
grep -q 'PRIOR_SUCCESSOR_PRIORITY_CLASSIFICATION=' "$prior_program_state"
grep -q 'SUPERSEDED_BY_REPOSITORY_EVIDENCE' "$prior_program_state"
grep -q 'NEW_IMPLEMENTATION_REQUIRED=' "$prior_program_state"
grep -q '^NO$' <(awk '/NEW_IMPLEMENTATION_REQUIRED=/{getline; print}' "$prior_program_state")
grep -q 'CURRENT_DEFERRED_WORK=' "$prior_program_state"
grep -q 'PRESERVED_WITHOUT_PRIORITY_PROMOTION' "$prior_program_state"
grep -q 'SUCCESSOR_MILESTONE=' "$prior_program_state"
grep -q 'NOT_YET_ESTABLISHED' "$prior_program_state"
echo "PRIOR_CORRECTED_PROGRAM_STATE=CONFIRMED"

echo
echo "=== PHASE 1 DISPOSITION ==="

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION

PHASE_1=
CURRENT_CAPABILITY_AND_DEFERRED_WORK_RECONCILIATION

PHASE_1_CORRIDOR_1=
COMPLETED_RUNTIME_CAPABILITY_INVENTORY
STATUS=
COMPLETE

PHASE_1_CORRIDOR_2=
DEFERRED_WORK_INVENTORY
STATUS=
COMPLETE

PHASE_1_CORRIDOR_3=
UNRESOLVED_CAPABILITY_GAP_CLASSIFICATION
STATUS=
COMPLETE

PHASE_1_CORRIDOR_4=
SUCCESSOR_PRIORITY_BOUNDARY
STATUS=
COMPLETE

PHASE_1_RESULT=
COMPLETE_WITH_ZERO_CURRENT_EVIDENCE_SUPPORTED_UNRESOLVED_CAPABILITY_GAPS

CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION=
IMPLEMENTED_AND_VALIDATED

SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION=
CLOSED

GENERATION_STABILITY=
CLOSED_WITH_KNOWN_PRODUCTION_GENERATION_INSTABILITY

PRODUCTION_GENERATION_INSTABILITY=
PRESERVED_AS_DEFERRED_KNOWN_CONDITION

PRODUCTION_GENERATION_POLICY_REOPENED=
NO

CURRENT_DEFERRED_WORK=
PRESERVED_WITHOUT_PRIORITY_PROMOTION

CURRENT_RUNTIME_SUCCESSOR_CAPABILITY=
NONE_ESTABLISHED

SUCCESSOR_PRIORITY=
NONE_ESTABLISHED

NEXT_RUNTIME_IMPLEMENTATION_MILESTONE=
NOT_ESTABLISHED

NEW_IMPLEMENTATION_REQUIRED=
NO

PROGRAM_RECONCILIATION_MILESTONE_CLOSURE_READINESS=
REQUIRES_PROGRAM_LEVEL_DISPOSITION_CLASSIFICATION

SUCCESSOR_DECISION_BOUNDARY=
DO_NOT_INVENT_OR_PROMOTE_A_RUNTIME_SUCCESSOR_WITHOUT_NEW_EVIDENCE

PERMITTED_NEXT_DECISION_CLASSES=
CLOSE_PROGRAM_RECONCILIATION_WITH_NO_RUNTIME_SUCCESSOR_ESTABLISHED
OR
ESTABLISH_A_NEW_INVESTIGATION_MILESTONE_ONLY_IF_CURRENT_REPOSITORY_EVIDENCE_SUPPORTS_A_DISTINCT_UNRESOLVED_PROGRAM_QUESTION

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

PHASE_1_STATUS=
COMPLETE

NEXT_PHASE=
PROGRAM_RECONCILIATION_CLOSURE_AND_SUCCESSOR_DISPOSITION

NEXT_CORRIDOR=
PROGRAM_RECONCILIATION_CLOSURE_READINESS

NEXT_ACTION=
CLASSIFY_PROGRAM_RECONCILIATION_MILESTONE_CLOSURE_READINESS
MAP
