#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY CORRIDOR 3: FAILURE OWNERSHIP ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 062bbfca HEAD
test -z "$(git status --porcelain)"

source_file="scripts/enter-failure-ownership-corridor.sh"
test -f "$source_file"

grep -q '^MODEL_GENERATION_LAYER_INVOLVEMENT=$' "$source_file"
grep -q '^ESTABLISHED$' <(awk '/MODEL_GENERATION_LAYER_INVOLVEMENT=/{getline; print}' "$source_file")

grep -q '^VALIDATOR_MALFUNCTION_ESTABLISHED=$' "$source_file"
grep -q '^NO$' <(awk '/VALIDATOR_MALFUNCTION_ESTABLISHED=/{getline; print}' "$source_file")

grep -q '^CONTEXT_RUNTIME_MALFUNCTION_ESTABLISHED=$' "$source_file"
grep -q '^NO$' <(awk '/CONTEXT_RUNTIME_MALFUNCTION_ESTABLISHED=/{getline; print}' "$source_file")

grep -q '^IEL_MALFUNCTION_ESTABLISHED=$' "$source_file"
grep -q '^NO$' <(awk '/IEL_MALFUNCTION_ESTABLISHED=/{getline; print}' "$source_file")

grep -q '^ONE_INVOCATION_ARCHITECTURE_MALFUNCTION_ESTABLISHED=$' "$source_file"
grep -q '^NO$' <(awk '/ONE_INVOCATION_ARCHITECTURE_MALFUNCTION_ESTABLISHED=/{getline; print}' "$source_file")

cat <<'MAP'
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

CORRIDOR_3=
FAILURE_OWNERSHIP

ESTABLISHED_FAILURE=
INVALID_MODEL_AUTHORED_PROJECT_CONTEXT_SUPPORT_PROVENANCE

PRIMARY_FAILURE_OWNER_CLASS=
MODEL_GENERATION_LAYER

PRIMARY_FAILURE_OWNER_CLASSIFICATION=
ESTABLISHED

VALIDATOR_OWNERSHIP=
NOT_ESTABLISHED

CONTEXT_RUNTIME_OWNERSHIP=
NOT_ESTABLISHED

IEL_OWNERSHIP=
NOT_ESTABLISHED

ONE_INVOCATION_ARCHITECTURE_OWNERSHIP=
NOT_ESTABLISHED

EXACT_MODEL_GENERATION_SUBCAUSE=
UNRESOLVED

SUBCAUSE_RESOLUTION_REQUIRED_FOR_CORRIDOR_CLOSURE=
NO

FAILURE_OWNERSHIP_CLASSIFICATION=
COMPLETE

NEW_PRODUCTION_CHANGE=
NONE

IMPLEMENTATION_AUTHORIZED=
NO_NEW_IMPLEMENTATION

CORRIDOR_3_STATUS=
READY_FOR_CLOSURE

DR_REQUIRED_BEFORE_NEXT_CORRIDOR=
YES

NEXT_ACTION=
STOP_FOR_CORRIDOR_3_DR_CHECKPOINT
MAP
