#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY CURRENT SEMANTIC HISTORY CONTEXT OPTIMIZATION SCOPE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor d3e2a0fc HEAD

echo "=== VERIFY CURRENT RECONCILIATION ==="
current="scripts/reconcile-current-semantic-history-context-optimization-state.sh"
test -f "$current"
grep -q 'CURRENT_STATE_RECONCILIATION=' "$current"
grep -q 'COMPLETE' "$current"
grep -q 'CURRENT_SEMANTIC_RANKING=' "$current"
grep -q 'NOT_IMPLEMENTED' "$current"
grep -q 'CURRENT_REPOSITORY_CONTROLLED_POST_RETRIEVAL_TOKEN_BUDGET=' "$current"
grep -q 'CURRENT_HYBRID_CONTEXT_OPTIMIZATION=' "$current"
grep -q 'CURRENT_MODEL_RUNTIME_CONTEXT_OPTIMIZATION=' "$current"
grep -q 'CURRENT_BOUNDED_HISTORY_WINDOW_OPTIMIZATION=' "$current"
echo "CURRENT_RECONCILIATION=CONFIRMED"

echo
echo "=== VERIFY EXISTING SCOPE SEMANTICS ==="
legacy="scripts/classify-semantic-history-context-optimization-scope.sh"
test -f "$legacy"

grep -q 'OPTIMIZATION_SCOPE=' "$legacy"
grep -q 'SEMANTIC_HISTORY_RANKING' "$legacy"
grep -q 'TOKEN_BUDGET_BEHAVIOR' "$legacy"
grep -q 'HYBRID_CONTEXT_RELATIONSHIP' "$legacy"
grep -q 'MODEL_RUNTIME_CONTEXT_BOUNDARY' "$legacy"
grep -q 'BOUNDED_HISTORY_WINDOW_OPTIMIZATION' "$legacy"
grep -q 'SCOPE_ORDERING_PRINCIPLE=' "$legacy"
grep -q 'CLASSIFY_REQUIREMENT_AND_OWNERSHIP_BEFORE_DESIGN_OR_IMPLEMENTATION' "$legacy"

echo "EXISTING_SCOPE_SEMANTICS=CONFIRMED"

cat <<'MAP'
MILESTONE=
SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION

MILESTONE_STATUS=
ACTIVE_SCOPE_CLASSIFICATION

EXISTING_FOUNDATION=
PRESERVE

OPTIMIZATION_SCOPE=
SEMANTIC_HISTORY_RANKING
TOKEN_BUDGET_BEHAVIOR
HYBRID_CONTEXT_RELATIONSHIP
MODEL_RUNTIME_CONTEXT_BOUNDARY
BOUNDED_HISTORY_WINDOW_OPTIMIZATION

SEMANTIC_HISTORY_RANKING_STATUS=
INVESTIGATION_REQUIRED

TOKEN_BUDGET_STATUS=
INVESTIGATION_REQUIRED

HYBRID_CONTEXT_STATUS=
INVESTIGATION_REQUIRED

MODEL_RUNTIME_CONTEXT_STATUS=
INVESTIGATION_REQUIRED

BOUNDED_HISTORY_WINDOW_STATUS=
INVESTIGATION_REQUIRED

SCOPE_ORDERING_PRINCIPLE=
CLASSIFY_REQUIREMENT_AND_OWNERSHIP_BEFORE_DESIGN_OR_IMPLEMENTATION

RANKING_IMPLEMENTATION=
NOT_AUTHORIZED

TOKEN_BUDGET_IMPLEMENTATION=
NOT_AUTHORIZED

HYBRID_CONTEXT_IMPLEMENTATION=
NOT_AUTHORIZED

MODEL_RUNTIME_CONTEXT_IMPLEMENTATION=
NOT_AUTHORIZED

HISTORY_WINDOW_CHANGE=
NOT_AUTHORIZED

PROJECT_CONTEXT_RETRIEVAL_CONVERGENCE=
NOT_AUTHORIZED

SELECTED_HISTORY_CONTRACT_CHANGE=
NOT_AUTHORIZED

AUTHORITY_BOUNDARY_CHANGE=
NOT_AUTHORIZED

CONTAMINATION_BOUNDARY_CHANGE=
NOT_AUTHORIZED

PROMPT_CHANGE=
NOT_AUTHORIZED

OLLAMA_INVOCATION_COUNT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CONCERN=
SEPARATE_AND_DEFERRED

PRODUCTION_GENERATION_POLICY=
UNCHANGED

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

SCOPE_CLASSIFICATION=
COMPLETE

NEXT_ACTION=
DISCOVER_SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION_PHASE_AND_CORRIDOR_MAP
MAP
