#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY EXPERIMENTAL PRESENTATION PRODUCTION PROMOTION IMPLEMENTATION READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 37f67d46 HEAD
test -z "$(git status --porcelain)"

boundary="scripts/classify-experimental-presentation-production-regression-validation-boundary.sh"
ollama="scripts/utils/ollamaChat.ts"

for file in "$boundary" "$ollama"; do
  test -f "$file"
done

grep -q 'PRODUCTION_REMEDY_READINESS=' "$boundary"
grep -q '^READY_FOR_IMPLEMENTATION_READINESS_CLASSIFICATION$' \
  <(awk '/PRODUCTION_REMEDY_READINESS=/{getline; print}' "$boundary")

grep -q 'PRODUCTION_PROMPT_PROMOTION=' "$boundary"
grep -q '^POTENTIALLY_JUSTIFIED_BY_CURRENT_EVIDENCE_BUT_NOT_YET_AUTHORIZED$' \
  <(awk '/PRODUCTION_PROMPT_PROMOTION=/{getline; print}' "$boundary")

grep -q 'validationPromptPresentationVariant' "$ollama"
grep -q 'explicit_parent_child_separation' "$ollama"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

READINESS_UNIT=
EXPERIMENTAL_PRESENTATION_PRODUCTION_PROMOTION_IMPLEMENTATION_READINESS

INTERVENTION_CANDIDATE=
EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION

FIXED_SEED_DIAGNOSTIC_EVIDENCE=
CONTROL_0_OF_10_EXPERIMENTAL_10_OF_10

UNSEEDED_EXPERIMENTAL_EVIDENCE=
10_OF_10_SEMANTIC_PASS
0_OF_10_UNSUPPLIED_SUPPORT_FAILURE
0_OF_10_FAIL_CLOSED_OR_RUNTIME_REJECTION

OUTPUT_VARIANCE=
9_UNIQUE_FINGERPRINTS_WITH_SEMANTIC_RELIABILITY_PRESERVED

PRODUCTION_PROMOTION_SCOPE=
MAKE_EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION_THE_DEFAULT_PROMPT_PRESENTATION

AUTHORIZED_IMPLEMENTATION_SURFACE=
scripts/utils/ollamaChat.ts

EXPECTED_CHANGE_CLASS=
PROMPT_PRESENTATION_STRUCTURE_ONLY

SEMANTIC_CONTRACT_CHANGE=
NONE

STRUCTURED_RESPONSE_SCHEMA_CHANGE=
NONE

SUPPORT_PROVENANCE_RULE_CHANGE=
NONE

SELECTED_CONTEXT_SEGMENT_RULE_CHANGE=
NONE

FAIL_CLOSED_VALIDATOR_CHANGE=
NONE

MODEL_CHANGE=
NONE

GENERATION_POLICY_CHANGE=
NONE

RETRY_OR_SECOND_MODEL_CALL=
NONE

ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=
PRESERVED

REPLY_AND_DURABLE_INTERPRETATION_SEPARATION=
PRESERVED

IEL_PERSISTENCE_BOUNDARY=
PRESERVED

CONVERSATION_CONTEXT_BOUNDARY=
PRESERVED

PRIOR_INVESTIGATION_LIFECYCLE_BOUNDARY=
PRESERVED

LIVING_DRAFT_DERIVATION_BOUNDARY=
PRESERVED

APPROVAL_PIPELINE_AUTHORITY_BOUNDARY=
PRESERVED

IMPLEMENTATION_STRATEGY=
PROMOTE_EXISTING_VALIDATED_PRESENTATION_STRUCTURE_WITHOUT_ALTERING_SEMANTICS_OR_PROVENANCE_IDENTITIES

ROLLBACK_BOUNDARY=
RESTORE_CURRENT_DEFAULT_PRESENTATION_PATH_WHILE_RETAINING_VALIDATION_EVIDENCE_AND_DIAGNOSTIC_RUNNERS

POST_IMPLEMENTATION_REQUIRED_VALIDATION=
TARGETED_TYPESCRIPT_VALIDATION
DETERMINISTIC_EXISTING_REGRESSION_SUITE
PRODUCTION_BEHAVIORAL_UNSEEDED_SAMPLE

PRODUCTION_PROMOTION_IMPLEMENTATION_READINESS=
READY

PRODUCTION_PROMPT_CHANGE=
NOT_YET_AUTHORIZED

PRODUCTION_REMEDY_AUTHORIZATION_REQUIRED=
YES

PRODUCTION_CHANGE=
NONE

CORRIDOR_1_STATUS=
ACTIVE

NEXT_ACTION=
AUTHORIZE_EXPERIMENTAL_PRESENTATION_PRODUCTION_PROMOTION

IMPLEMENTATION_AUTHORIZED=
NO
MAP
