#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY RELIABLE PRODUCTION COLLABORATION INTERVENTION BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 254f202b HEAD

constraints="scripts/classify-reliable-production-collaboration-constraint-preservation.sh"
ownership="scripts/investigate-production-collaboration-failure-ownership.sh"
baseline="scripts/reconcile-current-production-failure-baseline.sh"
causal="scripts/classify-failure-repeatability-and-causal-boundary.sh"

for artifact in "$constraints" "$ownership" "$baseline" "$causal"; do
  test -f "$artifact"
  echo "PRESENT=$artifact"
done

echo
echo "=== VERIFY CORRIDOR 4 CLOSURE ==="
grep -q 'CORRIDOR_4_STATUS=' "$constraints"
grep -q '^COMPLETE$' <(awk '/CORRIDOR_4_STATUS=/{getline; print}' "$constraints")
grep -q 'NEXT_CORRIDOR=' "$constraints"
grep -q '^INTERVENTION_BOUNDARY$' <(awk '/NEXT_CORRIDOR=/{getline; print}' "$constraints")
echo "CORRIDOR_4_CLOSURE=CONFIRMED"

echo
echo "=== VERIFY FAILURE OWNERSHIP ==="
grep -q 'PRIMARY_FAILURE_OWNER_CLASS=' "$ownership"
grep -q '^MODEL_GENERATION_LAYER$' <(awk '/PRIMARY_FAILURE_OWNER_CLASS=/{getline; print}' "$ownership")
grep -q 'PRECISE_MODEL_INTERNAL_ROOT_CAUSE=' "$ownership"
grep -q '^NOT_ESTABLISHED$' <(awk '/PRECISE_MODEL_INTERNAL_ROOT_CAUSE=/{getline; print}' "$ownership")
echo "FAILURE_OWNERSHIP=CONFIRMED"

echo
echo "=== VERIFY GENERATION CONTROL SENSITIVITY WITHOUT REMEDY ==="
grep -q 'GENERATION_LAYER_SENSITIVITY_ESTABLISHED' "$causal"
grep -q 'FIXED_SEED_AS_ROOT_CAUSE=' "$causal"
grep -q 'FIXED_SEED_AS_PRODUCTION_REMEDY=' "$causal"
grep -q 'NOT_ESTABLISHED' "$causal"
echo "GENERATION_CONTROL_SENSITIVITY=CONFIRMED"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_1=
STARTING_BOUNDARY_AND_RELIABILITY_BASELINE

CORRIDOR_5=
INTERVENTION_BOUNDARY

CORRIDOR_PURPOSE=
DETERMINE_WHICH_GENERATION_LAYER_INTERVENTION_CLASSES_ARE_EVIDENCE_SUPPORTED_FOR_FURTHER_INVESTIGATION_WITHOUT_PREMATURELY_SELECTING_A_REMEDY

CURRENT_FAILURE_OWNER=
MODEL_GENERATION_LAYER

EXACT_GENERATION_SUBCAUSE=
NOT_ESTABLISHED

EVIDENCE_SUPPORTED_INTERVENTION_CLASS_1=
PROMPT_OR_RESPONSE_CONTRACT_PRESENTATION

RATIONALE_1=
THE_FAILURE_IS_MODEL_AUTHORED_SEMANTIC_OR_PROVENANCE_OUTPUT_AND_PROMPT_PRESENTATION_IS_UPSTREAM_OF_DETERMINISTIC_ACCEPTANCE

EVIDENCE_SUPPORTED_INTERVENTION_CLASS_2=
GENERATION_CONTROL_OR_SAMPLING_POLICY

RATIONALE_2=
GENERATION_LAYER_CONTROL_STATE_SENSITIVITY_IS_ESTABLISHED_BUT_NO_SPECIFIC_PRODUCTION_POLICY_IS_YET_JUSTIFIED

EVIDENCE_SUPPORTED_INTERVENTION_CLASS_3=
MODEL_CAPABILITY

RATIONALE_3=
MODEL_GENERATION_OWNS_THE_FAILURE_SURFACE_AND_CURRENT_EVIDENCE_DOES_NOT_ESTABLISH_THAT_THE_EXISTING_MODEL_CAN_RELIABLY_SATISFY_THE_SEMANTIC_CONTRACT

EVIDENCE_SUPPORTED_INTERVENTION_CLASS_4=
OTHER_BOUNDED_GENERATION_INPUT_CONDITIONS

RATIONALE_4=
THE_EXACT_GENERATION_SUBCAUSE_REMAINS_UNRESOLVED_AND_MAY_INVOLVE_A_BOUNDED_INPUT_CONDITION_NOT_YET_ISOLATED

INTERVENTION_CLASSES_NOT_YET_SUPPORTED_AS_IMPLEMENTATION=
PROMPT_CHANGE
PRODUCTION_FIXED_SEED
TEMPERATURE_CHANGE
TOP_P_CHANGE
TOP_K_CHANGE
MODEL_REPLACEMENT
AUTOMATIC_RETRY
SECOND_MODEL_INVOCATION
VALIDATOR_CHANGE

FIXED_SEED_AS_ROOT_CAUSE=
NOT_ESTABLISHED

FIXED_SEED_AS_PRODUCTION_REMEDY=
NOT_ESTABLISHED

PROMPT_AS_ROOT_CAUSE=
NOT_ESTABLISHED

MODEL_CAPABILITY_AS_ROOT_CAUSE=
NOT_ESTABLISHED

SAMPLING_POLICY_AS_ROOT_CAUSE=
NOT_ESTABLISHED

PREFERRED_NEXT_INVESTIGATION_ORDER=
PROMPT_OR_RESPONSE_CONTRACT_PRESENTATION
GENERATION_CONTROL_OR_SAMPLING_POLICY
MODEL_CAPABILITY
OTHER_BOUNDED_GENERATION_INPUT_CONDITIONS

ORDER_RATIONALE=
INVESTIGATE_THE_LOWEST_SCOPE_GENERATION_LAYER_SURFACES_FIRST_WHILE_PRESERVING_EXISTING_ARCHITECTURAL_AND_SEMANTIC_GUARDS

INTERVENTION_BOUNDARY_CLASSIFICATION=
MULTIPLE_GENERATION_LAYER_INTERVENTION_CLASSES_ARE_EVIDENCE_SUPPORTED_FOR_INVESTIGATION_BUT_NO_IMPLEMENTATION_REMEDY_IS_YET_ESTABLISHED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

VALIDATOR_WEAKENING=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

PROMPT_CHANGE=
NOT_AUTHORIZED

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

CORRIDOR_5_STATUS=
COMPLETE

PHASE_1_STATUS=
COMPLETE

PHASE_1_RESULT=
RELIABILITY_TARGET_BASELINE_FAILURE_OWNERSHIP_CONSTRAINTS_AND_INTERVENTION_BOUNDARY_ESTABLISHED_WITHOUT_SELECTING_A_PRODUCTION_REMEDY

NEXT_PHASE=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

NEXT_CORRIDOR=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

NEXT_ACTION=
OPEN_GENERATION_LAYER_INTERVENTION_INVESTIGATION_STARTING_BOUNDARY
MAP
