#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PROGRAM RECONCILIATION MILESTONE CLOSURE READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor c9feaec6 HEAD

phase1="scripts/classify-program-reconciliation-phase-1-disposition-and-successor-decision-boundary.sh"
test -f "$phase1"

echo "=== VERIFY PHASE 1 DISPOSITION ==="
grep -q 'PHASE_1_STATUS=' "$phase1"
grep -q 'COMPLETE' "$phase1"
grep -q 'PHASE_1_RESULT=' "$phase1"
grep -q 'COMPLETE_WITH_ZERO_CURRENT_EVIDENCE_SUPPORTED_UNRESOLVED_CAPABILITY_GAPS' "$phase1"
grep -q 'CURRENT_RUNTIME_SUCCESSOR_CAPABILITY=' "$phase1"
grep -q 'NONE_ESTABLISHED' "$phase1"
grep -q 'NEXT_RUNTIME_IMPLEMENTATION_MILESTONE=' "$phase1"
grep -q 'NOT_ESTABLISHED' "$phase1"
grep -q 'NEW_IMPLEMENTATION_REQUIRED=' "$phase1"
grep -q '^NO$' <(awk '/NEW_IMPLEMENTATION_REQUIRED=/{getline; print}' "$phase1")
echo "PHASE_1_DISPOSITION=CONFIRMED"

echo
echo "=== VERIFY CURRENT COMPLETED CORRIDORS ==="

for artifact in \
  scripts/reconcile-current-completed-runtime-capability-inventory.sh \
  scripts/reconcile-current-deferred-work-inventory.sh \
  scripts/reconcile-current-unresolved-capability-gaps.sh \
  scripts/reconcile-current-successor-priority-boundary.sh
do
  test -f "$artifact"
  echo "PRESENT=$artifact"
done

grep -q 'CORRIDOR_1_STATUS=' scripts/reconcile-current-completed-runtime-capability-inventory.sh
grep -q 'CORRIDOR_2_STATUS=' scripts/reconcile-current-deferred-work-inventory.sh
grep -q 'CORRIDOR_3_STATUS=' scripts/reconcile-current-unresolved-capability-gaps.sh
grep -q 'PRIORITY_BOUNDARY_STATUS=' scripts/reconcile-current-successor-priority-boundary.sh

echo "ALL_PHASE_1_CORRIDORS=COMPLETE"

echo
echo "=== CHECK FOR EXISTING CLOSURE / SUCCESSOR EVIDENCE ==="

grep -RniE \
  --exclude-dir=node_modules \
  --exclude-dir=.git \
  'PROGRAM_RECONCILIATION.*(CLOSE|CLOSED|CLOSURE)|CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION.*(CLOSE|CLOSED)|NO_EVIDENCE_SUPPORTED_RUNTIME_SUCCESSOR|SUCCESSOR_MILESTONE=.*NOT_YET_ESTABLISHED' \
  scripts docs 2>/dev/null | head -220 || true

echo
echo "=== MILESTONE CLOSURE READINESS CLASSIFICATION ==="

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION

MILESTONE_CLASS=
INVESTIGATION_AND_PROGRAM_BOUNDARY_CLASSIFICATION

PHASE_1=
CURRENT_CAPABILITY_AND_DEFERRED_WORK_RECONCILIATION

PHASE_1_STATUS=
COMPLETE

PHASE_1_RESULT=
COMPLETE_WITH_ZERO_CURRENT_EVIDENCE_SUPPORTED_UNRESOLVED_CAPABILITY_GAPS

COMPLETED_RUNTIME_CAPABILITY_INVENTORY=
COMPLETE_AND_CURRENT

DEFERRED_WORK_INVENTORY=
COMPLETE_AND_CURRENT

UNRESOLVED_CAPABILITY_GAP_CLASSIFICATION=
COMPLETE_WITH_ZERO_CURRENT_INVENTORIED_GAPS

SUCCESSOR_PRIORITY_BOUNDARY=
COMPLETE_WITH_NO_EVIDENCE_SUPPORTED_RUNTIME_SUCCESSOR_ESTABLISHED

CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION=
IMPLEMENTED_AND_VALIDATED

SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION=
CLOSED

GENERATION_STABILITY=
CLOSED

PRODUCTION_GENERATION_INSTABILITY=
PRESERVED_AS_KNOWN_DEFERRED_CONDITION

PRODUCTION_RUNTIME_REGRESSION=
NOT_ESTABLISHED

CURRENT_DEFERRED_WORK=
PRESERVED_WITHOUT_PRIORITY_PROMOTION

NEW_RUNTIME_CAPABILITY_REQUIREMENT=
NONE_ESTABLISHED

NEW_RUNTIME_IMPLEMENTATION_MILESTONE=
NONE_ESTABLISHED

MILESTONE_PURPOSE_SATISFIED=
YES

MILESTONE_CAN_CLOSE=
YES

CLOSURE_DOES_NOT_MEAN=
ALL_FUTURE_WORK_COMPLETE
PRODUCTION_GENERATION_STABILITY_ESTABLISHED
DEFERRED_CONDITIONS_RESOLVED

CLOSURE_MEANS=
CURRENT_CAPABILITIES_RECONCILED
CURRENT_DEFERRED_WORK_RECONCILED
CURRENT_UNRESOLVED_GAPS_RECONCILED
CURRENT_SUCCESSOR_PRIORITY_RECONCILED
NO_EVIDENCE_SUPPORTED_RUNTIME_SUCCESSOR_CURRENTLY_ESTABLISHED

SUCCESSOR_DECISION_BOUNDARY=
REQUIRE_NEW_EVIDENCE_OR_EXPLICIT_NEW_PROGRAM_OBJECTIVE_BEFORE_OPENING_ANOTHER_RUNTIME_MILESTONE

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_GENERATION_POLICY_REOPENED=
NO

PRODUCTION_CHANGE=
NONE

PROGRAM_RECONCILIATION_MILESTONE_CLOSURE_READINESS=
READY

NEXT_ACTION=
CLOSE_CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION_MILESTONE
MAP
