#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=EXECUTIVE_MISSION_OVERVIEW' \
  'CORRIDOR=PIPELINE_POSITION' \
  'AUTHORITATIVE_GOVERNANCE_PIPELINE_STATE=PARTIAL' \
  'LIVE_MAIN_DB_DELEGATION_STATE=AVAILABLE' \
  'LIVE_MAIN_DB_VALIDATION_STATE=AVAILABLE' \
  'LIVE_MAIN_DB_ENVELOPE_GATE_STATE=AVAILABLE' \
  'LIVE_MAIN_DB_ENVELOPE_LIFECYCLE_STATE=AVAILABLE' \
  'LIVE_MAIN_DB_OPERATIONAL_INTAKE_STATE=NOT_AVAILABLE' \
  'DEPARTMENT_LEVEL_PIPELINE_POSITION=NOT_ESTABLISHED_ON_MISSION_READ_PERSISTENCE_SURFACE' \
  'MISSION_PIPELINE_PRESENTATION_CONTRACT=ORGANIZATIONAL_MOVEMENT_ONLY_WHEN_AUTHORITATIVE' \
  'MISSION_PROGRESS_AND_PIPELINE=MUST_REMAIN_DISTINCT' \
  'NEW_SEMANTIC_AUTHORITY_REQUIRED=NO' \
  'PIPELINE_PROJECTION_BOUNDARY=GOVERNANCE_MOVEMENT_ONLY_UNTIL_OPERATIONAL_INTAKE_IS_AUTHORITATIVE' \
  'RENDERER_MAY_NOT_INFER_DEPARTMENT_OR_AGENT_POSITION=YES' \
  'GAP_CLASS=LIVE_PERSISTENCE_AND_READ_PROJECTION_COVERAGE' \
  'CORRIDOR_3_CLASSIFICATION=PARTIAL_PIPELINE_AUTHORITY_CONFIRMED' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'NEXT_CORRIDOR=EXECUTIVE_OVERVIEW_VALIDATION_AND_CLOSURE'
