#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — DEFERRED DISPOSITION CLASSIFICATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 15763f02 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-2-deferred-disposition\.sh$|^ M scripts/classify-phase-3-corridor-2-deferred-disposition\.sh$' ||
  true
)"
test -z "$unexpected"

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION

SCHEMA_AND_PROMPT_CONTRACT=
ESTABLISHED

MODEL_BEHAVIORAL_RELIABILITY=
NOT_ESTABLISHED

REASON=
CROSS_CUTTING_SELECTED_CONTEXT_GENERATION_BLOCK_PREVENTS_CLEAN_OBSERVATION_OF_REASONING_STATUS_BEHAVIOR

REASONING_STATUS_DEFECT_ESTABLISHED=
NO

VALIDATOR_MALFUNCTION_ESTABLISHED=
NO

FAIL_CLOSED_VALIDATION=
PRESERVED

THREE_FAILED_MODEL_ATTEMPTS=
REACHED

FURTHER_MODEL_ATTEMPT=
NOT_AUTHORIZED

CORRIDOR_2_DISPOSITION=
DEFERRED_WITH_EXPLICIT_UNRESOLVED_BEHAVIORAL_RELIABILITY_LIMIT

CORRIDOR_2_CLOSED_AS_FULLY_VALIDATED=
NO

PHASE_3_CAN_CONTINUE_TO_CORRIDOR_3=
YES

CONTINUATION_BASIS=
CORRIDOR_3_CAN_CLASSIFY_THE_SURFACING_CONTRACT_FROM_THE_ESTABLISHED_REASONING_STATUS_SCHEMA_AND_CLASSIFICATION_SEMANTICS_WITHOUT_CLAIMING_MODEL_BEHAVIORAL_RELIABILITY

REQUIRED_CARRY_FORWARD_LIMIT=
DO_NOT_REPRESENT_OPTIONAL_OR_RECOMMENDED_AS_PRODUCTION_RELIABLE_UNTIL_BEHAVIORAL_VALIDATION_IS_UNBLOCKED_AND_COMPLETED

CORRIDOR_3=
SURFACING_CONTRACT

CORRIDOR_3_IMPLEMENTATION_AUTHORIZED=
NO

PRODUCTION_CHANGE=
NONE

DR_NOW=
NO

NEXT_ACTION=
ENTER_CORRIDOR_3_IN_COLLABORATION_MODE_AND_CLASSIFY_HOW_OPTIONAL_VERSUS_RECOMMENDED_SHOULD_SURFACE_WHILE_PRESERVING_THE_DEFERRED_RELIABILITY_LIMIT
MAP
