#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — SELECTED CONTEXT REJECTION CAUSE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 38a22c39 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-phase-3-corridor-2-selected-context-rejection-cause\.sh$|^ M scripts/classify-phase-3-corridor-2-selected-context-rejection-cause\.sh$' ||
  true
)"
test -z "$unexpected"

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION
STATUS=ACTIVE

DIAGNOSTIC_COMMIT=38a22c39

SUPPLIED_IDENTITY=
docs/reasoning-status-behavior-validation.md:20:20

MODEL_AUTHORED_IDENTITY=
docs/reasoning-status_behavior_validation.md:20:20

IDENTITY_DIFFERENCE=
RELATIVE_PATH_ONLY

MODEL_MUTATION=
HYPHENS_REPLACED_WITH_UNDERSCORES_IN_BEHAVIOR_VALIDATION_PORTION

SOURCE_LINE_IDENTITY=
MATCH

FAIL_CLOSED_REJECTION_CAUSE=
MODEL_AUTHORED_RELATIVE_PATH_DID_NOT_EXACTLY_MATCH_SUPPLIED_CANDIDATE_IDENTITY

FIXTURE_SHAPE_FAILURE=
NOT_ESTABLISHED

CLASSIFICATION_RULE_FAILURE=
NOT_ESTABLISHED

VALIDATOR_MALFUNCTION=
NOT_ESTABLISHED

FAIL_CLOSED_VALIDATOR_BEHAVIOR=
CORRECT_BY_CURRENT_CONTRACT

FAILED_BEHAVIOR_VALIDATION_ATTEMPTS=2
THIRD_BEHAVIOR_VALIDATION_ATTEMPT=NOT_STARTED

NEXT_HYPOTHESIS=
REMOVE_PROJECT_CONTEXT_FROM_REASONING_STATUS_BEHAVIOR_VALIDATION_SO_SELECTED_CONTEXT_PROVENANCE_IS_NOT_INVOLVED_IN_THE_CLASSIFIER_TEST

RATIONALE=
THE_CLASSIFIER_CASES_TEST_EXPLANATION_STATUS_SEMANTICS_AND_DO_NOT_REQUIRE_PROJECT_CONTEXT_TO_ESTABLISH_OPTIONAL_OR_RECOMMENDED_SELECTION

PRODUCTION_CHANGE=NONE
DR_NOW=NO
NEXT_ACTION=BUILD_CONTEXT_FREE_BOUNDED_BEHAVIOR_VALIDATION_ATTEMPT_3
MAP
