#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=39658257' \
  'ISSUE_RESOLVED=NO' \
  'UNSEEDED_ARM_COMPLETE=YES' \
  'CONTROLLED_ARM_COMPLETE=UNKNOWN' \
  'PROCESS_STATE_CLASSIFICATION=ACTIVE_LONG_RUNNING_COMPARISON_PROCESS_PRESENT'

printf '\n=== VERIFIED ACTIVE PROCESS ===\n'
ps -p 71361,71372,71378 -o pid=,ppid=,etime=,stat=,command= || true

printf '\n=== OLLAMA PROCESS ===\n'
ps -p 801,71392 -o pid=,ppid=,etime=,stat=,command= || true

printf '\n=== CLASSIFICATION ===\n'
printf '%s\n' \
  'COMPARISON_PROCESS_PRESENT=YES' \
  'COMPARISON_PROCESS_ELAPSED_TIME_EXCEEDS_NINE_MINUTES=YES' \
  'CONTROLLED_ARM_PROGRESS_EVIDENCE=NOT_ESTABLISHED_FROM_PROCESS_TABLE' \
  'PROCESS_TERMINATION_AUTHORIZED=NO' \
  'NEW_EXPERIMENT_AUTHORIZED=NO' \
  'PRODUCTION_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_CHANGE_AUTHORIZED=NO' \
  'NEXT_ACTION=INSPECT_ACTIVE_PROCESS_OUTPUT_OR_FILE_DESCRIPTORS_BEFORE_DECIDING_RECOVERY'

printf '\n=== RUNNER WORKTREE STATE ===\n'
git status --short -- scripts/run-dashboard-generation-control-comparison.ts
