#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=EXECUTIVE_MISSION_OVERVIEW' \
  'CORRIDOR=MISSION_STATE_PROJECTION' \
  'AUTHORITATIVE_GOVERNANCE_STATE=EXISTS' \
  'MISSION_READ_STATE_PROJECTION=PARTIAL' \
  'MISSION_READ_STAGE_IMPLEMENTED=ENVELOPE_CREATED_AND_ASSIGNED_ONLY' \
  'MISSION_READ_STAGE_CONTRACT_BROADER_THAN_IMPLEMENTATION=YES' \
  'MISSION_READ_OWNER_PROJECTION=PARTIAL_GENERIC_DEPARTMENT_ONLY' \
  'AUTHORITATIVE_ASSIGNMENT_SOURCES=EXIST_BUT_NOT_PROJECTED' \
  'MISSION_READ_AWAITING_PROJECTION=UNIMPLEMENTED_NULL_ONLY' \
  'AUTHORITATIVE_DELEGATION_VALIDATION_GATE_STATE=EXISTS_BUT_NOT_PROJECTED' \
  'MISSION_READ_HEALTH_PROJECTION=INTEGRITY_WARNINGS_ONLY' \
  'NEW_SEMANTIC_AUTHORITY_REQUIRED=NO' \
  'NEW_PERSISTENCE_REQUIRED=NO' \
  'GAP_CLASS=AUTHORITATIVE_STATE_READ_AND_PROJECTION_COVERAGE' \
  'RENDERER_SEMANTIC_AUTHORITY=NOT_ALLOWED' \
  'CORRIDOR_2_CLASSIFICATION=PARTIAL_PROJECTION_CONFIRMED' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'NEXT_CORRIDOR=PIPELINE_POSITION'
