#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PROMPT PRESENTATION PRODUCTION REMEDY READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor b53d1648 HEAD
test -z "$(git status --porcelain)"

results="scripts/classify-prompt-presentation-diagnostic-results.sh"
test -f "$results"

grep -q 'PROMPT_PRESENTATION_STRUCTURE_AS_CONTRIBUTING_FACTOR=' "$results"
grep -q '^STRONGLY_SUPPORTED_ON_TESTED_DIAGNOSTIC_SURFACE$' \
  <(awk '/PROMPT_PRESENTATION_STRUCTURE_AS_CONTRIBUTING_FACTOR=/{getline; print}' "$results")

grep -q 'PRODUCTION_REMEDY=' "$results"
grep -q '^NOT_YET_ESTABLISHED$' \
  <(awk '/PRODUCTION_REMEDY=/{getline; print}' "$results")

grep -q 'PRODUCTION_PROMPT_CHANGE=' "$results"
grep -q '^NOT_AUTHORIZED$' \
  <(awk '/PRODUCTION_PROMPT_CHANGE=/{getline; print}' "$results")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

READINESS_UNIT=
PROMPT_PRESENTATION_PRODUCTION_REMEDY_READINESS

DIAGNOSTIC_EVIDENCE_STRENGTH=
STRONG

CONTROL_BEHAVIOR=
0_OF_10_SEMANTIC_PASS
10_OF_10_UNSUPPLIED_SUPPORT_FAILURE

EXPERIMENTAL_BEHAVIOR=
10_OF_10_SEMANTIC_PASS
0_OF_10_UNSUPPLIED_SUPPORT_FAILURE

PROMPT_PRESENTATION_STRUCTURE_AS_CONTRIBUTING_FACTOR=
STRONGLY_SUPPORTED_ON_TESTED_FIXED_SEED_DIAGNOSTIC_SURFACE

PRODUCTION_EQUIVALENT_UNSEEDED_VALIDATION_OF_EXPERIMENTAL_PRESENTATION=
NOT_YET_PERFORMED

PRODUCTION_SURFACE_REGRESSION_VALIDATION=
NOT_YET_PERFORMED

DEFAULT_PRODUCTION_PROMPT_REPLACEMENT=
NOT_YET_JUSTIFIED

PRODUCTION_REMEDY_READINESS=
NOT_READY

REASON=
FIXED_SEED_DIAGNOSTIC_EVIDENCE_SUPPORTS_PRESENTATION_CAUSAL_CONTRIBUTION_BUT_DOES_NOT_ESTABLISH_RELIABILITY_ON_ORDINARY_UNSEEDED_PRODUCTION_EQUIVALENT_GENERATION

NEXT_REQUIRED_EVIDENCE=
BOUNDED_UNSEEDED_VALIDATION_OF_THE_EXPERIMENTAL_PRESENTATION_WITH_IDENTICAL_SEMANTIC_AND_PROVENANCE_CONTRACTS

NEXT_VALIDATION_CLASS=
NON_PRODUCTION_PRODUCTION_EQUIVALENT_UNSEEDED_PRESENTATION_VALIDATION

FAIL_CLOSED_VALIDATION=
MUST_REMAIN_UNCHANGED

SUPPORT_PROVENANCE_RULES=
MUST_REMAIN_UNCHANGED

SELECTED_CONTEXT_SEGMENT_RULES=
MUST_REMAIN_UNCHANGED

MODEL=
MUST_REMAIN_UNCHANGED

RETRY_OR_SECOND_MODEL_CALL=
NOT_PERMITTED

PRODUCTION_PROMPT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

PRODUCTION_CHANGE=
NONE

CORRIDOR_1_STATUS=
ACTIVE

NEXT_ACTION=
DESIGN_BOUNDED_UNSEEDED_EXPERIMENTAL_PRESENTATION_VALIDATION
MAP
