#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="5aa7f5ddb"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — GOVERNANCE READ BINDING GAP CLASSIFICATION ==="
echo "MODE=EXECUTION"
echo "PRODUCTION_CHANGE=NONE"
echo

echo "=== VERIFIED PERSISTED GOVERNANCE FACTS ==="
echo "DELEGATION_PERSISTED=YES"
echo "DELEGATION_FIELDS=delegation_id,project_id,package_id,package_version,authorization_state,authorization_timestamp,delegated_by"
echo "VALIDATION_RESULT_PERSISTED=YES"
echo "VALIDATION_FIELDS=validation_result_id,package_id,package_version,delegation_id,validation_status,validation_timestamp"
echo "ENVELOPE_GATE_PERSISTED=YES"
echo "ENVELOPE_GATE_BINDS=package_lineage,delegation_id,validation_result_id,gate_status"
echo

echo "=== READER CLASSIFICATION ==="
echo "Q1_PUBLIC_EXACT_DELEGATION_READER_EXISTS=NO_EVIDENCE_FOUND"
echo "Q2_PUBLIC_EXACT_VALIDATION_READER_EXISTS=NO_EVIDENCE_FOUND"
echo "Q3_PUBLIC_EXACT_ENVELOPE_LINEAGE_READER_EXISTS=NO_EVIDENCE_FOUND"
echo "Q4_NARROW_READ_ONLY_READERS_REQUIRED=YES"
echo "Q5_ROUTE_CAN_BIND_GOVERNANCE_OK_WITHOUT_SYNTHESIS=YES_AFTER_NARROW_READERS"
echo

echo "=== MINIMUM REQUIRED READ UNIT ==="
echo "UNIT_1=FAIL_CLOSED_EXACT_DELEGATION_READER"
echo "UNIT_2=FAIL_CLOSED_EXACT_VALIDATION_RESULT_READER"
echo "UNIT_3=FAIL_CLOSED_EXACT_ENVELOPE_GATE_OR_LINEAGE_READER"
echo "UNIT_4=EXACT_PACKAGE_VERSION_DELEGATION_VALIDATION_CORRELATION"
echo "UNIT_5=TARGETED_READ_ONLY_TESTS"
echo
echo "OWNER=EXISTING_GOVERNANCE_PERSISTENCE_DOMAIN"
echo "NEW_DATABASE_OWNER_REQUIRED=NO"
echo "NEW_AUTHORITY_CREATED=NO"
echo "NEW_DELEGATION_CREATED=NO"
echo "NEW_VALIDATION_CREATED=NO"
echo "NEW_GATE_CREATED=NO"
echo

echo "=== FAIL-CLOSED REQUIREMENTS ==="
echo "MISSING_DELEGATION=REJECT"
echo "MISMATCHED_PACKAGE_LINEAGE=REJECT"
echo "NONAUTHORIZED_DELEGATION_STATE=REJECT"
echo "MISSING_VALIDATION_RESULT=REJECT"
echo "MISMATCHED_VALIDATION_DELEGATION=REJECT"
echo "UNSUCCESSFUL_VALIDATION_STATUS=REJECT"
echo "MISSING_OR_MISMATCHED_ENVELOPE_GATE=REJECT"
echo "ROUTE_SYNTHESIZED_GOVERNANCE_OK=PROHIBITED"
echo "ROUTE_SYNTHESIZED_DELEGATION=PROHIBITED"
echo

echo "=== AUTHORIZATION BOUNDARY ==="
echo "CURRENT_UNMOUNTED_ROUTE_AUTHORIZATION_COVERS_ROUTE_COMPOSITION=YES"
echo "CURRENT_UNMOUNTED_ROUTE_AUTHORIZATION_COVERS_NEW_GOVERNANCE_READERS=NO"
echo "MINIMUM_GOVERNANCE_READ_UNIT_REQUIRES_SEPARATE_IMPLEMENTATION_AUTHORIZATION=YES"
echo "ROUTE_IMPLEMENTATION_REMAINS_PAUSED=YES"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo

echo "=== CLASSIFICATION RESULT ==="
echo "GOVERNANCE_READ_BINDING_GAP_CONFIRMED=YES"
echo "MINIMUM_GOVERNANCE_READ_UNIT_CLASSIFIED=YES"
echo "CORRIDOR_6_STATUS=AWAITING_BOUNDED_GOVERNANCE_READ_UNIT_IMPLEMENTATION_AUTHORIZATION"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=REQUEST_EXPLICIT_USER_AUTHORIZATION_FOR_BOUNDED_GOVERNANCE_READ_UNIT_AND_TARGETED_TESTS"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
