#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PROMPT AND RESPONSE CONTRACT PRESENTATION CORRIDOR CLOSURE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor fbdee7f4 HEAD
test -z "$(git status --porcelain)"

results="scripts/classify-post-promotion-production-behavioral-results.sh"
test -f "$results"

grep -q 'CORRIDOR_1_STATUS=' "$results"
grep -q '^READY_FOR_CLOSURE_CLASSIFICATION$' \
  <(awk '/CORRIDOR_1_STATUS=/{getline; print}' "$results")

grep -q 'SEMANTIC_RESULT=' "$results"
grep -q '^10_OF_10_PASS$' \
  <(awk '/SEMANTIC_RESULT=/{getline; print}' "$results")

grep -q 'DETERMINISTIC_REGRESSION_RESULT=' "$results"
grep -q '^127_OF_127_PASS$' \
  <(awk '/DETERMINISTIC_REGRESSION_RESULT=/{getline; print}' "$results")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

CORRIDOR_1_FINAL_RESULT=
SUCCESSFUL_PRODUCTION_PROMPT_PRESENTATION_REMEDY_ESTABLISHED

PRODUCTION_INTERVENTION=
EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION_AS_DEFAULT

FIXED_SEED_DIAGNOSTIC=
CONTROL_0_OF_10_EXPERIMENTAL_10_OF_10

UNSEEDED_PRE_PROMOTION_EXPERIMENTAL=
10_OF_10_SEMANTIC_PASS

POST_PROMOTION_DETERMINISTIC_REGRESSION=
127_OF_127_PASS

POST_PROMOTION_PRODUCTION_BEHAVIORAL_SAMPLE=
10_OF_10_SEMANTIC_PASS

POST_PROMOTION_UNSUPPLIED_SUPPORT_FAILURES=
0_OF_10

POST_PROMOTION_FAIL_CLOSED_OR_RUNTIME_REJECTIONS=
0_OF_10

OUTPUT_VARIANCE=
10_UNIQUE_FINGERPRINTS_ACROSS_10_POST_PROMOTION_RUNS

SEMANTIC_RELIABILITY_DESPITE_OUTPUT_VARIANCE=
ESTABLISHED_ON_TESTED_PRODUCTION_SURFACE

FAIL_CLOSED_VALIDATION=
PRESERVED

SUPPORT_PROVENANCE_CONTRACT=
PRESERVED

SELECTED_CONTEXT_SEGMENT_CONTRACT=
PRESERVED

STRUCTURED_RESPONSE_SCHEMA=
PRESERVED

MODEL=
UNCHANGED

GENERATION_POLICY=
UNCHANGED

RETRY_OR_SECOND_MODEL_CALL=
NONE

ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=
PRESERVED

CORRIDOR_1_STATUS=
CLOSED

PRODUCTION_CHANGE=
PROMPT_PRESENTATION_DEFAULT_PROMOTED

SUCCESSOR_CORRIDOR=
GENERATION_CONTROL_AND_SAMPLING_POLICY

SUCCESSOR_CORRIDOR_ENTRY_REQUIREMENT=
CLASSIFY_WHETHER_FURTHER_GENERATION_CONTROL_INVESTIGATION_REMAINS_NECESSARY_AFTER_SUCCESSFUL_CORRIDOR_1_REMEDY

NEXT_ACTION=
CLASSIFY_PHASE_2_SUCCESSOR_CORRIDOR_NECESSITY
MAP
