#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=DELEGATION_WORKSPACE' \
  'ACTIVE_CORRIDOR=REQUEST_CHANGES_PERSISTENCE' \
  'CURRENT_CHECKPOINT=0ca8563b' \
  'MODE=COLLABORATION' \
  'PURPOSE=CLASSIFY_REQUEST_CHANGES_IMPLEMENTATION_READINESS_FROM_VERIFIED_IDENTITY_PATH'

printf '\n=== VERIFIED IDENTITY PATH ===\n'
printf '%s\n' \
  'APPROVAL_READ_MODEL_HAS_PROJECT_ID=YES' \
  'APPROVAL_READ_MODEL_HAS_CONVERSATION_ID=YES' \
  'REPOSITORY_SOURCE_HAS_PROJECT_ID=YES' \
  'REPOSITORY_SOURCE_HAS_CONVERSATION_ID=YES' \
  'REPOSITORY_DETAIL_LOOKUP=PROJECT_ID_PLUS_DRAFT_PACKAGE_ID' \
  'APPROVAL_REQUEST_ID_CURRENTLY_DERIVED_FROM_DRAFT_IDENTITY=YES' \
  'SERVER_CAN_RESOLVE_AUTHORITATIVE_PROJECT_AND_CONVERSATION=YES'

printf '\n=== REQUIRED FAIL-CLOSED BOUNDARY ===\n'
printf '%s\n' \
  'CLIENT_PROJECT_ID_AS_AUTHORITY=PROHIBITED' \
  'CLIENT_CONVERSATION_ID_AS_AUTHORITY=PROHIBITED' \
  'NULL_OR_EMPTY_ORIGINATING_CONVERSATION=REJECT' \
  'UNKNOWN_OR_NON_PENDING_DRAFT=REJECT' \
  'EMPTY_FEEDBACK=REJECT' \
  'SERVER_RESOLVED_PROJECT_ID=REQUIRED' \
  'SERVER_RESOLVED_CONVERSATION_ID=REQUIRED'

printf '\n=== EXISTING WORKFLOW REUSE ===\n'
printf '%s\n' \
  'WORKFLOW=runMatildaConversationWorkflow' \
  'WORKFLOW_MESSAGE=EXECUTIVE_FEEDBACK' \
  'WORKFLOW_PROJECT_ID=SERVER_RESOLVED' \
  'WORKFLOW_CONVERSATION_ID=SERVER_RESOLVED' \
  'IEL_PERSISTENCE=EXISTING_WORKFLOW' \
  'CONVERSATION_TURN_PERSISTENCE=EXISTING_WORKFLOW' \
  'LIVING_DRAFT_UPDATE=EXISTING_WORKFLOW' \
  'ACTIVE_CONVERSATION_SWITCH=NO'

printf '\n=== AUTHORITY PRESERVATION ===\n'
printf '%s\n' \
  'APPROVAL_STATUS_MUTATION=NO' \
  'CANONICAL_PACKAGE_MUTATION=NO' \
  'DELEGATION_MUTATION=NO' \
  'VALIDATION_AUTHORIZATION=NO' \
  'ENVELOPE_AUTHORIZATION=NO' \
  'EXECUTION_AUTHORIZATION=NO' \
  'NEW_SEMANTIC_AUTHORITY=NO' \
  'NEW_PERSISTENCE=NO'

printf '\n=== READINESS DETERMINATION ===\n'
printf '%s\n' \
  'IDENTITY_RESOLUTION_PATH=VERIFIED' \
  'SHARED_INTERPRETATION_PATH=VERIFIED' \
  'PERSISTENCE_OWNERSHIP=VERIFIED_EXISTING_WORKFLOW' \
  'IMPLEMENTATION_SCOPE=THIN_ROUTE_PLUS_EXISTING_CLIENT_CONTROL' \
  'CORRIDOR_1_IMPLEMENTATION_READINESS=READY_BOUNDED' \
  'IMPLEMENTATION_STARTED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'NEXT_ACTION=REQUEST_EXPLICIT_IMPLEMENTATION_AUTHORIZATION'

printf '\n=== WORKTREE ===\n'
git status --short
