#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=9678e6cb' \
  'ISSUE_RESOLVED=NO' \
  'ACTION=CLASSIFY_POST_FIX_TIMEOUT_LOG_CORRELATION' \
  'NEW_OLLAMA_INVOCATION=NO' \
  'PRODUCTION_CHANGE=NO'

printf '\n=== EXACT POST-FIX TIMEOUT EVIDENCE ===\n'
printf '%s\n' \
  'POST_FIX_ATTEMPT_1_SERVER_STATUS=500' \
  'POST_FIX_ATTEMPT_1_SERVER_DURATION_APPROX=59.999_SECONDS' \
  'POST_FIX_ATTEMPT_1_PROMPT_TOKENS=4151' \
  'POST_FIX_ATTEMPT_1_LAST_OBSERVED_DECODED_TOKENS=1416' \
  'POST_FIX_ATTEMPT_1_SERVER_CANCEL_TASK=YES' \
  'POST_FIX_ATTEMPT_1_STOP_PROCESSING_TOKENS=5621' \
  'POST_FIX_ATTEMPT_2_SERVER_STATUS=500' \
  'POST_FIX_ATTEMPT_2_SERVER_DURATION_APPROX=60_SECONDS' \
  'POST_FIX_ATTEMPT_2_PROMPT_TOKENS=4151' \
  'POST_FIX_ATTEMPT_2_LAST_OBSERVED_DECODED_TOKENS=1431' \
  'POST_FIX_ATTEMPT_2_SERVER_CANCEL_TASK=YES' \
  'POST_FIX_ATTEMPT_2_STOP_PROCESSING_TOKENS=5652'

printf '\n=== CAUSAL CLASSIFICATION ===\n'
printf '%s\n' \
  'POST_FIX_TIMEOUT_REQUEST_TO_SERVER_TASK_MAPPING_ESTABLISHED=YES' \
  'CLIENT_ABORT_OCCURRED_AT_60_SECOND_BOUNDARY=YES' \
  'OLLAMA_WAS_STILL_ACTIVELY_DECODING_AT_ABORT=YES' \
  'PROMPT_EVALUATION_STALL_ESTABLISHED=NO' \
  'OLLAMA_SERVICE_FAILURE_ESTABLISHED=NO' \
  'VALIDATOR_FAILURE_CAUSED_TIMEOUT=NO' \
  'PROMPT_SIZE_AS_PRIMARY_TIMEOUT_CAUSE_SUPPORTED=NO' \
  'IMMEDIATE_TIMEOUT_CAUSE=CLIENT_ABORT_DURING_ACTIVE_RESPONSE_GENERATION' \
  'WHY_MODEL_GENERATION_REQUIRES_MORE_THAN_60_SECONDS=NOT_YET_ESTABLISHED'

printf '\n=== SUPPORT REFERENCE FIX STATUS ===\n'
printf '%s\n' \
  'SUPPORT_REFERENCE_FIX_VALIDATED=NO' \
  'SUPPORT_REFERENCE_FIX_DISPROVEN=NO' \
  'POST_FIX_OUTPUT_NEVER_RETURNED_TO_VALIDATOR=YES' \
  'THIRD_IDENTICAL_VALIDATION_JUSTIFIED=NO'

printf '\n=== NEXT DECISION CLASS ===\n'
printf '%s\n' \
  'NEXT_ACTION=CLASSIFY_TIMEOUT_POLICY_AND_RESPONSE_LENGTH_BOUNDARY_BEFORE_ANY_IMPLEMENTATION' \
  'QUESTION=WHETHER_60_SECOND_CLIENT_TIMEOUT_IS_INCOMPATIBLE_WITH_OBSERVED_NORMAL_STRUCTURED_RESPONSE_GENERATION_DURATION_ON_THIS_PRODUCTION_EQUIVALENT_SURFACE' \
  'TIMEOUT_CHANGE_AUTHORIZED=NO' \
  'MODEL_CHANGE_AUTHORIZED=NO' \
  'PROMPT_CHANGE_AUTHORIZED=NO' \
  'RETRY_CHANGE_AUTHORIZED=NO'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'THIRD_OLLAMA_INVOCATION=NO' \
  'TIMEOUT_CHANGED=NO' \
  'MODEL_CHANGED=NO' \
  'VALIDATOR_CHANGED=NO' \
  'PROMPT_CHANGED=NO' \
  'GENERATION_POLICY_CHANGED=NO'

printf '\n=== WORKTREE ===\n'
git status --short
