#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=EXECUTIVE_MISSION_OVERVIEW' \
  'CORRIDOR=EXECUTIVE_OVERVIEW_VALIDATION_AND_CLOSURE' \
  'CORRIDOR_1=MISSION_IDENTITY_AND_OBJECTIVE_CLASSIFIED' \
  'CORRIDOR_2=MISSION_STATE_PROJECTION_CLASSIFIED' \
  'CORRIDOR_3=PIPELINE_POSITION_CLASSIFIED' \
  'MISSION_OBJECTIVE_AUTHORITY=GOVERNANCE_PACKAGE_REQUESTED_OUTCOME' \
  'MISSION_OBJECTIVE_PROJECTION_GAP=CONFIRMED' \
  'MISSION_STATE_PROJECTION=PARTIAL' \
  'GOVERNANCE_PIPELINE_PROJECTION=PARTIAL' \
  'DEPARTMENT_LEVEL_PIPELINE_AUTHORITY=NOT_ESTABLISHED_ON_LIVE_MAIN_DB' \
  'NEW_SEMANTIC_AUTHORITY_REQUIRED=NO' \
  'NEW_PERSISTENCE_REQUIRED_FOR_CURRENT_BOUNDED_SCOPE=NO' \
  'SMALLEST_SAFE_IMPLEMENTATION_SURFACE=MISSION_READ_PROJECTION_AND_EXECUTIVE_PRESENTATION_MAPPING' \
  'RENDERER_SEMANTIC_AUTHORITY=NOT_ALLOWED' \
  'CLIENT_PRODUCTION_BUILD=PASS' \
  'PRE_IMPLEMENTATION_REPOSITORY_RECONCILIATION=COMPLETE' \
  'IMPLEMENTATION_DIRECTION=STABLE' \
  'IMPLEMENTATION_READINESS=READY_BOUNDED' \
  'EXECUTIVE_MISSION_OVERVIEW_IMPLEMENTED=NO' \
  'PHASE_OUTCOME_ACHIEVED=NO' \
  'PHASE_CLOSURE_READY=NO' \
  'PHASE_CLOSURE_BLOCKER=BOUNDED_IMPLEMENTATION_AND_POST_IMPLEMENTATION_VALIDATION_NOT_YET_PERFORMED' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'NEXT_ACTION=AWAIT_EXPLICIT_IMPLEMENTATION_AUTHORIZATION'

printf '\n=== CHECKPOINT ===\n'
git rev-parse --short HEAD
git status --short
