#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PROMPT PRESENTATION COMPLEXITY AND PARENT-CHILD IDENTITY RISK ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor e032ec20 HEAD

corridor="scripts/investigate-prompt-and-response-contract-presentation.sh"
ollama="scripts/utils/ollamaChat.ts"

for artifact in "$corridor" "$ollama"; do
  test -f "$artifact"
  echo "PRESENT=$artifact"
done

echo
echo "=== VERIFY CURRENT CORRIDOR STATE ==="
grep -q 'CORRIDOR_1_STATUS=' "$corridor"
grep -q '^ACTIVE$' <(awk '/CORRIDOR_1_STATUS=/{getline; print}' "$corridor")
grep -q 'NEXT_ACTION=' "$corridor"
grep -q '^CLASSIFY_PROMPT_PRESENTATION_COMPLEXITY_AND_PARENT_CHILD_IDENTITY_RISK$' \
  <(awk '/NEXT_ACTION=/{getline; print}' "$corridor")
echo "CORRIDOR_STATE=CONFIRMED"

echo
echo "=== VERIFY DUAL IDENTITY PRESENTATION ==="
grep -q 'Bounded project context evidence:' "$ollama"
grep -q 'Source: ${item.relativePath}:${item.lineNumber}' "$ollama"
grep -q 'Project-context segment candidates:' "$ollama"
grep -q 'relativePath = ${item.relativePath}' "$ollama"
grep -q 'sourceStartLine = ${item.sourceStartLine}' "$ollama"
grep -q 'sourceEndLine = ${item.sourceEndLine}' "$ollama"
echo "DUAL_IDENTITY_PRESENTATION=CONFIRMED"

echo
echo "=== VERIFY MODEL MUST MAP CHILD SELECTION TO PARENT SUPPORT ==="
grep -q 'selectedContextSegments records semantic project-context admission; supportSourceReferences records support provenance' "$ollama"
grep -q 'For project-context support, use type project_context_excerpt with the exact relativePath and lineNumber supplied' "$ollama"
grep -q 'Never use a Segment source line range, sourceStartLine, sourceEndLine, or child segment line number as a project_context_excerpt support identity' "$ollama"
grep -q 'project-context support without selecting a supplied child segment for that parent' "$ollama"
echo "PARENT_CHILD_MAPPING_REQUIREMENT=CONFIRMED"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

INVESTIGATION_UNIT=
PROMPT_PRESENTATION_COMPLEXITY_AND_PARENT_CHILD_IDENTITY_RISK

CURRENT_PRESENTATION_MODEL=
PARENT_PROJECT_CONTEXT_SOURCE_IDENTITIES
PLUS
CHILD_SEGMENT_SELECTION_IDENTITIES

PARENT_IDENTITY=
RELATIVE_PATH_COLON_PARENT_LINE_NUMBER

CHILD_IDENTITY=
RELATIVE_PATH_PLUS_SOURCE_START_LINE_PLUS_SOURCE_END_LINE

MODEL_REQUIRED_CROSS_MAPPING=
SELECT_CHILD_SEGMENTS_FOR_SEMANTIC_ADMISSION
WHILE
CITING_ONLY_PARENT_SOURCE_IDENTITIES_FOR_SUPPORT_PROVENANCE

MODEL_REQUIRED_NEGATIVE_RULE=
DO_NOT_USE_CHILD_SEGMENT_LINE_INFORMATION_AS_PARENT_SUPPORT_IDENTITY

DETERMINISTIC_POST_GENERATION_REQUIREMENT=
PARENT_SUPPORT_REFERENCE_MUST_MATCH_SUPPLIED_PARENT
AND
SUPPORTED_PARENT_WITH_CHILDREN_MUST_HAVE_SELECTED_CHILD

PRESENTATION_COMPLEXITY=
ESTABLISHED

MULTIPLE_RELATED_IDENTITY_SCHEMES_IN_SINGLE_GENERATION_CONTRACT=
ESTABLISHED

MODEL_MUST_TRANSFORM_BETWEEN_RELATED_PARENT_AND_CHILD_IDENTITY_DOMAINS=
ESTABLISHED

PARENT_CHILD_IDENTITY_CONFUSION_RISK=
STRUCTURALLY_PLAUSIBLE

PARENT_CHILD_IDENTITY_CONFUSION_AS_OBSERVED_ROOT_CAUSE=
NOT_ESTABLISHED

PROMPT_PRESENTATION_COMPLEXITY_AS_OBSERVED_ROOT_CAUSE=
NOT_ESTABLISHED

SIMPLE_MISSING_INSTRUCTION_CAUSE=
NOT_ESTABLISHED

CURRENT_PROMPT_RULES=
EXPLICIT

CURRENT_VALIDATOR=
CORRECTLY_FAIL_CLOSED

EVIDENCE_GAP=
NO_CONTROLLED_COMPARISON_CURRENTLY_ESTABLISHES_WHETHER_REDUCING_OR_RESTRUCTURING_PARENT_CHILD_IDENTITY_PRESENTATION_IMPROVES_SEMANTIC_ACCEPTANCE

PROMPT_INTERVENTION_REQUIREMENT=
NOT_YET_ESTABLISHED

PROMPT_INTERVENTION_READINESS=
NOT_READY

NEXT_BOUNDED_INVESTIGATION=
DEFINE_A_NON_PRODUCTION_DIAGNOSTIC_COMPARISON_THAT_CHANGES_PRESENTATION_ONLY_AND_PRESERVES_THE_SEMANTIC_CONTRACT

DIAGNOSTIC_GOAL=
TEST_WHETHER_PARENT_CHILD_IDENTITY_PRESENTATION_COMPLEXITY_MATERIALLY_CONTRIBUTES_TO_UNSUPPLIED_SUPPORT_REFERENCE_FAILURES

PRODUCTION_PROMPT_CHANGE=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

CORRIDOR_1_STATUS=
ACTIVE

NEXT_ACTION=
DEFINE_PROMPT_PRESENTATION_DIAGNOSTIC_COMPARISON_BOUNDARY
MAP
