#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY BOUNDED UNSEEDED PRESENTATION VALIDATION IMPLEMENTATION READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 5e8e3ee1 HEAD
test -z "$(git status --porcelain)"

design="scripts/design-bounded-unseeded-experimental-presentation-validation.sh"
runner="scripts/run-bounded-prompt-presentation-diagnostic.ts"
ollama="scripts/utils/ollamaChat.ts"

for file in "$design" "$runner" "$ollama"; do
  test -f "$file"
done

grep -q 'DESIGN_STATUS=' "$design"
grep -q '^COMPLETE$' <(awk '/DESIGN_STATUS=/{getline; print}' "$design")
grep -q 'GENERATION_SEED=' "$design"
grep -q '^ABSENT$' <(awk '/GENERATION_SEED=/{getline; print}' "$design")
grep -q 'RUN_COUNT=' "$design"
grep -q '^10$' <(awk '/RUN_COUNT=/{getline; print}' "$design")
grep -q 'PRESENTATION_VARIANT=' "$design"
grep -q '^EXPLICIT_PARENT_CHILD_SEPARATION$' <(awk '/PRESENTATION_VARIANT=/{getline; print}' "$design")

grep -q 'validationPromptPresentationVariant' "$ollama"
grep -q 'explicit_parent_child_separation' "$ollama"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

READINESS_UNIT=
BOUNDED_UNSEEDED_EXPERIMENTAL_PRESENTATION_VALIDATION_IMPLEMENTATION_READINESS

DESIGN_STATUS=
COMPLETE

VALIDATION_CLASS=
NON_PRODUCTION_PRODUCTION_EQUIVALENT_UNSEEDED_PRESENTATION_VALIDATION

TEST_ARM=
EXPERIMENTAL_PRESENTATION_ONLY

PRESENTATION_VARIANT=
EXPLICIT_PARENT_CHILD_SEPARATION

RUN_COUNT=
10

GENERATION_SEED=
ABSENT

EXISTING_PRESENTATION_SELECTOR=
AVAILABLE

NEW_RUNTIME_SEAM_REQUIRED=
NO

NEW_PRODUCTION_SURFACE_REQUIRED=
NO

IMPLEMENTATION_SURFACE=
BOUNDED_VALIDATION_RUNNER_ONLY

RUNNER_REQUIREMENT=
REUSE_EXISTING_DIAGNOSTIC_INPUTS_AND_PRESENTATION_SELECTOR_WITHOUT_VALIDATION_GENERATION_SEED

ONE_INVOCATION_PER_RUN=
PRESERVED

EXECUTION_MODE=
SEQUENTIAL

RETRY=
NONE

SEMANTIC_CONTRACT=
UNCHANGED

STRUCTURED_RESPONSE_SCHEMA=
UNCHANGED

SUPPORT_PROVENANCE_RULES=
UNCHANGED

SELECTED_CONTEXT_SEGMENT_RULES=
UNCHANGED

FAIL_CLOSED_VALIDATION=
UNCHANGED

MODEL=
UNCHANGED

PRODUCTION_PROMPT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

IMPLEMENTATION_RISK=
BOUNDED_AND_REVERSIBLE

ROLLBACK_BOUNDARY=
REMOVE_UNSEEDED_VALIDATION_RUNNER_ONLY

VALIDATION_IMPLEMENTATION=
EVIDENCE_SUPPORTED

VALIDATION_IMPLEMENTATION_READINESS=
READY

PRODUCTION_REMEDY_READINESS=
NOT_READY

PRODUCTION_CHANGE=
NONE

CORRIDOR_1_STATUS=
ACTIVE

NEXT_ACTION=
IMPLEMENT_BOUNDED_UNSEEDED_EXPERIMENTAL_PRESENTATION_VALIDATION

IMPLEMENTATION_AUTHORIZED=
NO
MAP
