#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY PROMPT PRESENTATION DIAGNOSTIC RUNNER IMPLEMENTATION READINESS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 84f360d8 HEAD

design="scripts/design-bounded-prompt-presentation-diagnostic-runner.sh"
boundary="scripts/define-prompt-presentation-diagnostic-comparison-boundary.sh"
ollama="scripts/utils/ollamaChat.ts"

for artifact in "$design" "$boundary" "$ollama"; do
  test -f "$artifact"
  echo "PRESENT=$artifact"
done

echo
echo "=== VERIFY RUNNER DESIGN CLOSURE ==="
grep -q 'RUNNER_DESIGN_STATUS=' "$design"
grep -q '^COMPLETE$' <(awk '/RUNNER_DESIGN_STATUS=/{getline; print}' "$design")
grep -q 'NEXT_ACTION=' "$design"
grep -q '^CLASSIFY_PROMPT_PRESENTATION_DIAGNOSTIC_RUNNER_IMPLEMENTATION_READINESS$' \
  <(awk '/NEXT_ACTION=/{getline; print}' "$design")
echo "RUNNER_DESIGN_CLOSURE=CONFIRMED"

echo
echo "=== VERIFY VALIDATION-ONLY BOUNDARY ==="
grep -q 'VALIDATION_ONLY_NON_PRODUCTION_AB_COMPARISON' "$design"
grep -q 'FIXED_SEED_SCOPE=' "$design"
grep -q '^VALIDATION_ONLY$' <(awk '/FIXED_SEED_SCOPE=/{getline; print}' "$design")
grep -q 'ONLY_CHANGED_VARIABLE=' "$design"
grep -q '^PROMPT_PRESENTATION_STRUCTURE$' <(awk '/ONLY_CHANGED_VARIABLE=/{getline; print}' "$design")
echo "VALIDATION_ONLY_BOUNDARY=CONFIRMED"

echo
echo "=== VERIFY PRODUCTION SURFACE IS NOT AUTHORIZED ==="
grep -q 'PRODUCTION_PROMPT_CHANGE=' "$design"
grep -q '^NOT_AUTHORIZED$' <(awk '/PRODUCTION_PROMPT_CHANGE=/{getline; print}' "$design")
grep -q 'PRODUCTION_GENERATION_POLICY_CHANGE=' "$design"
grep -q '^NOT_AUTHORIZED$' <(awk '/PRODUCTION_GENERATION_POLICY_CHANGE=/{getline; print}' "$design")
echo "PRODUCTION_AUTHORIZATION_BOUNDARY=CONFIRMED"

echo
echo "=== VERIFY DIAGNOSTIC SEAM REQUIREMENT ==="
grep -q 'validationGenerationSeed' "$ollama"
grep -q 'options:' "$ollama"
grep -q 'seed: context.validationGenerationSeed' "$ollama"
echo "EXISTING_VALIDATION_GENERATION_SEAM=CONFIRMED"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

INVESTIGATION_UNIT=
PROMPT_PRESENTATION_DIAGNOSTIC_RUNNER_IMPLEMENTATION_READINESS

RUNNER_DESIGN=
COMPLETE

DIAGNOSTIC_CLASS=
VALIDATION_ONLY_NON_PRODUCTION_AB_COMPARISON

CONTROL_ARM=
CURRENT_PRODUCTION_EQUIVALENT_PROMPT_PRESENTATION

EXPERIMENTAL_ARM=
SEMANTICALLY_EQUIVALENT_PRESENTATION_ONLY_VARIANT

ONLY_CHANGED_VARIABLE=
PROMPT_PRESENTATION_STRUCTURE

FIXED_SEED=
424242

FIXED_SEED_SCOPE=
VALIDATION_ONLY

EXISTING_VALIDATION_GENERATION_SEAM=
AVAILABLE

REQUIRED_NEW_DIAGNOSTIC_SEAM=
REQUEST_SCOPED_PRESENTATION_VARIANT_SELECTOR

REQUIRED_SEAM_SCOPE=
VALIDATION_ONLY

PRODUCTION_DEFAULT_BEHAVIOR=
UNCHANGED

PRODUCTION_PROMPT_PRESENTATION=
UNCHANGED

STRUCTURED_RESPONSE_SCHEMA=
UNCHANGED

SEMANTIC_CONTRACT=
UNCHANGED

SUPPORT_PROVENANCE_RULES=
UNCHANGED

SELECTED_CONTEXT_SEGMENT_RULES=
UNCHANGED

FAIL_CLOSED_VALIDATION=
UNCHANGED

MODEL=
UNCHANGED

ONE_INVOCATION_PER_RUN=
PRESERVED

RETRY=
NONE

IMPLEMENTATION_SURFACE=
SCRIPTS_UTILS_OLLAMA_CHAT_VALIDATION_ONLY_PRESENTATION_BRANCH
PLUS
BOUNDED_DIAGNOSTIC_RUNNER

IMPLEMENTATION_BOUNDARY=
DIAGNOSTIC_ONLY_SEAM_MUST_BE_INERT_WHEN_NO_VALIDATION_PRESENTATION_VARIANT_IS_SUPPLIED

ROLLBACK_BOUNDARY=
REMOVE_VALIDATION_PRESENTATION_VARIANT_SEAM_AND_RUNNER_TO_RESTORE_PRE_DIAGNOSTIC_STATE

IMPLEMENTATION_RISK=
BOUNDED_AND_REVERSIBLE_IF_VALIDATION_ONLY_DEFAULT_INERTNESS_IS_PRESERVED

PRODUCTION_PROMPT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

DIAGNOSTIC_RUNNER_IMPLEMENTATION=
EVIDENCE_SUPPORTED

DIAGNOSTIC_RUNNER_IMPLEMENTATION_READINESS=
READY

PRODUCTION_REMEDY_READINESS=
NOT_READY

CORRIDOR_1_STATUS=
ACTIVE

NEXT_ACTION=
IMPLEMENT_BOUNDED_VALIDATION_ONLY_PROMPT_PRESENTATION_DIAGNOSTIC

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE
MAP
