#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OLLAMA="scripts/utils/ollamaChat.ts"
RUNNER="scripts/run-dashboard-generation-control-comparison.ts"
RESULT="docs/checkpoints/MATILDA_UI_503_REPLACEMENT_CONTROLLED_COMPARISON_RESULT.txt"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=3c9331a3' \
  'ISSUE_RESOLVED=NO' \
  'ACTION=CLASSIFY_PROJECT_CONTEXT_SUPPORT_REFERENCE_MAPPING_GAP' \
  'NEW_OLLAMA_INVOCATION=NO'

printf '\n=== SUPPLIED PARENT IDENTITY PRESENTATION ===\n'
sed -n '751,870p' "$OLLAMA"

printf '\n=== VALIDATOR PARENT IDENTITY MEMBERSHIP ===\n'
sed -n '1040,1145p' "$OLLAMA"

printf '\n=== PARSED SUPPORT OBSERVABILITY ===\n'
sed -n '232,345p' "$RUNNER"

printf '\n=== RESULT EVIDENCE ===\n'
grep -nE \
  'CONTROLLED RUN|parsedSelectedContextCount|parsedSupportReferenceCount|failureClass|errorMessage|COMPARISON SUMMARY|ACCEPTANCE BOUNDARY' \
  "$RESULT" || true

printf '\n=== CONTRACT CLASSIFICATION ===\n'

PROMPT_PARENT_IDENTITY="$(
  grep -F 'For project-context support, use type project_context_excerpt with the exact relativePath and lineNumber supplied in bounded project context evidence.' \
    "$OLLAMA" || true
)"

VALIDATOR_PARENT_IDENTITY="$(
  grep -F '${excerpt.relativePath}:${excerpt.lineNumber}' "$OLLAMA" || true
)"

if [[ -n "$PROMPT_PARENT_IDENTITY" ]] && [[ -n "$VALIDATOR_PARENT_IDENTITY" ]]; then
  printf '%s\n' \
    'PROMPT_PARENT_IDENTITY_SHAPE=relativePath:lineNumber' \
    'VALIDATOR_PARENT_IDENTITY_SHAPE=relativePath:lineNumber' \
    'PROMPT_VALIDATOR_PARENT_IDENTITY_SHAPE_MISMATCH=NO'
else
  printf '%s\n' \
    'PROMPT_VALIDATOR_PARENT_IDENTITY_SHAPE_MISMATCH=NOT_CLASSIFIABLE'
fi

if grep -q 'parsedSupportReferenceCount' "$RUNNER" \
  && ! grep -qE 'parsedSupport(SourceReferences|References):' "$RUNNER"; then
  printf '%s\n' \
    'PARSED_SUPPORT_REFERENCE_VALUES_PERSISTED=NO' \
    'PARSED_SUPPORT_REFERENCE_COUNT_ONLY=YES'
else
  printf '%s\n' \
    'PARSED_SUPPORT_REFERENCE_VALUES_PERSISTED=UNKNOWN_OR_PRESENT'
fi

printf '%s\n' \
  'MODEL_RETURNED_PROJECT_CONTEXT_SUPPORT_REFERENCES=YES' \
  'MODEL_RETURNED_REFERENCE_VALUES_AVAILABLE_IN_COMMITTED_RESULT=NO' \
  'EXACT_OFFENDING_REFERENCE_IDENTITY_ESTABLISHED=NO' \
  'CHILD_LINE_NUMBER_CONFUSION_ESTABLISHED=NO' \
  'VALIDATOR_MALFUNCTION_ESTABLISHED=NO' \
  'CURRENT_EVIDENCE_SUPPORTS_PROMPT_VALIDATOR_SHAPE_ALIGNMENT=YES' \
  'CURRENT_GAP=OFFENDING_MODEL_AUTHORED_REFERENCE_VALUES_NOT_CAPTURED' \
  'NEXT_SOLUTION_CLASS=ADD_VALIDATION_ONLY_OBSERVABILITY_FOR_PARSED_SUPPORT_REFERENCE_VALUES_BEFORE_MEMBERSHIP_REJECTION' \
  'IMPLEMENTATION_AUTHORIZED=NO'

printf '\n=== SAFETY BOUNDARY ===\n'
printf '%s\n' \
  'PRODUCTION_PROMPT_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_WEAKENING_AUTHORIZED=NO' \
  'GENERATION_POLICY_CHANGE_AUTHORIZED=NO' \
  'MODEL_CHANGE_AUTHORIZED=NO' \
  'NEW_EXPERIMENT_AUTHORIZED=NO' \
  'NEXT_ACTION=CLASSIFY_MINIMUM_OBSERVABILITY_CHANGE_REQUIRED_TO_CAPTURE_EXACT_OFFENDING_REFERENCE_VALUES'

printf '\n=== WORKTREE ===\n'
git status --short
