#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY SEMANTIC HISTORY CONTEXT OPTIMIZATION SCOPE ==="

echo
echo "=== BASELINE ==="
echo "BRANCH=$(git branch --show-current)"
echo "HEAD=$(git rev-parse --short=8 HEAD)"
echo "COMMIT=$(git log -1 --format=%s)"
git status --short

echo
echo "=== VERIFY CURRENT-STATE RECONCILIATION CHECKPOINT ==="

expected_head="a9c2b334"

if [[ "$(git rev-parse --short=8 HEAD)" != "$expected_head" ]]; then
  echo "STOP: HEAD no longer matches current-state reconciliation checkpoint $expected_head."
  exit 2
fi

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/classify-semantic-history-context-optimization-scope\.sh$|^ M scripts/classify-semantic-history-context-optimization-scope\.sh$' ||
  true
)"

if [[ -n "$unexpected" ]]; then
  echo "STOP: unexpected working-tree changes exist:"
  printf '%s\n' "$unexpected"
  exit 2
fi

echo "CURRENT_STATE_RECONCILIATION_CHECKPOINT=CONFIRMED"

echo
echo "=== VERIFY GOVERNING RECONCILIATION ==="

grep -nE \
  'CURRENT_STATE_RECONCILIATION=|COMPLETE|CURRENT_SEMANTIC_RANKING=|CURRENT_REPOSITORY_CONTROLLED_POST_RETRIEVAL_TOKEN_BUDGET=|CURRENT_HYBRID_CONTEXT_OPTIMIZATION=|CURRENT_MODEL_RUNTIME_CONTEXT_OPTIMIZATION=|CURRENT_BOUNDED_HISTORY_WINDOW_OPTIMIZATION=|NEXT_ACTION=|CLASSIFY_SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION_SCOPE' \
  scripts/reconcile-semantic-history-context-optimization-current-state.sh

echo "GOVERNING_RECONCILIATION=CONFIRMED"

echo
echo "=== VERIFY EXISTING FOUNDATION REMAINS DISTINCT FROM OPTIMIZATION ==="

grep -nE \
  'bounded|authority|contamination|selectedHistory|ranking|token|retrieval window|project-context' \
  docs/architecture/SEMANTIC_HISTORY_SELECTION_OBJECTIVES.md \
  docs/architecture/SEMANTIC_HISTORY_REPOSITORY_READINESS.md \
  | head -260 || true

echo
echo "=== SCOPE CLASSIFICATION ==="

cat <<'MAP'
MILESTONE=
  SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION

MILESTONE_STATUS=
  ACTIVE_SCOPE_CLASSIFICATION

EXISTING_FOUNDATION=
  PRESERVE

EXISTING_FOUNDATION_INCLUDES=
  PROJECT_AND_CONVERSATION_SCOPED_HISTORY_RETRIEVAL
  BOUNDED_CHRONOLOGICAL_RETRIEVAL
  AUTHORITY_EVALUATION
  CONTAMINATION_EVALUATION
  ADMISSION_BASED_SELECTION
  SELECTED_HISTORY
  CHRONOLOGY_PRESERVATION
  LINEAGE_AND_METADATA_PRESERVATION
  INPUT_IMMUTABILITY
  CONVERSATION_CONTEXT_RUNTIME
  OLLAMA_SELECTED_HISTORY_CONSUMPTION

OPTIMIZATION_SCOPE=
  SEMANTIC_HISTORY_RANKING
  TOKEN_BUDGET_BEHAVIOR
  HYBRID_CONTEXT_RELATIONSHIP
  MODEL_RUNTIME_CONTEXT_BOUNDARY
  BOUNDED_HISTORY_WINDOW_OPTIMIZATION

SEMANTIC_HISTORY_RANKING_STATUS=
  INVESTIGATION_REQUIRED

SEMANTIC_HISTORY_RANKING_QUESTION=
  DETERMINE_WHETHER_COMPARATIVE_SEMANTIC_RANKING_IS_REQUIRED_AFTER_AUTHORITY_AND_CONTAMINATION_ADMISSION

TOKEN_BUDGET_STATUS=
  INVESTIGATION_REQUIRED

TOKEN_BUDGET_QUESTION=
  DETERMINE_WHETHER_REPOSITORY_CONTROLLED_TOKEN_BUDGETING_IS_REQUIRED_AFTER_HISTORY_SELECTION

HYBRID_CONTEXT_STATUS=
  INVESTIGATION_REQUIRED

HYBRID_CONTEXT_QUESTION=
  DETERMINE_WHETHER_CONVERSATION_HISTORY_AND_PROJECT_CONTEXT_REQUIRE_COORDINATED_OPTIMIZATION_WHILE_PRESERVING_DISTINCT_AUTHORITY_BOUNDARIES

MODEL_RUNTIME_CONTEXT_STATUS=
  INVESTIGATION_REQUIRED

MODEL_RUNTIME_CONTEXT_QUESTION=
  DETERMINE_WHETHER_MODEL_CONTEXT_CAPACITY_OR_RUNTIME_CONSTRAINTS_SHOULD_GOVERN_HISTORY_SELECTION_OR_BUDGETING

BOUNDED_HISTORY_WINDOW_STATUS=
  INVESTIGATION_REQUIRED

BOUNDED_HISTORY_WINDOW_QUESTION=
  DETERMINE_WHETHER_THE_CURRENT_BOUNDED_HISTORY_WINDOW_IS_ARCHITECTURALLY_JUSTIFIED_OR_REQUIRES_OPTIMIZATION

SCOPE_ORDERING_PRINCIPLE=
  CLASSIFY_REQUIREMENT_AND_OWNERSHIP_BEFORE_DESIGN_OR_IMPLEMENTATION

RANKING_IMPLEMENTATION=
  NOT_AUTHORIZED

TOKEN_BUDGET_IMPLEMENTATION=
  NOT_AUTHORIZED

HYBRID_CONTEXT_IMPLEMENTATION=
  NOT_AUTHORIZED

MODEL_RUNTIME_CONTEXT_IMPLEMENTATION=
  NOT_AUTHORIZED

HISTORY_WINDOW_CHANGE=
  NOT_AUTHORIZED

PROJECT_CONTEXT_RETRIEVAL_CONVERGENCE=
  NOT_AUTHORIZED

SELECTED_HISTORY_CONTRACT_CHANGE=
  NOT_AUTHORIZED

AUTHORITY_BOUNDARY_CHANGE=
  NOT_AUTHORIZED

CONTAMINATION_BOUNDARY_CHANGE=
  NOT_AUTHORIZED

PROMPT_CHANGE=
  NOT_AUTHORIZED

OLLAMA_INVOCATION_COUNT_CHANGE=
  NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CONCERN=
  SEPARATE_AND_DEFERRED

PRODUCTION_GENERATION_POLICY=
  UNCHANGED

IMPLEMENTATION_AUTHORIZED=
  NO

IMPLEMENTATION_STARTED=
  NO

PRODUCTION_CHANGE=
  NONE

SCOPE_CLASSIFICATION=
  COMPLETE

NEXT_ACTION=
  DISCOVER_SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION_PHASE_AND_CORRIDOR_MAP
MAP

echo
echo "=== VERIFY CLASSIFICATION-ONLY CHANGE SURFACE ==="

changed="$(
  git diff --name-only |
  grep -vE '^scripts/classify-semantic-history-context-optimization-scope\.sh$' ||
  true
)"

if [[ -n "$changed" ]]; then
  echo "STOP: files outside scope-classification surface changed:"
  printf '%s\n' "$changed"
  exit 2
fi

echo "CLASSIFICATION_ONLY_CHANGE_SURFACE_CONFIRMED"

echo
echo "=== DIFF CHECK ==="
git diff --check
