#!/usr/bin/env bash
set -euo pipefail

echo "=== CLASSIFY REGRESSION RUNNER DEPENDENCY BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor e734a7b7 HEAD
test -z "$(git status --porcelain)"

grep -q '"tsx":' package.json
if grep -q '"vitest":' package.json; then
  echo "STOP: vitest unexpectedly declared in package.json."
  exit 2
fi

cat <<'MAP'
REGRESSION_RUNNER_ATTEMPT=
STOPPED_BEFORE_TEST_EXECUTION

CAUSE=
VITEST_NOT_DECLARED_OR_INSTALLED_IN_REPOSITORY

USER_DECLINED_IMPLICIT_INSTALL=
YES

PACKAGE_INSTALL_AUTHORIZED=
NO

PRODUCTION_PROMOTION=
REMAINS_AT_00292763

TARGETED_TYPESCRIPT_VALIDATION=
PASS

DETERMINISTIC_REGRESSION_SUITE=
NOT_YET_EXECUTED

PRODUCTION_BEHAVIORAL_UNSEEDED_SAMPLE=
NOT_STARTED

CURRENT_PRODUCTION_CHANGE=
PROMPT_PRESENTATION_DEFAULT_PROMOTED_PENDING_REQUIRED_VALIDATION

SAFE_NEXT_ACTION=
IDENTIFY_EXISTING_REPOSITORY_TEST_EXECUTION_METHOD_WITHOUT_ADDING_DEPENDENCIES

PRODUCTION_CHANGE_THIS_STEP=
NONE
MAP
