#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="aa70c356a"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — EXECUTION ENVELOPE DURABILITY UNIT CLOSURE ==="
echo "MODE=EXECUTION"
echo "IMPLEMENTATION_COMMIT=fb8f7ba3e"
echo "VERIFICATION_COMMIT=aa70c356a"
echo

echo "=== VERIFIED CLOSED UNIT ==="
echo "EXECUTION_ENVELOPE_DURABILITY_UNIT_STATUS=CLOSED"
echo "DURABLE_REPO_PATH_BINDING=CLOSED_VERIFIED"
echo "DURABLE_EXPECTED_HEAD_BINDING=CLOSED_VERIFIED"
echo "DURABLE_ALLOWED_PATHS_BINDING=CLOSED_VERIFIED"
echo "DURABLE_FORBIDDEN_PATHS_BINDING=CLOSED_VERIFIED"
echo "DURABLE_SCOPE_CONSTRAINTS_BINDING=CLOSED_VERIFIED"
echo "EXACT_APPROVAL_ENVELOPE_PACKAGE_CORRELATION=CLOSED_VERIFIED"
echo "FAIL_CLOSED_EXECUTION_SCOPE_READER=CLOSED_VERIFIED"
echo "ENVELOPE_REPLAY_PREVENTION=CLOSED_VERIFIED"
echo "APPROVED_BRANCH_REUSE=CLOSED_VERIFIED"
echo

echo "=== PRESERVED BOUNDARIES ==="
echo "PRODUCTION_DB_USED_BY_TESTS=NO"
echo "REAL_GIT_EFFECTS_PERFORMED=NO"
echo "ROUTE_IMPLEMENTATION_CHANGED=NO"
echo "ROUTE_MOUNT_CHANGED=NO"
echo "PRODUCTION_REACHABILITY_CHANGED=NO"
echo "GIT_EFFECT_CHANGED=NO"
echo "GENERIC_CADE_AUTHORITY_CHANGED=NO"
echo "GENERIC_SHELL_AUTHORITY_CHANGED=NO"
echo "GENERIC_MUTATION_AUTHORITY_CHANGED=NO"
echo "SCHEDULER_OR_AUTONOMY_CHANGED=NO"
echo

echo "=== AUTHORIZATION CONTINUITY ==="
echo "UNMOUNTED_DEDICATED_EXECUTION_ROUTE_IMPLEMENTATION_AUTHORIZED=YES"
echo "UNMOUNTED_DEDICATED_EXECUTION_ROUTE_IMPLEMENTATION_AUTHORIZATION_REMAINS_VALID=YES"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "ROUTE_IMPLEMENTATION_MAY_RESUME=YES"
echo

echo "=== CORRIDOR / PHASE STATE ==="
echo "CORRIDOR_6_STATUS=OPEN_UNMOUNTED_DEDICATED_EXECUTION_ROUTE_IMPLEMENTATION_READY_TO_RESUME"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=RESUME_PREVIOUSLY_AUTHORIZED_UNMOUNTED_DEDICATED_EXECUTION_ROUTE_IMPLEMENTATION_AND_TARGETED_TESTS"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
