#!/usr/bin/env bash
set -euo pipefail

echo "=== CLOSE PRODUCTION RELIABILITY VALIDATION AND RELIABLE PRODUCTION COLLABORATION MILESTONE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor acdf019f HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/close-production-reliability-validation-and-reliable-production-collaboration-milestone\.sh$|^ M scripts/close-production-reliability-validation-and-reliable-production-collaboration-milestone\.sh$' ||
  true
)"
test -z "$unexpected"

readiness="scripts/classify-reliable-production-collaboration-milestone-closure-readiness.sh"
test -f "$readiness"

grep -q 'MILESTONE_CLOSURE_READINESS=' "$readiness"
grep -q '^READY_ON_CURRENT_REPOSITORY_EVIDENCE$' \
  <(awk '/MILESTONE_CLOSURE_READINESS=/{getline; print}' "$readiness")

grep -q 'CORRIDOR_5_STATUS=' "$readiness"
grep -q '^READY_FOR_CLOSURE$' \
  <(awk '/CORRIDOR_5_STATUS=/{getline; print}' "$readiness")

grep -q 'UNRESOLVED_MILESTONE_BLOCKER=' "$readiness"
grep -q '^NONE_ESTABLISHED$' \
  <(awk '/UNRESOLVED_MILESTONE_BLOCKER=/{getline; print}' "$readiness")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION
PHASE_1=
STARTING_BOUNDARY_AND_RELIABILITY_BASELINE
PHASE_1_STATUS=
CLOSED
PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION
PHASE_2_STATUS=
CLOSED
PHASE_3=
PRODUCTION_RELIABILITY_VALIDATION_AND_MILESTONE_CLOSURE
PHASE_3_CORRIDOR_1=
RELIABILITY_CONTRACT_RECONCILIATION
PHASE_3_CORRIDOR_1_STATUS=
CLOSED
PHASE_3_CORRIDOR_2=
PRODUCTION_BEHAVIORAL_RELIABILITY_CONFIRMATION
PHASE_3_CORRIDOR_2_STATUS=
CLOSED
PHASE_3_CORRIDOR_3=
FAIL_CLOSED_AND_PROVENANCE_CONTRACT_CONFIRMATION
PHASE_3_CORRIDOR_3_STATUS=
CLOSED
PHASE_3_CORRIDOR_4=
ARCHITECTURAL_INVARIANT_CONFIRMATION
PHASE_3_CORRIDOR_4_STATUS=
CLOSED
PHASE_3_CORRIDOR_5=
MILESTONE_CLOSURE_READINESS
PHASE_3_CORRIDOR_5_STATUS=
CLOSED
PHASE_3_FINAL_RESULT=
MILESTONE_LEVEL_PRODUCTION_RELIABILITY_VALIDATED_WITH_ARCHITECTURAL_AND_FAIL_CLOSED_CONTRACTS_PRESERVED
PHASE_3_STATUS=
CLOSED
RELIABILITY_TARGET=
SATISFIED_ON_TESTED_PRODUCTION_SURFACE
PRODUCTION_INTERVENTION=
EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION_AS_PRODUCTION_DEFAULT
POST_PROMOTION_BEHAVIORAL_RESULT=
10_OF_10_SEMANTIC_PASS
UNSUPPORTED_PROVENANCE_FAILURES=
0_OF_10
FAIL_CLOSED_OR_RUNTIME_REJECTIONS=
0_OF_10
DETERMINISTIC_REGRESSION=
127_OF_127_PASS
FAIL_CLOSED_VALIDATION=
PRESERVED
SUPPORT_PROVENANCE_CONTRACT=
PRESERVED
ARCHITECTURAL_INVARIANTS=
PRESERVED
ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=
PRESERVED
MODEL=
UNCHANGED
GENERATION_POLICY=
UNCHANGED
RETRY_OR_SECOND_MODEL_CALL=
NONE
ADDITIONAL_RELIABILITY_INTERVENTION_REQUIRED=
NO_CURRENT_EVIDENCE_SUPPORTED_REQUIREMENT
UNRESOLVED_MILESTONE_BLOCKER=
NONE_ESTABLISHED
FINAL_CLOSURE_DR=
20260816_214938
FINAL_CLOSURE_DR_PROTECTS_READINESS_COMMIT=
acdf019f
NEW_PRODUCTION_CHANGE=
NONE
MILESTONE_STATUS=
CLOSED
NEXT_ACTION=
CLASSIFY_NEXT_CANONICAL_MILESTONE_FROM_REPOSITORY_EVIDENCE
MAP
