#!/usr/bin/env bash
set -euo pipefail

echo "=== CLOSE INTERVENTION SELECTION CORRIDOR AND PHASE 2 ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 21b967ec HEAD
test -z "$(git status --porcelain)"

readiness="scripts/classify-selected-intervention-sufficiency-and-phase-2-closure-readiness.sh"
test -f "$readiness"

grep -q 'CORRIDOR_5_STATUS=' "$readiness"
grep -q '^READY_FOR_CLOSURE$' \
  <(awk '/CORRIDOR_5_STATUS=/{getline; print}' "$readiness")

grep -q 'PHASE_2_CLOSURE_READINESS=' "$readiness"
grep -q '^READY$' \
  <(awk '/PHASE_2_CLOSURE_READINESS=/{getline; print}' "$readiness")

grep -q 'ADDITIONAL_INTERVENTION_REQUIRED=' "$readiness"
grep -q '^NO_CURRENT_EVIDENCE_SUPPORTED_REQUIREMENT$' \
  <(awk '/ADDITIONAL_INTERVENTION_REQUIRED=/{getline; print}' "$readiness")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

CORRIDOR_1_STATUS=
CLOSED_WITH_SUCCESSFUL_PRODUCTION_REMEDY

CORRIDOR_2=
GENERATION_CONTROL_AND_SAMPLING_POLICY

CORRIDOR_2_STATUS=
NOT_REQUIRED_AFTER_SUCCESSFUL_HIGHER_PRIORITY_INTERVENTION

CORRIDOR_3=
MODEL_CAPABILITY

CORRIDOR_3_STATUS=
NOT_REQUIRED_AFTER_SUCCESSFUL_HIGHER_PRIORITY_INTERVENTION

CORRIDOR_4=
BOUNDED_GENERATION_INPUT_CONDITIONS

CORRIDOR_4_STATUS=
NOT_REQUIRED_AFTER_SUCCESSFUL_HIGHER_PRIORITY_INTERVENTION

CORRIDOR_5=
INTERVENTION_SELECTION_AND_IMPLEMENTATION_READINESS

CORRIDOR_5_STATUS=
CLOSED

SELECTED_PRODUCTION_INTERVENTION=
EXPLICIT_PARENT_CHILD_PRESENTATION_SEPARATION_AS_PRODUCTION_DEFAULT

SELECTED_INTERVENTION_IMPLEMENTATION=
COMPLETE

SELECTED_INTERVENTION_VALIDATION=
COMPLETE

DETERMINISTIC_REGRESSION=
127_OF_127_PASS

POST_PROMOTION_PRODUCTION_BEHAVIORAL_VALIDATION=
10_OF_10_SEMANTIC_PASS

POST_PROMOTION_UNSUPPLIED_SUPPORT_FAILURES=
0_OF_10

POST_PROMOTION_FAIL_CLOSED_OR_RUNTIME_REJECTIONS=
0_OF_10

SEMANTIC_RELIABILITY_DESPITE_OUTPUT_VARIANCE=
ESTABLISHED_ON_TESTED_PRODUCTION_SURFACE

FAIL_CLOSED_VALIDATION=
PRESERVED

SUPPORT_PROVENANCE_CONTRACT=
PRESERVED

SELECTED_CONTEXT_SEGMENT_CONTRACT=
PRESERVED

STRUCTURED_RESPONSE_SCHEMA=
PRESERVED

MODEL=
UNCHANGED

GENERATION_POLICY=
UNCHANGED

RETRY_OR_SECOND_MODEL_CALL=
NONE

ONE_WORKFLOW_ONE_OLLAMA_INVOCATION=
PRESERVED

ADDITIONAL_INTERVENTION_REQUIRED=
NO_CURRENT_EVIDENCE_SUPPORTED_REQUIREMENT

PHASE_2_FINAL_RESULT=
SUCCESSFUL_BOUNDED_PRODUCTION_PROMPT_PRESENTATION_INTERVENTION_IMPLEMENTED_AND_VALIDATED

PHASE_2_STATUS=
CLOSED

NEW_PRODUCTION_CHANGE=
NONE

NEXT_ACTION=
CLASSIFY_RELIABLE_PRODUCTION_COLLABORATION_SUCCESSOR_PHASE_BOUNDARY
MAP
