#!/usr/bin/env bash
set -euo pipefail

echo "=== CLOSE PRODUCTION BEHAVIORAL RELIABILITY CONFIRMATION AND ENTER FAIL-CLOSED AND PROVENANCE CONTRACT CONFIRMATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor d5b61f3e HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/close-production-behavioral-reliability-confirmation-and-enter-fail-closed-and-provenance-contract-confirmation\.sh$|^ M scripts/close-production-behavioral-reliability-confirmation-and-enter-fail-closed-and-provenance-contract-confirmation\.sh$' ||
  true
)"
test -z "$unexpected"

corridor2="scripts/classify-production-behavioral-reliability-confirmation-sufficiency.sh"
test -f "$corridor2"

grep -q 'CORRIDOR_2_STATUS=' "$corridor2"
grep -q '^READY_FOR_CLOSURE$' \
  <(awk '/CORRIDOR_2_STATUS=/{getline; print}' "$corridor2")

grep -q 'BEHAVIORAL_RELIABILITY_CONFIRMATION=' "$corridor2"
grep -q '^SUFFICIENT_ON_CURRENT_EVIDENCE$' \
  <(awk '/BEHAVIORAL_RELIABILITY_CONFIRMATION=/{getline; print}' "$corridor2")

grep -q 'ADDITIONAL_VALIDATION_GAP=' "$corridor2"
grep -q '^NONE_ESTABLISHED$' \
  <(awk '/ADDITIONAL_VALIDATION_GAP=/{getline; print}' "$corridor2")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_3=
PRODUCTION_RELIABILITY_VALIDATION_AND_MILESTONE_CLOSURE

CORRIDOR_2=
PRODUCTION_BEHAVIORAL_RELIABILITY_CONFIRMATION

CORRIDOR_2_RESULT=
ORDINARY_UNSEEDED_PRODUCTION_BEHAVIOR_CONFIRMED_RELIABLE_ON_CURRENT_TESTED_SURFACE

SEMANTIC_PASSES=
10_OF_10

UNSUPPORTED_PROVENANCE_FAILURES=
0_OF_10

FAIL_CLOSED_OR_RUNTIME_REJECTIONS=
0_OF_10

SEMANTIC_RELIABILITY_DESPITE_OUTPUT_VARIANCE=
ESTABLISHED_ON_TESTED_PRODUCTION_SURFACE

ADDITIONAL_BEHAVIORAL_SAMPLE_REQUIRED=
NO_CURRENT_EVIDENCE_SUPPORTED_REQUIREMENT

ADDITIONAL_VALIDATION_GAP=
NONE_ESTABLISHED

CORRIDOR_2_STATUS=
CLOSED

ACTIVE_CORRIDOR=
FAIL_CLOSED_AND_PROVENANCE_CONTRACT_CONFIRMATION

CORRIDOR_3_PURPOSE=
CONFIRM_FAIL_CLOSED_VALIDATION_SUPPORT_PROVENANCE_AND_SELECTED_CONTEXT_SEGMENT_BOUNDARIES_REMAIN_PRESERVED

NEW_PRODUCTION_CHANGE=
NONE

IMPLEMENTATION_AUTHORIZED=
NO_NEW_IMPLEMENTATION

NEXT_ACTION=
CLASSIFY_FAIL_CLOSED_AND_PROVENANCE_CONTRACT_CONFIRMATION
MAP
