#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="4666c33ed"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — EXECUTION APPROVAL TRANSITION UNIT CLOSURE ==="
echo "MODE=COLLABORATION"
echo "IMPLEMENTATION_COMMIT=63d56ec48"
echo "VERIFICATION_COMMIT=4666c33ed"
echo
echo "APPROVAL_PERSISTENCE_IMPLEMENTED=YES"
echo "USER_OWNED_APPROVAL_WRITE_IMPLEMENTED=YES"
echo "FAIL_CLOSED_READER_IMPLEMENTED=YES"
echo "APPROVAL_COMPILER_IMPLEMENTED=YES"
echo "TARGETED_TESTS_PASS=YES"
echo "TYPECHECK_PASS=YES"
echo "PRODUCTION_CALLER_ESTABLISHED=NO"
echo "PRODUCTION_REACHABILITY_CHANGED=NO"
echo "ROUTE_MOUNT_CHANGED=NO"
echo "GIT_EFFECT_CHANGED=NO"
echo
echo "EXECUTION_APPROVAL_TRANSITION_UNIT_STATUS=CLOSED"
echo "INPUT_B=AUTHORITATIVE_APPROVED_EXECUTION_APPROVAL"
echo "INPUT_B_STATUS=RESOLVED_AT_CAPABILITY_LAYER"
echo "CORRIDOR_6_STATUS=OPEN_PENDING_PRODUCTION_REACHABILITY_REASSESSMENT"
echo "PHASE_1_STATUS=ACTIVE"
echo
echo "=== NEXT BOUNDARY ==="
echo "NEXT_TARGET=MINIMUM_PRODUCTION_REACHABILITY_REASSESSMENT"
echo "DEDICATED_EXECUTION_ROUTE_AUTHORIZED=NO"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "NEXT_ACTION=REASSESS_WHETHER_THE_PREVIOUSLY_CLASSIFIED_DEDICATED_EXECUTION_ROUTE_IS_NOW_THE_MINIMUM_SAFE_REACHABILITY_SURFACE"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
