#!/usr/bin/env bash
set -euo pipefail

echo "=== CLOSE CONVERSATION ENGINE GENERATION STABILITY MILESTONE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor bd2974f9 HEAD

closure="scripts/classify-current-phase-3-generation-stability-closure-readiness.sh"
test -f "$closure"

echo "=== VERIFY CLOSURE READINESS ==="

grep -q 'MILESTONE_CAN_CLOSE=' "$closure"
grep -q '^YES$' <(grep -A1 'MILESTONE_CAN_CLOSE=' "$closure" | tail -1 | tr -d '[:space:]')
grep -q 'PHASE_3_CLOSURE_READINESS=' "$closure"
grep -q '^READY$' <(grep -A1 'PHASE_3_CLOSURE_READINESS=' "$closure" | tail -1 | tr -d '[:space:]')
grep -q 'CORRIDOR_6_CLOSURE_READINESS=' "$closure"
grep -q '^ESTABLISHED$' <(grep -A1 'CORRIDOR_6_CLOSURE_READINESS=' "$closure" | tail -1 | tr -d '[:space:]')

echo "CLOSURE_READINESS=CONFIRMED"

echo
echo "=== VERIFY CURRENT PRODUCTION BASELINE ==="

if grep -qE \
  'validationGenerationSeed|temperature:|top_p:|top_k:|seed:' \
  server/matilda-chat-workflow.ts
then
  echo "STOP: production workflow contains explicit generation control."
  exit 2
fi

production_call_count="$(grep -c 'await ollamaChat(message' server/matilda-chat-workflow.ts || true)"
test "$production_call_count" -eq 1

echo "CURRENT_PRODUCTION_GENERATION_POLICY=UNCHANGED_UNCONFIGURED_UNSEEDED"
echo "CURRENT_PRODUCTION_OLLAMA_INVOCATIONS_PER_WORKFLOW=ONE"
echo "PRODUCTION_CHANGE=NONE"

cat <<'MAP'
MILESTONE=
CONVERSATION_ENGINE_GENERATION_STABILITY

MILESTONE_STATUS=
COMPLETE

PHASE_1=
PRODUCTION_GENERATION_STABILITY_CHARACTERIZATION

PHASE_1_STATUS=
COMPLETE

PHASE_1_RESULT=
MATERIAL_UNSEEDED_GENERATION_INSTABILITY_ESTABLISHED

PHASE_2=
GENERATION_POLICY_AND_CONTROL_BOUNDARY

PHASE_2_STATUS=
COMPLETE

PHASE_2_RESULT=
PRODUCTION_GENERATION_POLICY_DEFERRED
PRODUCTION_POLICY_UNCHANGED

PHASE_3=
PRODUCTION_STABILITY_VALIDATION_AND_CLOSURE

PHASE_3_STATUS=
COMPLETE

PHASE_3_CORRIDOR_1=
PRODUCTION_STABILITY_CONTRACT
COMPLETE

PHASE_3_CORRIDOR_2=
UNSEEDED_BEHAVIORAL_VALIDATION
COMPLETE

PHASE_3_CORRIDOR_3=
FAIL_CLOSED_CONTRACT_PRESERVATION
COMPLETE

PHASE_3_CORRIDOR_4=
SINGLE_OLLAMA_INVOCATION
COMPLETE

PHASE_3_CORRIDOR_5=
PRODUCTION_REGRESSION_VALIDATION
COMPLETE

PHASE_3_CORRIDOR_6=
GENERATION_STABILITY_CLOSURE
COMPLETE

FINAL_PRODUCTION_STABILITY_CLASSIFICATION=
UNSTABLE

CURRENT_PHASE_3_SAMPLE=
TOTAL_RUNS=10
SEMANTIC_PASS_RUNS=0
FAIL_CLOSED_OR_RUNTIME_REJECTION_RUNS=10
SEMANTIC_FAILURE_RUNS=0
UNIQUE_EXACT_OUTPUT_FINGERPRINTS=1

FAIL_CLOSED_CONTRACT=
PRESERVED

SINGLE_OLLAMA_INVOCATION=
PRESERVED

DETERMINISTIC_REGRESSION_SET=
7_OF_7_TEST_FILES_PASS
37_OF_37_ASSERTIONS_PASS

PRODUCTION_RUNTIME_REGRESSION=
NOT_ESTABLISHED_ON_SELECTED_DETERMINISTIC_SURFACE

UNQUALIFIED_PRODUCTION_STABLE=
NO

UNRESOLVED_PRODUCTION_CONDITION=
GENERATION_INSTABILITY_REMAINS

UNRESOLVED_CONDITION_DISPOSITION=
DEFERRED_PRODUCTION_POLICY_CONCERN

PRODUCTION_GENERATION_POLICY_PROMOTION=
NOT_AUTHORIZED

FIXED_SEED_PROMOTION=
NOT_AUTHORIZED

VALIDATOR_RELAXATION=
NOT_AUTHORIZED

RETRY_OR_MULTI_INVOCATION=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

PRODUCTION_IMPLEMENTATION_AUTHORIZED=
NO

PRODUCTION_GENERATION_POLICY_CHANGE_AUTHORIZED=
NO

PRODUCTION_GENERATION_POLICY=
UNCHANGED_UNCONFIGURED_UNSEEDED

PRODUCTION_CHANGE=
NONE

GENERATION_STABILITY_MILESTONE=
COMPLETE_WITH_PRODUCTION_GENERATION_INSTABILITY_EXPLICITLY_ESTABLISHED

NEXT_ACTION=
RUN_FINAL_DR_FOR_GENERATION_STABILITY_MILESTONE
MAP
