#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 — REASONING STATUS PRODUCTION BEHAVIOR CLOSURE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor a770ef39 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/close-phase-3-reasoning-status-production-behavior\.sh$|^ M scripts/close-phase-3-reasoning-status-production-behavior\.sh$' ||
  true
)"
test -z "$unexpected"

npx tsx --test scripts/utils/ollamaChat.explanation-status.test.ts
npx tsx --test scripts/utils/ollamaChat.reasoning-status-surfacing.test.ts
bash scripts/guard-ollama-response-contract.sh
git diff --check

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
PHASE_3_STATUS=CLOSED_BOUNDED

CORRIDOR_1=CLASSIFICATION_RULE
CORRIDOR_1_STATUS=CLOSED

CORRIDOR_2=BEHAVIOR_VALIDATION
CORRIDOR_2_STATUS=DEFERRED_WITH_EXPLICIT_UNRESOLVED_BEHAVIORAL_RELIABILITY_LIMIT

CORRIDOR_3=SURFACING_CONTRACT
CORRIDOR_3_STATUS=CLOSED
CORRIDOR_3_DR=20260818_100454

CORRIDOR_4=PRODUCTION_VALIDATION_AND_CLOSURE
CORRIDOR_4_STATUS=CLOSED

CLASSIFICATION_CONTRACT=PASS
SURFACING_CONTRACT=PASS
PRODUCTION_CONTRACT_INTEGRITY=VALIDATED
RESPONSE_CONTRACT_GUARD=PASS
INVESTIGATION_LIFECYCLE_GUARD=PASS
SINGLE_OLLAMA_INVOCATION=PRESERVED
FAIL_CLOSED_VALIDATION=PRESERVED
PRODUCTION_VALIDATION_SEED=ABSENT
VISIBLE_REASONING_STATUS_LABEL=NO

MODEL_BEHAVIORAL_RELIABILITY=NOT_ESTABLISHED
BEHAVIORAL_RELIABILITY_LIMIT=CARRIED_FORWARD_EXPLICITLY
FOURTH_MODEL_VALIDATION_ATTEMPT=NOT_RUN
REASONING_STATUS_DEFECT_ESTABLISHED=NO
FAIL_CLOSED_VALIDATOR_MALFUNCTION_ESTABLISHED=NO

FULL_BEHAVIORAL_RELIABILITY_CLOSURE=NOT_CLAIMED
BOUNDED_PHASE_3_CLOSURE=COMPLETE
PRODUCTION_CHANGE=NONE
DR_NOW=YES
NEXT_ACTION=COMMIT_PHASE_3_BOUNDED_CLOSURE_AND_RUN_SINGLE_CANONICAL_DR
MAP
