#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=0e896566' \
  'ISSUE_RESOLVED=NO' \
  'COMPARISON_CONTRACT=DEFINED' \
  'IMPLEMENTATION_READY=YES' \
  'IMPLEMENTATION_STARTED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'USER_AUTHORIZATION_REQUIRED=YES' \
  'NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION'

printf '\n=== AUTHORIZED SCOPE IF APPROVED ===\n'
printf '%s\n' \
  'SURFACE=NEW_VALIDATION_ONLY_RUNNER_ONLY' \
  'UNSEEDED_ARM=10_RUNS' \
  'CONTROLLED_ARM=10_RUNS' \
  'CONTROLLED_SEED=424242' \
  'PRODUCTION_FILE_MUTATION=NONE' \
  'DATABASE_WRITE=NONE' \
  'RETRY=NONE'

printf '\n=== RESOLUTION STATUS ===\n'
printf '%s\n' \
  'ISSUE_RESOLVED=NO' \
  'REASON=EXPERIMENT_HAS_NOT_BEEN_AUTHORIZED_OR_RUN'

printf '\n=== WORKTREE ===\n'
git status --short
