#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=7e038357' \
  'ISSUE_RESOLVED=NO' \
  'COMPARISON_CONTRACT=DEFINED' \
  'IMPLEMENTATION_READY=YES' \
  'IMPLEMENTATION_STARTED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'USER_AUTHORIZATION_REQUIRED=YES' \
  'NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION'

printf '\n=== BOUNDED SCOPE IF AUTHORIZED ===\n'
printf '%s\n' \
  'SURFACE=NEW_VALIDATION_ONLY_RUNNER_ONLY' \
  'UNSEEDED_ARM=10_RUNS' \
  'CONTROLLED_ARM=10_RUNS' \
  'CONTROLLED_SEED=424242' \
  'CAUSAL_VARIABLE=validationGenerationSeed_ONLY' \
  'DATABASE_WRITE=NONE' \
  'PRODUCTION_FILE_MUTATION=NONE' \
  'RETRY=NONE'

printf '\n=== RESOLUTION STATUS ===\n'
printf '%s\n' \
  'ISSUE_RESOLVED=NO' \
  'REASON=IMPLEMENTATION_REMAINS_UNAUTHORIZED'

printf '\n=== WORKTREE ===\n'
git status --short
