#!/usr/bin/env bash
set -euo pipefail

echo "=== DEFINE PROMPT PRESENTATION DIAGNOSTIC COMPARISON BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 196ef6c3 HEAD

risk="scripts/classify-prompt-presentation-complexity-parent-child-identity-risk.sh"
ollama="scripts/utils/ollamaChat.ts"

for artifact in "$risk" "$ollama"; do
  test -f "$artifact"
  echo "PRESENT=$artifact"
done

echo
echo "=== VERIFY CURRENT INVESTIGATION STATE ==="
grep -q 'CORRIDOR_1_STATUS=' "$risk"
grep -q '^ACTIVE$' <(awk '/CORRIDOR_1_STATUS=/{getline; print}' "$risk")
grep -q 'NEXT_ACTION=' "$risk"
grep -q '^DEFINE_PROMPT_PRESENTATION_DIAGNOSTIC_COMPARISON_BOUNDARY$' \
  <(awk '/NEXT_ACTION=/{getline; print}' "$risk")
echo "CURRENT_INVESTIGATION_STATE=CONFIRMED"

echo
echo "=== VERIFY CURRENT SEMANTIC CONTRACT SURFACES ==="
grep -q 'selectedContextSegments records semantic project-context admission; supportSourceReferences records support provenance' "$ollama"
grep -q 'For project_context_excerpt support, use only a Source identity explicitly shown under Bounded project context evidence' "$ollama"
grep -q 'Ollama returned a project-context support reference that was not supplied in this invocation' "$ollama"
grep -q 'Ollama returned project-context support without selecting a supplied child segment for that parent' "$ollama"
echo "SEMANTIC_CONTRACT_SURFACES=CONFIRMED"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

INVESTIGATION_UNIT=
PROMPT_PRESENTATION_DIAGNOSTIC_COMPARISON_BOUNDARY

DIAGNOSTIC_CLASS=
NON_PRODUCTION_VALIDATION_ONLY_PRESENTATION_COMPARISON

DIAGNOSTIC_QUESTION=
DOES_REDUCING_PARENT_CHILD_IDENTITY_PRESENTATION_COMPLEXITY_MATERIALLY_REDUCE_UNSUPPLIED_PROJECT_CONTEXT_SUPPORT_REFERENCE_FAILURES

CONTROL_CONDITION=
CURRENT_PRODUCTION_EQUIVALENT_PROMPT_PRESENTATION

EXPERIMENTAL_CONDITION=
SEMANTICALLY_EQUIVALENT_PRESENTATION_WITH_PARENT_SUPPORT_IDENTITY_AND_CHILD_SELECTION_IDENTITY_MORE_EXPLICITLY_SEPARATED

ONLY_ALLOWED_DIAGNOSTIC_VARIABLE=
PROMPT_PRESENTATION_STRUCTURE

MUST_REMAIN_IDENTICAL_BETWEEN_CONTROL_AND_EXPERIMENT=
USER_MESSAGE
PROJECT_CONTEXT_EXCERPTS
PROJECT_CONTEXT_SEGMENT_CANDIDATES
CONVERSATION_HISTORY
PRIOR_INVESTIGATION_LIFECYCLE_CONTEXT
STRUCTURED_RESPONSE_SCHEMA
SUPPORT_PROVENANCE_SEMANTIC_RULE
SELECTED_CONTEXT_SEGMENT_SEMANTIC_RULE
FAIL_CLOSED_VALIDATION
MODEL
OLLAMA_ENDPOINT
ONE_INVOCATION_PER_RUN
VALIDATION_GENERATION_CONTROL_STATE

SEMANTIC_CONTRACT_CHANGE=
NOT_ALLOWED

SUPPORT_PROVENANCE_RULE_CHANGE=
NOT_ALLOWED

VALIDATOR_CHANGE=
NOT_ALLOWED

MODEL_CHANGE=
NOT_ALLOWED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_ALLOWED

RETRY_OR_SECOND_MODEL_CALL=
NOT_ALLOWED

PRODUCTION_PROMPT_CHANGE=
NOT_ALLOWED

DIAGNOSTIC_PRESENTATION_CHANGE=
ALLOWED_ONLY_ON_VALIDATION_SURFACE

PRIMARY_OBSERVATION=
VALID_OR_INVALID_PROJECT_CONTEXT_SUPPORT_PROVENANCE

SECONDARY_OBSERVATIONS=
SEMANTIC_ACCEPTANCE_RESULT
SELECTED_CONTEXT_SEGMENT_VALIDITY
EXACT_OUTPUT_FINGERPRINT_FOR_OBSERVABILITY_ONLY

SUCCESS_INTERPRETATION_BOUNDARY=
A_MEASURABLE_IMPROVEMENT_IN_VALID_SUPPORT_PROVENANCE_UNDER_PRESENTATION_ONLY_CHANGE_WOULD_SUPPORT_PRESENTATION_STRUCTURE_AS_A_CONTRIBUTING_FACTOR

NON_SUCCESS_INTERPRETATION_BOUNDARY=
NO_MEANINGFUL_IMPROVEMENT_WOULD_WEAKEN_THE_PRESENTATION_COMPLEXITY_HYPOTHESIS_AND_SHIFT_ATTENTION_TO_OTHER_GENERATION_LAYER_INTERVENTION_CLASSES

CAUSAL_LIMIT=
EVEN_A_POSITIVE_DIAGNOSTIC_RESULT_WOULD_NOT_BY_ITSELF_AUTHORIZE_A_PRODUCTION_PROMPT_CHANGE

SAMPLE_SIZE=
NOT_YET_ESTABLISHED

FIXED_OR_UNSEEDED_DIAGNOSTIC_MODE=
NOT_YET_ESTABLISHED

RUNNER_IMPLEMENTATION=
NOT_AUTHORIZED_BY_THIS_CLASSIFICATION

DIAGNOSTIC_IMPLEMENTATION_READINESS=
READY_FOR_BOUNDED_RUNNER_DESIGN

PRODUCTION_CHANGE=
NONE

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

CORRIDOR_1_STATUS=
ACTIVE

NEXT_ACTION=
DESIGN_BOUNDED_PROMPT_PRESENTATION_DIAGNOSTIC_RUNNER
MAP
