#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=16ea9dab' \
  'ISSUE_RESOLVED=NO' \
  'MODE=COLLABORATION_EXPERIMENT_DEFINITION' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'TARGET=DEFINE_BOUNDED_VALIDATION_ONLY_CONTROL_COMPARISON'

printf '\n=== COMPARISON CONTRACT ===\n'
printf '%s\n' \
  'EXPERIMENT_CLASS=VALIDATION_ONLY' \
  'CAUSAL_VARIABLE=validationGenerationSeed_ONLY' \
  'UNSEEDED_ARM_VALIDATION_GENERATION_SEED=ABSENT' \
  'CONTROLLED_ARM_VALIDATION_GENERATION_SEED=424242' \
  'SAME_MODEL=REQUIRED' \
  'SAME_PROMPT=REQUIRED' \
  'SAME_USER_MESSAGE=REQUIRED' \
  'SAME_CONTEXT=REQUIRED' \
  'SAME_VALIDATORS=REQUIRED' \
  'SAME_TIMEOUT=REQUIRED' \
  'PRODUCTION_RUNTIME_MUTATION=NONE'

printf '\n=== REQUEST IDENTITY BOUNDARY ===\n'
printf '%s\n' \
  'SOURCE_REQUEST=EXACT_CURRENT_DASHBOARD_REQUEST' \
  'REQUEST_CONTEXT_SNAPSHOT=REQUIRED' \
  'DIAGNOSTIC_RUN_PERSISTENCE=PROHIBITED' \
  'REASON=EACH_ARM_MUST_RECEIVE_IDENTICAL_CONTEXT_WITHOUT_PRIOR_RUNS_MUTATING_HISTORY'

printf '\n=== SAMPLE BOUNDARY ===\n'
printf '%s\n' \
  'UNSEEDED_SAMPLE_COUNT=10' \
  'CONTROLLED_SAMPLE_COUNT=10' \
  'FAILED_RUN_RETRY=NO' \
  'CONTROLLED_SEED_CONSTANT=424242'

printf '\n=== OBSERVATIONS ===\n'
printf '%s\n' \
  'OBSERVE_STRUCTURED_ACCEPTANCE=YES' \
  'OBSERVE_SUPPORT_PROVENANCE_ACCEPTANCE=YES' \
  'OBSERVE_SELECTED_CONTEXT_ACCEPTANCE=YES' \
  'OBSERVE_TIMEOUT=YES' \
  'OBSERVE_SEMANTIC_OUTPUT=YES' \
  'OBSERVE_EXACT_OUTPUT_FINGERPRINT=YES' \
  'OBSERVE_FAILURE_CLASS=YES'

printf '\n=== ACCEPTANCE BOUNDARY ===\n'
printf '%s\n' \
  'PRIMARY_CONTROL_CRITERION=CONTROLLED_ARM_10_OF_10_STRUCTURED_AND_PROVENANCE_ACCEPTANCE' \
  'COMPARATIVE_CRITERION=CONTROLLED_ARM_HAS_FEWER_FAILURES_THAN_UNSEEDED_ARM' \
  'SEMANTIC_CRITERION=NO_MATERIAL_SEMANTIC_CONTRACT_REGRESSION' \
  'REPEATABILITY_ALONE_SUFFICIENT=NO' \
  'SINGLE_SUCCESS_SUFFICIENT=NO' \
  'PRODUCTION_PROMOTION_AUTHORIZED_BY_THIS_TEST=NO'

printf '\n=== PRESERVATION BOUNDARY ===\n'
printf '%s\n' \
  'REPLY_CONTRACT=PRESERVE' \
  'SELECTED_CONTEXT_CONTRACT=PRESERVE' \
  'SUPPORT_PROVENANCE_CONTRACT=PRESERVE' \
  'INVESTIGATION_LIFECYCLE_CONTRACT=PRESERVE' \
  'DURABLE_INTERPRETATION_CONTRACT=PRESERVE' \
  'FAIL_CLOSED_CONTRACT=PRESERVE' \
  'ONE_OLLAMA_INVOCATION_PER_RUN=PRESERVE'

printf '\n=== AUTHORIZATION BOUNDARY ===\n'
printf '%s\n' \
  'PRODUCTION_SEED_AUTHORIZED=NO' \
  'MODEL_CHANGE_AUTHORIZED=NO' \
  'RETRY_CHANGE_AUTHORIZED=NO' \
  'TIMEOUT_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_CHANGE_AUTHORIZED=NO' \
  'PROMPT_CHANGE_AUTHORIZED=NO' \
  'PRODUCTION_GENERATION_POLICY_CHANGE_AUTHORIZED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO'

printf '\n=== DISPOSITION ===\n'
printf '%s\n' \
  'COMPARISON_CONTRACT=DEFINED' \
  'EXPERIMENT_IMPLEMENTATION=NOT_STARTED' \
  'PRODUCTION_GENERATION_POLICY=UNCHANGED_UNCONFIGURED_UNSEEDED' \
  'NEXT_ACTION=CLASSIFY_BOUNDED_DASHBOARD_GENERATION_CONTROL_COMPARISON_IMPLEMENTATION_READINESS'

printf '\n=== WORKTREE ===\n'
git status --short
