#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=7a430fc6' \
  'MODE=COLLABORATION' \
  'ISSUE_RESOLVED=NO' \
  'ROOT_CAUSE_CLASSIFIED=YES' \
  'ROOT_CAUSE=PROMPT_OUTPUT_CONSTRAINT_GAP_FOR_EMPTY_CONVERSATION_HISTORY' \
  'FAIL_CLOSED_VALIDATOR=CORRECT_AND_MUST_BE_PRESERVED' \
  'PRODUCTION_FIX_AUTHORIZED=NO' \
  'TARGET=DEFINE_BOUNDED_PROMPT_CONTRACT_FIX_AND_VALIDATION_BOUNDARY'

printf '\n=== VERIFIED FAILURE CONDITIONS ===\n'
printf '%s\n' \
  'PERSISTED_PRIOR_TURN_COUNT=0' \
  'SUPPLIED_CONVERSATION_SOURCE_ID_COUNT=0' \
  'MODEL_RETURNED_CONVERSATION_SUPPORT_REFERENCE=YES' \
  'RETURNED_REFERENCE_WAS_SUPPLIED=NO' \
  'VALIDATOR_REJECTED_REFERENCE=YES' \
  'HTTP_RESULT=503' \
  'OLLAMA_SERVICE=HEALTHY' \
  'MODEL_AVAILABLE=YES'

printf '\n=== BOUNDED FIX CONTRACT ===\n'
printf '%s\n' \
  'CHANGE_OWNER=scripts/utils/ollamaChat.ts_PROMPT_CONSTRUCTION' \
  'REQUIRED_RULE_1=EXPLICITLY_PRESENT_ALLOWED_CONVERSATION_SUPPORT_SOURCE_IDENTIFIERS' \
  'REQUIRED_RULE_2=WHEN_ALLOWED_CONVERSATION_SUPPORT_SET_IS_EMPTY_MODEL_MUST_RETURN_NO_CONVERSATION_TURN_SUPPORT_REFERENCES' \
  'REQUIRED_RULE_3=CURRENT_USER_MESSAGE_MUST_NOT_BE_REPRESENTED_AS_PRIOR_CONVERSATION_SUPPORT' \
  'REQUIRED_RULE_4=MODEL_MUST_CONTINUE_USING_EXACT_SUPPLIED_SOURCE_TURN_IDS_WHEN_HISTORY_EXISTS' \
  'VALIDATOR_CHANGE=NO' \
  'VALIDATOR_WEAKENING=PROHIBITED' \
  'PERSISTENCE_CHANGE=NO' \
  'AUTHORITY_CHANGE=NO' \
  'GENERATION_POLICY_CHANGE=NO' \
  'RETRY_CHANGE=NO' \
  'MODEL_CHANGE=NO'

printf '\n=== REQUIRED VALIDATION CASES ===\n'
printf '%s\n' \
  'CASE_1=EMPTY_HISTORY_REQUEST_RETURNS_WITHOUT_UNSUPPLIED_CONVERSATION_REFERENCE' \
  'CASE_2=EMPTY_HISTORY_SUPPORT_REFERENCES_CONTAIN_NO_CONVERSATION_TURN_REFERENCE' \
  'CASE_3=NONEMPTY_HISTORY_MAY_REFERENCE_ONLY_EXACT_SUPPLIED_SOURCE_TURN_IDS' \
  'CASE_4=INVENTED_CONVERSATION_SOURCE_ID_STILL_FAILS_CLOSED' \
  'CASE_5=PROJECT_CONTEXT_SUPPORT_VALIDATION_REMAINS_UNCHANGED' \
  'CASE_6=ONE_WORKFLOW_ONE_OLLAMA_INVOCATION_REMAINS_PRESERVED'

printf '\n=== IMPLEMENTATION BOUNDARY ===\n'
printf '%s\n' \
  'IMPLEMENTATION_SCOPE=BOUNDED_PROMPT_CONTRACT_CHANGE_ONLY' \
  'IMPLEMENTATION_READY=YES' \
  'IMPLEMENTATION_STARTED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'NEXT_ACTION=AWAIT_EXPLICIT_IMPLEMENTATION_AUTHORIZATION'

printf '\n=== WORKTREE ===\n'
git status --short
