#!/usr/bin/env bash
set -euo pipefail

echo "=== DESIGN BOUNDED UNSEEDED EXPERIMENTAL PRESENTATION VALIDATION ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor b2b56017 HEAD
test -z "$(git status --porcelain)"

readiness="scripts/classify-prompt-presentation-production-remedy-readiness.sh"
runner="scripts/run-bounded-prompt-presentation-diagnostic.ts"
ollama="scripts/utils/ollamaChat.ts"

for file in "$readiness" "$runner" "$ollama"; do
  test -f "$file"
done

grep -q 'PRODUCTION_REMEDY_READINESS=' "$readiness"
grep -q '^NOT_READY$' <(awk '/PRODUCTION_REMEDY_READINESS=/{getline; print}' "$readiness")
grep -q 'NEXT_VALIDATION_CLASS=' "$readiness"
grep -q '^NON_PRODUCTION_PRODUCTION_EQUIVALENT_UNSEEDED_PRESENTATION_VALIDATION$' \
  <(awk '/NEXT_VALIDATION_CLASS=/{getline; print}' "$readiness")

grep -q 'validationPromptPresentationVariant' "$ollama"
grep -q 'explicit_parent_child_separation' "$ollama"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

DESIGN_UNIT=
BOUNDED_UNSEEDED_EXPERIMENTAL_PRESENTATION_VALIDATION

VALIDATION_CLASS=
NON_PRODUCTION_PRODUCTION_EQUIVALENT_UNSEEDED_PRESENTATION_VALIDATION

GOVERNING_QUESTION=
DOES_THE_EXPERIMENTAL_PARENT_CHILD_PRESENTATION_REMAIN_RELIABLE_WHEN_THE_FIXED_DIAGNOSTIC_SEED_IS_REMOVED

TEST_ARM=
EXPERIMENTAL_PRESENTATION_ONLY

PRESENTATION_VARIANT=
EXPLICIT_PARENT_CHILD_SEPARATION

GENERATION_SEED=
ABSENT

GENERATION_CONTROL_STATE=
ORDINARY_UNSEEDED

RUN_COUNT=
10

EXECUTION_MODE=
SEQUENTIAL

ONE_INVOCATION_PER_RUN=
PRESERVED

RETRY=
NONE

USER_MESSAGE=
IDENTICAL_TO_FIXED_SEED_DIAGNOSTIC

PROJECT_CONTEXT_EXCERPTS=
IDENTICAL_TO_FIXED_SEED_DIAGNOSTIC

PROJECT_CONTEXT_SEGMENT_CANDIDATES=
IDENTICAL_TO_FIXED_SEED_DIAGNOSTIC

STRUCTURED_RESPONSE_SCHEMA=
UNCHANGED

SEMANTIC_CONTRACT=
UNCHANGED

SUPPORT_PROVENANCE_RULES=
UNCHANGED

SELECTED_CONTEXT_SEGMENT_RULES=
UNCHANGED

FAIL_CLOSED_VALIDATION=
UNCHANGED

MODEL=
UNCHANGED

ENDPOINT=
UNCHANGED

ONLY_MATERIAL_DIFFERENCE_FROM_SUCCESSFUL_EXPERIMENTAL_DIAGNOSTIC=
VALIDATION_GENERATION_SEED_REMOVED

PRIMARY_METRIC=
SEMANTIC_PASS_RATE

PRIMARY_FAILURE_METRIC=
UNSUPPLIED_PROJECT_CONTEXT_SUPPORT_REFERENCE_COUNT

SECONDARY_METRICS=
FAIL_CLOSED_OR_RUNTIME_REJECTION_COUNT
UNIQUE_EXACT_OUTPUT_FINGERPRINT_COUNT

SUCCESS_THRESHOLD=
10_OF_10_SEMANTIC_PASS_WITH_ZERO_UNSUPPLIED_SUPPORT_FAILURES

PARTIAL_SUCCESS=
SEMANTIC_PASS_RATE_MATERIALLY_ABOVE_EXISTING_UNSEEDED_PRODUCTION_EQUIVALENT_BASELINE_BUT_BELOW_10_OF_10

NON_SUCCESS=
NO_MATERIAL_RELIABILITY_IMPROVEMENT_OR_PERSISTENT_UNSUPPLIED_SUPPORT_FAILURES

INTERPRETATION_BOUNDARY=
SUCCESS_SUPPORTS_UNSEEDED_RELIABILITY_OF_THE_EXPERIMENTAL_PRESENTATION_ON_THIS_BOUNDED_SURFACE_BUT_DOES_NOT_ALONE_AUTHORIZE_PRODUCTION_PROMPT_REPLACEMENT

PRODUCTION_REGRESSION_VALIDATION_AFTER_SUCCESS=
STILL_REQUIRED

PRODUCTION_PROMPT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

VALIDATION_IMPLEMENTATION=
NOT_STARTED

PRODUCTION_CHANGE=
NONE

CORRIDOR_1_STATUS=
ACTIVE

DESIGN_STATUS=
COMPLETE

NEXT_ACTION=
CLASSIFY_BOUNDED_UNSEEDED_PRESENTATION_VALIDATION_IMPLEMENTATION_READINESS
MAP
