#!/usr/bin/env bash
set -euo pipefail

echo "=== DISCOVER SEMANTIC HISTORY CONTEXT OPTIMIZATION PHASE AND CORRIDOR MAP ==="

echo
echo "=== BASELINE ==="
echo "BRANCH=$(git branch --show-current)"
echo "HEAD=$(git rev-parse --short=8 HEAD)"
echo "COMMIT=$(git log -1 --format=%s)"
git status --short

echo
echo "=== VERIFY SCOPE-CLASSIFICATION CHECKPOINT ==="

expected_head="5ff4d05f"

if [[ "$(git rev-parse --short=8 HEAD)" != "$expected_head" ]]; then
  echo "STOP: HEAD no longer matches semantic-history scope-classification checkpoint $expected_head."
  exit 2
fi

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/discover-semantic-history-context-optimization-phase-and-corridor-map\.sh$|^ M scripts/discover-semantic-history-context-optimization-phase-and-corridor-map\.sh$' ||
  true
)"

if [[ -n "$unexpected" ]]; then
  echo "STOP: unexpected working-tree changes exist:"
  printf '%s\n' "$unexpected"
  exit 2
fi

echo "SCOPE_CLASSIFICATION_CHECKPOINT=CONFIRMED"

echo
echo "=== VERIFY GOVERNING SCOPE ==="

grep -nE \
  'OPTIMIZATION_SCOPE=|SEMANTIC_HISTORY_RANKING_STATUS=|TOKEN_BUDGET_STATUS=|HYBRID_CONTEXT_STATUS=|MODEL_RUNTIME_CONTEXT_STATUS=|BOUNDED_HISTORY_WINDOW_STATUS=|SCOPE_ORDERING_PRINCIPLE=|IMPLEMENTATION_AUTHORIZED=|NEXT_ACTION=|DISCOVER_SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION_PHASE_AND_CORRIDOR_MAP' \
  scripts/classify-semantic-history-context-optimization-scope.sh

echo "GOVERNING_SCOPE=CONFIRMED"

echo
echo "=== VERIFY ARCHITECTURAL INVESTIGATION FOUNDATION ==="

for file in \
  docs/architecture/SEMANTIC_HISTORY_INVENTORY.md \
  docs/architecture/SEMANTIC_HISTORY_SELECTION_OBJECTIVES.md \
  docs/architecture/SEMANTIC_HISTORY_BEHAVIORAL_VALIDATION.md \
  docs/architecture/SEMANTIC_HISTORY_REPOSITORY_READINESS.md
do
  [[ -f "$file" ]] || {
    echo "STOP: required architecture document missing: $file"
    exit 2
  }
  echo "FOUND=$file"
done

echo "ARCHITECTURAL_INVESTIGATION_FOUNDATION=CONFIRMED"

echo
echo "=== DISCOVER PHASE AND CORRIDOR MAP ==="

cat <<'MAP'
MILESTONE=
  SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION

MILESTONE_STATUS=
  ACTIVE

PHASE_1=
  SEMANTIC_SELECTION_OPTIMIZATION

PHASE_1_PURPOSE=
  DETERMINE_WHETHER_AND_HOW_ADMITTED_CONVERSATION_HISTORY_REQUIRES_COMPARATIVE_SEMANTIC_SELECTION_BEYOND_EXISTING_AUTHORITY_AND_CONTAMINATION_FILTERING

PHASE_1_CORRIDORS=
  SEMANTIC_RANKING_REQUIREMENT
  SEMANTIC_RANKING_OWNERSHIP
  RANKING_INPUT_AND_OUTPUT_BOUNDARY
  CHRONOLOGY_AND_LINEAGE_PRESERVATION
  SEMANTIC_SELECTION_VALIDATION

PHASE_2=
  CONTEXT_BUDGET_AND_WINDOW_OPTIMIZATION

PHASE_2_PURPOSE=
  DETERMINE_WHETHER_REPOSITORY_CONTROLLED_CONTEXT_BUDGETING_IS_REQUIRED_AND_WHETHER_THE_EXISTING_BOUNDED_HISTORY_WINDOW_IS_ARCHITECTURALLY_JUSTIFIED

PHASE_2_CORRIDORS=
  TOKEN_BUDGET_REQUIREMENT
  TOKEN_BUDGET_OWNERSHIP
  HISTORY_WINDOW_JUSTIFICATION
  BUDGET_AND_WINDOW_INTERACTION
  CONTEXT_BUDGET_VALIDATION

PHASE_3=
  HYBRID_AND_MODEL_CONTEXT_OPTIMIZATION

PHASE_3_PURPOSE=
  DETERMINE_THE_RELATIONSHIP_BETWEEN_CONVERSATION_HISTORY_PROJECT_CONTEXT_AND_MODEL_RUNTIME_CONTEXT_WITHOUT_COLLAPSING_DISTINCT_AUTHORITY_OR_RETRIEVAL_BOUNDARIES

PHASE_3_CORRIDORS=
  HYBRID_CONTEXT_REQUIREMENT
  HISTORY_AND_PROJECT_CONTEXT_RELATIONSHIP
  MODEL_RUNTIME_CONTEXT_BOUNDARY
  CROSS_CONTEXT_PRIORITY_AND_PRESERVATION
  HYBRID_CONTEXT_VALIDATION

PHASE_4=
  OPTIMIZATION_INTEGRATION_AND_CLOSURE

PHASE_4_PURPOSE=
  VALIDATE_ANY_AUTHORIZED_OPTIMIZATION_AS_ONE_COHERENT_CONVERSATION_HISTORY_PREPARATION_SYSTEM_AND_CLOSE_THE_MILESTONE_WITH_EXPLICIT_DEFERRED_CONDITIONS

PHASE_4_CORRIDORS=
  INTEGRATED_OPTIMIZATION_BOUNDARY
  SELECTED_HISTORY_CONTRACT_PRESERVATION
  ONE_OLLAMA_INVOCATION_PRESERVATION
  DETERMINISTIC_REGRESSION_VALIDATION
  MILESTONE_CLOSURE_CLASSIFICATION

PHASE_ORDER=
  SEMANTIC_SELECTION_OPTIMIZATION
  CONTEXT_BUDGET_AND_WINDOW_OPTIMIZATION
  HYBRID_AND_MODEL_CONTEXT_OPTIMIZATION
  OPTIMIZATION_INTEGRATION_AND_CLOSURE

ORDERING_RATIONALE=
  SEMANTIC_SELECTION_REQUIREMENTS_MUST_BE_CLASSIFIED_BEFORE_BUDGETING_OR_WINDOW_POLICY
  BUDGET_AND_WINDOW_REQUIREMENTS_MUST_BE_CLASSIFIED_BEFORE_HYBRID_CONTEXT_COORDINATION
  HYBRID_AND_MODEL_CONTEXT_BOUNDARIES_MUST_BE_CLASSIFIED_BEFORE_INTEGRATED_OPTIMIZATION_VALIDATION
  IMPLEMENTATION_MUST_NOT_PRECEDE_REQUIREMENT_OWNERSHIP_AND_BOUNDARY_CLASSIFICATION

EXISTING_HISTORY_PREPARATION=
  PRESERVE

AUTHORITY_EVALUATION=
  PRESERVE

CONTAMINATION_EVALUATION=
  PRESERVE

SELECTED_HISTORY=
  PRESERVE_UNLESS_LATER_EXPLICITLY_AUTHORIZED

PROJECT_CONTEXT_RETRIEVAL=
  REMAINS_DISTINCT

PROJECT_CONTEXT_RETRIEVAL_CONVERGENCE=
  NOT_ASSUMED

SEMANTIC_RANKING_REQUIRED=
  NOT_YET_DETERMINED

TOKEN_BUDGET_REQUIRED=
  NOT_YET_DETERMINED

HISTORY_WINDOW_CHANGE_REQUIRED=
  NOT_YET_DETERMINED

HYBRID_CONTEXT_COORDINATION_REQUIRED=
  NOT_YET_DETERMINED

MODEL_RUNTIME_CONTEXT_CHANGE_REQUIRED=
  NOT_YET_DETERMINED

PRODUCTION_GENERATION_POLICY_CONCERN=
  SEPARATE_AND_DEFERRED

PRODUCTION_GENERATION_POLICY=
  UNCHANGED

IMPLEMENTATION_AUTHORIZED=
  NO

IMPLEMENTATION_STARTED=
  NO

PRODUCTION_CHANGE=
  NONE

PHASE_MAP=
  DISCOVERED

CORRIDOR_MAP=
  DISCOVERED

CURRENT_PHASE=
  PHASE_1_SEMANTIC_SELECTION_OPTIMIZATION

CURRENT_CORRIDOR=
  SEMANTIC_RANKING_REQUIREMENT

NEXT_ACTION=
  CLASSIFY_SEMANTIC_RANKING_REQUIREMENT
MAP

echo
echo "=== VERIFY DISCOVERY-ONLY CHANGE SURFACE ==="

changed="$(
  git diff --name-only |
  grep -vE '^scripts/discover-semantic-history-context-optimization-phase-and-corridor-map\.sh$' ||
  true
)"

if [[ -n "$changed" ]]; then
  echo "STOP: files outside phase-and-corridor discovery scope changed:"
  printf '%s\n' "$changed"
  exit 2
fi

echo "DISCOVERY_ONLY_CHANGE_SURFACE_CONFIRMED"

echo
echo "=== DIFF CHECK ==="
git diff --check
