#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 3 — SURFACING CONTRACT ENTRY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor fd0cfb2b HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/enter-phase-3-corridor-3-surfacing-contract\.sh$|^ M scripts/enter-phase-3-corridor-3-surfacing-contract\.sh$' ||
  true
)"
test -z "$unexpected"

grep -Fq 'Set explanationStatus to optional by default.' scripts/utils/ollamaChat.ts
grep -Fq "Set explanationStatus to recommended only when skipping supporting reasoning is likely to materially affect the user's next engineering decision." scripts/utils/ollamaChat.ts
grep -Fq 'Do not set explanationStatus to recommended merely because evidence exists, the work was substantial, or additional explanation is available.' scripts/utils/ollamaChat.ts

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION
CORRIDOR_2_DISPOSITION=DEFERRED_WITH_EXPLICIT_UNRESOLVED_BEHAVIORAL_RELIABILITY_LIMIT
CORRIDOR_2_MODEL_BEHAVIORAL_RELIABILITY=NOT_ESTABLISHED

CORRIDOR_3=SURFACING_CONTRACT
CORRIDOR_3_STATUS=ACTIVE
MODE=COLLABORATION
IMPLEMENTATION_AUTHORIZED=NO

ESTABLISHED_SEMANTICS=
OPTIONAL_DEFAULT__RECOMMENDED_ONLY_FOR_MATERIAL_NEXT_DECISION_IMPACT__EVIDENCE_VOLUME_OR_WORK_VOLUME_ALONE_DOES_NOT_TRIGGER_RECOMMENDED

SURFACING_QUESTION=
HOW_SHOULD_OPTIONAL_VERSUS_RECOMMENDED_AFFECT_THE_USER_VISIBLE_REPLY_WITHOUT_REINTRODUCING_A_MANDATORY_REASONING_STATUS_LABEL_OR_MAKING_COLLABORATION_HEAVIER

CANDIDATE_OPTIONAL_BEHAVIOR=
LEAD_WITH_THE_CONCISE_ANSWER_AND_INCLUDE_ONLY_SUPPORTING_REASONING_NEEDED_FOR_THE_IMMEDIATE_INTERACTION

CANDIDATE_RECOMMENDED_BEHAVIOR=
LEAD_WITH_THE_CONCISE_ANSWER_THEN_INCLUDE_ENOUGH_SUPPORTING_REASONING_TO_PRESERVE_THE_MATERIAL_ARCHITECTURAL_BOUNDARY_UNCERTAINTY_TRADEOFF_OR_EVIDENCE_INTERPRETATION_THAT_COULD_CHANGE_THE_USERS_NEXT_DECISION

MANDATORY_VISIBLE_REASONING_STATUS_LABEL=
NOT_ESTABLISHED_AND_HISTORICALLY_REJECTED

STATUS_FIELD_USER_VISIBLE_BY_DEFAULT=
NO

REQUIRED_CARRY_FORWARD_LIMIT=
DO_NOT_REPRESENT_OPTIONAL_OR_RECOMMENDED_AS_PRODUCTION_RELIABLE_UNTIL_CORRIDOR_2_BEHAVIORAL_VALIDATION_IS_UNBLOCKED_AND_COMPLETED

PRODUCTION_CHANGE=NONE
DR_NOW=NO

NEXT_ACTION=
INVESTIGATE_EXISTING_REPLY_COMPOSITION_AND_UI_CONSUMPTION_SURFACES_TO_CLASSIFY_THE_SMALLEST_SURFACING_CONTRACT_WITHOUT_IMPLEMENTATION
MAP
