#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=DELEGATION_WORKSPACE' \
  'MODE=COLLABORATION' \
  'CURRENT_CHECKPOINT=8a38f6c5' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'PURPOSE=FINALIZE_DELEGATION_WORKSPACE_CORRIDOR_MAP_FROM_REPOSITORY_EVIDENCE'

printf '\n=== RECONCILED CAPABILITY STATE ===\n'
printf '%s\n' \
  'APPROVAL_READ_MODEL_DECISION=APPROVE_CANONICAL_PACKAGE_ONLY' \
  'CANONICAL_APPROVAL_MUTATION=IMPLEMENTED' \
  'CANONICAL_APPROVAL_GRANTS_DELEGATION_AUTHORITY=NO' \
  'REQUEST_CHANGES_UI=PRESENT' \
  'REQUEST_CHANGES_PERSISTENCE=NOT_IMPLEMENTED' \
  'GOVERNANCE_DELEGATION_MUTATION=IMPLEMENTED' \
  'EXECUTIVE_INBOX_DELEGATION_ACTION=NOT_IMPLEMENTED' \
  'OPERATIONAL_INTAKE_AFTER_ASSIGNED_LIFECYCLE=IMPLEMENTED' \
  'OPERATIONAL_INTAKE_EXECUTION_AUTHORITY=FALSE' \
  'MISSION_CONTROL_GOVERNANCE_PROJECTION=ALREADY_IMPLEMENTED'

printf '\n=== FINAL CORRIDOR MAP ===\n'
printf '%s\n' \
  'CORRIDOR_1=REQUEST_CHANGES_PERSISTENCE' \
  'CORRIDOR_1_PURPOSE=MAKE_EXISTING_EXECUTIVE_REQUEST_CHANGES_CONTROL_AUTHORITATIVE_AND_DURABLE' \
  'CORRIDOR_2=EXECUTIVE_DELEGATION_DECISION' \
  'CORRIDOR_2_PURPOSE=CONNECT_EXECUTIVE_INBOX_TO_EXISTING_GOVERNANCE_DELEGATION_AUTHORITY_WITHOUT_IMPLYING_EXECUTION' \
  'CORRIDOR_3=DELEGATION_HANDOFF_VISIBILITY' \
  'CORRIDOR_3_PURPOSE=CONFIRM_AND_PRESENT_HANDOFF_FROM_EXECUTIVE_DECISION_TO_EXISTING_MISSION_CONTROL_GOVERNANCE_POSITION' \
  'CORRIDOR_4=DELEGATION_WORKSPACE_VALIDATION_AND_CLOSURE' \
  'CORRIDOR_4_PURPOSE=VALIDATE_DECISION_BOUNDARIES_FAIL_CLOSED_BEHAVIOR_AND_PHASE_INTEGRATION'

printf '\n=== REMOVED AS REDUNDANT OR UNSUPPORTED ===\n'
printf '%s\n' \
  'SEPARATE_DELEGATION_PERSISTENCE_CORRIDOR=NOT_REQUIRED_EXISTING_GOVERNANCE_DELEGATION_MUTATION_PRESENT' \
  'NEW_OPERATIONAL_INTAKE_CORRIDOR=NOT_REQUIRED_EXISTING_ASSIGNED_LIFECYCLE_HANDOFF_PRESENT' \
  'EXECUTION_AUTHORIZATION_CORRIDOR=OUT_OF_SCOPE' \
  'DEPARTMENT_OR_AGENT_ASSIGNMENT_CORRIDOR=OUT_OF_SCOPE_UNLESS_SEPARATELY_AUTHORIZED'

printf '\n=== GOVERNANCE BOUNDARIES ===\n'
printf '%s\n' \
  'APPROVAL_AND_DELEGATION=MUST_REMAIN_DISTINCT' \
  'DELEGATION_AND_EXECUTION=MUST_REMAIN_DISTINCT' \
  'REQUEST_CHANGES=MUST_NOT_GRANT_DOWNSTREAM_AUTHORITY' \
  'DELEGATION=MUST_USE_EXISTING_AUTHORITATIVE_GOVERNANCE_PATH' \
  'NEW_SEMANTIC_AUTHORITY=NO' \
  'SPECULATIVE_NEW_PERSISTENCE=PROHIBITED' \
  'IMPLEMENTATION_STARTED=NO'

printf '\n=== NEXT ACTION ===\n'
echo 'NEXT_CORRIDOR=REQUEST_CHANGES_PERSISTENCE'
echo 'NEXT_ACTION=INSPECT_REQUEST_CHANGES_PERSISTENCE_OWNERSHIP_AND_IMPLEMENTATION_BOUNDARY'

printf '\n=== WORKTREE ===\n'
git status --short
