#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="37d6ad09b"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — GOVERNANCE READ PROVENANCE DECISION GATE ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo
echo "GOVERNANCE_READ_IMPLEMENTATION_PRESENT=YES"
echo "GOVERNANCE_READ_TESTS_PASS=YES"
echo "PRIOR_AUTHORIZATION_RECORD_28bb23ea8=NON_AUTHORITATIVE"
echo "RECONCILIATION_COMMIT=c6d7db3bd"
echo "CURRENT_ROUTE_DEPENDS_ON_GOVERNANCE_READ_CHAIN=YES"
echo
echo "USER_DECISION_REQUIRED=YES"
echo "VALID_DECISION_1=RETAIN_AND_ACCEPT_EXISTING_GOVERNANCE_READ_UNIT"
echo "VALID_DECISION_2=ROLLBACK_OR_REPLACE_EXISTING_GOVERNANCE_READ_UNIT"
echo
echo "NO_DECISION_INFERRED_FROM_TERMINAL_OUTPUT=YES"
echo "NO_RETROACTIVE_AUTHORIZATION_CLAIMED=YES"
echo "NO_PRODUCTION_BINDING_OR_ROUTE_MOUNT_WORK_MAY_PROCEED_UNTIL_USER_DECISION=YES"
echo
echo "CORRIDOR_6_STATUS=ACTIVE_WAITING_ON_USER_GOVERNANCE_READ_PROVENANCE_DECISION"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=USER_MUST_EXPLICITLY_CHOOSE_RETAIN_OR_ROLLBACK_FOR_GOVERNANCE_READ_UNIT"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
