#!/usr/bin/env bash
set -euo pipefail

EXPECTED_HEAD="791e6ca26a84278a5e48d0756657958a590a985a"
CURRENT_HEAD="$(git rev-parse HEAD)"

echo "=== CORRIDOR 6 AUTHORIZATION HOLD ==="
echo "EXPECTED_HEAD=${EXPECTED_HEAD}"
echo "CURRENT_HEAD=${CURRENT_HEAD}"
test "${CURRENT_HEAD}" = "${EXPECTED_HEAD}"

echo "DEDICATED_ROUTE_MOUNTED=NO"
echo "PRODUCTION_REACHABILITY=NO"
echo "EXPLICIT_USER_CHAT_AUTHORIZATION_PRESENT=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CORRIDOR_6_STATUS=ACTIVE"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=AWAIT_EXPLICIT_USER_CHAT_AUTHORIZATION"
echo "PRODUCTION_CHANGE=NONE"
