#!/usr/bin/env bash
set -euo pipefail

echo "=== OPEN GENERATION LAYER INTERVENTION INVESTIGATION STARTING BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 5d7f2f67 HEAD

phase1="scripts/classify-reliable-production-collaboration-intervention-boundary.sh"
test -f "$phase1"

grep -q 'PHASE_1_STATUS=' "$phase1"
grep -q '^COMPLETE$' <(awk '/PHASE_1_STATUS=/{getline; print}' "$phase1")
grep -q 'NEXT_PHASE=' "$phase1"
grep -q '^GENERATION_LAYER_INTERVENTION_INVESTIGATION$' <(awk '/NEXT_PHASE=/{getline; print}' "$phase1")
grep -q 'NEXT_CORRIDOR=' "$phase1"
grep -q '^PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION$' <(awk '/NEXT_CORRIDOR=/{getline; print}' "$phase1")

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE_1=
STARTING_BOUNDARY_AND_RELIABILITY_BASELINE

PHASE_1_STATUS=
COMPLETE

PHASE_2=
GENERATION_LAYER_INTERVENTION_INVESTIGATION

PHASE_2_STATUS=
STARTING

PHASE_2_CORRIDOR_1=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

PHASE_2_CORRIDOR_2=
GENERATION_CONTROL_AND_SAMPLING_POLICY

PHASE_2_CORRIDOR_3=
MODEL_CAPABILITY

PHASE_2_CORRIDOR_4=
BOUNDED_GENERATION_INPUT_CONDITIONS

PHASE_2_CORRIDOR_5=
INTERVENTION_SELECTION_AND_IMPLEMENTATION_READINESS

PHASE_2_CORRIDOR_COUNT=
5

ACTIVE_CORRIDOR=
PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION

GOVERNING_FAILURE_OWNER=
MODEL_GENERATION_LAYER

EXACT_GENERATION_SUBCAUSE=
NOT_ESTABLISHED

GOVERNING_RELIABILITY_TARGET=
CONSISTENTLY_USABLE_ORDINARY_PRODUCTION_COLLABORATION_WITHOUT_SACRIFICING_SEMANTIC_OR_PROVENANCE_INTEGRITY

PRESERVE=
USER_INTENT_AUTHORITY
MATILDA_INTERPRETATION_AUTHORITY
REPLY_AND_DURABLE_INTERPRETATION_SEPARATION
WORKFLOW_OWNED_IEL_PERSISTENCE
CONVERSATION_CONTEXT_BOUNDARY
PROJECT_CONTEXT_PROVENANCE_BOUNDARY
PRIOR_INVESTIGATION_LIFECYCLE_CONTEXT_BOUNDARY
FAIL_CLOSED_STRUCTURED_RESPONSE_VALIDATION
UNSUPPORTED_PROVENANCE_REJECTION
ONE_USER_MESSAGE_TO_ONE_WORKFLOW
ONE_WORKFLOW_TO_ONE_OLLAMA_INVOCATION_BY_DEFAULT

PHASE_2_PURPOSE=
ISOLATE_THE_ACTIONABLE_GENERATION_LAYER_SUBCAUSE
COMPARE_EVIDENCE_SUPPORTED_INTERVENTION_CLASSES
SELECT_NO_REMEDY_UNTIL_ONE_IS_EVIDENCE_SUPPORTED
ESTABLISH_IMPLEMENTATION_READINESS_ONLY_AFTER_SEMANTIC_AND_ROLLBACK_BOUNDARIES_ARE_CLEAR

PROMPT_CHANGE=
NOT_AUTHORIZED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

VALIDATOR_CHANGE=
NOT_AUTHORIZED

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

NEXT_ACTION=
INVESTIGATE_PROMPT_AND_RESPONSE_CONTRACT_PRESENTATION
MAP
