#!/usr/bin/env bash
set -euo pipefail

echo "=== OPEN RELIABLE PRODUCTION COLLABORATION STARTING BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

NEW_EXPLICIT_PROGRAM_OBJECTIVE=
RELIABLE_DAY_TO_DAY_PRODUCTION_COLLABORATION_WITH_MATILDA

MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

MILESTONE_STATUS=
OPEN

PHASE_1=
STARTING_BOUNDARY_AND_RELIABILITY_BASELINE

PHASE_1_STATUS=
STARTING

PHASE_1_CORRIDOR_1=
COLLABORATION_RELIABILITY_CONTRACT

PHASE_1_CORRIDOR_2=
PRODUCTION_FAILURE_BASELINE

PHASE_1_CORRIDOR_3=
FAILURE_OWNERSHIP

PHASE_1_CORRIDOR_4=
CONSTRAINT_PRESERVATION

PHASE_1_CORRIDOR_5=
INTERVENTION_BOUNDARY

PHASE_1_CORRIDOR_COUNT=
5

ACTIVE_CORRIDOR=
COLLABORATION_RELIABILITY_CONTRACT

PREDECESSOR_PROGRAM_RECONCILIATION=
CLOSED

PREDECESSOR_GENERATION_STABILITY=
CLOSED_WITH_PRODUCTION_GENERATION_INSTABILITY_EXPLICITLY_ESTABLISHED

KNOWN_PRODUCTION_GENERATION_INSTABILITY=
PRESERVED_AS_GOVERNING_STARTING_EVIDENCE

FAIL_CLOSED_VALIDATION=
MUST_BE_PRESERVED

MATILDA_SEMANTIC_AUTHORSHIP=
MUST_BE_PRESERVED

ONE_WORKFLOW=
MUST_BE_PRESERVED_UNLESS_LATER_EVIDENCE_EXPLICITLY_ESTABLISHES_OTHERWISE

ONE_OLLAMA_INVOCATION=
MUST_BE_PRESERVED_UNLESS_LATER_EVIDENCE_EXPLICITLY_ESTABLISHES_OTHERWISE

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED

VALIDATOR_WEAKENING=
NOT_AUTHORIZED

RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED

MODEL_CHANGE=
NOT_AUTHORIZED

PROMPT_CHANGE=
NOT_AUTHORIZED

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

PHASE_1_PURPOSE=
DEFINE_THE_RELIABILITY_TARGET
PRESERVE_THE_EXISTING_STABILITY_EVIDENCE
CLASSIFY_CURRENT_FAILURE_OWNERSHIP
IDENTIFY_IMMUTABLE_INVESTIGATION_CONSTRAINTS
ESTABLISH_EVIDENCE_SUPPORTED_INTERVENTION_CLASSES_BEFORE_IMPLEMENTATION

NEXT_ACTION=
INVESTIGATE_COLLABORATION_RELIABILITY_CONTRACT
MAP
