#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — PREPARE BEHAVIOR VALIDATION ATTEMPT 2 ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"

cat <<'MAP'
ATTEMPT_1_RESULT=PRE_TARGET_FAIL_CLOSED_SELECTED_CONTEXT_REJECTION
ATTEMPT_1_CLASSIFICATION_RULE_RESULT=NOT_OBSERVED
ATTEMPT_2_STATUS=READY
REPOSITORY_SUPPORTED_FIXTURE_SHAPE=ESTABLISHED
FIXTURE_SOURCE=EXISTING_PASSING_PROJECT_CONTEXT_SEGMENT_CANDIDATE_PATTERN
REQUIRED_PARENT_CONTEXT=PROJECT_CONTEXT_EXCERPT
REQUIRED_CHILD_CONTEXT=PROJECT_CONTEXT_SEGMENT_CANDIDATE
CHILD_IDENTITY_RULE=RELATIVE_PATH_SOURCE_START_LINE_SOURCE_END_LINE_MUST_MATCH_SUPPLIED_CANDIDATE
FIXED_SEED_ROLE=DIAGNOSTIC_REPEATABILITY_ONLY_NOT_PRODUCTION_POLICY
PRODUCTION_VALIDATOR_CHANGE=NONE
PRODUCTION_PROMPT_CHANGE=NONE
STRUCTURED_SCHEMA_CHANGE=NONE
RETRY_POLICY_CHANGE=NONE
MODEL_INVOCATION_COUNT_CHANGE=NONE
DR_NOW=NO
NEXT_ACTION=PATCH_ONLY_THE_CORRIDOR_2_VALIDATION_HARNESS_TO_SUPPLY_A_VALIDATED_BOUNDED_CONTEXT_FIXTURE_THEN_RUN_ATTEMPT_2
MAP

printf '\n--- CURRENT ATTEMPT 1 HARNESS ---\n'
sed -n '1,220p' scripts/validate-phase-3-corridor-2-reasoning-status-behavior.ts

printf '\n--- CANONICAL PASSING FIXTURE REFERENCE ---\n'
sed -n '1,110p' scripts/run-bounded-prompt-presentation-diagnostic.ts

printf '\n--- SEEDED PASSING FIXTURE REFERENCE ---\n'
sed -n '1,120p' scripts/validate-adaptive-detail-mixed-content-seeded-live.ts
