#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=f1686b02' \
  'ISSUE_RESOLVED=NO' \
  'MODE=COLLABORATION_POLICY_REASSESSMENT' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'TARGET=REASSESS_PREVIOUS_NO_PRODUCTION_POLICY_DETERMINATION_AGAINST_NEW_LIVE_DASHBOARD_EVIDENCE'

printf '\n=== PRIOR PHASE 2 EVIDENCE ===\n'
git show --stat --oneline 11e70aa6 || true
git show --stat --oneline b0a84ebb || true
git show --stat --oneline c88ea891 || true
git show --stat --oneline b61e6f43 || true
git show --stat --oneline cfc6609e || true
git show --stat --oneline 08d9d38d || true

printf '\n=== PRIOR POLICY DETERMINATIONS ===\n'
grep -Rni --exclude-dir=node_modules --exclude-dir=.git \
  -E \
  'PRODUCTION_POLICY_NECESSITY|PRODUCTION_GENERATION_POLICY|validationGenerationSeed|REQUEST_SCOPED|NO_PRODUCTION_POLICY|SEMANTIC_PRESERVATION|UNCHANGED_UNCONFIGURED_UNSEEDED_GENERATION' \
  docs scripts 2>/dev/null | head -500

printf '\n=== NEW LIVE DASHBOARD EVIDENCE ===\n'
printf '%s\n' \
  'DIRECT_MODEL_AVAILABILITY=PASS' \
  'OLLAMA_SERVICE_HEALTH=PASS' \
  'LIVE_API_PATH=HAS_PASSED_AT_LEAST_ONCE' \
  'LIVE_DASHBOARD_PROXY_PATH=REACHES_BACKEND' \
  'OBSERVED_FAILURE_CLASS_1=INVALID_CONVERSATION_SUPPORT_PROVENANCE' \
  'OBSERVED_FAILURE_CLASS_2=INVALID_SELECTED_CONTEXT_SEGMENT' \
  'OBSERVED_FAILURE_CLASS_3=OLLAMA_CHAT_TIMEOUT' \
  'OBSERVED_FAILURE_CLASS_4=INVALID_PROJECT_CONTEXT_SUPPORT_PROVENANCE' \
  'RESTORED_PRE_FIX_RUNTIME_STILL_FAILS=YES' \
  'FAIL_CLOSED_VALIDATOR_MALFUNCTION_ESTABLISHED=NO' \
  'REFERENCE_SPECIFIC_PROMPT_FIX_ROOT_CAUSE=NO'

printf '\n=== CURRENT CONTROL SURFACE ===\n'
grep -n -A20 -B12 -E \
  'validationGenerationSeed|options:|seed|OLLAMA_CHAT_TIMEOUT_MS|AbortController' \
  scripts/utils/ollamaChat.ts

printf '\n=== REASSESSMENT ===\n'
printf '%s\n' \
  'PREVIOUS_PHASE_2_DETERMINATION=PRODUCTION_POLICY_NECESSITY_NOT_ESTABLISHED' \
  'NEW_EVIDENCE=MULTIPLE_USER_VISIBLE_503_FAILURES_ON_REAL_DASHBOARD_PATH' \
  'NEW_EVIDENCE_SCOPE=PRODUCTION_EQUIVALENT_USER_FACING_RUNTIME' \
  'PREVIOUS_NO_POLICY_DETERMINATION_REQUIRES_REOPENING=YES' \
  'PRODUCTION_POLICY_NECESSITY_NOW_ESTABLISHED=NOT_YET' \
  'CONTROL_INTERVENTION_NECESSITY_NOW_ESTABLISHED=NOT_YET' \
  'REASON=NEW_EVIDENCE_ESTABLISHES_OPERATIONAL_IMPACT_BUT_NOT_YET_WHICH_CONTROL_CAN_REDUCE_FAILURES_WITHOUT_SEMANTIC_REGRESSION' \
  'NEXT_HYPOTHESIS=CONTROLLED_GENERATION_CAN_REDUCE_INVALID_STRUCTURED_OUTPUT_WHILE_PRESERVING_SEMANTICS'

printf '\n=== SAFE INVESTIGATION BOUNDARY ===\n'
printf '%s\n' \
  'PRODUCTION_SEED_AUTHORIZED=NO' \
  'PRODUCTION_TEMPERATURE_AUTHORIZED=NO' \
  'PRODUCTION_TOP_P_AUTHORIZED=NO' \
  'PRODUCTION_TOP_K_AUTHORIZED=NO' \
  'MODEL_CHANGE_AUTHORIZED=NO' \
  'RETRY_CHANGE_AUTHORIZED=NO' \
  'TIMEOUT_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_CHANGE_AUTHORIZED=NO' \
  'VALIDATOR_WEAKENING_AUTHORIZED=NO' \
  'NEXT_TEST_CLASS=VALIDATION_ONLY_CONTROLLED_VS_UNSEEDED_COMPARISON_ON_EXACT_DASHBOARD_REQUEST'

printf '\n=== REQUIRED NEXT TEST ===\n'
printf '%s\n' \
  'TEST_REQUEST=EXACT_CURRENT_DASHBOARD_REQUEST' \
  'UNSEEDED_ARM=REQUIRED' \
  'CONTROLLED_SEED_ARM=REQUIRED' \
  'CONTROLLED_SEED=424242' \
  'SAME_MODEL=REQUIRED' \
  'SAME_PROMPT=REQUIRED' \
  'SAME_CONTEXT=REQUIRED' \
  'SAME_VALIDATORS=REQUIRED' \
  'COMPARE=HTTP_SUCCESS_STRUCTURED_ACCEPTANCE_SUPPORT_PROVENANCE_AND_SEMANTIC_OUTPUT' \
  'IMPLEMENTATION_STARTED=NO' \
  'NEXT_ACTION=DEFINE_BOUNDED_VALIDATION_ONLY_CONTROL_COMPARISON'

printf '\n=== WORKTREE ===\n'
git status --short
