#!/usr/bin/env bash
set -euo pipefail

echo "=== RECONCILE CURRENT DEFERRED WORK INVENTORY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 488c991a HEAD

current_inventory="scripts/reconcile-current-completed-runtime-capability-inventory.sh"
legacy="scripts/classify-deferred-work-inventory.sh"

test -f "$current_inventory"
test -f "$legacy"

echo "=== VERIFY CORRIDOR 1 CLOSURE ==="
grep -q 'CORRIDOR_1_STATUS=' "$current_inventory"
grep -q 'COMPLETE' "$current_inventory"
grep -q 'NEXT_CORRIDOR=' "$current_inventory"
grep -q 'DEFERRED_WORK_INVENTORY' "$current_inventory"
echo "CORRIDOR_1_CLOSURE=CONFIRMED"

echo
echo "=== VERIFY LEGACY DEFERRED INVENTORY ==="
grep -q 'DEFERRED_WORK_INVENTORY_STATUS=' "$legacy"
grep -q 'COMPLETE' "$legacy"
grep -q 'DEFERRED_PRODUCTION_GENERATION_INSTABILITY=' "$legacy"
grep -q 'SEMANTIC_HISTORY_RANKING=' "$legacy"
grep -q 'TOKEN_BUDGET_CONTROL=' "$legacy"
grep -q 'HISTORY_WINDOW_CHANGE=' "$legacy"
grep -q 'HYBRID_CONTEXT_COORDINATION=' "$legacy"
grep -q 'MODEL_RUNTIME_CONTEXT_CONFIGURATION=' "$legacy"
grep -q 'INTEGRATED_OPTIMIZATION_LAYER=' "$legacy"
grep -q 'CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION=' "$legacy"
grep -q 'RECOVERY_AND_CORRELATION_REFINEMENTS=' "$legacy"
grep -q 'PROMPT_EVOLUTION=' "$legacy"
echo "LEGACY_DEFERRED_INVENTORY=CONFIRMED"

echo
echo "=== RECONCILE STALE DEFERRED ITEMS ==="

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION

PHASE=
CURRENT_CAPABILITY_AND_DEFERRED_WORK_RECONCILIATION

CORRIDOR=
DEFERRED_WORK_INVENTORY

DEFERRED_PRODUCTION_GENERATION_INSTABILITY=
PRESENT_AS_KNOWN_CONDITION

PRODUCTION_RUNTIME_REGRESSION=
NOT_ESTABLISHED

SEMANTIC_HISTORY_RANKING=
REQUIREMENT_NOT_ESTABLISHED_AND_MILESTONE_CLOSED

TOKEN_BUDGET_CONTROL=
REQUIREMENT_NOT_ESTABLISHED_AND_MILESTONE_CLOSED

HISTORY_WINDOW_CHANGE=
REQUIREMENT_NOT_ESTABLISHED_AND_MILESTONE_CLOSED

HYBRID_CONTEXT_COORDINATION=
REQUIREMENT_NOT_ESTABLISHED_AND_MILESTONE_CLOSED

MODEL_RUNTIME_CONTEXT_CONFIGURATION=
CHANGE_REQUIREMENT_NOT_ESTABLISHED_AND_MILESTONE_CLOSED

INTEGRATED_OPTIMIZATION_LAYER=
REQUIREMENT_NOT_ESTABLISHED_AND_MILESTONE_CLOSED

CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION=
IMPLEMENTED_AND_VALIDATED
NO_LONGER_DEFERRED

EVALUATED_INTERPRETATIONS_SURFACING=
IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

CONTAMINATION_EVALUATIONS_SURFACING=
IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

INTERPRETATION_AUTHORITY_LIFECYCLE_STATE_SURFACING=
IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

RECONSTRUCTED_INVESTIGATION_LIFECYCLE_STATE_SURFACING=
IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

SELECTED_PRIOR_INVESTIGATION_LIFECYCLE_CONTEXT_SURFACING=
IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

RECOVERY_AND_CORRELATION_REFINEMENTS=
DEFERRED_REQUIREMENT_AND_PRIORITY_NOT_ESTABLISHED

PROMPT_EVOLUTION=
DEFERRED_REQUIREMENT_AND_PRIORITY_NOT_ESTABLISHED

MODEL_RUNTIME_CONTEXT_OPTIMIZATION=
REQUIREMENT_NOT_ESTABLISHED_AND_MILESTONE_CLOSED

TWENTY_TURN_WINDOW_OPTIMIZATION=
CHANGE_REQUIREMENT_NOT_ESTABLISHED_AND_MILESTONE_CLOSED

CURRENT_DEFERRED_WORK_INTERPRETATION=
The prior deferred-work inventory contained one stale runtime gap:
cross-turn Investigation Lifecycle transition validation.

That capability is now implemented and validated and must be removed from the
active deferred-gap set.

Semantic History optimization concerns were investigated through their own
completed milestone without establishing implementation requirements.

Production generation instability remains an explicit known deferred policy
condition and is not reopened here.

Remaining surfaced-vs-internal capabilities, recovery/correlation refinements,
and prompt evolution remain candidates for later gap classification only.
No implementation requirement or priority is established by this inventory.

DEFERRED_WORK_INVENTORY_CURRENTNESS=
CURRENT_AFTER_REMOVING_COMPLETED_CROSS_TURN_VALIDATION_AND_CLOSED_SEMANTIC_HISTORY_GAPS

CORRIDOR_2_STATUS=
COMPLETE

IMPLEMENTATION_REQUIREMENT_CREATED=
NO

PRIORITY_ASSIGNED=
NO

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_GENERATION_POLICY_REOPENED=
NO

PRODUCTION_CHANGE=
NONE

NEXT_CORRIDOR=
UNRESOLVED_CAPABILITY_GAP_CLASSIFICATION

NEXT_ACTION=
RECONCILE_UNRESOLVED_CAPABILITY_GAPS_CURRENTNESS
MAP
