#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="9cf879e57"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — EXECUTION ENVELOPE DURABILITY AUTHORIZATION ==="
echo "MODE=EXECUTION"
echo "EXECUTION_ENVELOPE_DURABILITY_IMPLEMENTATION_AUTHORIZED=YES"
echo
echo "AUTHORIZED_UNIT_1=DURABLE_REPO_PATH_BINDING"
echo "AUTHORIZED_UNIT_2=DURABLE_EXPECTED_HEAD_BINDING"
echo "AUTHORIZED_UNIT_3=DURABLE_ALLOWED_PATHS_BINDING"
echo "AUTHORIZED_UNIT_4=DURABLE_FORBIDDEN_PATHS_BINDING"
echo "AUTHORIZED_UNIT_5=DURABLE_SCOPE_CONSTRAINTS_BINDING"
echo "AUTHORIZED_UNIT_6=EXACT_ENVELOPE_AND_PACKAGE_LINEAGE_BINDING"
echo "AUTHORIZED_UNIT_7=FAIL_CLOSED_READ_ONLY_EXECUTION_SCOPE_READER"
echo "AUTHORIZED_UNIT_8=TARGETED_PERSISTENCE_AND_READER_TESTS"
echo
echo "USER_OWNED_EXECUTION_SCOPE_APPROVAL_REQUIRED=YES"
echo "EXISTING_GOVERNANCE_EXECUTION_APPROVAL_DOMAIN_REUSED=YES"
echo "PARALLEL_GENERAL_APPROVAL_SYSTEM=NO"
echo "CLIENT_SUPPLIED_RUNTIME_AUTHORITY=NO"
echo "CURRENT_GIT_HEAD_AS_IMPLICIT_AUTHORITY=NO"
echo "PROCESS_CWD_AS_IMPLICIT_AUTHORITY=NO"
echo "COMMIT_AUTHORITY_IMPLIES_PUSH=NO"
echo "REPLAY_ACROSS_ENVELOPES=PROHIBITED"
echo
echo "UNMOUNTED_EXECUTION_ROUTE_IMPLEMENTATION=SEPARATELY_AUTHORIZED_AND_REMAINS_PAUSED_UNTIL_DURABILITY_UNIT_VERIFIED"
echo "SERVER_INDEX_ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGES_AUTHORIZED=NO"
echo "REMOTE_PUSH_EFFECT_CHANGES_AUTHORIZED=NO"
echo "GENERIC_CADE_CHANGES_AUTHORIZED=NO"
echo "GENERIC_SHELL_AUTHORITY_AUTHORIZED=NO"
echo "GENERIC_MUTATION_AUTHORITY_AUTHORIZED=NO"
echo "SCHEDULER_OR_AUTONOMY_AUTHORIZED=NO"
echo
echo "CORRIDOR_6_STATUS=EXECUTION_ENVELOPE_DURABILITY_IMPLEMENTATION_AUTHORIZED"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=IMPLEMENT_BOUNDED_EXECUTION_ENVELOPE_DURABILITY_UNIT_AND_TARGETED_TESTS"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
