#!/usr/bin/env bash
set -euo pipefail

echo "=== RECONCILE CURRENT COMPLETED RUNTIME CAPABILITY INVENTORY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 37bceadd HEAD

milestone="scripts/classify-current-conversation-engine-program-reconciliation-milestone.sh"
legacy="scripts/classify-completed-runtime-capability-inventory.sh"

test -f "$milestone"
test -f "$legacy"

echo "=== VERIFY CURRENT MILESTONE BOUNDARY ==="
grep -q 'CURRENT_CANONICAL_MILESTONE=' "$milestone"
grep -q 'CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION' "$milestone"
grep -q 'PHASE_1_CORRIDOR_1=' "$milestone"
grep -q 'COMPLETED_RUNTIME_CAPABILITY_INVENTORY' "$milestone"
echo "CURRENT_MILESTONE_BOUNDARY=CONFIRMED"

echo
echo "=== VERIFY LEGACY INVENTORY SEMANTICS ==="
grep -q 'COMPLETED_RUNTIME_CAPABILITY_INVENTORY_STATUS=' "$legacy"
grep -q 'COMPLETE' "$legacy"
grep -q 'WORKFLOW_ORCHESTRATION=' "$legacy"
grep -q 'ONE_WORKFLOW_TO_ONE_OLLAMA_INVOCATION=' "$legacy"
grep -q 'INVESTIGATION_LIFECYCLE_RECONSTRUCTION=' "$legacy"
grep -q 'PRIOR_INVESTIGATION_LIFECYCLE_SCOPED_SELECTION=' "$legacy"
grep -q 'CONVERSATION_HISTORY_RETRIEVAL=' "$legacy"
grep -q 'SELECTED_HISTORY=' "$legacy"
grep -q 'CONVERSATION_CONTEXT_RUNTIME=' "$legacy"
grep -q 'PROJECT_CONTEXT_PROVENANCE_VALIDATION=' "$legacy"
grep -q 'FAIL_CLOSED_STRUCTURED_RESPONSE_VALIDATION=' "$legacy"
grep -q 'LIVING_DRAFT_DERIVATION_FROM_IEL=' "$legacy"
grep -q 'APPROVAL_PIPELINE=' "$legacy"
echo "LEGACY_INVENTORY_SEMANTICS=CONFIRMED"

echo
echo "=== VERIFY CURRENT REPRESENTATIVE RUNTIME SURFACES ==="
test -f server/matilda-chat-workflow.ts
test -f server/matilda-conversation-context-runtime.ts
test -f server/matilda-history-selection-runtime.ts
test -f scripts/utils/ollamaChat.ts

grep -q 'conversationContext.selectedHistory' server/matilda-chat-workflow.ts
grep -q 'priorInvestigationLifecycle' server/matilda-chat-workflow.ts
grep -q 'projectContextExcerpts' server/matilda-chat-workflow.ts
grep -q 'await[[:space:]]*ollamaChat(' server/matilda-chat-workflow.ts
grep -q 'selectedHistory' server/matilda-conversation-context-runtime.ts
grep -q 'investigation identity that does not match prior lifecycle context' scripts/utils/ollamaChat.ts

echo "CURRENT_REPRESENTATIVE_RUNTIME_SURFACES=CONFIRMED"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION

PHASE=
CURRENT_CAPABILITY_AND_DEFERRED_WORK_RECONCILIATION

CORRIDOR=
COMPLETED_RUNTIME_CAPABILITY_INVENTORY

WORKFLOW_ORCHESTRATION=
IMPLEMENTED

ONE_USER_MESSAGE_TO_ONE_WORKFLOW=
IMPLEMENTED

ONE_WORKFLOW_TO_ONE_OLLAMA_INVOCATION=
IMPLEMENTED

STRUCTURED_OLLAMA_RESPONSE_CONTRACT=
IMPLEMENTED

REPLY_AND_DURABLE_INTERPRETATION_SEPARATION=
IMPLEMENTED

WORKFLOW_OWNED_DURABLE_IEL_PERSISTENCE=
IMPLEMENTED

INVESTIGATION_LIFECYCLE_CURRENT_TURN_TRANSPORT=
IMPLEMENTED

INVESTIGATION_LIFECYCLE_RECONSTRUCTION=
IMPLEMENTED

PRIOR_INVESTIGATION_LIFECYCLE_SCOPED_SELECTION=
IMPLEMENTED

PRIOR_INVESTIGATION_LIFECYCLE_TYPED_CONTEXT_CHANNEL=
IMPLEMENTED

CROSS_TURN_INVESTIGATION_IDENTITY_CONTINUITY_VALIDATION=
IMPLEMENTED_AND_VALIDATED

CONVERSATION_HISTORY_RETRIEVAL=
IMPLEMENTED

PROJECT_AND_CONVERSATION_SCOPING=
IMPLEMENTED

BOUNDED_CHRONOLOGICAL_RETRIEVAL=
IMPLEMENTED

INTERPRETATION_AUTHORITY_EVALUATION=
IMPLEMENTED

CONTAMINATION_EVALUATION=
IMPLEMENTED

ADMISSION_BASED_HISTORY_SELECTION=
IMPLEMENTED

SELECTED_HISTORY=
IMPLEMENTED

SELECTED_HISTORY_CHRONOLOGY=
PRESERVED

SELECTED_HISTORY_LINEAGE_AND_METADATA=
PRESERVED

SELECTED_HISTORY_INPUT_IMMUTABILITY=
PRESERVED

CONVERSATION_CONTEXT_RUNTIME=
IMPLEMENTED

PROJECT_CONTEXT_EXCERPT_CHANNEL=
IMPLEMENTED

PROJECT_CONTEXT_PROVENANCE_VALIDATION=
IMPLEMENTED

PRIOR_LIFECYCLE_CONTEXT_SEPARATION=
IMPLEMENTED

OLLAMA_SELECTED_HISTORY_CONSUMPTION=
IMPLEMENTED

OLLAMA_PROJECT_CONTEXT_CONSUMPTION=
IMPLEMENTED

OLLAMA_PRIOR_LIFECYCLE_CONTEXT_CONSUMPTION=
IMPLEMENTED

ONE_OLLAMA_INVOCATION=
IMPLEMENTED

FAIL_CLOSED_STRUCTURED_RESPONSE_VALIDATION=
IMPLEMENTED

LIVING_DRAFT_DERIVATION_FROM_IEL=
IMPLEMENTED

APPROVAL_PIPELINE=
IMPLEMENTED

SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION=
CLOSED_WITH_NO_NEW_RUNTIME_OPTIMIZATION_REQUIREMENT_ESTABLISHED

GENERATION_STABILITY=
CLOSED_WITH_PRODUCTION_GENERATION_INSTABILITY_EXPLICITLY_ESTABLISHED

PRODUCTION_GENERATION_POLICY=
UNCHANGED_UNCONFIGURED_UNSEEDED

COMPLETED_RUNTIME_CAPABILITY_INVENTORY_CURRENTNESS=
CURRENT_WITH_ADDITIVE_CROSS_TURN_VALIDATION_UPDATE

CORRIDOR_1_STATUS=
COMPLETE

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_CHANGE=
NONE

NEXT_CORRIDOR=
DEFERRED_WORK_INVENTORY

NEXT_ACTION=
RECONCILE_DEFERRED_WORK_INVENTORY_CURRENTNESS
MAP
