#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="9cd4c128a"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — APPROVAL TRANSITION IMPLEMENTATION AUTHORIZATION ==="
echo "MODE=EXECUTION"
echo "CORRIDOR_6=SELF_IMPROVEMENT_EXECUTION_ACTIVATION_CLOSURE"
echo "IMPLEMENTATION_AUTHORIZED=YES"
echo

echo "=== AUTHORIZED SCOPE ==="
echo "UNIT_1=NARROW_EXECUTION_APPROVAL_PERSISTENCE_IN_EXISTING_GOVERNANCE_DOMAIN"
echo "UNIT_2=USER_OWNED_APPROVAL_REQUIRED_TO_APPROVED_WRITE_TRANSITION"
echo "UNIT_3=FAIL_CLOSED_READ_ONLY_EXECUTION_APPROVAL_READER"
echo "UNIT_4=COMPILER_TO_EXISTING_EXECUTION_APPROVAL_ARTIFACT_SHAPE"
echo "UNIT_5=TARGETED_TESTS"
echo

echo "=== STILL EXCLUDED ==="
echo "EXECUTION_ROUTE_AUTHORIZED=NO"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGE_AUTHORIZED=NO"
echo "REMOTE_PUSH_EFFECT_CHANGE_AUTHORIZED=NO"
echo "GENERIC_CADE_CHANGE_AUTHORIZED=NO"
echo "SCHEDULER_OR_AUTONOMY_CHANGE_AUTHORIZED=NO"
echo "PARALLEL_APPROVAL_SYSTEM_AUTHORIZED=NO"
echo "CORRIDOR_2_REOPEN_AUTHORIZED=NO"
echo

echo "=== AUTHORITY INVARIANTS ==="
echo "USER_IS_EXECUTION_APPROVAL_AUTHORITY=YES"
echo "MATILDA_SELF_APPROVAL=FORBIDDEN"
echo "CADE_SELF_APPROVAL=FORBIDDEN"
echo "CANONICAL_PACKAGE_APPROVAL_IMPLIES_EXECUTION_APPROVAL=NO"
echo "APPROVAL_MUST_BIND_EXACT_ENVELOPE=YES"
echo "APPROVAL_MUST_BIND_EXACT_VERSION_CONTROL_SCOPE=YES"
echo "PUSH_MAY_BE_IMPLIED_BY_COMMIT=NO"
echo "REPLAY_ACROSS_DIFFERENT_ENVELOPE=PROHIBITED"
echo

echo "=== IMPLEMENTATION SAFETY GATE ==="
echo "IMPLEMENTATION_MAY_BEGIN=YES"
echo "FIRST_IMPLEMENTATION_ACTION=INSPECT_EXACT_GOVERNANCE_RUNTIME_SCHEMA_AND_DATABASE_EXPORT_BOUNDARIES"
echo "SPECULATIVE_SCHEMA_PATCHING=FORBIDDEN"
echo "NEXT_ACTION=IMPLEMENT_ONLY_AFTER_EXACT_INSERTION_AND_READER_BOUNDARIES_ARE_CONFIRMED"
echo

echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
