#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="7911e7df3"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — APPROVAL TRANSITION AUTHORIZATION REQUEST ==="
echo "MODE=COLLABORATION"
echo "CORRIDOR_6=SELF_IMPROVEMENT_EXECUTION_ACTIVATION_CLOSURE"
echo "IMPLEMENTATION_READY=YES"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo
echo "=== AUTHORIZATION SCOPE ==="
echo "UNIT_1=NARROW_EXECUTION_APPROVAL_PERSISTENCE_IN_EXISTING_GOVERNANCE_DOMAIN"
echo "UNIT_2=USER_OWNED_APPROVAL_REQUIRED_TO_APPROVED_WRITE_TRANSITION"
echo "UNIT_3=FAIL_CLOSED_READ_ONLY_EXECUTION_APPROVAL_READER"
echo "UNIT_4=COMPILER_TO_EXISTING_EXECUTION_APPROVAL_ARTIFACT_SHAPE"
echo "UNIT_5=TARGETED_TESTS"
echo
echo "=== EXCLUDED ==="
echo "EXECUTION_ROUTE_INCLUDED=NO"
echo "ROUTE_MOUNT_INCLUDED=NO"
echo "PRODUCTION_REACHABILITY_INCLUDED=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGE=NO"
echo "REMOTE_PUSH_EFFECT_CHANGE=NO"
echo "GENERIC_CADE_CHANGE=NO"
echo "SCHEDULER_OR_AUTONOMY_CHANGE=NO"
echo "PARALLEL_APPROVAL_SYSTEM=NO"
echo "CORRIDOR_2_REOPEN=NO"
echo
echo "=== AUTHORITY BOUNDARY ==="
echo "USER_IS_EXECUTION_APPROVAL_AUTHORITY=YES"
echo "MATILDA_SELF_APPROVAL=FORBIDDEN"
echo "CADE_SELF_APPROVAL=FORBIDDEN"
echo "CANONICAL_PACKAGE_APPROVAL_IMPLIES_EXECUTION_APPROVAL=NO"
echo "APPROVAL_MUST_BIND_EXACT_ENVELOPE=YES"
echo "APPROVAL_MUST_BIND_EXACT_VERSION_CONTROL_SCOPE=YES"
echo "PUSH_MAY_BE_IMPLIED_BY_COMMIT=NO"
echo "REPLAY_ACROSS_DIFFERENT_ENVELOPE=PROHIBITED"
echo
echo "=== REQUIRED CHAT AUTHORIZATION ==="
echo "REQUESTED_USER_STATEMENT=I authorize the bounded Corridor 6 execution approval transition persistence, write transition, reader/compiler, and targeted tests implementation."
echo "NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION_IN_CHAT"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
