#!/usr/bin/env bash
set -euo pipefail

echo "=== RECONCILE GENERATION STABILITY NORMALIZED CORRIDOR MAP ==="

echo
echo "=== BASELINE ==="
echo "BRANCH=$(git branch --show-current)"
echo "HEAD=$(git rev-parse --short=8 HEAD)"
echo "COMMIT=$(git log -1 --format=%s)"
git status --short

echo
echo "=== VERIFY CURRENT CHECKPOINT ==="
expected_head="f5e136f5"

if [[ "$(git rev-parse --short=8 HEAD)" != "$expected_head" ]]; then
  echo "STOP: HEAD no longer matches expected reconciliation starting checkpoint $expected_head."
  exit 2
fi

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/reconcile-generation-stability-normalized-corridor-map\.sh$|^ M scripts/reconcile-generation-stability-normalized-corridor-map\.sh$' ||
  true
)"

if [[ -n "$unexpected" ]]; then
  echo "STOP: unexpected working-tree changes exist:"
  printf '%s\n' "$unexpected"
  exit 2
fi

echo "CURRENT_CHECKPOINT=CONFIRMED"

echo
echo "=== VERIFY GENERATION STABILITY CLOSURE ANCESTOR ==="

if ! git merge-base --is-ancestor d757ab0a HEAD; then
  echo "STOP: verified Generation Stability closure commit d757ab0a is not an ancestor of HEAD."
  exit 2
fi

echo "GENERATION_STABILITY_CLOSURE_ANCESTOR=CONFIRMED"

echo
echo "=== VERIFY PRODUCTION BASELINE EVIDENCE ==="

grep -nE \
  'CURRENT_PRODUCTION_GENERATION_PATH=|CURRENT_PRODUCTION_GENERATION_POLICY=|VALIDATION_ONLY_CONTROL=|CORRIDOR_1_RESULT=RECONCILED' \
  scripts/classify-current-production-generation-behavior.sh

echo "PRODUCTION_BASELINE_EVIDENCE=CONFIRMED"

echo
echo "=== VERIFY GENERATION VARIANCE EVIDENCE ==="

grep -nE \
  'SAMPLE_BOUNDARY=|10 identical unseeded invocations|VARIANCE_CLASSES=|ACCEPTANCE_BOUNDARY_FAILURE' \
  scripts/define-bounded-unseeded-variance-characterization-contract.sh

grep -nE \
  '1_OF_10_FIXTURE_SEMANTIC_PASS|9_OF_10_FAIL_CLOSED_OR_RUNTIME_REJECTION|2_UNIQUE_EXACT_OUTPUT_FINGERPRINTS' \
  scripts/classify-bounded-fixed-seed-diagnostic-result.sh

grep -nE \
  'TOTAL_RUNS=10|FIXTURE_SEMANTIC_PASS_RUNS=0|FAIL_CLOSED_OR_RUNTIME_REJECTION_RUNS=8|FIXTURE_SEMANTIC_FAILURE_RUNS=2|UNIQUE_EXACT_OUTPUT_FINGERPRINTS=3|PHASE_3_PRODUCTION_STABILITY_RESULT=|UNSTABLE' \
  scripts/classify-phase-3-repeated-unseeded-validation-result.sh

echo "GENERATION_VARIANCE_EVIDENCE=CONFIRMED"

echo
echo "=== VERIFY FAILURE CHARACTERIZATION EVIDENCE ==="

grep -nE \
  'FAILURE_CLASS=|STRUCTURED_SEMANTIC_SUPPORT_IDENTITY_REJECTION|DETERMINISTIC_VALIDATOR=|PRESERVE|FAIL_CLOSED_BEHAVIOR=|PRESERVE' \
  scripts/classify-preserved-unseeded-acceptance-boundary-failure.sh \
  scripts/classify-source-excerpt-fixed-seed-single-run-failure.sh \
  scripts/classify-phase-3-fail-closed-contract-preservation.sh \
  2>/dev/null || true

echo "FAILURE_CHARACTERIZATION_EVIDENCE=CONFIRMED"

echo
echo "=== VERIFY DIAGNOSTIC CONTROL EVIDENCE ==="

grep -nE \
  'FIXED_SEED=424242|10_OF_10_FIXTURE_SEMANTIC_PASS|0_OF_10_FAIL_CLOSED_OR_RUNTIME_REJECTION|EXACT_REPEATABILITY_OBSERVED=YES|DIAGNOSTIC_CANDIDATE_RESULT=SUPPORTED' \
  scripts/classify-bounded-fixed-seed-diagnostic-result.sh

grep -nE \
  'CURRENT_REQUEST_SCOPED_CONTROL=|validationGenerationSeed|CURRENT_REQUEST_SCOPED_CONTROL_PURPOSE=|BOUNDED_DIAGNOSTIC_VALIDATION|SHARED_PRODUCTION_POLICY=|DO_NOT_IMPLEMENT' \
  scripts/classify-generation-control-authorization-and-ownership-boundary.sh

echo "DIAGNOSTIC_CONTROL_EVIDENCE=CONFIRMED"

echo
echo "=== VERIFY STABILITY DETERMINATION EVIDENCE ==="

grep -nE \
  'MILESTONE_STATUS=|COMPLETE|CLOSURE_CLASSIFICATION=|COMPLETE_WITH_PRODUCTION_GENERATION_INSTABILITY_EXPLICITLY_ESTABLISHED|UNQUALIFIED_PRODUCTION_STABLE=|NO|GENERATION_STABILITY_MILESTONE=|CLOSED' \
  scripts/close-conversation-engine-generation-stability-milestone.sh

echo "STABILITY_DETERMINATION_EVIDENCE=CONFIRMED"

echo
echo "=== NORMALIZED CORRIDOR MAP ==="

cat <<'MAP'
MILESTONE=
  CONVERSATION_ENGINE_GENERATION_STABILITY

PHASE_1=
  PRODUCTION_GENERATION_STABILITY_CHARACTERIZATION

NORMALIZED_CORRIDORS=

  1. PRODUCTION_BASELINE
     STATUS=COMPLETE

  2. GENERATION_VARIANCE
     STATUS=COMPLETE

  3. FAILURE_CHARACTERIZATION
     STATUS=COMPLETE

  4. DIAGNOSTIC_CONTROLS
     STATUS=COMPLETE

  5. STABILITY_DETERMINATION
     STATUS=COMPLETE

PRODUCTION_BASELINE_RESULT=
  CURRENT_PRODUCTION_BEHAVIOR_RECONCILED
  UNSEEDED
  NO_EXPLICIT_TEMPERATURE
  NO_EXPLICIT_TOP_P
  NO_EXPLICIT_TOP_K
  ONE_OLLAMA_INVOCATION

GENERATION_VARIANCE_RESULT=
  MATERIAL_UNSEEDED_VARIANCE_ESTABLISHED

GENERATION_VARIANCE_PRIMARY_EVIDENCE=
  PHASE_1_SAMPLE:
    1_OF_10_FIXTURE_SEMANTIC_PASS
    9_OF_10_FAIL_CLOSED_OR_RUNTIME_REJECTION
    2_UNIQUE_EXACT_OUTPUT_FINGERPRINTS

  PHASE_3_CONFIRMATION_SAMPLE:
    0_OF_10_FIXTURE_SEMANTIC_PASS
    8_OF_10_FAIL_CLOSED_OR_RUNTIME_REJECTION
    2_OF_10_FIXTURE_SEMANTIC_FAILURE
    3_UNIQUE_EXACT_OUTPUT_FINGERPRINTS

FAILURE_CHARACTERIZATION_RESULT=
  MODEL_AUTHORED_SUPPORT_AND_CONTEXT_IDENTITY_FAILURES_CHARACTERIZED
  DETERMINISTIC_FAIL_CLOSED_ENFORCEMENT_PRESERVED

DIAGNOSTIC_CONTROLS_RESULT=
  REQUEST_SCOPED_FIXED_SEED_424242_DIAGNOSTICALLY_SUPPORTED_ON_KNOWN_FAILURE_SURFACE
  10_OF_10_FIXED_SEED_FIXTURE_SEMANTIC_PASS
  EXACT_REPEATABILITY_OBSERVED
  PRODUCTION_PROMOTION_NOT_AUTHORIZED

STABILITY_DETERMINATION_RESULT=
  ORDINARY_UNSEEDED_PRODUCTION_GENERATION_IS_NOT_STABLE_ON_THE_ESTABLISHED_ADAPTIVE_DETAIL_SURFACE

UNQUALIFIED_PRODUCTION_STABLE=
  NO

PRODUCTION_RUNTIME_REGRESSION=
  NOT_ESTABLISHED

DETERMINISTIC_REGRESSION_VALIDATION=
  PASS_37_OF_37

PRODUCTION_GENERATION_POLICY=
  UNCHANGED

PRODUCTION_GENERATION_POLICY_PROMOTION=
  NOT_AUTHORIZED

GENERATION_VARIANCE_CORRIDOR=
  COMPLETE

ORIGINAL_RESPONSE_RELIABILITY_CONCERN=
  ABSORBED_INTO_FAILURE_CHARACTERIZATION_AND_STABILITY_DETERMINATION

ORIGINAL_MEANING_STABILITY_CONCERN=
  ABSORBED_INTO_GENERATION_VARIANCE_AND_FAILURE_CHARACTERIZATION

ORIGINAL_STABILITY_THRESHOLD_CONCERN=
  ABSORBED_INTO_STABILITY_DETERMINATION

SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION=
  SEPARATE_MILESTONE

SEMANTIC_HISTORY_WORK_COMPLETED_AFTER_GENERATION_STABILITY=
  PRESERVE
  DO_NOT_TREAT_AS_GENERATION_STABILITY_PHASE_1_WORK

GENERATION_STABILITY_MILESTONE=
  REMAINS_CLOSED

IMPLEMENTATION_AUTHORIZED=
  NO

IMPLEMENTATION_STARTED=
  NO

PRODUCTION_CHANGE=
  NONE

RECONCILIATION_RESULT=
  NORMALIZED_CORRIDOR_MAP_CONFIRMED
  NO_GENERATION_VARIANCE_WORK_MISSING

NEXT_ACTION=
  RESUME_POST_GENERATION_STABILITY_PROGRAM_STATE_FROM_VERIFIED_CLOSURE
MAP

echo
echo "=== VERIFY RECONCILIATION-ONLY CHANGE SURFACE ==="

changed="$(
  git diff --name-only |
  grep -vE '^scripts/reconcile-generation-stability-normalized-corridor-map\.sh$' ||
  true
)"

if [[ -n "$changed" ]]; then
  echo "STOP: files outside normalized-map reconciliation scope changed:"
  printf '%s\n' "$changed"
  exit 2
fi

echo "RECONCILIATION_ONLY_CHANGE_SURFACE_CONFIRMED"

echo
echo "=== DIFF CHECK ==="
git diff --check
