#!/usr/bin/env bash
set -euo pipefail

echo "=== RECONCILE CURRENT PRODUCTION FAILURE BASELINE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 7e7eabc1 HEAD

contract="scripts/investigate-collaboration-reliability-contract.sh"
phase3="scripts/classify-current-phase-3-repeated-unseeded-validation-result.sh"
phase1="scripts/classify-production-stability-from-established-evidence.sh"
failure_classes="scripts/classify-failure-characterization-observed-classes.sh"
closure="scripts/close-conversation-engine-generation-stability-milestone.sh"

for artifact in "$contract" "$phase3" "$phase1" "$failure_classes" "$closure"; do
  test -f "$artifact"
  echo "PRESENT=$artifact"
done

echo
echo "=== VERIFY CORRIDOR 1 CLOSURE ==="
grep -q 'CORRIDOR_1_STATUS=' "$contract"
grep -q 'COMPLETE' "$contract"
grep -q 'PRODUCTION_FAILURE_BASELINE' "$contract"
echo "CORRIDOR_1_CLOSURE=CONFIRMED"

echo
echo "=== VERIFY CURRENT GOVERNING SAMPLE ==="
grep -q 'FAIL_CLOSED_OR_RUNTIME_REJECTION_RUNS=10' "$phase3"
grep -q 'UNSTABLE' "$phase3"
grep -q 'PRESERVED_ON_ALL_10_OBSERVED_FAILURES' "$phase3"
echo "CURRENT_PHASE_3_SAMPLE=CONFIRMED"

echo
echo "=== VERIFY EARLIER COMPARISON SAMPLE ==="
grep -q 'FULL_SEMANTIC_PASS_RUNS=0' "$phase1"
grep -q 'FAIL_CLOSED_OR_RUNTIME_REJECTION_RUNS=8' "$phase1"
grep -q 'SEMANTIC_ACCEPTANCE_FAILURE_RUNS=2' "$phase1"
echo "EARLIER_PHASE_1_SAMPLE=CONFIRMED"

echo
echo "=== VERIFY FAILURE CLASSES ==="
grep -q 'MODEL_AUTHORED_INVALID_SUPPORT_PROVENANCE' "$failure_classes"
grep -q 'SEMANTIC_ACCEPTANCE_FAILURE_AFTER_SUCCESSFUL_ADAPTER_RETURN' "$failure_classes"
grep -q 'PRODUCTION_RUNTIME_REGRESSION=NOT_ESTABLISHED' "$failure_classes"
grep -q 'FAIL_CLOSED_CONTRACT=PRESERVED' "$failure_classes"
echo "FAILURE_CLASSES=CONFIRMED"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION
PHASE_1=
STARTING_BOUNDARY_AND_RELIABILITY_BASELINE
CORRIDOR_2=
PRODUCTION_FAILURE_BASELINE

BASELINE_SOURCE=
EXISTING_GENERATION_STABILITY_EVIDENCE_ONLY
NEW_LIVE_SAMPLE_REQUIRED=
NO

CURRENT_GOVERNING_SAMPLE=
10_UNSEEDED_PRODUCTION_EQUIVALENT_RUNS
SEMANTIC_PASS_RUNS=
0
FAIL_CLOSED_OR_RUNTIME_REJECTION_RUNS=
10
CURRENT_PRIMARY_FAILURE_SIGNATURE=
UNSUPPLIED_PROJECT_CONTEXT_SUPPORT_REFERENCE
FAIL_CLOSED_VALIDATION=
PRESERVED

EARLIER_SAMPLE=
10_UNSEEDED_PRODUCTION_EQUIVALENT_RUNS
FULL_SEMANTIC_PASS_RUNS=
0
FAIL_CLOSED_OR_RUNTIME_REJECTION_RUNS=
8
SEMANTIC_ACCEPTANCE_FAILURE_RUNS=
2

OBSERVED_FAILURE_CLASSES=
MODEL_AUTHORED_INVALID_SUPPORT_PROVENANCE
SEMANTIC_ACCEPTANCE_FAILURE_AFTER_SUCCESSFUL_ADAPTER_RETURN

PRODUCTION_STABILITY=
NOT_ESTABLISHED
MATERIAL_GENERATION_INSTABILITY=
ESTABLISHED
PRODUCTION_RUNTIME_REGRESSION=
NOT_ESTABLISHED
DETERMINISTIC_VALIDATOR_MALFUNCTION=
NOT_ESTABLISHED

BASELINE_INTERPRETATION=
Existing evidence establishes a material day-to-day collaboration reliability
problem on the ordinary unseeded production-equivalent path.
The validator is correctly rejecting invalid semantic or provenance output.
The evidence does not yet establish causal ownership or an implementation remedy.

FAILURE_ROOT_CAUSE=
NOT_YET_ESTABLISHED
FAILURE_OWNERSHIP=
NOT_YET_CLASSIFIED
IMPLEMENTATION_REMEDY=
NOT_YET_ESTABLISHED

PRODUCTION_GENERATION_POLICY_CHANGE=
NOT_AUTHORIZED
VALIDATOR_WEAKENING=
NOT_AUTHORIZED
RETRY_OR_SECOND_MODEL_CALL=
NOT_AUTHORIZED
MODEL_CHANGE=
NOT_AUTHORIZED
PROMPT_CHANGE=
NOT_AUTHORIZED
IMPLEMENTATION_AUTHORIZED=
NO
IMPLEMENTATION_STARTED=
NO
PRODUCTION_CHANGE=
NONE

CORRIDOR_2_STATUS=
COMPLETE
NEXT_CORRIDOR=
FAILURE_OWNERSHIP
NEXT_ACTION=
INVESTIGATE_AND_CLASSIFY_PRODUCTION_COLLABORATION_FAILURE_OWNERSHIP
MAP
