#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="58abf60d4"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — EXECUTION ENVELOPE DURABILITY IMPLEMENTATION START ==="
echo "MODE=EXECUTION"
echo "EXECUTION_ENVELOPE_DURABILITY_IMPLEMENTATION_AUTHORIZED=YES"
echo "AUTHORIZED_CHECKPOINT=58abf60d4"
echo

echo "=== IMPLEMENTATION TARGET ==="
echo "TARGET_1=DURABLE_REPO_PATH_BINDING"
echo "TARGET_2=DURABLE_EXPECTED_HEAD_BINDING"
echo "TARGET_3=DURABLE_ALLOWED_PATHS_BINDING"
echo "TARGET_4=DURABLE_FORBIDDEN_PATHS_BINDING"
echo "TARGET_5=DURABLE_SCOPE_CONSTRAINTS_BINDING"
echo "TARGET_6=EXACT_ENVELOPE_AND_PACKAGE_LINEAGE_BINDING"
echo "TARGET_7=FAIL_CLOSED_READ_ONLY_EXECUTION_SCOPE_READER"
echo "TARGET_8=TARGETED_PERSISTENCE_AND_READER_TESTS"
echo

echo "=== REQUIRED OWNER / BOUNDARY ==="
echo "PERSISTENCE_OWNER=EXISTING_GOVERNANCE_EXECUTION_APPROVAL_DOMAIN"
echo "PARALLEL_APPROVAL_SYSTEM=PROHIBITED"
echo "NEW_GENERIC_AUTHORITY_LAYER=PROHIBITED"
echo "USER_OWNED_EXECUTION_SCOPE_APPROVAL_REQUIRED=YES"
echo "CURRENT_GIT_HEAD_AS_AUTHORITY=PROHIBITED"
echo "PROCESS_CWD_AS_AUTHORITY=PROHIBITED"
echo "CLIENT_SUPPLIED_RUNTIME_AUTHORITY=PROHIBITED"
echo "REPLAY_ACROSS_ENVELOPES=PROHIBITED"
echo "COMMIT_AUTHORITY_IMPLIES_PUSH=NO"
echo

echo "=== EXCLUDED SURFACES ==="
echo "UNMOUNTED_EXECUTION_ROUTE_CHANGE=NO_IN_THIS_UNIT"
echo "SERVER_INDEX_ROUTE_MOUNT_CHANGE=NO"
echo "PRODUCTION_REACHABILITY_CHANGE=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGE=NO"
echo "REMOTE_PUSH_EFFECT_CHANGE=NO"
echo "GENERIC_CADE_CHANGE=NO"
echo "GENERIC_SHELL_CHANGE=NO"
echo "GENERIC_MUTATION_CHANGE=NO"
echo "SCHEDULER_OR_AUTONOMY_CHANGE=NO"
echo

echo "=== PRE-IMPLEMENTATION SOURCE CHECK ==="
sed -n '1,420p' db/governance-execution-approval-persistence.ts
echo
grep -n -B30 -A90 'CREATE TABLE IF NOT EXISTS governance_envelopes' db/governance-runtime.ts
echo
grep -n -B30 -A130 'export function createGovernanceEnvelope' db/governance-runtime.ts
echo

echo "=== IMPLEMENTATION READINESS ==="
echo "IMPLEMENTATION_MAY_PROCEED=YES"
echo "FIRST_CHANGE=EXTEND_EXISTING_GOVERNANCE_EXECUTION_APPROVAL_DOMAIN_WITH_NARROW_DURABLE_EXECUTION_SCOPE_BINDING"
echo "TEST_REQUIREMENT=IN_MEMORY_SQLITE_ONLY"
echo "REAL_GIT_EFFECTS_ALLOWED=NO"
echo
echo "CORRIDOR_6_STATUS=EXECUTION_ENVELOPE_DURABILITY_IMPLEMENTATION_IN_PROGRESS"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=IMPLEMENT_DURABILITY_BINDING_READER_AND_TARGETED_TESTS"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
