#!/usr/bin/env bash
set -euo pipefail

echo "=== RECORD PROGRAM RECONCILIATION FINAL DR CHECKPOINT ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 6b18884a HEAD

closure="scripts/close-conversation-engine-program-reconciliation-milestone.sh"
checkpoint="scripts/capture-program-reconciliation-final-checkpoint.sh"

test -f "$closure"
test -f "$checkpoint"

grep -q 'MILESTONE_STATUS=' "$closure"
grep -q 'CLOSED' "$closure"
grep -q 'NEXT_RUNTIME_IMPLEMENTATION_MILESTONE=' "$closure"
grep -q 'NONE_ESTABLISHED' "$closure"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE
CLOSED_MILESTONE=
CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION
MILESTONE_CLOSURE_COMMIT=
32c26bba
FINAL_CHECKPOINT_COMMIT=
6b18884a
FINAL_DR=
20260813_194322
FINAL_DR_STATUS=
COMPLETE
MILESTONE_STATUS=
CLOSED_AND_DR_PROTECTED
PHASE_1_STATUS=
COMPLETE_AND_DR_PROTECTED
CURRENT_UNRESOLVED_CAPABILITY_GAPS=
ZERO_ON_CURRENT_INVENTORIED_SURFACE
CURRENT_SUCCESSOR_PRIORITY=
NONE_ESTABLISHED
NEXT_RUNTIME_IMPLEMENTATION_MILESTONE=
NONE_ESTABLISHED
PRODUCTION_GENERATION_INSTABILITY=
PRESERVED_AS_KNOWN_DEFERRED_CONDITION
PRODUCTION_GENERATION_POLICY=
UNCHANGED_UNCONFIGURED_UNSEEDED
PRODUCTION_CHANGE=
NONE
NEXT_PROGRAM_STATE=
NO_ACTIVE_RUNTIME_SUCCESSOR_MILESTONE_ESTABLISHED
NEXT_ACTION=
AWAIT_NEW_EVIDENCE_OR_EXPLICIT_NEW_PROGRAM_OBJECTIVE
MAP
