#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="473c310ea"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — EXECUTION ENVELOPE DURABILITY AUTHORIZATION REQUEST ==="
echo "MODE=COLLABORATION"
echo "CORRIDOR_6_STATUS=AWAITING_EXECUTION_ENVELOPE_DURABILITY_IMPLEMENTATION_AUTHORIZATION"
echo "PHASE_1_STATUS=ACTIVE"
echo

echo "=== PROPOSED BOUNDED IMPLEMENTATION UNIT ==="
echo "UNIT_1=DURABLE_REPO_PATH_BINDING"
echo "UNIT_2=DURABLE_EXPECTED_HEAD_BINDING"
echo "UNIT_3=DURABLE_ALLOWED_PATHS_BINDING"
echo "UNIT_4=DURABLE_FORBIDDEN_PATHS_BINDING"
echo "UNIT_5=DURABLE_SCOPE_CONSTRAINTS_BINDING"
echo "UNIT_6=EXACT_ENVELOPE_AND_PACKAGE_LINEAGE_BINDING"
echo "UNIT_7=FAIL_CLOSED_READ_ONLY_EXECUTION_SCOPE_READER"
echo "UNIT_8=TARGETED_PERSISTENCE_AND_READER_TESTS"
echo

echo "=== AUTHORITY REQUIREMENTS ==="
echo "USER_OWNED_EXECUTION_SCOPE_APPROVAL_REQUIRED=YES"
echo "EXISTING_EXECUTION_APPROVAL_DOMAIN_REUSED=YES"
echo "PARALLEL_GENERAL_APPROVAL_SYSTEM=NO"
echo "CLIENT_SUPPLIED_RUNTIME_AUTHORITY=NO"
echo "CURRENT_GIT_HEAD_AS_IMPLICIT_AUTHORITY=NO"
echo "PROCESS_CWD_AS_IMPLICIT_AUTHORITY=NO"
echo "COMMIT_AUTHORITY_IMPLIES_PUSH=NO"
echo "REPLAY_ACROSS_ENVELOPES=PROHIBITED"
echo

echo "=== EXCLUDED FROM THIS REQUEST ==="
echo "UNMOUNTED_EXECUTION_ROUTE_IMPLEMENTATION=EXCLUDED_ALREADY_SEPARATELY_AUTHORIZED"
echo "SERVER_INDEX_ROUTE_MOUNT=EXCLUDED"
echo "PRODUCTION_REACHABILITY=EXCLUDED"
echo "LOCAL_COMMIT_EFFECT_CHANGES=EXCLUDED"
echo "REMOTE_PUSH_EFFECT_CHANGES=EXCLUDED"
echo "GENERIC_CADE_CHANGES=EXCLUDED"
echo "GENERIC_SHELL_AUTHORITY=EXCLUDED"
echo "GENERIC_MUTATION_AUTHORITY=EXCLUDED"
echo "SCHEDULER_OR_AUTONOMY=EXCLUDED"
echo

echo "=== IMPLEMENTATION GATE ==="
echo "EXECUTION_ENVELOPE_DURABILITY_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXPLICIT_CHAT_AUTHORIZATION_REQUIRED=YES"
echo "AUTHORIZED_ROUTE_IMPLEMENTATION_REMAINS_PAUSED=YES"
echo "NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION"
echo

echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
