#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=b14cf45e' \
  'ISSUE_RESOLVED=NO' \
  'MODE=COLLABORATION_EXPLICIT_AUTHORIZATION_GATE' \
  'COMPARISON_CONTRACT=DEFINED' \
  'IMPLEMENTATION_READY=YES' \
  'IMPLEMENTATION_STARTED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'USER_AUTHORIZATION_REQUIRED=YES' \
  'AUTHORIZED_SCOPE_IF_USER_APPROVES=VALIDATION_ONLY_RUNNER_IMPLEMENTATION_AND_EXECUTION' \
  'NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION'

printf '\n=== BOUNDED AUTHORIZATION SCOPE ===\n'
printf '%s\n' \
  'NEW_VALIDATION_ONLY_RUNNER=ONLY_ALLOWED_IMPLEMENTATION_SURFACE' \
  'UNSEEDED_ARM=10_RUNS' \
  'CONTROLLED_ARM=10_RUNS' \
  'CONTROLLED_SEED=424242' \
  'CAUSAL_VARIABLE=validationGenerationSeed_ONLY' \
  'PRODUCTION_FILE_MUTATION=NONE' \
  'DATABASE_WRITE=NONE' \
  'RETRY=NONE' \
  'ROLLBACK_SCOPE=DELETE_NEW_VALIDATION_ONLY_RUNNER'

printf '\n=== STILL PROHIBITED ===\n'
printf '%s\n' \
  'PRODUCTION_SEED=NO' \
  'PRODUCTION_POLICY_CHANGE=NO' \
  'VALIDATOR_CHANGE=NO' \
  'VALIDATOR_WEAKENING=NO' \
  'PROMPT_CHANGE=NO' \
  'MODEL_CHANGE=NO' \
  'RETRY_CHANGE=NO' \
  'TIMEOUT_CHANGE=NO' \
  'PERSISTENCE_CHANGE=NO'

printf '\n=== RESOLUTION STATUS ===\n'
printf '%s\n' \
  'ISSUE_RESOLVED=NO' \
  'REASON=VALIDATION_ONLY_COMPARISON_IMPLEMENTATION_NOT_AUTHORIZED_OR_RUN'

printf '\n=== WORKTREE ===\n'
git status --short
