#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

expected_head="08d9d38d"

echo "=== RECONCILE CANONICAL PHASE 3 STARTING BOUNDARY ==="

if [[ "$(git rev-parse --short=8 HEAD)" != "$expected_head" ]]; then
  echo "STOP: HEAD no longer matches protected Phase 2 closure checkpoint $expected_head."
  exit 1
fi

unexpected="$(
  git status --short |
  grep -vE '^\?\? scripts/reconcile-canonical-phase-3-starting-boundary\.sh$|^ M scripts/reconcile-canonical-phase-3-starting-boundary\.sh$' ||
  true
)"

if [[ -n "$unexpected" ]]; then
  echo "STOP: unexpected working-tree changes."
  printf '%s\n' "$unexpected"
  exit 1
fi

echo "PROTECTED_PHASE_2_DR=20260812_155502"

grep -q 'PHASE_2_STATUS=CLOSED' \
  docs/architecture/CONVERSATION_ENGINE_GENERATION_STABILITY.md
grep -q 'PHASE_2_DISPOSITION=COMPLETE_WITH_NO_PRODUCTION_POLICY_IMPLEMENTATION' \
  docs/architecture/CONVERSATION_ENGINE_GENERATION_STABILITY.md
grep -q 'CURRENT_PRODUCTION_BASELINE=UNCONFIGURED_UNSEEDED_GENERATION' \
  docs/architecture/CONVERSATION_ENGINE_GENERATION_STABILITY.md

if grep -q 'validationGenerationSeed' server/matilda-chat-workflow.ts; then
  echo "STOP: production workflow now supplies validationGenerationSeed."
  exit 1
fi

cat <<'FINDINGS'

MILESTONE=CONVERSATION_ENGINE_GENERATION_STABILITY
PHASE=PRODUCTION_STABILITY_VALIDATION_AND_CLOSURE
PHASE_NUMBER=3

CANONICAL_CORRIDOR_COUNT=6
CORRIDOR_1=PRODUCTION_STABILITY_VALIDATION_CONTRACT
CORRIDOR_2=REPEATED_UNSEEDED_BEHAVIORAL_VALIDATION
CORRIDOR_3=FAIL_CLOSED_CONTRACT_PRESERVATION
CORRIDOR_4=SINGLE_OLLAMA_INVOCATION_PRESERVATION
CORRIDOR_5=PRODUCTION_REGRESSION_VALIDATION
CORRIDOR_6=GENERATION_STABILITY_CLOSURE_CLASSIFICATION

PHASE_2_PRODUCTION_POLICY_IMPLEMENTATION=NONE
PHASE_3_PRODUCTION_STATE_TO_VALIDATE=UNCHANGED_UNCONFIGURED_UNSEEDED_GENERATION
SEEDED_DIAGNOSTIC_EVIDENCE_ROLE=SUPPORTING_DIAGNOSTIC_ONLY
SEEDED_DIAGNOSTIC_EVIDENCE_SUFFICIENT_FOR_PRODUCTION_STABILITY=NO

EXISTING_GENERATION_STABILITY_PHASE_3_ARTIFACTS=
  POTENTIALLY_REUSABLE_SUBJECT_TO_CURRENT_ANCESTRY_AND_CONTRACT_VALIDATION

PRODUCTION_CHANGE=NONE
IMPLEMENTATION_AUTHORIZED=NO
PHASE_3_STATUS=STARTING_BOUNDARY_RECONCILED
ACTIVE_CORRIDOR=PRODUCTION_STABILITY_VALIDATION_CONTRACT
NEXT_ACTION=VALIDATE_EXISTING_CORRIDOR_1_ARTIFACT_AGAINST_CANONICAL_PHASE_2_CLOSURE
FINDINGS
