#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="d52d5cf84"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — GOVERNANCE READ UNIT AUTHORIZATION GATE ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo
echo "=== AUTHORIZATION REQUIREMENT ==="
echo "EXPLICIT_USER_CHAT_AUTHORIZATION_REQUIRED=YES"
echo "TERMINAL_EXECUTION_DOES_NOT_CONSTITUTE_AUTHORIZATION=YES"
echo "ASSISTANT_CANNOT_GRANT_USER_AUTHORITY=YES"
echo
echo "=== REQUESTED IMPLEMENTATION UNITS ==="
echo "UNIT_1=FAIL_CLOSED_EXACT_DELEGATION_READER"
echo "UNIT_2=FAIL_CLOSED_EXACT_VALIDATION_RESULT_READER"
echo "UNIT_3=FAIL_CLOSED_EXACT_ENVELOPE_GATE_OR_LINEAGE_READER"
echo "UNIT_4=EXACT_PACKAGE_VERSION_DELEGATION_VALIDATION_CORRELATION"
echo "UNIT_5=TARGETED_READ_ONLY_TESTS"
echo
echo "=== PRESERVED BOUNDARY ==="
echo "OWNER=EXISTING_GOVERNANCE_PERSISTENCE_DOMAIN"
echo "NEW_DATABASE_OWNER=NO"
echo "NEW_AUTHORITY_CREATION=NO"
echo "ROUTE_IMPLEMENTATION_REMAINS_PAUSED=YES"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "GIT_EFFECT_CHANGES_AUTHORIZED=NO"
echo "GENERIC_CADE_CHANGES_AUTHORIZED=NO"
echo "GENERIC_SHELL_OR_MUTATION_AUTHORITY_AUTHORIZED=NO"
echo "SCHEDULER_OR_AUTONOMY_AUTHORIZED=NO"
echo
echo "=== CURRENT STATE ==="
echo "GOVERNANCE_READ_UNIT_IMPLEMENTATION_AUTHORIZED=NO"
echo "CORRIDOR_6_STATUS=AWAITING_EXPLICIT_USER_CHAT_AUTHORIZATION"
echo "PHASE_1_STATUS=ACTIVE"
echo
echo "AUTHORIZATION_TEXT=I authorize the bounded Corridor 6 governance read-only unit and targeted tests implementation."
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
