#!/usr/bin/env bash
set -euo pipefail

echo "=== RECONCILE CURRENT UNRESOLVED CAPABILITY GAPS ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 9c427542 HEAD

deferred="scripts/reconcile-current-deferred-work-inventory.sh"
legacy="scripts/classify-unresolved-capability-gaps.sh"

test -f "$deferred"
test -f "$legacy"

echo "=== VERIFY CORRIDOR 2 CLOSURE ==="
grep -q 'CORRIDOR_2_STATUS=' "$deferred"
grep -q 'COMPLETE' "$deferred"
grep -q 'NEXT_CORRIDOR=' "$deferred"
grep -q 'UNRESOLVED_CAPABILITY_GAP_CLASSIFICATION' "$deferred"
echo "CORRIDOR_2_CLOSURE=CONFIRMED"

echo
echo "=== VERIFY LEGACY GAP CLASSIFICATION ==="
grep -q 'UNRESOLVED_CAPABILITY_GAP_CLASSIFICATION_STATUS=' "$legacy"
grep -q 'COMPLETE' "$legacy"
grep -q 'PRIMARY_UNRESOLVED_CAPABILITY_GAP=' "$legacy"
grep -q 'CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION' "$legacy"
grep -q 'UNRESOLVED_CAPABILITY_GAP_COUNT=' "$legacy"
grep -q 'ONE' "$legacy"
echo "LEGACY_GAP_CLASSIFICATION=CONFIRMED"

echo
echo "=== RECONCILE STALE PRIMARY GAP ==="

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION

PHASE=
CURRENT_CAPABILITY_AND_DEFERRED_WORK_RECONCILIATION

CORRIDOR=
UNRESOLVED_CAPABILITY_GAP_CLASSIFICATION

CLASSIFICATION_RULE=
A capability is an unresolved gap only when a required architectural behavior
or validation boundary is established but still missing from the runtime.

DEFERRED_PRODUCTION_GENERATION_INSTABILITY=
KNOWN_CONDITION_NOT_CAPABILITY_GAP

SEMANTIC_HISTORY_RANKING=
NOT_A_CURRENT_GAP_REQUIREMENT_NOT_ESTABLISHED

TOKEN_BUDGET_CONTROL=
NOT_A_CURRENT_GAP_REQUIREMENT_NOT_ESTABLISHED

HISTORY_WINDOW_CHANGE=
NOT_A_CURRENT_GAP_CHANGE_REQUIREMENT_NOT_ESTABLISHED

HYBRID_CONTEXT_COORDINATION=
NOT_A_CURRENT_GAP_REQUIREMENT_NOT_ESTABLISHED

MODEL_RUNTIME_CONTEXT_CONFIGURATION=
NOT_A_CURRENT_GAP_CHANGE_REQUIREMENT_NOT_ESTABLISHED

INTEGRATED_OPTIMIZATION_LAYER=
NOT_A_CURRENT_GAP_REQUIREMENT_NOT_ESTABLISHED

EVALUATED_INTERPRETATIONS_SURFACING=
NOT_A_RUNTIME_CAPABILITY_GAP_IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

CONTAMINATION_EVALUATIONS_SURFACING=
NOT_A_RUNTIME_CAPABILITY_GAP_IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

INTERPRETATION_AUTHORITY_LIFECYCLE_STATE_SURFACING=
NOT_A_RUNTIME_CAPABILITY_GAP_IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

RECONSTRUCTED_INVESTIGATION_LIFECYCLE_STATE_SURFACING=
NOT_A_RUNTIME_CAPABILITY_GAP_IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

SELECTED_PRIOR_INVESTIGATION_LIFECYCLE_CONTEXT_SURFACING=
NOT_A_RUNTIME_CAPABILITY_GAP_IMPLEMENTED_BUT_NOT_INDEPENDENTLY_SURFACED

RECOVERY_AND_CORRELATION_REFINEMENTS=
DEFERRED_REFINEMENT_REQUIREMENT_NOT_ESTABLISHED

PROMPT_EVOLUTION=
DEFERRED_REFINEMENT_REQUIREMENT_NOT_ESTABLISHED

CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION=
IMPLEMENTED_AND_VALIDATED
NO_LONGER_AN_UNRESOLVED_CAPABILITY_GAP

CURRENT_GAP_RECONCILIATION=
The legacy classification identified exactly one unresolved capability gap:
cross-turn Investigation Lifecycle transition validation.

That premise is now stale because the capability has since been implemented
and validated.

No other inventoried item currently satisfies the established-gap rule.
Generation instability remains a known production condition rather than a
missing architectural capability, while other deferred items still lack an
established implementation requirement.

UNRESOLVED_CAPABILITY_GAP_COUNT=
ZERO_ON_CURRENT_INVENTORIED_SURFACE

PRIMARY_UNRESOLVED_CAPABILITY_GAP=
NONE_ESTABLISHED

IMPLEMENTATION_READINESS=
NOT_APPLICABLE_WITHOUT_ESTABLISHED_GAP

PRIORITY=
REQUIRES_SUCCESSOR_PRIORITY_RECONCILIATION_WITH_ZERO_CURRENT_CAPABILITY_GAPS

UNRESOLVED_CAPABILITY_GAP_CLASSIFICATION_CURRENTNESS=
CURRENT_AFTER_REMOVING_IMPLEMENTED_CROSS_TURN_VALIDATION

CORRIDOR_3_STATUS=
COMPLETE

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_GENERATION_POLICY_REOPENED=
NO

PRODUCTION_CHANGE=
NONE

NEXT_CORRIDOR=
SUCCESSOR_PRIORITY_BOUNDARY

NEXT_ACTION=
RECONCILE_SUCCESSOR_PRIORITY_BOUNDARY_CURRENTNESS
MAP
