#!/usr/bin/env bash
set -euo pipefail

echo "=== RECORD PROGRAM RECONCILIATION POST-DR TERMINAL STATE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor c56e9750 HEAD

record="scripts/record-program-reconciliation-final-dr-checkpoint.sh"
test -f "$record"

grep -q 'FINAL_DR=' "$record"
grep -q '20260813_194322' "$record"
grep -q 'MILESTONE_STATUS=' "$record"
grep -q 'CLOSED_AND_DR_PROTECTED' "$record"
grep -q 'NEXT_RUNTIME_IMPLEMENTATION_MILESTONE=' "$record"
grep -q 'NONE_ESTABLISHED' "$record"

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

TERMINAL_CHECKPOINT_COMMIT=
c56e9750

FINAL_DR=
20260813_194322

PROGRAM_RECONCILIATION_MILESTONE=
CLOSED_AND_DR_PROTECTED

PHASE_1=
COMPLETE_AND_DR_PROTECTED

CURRENT_UNRESOLVED_CAPABILITY_GAPS=
ZERO_ON_CURRENT_INVENTORIED_SURFACE

CURRENT_SUCCESSOR_PRIORITY=
NONE_ESTABLISHED

ACTIVE_RUNTIME_SUCCESSOR_MILESTONE=
NONE

PRODUCTION_GENERATION_INSTABILITY=
PRESERVED_AS_KNOWN_DEFERRED_CONDITION

PRODUCTION_GENERATION_POLICY=
UNCHANGED_UNCONFIGURED_UNSEEDED

PRODUCTION_CHANGE=
NONE

PROGRAM_STATE=
STABLE_TERMINAL_CHECKPOINT

CONTINUATION_BOUNDARY=
DO_NOT_OPEN_NEW_RUNTIME_WORK_WITHOUT_NEW_EVIDENCE_OR_EXPLICIT_PROGRAM_OBJECTIVE

NEXT_ACTION=
NONE_AUTOMATIC
MAP
