#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="4fe7f1814"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — DEDICATED EXECUTION ROUTE IMPLEMENTATION AUTHORIZATION ==="
echo "MODE=EXECUTION"
echo "AUTHORIZATION_SOURCE=CURRENT_CHAT"
echo "AUTHORIZED_SCOPE=UNMOUNTED_DEDICATED_EXECUTION_ROUTE_PLUS_TARGETED_TESTS_ONLY"
echo
echo "UNIT_1=UNMOUNTED_DEDICATED_EXECUTION_ROUTE"
echo "UNIT_2=EXACT_APPROVAL_ID_AND_ENVELOPE_ID_VALIDATION"
echo "UNIT_3=DURABLE_APPROVAL_READER_BINDING"
echo "UNIT_4=CANONICAL_ENVELOPE_BINDING"
echo "UNIT_5=PERSISTED_APPROVAL_COMPILER_BINDING"
echo "UNIT_6=EXISTING_EXECUTION_APPROVAL_GATE_BINDING"
echo "UNIT_7=BOUNDED_PRODUCTION_EXECUTION_ENTRY_POINT_CALL"
echo "UNIT_8=TARGETED_ROUTE_TESTS"
echo
echo "=== EXCLUDED ==="
echo "SERVER_INDEX_MOUNT=NO"
echo "PRODUCTION_REACHABILITY=NO"
echo "GENERIC_CADE_CHANGE=NO"
echo "GENERIC_SHELL_CHANGE=NO"
echo "GENERIC_MUTATION_CHANGE=NO"
echo "AUTONOMY_CHANGE=NO"
echo "SCHEDULER_CHANGE=NO"
echo "LOCAL_COMMIT_EFFECT_CHANGE=NO"
echo "REMOTE_PUSH_EFFECT_CHANGE=NO"
echo
echo "ROUTE_IMPLEMENTATION_AUTHORIZED=YES"
echo "ROUTE_MOUNT_AUTHORIZED=NO"
echo "PRODUCTION_REACHABILITY_AUTHORIZED=NO"
echo "CORRIDOR_6_STATUS=DEDICATED_EXECUTION_ROUTE_IMPLEMENTATION_AUTHORIZED"
echo "NEXT_ACTION=INSPECT_EXACT_CANONICAL_ENVELOPE_READER_AND_EXECUTION_APPROVAL_GATE_BINDING_BEFORE_IMPLEMENTATION"
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
