#!/usr/bin/env bash
set -euo pipefail

echo "=== RECONCILE CURRENT SEMANTIC HISTORY CONTEXT OPTIMIZATION STATE ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor 2322ae14 HEAD

echo "=== VERIFY SUCCESSOR PRIORITY ==="
successor="scripts/reconcile-current-successor-priority-after-generation-stability.sh"
test -f "$successor"
grep -q 'REPOSITORY_SUPPORTED_NEXT_CANONICAL_MILESTONE=' "$successor"
grep -q 'SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION' "$successor"
grep -q 'SEMANTIC_HISTORY_MILESTONE_STATUS=' "$successor"
grep -q 'CLASSIFIED_NOT_STARTED' "$successor"
echo "SUCCESSOR_PRIORITY=CONFIRMED"

echo
echo "=== VERIFY EXISTING SEMANTIC HISTORY RECONCILIATION ARTIFACT ==="
legacy="scripts/reconcile-semantic-history-context-optimization-current-state.sh"
test -f "$legacy"

grep -q 'CURRENT_IMPLEMENTED_FOUNDATION=' "$legacy"
grep -q 'CURRENT_SELECTION_MODEL=' "$legacy"
grep -q 'NOT_COMPARATIVE_SEMANTIC_RANKING' "$legacy"
grep -q 'CURRENT_SEMANTIC_RANKING=' "$legacy"
grep -q 'NOT_IMPLEMENTED' "$legacy"
grep -q 'CURRENT_REPOSITORY_CONTROLLED_POST_RETRIEVAL_TOKEN_BUDGET=' "$legacy"
grep -q 'NOT_ESTABLISHED' "$legacy"
grep -q 'CURRENT_HYBRID_CONTEXT_OPTIMIZATION=' "$legacy"
grep -q 'CURRENT_MODEL_RUNTIME_CONTEXT_OPTIMIZATION=' "$legacy"
grep -q 'CURRENT_BOUNDED_HISTORY_WINDOW_OPTIMIZATION=' "$legacy"

echo "EXISTING_RECONCILIATION_SEMANTICS=CONFIRMED"

echo
echo "=== VERIFY ARCHITECTURE FOUNDATION ==="
docs=(
  docs/architecture/SEMANTIC_HISTORY_INVENTORY.md
  docs/architecture/SEMANTIC_HISTORY_SELECTION_OBJECTIVES.md
  docs/architecture/SEMANTIC_HISTORY_BEHAVIORAL_VALIDATION.md
  docs/architecture/SEMANTIC_HISTORY_REPOSITORY_READINESS.md
)

for file in "${docs[@]}"; do
  test -f "$file"
  echo "PRESENT=$file"
done

echo
echo "=== VERIFY CURRENT RUNTIME FOUNDATION ==="
grep -RniE \
  'selectedHistory|evaluatedInterpretations|contaminationEvaluations|listMatildaConversationTurns|conversationContext' \
  server scripts/utils scripts \
  --include='*.ts' \
  2>/dev/null | head -260 || true

echo
echo "=== CURRENT STATE CLASSIFICATION ==="
cat <<'MAP'
MILESTONE=
SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION

MILESTONE_STATUS=
ACTIVE_RECONCILIATION

CURRENT_IMPLEMENTED_FOUNDATION=
PROJECT_AND_CONVERSATION_SCOPED_HISTORY_RETRIEVAL
BOUNDED_CHRONOLOGICAL_RETRIEVAL
AUTHORITY_EVALUATION
CONTAMINATION_EVALUATION
ADMISSION_BASED_SELECTION
SELECTED_HISTORY
CHRONOLOGY_PRESERVATION
LINEAGE_AND_METADATA_PRESERVATION
INPUT_IMMUTABILITY
CONVERSATION_CONTEXT_RUNTIME
OLLAMA_SELECTED_HISTORY_CONSUMPTION

CURRENT_SELECTION_MODEL=
ADMISSION_BASED
NOT_COMPARATIVE_SEMANTIC_RANKING

CURRENT_SEMANTIC_RANKING=
NOT_IMPLEMENTED

CURRENT_REPOSITORY_CONTROLLED_POST_RETRIEVAL_TOKEN_BUDGET=
NOT_ESTABLISHED

CURRENT_HYBRID_CONTEXT_OPTIMIZATION=
NOT_ESTABLISHED

CURRENT_MODEL_RUNTIME_CONTEXT_OPTIMIZATION=
NOT_ESTABLISHED

CURRENT_BOUNDED_HISTORY_WINDOW_OPTIMIZATION=
NOT_ESTABLISHED_BEYOND_EXISTING_RETRIEVAL_BOUND

CURRENT_STATE_RECONCILIATION=
COMPLETE

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_GENERATION_POLICY_REOPENED=
NO

PRODUCTION_CHANGE=
NONE

NEXT_ACTION=
CLASSIFY_SEMANTIC_HISTORY_CONTEXT_OPTIMIZATION_SCOPE
MAP
