#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=446db12d' \
  'ISSUE_RESOLVED=NO' \
  'MODE=COLLABORATION_AUTHORIZATION_RECORD' \
  'COMPARISON_CONTRACT=DEFINED' \
  'IMPLEMENTATION_READY=YES' \
  'IMPLEMENTATION_STARTED=NO' \
  'IMPLEMENTATION_AUTHORIZED=NO' \
  'USER_AUTHORIZATION_REQUIRED=YES' \
  'NEXT_ACTION=AWAIT_EXPLICIT_USER_AUTHORIZATION'

printf '\n=== AUTHORIZATION SCOPE IF GRANTED ===\n'
printf '%s\n' \
  'AUTHORIZED_SURFACE=NEW_VALIDATION_ONLY_RUNNER_ONLY' \
  'UNSEEDED_ARM=10_RUNS' \
  'CONTROLLED_ARM=10_RUNS' \
  'CONTROLLED_SEED=424242' \
  'CAUSAL_VARIABLE=validationGenerationSeed_ONLY' \
  'DATABASE_WRITE=NONE' \
  'PRODUCTION_FILE_MUTATION=NONE' \
  'RETRY=NONE' \
  'ROLLBACK_SCOPE=DELETE_NEW_VALIDATION_ONLY_RUNNER'

printf '\n=== EXPLICITLY NOT AUTHORIZED ===\n'
printf '%s\n' \
  'PRODUCTION_SEED=NO' \
  'PRODUCTION_POLICY_CHANGE=NO' \
  'VALIDATOR_CHANGE=NO' \
  'VALIDATOR_WEAKENING=NO' \
  'PROMPT_CHANGE=NO' \
  'MODEL_CHANGE=NO' \
  'RETRY_CHANGE=NO' \
  'TIMEOUT_CHANGE=NO' \
  'PERSISTENCE_CHANGE=NO'

printf '\n=== RESOLUTION STATUS ===\n'
printf '%s\n' \
  'ISSUE_RESOLVED=NO' \
  'REASON=IMPLEMENTATION_GATE_REMAINS_CLOSED'

printf '\n=== WORKTREE ===\n'
git status --short
