#!/usr/bin/env bash
set -euo pipefail

echo "=== RECONCILE CURRENT SUCCESSOR PRIORITY BOUNDARY ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
test -z "$(git status --porcelain)"
git merge-base --is-ancestor d0b67857 HEAD

gaps="scripts/reconcile-current-unresolved-capability-gaps.sh"
legacy="scripts/classify-successor-priority-boundary.sh"

test -f "$gaps"
test -f "$legacy"

echo "=== VERIFY CORRIDOR 3 CLOSURE ==="
grep -q 'CORRIDOR_3_STATUS=' "$gaps"
grep -q 'COMPLETE' "$gaps"
grep -q 'UNRESOLVED_CAPABILITY_GAP_COUNT=' "$gaps"
grep -q 'ZERO_ON_CURRENT_INVENTORIED_SURFACE' "$gaps"
grep -q 'PRIMARY_UNRESOLVED_CAPABILITY_GAP=' "$gaps"
grep -q 'NONE_ESTABLISHED' "$gaps"
grep -q 'NEXT_CORRIDOR=' "$gaps"
grep -q 'SUCCESSOR_PRIORITY_BOUNDARY' "$gaps"
echo "CORRIDOR_3_CLOSURE=CONFIRMED"

echo
echo "=== VERIFY LEGACY PRIORITY CLASSIFICATION ==="
grep -q 'CURRENT_GENUINE_UNRESOLVED_CAPABILITY_GAPS=' "$legacy"
grep -q 'PRIMARY_UNRESOLVED_CAPABILITY_GAP=' "$legacy"
grep -q 'CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION' "$legacy"
grep -q 'SUCCESSOR_PRIORITY=' "$legacy"
grep -q 'NEXT_MILESTONE_CANDIDATE=' "$legacy"
grep -q 'PRIORITY_BOUNDARY_STATUS=' "$legacy"
grep -q 'PHASE_1_STATUS=' "$legacy"
echo "LEGACY_PRIORITY_CLASSIFICATION=CONFIRMED"

echo
echo "=== RECONCILE STALE PRIORITY PREMISE ==="

cat <<'MAP'
PROGRAM=
MATILDA_CONVERSATION_ENGINE

MILESTONE=
CONVERSATION_ENGINE_PROGRAM_RECONCILIATION_AND_NEXT_CAPABILITY_DETERMINATION

PHASE=
CURRENT_CAPABILITY_AND_DEFERRED_WORK_RECONCILIATION

CORRIDOR=
SUCCESSOR_PRIORITY_BOUNDARY

CURRENT_GENUINE_UNRESOLVED_CAPABILITY_GAPS=
ZERO_ON_CURRENT_INVENTORIED_SURFACE

PRIMARY_UNRESOLVED_CAPABILITY_GAP=
NONE_ESTABLISHED

LEGACY_SUCCESSOR_PRIORITY=
CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION

LEGACY_PRIORITY_CURRENTNESS=
STALE

LEGACY_PRIORITY_INVALIDATION_REASON=
CROSS_TURN_INVESTIGATION_LIFECYCLE_TRANSITION_VALIDATION_IS_NOW_IMPLEMENTED_AND_VALIDATED

OTHER_DEFERRED_ITEMS=
NOT_CURRENTLY_ESTABLISHED_AS_CAPABILITY_GAPS

DEFERRED_PRODUCTION_GENERATION_INSTABILITY=
KNOWN_CONDITION_NOT_AUTOMATIC_SUCCESSOR_CAPABILITY

SUCCESSOR_PRIORITY=
NONE_ESTABLISHED_ON_CURRENT_INVENTORIED_SURFACE

NEXT_MILESTONE_CANDIDATE=
NONE_ESTABLISHED

PRIORITY_BASIS=
The prior successor-priority classification depended on exactly one unresolved
capability gap: cross-turn Investigation Lifecycle transition validation.

Current repository evidence invalidates that premise because the capability is
now implemented and validated.

Corridor 3 now establishes zero unresolved capability gaps on the current
inventoried surface.

Other deferred items either have no established requirement, represent known
conditions rather than missing capabilities, or are implemented but not
independently surfaced.

Therefore evidence does not currently support promoting a runtime implementation
milestone from this inventory.

SUCCESSOR_PRIORITY_CLASSIFICATION=
NO_EVIDENCE_SUPPORTED_RUNTIME_SUCCESSOR_ESTABLISHED

IMPLEMENTATION_READINESS=
NOT_APPLICABLE_WITHOUT_ESTABLISHED_SUCCESSOR_CAPABILITY

IMPLEMENTATION_AUTHORIZATION=
NOT_GRANTED

PRIORITY_BOUNDARY_STATUS=
COMPLETE

PHASE_1_STATUS=
COMPLETE

IMPLEMENTATION_AUTHORIZED=
NO

IMPLEMENTATION_STARTED=
NO

PRODUCTION_GENERATION_POLICY_REOPENED=
NO

PRODUCTION_CHANGE=
NONE

NEXT_PHASE=
NOT_YET_ESTABLISHED

NEXT_CORRIDOR=
NOT_YET_ESTABLISHED

NEXT_ACTION=
CLASSIFY_PROGRAM_RECONCILIATION_PHASE_1_DISPOSITION_AND_SUCCESSOR_DECISION_BOUNDARY
MAP
