#!/usr/bin/env bash
set -euo pipefail

echo "PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR"
echo "CORRIDOR_1=CLASSIFICATION_RULE"
echo "CORRIDOR_1_STATUS=DR_PROTECTED_CLOSED"
echo "CORRIDOR_1_COMMIT=79894de9"
echo "NEXT_CORRIDOR=BEHAVIOR_VALIDATION"
