#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="78e93020a"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — GOVERNANCE READ UNIT AUTHORIZATION REQUEST ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"
echo
echo "=== REQUESTED BOUNDED IMPLEMENTATION UNITS ==="
echo "UNIT_1=FAIL_CLOSED_EXACT_DELEGATION_READER"
echo "UNIT_2=FAIL_CLOSED_EXACT_VALIDATION_RESULT_READER"
echo "UNIT_3=FAIL_CLOSED_EXACT_ENVELOPE_GATE_OR_LINEAGE_READER"
echo "UNIT_4=EXACT_PACKAGE_VERSION_DELEGATION_VALIDATION_CORRELATION"
echo "UNIT_5=TARGETED_READ_ONLY_TESTS"
echo
echo "=== REQUIRED OWNER / BOUNDARY ==="
echo "OWNER=EXISTING_GOVERNANCE_PERSISTENCE_DOMAIN"
echo "NEW_DATABASE_OWNER=NO"
echo "NEW_AUTHORITY_CREATION=NO"
echo "NEW_DELEGATION_CREATION=NO"
echo "NEW_VALIDATION_CREATION=NO"
echo "NEW_GATE_CREATION=NO"
echo "ROUTE_SYNTHESIZED_GOVERNANCE_OK=PROHIBITED"
echo "ROUTE_SYNTHESIZED_DELEGATION=PROHIBITED"
echo
echo "=== EXCLUDED FROM THIS AUTHORIZATION ==="
echo "UNMOUNTED_EXECUTION_ROUTE_IMPLEMENTATION=SEPARATELY_AUTHORIZED_AND_PAUSED"
echo "SERVER_INDEX_ROUTE_MOUNT=NOT_AUTHORIZED"
echo "PRODUCTION_REACHABILITY=NOT_AUTHORIZED"
echo "LOCAL_COMMIT_EFFECT_CHANGES=NOT_AUTHORIZED"
echo "REMOTE_PUSH_EFFECT_CHANGES=NOT_AUTHORIZED"
echo "GENERIC_CADE_CHANGES=NOT_AUTHORIZED"
echo "GENERIC_SHELL_AUTHORITY=NOT_AUTHORIZED"
echo "GENERIC_MUTATION_AUTHORITY=NOT_AUTHORIZED"
echo "SCHEDULER_OR_AUTONOMY=NOT_AUTHORIZED"
echo
echo "=== AUTHORIZATION STATE ==="
echo "GOVERNANCE_READ_UNIT_IMPLEMENTATION_AUTHORIZED=NO"
echo "EXPLICIT_USER_CHAT_AUTHORIZATION_REQUIRED=YES"
echo "CORRIDOR_6_STATUS=AWAITING_BOUNDED_GOVERNANCE_READ_UNIT_IMPLEMENTATION_AUTHORIZATION"
echo "PHASE_1_STATUS=ACTIVE"
echo
echo "REQUESTED_USER_AUTHORIZATION_TEXT=I authorize the bounded Corridor 6 governance read-only unit and targeted tests implementation."
echo
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
git status --short
