#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'CHECKPOINT=MATILDA_UI_SMOKE_TEST_503' \
  'CURRENT_CHECKPOINT=90dbaa8d' \
  'ISSUE_RESOLVED=NO' \
  'LIVE_BACKEND_API=PASS' \
  'TURN_PERSISTENCE=PASS' \
  'DASHBOARD_CLIENT_5173=HEALTHY_VIA_LOCALHOST' \
  'DASHBOARD_CLIENT_BINDING=IPV6_LOCALHOST' \
  'PREVIOUS_127_0_0_1_CLIENT_HEALTH_CHECK=FALSE_NEGATIVE' \
  'DELEGATION_WORKSPACE=PAUSED' \
  'NEXT_ACTION=VERIFY_DASHBOARD_PROXY_CHAT_VIA_LOCALHOST_5173'

printf '\n=== WORKTREE ===\n'
git status --short
