#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="7cfd90dee"
STABLE_CHECKPOINT="bf6eecb5b"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — NATIVE RUNTIME ROUTE ATTEMPT CONTAINMENT ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=ROLLBACK_ONLY"
echo "FAILED_ROUTE_ATTEMPT=YES"
echo "FAILURE_CLASS=APPROVAL_GATE_SOURCE_MODULE_RESOLUTION"
echo "MISSING_MODULE=server/execution/matilda-execution-switch-evaluator.js"
echo "ROUTE_LOGIC_EXECUTED=NO"
echo

echo "=== CONTRADICTION RESOLUTION ==="
echo "PRIOR_REASSESSMENT_SOURCE_APPROVAL_GATE_IMPORT_PASS=NOT_REPRODUCED_BY_ROUTE_TEST_RUNTIME"
echo "REPOSITORY_NATIVE_ROUTE_TEST_IMPORT=FAIL"
echo "DIRECT_ROUTE_IMPORT_TRANSITIVELY_REACHES_NONEXISTENT_JS_SPECIFIER=YES"
echo "NEW_ROUTE_IMPLEMENTATION_CANNOT_BE_VERIFIED_ON_CURRENT_RUNTIME_BOUNDARY=YES"
echo "NO_FURTHER_FIX_LAYERING=YES"
echo

echo "=== ROLLBACK ==="
echo "CURRENT_HEAD=$EXPECTED_HEAD"
echo "RETURN_TO=$STABLE_CHECKPOINT"
echo "PRESERVE_UNTRACKED_FILES=YES"
echo

git reset --hard "$STABLE_CHECKPOINT"

[[ "$(git rev-parse HEAD)" == "$STABLE_CHECKPOINT"* ]] || {
  echo "STOP=ROLLBACK_HEAD_MISMATCH"
  exit 1
}

npx tsc --noEmit

echo
echo "=== POST-ROLLBACK STATE ==="
echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
echo "ROUTE_IMPLEMENTATION_PRESENT=NO"
echo "ROUTE_MOUNTED=NO"
echo "PRODUCTION_REACHABILITY_CHANGED=NO"
echo "CORRIDOR_6_STATUS=ACTIVE_BLOCKED_ON_APPROVAL_GATE_RUNTIME_BOUNDARY"
echo "PHASE_1_STATUS=ACTIVE"
echo "NEXT_ACTION=CLASSIFY_APPROVAL_GATE_RUNTIME_BOUNDARY_AS_SEPARATE_PREEXISTING_CAPABILITY_ISSUE_BEFORE_ANY_NEW_ROUTE_IMPLEMENTATION"
git status --short
