#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD="6d6abd888"
LAST_STABLE_PRE_ROUTE_CHECKPOINT="2bb9be31d"

if [[ "$(git rev-parse HEAD)" != "$EXPECTED_HEAD"* ]]; then
  echo "STOP=UNEXPECTED_HEAD"
  echo "CURRENT_HEAD=$(git rev-parse HEAD)"
  exit 1
fi

echo "=== CORRIDOR 6 — THIRD VERIFICATION FAILURE CONTAINMENT ==="
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=ROLLBACK_ONLY"
echo "FAILED_VERIFICATION_ATTEMPTS=3"
echo

echo "=== THIRD FAILURE ==="
echo "FAILURE_CLASS=TEST_HARNESS_PATH_CONSTRUCTION"
echo "ERROR=relative path can't be expressed as a file URI"
echo "ROUTE_LOGIC_EXECUTED=NO"
echo "THREE_FAILED_HYPOTHESIS_RULE=TRIGGERED"
echo

echo "=== REVERT BOUNDARY ==="
echo "CURRENT_HEAD=$EXPECTED_HEAD"
echo "LAST_STABLE_PRE_ROUTE_CHECKPOINT=$LAST_STABLE_PRE_ROUTE_CHECKPOINT"
echo "REVERT_SCOPE=ALL_COMMITS_AFTER_LAST_STABLE_PRE_ROUTE_CHECKPOINT"
echo "PRESERVE_UNTRACKED_FILES=YES"
echo "NO_NEW_FIX_ATTEMPT=YES"
echo

git reset --hard "$LAST_STABLE_PRE_ROUTE_CHECKPOINT"

echo
echo "=== POST-REVERT VERIFICATION ==="
[[ "$(git rev-parse HEAD)" == "$LAST_STABLE_PRE_ROUTE_CHECKPOINT"* ]] || {
  echo "STOP=REVERT_HEAD_MISMATCH"
  exit 1
}

npx tsc --noEmit

echo "HEAD=$(git rev-parse HEAD)"
echo "BRANCH=$(git branch --show-current)"
echo "CORRIDOR_6_STATUS=ACTIVE_REASSESSMENT_REQUIRED"
echo "PHASE_1_STATUS=ACTIVE"
echo "ROUTE_IMPLEMENTATION_PRESENT=NO"
echo "ROUTE_MOUNTED=NO"
echo "PRODUCTION_REACHABILITY_CHANGED=NO"
echo "NEXT_ACTION=REASSESS_ROUTE_VERIFICATION_AND_RUNTIME_MODEL_FROM_STABLE_CHECKPOINT"
git status --short
