#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

printf '%s\n' \
  'MILESTONE=EXECUTIVE_MISSION_CONTROL' \
  'PHASE=EXECUTIVE_MISSION_OVERVIEW' \
  'CORRIDOR_4=EXECUTIVE_OVERVIEW_VALIDATION_AND_CLOSURE' \
  'CORRIDOR_4_STATUS=CLOSED' \
  'VALIDATION_COMMIT=6e0bd068' \
  'CLOSURE_COMMIT=be0ad775' \
  'PHASE_STATUS=READY_FOR_FINAL_DR' \
  'NEXT_ACTION=RUN_FINAL_PHASE_DR'

dr
