#!/usr/bin/env bash
set -euo pipefail

echo "=== STOP CORRIDOR 5 AND PHASE FOR DR ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor 51e9d26e HEAD
test -z "$(git status --porcelain)"

cat <<'MAP'
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION

PHASE=
STARTING_BOUNDARY_AND_RELIABILITY_BASELINE

CORRIDOR_5=
INTERVENTION_BOUNDARY

CORRIDOR_5_STATUS=
CLOSED_PENDING_DR_CHECKPOINT

INTERVENTION_BOUNDARY_CLASSIFICATION=
COMPLETE

PHASE_DIAGNOSIS_DEFINED=
YES

PHASE_FAILURE_BASELINE_DEFINED=
YES

PHASE_FAILURE_OWNERSHIP_DEFINED=
YES

PHASE_CONSTRAINTS_DEFINED=
YES

PHASE_INTERVENTION_BOUNDARY_DEFINED=
YES

PHASE_CLOSURE_READINESS=
ESTABLISHED

PHASE_STATUS=
CLOSED_PENDING_DR_CHECKPOINT

PRODUCTION_REMEDY_SELECTED=
NO

NEW_PRODUCTION_CHANGE=
NONE

IMPLEMENTATION_AUTHORIZED=
NO_NEW_IMPLEMENTATION

DR_REQUIRED=
YES

NEXT_PHASE_ENTRY_AUTHORIZED=
NO

NEXT_ACTION=
RUN_DR_NOW_AND_RETURN_CHECKPOINT
MAP
