#!/usr/bin/env bash
set -euo pipefail

EXPECTED_HEAD="a96fc84be2d594911528746e001e0d9b9c106b7b"
CURRENT_HEAD="$(git rev-parse HEAD)"

echo "=== CORRIDOR 6 HOLD CHECKPOINT CHURN TERMINATED ==="
echo "EXPECTED_HEAD=${EXPECTED_HEAD}"
echo "CURRENT_HEAD=${CURRENT_HEAD}"
test "${CURRENT_HEAD}" = "${EXPECTED_HEAD}"

echo "DEDICATED_ROUTE_MOUNTED=NO"
echo "PRODUCTION_REACHABILITY=NO"
echo "EXPLICIT_USER_CHAT_AUTHORIZATION_PRESENT=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CORRIDOR_6_STATUS=ACTIVE"
echo "PHASE_1_STATUS=ACTIVE"
echo "FURTHER_HOLD_CHECKPOINT_CHURN=STOP"
echo "NEXT_ACTION=AWAIT_EXPLICIT_USER_CHAT_AUTHORIZATION"
echo "PRODUCTION_CHANGE=NONE"
