#!/usr/bin/env bash
set -euo pipefail

echo "=== STOP CORRIDOR 3 FOR DR ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor a28001dc HEAD
test -z "$(git status --porcelain)"

cat <<'MAP'
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION
CORRIDOR_3=
FAILURE_OWNERSHIP
CORRIDOR_3_STATUS=
CLOSED_PENDING_DR_CHECKPOINT
FAILURE_OWNERSHIP_CLASSIFICATION=
COMPLETE
PRIMARY_FAILURE_OWNER_CLASS=
MODEL_GENERATION_LAYER
EXACT_MODEL_GENERATION_SUBCAUSE=
UNRESOLVED
SUBCAUSE_RESOLUTION_REQUIRED_FOR_CLOSURE=
NO
DR_REQUIRED=
YES
NEXT_CORRIDOR_ENTRY_AUTHORIZED=
NO
NEXT_ACTION=
RUN_DR_NOW
MAP
