#!/usr/bin/env bash
set -euo pipefail

echo "=== PHASE 3 / CORRIDOR 2 — STOP AFTER THIRD FAILED VALIDATION ATTEMPT ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor ea6b6a17 HEAD

unexpected="$(
  git status --porcelain |
  grep -vE '^\?\? scripts/stop-phase-3-corridor-2-after-third-failed-validation\.sh$|^ M scripts/stop-phase-3-corridor-2-after-third-failed-validation\.sh$' ||
  true
)"
test -z "$unexpected"

cat <<'MAP'
PHASE_3=REASONING_STATUS_PRODUCTION_BEHAVIOR
CORRIDOR_2=BEHAVIOR_VALIDATION
STATUS=BLOCKED_PENDING_REASSESSMENT

BEHAVIOR_VALIDATION_ATTEMPTS=3
ATTEMPT_1=FAIL_CLOSED_SELECTED_CONTEXT_REJECTION
ATTEMPT_2=FAIL_CLOSED_SELECTED_CONTEXT_REJECTION
ATTEMPT_3=FAIL_CLOSED_SELECTED_CONTEXT_REJECTION
ATTEMPT_3_PROJECT_CONTEXT_CANDIDATES=NONE
TARGET_EXPLANATION_STATUS_OBSERVED=NO

CURRENT_HYPOTHESIS=PROJECT_CONTEXT_FIXTURE_CAUSES_SELECTED_CONTEXT_REJECTION
CURRENT_HYPOTHESIS_STATUS=FALSIFIED_AS_SUFFICIENT_EXPLANATION

NEW_EVIDENCE=MODEL_AUTHORED_SELECTED_CONTEXT_CAN_OCCUR_EVEN_WHEN_NO_PROJECT_CONTEXT_CANDIDATES_ARE_SUPPLIED

CLASSIFICATION_RULE_FAILURE_ESTABLISHED=NO
VALIDATOR_MALFUNCTION_ESTABLISHED=NO
PRODUCTION_REASONING_STATUS_FAILURE_ESTABLISHED=NO

THREE_FAILED_ATTEMPT_RULE=REACHED
FAILED_ATTEMPT_HARNESS=REMOVED
WORKTREE_RESET_TO_LAST_COMMITTED_STATE=YES

PRODUCTION_CHANGE=NONE
NEW_FIX_ATTEMPT_AUTHORIZED=NO
DR_NOW=NO

CURRENT_BOUNDARY=STOP_AND_REASSESS_FAILURE_CLASS_BEFORE_ANY_NEW_VALIDATION_APPROACH
NEXT_ACTION=REASSESS_WHETHER_SELECTED_CONTEXT_OUTPUT_REQUIREMENTS_CREATE_A_CROSS_CUTTING_VALIDATION_BLOCK_UNRELATED_TO_REASONING_STATUS
MAP
