#!/usr/bin/env bash
set -euo pipefail

echo "=== STOP CORRIDOR 4 FOR DR ==="

test "$(git branch --show-current)" = "feature/support-source-references-runtime"
git merge-base --is-ancestor afc23d21 HEAD
test -z "$(git status --porcelain)"

cat <<'MAP'
MILESTONE=
CONVERSATION_ENGINE_RELIABLE_PRODUCTION_COLLABORATION
CORRIDOR_4=
CONSTRAINT_PRESERVATION
CORRIDOR_4_STATUS=
CLOSED_PENDING_DR_CHECKPOINT
CONSTRAINT_PRESERVATION_CLASSIFICATION=
COMPLETE
FAIL_CLOSED_VALIDATION=
PRESERVED
SUPPORT_PROVENANCE_CONTRACT=
PRESERVED
AUTHORITY_BOUNDARIES=
PRESERVED
ARCHITECTURAL_INVARIANTS=
PRESERVED
NEW_PRODUCTION_CHANGE=
NONE
DR_REQUIRED=
YES
NEXT_CORRIDOR_ENTRY_AUTHORIZED=
NO
NEXT_ACTION=
RUN_DR_NOW
MAP
