#!/usr/bin/env bash
set -euo pipefail

EXPECTED_HEAD="67e8d5d56"

echo "=== CORRIDOR 6 EXPLICIT AUTHORIZATION HOLD CURRENT STATE ==="
test "$(git rev-parse --short HEAD)" = "${EXPECTED_HEAD}"

echo "LATEST_VERIFIED_COMMIT=67e8d5d5644da014e26ca5f7957169b36422e882"
echo "DEDICATED_ROUTE_MOUNTED=NO"
echo "PRODUCTION_REACHABILITY=NO"
echo "USER_INTENT_AUTHORITY_REQUIRED=YES"
echo "EXPLICIT_USER_CHAT_AUTHORIZATION_PRESENT=NO"
echo "IMPLEMENTATION_AUTHORIZED=NO"
echo "CORRIDOR_6_STATUS=ACTIVE"
echo "PHASE_1_STATUS=ACTIVE"
