#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

EXPECTED_HEAD_PREFIX="536817a8b"
CURRENT_HEAD="$(git rev-parse HEAD)"

echo "=== SELF-IMPROVEMENT TARGET SEMANTICS VERIFICATION ==="
echo "EXPECTED_HEAD_PREFIX=${EXPECTED_HEAD_PREFIX}"
echo "CURRENT_HEAD=${CURRENT_HEAD}"
echo "MODE=COLLABORATION"
echo "PRODUCTION_CHANGE=NONE"

if [[ "${CURRENT_HEAD}" != "${EXPECTED_HEAD_PREFIX}"* ]]; then
  echo "UNEXPECTED_HEAD=${CURRENT_HEAD}"
  exit 1
fi

SCOPE_FILE="db/governance-execution-scope-persistence.ts"
ROUTE_FILE="server/routes/governance-execution-route.ts"

grep -q 'repo_path: string' "${SCOPE_FILE}"
grep -q 'expected_head: string' "${SCOPE_FILE}"
grep -q 'allowed_paths: string\[\]' "${SCOPE_FILE}"
grep -q 'repo_path: scope.repo_path' "${ROUTE_FILE}"
grep -q 'branch: scope.branch' "${ROUTE_FILE}"
grep -q 'expected_head: scope.expected_head' "${ROUTE_FILE}"

echo "DURABLE_EXECUTION_TARGET_REPO_PATH=VERIFIED"
echo "DURABLE_EXECUTION_TARGET_BRANCH=VERIFIED"
echo "DURABLE_EXECUTION_TARGET_EXPECTED_HEAD=VERIFIED"
echo "DURABLE_MUTATION_SCOPE=VERIFIED"
echo "ROUTE_DERIVES_PROJECT_TARGET_FROM_PERSISTED_SCOPE=VERIFIED"

echo
echo "CONCLUSION=SELF_IMPROVEMENT_IS_TARGET_RELATIVE"
echo "SELF_AWARE_RECURSION_REQUIRED=NO"
echo "OWN_REPO_TARGETED_EQUALS_SELF_MODIFICATION=YES"
echo "OTHER_REPO_TARGETED_USES_SAME_GOVERNED_EXECUTION_MODEL=YES"
echo "PHASE_1_CLOSURE_CHANGED=NO"
echo "PHASE_2_FRAMING_REQUIRES_RECONCILIATION=YES"
echo "PHASE_2_SHOULD_NOT_ASSUME_CONSCIOUS_SELF_MODIFICATION=YES"
echo "PHASE_2_CORRIDORS_SHOULD_BE_DERIVED_FROM_TARGETED_REPO_ORCHESTRATION=YES"
echo "PHASE_2_RENAME_AUTHORIZED=NO"
echo "NEXT_STEP=RECONCILE_PHASE_2_CORRIDORS_AGAINST_TARGET_RELATIVE_EXECUTION_MODEL"
